### ISSUE TITLE
feature request: Seafile mobile client (Aplle/Android) should switch to landscape mode if turning the device 90 degrees

### ISSUE THREAD

**Issue by peters77** [haiwen/seafile#1003]
Hi, 

maybe it's just an open request...but it would be really nice if the seafile client would switch into landscape mode and use the space to fit into if I turn the mobile device 90 degrees. 
Should work for pdf, xls or jpg. 
On IPhone only a fixed portrait mode is available, no auto switch into landscape?

Regards,

Christian

**Comment by shoeper** [comment]
the client has its own repository. See haiwen/seadroid

**Comment by peters77** [comment]
Sorry!
