### ISSUE TITLE
access non-markdown files in public group

### ISSUE THREAD

**Issue by billryan** [haiwen/seafile#1005]
I created a Public Group and enable wiki on my private seafile server such as [Public - Network](https://seafile.yuanbin.me/group/1/wiki/network/), but when I share this link to other users, they cannot view the pdf files without logging in.

Now that a Group is Public, the files in it should be public accessible too.

**Comment by azazel75** [comment]
I have the same problem

**Comment by shoeper** [comment]
Although these might not be the best solution a working solution would be to

1. share a folder by link and link it from the markdown page
2. share individual files by link. By appending ?dl=true they can also get hotlinked.
