### ISSUE TITLE
Resync bug with http sync

### ISSUE THREAD

**Issue by Semmelbroesel24** [haiwen/seafile#1007]
Hi,

Server 4.0.4 and Client 4.0.5

I changed to nginx to sync over http. That works.
But if i say resync an library the client show connect to server. If i stop the download and say sync with the folder again it works.
There must an bug with resync an library and http.

Grettings Mario

**Comment by lins05** [comment]
Normally people configure seafile to run behind nginx/apache, and it's
nginx/apache that listens on port 80.

**Comment by Semmelbroesel24** [comment]
With Client 4.0,6 the same problem. Only stopy sync and sync folder again works.
Resync show only connect to server.
