### ISSUE TITLE
Error when cookies disabled in browser

### ISSUE THREAD

**Issue by macjul** [haiwen/seafile#1009]
I disabled cookies in my browser an got an error, if I tried to open an password-protected Seafile-link, after I typed in the password. Later I understood, that disabled cookies had been the problem. It would be helpful, if the user gets a  message like: "You need to enable cookies in your browser in order to see the access the file."

![schnappschuss_010515_091223_am_010715_083643_am](https://cloud.githubusercontent.com/assets/9968221/5642353/5e7d5780-9648-11e4-8570-d5e79bc75ee1.jpg)

**Comment by lins05** [comment]
To use seafile you have to enable cookies in your browser.
