### ISSUE TITLE
Windows icon overlay for sync status

### ISSUE THREAD

**Issue by matpat996** [haiwen/seafile#1010]
Dear Devs!

Is there any possibility to add an icon overlay to the files and folders to see if the file/folder is already synced or not, or if it is uploading right now?

Best regards!

**Comment by matpat996** [comment]
No idea?

**Comment by freeplant** [comment]
This feature is not added yet.

**Comment by rulistaff** [comment]
+1

Owncloud, sugarSync, oneDrive, dropbox....
They all already have this feature (under windows linux or macos)

**Comment by matpat996** [comment]
Can be closed. Thanks for the implementation guys, it's awesome!
