### ISSUE TITLE
change user email

### ISSUE THREAD

**Issue by jc06700** [haiwen/seafile#1011]
A new feature I find interesting.

Sometimes it's usefull to change user email.
I check and I don't find how to do this (neither from the user interface, nor from the admin interface).
So I have to modify many tables in the 3 databases (ccnet-db, seafile-db, seahub-db)

If you think this idea is interesting ?

Regards
JCA, a new user very impressed and satisfied by this great tool 
(Mostly the v4 release and the possibility to synchronize data using standart ports : 80 or 443)

**Comment by shoeper** [comment]
Nice idea, think this should get included.

**Comment by jc06700** [comment]
Ok i Transfer this issue to seahub
