### ISSUE TITLE
wiki problem with [[...]] in code block

### ISSUE THREAD

**Issue by simsasaile** [haiwen/seafile#1016]
Hi,

I found a litte bug in the wiki-modul.

If you write something in double brackets like [[test]] in a code block the wiki-page 'thinks' you want to link to another wiki-file, which is normally a cool function but not if your code contains double brackets.

The expected behavior is that the wiki changes nothing in code blocks.

How to reproduce:

create a wiki page and paste following code in it:

![bildschirmfoto 2015-01-09 um 22 06 42](https://cloud.githubusercontent.com/assets/7559897/5687343/e209a2de-984b-11e4-8217-1dd5b6222d83.png)

Now save the page, and see the result:

![bildschirmfoto 2015-01-09 um 21 59 37](https://cloud.githubusercontent.com/assets/7559897/5687233/db9819e0-984a-11e4-98f8-2b2106ccd844.png)

So only the last test reproduces the expected result.

**Comment by shoeper** [comment]
It has been fixed (I don't know by which version).
