### ISSUE TITLE
Sync single file or part of repo from server?

### ISSUE THREAD

**Issue by ustcnene** [haiwen/seafile#1018]
Can I use seafile-client sync part of repo  from seafile server? 
I sync some files in desktop to the server ， if I want to use some file in other client，
I must sync all files in that repo? 
Is there a way to sync part of repo from server?

**Comment by shoeper** [comment]
At the moment this is not possible. But you can use the cloud browser (included in the client) or you could create another library if you need to sync some files with one but not another device.

**Comment by shoeper** [comment]
Using the pro edition single folders of a library can get synced.

**Comment by levinus** [comment]
With the "Sub-Libraries" theres also an option for this in the community edit.
