### ISSUE TITLE
Mac client removes folders

### ISSUE THREAD

**Issue by MetalMuxa** [haiwen/seafile#1019]
Hello,

Here is case to reproduce the problem. We have Windows and Mac clients and Linux server (latest versions everywhere).
1. Create any new folder with files in any library at Windows client (our sample /site/docs/1/)
2. Wait for all clients to sync it
3. Remove this folder at Windows client (our sample /site/docs/1/)
4. Mac client got this change and removes parent folder to removed one. As result, it removes lots of files that should not be removed (in our sample, it removes complete /site/docs/ from Seafile).

I suppose the problem is critical because everybody can loose files knowing nothing about it.

**Comment by freeplant** [comment]
What mac client version do you use?

**Comment by GITchristoph** [comment]
Hi MetalMuxa

We had that same problem in client version 4.0.4 and for us it resolved on client version 4.0.5.
We neither can reproduce this issue with 4.0.6.

COuld it be you are still on 4.0.4?

**Comment by freeplant** [comment]
This was a bug in v4.0.4 and v4.0.5 when we adding a support to sync libraries with special French characters. It should be fixed in the latest v4.0.6.

**Comment by MetalMuxa** [comment]
You're right, just found that Mac still uses 4.0.4. Will upgrade it till 4.0.6 now and recheck.
Thanks!

**Comment by MetalMuxa** [comment]
Problem is really solved in 4.0.6. I close the ticket.
