### ISSUE TITLE
support range requests / streaming

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile#1021]
It would be very nice if seafile could support range requests to stream video files. Support by the app to not cache but stream a file when wanted would also be very nice.

**Comment by Alukardd** [comment]
I also want to have this feature. But not for streaming, for the specific software which want to seek a specific range of shared file.

**Comment by lins05** [comment]
byte-range requests support was added in last year. Check
https://seacloud.cc/group/3/wiki/server-changelog and search for "by-range".

**Comment by Alukardd** [comment]
At this moment I use ```seafile-server-4.4.6``` and I got error from my software when trying to get byte-range request to seahub.
```
# curl -I "http://seafile.domain.org/f/10d8774bca/?raw=1"
HTTP/1.1 302 FOUND
Date: Fri, 15 Jan 2016 12:21:49 GMT
Server: gunicorn/0.16.1
Transfer-Encoding: chunked
Vary: Accept-Language,Cookie
Content-Type: text/html; charset=utf-8
Location: http://seafile.domain.org:8082/files/404f1809-df97-47e8-88cf-55d580f1f4b2/SW_DVD5_Windows_Svr_2008w_SP2_English__x64_DC_EE_SE_X15-41371.ISO
Content-Language: en
```

**Comment by lins05** [comment]
302 redirect is correct answer from seahub. Try send the request to the returned "Location" with the range param in your request header.

**Comment by Alukardd** [comment]
continue
```
# curl -I "http://seafile.domain.org:8082/files/b310f952-9ff9-4c2f-8eda-e51e9fce4e67/SW_DVD5_Windows_Svr_2008w_SP2_English__x64_DC_EE_SE_X15-41371.ISO"                                  [15:51]
HTTP/1.1 200 OK
Last-Modified: Fri, 15 Jan 2016 12:51:13 GMT
Cache-Control: max-age=3600
Access-Control-Allow-Origin: *
Content-Type: application/octet-stream
Content-Length: 2755887104
Content-Disposition: inline;filename="SW_DVD5_Windows_Svr_2008w_SP2_English__x64_DC_EE_SE_X15-41371.ISO"
X-Content-Type-Options: nosniff
```

**Comment by lins05** [comment]
Why do you use `curl -I`? Do you mean you don't see the `Accept-Ranges` in response header? According to this [http RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), 

```
  Origin servers that accept byte-range requests MAY send
          Accept-Ranges: bytes
      but are not required to do so. Clients MAY generate byte-range
      requests without having received this header for the resource
      involved.
```

If you add the proper `Range` header in your request, you'll see the server would return the bytes you specify:

```
$ curl http://127.0.0.1:8082/files/68c529ee-79b3-489d-9e4d-ec83b06de576/x.md 
xyz
```

```
$ curl -v -H 'Range: bytes=1-2' http://127.0.0.1:8082/files/68c529ee-79b3-489d-9e4d-ec83b06de576/x.md

> GET /files/68c529ee-79b3-489d-9e4d-ec83b06de576/x.md HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:8082
> Accept: */*
> Range: bytes=1-2
> 
< HTTP/1.1 206 Partial Content
< Last-Modified: Fri, 15 Jan 2016 13:41:41 GMT
< Cache-Control: max-age=3600
< Accept-Ranges: bytes
< Content-Type: application/octet-stream
< Content-Length: 2
< Content-Range: bytes 1-2/3
< Content-Disposition: inline;filename="x.md"
< X-Content-Type-Options: nosniff
< yz
```

**Comment by Alukardd** [comment]
@lins05, I read [sec14.5](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.5) of HTTP RFC, but as you know all MAY of the RFC should be read as MUST (I know about [MAY in RFC2119](https://tools.ietf.org/html/rfc2119#section-5)). In other case we always will be got situation like this. I assure you that many clients will not be use byte-range requests until they receive ```Accept-Ranges: bytes``` header from server.

I think that ```seahub``` should return byte-range header.

**Comment by rootbdfy** [comment]
So why seadrive not use range read ? Reading any section of a large file causes the entire file to be read.

**Comment by freeplant** [comment]
@rootbdfy Please open a new issue.
