### ISSUE TITLE
Conflict files created while working on a single computer

### ISSUE THREAD

**Issue by languitar** [haiwen/seafile#1022]
When working with mindmaps in docear (http://www.docear.org/) on a single computer, I constantly get conflict files, despite not editing in parallel on other computers.

**Comment by killing** [comment]
What can you find in the client's seafile.log? You can open it by right click on the tray icon.

**Comment by languitar** [comment]
Here is the fraction of the log from the time where such a conflict file was created:
https://gist.github.com/languitar/186f4ee553c684f498be
I switched off the auto sync when I noticed that conflicts were created. Strangely, I can't see anything related to that in the log.

**Comment by freeplant** [comment]
Can't see much information from the log. What server and client version do you use and on what platform?

**Comment by languitar** [comment]
Server was updates a few days ago.to 4.0.3 and this happens on linux and mac. This also happened with older versions of the server and client software.

**Comment by freeplant** [comment]
If you still have the problem with the lastest version, you may re-open the issue.

**Comment by languitar** [comment]
My usage pattern has changed, so this didn't happen again since then.

**Comment by chiralhat** [comment]
I have been having this exact problem recently, on a number of different computers running Windows Seafile client 5.1.2. The server is running on Ubuntu, and is version 5.0.5. I have not yet tested to see if this also happens on my Linux boxes. I am attaching the relevant lines from my seafile.log, but there's not much information in there.
[Conflict.txt](https://github.com/haiwen/seafile/files/332026/Conflict.txt)

**Comment by killing** [comment]
@chiralhat From you log, I can confirm that the client did detect the content of the file is changed from another client. There could be two causes:
1. The file content was really changed on another client.
2. The same file was uploaded on the web interface, which produces different hash value despite the contents are the same on desktop. But this only happens for larger files (like photos). In your case it's a python file, so it shouldn't.

**Comment by chiralhat** [comment]
Thanks for your response. Neither of those two are happening; I am the only one working on that particular file, and it was uploaded via the regular desktop client (created inside a synced folder). This happens fairly frequently, with a variety of different file types, and the main thing that appears to connect them is that the files are being updated and saved fairly rapidly (data being written to a file, or multiple short code changes being saved in quick succession). I hope this information helps.

**Comment by killing** [comment]
Perhaps a more complete log file would help me find the sequence. Could you send me your seafile.log?

**Comment by chiralhat** [comment]
Here you go. It gets big pretty quickly so I periodically replace it, but this has a couple days before and after the snippet I sent earlier (which contain more conflicts, as well).
[seafile.txt](https://github.com/haiwen/seafile/files/335048/seafile.txt)

**Comment by chiralhat** [comment]
Has there been any change on this issue? I am still experiencing the conflicts, with the same lack of information in the log. One of the common ways I see it now is when many new data files are being created in quick succession, about one every two seconds; when this is happening, I will get one conflict file for every several hundred files that are created; the non-conflict file will be entirely empty, and all the data (~87 kB) will be in the conflict file.
