### ISSUE TITLE
Security issue regarding shared links

### ISSUE THREAD

**Issue by warrenseine** [haiwen/seafile#1024]
Hi,

I've discovered an issue that can grant unwanted access to a file.

Here's how to reproduce:

1. Upload a file
2. Share this file publicly
3. Open the public link (available, works as expected)
4. Delete this file
5. Open the public link (unavailable, works as expected)
6. Upload another file with the same name
7. Open the public link (available, **unexpected**)
8. Go to "My links"
9. Open the public link (unavailable, expected)

I suspect that public links are purged when I visit "My links", but not when I delete the file.

Regards,
Warren.

**Comment by shoeper** [comment]
According to a recent test I made file links are removed when the file is being removed now.
