### ISSUE TITLE
User should be notified when files don't sync because of file name conflicts / rename files with bad file names

### ISSUE THREAD

**Issue by gebhard73** [haiwen/seafile#1025]
Hi,

when syncing from e.g. Linux to Windows there are several conditions when a file can't be created on the Windows system (e.g. if the filename contains a colon (:)).

As of now a file with 0 Bytes is created with the filename ending just before the first "bad" character. No notification.

Suggestion:
Option 1:
- inform the user about failed sync processes which stem from bad file names
- allow the user in a dialogue to rename each file with a bad file name on the server
- then retry the sync

Option 2:
- add configuration options as follows:
  - per library
  - automatically replace "bad" chars in file names on the server discovered during sync (yes/no), default no
  - replace with character "-" (option to enter one single char)
- if set to "yes" for lib AAA and the replacement char is e.g. "-" for lib AAA then the following should happen:
  - windows seafile client connects to server for sync lib AAA
  - server has a new file for the Windows system: "bad:file|name.png" (uploaded e.g. by a Linux client)
  - Windows client tries to sync, Windows won't let it create the file bacause of first ":"
  - rename option is "yes" and char is "-" for lib AAA -> Seafile Windows client renames the file to "bad-file|name.png" on the server (replaces all ":" with "-")
  - client retries sync, Windows won't let it create the file bacause of "|"
  - rename option is "yes" and char is "-" for lib AAA -> Seafile client renames the file to "bad-file-name.png" on the server (replaces all "|" with "-")
  - file is successfully synced
  - Linux client sees the change on the server (file renamed)
  - Linux client renames the file locally, too

Suggestions?

Cheers,
Gebhard

**Comment by freeplant** [comment]
Which version do you use? In the newest version, the files with invalid name for Windows will not be ignored in Linux/Mac.

**Comment by gebhard73** [comment]
Hi, I'm using as of now:
- server: 4.0.3
- Linux client: 4.0.5
- Windows client: 4.0.5 / 4.0.6

Interestingly the issue materialized after I updated everything from version 3.x. with old files. I'll conduct a test with the current setup and post an update. 

Thanks,
Gebhard

**Comment by gebhard73** [comment]
Hi,

uploaded a file with special chars with Linux client 4.0.5 to server 4.0.3.

The file is on the server, the name is cut before the first special character, the file size is 0 bytes.

Any suggestions?

Thanks,
Gebhard

**Comment by gebhard73** [comment]
Hi,

after updating the Windows client to 4.0.6 and doing the same test - ... no change in the behaviour.

First test with old Windows client (3.1.5, see above):
- Linux: create a file "Test:123|xxx.pdf" and let it sync to server (4.0.3)
- Windows client (3.1.5) connects to the server and tries to sync the test file ... but on the local file system a "Test" file is created (0 bytes) and synced back to the server

Test today:
- Linux: create a file "Test:123|yyy.pdf" and let it sync to server (4.0.3)
- Windows client (4.0.6) connects to the server and tries to sync the test file ... but on the local file system the existing "Test" file is updated (only time stamp, stays at 0 bytes) and synced back to the server

End result:

Server:
![server](https://cloud.githubusercontent.com/assets/10534403/5805577/57aa2dc6-a010-11e4-8eaa-e5ca28d7e749.png)


Windows client:
![windows](https://cloud.githubusercontent.com/assets/10534403/5805549/2e5e1b9e-a010-11e4-93e2-4b80cb52af16.png)


Any ideas?

Thanks,
Gebhard

**Comment by freeplant** [comment]
Thanks.

Files with name invalid for Windows will not be synced to the Windows machine. This is a feature not a bug.

In old version, files with name invalid for Windows will not be synced to the server even on Linux/Mac. We changed this behavior recently. In the new version, these files will be synced to the server, but not to the Windows machine.

**Comment by gebhard73** [comment]
Hi,

thanks, this explains the behaviour.

But then we're back to my original issue: I'd strongly suggest to inform via the (Windows) client that some file couldn't be synced to the Windows system and to have a possibility to auto-rename files on the server so that the could be synced (default should be off of course).

So what do you think of my original idea?

Thanks,
Gebhard

**Comment by killing** [comment]
Notification has been added.
