### ISSUE TITLE
server v4 will crash virtual servers

### ISSUE THREAD

**Issue by dakira** [haiwen/seafile#1026]
Since upgrading to v4 I get resource alerts on my virtual servers (openvz based, Plesk Virtuozzo in my case), saying they reached the *dcachesize* limit. In openvz speak that's *"The total size of dentry and inode structures locked in the memory."*

This value just increases endlessly, while the searfile server is running. There weren't any problems with v3.

Another value that goes through the roof is *numothersocks* ("*The number of sockets other than TCP ones. Local (UNIX-domain) sockets are used for communications inside the system. UDP sockets are used, for example, for Domain Name Service (DNS) queries. UDP and other sockets may also be used in some very specialized applications (SNMP agents and others).*")

**Comment by shoeper** [comment]
which version exactly?

**Comment by dakira** [comment]
I moved to v4 with 4.0.2. I'm pretty sure the problem started than. It is still there with 4.0.5.

I have since set higer hard limits. For *numothersocks* that seems to suffice. But *dcachesize* just keeps growing as long as Seafile is running.

Some more information if that helps: The system is in testing with ~10 users. Some have large libraries with a couple of thousand files. Some of the larger libraries date back to v2.

**Comment by shoeper** [comment]
according to http://faq.1blu.de/content/553/915/de/virtuozzo-_-das-dcachesize_parameter-befindet-sich-im-roten-bereich-was-tun.html (German) that's normal and no problem (high dcachesize).

numothersocks seems to be a real problem which afaik can only be solved by limiting number of processes.

In my opinion openvz is just shit. With openvz I directly had problems on KVM I've never had any issues.

**Comment by xifle** [comment]
Same problem here. seafile 4.0.5 uses a massive (> 200) amount of non-tcp sockets.
Why is it using soo many sockets? To me, this seems to be a bug or result of inefficient programming...
This is really annoying as it can no longer run on virtual machines where you have no influence on the numothersock setting...

**Comment by shoeper** [comment]
On my system are 221 unix sockets from seafile. Not sure it thats much - at least it's no problem. Unfortunately I've no comparison to 3.x

**Comment by dakira** [comment]
@shoeper since I increased the hardlimit for numothersocks I had no more system failures. The fact remains that both values were well within their soft limits while using v3.

**Comment by xifle** [comment]
@shoeper I downgraded to 3.1.7, which uses 84 non-tcp sockets on my machine...

**Comment by shoeper** [comment]
I'd think the increasement is caused by additional sockets needed for http sync, but I'm not sure

**Comment by freeplant** [comment]
This because we use Unix Socket for RPC communication between server components in version 4. Currently we don't release the cached opened socked until restart. So the opened sockets may grow to one hundred.

**Comment by xifle** [comment]
Thank you freeplant. The number of sockets does not increase slowly. It's at 220 right after starting the seafile server. Not sure what you mean with "cached" sockets and why you use so many. A socket-pair per process-process combination should by sufficient with a msg based IPC system. But as long as you guys know what the problem is.. :)

**Comment by dakira** [comment]
@freeplant will this be addressed or should we file this under *raised hardware requirements*?

**Comment by freeplant** [comment]
This will not be addressed recently.
