### ISSUE TITLE
seafile.conf missing

### ISSUE THREAD

**Issue by Gugi264** [haiwen/seafile#1031]
Hi, i was searching for the last whole day about the seafile.conf file stored in seafile-data.
Neither the folder nor the file is findeable.
Also found nothing online.
Will it be created later? 
Tried restarting, and manually adding it, it didn't work.

**Comment by lins05** [comment]
If you delete it by mistake, you can uncompress seafile server package to a
temporary place (like /tmp/), run the setup script again with the same
configuration, and then copy the seafile.conf file to your original
installation.

**Comment by Gugi264** [comment]
Hi!

Thanks for the tip!
But i am pretty sure i haven't deleted it. Strange.
But i will definitely try this out, thanks!
Shuai Lin <notifications@github.com> schrieb am Sun Jan 18 2015 at 3:35:29
AM:

**Comment by XakRu** [comment]
hi, @Gugi264 i had the same problem, i didn't found seafile.conf
Because i have different directories for seafile service and  for seafile data.
You can found location for this file in ~/haiwen/ccnet/seafile.ini
File located in seafile-data directory
