### ISSUE TITLE
last update is 1970-01-01 for every file

### ISSUE THREAD

**Issue by ant9000** [haiwen/seafile#1032]
Upgrading from 4.0.1 to 4.0.4 shows wrong last modified time for all files; version 4.0.5 also exhibits the same behaviour. Reverting to 4.0.1 cures the problem.

Specifically: seafile_api.list_dir_by_commit_and_path(repo.id,commit.id,'/') returns 0 as mtime for each entry, while seafile_api.get_files_last_modified(repo.id,'/',-1) has the correct values.

Seafile is running on a Debian Wheezy virtual server; filesystem is Ceph.

**Comment by freeplant** [comment]
See https://github.com/haiwen/seahub/issues/333

**Comment by ant9000** [comment]
Thank you for pointing me to the other discussion - I did miss it. I've just recreated my libraries, and now everything's working as before.
