### ISSUE TITLE
feature request: live markdown editor and other wiki improvements

### ISSUE THREAD

**Issue by simsasaile** [haiwen/seafile#1033]
I know the wiki is not on top of the priority list, but this open source project could improve the wiki a lot: https://github.com/benweet/stackedit/

A live demo is available here: https://stackedit.io/editor

In any case it would be really helpful if you could support commands like:

- Table of contents: [TOC]
- Mathematical expressions: MathJax

**Comment by funkyfuture** [comment]
i agree. but propably this belongs to the [seahib issues](https://github.com/haiwen/seahub/issues).

**Comment by shoeper** [comment]
+1

**Comment by CharlesNepote** [comment]
Hallojs provide a solution where markdown syntax is hiden: http://hallojs.org/demo/markdown/

With Hallojs you can write in Wysiwyg and get markdown code as a result. I think it's far better for beginners (and even for many advanced users).

See http://hallojs.org/

**Comment by funkyfuture** [comment]
i disagree that a wysiwig-editor that hides the source is useful for beginners.
the side-by-side-view is didacticly very useful.

**Comment by spotman** [comment]
:+1: for stackedit

**Comment by shoeper** [comment]
In v5 there is a side to side markdown editor.
