### ISSUE TITLE
Less space used on disk then shown on web interface for a library

### ISSUE THREAD

**Issue by acavas1** [haiwen/seafile#1036]
Could you please explain how is that I have less disk space usage on HDD then it is show on the web interface(seahub). I assume that there that the disk space should always have the greater value since the trash is not calculated when shown in the quota usage.

Thanks 
Best Regards

**Comment by shoeper** [comment]
Afaik seafile saves your data in blocks. If 2 files are partly the same the block is just saved once. That's also the reason for the fast sync (as long as your're not having very much data on a slow HDD - then the initial sync on bootup needs very much time). So if you change a 100MB textfile and just add a line just this small change is transfered and not the whole file.
