### ISSUE TITLE
Windows client removes empty folders

### ISSUE THREAD

**Issue by oliverm-be** [haiwen/seafile#1040]
I created following directory structure in seafile: /Seafile/Test/Blah

I removed the directory Test
Very shortly after removing this directory, a windows client also removes the parent directory Seafile for no reason.

The windows client is version 3.1.12, the server version is 3.0.4.

![selection_010](https://cloud.githubusercontent.com/assets/4815604/5856903/66172a56-a247-11e4-9351-14e818b6fd66.png)

**Comment by killing** [comment]
Try use version 4.x latest client.
