### ISSUE TITLE
Please make seafile installable via pip

### ISSUE THREAD

**Issue by guettli** [haiwen/seafile#1041]
Please make seafile installable via pip.

I don't want magic: Getting the source via pip is just the first step. Setting up the DBs and creating the configuration still needs to be done afterwards. But installing via pip would make the step easier. Even for people how don't know python.

**Comment by lins05** [comment]
Pip is more suitable for python libraries like Django. Seafile is much different from that, and it only uses python for the web ui. Take a look at  [seafile components overview](http://manual.seafile.com/overview/components.html).

Besides, to compile the source, there is [a long list of dependencies](http://manual.seafile.com/build_seafile/server.html) to install, which may not be wanted by most users.

**Comment by guettli** [comment]
OK, I though the other components are written in python, too. Nevertheless pip can run gcc at install time to compile the needed stuff.

You can close the issue as "won't fix", if there are no plans to do it.

**Comment by epe** [comment]
I think the way forward is to have binary packages available in the most common Linux Distros, This is the best way to have seafile integrated in the OS, since everybody is familiar with it. 
In Debian e.g. there is Source Packages, that might make sense if you want to compile it.

**Comment by shoeper** [comment]
debian packages would be really nice. It would make updating even easier and more comfortable.
