### ISSUE TITLE
Does ccnet/mykey.peer need to be backed up?

### ISSUE THREAD

**Issue by padhia** [haiwen/seafile#1044]
The manual lists only two steps for backup, namely, backing up mysql databases and data files folder. However, almost as a footnote, the manual says 
>The ID in `ccnet/ccnet.conf` must be consistent with `ccnet/mykey.peer` so do not forget to copy `ccnet/mykey.peer`.

I am a little confused; the manual never says to copy `ccnet/ccnet.conf`, so what's the point of copying just `ccnet/mykey.peer`? 

On related topic,
* If I just backup databases and data files, do I need anything else to recreate my setup on an entirely new setup?
* If the database and files are on a slightly different backup schedule, will there be any issues for restoring (beyond data will be as good as the oldest of the database or the file backup)?
* What the ID in `ccnet/ccnet.conf` is used for?

**Comment by shoeper** [comment]
I'm also interested in this.

**Comment by killing** [comment]
The documentation says that you should copy the whole installation directory. So the ccnet.conf and mykey.peer files should already be copied. The note is actually a reminder. It's a little bit confusing.
If the database and data is not consistent, seaf-fsck will realign them to the latest consistent state. It's actually a FAQ. Even though in the "restore" section we mention that seaf-fsck should be run after restore, it's still good to make this clear.
ccnet.conf contains the ID from mykey.peer file. This ID is used for non-http syncing protocol.

**Comment by JantarMantar** [comment]
Thank you for your answer. However, installation directory is mostly executables. It doesn't make sense to have exact same set of executables as a requirement for restore. If I, on a new machine, install latest version and generate a different set of ID and mykey.peer files, will the restored databases and data file folders not work?
