### ISSUE TITLE
Camera Upload feature offers no deduping

### ISSUE THREAD

**Issue by Wilm0r** [haiwen/seafile#1046]
I've recently had to recreate my Seafile account on my Android phone for some functionality to work again. (Share on Seafile was broken, when I tried to share stuff it'd just tell me to "Add an account first".)

Now I just noticed that camera syncing stopped, which makes sense since it's an account setting and I've just recreated it. I re-enabled it, hoping that it would catch up uploading just the few pictures I made over the last two weeks.

Unfortunately what happens instead is that every picture gets re-uploaded and my library now just contains lots of cuplicates. "IMG_20131230_135320 (1).jpg" next to "IMG_20131230_135320.jpg", etc. This is going to take a while and makes the library not very useful. Only thing I can do now is delete it including history and have the phone reupload everything, which on my ADSL connection is going to take days. :-(

**Comment by theRealBaccata** [comment]
I got the same problem here right now. Can't upload camera pictures due to "add an account first" issue while running setup wizard.

**Comment by shoeper** [comment]
Please reopen at https://github.com/haiwen/seadroid if you still see an issue here.
