### ISSUE TITLE
Seafile download (browser) only 1 connection and no resume ?

### ISSUE THREAD

**Issue by shubhank008** [haiwen/seafile#1047]
Hey guys,

I had transferred from server from EC2 to a self-hosted dedicated yesterday, its running centOS with LEMP and am using nginx-fastcgi for seahub

I paid attention today while downloading a file from my seahub share link, the download is using only 1 connection and no resume support. I am pretty sure (even though I didnt paid that much attention earlier) that it shouldn't be so.

I am using the nginx.conf file for my vhost from the manual, not custom or additional changes.

http://i.imgur.com/tOTKXb9.png

![image](https://cloud.githubusercontent.com/assets/3790163/5895584/3b463c1c-a54a-11e4-8188-10b2f2e54b37.png)

**Comment by DevCybran** [comment]
Having deployed the seafile server behind apache, I am running into the same problem - downloads cannot be resumed. This is especially disadvantageous when transmitting large files over a slow uplink.

**Comment by shoeper** [comment]
Earlier there was (and maybe still is) the issue that range requests weren't support. Afaik multi connection downloads require range requests and resume also requires range requests.

Another thing is that on download a ticket (or something similiar) is created being valid for 1 hour. So even with range requests resuming would only be possible as long as the ticket is valid.

**Comment by shubhank008** [comment]
I am using it behind nginx, well just one connection isn't a problem since I can still reach max download speed, but no resume sure is frustrating, specially for large files

Other thing to cope up with this would be integrating a option to directly start syncing/downloading a file via desktop client, as pretty sure it can resume downloads/sync ?
So something like, user can click "Download via Client" which will be a link to desktop client and clicking it will launch the client and start syncing/downloading the file

**Comment by shoeper** [comment]
Is it such a hassle to open the cloudbrowser and get the file?
Don't think so.
But resume capability would indeed be a nice feature.

**Comment by shubhank008** [comment]
Its not for the file owner, my issue for and probably @DevCybran was for public share/download
Ofcourse for the owner of file, he can just sync it using client

**Comment by shoeper** [comment]
Ok but nobody is willing to install an aplication just to download a file. So range requests and maybe extended ticket life times are the way to go.

**Comment by freeplant** [comment]
Range request will be supported after finishing other features.

**Comment by shoeper** [comment]
Ok, thanks.

**Comment by shoeper** [comment]
Range requests have been implemented in the meantime.

**Comment by strarsis** [comment]
@shoeper: So now the download can be resumed? When using Free Download Manager app, it doesn't seem to be able to resume the download...
