### ISSUE TITLE
Better docs in Chapter "Firewall"

### ISSUE THREAD

**Issue by guettli** [haiwen/seafile#1049]
http://manual.seafile.com/deploy/using_firewall.html

the current docs for "behind https" looks like this:

```
If you run Seafile behind Nginx/Apache with HTTPS, you should open ports

 | HTTPS
    | 443
    |-
    | Ccnet Daemon
    | 10001
    |-
    | Seafile Daemon
    | 12001
```

That's not enough information. Please explain the ports 10001 and 12001 in more depth. Or provide a link to a page with more infos.

**Comment by shoeper** [comment]
443 tcp. If you want to use http sync you don't need another port.
If you want to use default sync you also should open port 10001 and 12001.
If you don't want to use SSL/TLS you could also open port 8082 (?) and wouldn't have to proxy it with nginx or whatever.

**Comment by guettli** [comment]
Thank you for your fast reply.  Please improve the docs.

**Comment by shoeper** [comment]
I don't know all the details as well.
Interesting would also be if port 10001 and 12001 are only tcp or also udp.

**Comment by freeplant** [comment]
10001 and 12001 are only TCP
