### ISSUE TITLE
Docs: Deploy with Apache

### ISSUE THREAD

**Issue by guettli** [haiwen/seafile#1050]
http://manual.seafile.com/deploy/deploy_with_apache.html#detailed-explanation

```
When a user visit https://domain.com/home/my/, Apache receives this request and sends it to Seahub via fastcgi. This is controlled by the following config items: ....

RewriteRule ^/(seahub.*)$ /seahub.fcgi/$1 [QSA,L,E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

AFAIK the URL https://domain.com/home/my/ does not get send to fastcgi since the Rewrite Rule Regex looks for ^/(seahub.*)$.

This URL https://domain.com/seahub/home/my would be redirected to fastcgi ...

**Comment by rcoss** [comment]
I believe the correct rewrite rules for seahub are:
#
# seahub
#
RewriteRule ^/(media.*)$ /$1 [QSA,L,PT]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ /seahub.fcgi$1 [QSA,L,E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
