### ISSUE TITLE
Docs use domain.com, please use example.com

### ISSUE THREAD

**Issue by guettli** [haiwen/seafile#1051]
Docs use domain.com, please use example.com

**Comment by lins05** [comment]
Thanks for the suggestion, but I think most of the users/admins can under that both are only serving as a  place holder, don't they?

**Comment by shoeper** [comment]
example.com is a reserved domain name (see http://example.com/) while domain.com is normal domain bought by someone.

**Comment by lins05** [comment]
That makes sense. Fixed in haiwen/seafile-docs@ae00417
