### ISSUE TITLE
ccnet package under python2.6 directory?

### ISSUE THREAD

**Issue by guettli** [haiwen/seafile#1052]
I installed seafile 4.0.5 on a debian with Python2.7 only.

I checked the PYTHONPATH where the code lives.

Very crazy: the ccnet module is only available in a directory with this name:

```
./seafile-server-4.0.5/seafile/lib64/python2.6/site-packages/ccnet
```

I modified `seahub.sh` to exclude the python2.6 parts of the PYTHONPATH, and this shows: The python2.6 directory is needed, otherwise the `ccnet` package can'be loaded (ImportError).

Please clean this. This is confusing.

**Comment by lins05** [comment]
That's because we build the seafile server package on a centos 5.8 machine
to make sure it's compatible with most of linux distros, and centos 5.8 has
only python 2.6 installed.

Don't worry about this. Although it has a name "python2.6" in its path, It
runs well with  both python 2.6 and 2.7.
