### ISSUE TITLE
web interface login problems

### ISSUE THREAD

**Issue by dacog** [haiwen/seafile#1053]
Hi, 

I installed version 2.1, then upgraded to version 4.0.2 and everything worked ok. Now I upgraded to version 4.0.4 and I can't login to seafile through the web anymore. I run the upgrade scripts as indicated.
Desktop and mobile clients work ok, but the login in the website keeps telling me there is wrong email/password.

I'm using mysql for database and running seafile as described in the manual.
I already read and tried the following:
https://github.com/haiwen/seafile-client/issues/416
https://github.com/haiwen/seadroid/issues/2
https://groups.google.com/forum/#!msg/seafile/lufKQJl-dNM/eLrm3evGqM4J  (I haven't tried to delete de EmailUsers tables as I have read reset-admin.sh only workd with sqlite.
https://github.com/haiwen/seahub/issues/13

Any ideas would be greatly appreciated :)

**Comment by lins05** [comment]
You can use reset-admin.sh. It works with both mysql and sqlite.

**Comment by dacog** [comment]
@lins05 thank you for your quick answer. I tried using reset-admin.sh but the problem persist. Any other ideas? I looked the logs and I can't see nothing that may tell me a hint of the error.

**Comment by lins05** [comment]
Have you looked at logs/ccnet.log and logs/seahub.log,
logs/seahub_django_requests.log?

**Comment by BThunderW** [comment]
I have the same problem. Can no longer log into the web interface. Tried reset-admin.sh, created a new admin account using this method, still can not log in. Tried using the reset password link that's sent via email, I can reset the password but still can not log in. I'm completely locked out of seafile right now.

**Comment by shoeper** [comment]
I'd check if database connection works. Try to login manually with data from seafile config.

**Comment by lins05** [comment]
@dacog @BThunderW As I mentioned above, you can check the seahub logs to see what happened.
