### ISSUE TITLE
Files not appearing after successful sync

### ISSUE THREAD

**Issue by geist1** [haiwen/seafile#1056]
Hi

I noticed that with an (unencrypted) folder that is shared with me, the files did not show up after being succesfully synced. i was asked to look at some files, but couldn't find them and assumed they haven't been put in the folder. but then i checked in the browser and a bunch of files are showing up there, but not in the folder on my iMac. I have a macbook pro that is syncing the same folder but had seafile client (4.0.6) closed for a couple of days and opened it to let it sync. It immediately started pulling the files, so i opened the folder and checked and a few of the files (the first of the bunch) not showing on my iMac showed up, but the rest was still missing. It definitely continued downloading and finished all files. i opened at "Downloading - 15%"

i suspect, that the problem of files not showing up only happens, when the folder is open on the computer. that would explain why only a few were visible, because i opened the folder while it was downloading. no new files appeared after opening the folder, altough new files were still being downloaded. the iMac  had the window of the folder open the whole time and the seafile client is open all the time, too. so that would explain why no new files were showing.

i will restart the computer now and see if they show up.

**Comment by geist1** [comment]
After the restart the files showed up

**Comment by geist1** [comment]
Well, today the folder was not open, but the files did sync but are not showing up in the folder.

**Comment by freeplant** [comment]
What's your OS X version? Some version of Finder can't show files updated by other programs correctly.

**Comment by geist1** [comment]
It's 10.10.2 .. I recently updated it from 10.10.1

Sent from my GameBoy
