### ISSUE TITLE
Feature : modification number of threads

### ISSUE THREAD

**Issue by lavoisier16** [haiwen/seafile#1057]
For http syncing, seafile uses a fixed number of threads. Is it possible to change this value  ? for example through  a configuration option ?

**Comment by lins05** [comment]
We may add it later. Related: https://groups.google.com/forum/#!msg/seafile/YVULk2CAsxM/_TAD_3Q0goEJ.

**Comment by shoeper** [comment]
It would be really nice if the server admin could define the number of threads it's client should use.

**Comment by freeplant** [comment]
We don't have a plan to support such feature.
