### ISSUE TITLE
Seahub: Do not publicly show the server version

### ISSUE THREAD

**Issue by thewilli** [haiwen/seafile#1060]
Do not show the server version at the footer by default - at least not to anonymous users. This behavior simplifies attacks, if a server is not updated immediately. 

I would suggest to present this information to admins only.

**Comment by shoeper** [comment]
If one knows a vulnerability for seafile he would just attack every server.
So not showing it doesn't provide any security enhancement.

**Comment by thewilli** [comment]
@shoeper If there is a vulnerability, one could easily scan for targets by just scanning for the version string. If it wouldn't be shown, you would have to scan for the vulnerability first, which complicates automatic attacks IMHO

**Comment by shoeper** [comment]
Why should one scan for the version string? He wouldn't be able to hack company installations with modified front end and all other installations with a modified frontend (these are the ones one wants to hack in general).
So it is way easier to just attack EVERY seafile server.

**Comment by shubhank008** [comment]
In seafile-server-latest directory (or your install directory), edit this file
```seahub/seahub/templates/footer.html```

Simply remove this line
 ```<p>{% trans "Server Version: " %}{{ seafile_version }}</p>```
