### ISSUE TITLE
Feature Request: Upload and replace files

### ISSUE THREAD

**Issue by RunasSudo** [haiwen/seafile#1061]
Currently, when uploading a file through the web interface, with the same name as an existing file, the new file will be given the name `file (1).ext`. It would be great to instead have an option for Seafile to overwrite the old file.

**Comment by freeplant** [comment]
You can use the update function: 

![qq20150202-1 2x](https://cloud.githubusercontent.com/assets/109339/6000254/dddbee8c-ab16-11e4-9f2f-71ca9dc06fec.png)

**Comment by RunasSudo** [comment]
Thanks! But it still seems logical to have an upload-and-overwrite function, particularly when uploading large numbers of files.

**Comment by freeplant** [comment]
It is already implemented.
