### ISSUE TITLE
Cloud file browser - date sorting problem

### ISSUE THREAD

**Issue by teklabania** [haiwen/seafile#1063]
General description:
Date sorting in *cloud file browser* doesn't work well. Sorting is done by date-name but the date is displayed in mixed-way relatively and absolutely which leads to sorting in wrong order. 

Current behaviour:
Sorting is done by date-name. When relative and absolute dates are mixed the sorting is messed up. E.g.:
1 day ago
2 days ago
2010-11-10
3 days ago
4 minutes ago

Expected behaviour:
Sorting should be done by date, no matter in what format it is displayed. E.g.:
4 minutes ago
1 day ago
2 days ago
3 days ago
2010-11-10

Seafile client version:
4.0.7, Arch Linux (but occured also in earlier versions e.g. 4.0.1)

Example:
![cloud_file_browser_sorting_issue](https://cloud.githubusercontent.com/assets/8668038/6030062/15dcf3c4-abf5-11e4-8485-af13b8cdddf2.png)

**Comment by lins05** [comment]
Thanks for reporting, we'll fix this.

**Comment by Chilledheart** [comment]
@lins05 this should be fixed at https://github.com/haiwen/seafile-client/pull/447

**Comment by lins05** [comment]
Fixed in https://github.com/haiwen/seafile-client/pull/447. We would include it in the next release.
