### ISSUE TITLE
Change LDAP group name cause the used space 0 bytes under admin page.

### ISSUE THREAD

**Issue by FireROR** [haiwen/seafile#1065]
We have a AD group name A in the past and recently we changed group name to B.

The used space shows 0 bytes under admin page. Is there way to re-enforce the space calculation?

Thanks

This is under user login.. This shows the correct used space.
![wang](https://cloud.githubusercontent.com/assets/8516814/6067738/b1f5056c-ad44-11e4-8c13-4aef96692102.jpg)

This is under admin user manage page.
![0byte](https://cloud.githubusercontent.com/assets/8516814/6067767/dedd0fac-ad44-11e4-8ac9-fbb73bf4a7e6.jpg)

User belongs to AD group A but the group name has been changed to B.

**Comment by freeplant** [comment]
What version do you use? Can you check server version 4.0.6?

**Comment by FireROR** [comment]
Yes. Version 4.0.6

**Comment by FireROR** [comment]
yes. 4.0.6 does fix the issue.

Thanks
