### ISSUE TITLE
ProgressBar doesn't display on Internet Explorer

### ISSUE THREAD

**Issue by darkcircle** [haiwen/seafile#1066]
my client reports that he couldn't see progress-bar during uploading some heavy file(he was trying to upload user-created-movie).

He is using Windows 8.x and Internet Explorer 10~11 as his main client platform.

**Comment by shoeper** [comment]
Just gave it a test using ie (11.0.9600.17498 - update version 11.0.15) on windows 8.1 and it works as it should.

![Test progressbar with ie on windows 8.1](https://mno.pw/0786)

**Comment by darkcircle** [comment]
@shoeper  I've check this issue both 10 and 11. yes. you're right. that is no problem on 11, but some problem is being on IE 10. Sorry to late for checking your msg. and Thank you :+1:
