### ISSUE TITLE
Password field in (at least) Seafile Client 4.1.0/Win not properly escaped

### ISSUE THREAD

**Issue by lsrx** [haiwen/seafile#1072]
After upgrading server & client to 4.x I couldn't access my libraries with Seafile Client any longer: "Failed to login: Incorrect email or password" – although no problems signing into Seahub with exactly the same credentials. As it turns out, the plus sign (+) in my password caused the headache, it's not properly escaped but treated as whitespace like application/x-www-form-urlencoded.

Steps to reproduce:
1) Add/change account in Seahub with at least one + sign in password
2) Try to login with same credentials using Seahub Client => fails
3) Manually escape the + in your pass in Seahub Client with %2b, e. g.
transform abc+123 into abc%2b123 => succeeds

```
curl -v -k -d "username=user@example.com&password=abc+123" https://***.***.**/api2/auth-token/

=> {"non_field_errors": ["Unable to login with provided credentials."]}

curl -v -k -d "username=user@example.com&password=abc%2b123" https://***.***.**/api2/auth-token/

=> {"token": "8ba5abe3bed778b197424622e04256be91e2d9cc"}
```

Maybe the username is also affected.

**Comment by lins05** [comment]
Thanks for reporting! We're working on it. You can check it here
https://github.com/haiwen/seafile-client/pull/439 .

**Comment by lins05** [comment]
Fixed in https://github.com/haiwen/seafile-client/commit/64d609b0677f7b2d0d07d50b80f7465eadf58be3
