### ISSUE TITLE
Feature Request: Generate Direct/Raw Share Link To File

### ISSUE THREAD

**Issue by NGenesis** [haiwen/seafile#1073]
Please consider the ability to generate and display a URL that is a direct link to a file.  Discussion about this feature being implemented was initially brought up at https://groups.google.com/forum/#!topic/seafile/m5gBAAcTFio, but does not provide a clear proposal on what is to be implemented, so I will attempt to provide that in this feature request.

A typical share link to a file that is currently generated is in the form of https://cloud.example.com/f/{uid}/ (referred to as a "share link") should also generate an equivalent URL of https://cloud.example.com/download/f/{uid}.{fileext} (referred to as a "download link") which points directly at the file that has been shared, bypassing the preview/download page that is served up by the first form of the share link.

For example, a file shared with the name "avatar.png" will generate two links:
* A share link: https://cloud.example.com/f/91a89089b21/
 * displays the preview and download page for avatar.png.
* A download link: https://cloud.example.com/download/f/91a89089b21.png
 * displays avatar.png directly.

In addition to generating a download link (which should be done automatically when generating a share link), the web interface, Windows context menu and Cloud File Browser should be updated to allow the ability to view a download link.

The Windows context menu and Cloud File Browser provide the same interface when viewing a share link, so an option to copy either a share link or download link can be provided in the same interface.
![Share/Download Link Dialog](http://puu.sh/fLqdV/09651be1ef.png)

The download/preview page of a share link should also display the equivalent download link URL somewhere on the page.
![Preview/Download Webpage](http://puu.sh/fLs8X/8cbf374cb5.png)

**Comment by freeplant** [comment]
Thanks for the detailed specification! We will try to add it after releasing v4.1.

**Comment by shubhank008** [comment]
PS: Just to add/request, if you add this feature, please make it config based so that users who want it or doesnt want it can enable/disable it via the seafile/seahub config file

**Comment by freeplant** [comment]
Displaying both the sharing link and directly download link in the Windows dialog will cause confusing to many users.

**Comment by NGenesis** [comment]
What ever you think will work best, I will leave to your capable judgement.  There are numerous ways the link can be displayed, just so long as there is a way to retrieve the link easily once it has been generated through the respective interfaces.

Looking forward to seeing this feature in a future release.

**Comment by geist1** [comment]
This is a great idea. Would it be possible to also make the link obscure the file name?

**Comment by JoeyGH** [comment]
You should also add a "View File" to your Web API, similar to the "Download File" (see link below).

http://manual.seafile.com/develop/web_api.html#download-file

The URL you get from this works fine, but it downloads the file directly (ie. I can't view an image in a browser, because the browser downloads it instead).

I tried generating a view file url with Python API, where I changed the OP parameter to "view" instead of "download" and then it worked fine, but I would really like to have that option in Web API.

**Comment by GRMrGecko** [comment]
I'm looking forward to this. Right now I just have seafile-fuse configured with a link in my public server to share a whole folder publically.

My personal opionion is that the way a file is shared should be up to the user, maybe when you right click have it say "Copy link" and "Copy direct link"

**Comment by cybertk** [comment]
What is the status of this feature request?

**Comment by shoeper** [comment]
It has been implemented.

**Comment by cybertk** [comment]
Where I can find the direct link, the current shared download link is expired every day

**Comment by lins05** [comment]
plain share link: https://seafile.example.org/f/1234567
direct link: https://seafile.example.org/f/1234567?dl=1
