### ISSUE TITLE
Status "Connecting server..." forever

### ISSUE THREAD

**Issue by gibalmeida** [haiwen/seafile#1074]
After I've upgraded my Seafile server to 4.0.6 from 4.0.5, my windows client (version 4.0.7) stay with "connecting server..." at each library to sync.

**Comment by gibalmeida** [comment]
If I go to "Advanced settings" and mark "Enable file syncing with HTTP protocol" does it work!

**Comment by shoeper** [comment]
have you opened ports for non http/s sync (10001 and 12001 - both tcp)?

**Comment by gibalmeida** [comment]
Yes, these ports are opened. No firewall rules.
As I said before, when the server was version 4.0.5 the clients were connecting normally.

**Comment by shoeper** [comment]
I'm also just a user (and for everything just works). But anything in the logs? 

And how did you upgrade your server? By just extracting the new version, stopping the server, running at least minor-upgrade.sh and starting the server? Or did you also change something else?

**Comment by lins05** [comment]
@gibalmeida Is there any logs in your client? Right click the tray icon and choos "open logs folder".

**Comment by gibalmeida** [comment]
Shoeper, I did exactly you said: extracting the new version; stopping the server; running minor-upgrade.sh script; and, starting again the server.
I've been doing this since version 4.0.1 and had not had problems up to version 4.0.6

**Comment by gibalmeida** [comment]
Hey guys, sorry about I have opened this issue, the problem was in my client antivirus firewall. It was blocking the ports 10001 and 12001.
Thanks a lot.
