### ISSUE TITLE
Incorrect escaping of download URLs in list view

### ISSUE THREAD

**Issue by kvothe** [haiwen/seafile#1076]
When sharing a folder with files that have a # in their name (which is permitted on most file systems) the generated download link in the list view (the button on the right of each element) is not escaped correctly and the download understandably fails.

For example, a file named '#test.pdf' would lead to a link looking like this:
https://seafile.asdf.com/repo/xxx/yyy/?file_name=#test.pdf&op=download&t=zzz

In case of a pdf, when clicking on the pdf and opening the in-browser viewer the green download button on the top right is working correctly as the url is encoded correctly.

**Comment by shoeper** [comment]
This has been fixed in the meantime.
