### ISSUE TITLE
avatar loop

### ISSUE THREAD

**Issue by oozaru-hunter** [haiwen/seafile#1077]
Today I encountered after installing seafile the problem that I could not upload avatars. 
The problem was:
```
$:/opt/seahub-data# ls -lh
insgesamt 0
lrwxrwxrwx 1 root root 28 Feb 11 21:56 avatars -> ../../../seahub-data/avatars
```
Which I could solve by creating the avatars folder manually in /opt/seahub-data/
Now I can upload avatars without problem

I installed, deleted and reinstalled several times today, maybe something went wrong there...

**Comment by lins05** [comment]
Hmm..I don't see how this could happen. Can you tell me the version of seafile server and the details of your linux distro?

The related code is [here](https://github.com/haiwen/seafile/tree/950cda71519a0c6936f42d935b3b92c71ba5f210/scripts/setup-seafile.sh#L564) (for sqlite3) and [here](https://github.com/haiwen/seafile/tree/950cda71519a0c6936f42d935b3b92c71ba5f210/scripts/setup-seafile-mysql.py#L1072) (for mysql)

**Comment by oozaru-hunter** [comment]
seafile-server-4.0.6 and I use Debian Wheezy

**Comment by shamowfski** [comment]
My avatars are completely broken as well.  I have a more complex setup with a seperate reverse proxy server but even working directly on the seafile server, If i try to upload an avatar, the image link breaks and debugging shows 404's.

**Comment by lins05** [comment]
If you ever changed the domain or subdomain of your seafile server, try remove the folder /tmp/seahub_cache and restart seahub. Or if you're using seafile with memcached, just restart your memcached server.

Reference post on seafile forum: 
 [[solved] Avatars Display Broken Image Link, Can’t Upload New Avatars English](https://forum.seafile-server.org/t/solved-avatars-display-broken-image-link-cant-upload-new-avatars/599)

**Comment by oozaru-hunter** [comment]
After deleting /tmp/seahub_cache the new avatar is correctly displayed.
However, after uploading a new avater I have to delete /tmp/seahub_cache again to see it.
