### ISSUE TITLE
seaf-cli 4.0.4 failed status

### ISSUE THREAD

**Issue by kingfisher77** [haiwen/seafile#1078]
Hello,

in my new setup seaf-cli status does not work anymore:
seaf-cli 4.0.4 64bit
Seafile Server 4.0.6. Linux 64bit
Http-Sync

This error appears:

$ seaf-cli status
Name  Status  Progress
Traceback (most recent call last):
  File "/usr/local/src/seafile-cli-4.0.4/bin/seaf-cli.py", line 791, in <module>
    main()
  File "/usr/local/src/seafile-cli-4.0.4/bin/seaf-cli.py", line 787, in main
    args.func(args)
  File "/usr/local/src/seafile-cli-4.0.4/bin/seaf-cli.py", line 609, in seaf_status
    tx_task.block_done, tx_task.block_total,
AttributeError: 'NoneType' object has no attribute 'block_done'

Any ideas? Thank you!

**Comment by lins05** [comment]
Thanks for reporting, I'll look into this soon.

**Comment by lins05** [comment]
I reproduced this error. When downloading a library with http sync enabled, [`seafile_find_transfer_task`](https://github.com/haiwen/seafile/tree/950cda71519a0c6936f42d935b3b92c71ba5f210/app/seaf-cli#L607) would return `NULL`. But when http sync disabled this problem won't happen.

@killing Can you take a look at it?

**Comment by kingfisher77** [comment]
Just for the records, there are two other issues with seaf-cli which could be solved for a next version:

https://github.com/haiwen/seafile/issues/1078
https://github.com/haiwen/seafile/issues/1085

Thank you!

**Comment by kingfisher77** [comment]
Hello! Are there any news about the development of seaf-cli? Thank you! :)

**Comment by bill-mcgonigle** [comment]
there's a workaround here:

https://groups.google.com/forum/#!topic/seafile/pY4Y_xcNtis

I wish I knew https syncing support wasn't done before taking the upgrade ... :/
