### ISSUE TITLE
Seafile-Pro video playback not working (Swift-EC2)

### ISSUE THREAD

**Issue by shubhank008** [haiwen/seafile#1081]
Just wanted to report this possible bug, video playback is not working in seafile-pro when using Swift(EC2) backend.
All general upload/download/sync operations seems to be working

Uploaded 300MB MP4 file
Changed preview size setting in seahub.py to 300MB
Using Seafile-Pro 4.0.3
Using Swift Juno
Not using apache/nginx as its a test setup to do stress testing
No errors in any of the error logs

Another thing I noticed was, its not that there is a error or such, but using chrome's network inspection tool, I noticed that the page/shared link is downloading/loading the whole video file from the backend (aka using download link its downloading it in browser)

You can test it using this link on my stress testing environment
http://54.93.114.129:8000/f/b963adb14b/

---Update---
I just added nginx backend, above link won't work
Here is the updated link
http://54.93.114.129/f/b963adb14b/

**Comment by shubhank008** [comment]
I just added and enabled nginx server and now the video player is trying to load/access this URL which doesn't exist
```
http://54.93.114.129/f/b963adb14b/54.93.114.129/files/0e832d97-9d2a-4e67-9ebc-b6bb6308eefe/%5BAnimeOut%5DSword%20of%20the%20Stranger%20%28miniHD%20Hi10P%20720p%20500mb%29%5BRareAMV%5D%28Yoroshiku-THORA%29-OUT.mp4
```

**Comment by lins05** [comment]
Seafile server does not support [byte range requests](http://en.wikipedia.org/wiki/Byte_serving), which is required for streaming a video. This means the browser has to download the whole video file before starting to play it.

We have this feature on [our road map](https://seacloud.cc/group/3/wiki/seafile-roadmap/#50-2015430).

**Comment by shubhank008** [comment]
hmm.. so 3-4~ months approx.. well not that big of a problem, will wait for it
By the way, is there any separate repo or forum or place to make feature requests or report bugs, etc. related to Seafile-Pro or this same GIT is to be used ?

**Comment by lins05** [comment]
I'd suggest you post it in the seafile professional group, so that the
other pro edition users can also view & discuss it there.

**Comment by shubhank008** [comment]
Okay thanks, I will close this for the time being
