### ISSUE TITLE
Cannot compile with latest components.

### ISSUE THREAD

**Issue by maxolasersquad** [haiwen/seafile#1082]
I am running Ubuntu 14.04 and following the instructions at http://manual.seafile.com/build_seafile/server.html

I download the following:
  * ccnet-4.0.6-server
  * libsearpc-3.0.3-server
  * seafile-4.0.6-server
  * seahub-4.0.6-server

I was able to succussefully make and install ccnet and libsearpc, but when I try to compile seahub I get the following.
```
/usr/local/lib/libevhtp.a(evhtp.c.o): In function `_evhtp_accept_cb':
evhtp.c:(.text+0x52a7): undefined reference to `bufferevent_openssl_socket_new'
/usr/local/lib/libevhtp.a(evhtp.c.o): In function `_evhtp_run_in_thread':
evhtp.c:(.text+0x547f): undefined reference to `bufferevent_openssl_socket_new'
collect2: error: ld returned 1 exit status
make[3]: *** [seaf-server] Error 1
make[3]: Leaving directory `/data/haiwen/seafile-server/src/seafile-4.0.6-server/server'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/data/haiwen/seafile-server/src/seafile-4.0.6-server/server'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/haiwen/seafile-server/src/seafile-4.0.6-server'
make: *** [all] Error 2
```

**Comment by lins05** [comment]
This is a recent change. When building libevhtp, you need to run `cmake -DEVHTP_DISABLE_SSL=OFF -DEVHTP_BUILD_SHARED=ON .` instead of `cmake .` I'll update the document.

**Comment by maxolasersquad** [comment]
That did it. Thanks for the update.

**Comment by ns130291** [comment]
I have the same problem with 4.1.2, but I'm using the build script `build-server.py`. What do I have to change there to compile it successfully?

**Comment by lvedie** [comment]
Hi,
One year after, I have the same problem :
```
evhtp.c:(.text+0x4ef0): undefined reference to `bufferevent_openssl_socket_new'
collect2: error: ld returned 1 exit status
Makefile:611: recipe for target 'seaf-server' failed
```
I used the version 1.1.6 of libevhtp, and seafile-server-6.6.1. And I did compile libevhtp with the `-DEVHTP_DISABLE_SSL=OFF -DEVHTP_BUILD_SHARED=ON` flags.

Any idea ?

**Comment by schmittlauch** [comment]
@lvedie There is a bug in recent libevhtp versions that the configure flag has been changed from `-DEVHTP_BUILD_SHARED=ON` to `-DBUILD_SHARED_LIBS=ON`.

See criticalstack/libevhtp#145

**Comment by schmittlauch** [comment]
> This is a recent change. When building libevhtp, you need to run `cmake -DEVHTP_DISABLE_SSL=OFF -DEVHTP_BUILD_SHARED=ON .` instead of `cmake .` I'll update the document.

Btw, the [current build instructions](https://download.seafile.com/published/seafile-manual/build_seafile/server.md) say exactly the opposite:

> `cmake -DEVHTP_DISABLE_SSL=ON -DEVHTP_BUILD_SHARED=OFF .`

I am quite certain that we need shared libraries to link against and probably also want to have openssl support enabled, so please update the build instructions if they're wrong.
