### ISSUE TITLE
seafile 4.0 deleting contents of shared rw folders

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1083]
We have Mac and Linux clients experiencing contents of shared folders getting deleted by Seafile.  Client's are version 4.0 and the server is 4.0.6 running on ubuntu 14.04.  Let me know what you need to assist in debugging.

**Comment by killing** [comment]
This may be an old bug. What version of Mac client do you use? The problem should affect versions before 4.0.6.

**Comment by caniwi** [comment]
I believe they are all running 4.0.6 but will check again.

**Comment by caniwi** [comment]
we found 1 of 6 Max OSX machines was running 4.0.4.  Will monitor further.  Would this introduce the behaviour of the bug?

**Comment by killing** [comment]
Yes it can be the cause.

**Comment by caniwi** [comment]
I see a feature request coming on..... allow a server admin to see/query what version of client a user is using.

**Comment by caniwi** [comment]
This is resolved by making sure all clients are 4.0.6.
