### ISSUE TITLE
deactivate my library

### ISSUE THREAD

**Issue by Semmelbroesel24** [haiwen/seafile#1086]
Ho can i deactivate that every new user get his own library?

**Comment by shoeper** [comment]
Afaik that's not possible - but also no problem, what to you want to achieve with it?

**Comment by Semmelbroesel24** [comment]
It is very impossible, because. If you create users outside your orginisation to replicate data with your company you always get this stupid library. I never use this library so it would be nice if i can say don't create it. At the Moment I log in and delete it.

**Comment by shoeper** [comment]
Then you could use this: http://manual.seafile.com/develop/web_api.html
You could write a powerfull manger using the api (Or also just a small script to create new users).
