### ISSUE TITLE
Restore Data with Trash is very useless

### ISSUE THREAD

**Issue by Semmelbroesel24** [haiwen/seafile#1087]
Hi,

if an library is very big or have many users they use it. You have no chance restore Data with the Trash if your Data that you need is some weeks ago. If i open the trash i see only all Files and folders, this can be hundred of entries. The trash should changed, if i move to an folder the trash should only show files where delete in this folder. Next folder only this files and so one. Additional there should the ability to search for files. This will help so much to restore the right Data fast.

Greetings Mario

**Comment by killing** [comment]
Thanks for your suggestions. I agree showing deleted files and folders for a folder is useful. We'll add this in the future release.
