### ISSUE TITLE
Guestusers without the ability to create library

### ISSUE THREAD

**Issue by Semmelbroesel24** [haiwen/seafile#1088]
Hi,

their should the ability to create users that can not create libraries. This users should be guestuers.
Then seafile can use as a Datarom for customers that only whant to give Data.

Greetings Mario

**Comment by freeplant** [comment]
This feature is already in the pro edition. As described in the page http://seafile.com/en/product/private_server/ (Role based Account Management)

**Comment by shoeper** [comment]
What you can actually do is create a folder, click share & select upload with password protection. Then your customer is able to upload data to that folder.
I've just tested it and it works fine. But if you use seafile for commercial you could also support the devs by getting a pro licence. It starts at 140€/year for 5 users.

**Comment by Semmelbroesel24** [comment]
Hi,
this not an option. If you create a user he can log in and create his own library. But this is not we want.
We want he only can log in and can only open shared library.
Pro is not an option, because we need hundreds if user this is not affordable.

**Comment by shoeper** [comment]
Another idea that comes to my mind is that you'll set customers quota to 0. Or 1 MB or something like that.

Regarding "Pro is not an option, because we need hundreds if user this is not affordable.".
I'd try to contact the Seafile team. Maybe you can buy pro licence for you and your employees and those for your customers are included or at a very low price.

**Comment by Semmelbroesel24** [comment]
Hi,

this quota i will try. It is not perfekt but it should help. My problem is i would like to use seafile as a Dataroom. I must share a lot of files and i need over 150 guestusers if I look on the price list we are talking about 3750€ in one year. Sorry i not crazy.

**Comment by shoeper** [comment]
As I've said I would try contacting the team - but that's your decision. (Maybe you can get a licence for your guests for a much lower price. E.g. 2.5€)

**Comment by shoeper** [comment]
Just for clarification: I'm  not a member of the team and I'm not connected/related with the team or it's members in any way.
