### ISSUE TITLE
Trash bin to large -> Can't view trash bin through web panel

### ISSUE THREAD

**Issue by 4ley** [haiwen/seafile#1097]
I've deleted several GB's of files with a "Duplicate Files Deleter" Tool. Now I want to restore some files, but I can't open the trash bin, since the web panel loads infinitely. That's basically a bug.
As long it isn't fixed, I would appreciate a hint on how to restore the whole trash bin (e.g. through CLI). Restoring via snapshot is not an option, since new data was already uploaded after the deletion.
Any help is really appreciated!

**Comment by shoeper** [comment]
Increase your timeouts (from your Webserver). And it should work.

**Comment by 4ley** [comment]
I've set `fastcgi_read_timeout 36000;` `proxy_connect_timeout 36000;` and `proxy_read_timeout    36000;` still it loads and loads..
Basically the problem is with that immense count of small files that are inside the tash bin.

**Comment by shoeper** [comment]
look at your browsers dev tools after how much time the request times out.
I'm pretty sure that also with millions of files seahub should response after some time. It could be that you forgot a timeout. Proxy timeouts are afaik not relevant for Seahub.

**Comment by 4ley** [comment]
I've set all settings to high figures. Now the site was loading like 1 hour. Now it gives me "502 Bad Gateway". Somehow this is not really sufficient.

**Comment by shoeper** [comment]
Ok I agree. About how many files are we talking?

**Comment by 4ley** [comment]
Around 50k to 100k small files. I'm not sure how many have been deleted.
Paging and "search by filename" would be very nice features in this case, so I could restore only the files I miss. There was somewhere a feature request for this. I'm currently searching to link it.

**Comment by freeplant** [comment]
What server version do you use? we should have improved the trash bin loading performance in v4.0.6.

**Comment by 4ley** [comment]
Client 4.0.7 and Server 4.0.6. All up to date.

**Comment by 4ley** [comment]
@freeplant The problem is with the huge amount of small files. The produced HTML output would be serveral MBs in size. A paging and "search by filename" would be very helpfull now.

**Comment by killing** [comment]
You can try to restore the files via snapshot. I don't mean to reset back
to a snapshot. You can restore selected folders or files within a snapshot
now.

2015-02-26 0:54 GMT+08:00 4ley <notifications@github.com>:

**Comment by 4ley** [comment]
@killing okay this seems to be possible. There is simply a usability problem. When I want to restore a file, I have to always get 1 month back to open the snapshot and than search for the file in the snapshot manually since there is no search-by-filename option.
Is it possible to restore simply the whole trash bin?

**Comment by killing** [comment]
In the future we'll allow to view delete files for specific folder. That is, when you open trash in a folder, it only displays the deleted files under that folder. Could this help?

**Comment by shoeper** [comment]
Where is the performance drawback in the trash bin, can't that be tackled?
Is it also the contributor calculation?

You could e.g. implement an sql cache/fs cache for the trash bin and keep that up to date via service (ok, it's not the best way but it could improve overall seahub experience.

**Comment by 4ley** [comment]
@killing This could really help indeed. Features that would also help alot are: Search by filename in trash bin, restore whole trash bin or download trash as archive. Just to mention.

Do you have an broad time estimation when the new "trash bin per folder" feature will be out?

**Comment by novaflash** [comment]
Commenting because I have the same problem and even with insane timeouts, I'm still staring at a loading screen. The browser is still trying to load after about half an hour, and the page is still empty. Using nginx with the settings as recommended to increase the timeouts.

This server was originally set up with version 4.3.1, and now running 4.3.2. The problem still exists there as well. It would be most appreciated if the trash bin can be fixed to work with larger amounts of files.

**Comment by shoeper** [comment]
Trash performance has been improved in the last version.
