### ISSUE TITLE
Feature Request: make admin_in.png and admin_out.png themable

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1101]
There is very good branding capability within Seafile but the admin buttons don't appear to take theming and remain in the default Seafile colours.   These remaining in original colours irritates the designers.  Each upgrade of seafile overwrites the files as they are included in seahub/media/img/.

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/feature-request-make-admin-in-png-and-admin-out-png-themable/4350
