### ISSUE TITLE
MP3 Playback from WebUI fails on iOS (iPhone, iPad)

### ISSUE THREAD

**Issue by samboman** [haiwen/seafile#1102]
Preview (online listening in embedded player) of MP3-files works great on the desktop PC. But on iOS device the player displays, but at the right part of the player NaN:NaN shows instead of the track-time.

![image](https://cloud.githubusercontent.com/assets/1038277/6373592/079cec24-bd0c-11e4-98cd-f66d55d16b37.png)

Maybe a bug?
Workaround?

Seems to be related to the player / metadata:
https://wordpress.org/support/topic/mp3-files-not-working-on-iphone-and-ipad2
github.com/johndyer/mediaelement/issues/470
help.videojs.com/discussions/problems/1109-duration-infinitynannan

I'm using Nginx straight from Seafile Manual (HTTPS and HTTP tested).
Any thoughts?

//Sam

I have previously posted in the forum, but this is maybe the right place for the bug-report...
https://forum.seafile-server.org/t/mp3-playback-from-webui-fails-on-ios-iphone-ipad/624

**Comment by samboman** [comment]
Also, I tested in Safari on Windows 8, I got just a black player.:
![image](https://cloud.githubusercontent.com/assets/1038277/6426517/8f40c984-bf5f-11e4-9d00-9baf33309641.png)

**Comment by samboman** [comment]
Upgrade to latest: MediaElement.js ?

**Comment by freeplant** [comment]
Can you check the latest MediaElement.js can work by visiting their website?

**Comment by samboman** [comment]
I did a try to just replace the MediaElement.min.js - file. It didn't work. But I have not the basic knowledge in the Web UI structure...
I wonder if it is something in my setup or if it affects everybody.
MP3 Playback are a key feature for my users...

**Comment by samboman** [comment]
Shuld this be moved to: haiwen/seahub instead? The Web UI?...

**Comment by samboman** [comment]
Bump!
Can anyone with Seafile + iOS reproduce this, I would appreciate!

**Comment by iBigQ** [comment]
Can confirm with Seafile 4.0.5 and iOS 6. Audio plays but tracktime is NaN:NaN

**Comment by samboman** [comment]
@iBigQ Do you use Seafile with Nginx?

**Comment by samboman** [comment]
I can confirm it exists in 4.1.2 too. And if I try in Chrome I can start playback, but I dont get any position. Trying to click to progress-to fast forward to a position cause playing from beginning.
Also the blue cashing-indicator are not fully loaded.

![image](https://cloud.githubusercontent.com/assets/1038277/6996917/24a5b4d8-dba5-11e4-9427-0579e458efc5.png)

Only first minutes are available.

**Comment by iBigQ** [comment]
@samboman Yes, it is configured using FastCGI with Nginx

**Comment by freeplant** [comment]
This is because we don't support range-request in Seafile. range-request will be added soon.

**Comment by freeplant** [comment]
v4.2

**Comment by suminus** [comment]
ios video-playback issue

hi, i'm using version 4.2.1 with nginx on centos and mariadb.

videoplayback on iOS-devices runs only if you manually import the self-signed-https-certificate.
accepting/trusting it when loading the web-gui is not enough.

any suggestions? 

thx in advance.

**Comment by samboman** [comment]
@freeplant, I can confirm it is working in my installation. I just upgraded to Seafile 4.2.1 today, and I have tested in Chrome, iPhone and iPad. @suminus I have my selfsigned cert imported in my devices, but I will try to check it out.
I'm on Ubuntu, Nginx and MySql.

**Comment by samboman** [comment]
@freeplant MP3 audio works fine, but an MP4 video of 65MB (1 minute) does not play very well. When I look at the requests in chrome I got very many (its ok), but the transferred data size are 10 times as big as the video itself...

**Comment by suminus** [comment]
@samboman 
can you confirm that mp4-video plays fine without manually importing the certificate?

thx

**Comment by samboman** [comment]
@suminus
I can confirm after trying on an iPad that it is not playing mp3-files without importing the selfsigned certificate in the device.
After an import everything is fine!

**Comment by suminus** [comment]
what i found out is that iOS in gerneral does not trust self-signed certificates via the browser.
on my self-hosted server i'll try a StartSSL certificate - if there's time - next week.

**Comment by samboman** [comment]
I grabbed an SSL domain validation certificate from Comodo (via cheapsslsecurity.com) for $4.99 / year. It solved those problems while I wait for LetsEncrypt.org to settle, even if I dislike the certificaticate trust, Mafia-style: "pay and you are trusted...". :)

**Comment by suminus** [comment]
hey, thx for the info. i'll take a look at it. 
read already about LetsEncrypt.org. will be a better solution ...

**Comment by shoeper** [comment]
@samboman StartSSL is also free and trusted.

**Comment by suminus** [comment]
confirmed. StartSSL works fine for me - with iOS.
