### ISSUE TITLE
 Error when reading from block

### ISSUE THREAD

**Issue by shubhank008** [haiwen/seafile#1104]
Using Seafile-Pro with Openstack Swift backend storage

I am trying to upload a 1GB file, uploads within a few minutes from my server but remains stucked at 100% saving file for over 10 minutes.
My seafile server, openstack swift proxy and storage servers are all in same datacenter and 1Gbps network.

Seafile.log is full of 

```
[02/25/15 12:46:29] access-file.c(259): Error when reading from block 9a1ea3e4470bc63560282322d55f45e726ac5ebf.
[02/25/15 12:46:39] access-file.c(259): Error when reading from block 1cafed2c40dd89a22d7f8b64586bbec1d0dadf51.
[02/25/15 12:47:43] access-file.c(259): Error when reading from block 90c3fa07315baa3def6b45d137c3207233285a56.
[02/25/15 12:47:46] access-file.c(259): Error when reading from block 325565040dae3960def90e902436fb994016ca1c.
[02/25/15 12:47:49] access-file.c(259): Error when reading from block 325565040dae3960def90e902436fb994016ca1c.
[02/25/15 12:48:18] access-file.c(259): Error when reading from block 0d875d2b6049e5f0acdeb42efad95aca64b915ba.
[02/25/15 12:50:18] access-file.c(259): Error when reading from block 5d6a3e084d1b92e2f4a9fc09048c024a3d337c9a.
[02/25/15 12:52:03] access-file.c(259): Error when reading from block 9e5d0a28159c308e8426cdd7a6bd718fca935369.
[02/25/15 12:53:21] access-file.c(259): Error when reading from block 674dcf128d7830dd96e7e6a9381905cbe71b1461.
[02/25/15 12:53:37] access-file.c(259): Error when reading from block 8ebaa9f979e25f217ee2105eb9e754d60b046b92.
[02/25/15 12:53:47] access-file.c(259): Error when reading from block 1d86a7e7279623dc7321ce6135302153c2109854.
```

I am using nginx backend

**Comment by shoeper** [comment]
Upload via seahub or client?

**Comment by shubhank008** [comment]
Just tried both client and seahub, error remains and file upload/sync keeps stuck at 100%

**Comment by killing** [comment]
The error should be related to your server's local file system. The blocks are staged to the local file system before read/write to Swift. Is it full?

**Comment by shubhank008** [comment]
Nope, though the seafile instance is on a 50GB SSD node, it was definitely not full or even 20% space used. I have some doubt it might be related to inode or ulimit though. The manual suggests 30000, what kind of criteria is that number based on ?  

I have increased my inodes and ulimit currently, lets see if it occurs again.  

PS: When using Swift, is the indexing still done by seafile instance ? I was wondering why large files takes long to save after completing upload (saving file/upload status in browser and desktop client stays stuck at 0% for a few mins before and after actual uploading)

**Comment by killing** [comment]
Yes, when uploading from the browser, seafile server needs to index the
file. That makes "saving" a long procedure. I suggest you limit the size of
files uploaded from web.

2015-02-26 11:36 GMT+08:00 shubhank008 <notifications@github.com>:

**Comment by shubhank008** [comment]
Limiting it under 1GB won't let it be competitive and might prove not that best for us as we are developing the service to integrate as a API based backup as well (wordpress plugin planned)  
I see desktop client still didn't had this much delay, indexing is done by PC itself then ?  

Also, what are the suggested options for large files for browser then ? Would using a cluster and a independant background node (or a cluster of background nodes perhaps) make any difference ?

PS: Just to know, why is the transfer speed in desktop client comparatively low compared to browser ?

**Comment by shoeper** [comment]
> I see desktop client still didn't had this much delay, indexing is done by PC itself then ?

Yes, that's why I was asking how you'd upload the file. To keep server load low blocks are calculated by the client.

> PS: Just to know, why is the transfer speed in desktop client comparatively low compared to browser ?

is it? Here I get speeds beyond 60MiB/s. Are you sure it's due to bandwith? I could imagine a slow processor and/or hdd, so the upload is limited by indexing speed and not by bandwidth speed.

**Comment by shubhank008** [comment]
Well, considering that I am using windows servers for both browser and desktop upload, it shouldn't be the case as in both uploads, same server and network is used.

Also, as mentioned, seafile and upload servers are in same datacenter as well. And its not only in pro-license, even in normal license, upload speed is almost 1.5-2x times slower in desktop client compared to browser upload


PS: Seems the seafile server (seahub) crashes again today, not sure if both issues are related or not, will create a separate ticket for that

**Comment by shubhank008** [comment]
PS: The main listed error from reading from block is still appearing

**Comment by shoeper** [comment]
Which speed do you get with the client?
If you have fast desktop device upload should be faster than uploading via seahub. Furthermore you have to keep in mind, when the client finished the file/s is/are ready for everyone. When the browser uploads the file needs to get indexed afterwards, so when you have a big file the progress is far away from being finished.

**Comment by shubhank008** [comment]
Well as I mentioned again and again, its not about the "time" it takes to upload but the "upload speed" itself, for example, browser gives like 20MBps while desktop client gives 7MBps.  
Same network, same servers, same hardware  

@killing any guess or comments on the ` access-file.c(259): Error when reading from block 387d4488705b6cc78056396e246e86f4d2428016` error ? They still keep appearing in seafile.log

**Comment by shoeper** [comment]
> Well as I mentioned again and again, its not about the "time" it takes to upload but the "upload speed" > itself, for example, browser gives like 20MBps while desktop client gives 7MBps.

Well I did understand you but you did not understand me. The issue is not bandwith or upload speed. The thing needing time is the indexing. Because your client is not able to index more than 7MBps it cannot upload faster. This is no seafile issue I get 70MiB/s (sometimes even more). So your clients hardware is slow or you do not get more bandwith from amazon (for whatever reason).
