### ISSUE TITLE
Feature Request: Option to serve files from the filesystem

### ISSUE THREAD

**Issue by allo-** [haiwen/seafile#1107]
If you want to have a folder synced and served via read-only FTP/HTTP as well, the server stores the files in blocks and syncs from the blocks via a local client to the folder served by the ftp-server, storing all files twice. Possibly even three times during sync: server storage, client storage, syncfolder.

It would be a nice feature, if the server could optionally store the files (maybe on per library basis) without splitting into blocks and split them on the fly / keep a database with the offsets of the blocks in the files, so the raw filestore could be used to access the files without a sync-client.

**Comment by lins05** [comment]
You can use seafile's fuse extension to mount the library, and serve it via
ftp.

http://manual.seafile.com/extension/fuse.html

**Comment by allo-** [comment]
Hmm, i know it (though i did not try it yet), but fuse is slow and read-only. It would be cool if a ftp-upload would both fill seafile and a normal folder served via http.

**Comment by shoeper** [comment]
You could write a cron saving new files via WebApi to Seafile: http://manual.seafile.com/develop/web_api.html#create-file

**Comment by allo-** [comment]
Hmm, i will have a look. I close here, as i guess there is currently not interest in a solution without physical splitting.

I still think it would be nice to have something like this, because on the client the amount of disk space is doubled anyway, one time the file itself and then the blockstore ...
