### ISSUE TITLE
How to contribute corrections to seafile manual.

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1110]
The init.d script in the manual is slightly inconsistent and from my reading slightly incorrect.   The stop function should issue a stop for seahub first and then seafile.   It also uses $1 as an action to the calls for a stop whereas for a start or restart is is hard coded as a such.   

The second point is a bit niggly but the first one should be corrected.

**Comment by caniwi** [comment]
Also it would be good to have the update-rc.d stanza in the script.... may I suggest the following....

### BEGIN INIT INFO
# Provides:		seafile-server
# Required-Start:	$remote_fs $postgresql
# Required-Stop:	$remote_fs $postgresql
# Default-Start:	2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:	Seafile server
### END INIT INFO

**Comment by freeplant** [comment]
You can modify https://github.com/haiwen/seafile-docs, and send a pull request

**Comment by caniwi** [comment]
This was done.  Thanks
