### ISSUE TITLE
seafile win client 4.0.6 and 4.0.7.1 don't sync locked files after unlocking and don't show information on errors

### ISSUE THREAD

**Issue by zacharyTris** [haiwen/seafile#1111]
the win clients have problems with locked files.
Reproducible by locking a file exclusively and then add the folder to be synced (new add by "select folder" option in seafile client).
I used file locker util for testing: easy file locker: http://www.xoslab.com/efl.html after I found the issue with my locked outlook.pst file.

client 4.0.6:
Sync started. Ignored the locked files and synced everything else. Log says error 5 for locked files. - ok.
after sync finished: green hook. everything fine message for me. says status is synced - not ok - this is wrong as the folders are not in sync.
After unlocking the files and waiting some minutes: nothing happens. The files are not synced. Maybe I did not wait long enough. But: Added a new file to initiate sync. the locked files were NOT synced with the new file.
Selected manually to sync folder. Now the files were synced as well.
I think this is a major problem especially because the client does not tell that some files were not synced. Acutally the folder is _not_ in sync.

client 4.0.7.1:
same problem. plus: the sync stops at the locked file and does not even sync files that are after the locked file. Also says everything is fine (green hook and in sync message).
For this separate additional little problem see bug: https://github.com/haiwen/seafile/issues/1109

**Comment by freeplant** [comment]
About client 4.0.6 part:

In most cases, locked files should be readable and they will be synced. Some special programs lock files and make them not readable. So there locked files can't be synced until manually sync (sync now) or restarting the client.

**Comment by zacharyTris** [comment]
But it does not tell me that files were not synced!. So I assume from "green lights" that everything is fine. Without noticing that my files aren't synced. And I have to do it manually (?). When should I do that if I don't even know that the files were not synced?
The scenario (and initial problem) happend with outlook files. the outlook.pst is locked and cannot be copied. And you don't know that it is not synced. Both clients 4.0.6 and 4.0.7 report everything synchronized.

**Comment by freeplant** [comment]
It should have been fixed in the latest versions.
