### ISSUE TITLE
Possible to have multi seafile-data in different folder?

### ISSUE THREAD

**Issue by FireROR** [haiwen/seafile#1116]
Hi

Is that possible to put use two storage/folder/partition for seafile-data?

We are going to add two diff department in but they want to put files into different drive. Can we add more line into seafile.ini and point to different storage location? Or the data folder has to be one location...

Thanks

**Comment by freeplant** [comment]
It is not possible.

**Comment by shoeper** [comment]
ZFS (file system) can have multiple devices added to a single file system.

**Comment by FireROR** [comment]
The storage is cross on multi NFS site. so ZFS is not the option.

Thanks

**Comment by graywen24** [comment]
still now.. this still impossible ya..so sad

**Comment by shoeper** [comment]
I think it is possible with the professional edition.

**Comment by graywen24** [comment]
> I think it is possible with the professional edition.

just download new pro version ..saw 7.0.10 is ready..will try soon..thanks.

**Comment by shoeper** [comment]
https://download.seafile.com/published/seafile-manual/deploy_pro/multiple_storage_backends.md

**Comment by graywen24** [comment]
> https://download.seafile.com/published/seafile-manual/deploy_pro/multiple_storage_backends.md

Hi,  I read both Chinese and English manul for this multiple storage backend setup and reinstall new seafile pro 7.0.5 version.
I followed exactly the "user chosen" option:
> User Chosen
This policy lets the users to choose which storage class to use when creating a new library. The users can select any storage class that's been defined in the JSON file.

To use this policy, add following options in seahub_settings.py:

STORAGE_CLASS_MAPPING_POLICY = 'USER_SELECT'

If you enable storage class support but don't explicitely set STORAGE_CLASS_MAPPING_POLIICY in seahub_settings.py, this policy is used by default.

and Here is the storage class I defined even though all local file system??? here is my doubt, if I use different seafile-data folder will it support in this mutiple backend storage portion?

> [root@app01 conf]# cat seafile_storage_classes.json
[
{
"storage_id": "seafile-data",
"name": "seafile-data",
"is_default": true,
"fs": {"backend": "fs", "dir": "/seafile/seafile-data"},
"commits": {"backend": "fs", "dir": "/seafile/seafile-data"},
"blocks": {"backend": "fs", "dir": "/seafile/seafile-data"}
},
{
"storage_id": "cold_storage",
"name": "cold_storage",
"is_default": false,
"fs": {"backend": "fs", "dir": "/storage/seafile/cold_seafile-data"},
"commits": {"backend": "fs", "dir": "/storage/seafile/cold_seafile-data"},
"blocks": {"backend": "fs", "dir": "/storage/seafile/cold_seaflle-data"}
},
{
"storage_id": "new_storage",
"name": "new_storage",
"is_default": false,
"fs": {"backend": "fs", "dir": "/storage/seafile/new_seafile-data"},
"commits": {"backend": "fs", "dir": "/storage/seafile/new_seafile-data"},
"blocks": {"backend": "fs", "dir": "/storage/seafile/new_seafile-data"}
}
]"

as the "for_new_library": true, option is only mentioned in libarary ID mapping option so i removed it from my json file.

However I tested, frontend portal when I create new libarary by using new user account, still everything goes to  old seafile-data folder. There is no place to "CHOSEN" the storage class.

**Comment by graywen24** [comment]
> https://download.seafile.com/published/seafile-manual/deploy_pro/multiple_storage_backends.md

also I checked in seafile-db database, there is one  table for storage_id information, however the mapping is only repo_id, storage_id.  Do we need to add new storage_id before we confige this storage class json file?

**Comment by graywen24** [comment]
![image](https://user-images.githubusercontent.com/8322402/67361007-0a6a0600-f59a-11e9-9fe3-95f67cb0f957.png)

i think my guess is correct... but not sure whether it is the real steps but now I can store upload files under new seafile-data folder.

I manually changed database storage_id for the newly created library. can see the new id is "new_storage" which point to "fs": {"backend": "fs", "dir": "/storage/seafile/new_seafile-data"},
then I copy old commits folder(located at old seafile-data folder,as i didnt upload anything yet,so no folder under "fs" and "bloack") to this new  commit folder(commits": {"backend": "fs", "dir": "/storage/seafile/new_seafile-data"},)
then wola... all working ..
but it is really not a good way even can make it work.

**Comment by graywen24** [comment]
another update here. 
I tried to uprade to 7.0.6 and 7.0.10 this multip backend storage all not working and always will use default storage_id if you choose "USER_SELECT" oR "ROLE_BASED"
and there is a error if you choose above all, I have to comment enc_version line to make it pass thru, however still can not make it work.

Really hope any developer can look into it. 
[https://forum.seafile.com/t/cant-create-a-new-libraries-after-upgrade-to-7-0-5/9419](url)
