### ISSUE TITLE
how to find errors

### ISSUE THREAD

**Issue by Semmelbroesel24** [haiwen/seafile#1121]
a big problem is, how to find errors!
The logs show only there is an error, but where und why.
I have no chance to find which files is the problem.
This should be changed.

Greetings Mario

**Comment by 1resu** [comment]
Hi Mario,
to which logfile error your post is related?

**Comment by Semmelbroesel24** [comment]
The Client show, there is an error.
But which file doesn't like the client?
In the seafile log there are only upload error http://domian.de/ bla bla bla
So you have no chance to find the error.

**Comment by killing** [comment]
Your error is an upload error. And since Seafile doesn't upload files in a
one-by-one manner, you usually can't fix it by removing some files.

2015-03-10 4:46 GMT+08:00 Semmelbroesel24 <notifications@github.com>:

**Comment by Semmelbroesel24** [comment]
But it fix it. If I remove all files and copy step by step the files back.
But this take a long time, if the log show which file he doesn't like it
saves a lot of time. to find the problem.
My problems at the moment i got a lot of errors by download an library.

Greetings Mario

2015-03-10 3:25 GMT+01:00 Jiaqiang Xu <notifications@github.com>:
