### ISSUE TITLE
Logfile changed from 4.0.7 to 4.1.1

### ISSUE THREAD

**Issue by Semmelbroesel24** [haiwen/seafile#1122]
In 4.07 it was easy to read the logfile, in 4.1.1 it is impossible.

**Comment by 1resu** [comment]
Hi,
why it's impossible - what's the error message? Which OS do you use?

**Comment by shoeper** [comment]
I have 4.1.1 client and my logs are readible with a simple text editor.
Maybe your logs are corrupted?

**Comment by Semmelbroesel24** [comment]
lock at both logs and you can see what i mean.

**Comment by shoeper** [comment]
I did. They are as they were before.

**Comment by Semmelbroesel24** [comment]
No, need some glasses? Do nod see that the format is changed?

**Comment by shoeper** [comment]
Give me a screenshot, please.

**Comment by Semmelbroesel24** [comment]
![image](https://cloud.githubusercontent.com/assets/3932878/6566630/68c66b1a-c6bc-11e4-8aad-96bdaf313d66.png)

Yellow Client 4.0.7
Blue Client 4.1.1 

Which is easier do read? 
Don't write use something like notepad++

**Comment by shoeper** [comment]
Lol, sorry your just to DUMB to read a text file. Shell I send you screenshots? Both logs look the same here.

Wasting teems and my time for such a bullshit.

**Comment by shoeper** [comment]
And don't tell me you are using windows editor.

**Comment by Semmelbroesel24** [comment]
Yes of course i use the windows editor. Why not, before 4.1.1 it was all good.
Next reason Windows Editor is on all computers, so i have nothing do to!
Of cource if i use notepad++ then it will show correct. But everytime there is an error on a client i have to look at the logs. I can't install notepad++ or something on all computers. And there are many computers where i'm not admited do to that. 

So which of both are dump, I am in the business world at home and not do some hobby as you.

If your are not form devoloper team, why are you write?
No one is interessted of your mind.

**Comment by shoeper** [comment]
And why did you start offending me?
Btw there are enough editors out that can run out of the box without requiring rights or an installation routine.
I'm not sure if you are interested, but this one is quote good http://www.flos-freeware.ch/notepad2.html (can also replace windows editor (requirering admin rights oc)).

**Comment by killing** [comment]
It seems this is caused by upgrade of glib library in 4.1 version.

2015-03-10 9:40 GMT+08:00 Sven <notifications@github.com>:

**Comment by killing** [comment]
@Semmelbroesel24 You can use WordPad to open the log file. It's also included in every Windows.

**Comment by Semmelbroesel24** [comment]
yeah this worked, but i have do shutdown seafile :-(
If i use windows editor it can run.

2015-03-10 3:42 GMT+01:00 Jiaqiang Xu <notifications@github.com>:

**Comment by shoeper** [comment]
Because Wordpad opens the file in read-write mode.

To fix this for the bad windows editor `\r\n` is required. Unfortunately I wasn't able to find some nice solution to have a system independent line ending/line seperator. One possible way would be using macros.

**Comment by Semmelbroesel24** [comment]
Sorry this was not intention!
But you must unterstand, i run some server for my customers. Their cutomers
run the clients, if now is problem at this cutomers i have to call and help
then why their is an error.
Im not the admin of this computer, if I now run a program or something else
on this computers and something goes wrong after days. Then i have a
problem with this customers, they will say i was on the computer and do
something.
Normally i give you rigth, i use notepad++ and all is good. But in the
business world you have care sensitive what you do on foreign computers :-(
I have some painful experience with this.

please don't be angry.

Greetings Mario

2015-03-10 3:23 GMT+01:00 Jiaqiang Xu <notifications@github.com>:
