### ISSUE TITLE
giving a ldap user admin rights results in an account with two passwords

### ISSUE THREAD

**Issue by 1resu** [haiwen/seafile#1123]
Hi,

to solve issue #922 giving admin rights to a ldap-user, seafile creates for this user a database entry with the same password. Changing the ldap password of course doen't affect the database entry. In this case it's still possbile to login with the old password, because after rejecting from the ldap server with this credentials (email + old password) seafile looks at it's own database where the old password still exists.

Maybe a fast solution for this is to prevent login with database account, when an ldap entry exists. For the long term role based user accounts (e.g. normal user, admin) are a better way.

**Comment by shoeper** [comment]
@freeplant is this still the case?

**Comment by freeplant** [comment]
It should be fixed in the latest version.
