### ISSUE TITLE
update timestamp 1970-01-01 for all files in old libraries

### ISSUE THREAD

**Issue by woffs** [haiwen/seafile#1125]
The Web GUI and the Android App show the last update timestamp 1970-01-01 for all files in some libraries. It seems, that those libraries are affected, which were created some time ago (before version 4 or even before version 3). New files in those libraries are affected, too. It seems that new libraries are handled correctly.
How to fix? Deleting and re-creating all libraries on all connected machines is not an option.

**Comment by freeplant** [comment]
Please check haiwen/seahub#333 . I'm sorry this is not fixable.

**Comment by woffs** [comment]
I see. Should be a FAQ entry.

**Comment by shoeper** [comment]
https://forum.seafile-server.org/t/seafile-library-migration-v0-v1/3520?u=shoeper
