### ISSUE TITLE
how to cleanup sync folder Structure

### ISSUE THREAD

**Issue by cbergmann** [haiwen/seafile#1126]
Hi,

first thanks for the great software but I have one Problem with the windows client.

I synced a large library (30 GB). In the process the syncing failed once and I restarted. Now I found out that instead of "c:\Seafile\Library" the library is now in "c:\Seafile\Library-1". On another client which failed mutiple times it is on "c:\Seafile\Library-4". The folders "c:\Seafile\Library" and "c:\Seafile\Library-*" contain partily synced files.
Now I have two questions?
1. Is it save to remove the partly synced folders as they take up a significant ammount of space?
2. Is it possible to move the finally correctly saved folder to "c:\Seafile\Library". Regarding this I already searched trough the sqlite files and found out that the "c:\Seafile\seafile-data\repo.db" file contains the table "RepoProperty" with key "worktree". Is it save to close seafile-client, change db file, rename folder, reopen seafile client or would that break something?

Best regards
Clemens

**Comment by shoeper** [comment]
When right clicking on a library and selecting info you can see to which folder your library is currently synced. Then you can unsync it (files will stay on your disk). 
1. Delete the other folders with the name but not containing full library. 
2. Rename the folder which was in sync before to any name you want.
3. Go to the seafile client and sync your library again, say that you want to sync it with an existing folder. Select the folder you've previously renamed.

It will take a few seconds or minutes (depending on your library size) until the progress has finished.

**Comment by cbergmann** [comment]
thanks that worked
