### ISSUE TITLE
Block commit fail when client is using PUT through HTTP.

### ISSUE THREAD

**Issue by meyerd** [haiwen/seafile#1128]
My client is issuing PUT requests as I added a new empty file (which works) and then edited it. When the applet is trying to sync the modified file, the seafile.log shows
    
    [03/11/15 16:16:46] http-tx-mgr.c(2145): Bad response code for PUT https://deepsea.ldv.ei.tum.de/seafhttp/repo/a2aa342b-d3df-4375-8d05-5d90aa36980b/block/add7c3dfeb73b946f502617c8bedce90a643449c: 500.
    [03/11/15 16:16:46] http-tx-mgr.c(2352): Failed to send block add7c3dfeb73b946f502617c8bedce90a643449c for repo a2aa342b.

However, downloading files that were uploaded through the web interface works perfectly.
I drilled down on the server and the seafile.log there says

    [03/11/2015 04:24:11 PM] http-server.c(1137): Failed to commit block 43d7bfcb:bec573f0cac5fea7da275026d31f7565963a3df7.
    [03/11/2015 04:24:13 PM] ../common/block-backend-fs.c(176): [block bend] failed to commit block add7c3dfeb73b946f502617c8bedce90a643449c: Text file busy
    [03/11/2015 04:24:13 PM] http-server.c(1137): Failed to commit block a2aa342b:add7c3dfeb73b946f502617c8bedce90a643449c.

It seems to happen when the backend tries to rename the block. Which surprises me, as when I check with lsof, no such files are listed as open. Maybe a race condition?

I am using seafile server 4.0.6 and seafile client 4.1.1 on linux and windows (same problem). Also seems to be the same problem on mac 4.1.1 client.

**Comment by shoeper** [comment]
are you sure your webserver settings are ok?
The 500 error code seems mpre likely to be a webserver error. (internal server error)

**Comment by meyerd** [comment]
Yes pretty sure, that should be ok, since the error on the server shows up in the according http-server.c for seafile.

**Comment by soulohsix** [comment]
I have this exact same issue and none of my windows clients can upload files.  This is on a new server (4.0.6) setup and client 4.1.1.  Everything works fine (uploading files) with browser on the same computer as well as android client.  Any idea????

**Comment by killing** [comment]
May I ask what operating system do you use? And what file system do you use for the seafile installation? On Linux the error "Text file busy" only happens for executable files. Or it may be related to the file system you use. Like in this http://unix.stackexchange.com/questions/52951/gedit-wont-save-a-file-on-a-virtualbox-share-text-file-busy

**Comment by soulohsix** [comment]
Server os is ubuntu 14.04. Client is windows 7.  Actually after looking further I don't have the exact server error. Seafile.log on the server says failed to commit block...device or resource busy. Seafile data directory is a nfs mounted share. I thought it was an issue with that but why would Web and android work if there is an issue with nfs? My only issue is with windows client. 

<div>-------- Original message --------</div><div>From: Jiaqiang Xu <notifications@github.com> </div><div>Date:03/11/2015  9:15 PM  (GMT-06:00) </div><div>To: haiwen/seafile <seafile@noreply.github.com> </div><div>Cc: soulohsix <mabryantjr@gmail.com> </div><div>Subject: Re: [seafile] Block commit fail when client is using PUT through
  HTTP. (#1128) </div><div>
</div>May I ask what operating system do you use? And what file system do you use for the seafile installation? On Linux the error "Text file busy" only happens for executable files. Or it may be related to the file system you use. Like in this http://unix.stackexchange.com/questions/52951/gedit-wont-save-a-file-on-a-virtualbox-share-text-file-busy

**Comment by soulohsix** [comment]
All three methods (browser, android, and windows client) work when I move the seafile-data directory to the local disk. Only when seafile-data is on a nfs share does the windows client fail to upload. What am I missing here?

**Comment by killing** [comment]
This could be an NFS configuration or mounting issue. Uploading from client
and from the web shares the same block writing code.

2015-03-14 6:34 GMT+08:00 soulohsix <notifications@github.com>:

**Comment by meyerd** [comment]
Ok, that narrows down the problem, that could exist in my installation, as the seafile-data is also mounted not as nfs, but as SMB share from a windows raid system. Unfortunately, I cannot change that in my installation. What surprises me, is that it works from the web-interface without any problems, but not from clients. What could be the difference in handling blocks there?

**Comment by meyerd** [comment]
I just upgraded the server to version 4.1.1 and the problem seems to be gone now. So the issue can be closed.

**Comment by soulohsix** [comment]
I upgraded my server to 4.1.1 as well today and my issue is solved as well.
