### ISSUE TITLE
the Captcha is too complicated

### ISSUE THREAD

**Issue by linzy410** [haiwen/seafile#1133]
After repeated login failures, the Captcha that appears too complicated, our people in my compnay have not succeeded, please reduce the difficulty of Captcha 
thx

**Comment by xiez** [comment]
Can u show us a screenshot of the Captcha ?

**Comment by linzy410** [comment]
![4](https://cloud.githubusercontent.com/assets/1390499/6662562/b9e1aaf6-cbf7-11e4-96d9-bf305704abb3.png)
![1](https://cloud.githubusercontent.com/assets/1390499/6662563/ba53f192-cbf7-11e4-8e8f-19f34cfd28b6.png)
![2](https://cloud.githubusercontent.com/assets/1390499/6662564/bac8756c-cbf7-11e4-8d22-202c363b09e3.png)
![3](https://cloud.githubusercontent.com/assets/1390499/6662565/bad7b158-cbf7-11e4-9c75-43ab44e6ef6b.png)

**Comment by linzy410** [comment]
This is the actual size of the picture

**Comment by B3NG** [comment]
OK, this is really too complicated... :D

**Comment by xiez** [comment]
Seems there is something wrong with your Python Image Library, how did u install that ?
Can u provide your version of seafile server, and your OS ?

**Comment by xiez** [comment]
You can also disable Captcha temporarily by enlarge `LOGIN_ATTEMPT_LIMIT` in `seahub_settings.py`

**Comment by shoeper** [comment]
Can confirm that they should look better. See: ![](https://mno.pw/0804)
