### ISSUE TITLE
High CPU firefox load when playback a video

### ISSUE THREAD

**Issue by huegelc** [haiwen/seafile#1134]
Hi,

using the latest seafile server 4.0.6 . When I play a video (20MB) in the GUI I get a high CPU load on firefox (60%-75%) and the video wont start playing. File is a mp4 video.

Thank you

**Comment by lins05** [comment]
Seafile doesn't support http byte requests yet, which means the browser
would need to download the whole video file before starting to play it.

FYI we have this feature recorded in our roadmap, but not scheduled when to
implement it.

http://manual.seafile.com/roadmap.html

**Comment by huegelc** [comment]
Thank you for your information
