### ISSUE TITLE
Sparse history scheme

### ISSUE THREAD

**Issue by Munken** [haiwen/seafile#1135]
Currently the options for keeping the history is
* Full
* None
* Keep X days. 

In comparison [owncloud offer a hybrid history scheme](https://doc.owncloud.org/server/7.0/user_manual/files/versioncontrol.html) where 

* For the first second we keep one version
* For the first 10 seconds ownCloud keeps one version every 2 seconds
* For the first minute ownCloud keeps one version every 10 seconds
* For the first hour ownCloud keeps one version every minute
* For the first 24 hours ownCloud keeps one version every hour
*   For the first 30 days ownCloud keeps one version every day
*   After the first 30 days ownCloud keeps one version every week

This scheme would be a compromise in terms of space. 
Would it be feasible to implement this ?

**Comment by shoeper** [comment]
Seafile does not need this compromise. In comparison to owncloud seafile uses block storage. So updating 100mb does not lead to another file with 100mb but to one with few kb. So in a case where owncloud stores one version seafile can store 100 versions and will in many cases use less space than owncloud uses for one (Ok on smaller files there could be an issue).
So this could be implemented but is not needed and won't save that much space.
