### ISSUE TITLE
Feature request for seafile-ignore.txt

### ISSUE THREAD

**Issue by B3NG** [haiwen/seafile#1138]
Is there any feature planned for an exception in the "seafile-ignore.txt"?

I tried the git-ignore style for "anything but ABC":
```
# anything
  *

# the exception
  !ABC/
```
It doesn't work. :(
(anything is ignored - including "ABC")

Maybe I'm 2 stupid 4 it?! ;)

I think this feature would be very nice, because it can save a lot of time and work in configuring complex "seafile-ignore.txt"-situations.

I'm using: 
 - seafile-server (Linux) v.4.0.1
 - Client (Linux) v.4.0.7

**Comment by shoeper** [comment]
Your not too stupid. ! is currently not supported.
Only * and ? are.

**Comment by B3NG** [comment]
THX for your fast response.
What is the `?` for - also an wildcard like `*` ?

**Comment by shoeper** [comment]
See http://seafile.com/en/help/ignore/

**Comment by B3NG** [comment]
OK. got it! ;) Thx
Same question like in the beginning: is there a feature like an exception (`!`) planned?

**Comment by tokred** [comment]
Maybe rsync's approach to inclusion/exclusion syntax could be used as inspiration (not the whole set, just the basic include/exclude)? See man rsync, chapter "FILTER RULES", e.g.

    + foo1/
    + foo2/
    - *

Just an idea...

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/seafile-ignore-txt-add-exception-pattern/4351

**Comment by SourceDoctor** [comment]
something new about this feature?
It would be very useful if only specfic files are wanted to be synced
