### ISSUE TITLE
seafile-controller: error while loading shared libraries: libccnet.so.0

### ISSUE THREAD

**Issue by gjunp** [haiwen/seafile#1140]
when I use seafile-admin start ，the error is：
seafile-admin start

Starting seafile-server...
seafile-controller: error while loading shared libraries: libccnet.so.0: cannot open shared object file: No such file or directory
Error: Failed to start seafile

how can i get libccnet.so.0?

**Comment by lins05** [comment]
Run "sudo ldconfig", and try again.

**Comment by gjunp** [comment]
It's Ok ,Thanks

**Comment by Gustl22** [comment]
Maybe the link of `libccnet.so.0` to `libccnet.so.0.0.0` is missing. Compare the `seafile-server-x.x.x/seafile/lib` with a fresh installation folder.
