### ISSUE TITLE
Little share bug (How to remove a share with yourself?)

### ISSUE THREAD

**Issue by simsasaile** [haiwen/seafile#1141]
If you share a folder with yourself (I know that this is not a normal use case :) I did it just for a test) a message appears that you can not share a folder with yourself which makes totally sense. BUT the folder appears nevertheless in the client under "Sub Libraries".

That should not happen and I would like to know how to remove it, because it is not listet in the web frontend under Shares/Folder.

Thanks, Simsa

**Comment by simsasaile** [comment]
Found the answer by myself:
You can remove this shares by logging in as admin, go to settings, links:
Here you will find all public links and you can remove them.

**Comment by shoeper** [comment]
Ok, then you could also close this ;)

**Comment by simsasaile** [comment]
I don't agree, because I think this could be improved a bit, because the user doesn't always have admin rights to seafile to fix this.  

So I recommend not to create a share folder if the message that you can not share a folder with yourself appears or that the user also could delete this folder (that means it should also be listed in his/her share link section)

**Comment by shoeper** [comment]
Ok, right. Imho expected behaviour would be that sharing with yourself is not possible.

**Comment by shoeper** [comment]
Sharing with yourself isn't possible any longer.
