### ISSUE TITLE
There is no way to revert acces to a library for a device.

### ISSUE THREAD

**Issue by PocketSam** [haiwen/seafile#1143]
I've accidentally blocked one of my devices and now it can't acces to the library. I get an error "You don't have permission to access this library". But I didn't find a way to revert this action.

**Comment by shoeper** [comment]
Did you try logging out and in again (warning: afaik your sync settings are getting removed at the moment)?

If your admin I'd have a look to the sql tables if theres no option in the admin interface.

**Comment by freeplant** [comment]
Resync the library at the client will solve the problem.

**Comment by PocketSam** [comment]
Hey, that worked. I've tried it a couple times yesterday.
As for me there is no need for such function. =) Or it should have a page for blacklisted devices to whitelist them.
