### ISSUE TITLE
make Time format configurable

### ISSUE THREAD

**Issue by cbergmann** [haiwen/seafile#1146]
Hi there,

I could not find out if and when where it its possible to configure the granularity to which the time format in seahub is displayed.
If you want to find out file overwritten problems "5 days ago" might not be enough.

If this is not implemented yet I see two options:
1. make this configurable so you can specify the time format.
2. Commonly today it is possible to hover over the "abstract" time to see a popup with the actual timestamp (Daten and Time with Seconds)

Might this be possible?

**Comment by freeplant** [comment]
We will add the second option: "hover over the "abstract" time to see a popup with the actual timestamp"

**Comment by freeplant** [comment]
We are currently focus on finishing the new interface design. So this feature will be delayed to about 2 months. If you can implement it, it will be very helpful.

**Comment by cbergmann** [comment]
My current implementation idea is the following:
I would rename [translate_seahub_time](https://github.com/haiwen/seahub/blob/master/seahub/base/templatetags/seahub_tags.py#L168) to translate_seahub_time_str.
Introduce a new translate_seahub_time() function which calls the translate_seahub_time_str function and wraps it into `<time>` tag with the full information.

**Comment by lins05** [comment]
Sounds good to me. Go ahead and send us the pull request!
