### ISSUE TITLE
Bug: Some files won't sync and no notification about it. Everything with green marks.

### ISSUE THREAD

**Issue by infinity85** [haiwen/seafile#1147]
Hi,

I encountered a problem, that one of my ISO files won't sync. I did not notice it out of the Windows 4.1.1 client as the green hook indicated a good status. Other files sync without any problems. Even manual sync from client is not working. I did just notice it by entering the browserinterface and seeing that the file is missing.

Log files:
seafile.log
[03/11/15 12:20:28] seaf-daemon.c(490): starting seafile client 4.1.1
[03/11/15 12:20:28] seaf-daemon.c(492): seafile source code version 2c34475
[03/11/15 12:20:28] ../common/mq-mgr.c(60): [mq client] mq cilent is started
[03/11/15 12:20:28] ../common/mq-mgr.c(106): [mq mgr] publish to hearbeat mq: seafile.heartbeat
[...]
[03/19/15 15:24:37] Failed to write chunk 15b51f0956a4cef8d6153c3689cef9d065f9b690.
[03/19/15 15:24:37] CDC: failed to write chunk.
[03/19/15 15:24:37] Failed to chunk file with CDC.
[03/19/15 15:24:37] Failed to index file E://****.iso.
[03/19/15 15:24:37] repo-mgr.c(2077): All events are processed for repo 06cf0ceb-776f-4d4c-8850-83955c35ce53.

Deleted the file already, put it back, changed filename... even uploaded it through browser, but it somehow doesn't appear on server. Other files do though. The file is a 4,64gb big ISO file, which I created myself, so it is actually working after mounting and so on.

Not sure whether this is a client or server issue. The client starts indexing the file and shows then a synced status, but this particular file won't sync. Now I created the ISO a second time (resulting in different checksum) and now it syncs. Is it possible, that seafile somehow blocks a certain checksum so that it will never be synced again? I mean... Indexing starts at least.

**Comment by killing** [comment]
Where do you put your Seafile folder? Are there enough free space in that
partition? In indexing, Seafile writes blocks into Seafile/seafile-data
folder. The log shows that it fails to write blocks into that folder.

2015-03-20 0:51 GMT+08:00 infinity85 <notifications@github.com>:

**Comment by infinity85** [comment]
Thank you for your answer :)

My seafile-data folder is on an 256GB SSD (NTFS) which is hooket via SATA to a Banana Pi, which is running OpenMediaVault (http://bananas.gda.pl/pobierz). There is enough space, more than 100GB free, as my library is synced with ~80GB right now. As I mentioned the problem seemed to be only related to this particular ISO. I have the impression that while having it mounted the indexing startet and remembered the indexed checksum. So every attempt so sync the file again failed as I described in prior post. So after deleting the ISO and building a new one with the same content, the files syncs without any problems now. I built the new ISO (same content) with UltraISO. The checksums CRC32 and SHA1 were different between the two ISOs. The new one is synct immediatley. So if you see it from a simple point of view, I could claim that after the first indexing the determined checksum has been kind of blacklisted in the system or so.

Do you now have an idea how this happened? I don't have the not syncable ISO anymore, as I deleted it in favour of the new one, so I can't reproduce it anymore :(. I'm sorry, that I deleted it completely :(. 

Anyway, I would like to know what I have to do to avoid such issues or even better: I would like to have some errormessage or indicator in the client. In my case I did not notice it at first, because the green hook appeared quite soon indicating that everything is ok. But then I wondered how it could sync a 4,6gb file in under 2 minutes.

**Comment by mb3dot** [comment]
I had seen this message too and the problem was that seafile had a permission for the folder, but not for the files in the folder.

**Comment by yhtang** [comment]
I am still having a similar problem. Several files in a repo's .git/object folder could never get synced, and the files are as small as a few hundreds of bytes.
