### ISSUE TITLE
Implement SSO facilities

### ISSUE THREAD

**Issue by xortim** [haiwen/seafile#1148]
A lot of large organizations leverage SSO through various mechanisms. Having support for SAML, OpenID, and other external authentication providers to facilitate this would allow greater adoption in large scale environments.

**Comment by shoeper** [comment]
Shibboleth and LDAP are available so far.

**Comment by xortim** [comment]
I didn't see either in the list of features or in the Admin section of Seafile (granted I'm using the community edition at the moment).

**Comment by shoeper** [comment]
See manual.seafile.com.

Afaik LDAP is pro only and Shibboleth is also in community edition.

**Comment by xortim** [comment]
Excellent. Having used Shibboleth before this greatly simplifies the process (by a lot).
Will there be plans to support other SSO providers, this appears to be reliant upon Shibboleth specifically rather than the underlying standard (SAML). Other widely used SSO providers which implement SAML are OpenAM and Atlassian's Crowd.

**Comment by shoeper** [comment]
I'm no dev of Seafile.
Shibboleth is new in Seafile. It is finished in v 4.1 wich is currently beta (according to seafile.com).

And the roadmap can be found here: https://seacloud.cc/group/3/wiki/seafile-roadmap/. OAuth is on the list but has not been scheduled yet.

**Comment by devyoustice** [comment]
is it currently possible to write a CROWD authentication / authorization extension as a plugin?

**Comment by killing** [comment]
No, it's possible right now. We do not have plan to support it yet.

2015-09-07 21:46 GMT+08:00 devyoustice <notifications@github.com>:

**Comment by martinberlin** [comment]
+1 for a single sign on option like Oauth 2 + openid so we can integrate seafile in corporate networks for users that already have an account, without the extra hassle to sign in again for the cloud storage

**Comment by freeplant** [comment]
OAuth already supported.
