### ISSUE TITLE
Add Multi Factor Authentication

### ISSUE THREAD

**Issue by xortim** [haiwen/seafile#1149]
Adding MFA / 2FA would allow for better security handling in large scale implementations and also allow the product to meet the strict security and auditing requirements of large corporations and government installations.

**Comment by shoeper** [comment]
Just a question: Do they really need MFA? Always thought it wouldn't be an issue for companies because the use their own virtual network and private cloud/services.

**Comment by xortim** [comment]
You would think. I've worked on RFPs which explicitly call out the need for MFA and SSO integrations - on top of only being accessible behind a VPN/intranet.

**Comment by shoeper** [comment]
Ok thanks for explanation.

**Comment by xortim** [comment]
Being able to leverage some of the new security keys would be ideal. FIDO U2F is already supported by Google, if that is not a direction which the project wishes to go, then perhaps integrating with a third party MFA service like YubiCloud would be an option.

**Comment by softcat** [comment]
+1 FIDO U2F

**Comment by shoeper** [comment]
#671
