### ISSUE TITLE
Seafile-applet Freezes During Initial Setup

### ISSUE THREAD

**Issue by jsl303** [haiwen/seafile#1150]
I run client 4.1.2 on Windows 7, and server 4.1.0 on Ubuntu.
I also use a screen reader called NVDA (nvaccess.org).
I keep getting Seafile is not responding during the initial setup where you add account and sync library.
If I don't it fast enough before (few seconds), GUI applet freezes.
I have to kill seafile-applet from the task manager and keep trying it until I do it fast.
Also once everything is setup, when  I reboot, Seafile traps my keyboard from being used with screen reader. If I uninstall Seafile, it works fine.
I didn't have this problem in Seafile 3.

**Comment by jsl303** [comment]
It got fixed on seafile 4.2.6, but the bug was reintroduced in seafile 4.2.7... Seafile traps the keyboard for some reason.

**Comment by Chilledheart** [comment]
@jsl303 can you post the related log from `applet.log` ? I am afraid this issue is related to Qt's bugs, i.e.,  [QTBUG-29716] and [QTBUG-39522] .

[QTBUG-29716]: https://bugreports.qt.io/browse/QTBUG-29716
[QTBUG-39522]: https://bugreports.qt.io/browse/QTBUG-39522
