### ISSUE TITLE
Windows client silently not syncing with https + self signed certificate

### ISSUE THREAD

**Issue by arnova** [haiwen/seafile#1153]
We're running a Seafile server on Debian 7 using Apache + https + self-signed certificate. The problem is that when installing a Windows client and using the https:// path for our server, the client keep trying to "connect to server". This apparently is due to the self signed certificate. The user is never informed about any issue with the connection. Currently one can workaround this by enabling "Do not verify server certificate in HTTPS syncing" (note that this is bad English afaik). 

I propose to inform the user about the self signed certificate with a dialog and allow them to turn this option on from there. I think this will improve user experience quite a bit.

**Comment by louiz** [comment]
:+1:

**Comment by shoeper** [comment]
The solution should be to import the certificate in the systems ca storage.
