### ISSUE TITLE
Alter config files and seahub_settings.py

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1154]
Change the config files such that instead of a single large config for each component that they either get broken into .local (ie ccnet.conf and ccnet.local) or the config file has an include for conf.d similar to other linux config files.   

This would make automating the deployment of seafile and management automation easier given that each deployment of seafile writes unique information to the config files, especially ccnet.conf (ID) and seahub_settings.py (SECRET_KEY).

**Comment by forouher** [comment]
That would be very helpful. Maybe a combined config file:


[General]
USER_NAME = Seafile Servername
ID = blablabla
NAME = ServerName
SERVICE_URL = https://seafile.example.com

[network]
fileserver_port = 8082
networkLow_port = 10001
networkHigh_port = 12001

[Database]
ENGINE = mysql
HOST = 127.0.0.1
PORT = 3306
USER = seafile
PASSWD = BLABLA
ccnetDB = ccnet-db
seafileDB = seafile-db
seahubDB = seahub-db
CONNECTION_CHARSET = utf8

[WEBDAV]
enabled = false
port = 8080
fastcgi = false
share_name = /

[seahub]
SECRET_KEY = "5636546-54522-415a-5436-543537835785"
HTTP_SERVER_ROOT = '/seafhttp'
SERVE_STATIC = False
MEDIA_URL = '/seafmedia/'

[mail]
EMAIL_USE_TLS = True
EMAIL_HOST = 'mail'
EMAIL_HOST_USER = 'GFJIO'
EMAIL_HOST_PASSWORD = 'fdsg'
EMAIL_PORT = '587'
DEFAULT_FROM_EMAIL = ""
