### ISSUE TITLE
DNG (digital negative) preview in the web UI

### ISSUE THREAD

**Issue by christianparpart** [haiwen/seafile#1157]
Hey guys,

first, i'm glad you made such a wonderful product *and* it's opensource! :)

I'd like to be able to preview not just simple JPG files and friends, but also DNG files.

DNG files is an image format used by photographers (not just professionals but those with a better camera and a better photo management software). I am just about to upload my images to my private server at which I just set up Seafile. One thing I am really missing is DNG file previews.

FYI: have a look at the ufraw & imagemagick's convert tools for converting images on the command line (i.e.g generating thumbnails).

You could either add the above as package dependencies in order to generate thumbs or inline previews of DNG files or consume the code bits to do it yourself.

Regards,
Christian.

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/dng-digital-negative-preview-in-the-web-ui/4352
