### ISSUE TITLE
onigposix.h: No such file or directory

### ISSUE THREAD

**Issue by der-domi** [haiwen/seafile#1158]
Hey,

I try to compile the latest seafile on my Cubietruck/Debian. When I run the following commands:

cd seafile-${version}
./autogen.sh
./configure --disable-client --enable-server
make

I get an error:
gcc -DHAVE_CONFIG_H -I. -I..    -DPKGDATADIR=\"/usr/local/share/seafile\" -DPACKAGE_DATA_DIR=\""/usr/local/share/seafile"\" -DSEAFILE_SERVER -DFULL_FEATURE -I../include -I../lib -I../lib -I../common -pthread -I/usr/local/include -I/usr/local/include/searpc -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -pthread -I/usr/local/include -I/usr/local/include/searpc -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/local/include/zdb  -g -O2 -MT http-server.o -MD -MP -MF .deps/http-server.Tpo -c -o http-server.o http-server.c
In file included from http-server.c:15:0:
/usr/local/include/evhtp.h:11:23: fatal error: onigposix.h: No such file or directory

Does someone know where I'm getting the header from?

Thanks,
Dominik

**Comment by der-domi** [comment]
Hi,

I installed the Oniguruma-library [1]. Now I could build seafile. It would be very helpfully if this could be added to the documation [2].

Dominik

[1] http://www.geocities.jp/kosako3/oniguruma/index.html
[2] http://manual.seafile.com/build_seafile/server.html

**Comment by killing** [comment]
Which version of libevhtp do you use? We only officially tested version
1.1.6 or 1.1.7. In those version, the Oniguruma library is bundled into
libevhtp.

2015-03-29 5:02 GMT+08:00 der-domi <notifications@github.com>:

**Comment by der-domi** [comment]
I took the master zip which is linked in the docu and build the library how described. Correct, the header is included in the zip file. Maybe the "make install" command does not copy the header file?

Currently I have the following header files located:

# locate onigposix.h
/root/libevhtp-master/oniguruma/onigposix.h
/root/onig-5.9.6/onigposix.h
/usr/local/include/onigposix.h

The last one comes presumable from onig package. Unfortunately, I didn't try to locate the file before I installed the onig package.

**Comment by techoutlooks** [comment]
`sudo apt insall libonig-dev` on Ubuntu installs 'onigposix.h'
