### ISSUE TITLE
Mount folder on server as seafile library

### ISSUE THREAD

**Issue by chodid** [haiwen/seafile#1160]
Hello everybody,

with great interest I have followed Seafile development and some discussions for a while now. As I'm now starting to plan my own implementation of Seafile I was a bit sad to see that seaf-fuse is still a one-way street without write support. As I want to access folders stored on the server I'm looking for a way to access a specific folder on the server through seafile. Is this possible in any way?

Thanks hell of a lot in advance for any help!

**Comment by shoeper** [comment]
Afaik only option to do this is using webdav with e.g. dav2fs so far.

**Comment by autochthe** [comment]
Sorry I didn't see this issue earlier. #1171 is a duplicate and should be merged.

**Comment by chodid** [comment]
Is there a plan/roadmap to enable writing to a folder in FUSE? This would change Seafile from very good to awesome!

**Comment by shoeper** [comment]
It's not on the roadmap at the moment. See https://seacloud.cc/group/3/wiki/seafile-roadmap/
