### ISSUE TITLE
Support of Windows Proxy Settings and PAC file

### ISSUE THREAD

**Issue by xpac1985** [haiwen/seafile#1169]
Today I tried to use the HTTPS Sync on Seafile from our company network, and sadly failed.

Our company is using a so called PAC File (http://findproxyforurl.com/example-pac-file/) for Proxy determination. When I manually figure out the correct proxy for my Seafile server and enter it in the Seafile settings, everything works fine.

However, I'm often at varying customers, whose Wifi networks require different proxys being used.

It would be great if Seafile would have

a) the ability to use the Windows Proxy settings, as most applications already do, so you don't need to change proxy information in half a dozen programms when being in a different network, and 

b) supporting not only simple "IP:Port" proxy settings, but also using a PAC file which may be taken from the Windows settings.

I consider this a request for enhancement, not an issue, but I couldn't find a better suited place to post this request.

Thanks a lot for your work!

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/use-system-proxy-as-mostly-you-dont-know-the-proxy-address/2321/2
