### ISSUE TITLE
Add files to the seafile server via drag and drop without "uploading" them

### ISSUE THREAD

**Issue by Goagali** [haiwen/seafile#1170]
Hello,

I don't think the title really explains what I need or am trying to work out. 

I only just installed seafile a few hours ago and am still trying to work out the functions.

What I am trying to do might be easier to understand if you have used owncloud before.

There I had a deligated "server" folder into which I could just add files per drag and drop and then they'd imiidiatly show up in the webinterface without having to "upload" them since they already are on the server.

Now with seafile I have the folder D:\seafile-server\seafile-data\storage\blocks where all the uploaded data ends up in, but I can't just add files manually per drag and drop into that folder.
All I can do is use the Windows-Client, log in with the adminaccount, create a new sync folder, add the files into it and then seafiles uploads the files into itself again and the files are doubled.

I hope you can help me out on this. If its not clear what my question is, i can try to explain further.

Best greetings from germany,
Tom

**Comment by shoeper** [comment]
Seafile is a sever software. You could setup WebDAV or fuse (read only) to access Seafile files.

Seafile saves data as blocks to upload as few as possible. If you make small changes to big files seafile can upload just a few data and everything is fine.
