### ISSUE TITLE
seafile-server: local directory as library

### ISSUE THREAD

**Issue by autochthe** [haiwen/seafile#1171]
It would be nice to be able to load directories outside the data directory on the server filesystem as libraries using arbitrary paths.  This would be similar to the [Local Storage in OwnCloud](https://doc.owncloud.org/server/6.0/admin_manual/apps/files_external/index.html#local-storage) or the [Filesystem Driver in Pydio](https://pyd.io/docs/v6/workspaces/workspaces-drivers/filesystem-driver/), which bind directories on the local filesystem.

**Comment by autochthe** [comment]
Sorry, realized this is a duplicate of #1160.  These issues should be merged.

**Comment by shoeper** [comment]
You can use fuse: http://manual.seafile.com/extension/fuse.html.
But it is read only at the moment.

**Comment by allanman** [comment]
Isn't this request the inverse of what fuse offers, though? I read it as you already have a bunch of other files locally on the server machine that you would want to serve through seafile (without "uploading" it into a repo)

**Comment by shoeper** [comment]
With fuse files would be in the repo but accessable in the same way they would be directly on the disk.

Don't think serving files from disk through seafile will ever come. Writing this part would be like a rewrite and would raise same problems e.g. owncloud has.
The main feature of Seafile is it's "bullet proof" sync and git like behaviour.

**Comment by cocodrino** [comment]
@shoeper Hi, I did a similar question recently #1421 I'd like if you can explain me a bit more about what problems has owncloud and if is in the future plans could use fuse for write files and not only read..thanks!

**Comment by shoeper** [comment]
Versions in ownCloud are whole files. Change of few bytes of a 5 GiB file and you are going to have 2 5 GiB files and all clients are going to download the whole file again (at least this has been the case but I don't follow the ownCloud project fot quite some time anymore). This is slow, needs very much space for history of big files and needs additional traffic.

I don't know if there is a plan for adding write support in the future.
