### ISSUE TITLE
Build and Run url is dead

### ISSUE THREAD

**Issue by rm--** [haiwen/seafile#1173]
http://manual.seafile.com/develop/README.html returns 404.
Please fix it.

**Comment by shoeper** [comment]
Don't think so. See http://manual.seafile.com/build_seafile/server.html.
Or just have a look at http://manual.seafile.com/.

**Comment by rm--** [comment]
err...I mean the URL that is linked in the README.markdown in this repo.

**Comment by shoeper** [comment]
ok right. I've created a PR correcting this.

**Comment by rm--** [comment]
Great, thank you!
