### ISSUE TITLE
Windows client with HTTP syncing enabled still tries to connect to server port 10001

### ISSUE THREAD

**Issue by arnova** [haiwen/seafile#1175]
We have enabled HTTP syncing (actually using HTTPS) on all our Windows clients. This all seems to work well. While inspecting our server's logs (while investigating another issue) it seems the Windows clients are still trying to connect to Seafile/ccnet on port 10001. I think this shouldn't happen when HTTP syncing is enabled, right?

**Comment by shoeper** [comment]
If "allow http sync" is enabled on each server blocking those ports via firewall shouldn't be an issue. Afaik they're used as fallback.
