### ISSUE TITLE
seafile server 4.0 : where did the "generate shared link" go ?

### ISSUE THREAD

**Issue by jschaeff** [haiwen/seafile#1179]
Hi,

I search a lot, the interface, the web and the issue tracker, but could not find the answer. Since my update from 3.2 to 4.1, the "share" button on a file or on a directory disapeared.

Is there a way to "bring it back" ?

Thanks.

**Comment by shoeper** [comment]
It should be there.
Have you installed adblock? I had the problem some time ago that adblock blocked the share icon because there was some stupid general filter blocking all images named /img/share.png.

**Comment by jschaeff** [comment]
Oh, right. This is it. I'll put a note for my users.

Thanks.
