### ISSUE TITLE
Seafile applet eats up huge amount of memory

### ISSUE THREAD

**Issue by alvinwng** [haiwen/seafile#1181]
Recently I have been running a KVM virtual machine on a Linux system with Seafile client 4.0.5. It crashes around once per day. The reason was not clear until just now that I discovered the crash was due to seafile-applet eating up all the memory of the system. My laptop has just 8GB of and the virtual machine was using 3GB. At the time of crashing, seafile-applet was using 3.21GB. At the time of crashing, the server wasn't even online. Do you have any clue why this would happen?

I also looked up ccnet.log to see what happened. Each time before it eats up all my memory, it kept trying to resolve the domain name of my server, showing the "Error while resolving ..." and "DNS lookup failed for peer ..." messages in the log. Could it happen that memory was eaten up without being freed in the process?

Now that I have updated my client to 4.1.5, but the problem remains the same. The memory usage still keeps booming. This machine was not even using the files in my library and the updates mainly came from the other machine I am using. On the machine that is updating the files in the library, the memory usage of seafile-applet was just around 80MB.

**Comment by shoeper** [comment]
Some memory leaks have been fixed a few month ago. Please reopen at https://github.com/haiwen/seafile-client if you still have problems.
