### ISSUE TITLE
self signed ssl - thumbnails broken

### ISSUE THREAD

**Issue by sho-87** [haiwen/seafile#1183]
It seems that thumbnails/avatar image support acts a bit weirdly

I had a self signed ssl certificate, and when using that none of the thumbnails or avatar images would show. in fact it showed a broken link image (404)

Since then, I have purchased a certificate from a CA. That is set up to work with domain.com. When using seahub through domain.com everything works perfectly - all images and thumbnails show correctly

I host seafile server on a NAS on the network, so when I try to use seahub with 192.168.1.50 (using nginx with ssl, so listens on port 443), again, none of the thumbnails show and they give me a broken link image instead. This is even with a CA cert

This seems like a bug where if you use either a self signed certificate, or a CA certificate but coming in through a local ip, thumbnails and avatar image links are broken. But this is not the case when using a CA cert through domain.com

Im running this on windows 8.1, seafile server 4.0.6. Client machines are also win8.1 using chrome

**Comment by nem2k** [comment]
I also noticed a error in the dev console:

GET https://domain.com/media/avatars/groups/default.png/cloud//cloud//cloud/…oud//cloud//cloud//cloud//cloud//cloud//cloud//cloud//cloud//cloud//cloud/ net::ERR_TOO_MANY_REDIRECTS

I have seafile set up in a non-root directory (I access it using domain.com/cloud). In my nginx.conf file, I have the following line:

location / {
		rewrite ^ https://$http_host$request_uri/cloud permanent; #root access redirects to cloud
}

The aim of that is to redirect all traffic going to domain.com to domain.com/cloud, making seahub the default page on my site

Maybe I set up nginx.conf incorrectly, or maybe this is related to the issue reported in my first post?

**Comment by nem2k** [comment]
oops sorry I just realised there was a separate github repo for seahub. Can this thread be moved or should I repost it there?

**Comment by shoeper** [comment]
Please repost it there if you still think this is a general issue of seafile.
