### ISSUE TITLE
Add syslog logging

### ISSUE THREAD

**Issue by forouher** [haiwen/seafile#1185]
Currently Seafile server logs into 5 logfiles:

- ccnet.log
- controller.log
- seafile.log
- seahub_django_request.log
- seahub.log

This makes them hard to understand (one would have to manually correlate timestamps).

Syslog can help with that. If all seafile processes would log to syslog, then they would show up combined in e.g. /var/log/daemon.log

**Comment by thewilli** [comment]
:+1:

**Comment by shoeper** [comment]
Btw. there is one more log, that is used for mail logging.
Think its name is something like seahub_email_*.log.

**Comment by LeDistordu** [comment]
:+1:

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/add-syslog-logging/4354
