### ISSUE TITLE
Folder restore by time

### ISSUE THREAD

**Issue by webcaetano** [haiwen/seafile#1188]
[idea] [enhancement]
Hello, 

Basically, add the feature for restore all files inside a folder, by time, or by number of files modified.

Here is an open source program for Dropbox, that do this task i'm talking about:
https://github.com/clark800/dropbox-restore

----------------------------------------------

I had a personal experience that this task saved me a lot.
I was in a Hackathon at San Francisco, when somehow we delete the entire project inside Dropbox. 
The fun part is... in this exactly event, have an Dropbox tent, very close to us.
[Event Picture](http://distilleryimage9.s3.amazonaws.com/89df74fc509f11e3b8a112d765b26b39_8.jpg)
I talked to the crew there, and they told me: "There's nothing we can do!".... :scream: 

And then i research and find this repo https://github.com/clark800/dropbox-restore 
It saved the whole project. :relieved: 

----------------------------------------------
This is very good ideia.
I'll be very glad if seafile overtake Dropbox on this too.

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/folder-restore-by-time/4355
