### ISSUE TITLE
IOS 8.1.2 seafile client keep crashing

### ISSUE THREAD

**Issue by ddqp** [haiwen/seafile#1191]
when I sync photo from iphone to sever, it keep crashing and after every crash, when I resync, it will create a duplicate photo. 
APP version 1.9.7

**Comment by kissg1988** [comment]
This seems to be related to this issue:

> I finally fixed that problem, it should come from the libevhtp version, the firmware you compiled use the higher version, the one in your git is the 1.2.9-1, it works.

**Comment by shoeper** [comment]
Please reopen in https://github.com/haiwen/seafile-client if still existant
