### ISSUE TITLE
API always returns 404 for specific files (file detail)

### ISSUE THREAD

**Issue by Chocobozzz** [haiwen/seafile#1195]
Seafile server version : 4.1.2
Seafile client version: 4.1.4
Server and Client on ArchLinux.

Sometimes the api always returns for specific files a 404 status code. This files were uploaded with a large library (~10Gb of musics).

	12:20:11 0 [florian@:~]% curl -v -H 'Authorization: Token 046ae18db9ced8906a852c68a6cf74cf743eceeb' 'http://localhost:8000/api2/repos/23227d6c-0e40-47a6-993f-fc4d6947c7a6/file/detail/?p=/Best%2080/Captain%20Sensible%20-%20Wot.mp3'
	7mensible04/23/15ot.mp3'*   Trying 127.0.0.1...
	* Connected to localhost (127.0.0.1) port 8000 (#0)
	> GET /api2/repos/23227d6c-0e40-47a6-993f-fc4d6947c7a6/file/detail/?p=/Best%2080/Captain%20Sensible%20-%20Wot.mp3 HTTP/1.1
	> User-Agent: curl/7.41.0
	> Host: localhost:8000
	> Accept: */*
	> Authorization: Token 046ae18db9ced8906a852c68a6cf74cf743eceeb
	> 
	< HTTP/1.1 404 NOT FOUND
	< Server: gunicorn/0.16.1
	< Date: Thu, 23 Apr 2015 10:20:46 GMT
	< Connection: close
	< Transfer-Encoding: chunked
	< Vary: Accept, Accept-Language, Cookie
	< Content-Type: application/json
	< Content-Language: en
	< Allow: GET, HEAD, OPTIONS
	< 
	* Closing connection 0
	{"error_msg": "File not found."

But I can find and play the file with the web interface on the url *http://localhost:8000/repo/23227d6c-0e40-47a6-993f-fc4d6947c7a6/files/?p=/Best%2080/Captain%20Sensible%20-%20Wot.mp3*

Moreover, if I change the name of the file, wait for syncing, reput its old name and wait for syncing again, the same curl command returns the file details:

	12:20:46 0 [florian@:~]% curl -v -H 'Authorization: Token 046ae18db9ced8906a852c68a6cf74cf743eceeb' 'http://localhost:8000/api2/repos/23227d6c-0e40-47a6-993f-fc4d6947c7a6/file/detail/?p=/Best%2080/Captain%20Sensible%20-%20Wot.mp3'
	7mensible04/23/15ot.mp3'*   Trying 127.0.0.1...
	* Connected to localhost (127.0.0.1) port 8000 (#0)
	> GET /api2/repos/23227d6c-0e40-47a6-993f-fc4d6947c7a6/file/detail/?p=/Best%2080/Captain%20Sensible%20-%20Wot.mp3 HTTP/1.1
	> User-Agent: curl/7.41.0
	> Host: localhost:8000
	> Accept: */*
	> Authorization: Token 046ae18db9ced8906a852c68a6cf74cf743eceeb
	> 
	< HTTP/1.1 200 OK
	< Server: gunicorn/0.16.1
	< Date: Thu, 23 Apr 2015 10:23:22 GMT
	< Connection: close
	< Transfer-Encoding: chunked
	< Vary: Accept, Accept-Language, Cookie
	< Content-Type: application/json; charset=utf-8
	< Content-Language: en
	< Allow: GET, HEAD, OPTIONS
	< 
	* Closing connection 0
	{"id": "29e7137e0aa7b5197f6458231f7cf35127ab6957", "mtime": 1429784600, "type": "file", "name": "Captain Sensible - Wot.mp3", "size": 4839931

Thanks :)

**Comment by Chocobozzz** [comment]
After some inverstigations, it seems to be this part of code which cause an exception (line 1714 of *seahub/seahub/api2/views.py* of seafile server 4.2):

                commits = seafserv_threaded_rpc.list_file_revisions(repo_id,
                                                                    path,
                                                                    -1, -1)
                c = commits[0]

And thus it returns not found. If I remove this lines, the file details are found (without the *mtime* of course).

**Comment by Chocobozzz** [comment]
Any news? It's quite annoying, the Seafile implementation in Clementine simply doesn't work because of this issue.

**Comment by freeplant** [comment]
We will look into the problem this week.

**Comment by xiez** [comment]
Fixed in https://github.com/haiwen/seahub/commit/f6fffd6020fc135bbae1e3f7e2620745b55fbbb9, will be included in next version. Thanks!

**Comment by Chocobozzz** [comment]
Great, thanks to you !
