### ISSUE TITLE
New function advise:differ package outport and import 

### ISSUE THREAD

**Issue by linuxhenhao** [haiwen/seafile#1199]
First,Thanks for your great works! I've been using seafile for nearly one year, It's very suited for my demand. In my daily use,I got a idea about the seafile's new function.Now the file sync only works 
when your clients can all connect to your server.Lets imaging an situation: You have a directory named A ,Both on you client computer C1 and C2, but C2 can't connect to the internet,means C2-noLan. You may always add some new files on the C1 and you want the A on C2 be the same 
as C1.Even you do some works on the C2-noLan,You want that your works can be outported as a
package use the seafile client and then import on the C1's client and last transported to the server.
a brief image:
![diagram1](https://cloud.githubusercontent.com/assets/1101329/7337983/b822a524-ec6f-11e4-9b83-7f4f6ab5648a.png)

**Comment by shoeper** [comment]
I'd recommend using some external folder sync software therefor. Don't think this will ever be in seafile. There won't be many users out there using it and it does not fit into seafiles architecture.
