### ISSUE TITLE
Cannot browse subfolders when using a password-protected download link

### ISSUE THREAD

**Issue by lchavas** [haiwen/seafile#1208]
Hi,

On our seafile server 4.1.2 (centos 6.5, apache HTTP proxy), when a user generates a download link to a folder which contains sub-folders, if he chooses to password-protect the link then the users are unable to visit the subfolders of said folder.

When the user clicks on the subfolder, he is asked for the password and is redirected to the main folder. Therefore the user is stuck in the main folder, and we cannot password protect folder structures that we need to share.

However, the contents of subfolders are still properly downloadable as a zip.

I am available if you need more information.

Best regards,
Lewis

**Comment by chboehm** [comment]
Same issue on seafile server 4.2.2 (Debian Jessie with Nginx). Though zip download does not work for me.

**Comment by xiez** [comment]
hi, this issue is fixed in v4.2.3, see change log https://seacloud.cc/group/3/wiki/server-changelog/

**Comment by chboehm** [comment]
Hi xiez, I upgraded to v4.2.3 and it works now. Thank you!

**Comment by xiez** [comment]
cool! i close this issue now
