### ISSUE TITLE
Can't create sublibraries from Libraries that have been transferred to me from another account

### ISSUE THREAD

**Issue by geist1** [haiwen/seafile#1210]
As the title says...

I just transfered ownership of a library from another user to myself, because I wanted to create sublibraries for it (i couldn't do that, when the library was just shared to me).

Now I am the owner, but creating sublibraries does not work. I tested and I could create a sublibrary for a library that I have created myself.

**Comment by geist1** [comment]
just FYI
logging in and out of seahub did not help
restarting seafile & seahub did not help

**Comment by killing** [comment]
Have you tried to the new "selective sync" feature in the client? It's
available for Pro users. Double click an "unsynced" library in the client.
A cloud file browser will pop up. Choose a folder to sync in the interface.

2015-05-01 20:44 GMT+08:00 geist1 <notifications@github.com>:

**Comment by geist1** [comment]
Hm. For some reason the client does not recognize me as a Pro-user right now. It usually shows next to the server address "Professional version", but right now it does not. So when I double click an unsynced library, I don't get the option to chose a folder to sync.

It's strange. I remember I still saw the "professional version" showing up in the client yesterday, when I was troubleshooting the other issue i had
