### ISSUE TITLE
Client not recognizing Professional version

### ISSUE THREAD

**Issue by geist1** [haiwen/seafile#1211]
I mentioned this in another issue, but since it still does not work I am creating a new topic

For some reason the client does not recognize the pro version anymore. It usually shows next to the server address "Professional version", but not anymore. I also don't seem to get pro features in the client. On seahub i do get pro features

I am running 4.1.1 Pro version and 4.1.6 mac client. I tried on different computers with different accounts

how can this be troubleshooted?

**Comment by freeplant** [comment]
The client only detects whether the server is pro edition once at startup. If failed, it thinks it is a community edition. Can restart the client solve the problem?

**Comment by geist1** [comment]
I don't know what changed, but now it works. i restarted the client several times and also the server, but it never helped. now after your reply the "professional version" tag showed up again. on every computer/account. magic ^_^

thanks

**Comment by geist1** [comment]
btw, this is still happening often. i start the client and it does not recognize pro.

**Comment by Chilledheart** [comment]
@geist1 you might want to give version 4.2.0 a try http://www.seafile.com/en/download/ . The latest version store this information persistently.

**Comment by geist1** [comment]
Thanks! Seems to work every time now
