### ISSUE TITLE
Seafile 'crashing' frequently resulting in "server hiccups" and "504 Gateway Time-outs"

### ISSUE THREAD

**Issue by geist1** [haiwen/seafile#1214]
I just wanted to change the name of a subdirectory of a library in seahub and got the error:

```
Error received: 511 Unknown service (In _start_service)
```

nevertheless the name change worked, i noticed, after clicking away the little "rename-window" and reloaded the page.

I then realized I had to change the name again, so I did and again got the error message, clicked away the window and then tried to reload the page, but got this:

```Page unavailable

Sorry, but the requested page is unavailable due to a server hiccup.

Our engineers have been notified, so check back later.
```

After a few seconds of waiting, i can successfully reload. Out of curiosity, i again renamed the folder and tried to reload, except that this time seafile would not come back. the browser just indicates "loading" but nothing happens. I had to restart seafile to get it to work again. (no need to restart seahub). I just had it happen again that it just loads and loads and i waited .. it ended with a 

```
504 Gateway Time-out
```

then, after that, i could reload again (without having to restart seafile)

This is the situation:

I have a Library "A", that has a Folder in it that has the Name "Aa". In this folder are 2 Folders, "Aa1" and "Aa2". I don't know why, but renaming these folders (Aa, Aa1 and Aa2) works without error message and gateway time outs. But every new folder that is created, i cannot rename without the mentioned error messages.

I tried creating and renaming folders in another library and did not have any problems.

Please help me understand

Seafile Pro 4.1.1 and Mac Client 4.1.6

**Comment by killing** [comment]
Please have a look at the server seafile.log.

2015-05-04 21:48 GMT+08:00 geist1 <notifications@github.com>:

**Comment by geist1** [comment]
i just did and nothing comes up in the log after the error happens.

i remember this is a library that i transferred from another user to myself. could that be an issue?

**Comment by geist1** [comment]
Ok I did some more testing and figured out under what conditions the error happens. I can reproduce it at will, but for a reason I have not figured out, this ONLY is an issue in one particular library. The only special thing about that library is, that it was transferred from another user to myself.

Only folders that are empty produce the error 
```
Error received: 511 Unknown service (In _start_service)
```
and a server hiccup, when renamed.

As soon as there is another folder in that folder, or a file, the Folder can be renamed without creating a problem.

I hope this helps. I'll update if i find out more
