### ISSUE TITLE
Sync file ownership and permissions via Seafile running as system daemon via root

### ISSUE THREAD

**Issue by MurzNN** [haiwen/seafile#1215]
I need to sync full linux /home directory with several computers, so I need to keep file ownership and permissions.
I try to find two-side sync system that sync not only files, but it ownership (user & group) and permissions (read, write), but find nothing :(
Will be good to see ownership and permission sync feature in seafile, for start is as system daemon via root user and sync whole /home folder and other system folders.

I understand that this will got some problems:
- what to sync - uid&gid or user and group names?
- how to sync Windows ownership with Linux?
- what to do when some username on some system absent?
- what to do with different permission systems on linux and windows?

So at firs will be good to see this for only Linux sync feature, and sync numeric uid and gid for files. 

I think this feature will be demand for many system administrators, because at now there are nothing good solutions exists for two-side sync with keeping multi-user ownership.

**Comment by programster** [comment]
+1 to this. I'm constantly forgetting why my SSH keys are not working for git commits and only until I manually try to use the keys to log into the server do I get an unprotected key warning and realize Seafile hasn't synced them with 700 permissons.

**Comment by denis-b** [comment]
I implemented this in my branch : https://github.com/denis-b/seafile. It allows seaf-deamon to set uid:gid for repos when run as root. seaf-cli download|sync allows to pass user and group arguments. 
There are probably lots of bugs and still a lot of work before upstream integration, but it works for me.
Please test !

**Comment by h44z** [comment]
Any news on this? Will denis changes be merged to the main seafile-client?

**Comment by denis-b** [comment]
My fork of seaf-cli works perfectly on my production server. 
Safe integration with seafile client, allowing user to configure remote sync of network shares from desktop client will probably require implementing  username mapping between seafile and unix server, as passing uid/gid is insecure.
So for now, one have to use command line on samba server to sync libraries.

But please note that this is not adressing the original problem discussed in this thread : uid/gid and rights will not be synced. For this just use Unison !

**Comment by h44z** [comment]
Thanks for the reply. I will just need the uid/gid setting - as my seaf-cli is running on a NAS as root - so it needs to set permissions properly. Is your fork compatible with 4.4.2?

**Comment by denis-b** [comment]
Yes, i guess, my server is currently running 4.4.1, but i didn't saw any changes in seafile  api.

**Comment by h44z** [comment]
Ok I have merged your changes with the latest 5.0.1 tag and it seems to work perfectly =)

**Comment by MurzNN** [comment]
Maybe we can provide your patches to Seafile developers for applying it to core, if they works stable for your tasks all of this time?

**Comment by denis-b** [comment]
Of course you can. I'm using it on production server for a long time now, with large amounts of data and it is perfectly stable. I haven't merged it with actual code, but normally it is ok. 

feel free to submit the patch.

**Comment by h44z** [comment]
I have also used this for a while now with client 5.1.4 (see my repo, I have merged denis code there). Works perfectly fine.

Would be cool to have this changes in the main client!

**Comment by 4ley** [comment]
Any news on this?

**Comment by shoeper** [comment]
no

**Comment by 4ley** [comment]
As a workaround until the feature is implemented, you may set the default permissions with `setfacl` like this

`setfacl -R -d -m u::rwX,g::rwX,o::- data/`

and if you like to inherit the group, use setguid sticky bit like this

`chmod g+s data/`

**Comment by MurzNN** [comment]
@qnxor Does Dropbox preserve permissions even if file is edited on Windows?

**Comment by qnxor** [comment]
@MurzNN yes (or at least it doesn't remove executable permissions)

**Comment by perrinaz** [comment]
It's 2020 and seafile still lags behind dropbox in this respect.

**Comment by IllyaMoskvin** [comment]
@qnxor I found a possibly better work-around than a cronjob: [incron :: inotify cron system](http://inotify.aiken.cz/?section=incron&page=about&lang=en)

> This program is an "inotify cron" system. It consists of a daemon and a table manipulator. You can use it a similar way as the regular cron. The difference is that the inotify cron handles filesystem events rather than time periods.

It allows me to create rules that say, "When an attribute of this file changes, check if it's executable, and if not, make it so."

You can use [incrontab](https://linux.die.net/man/5/incrontab) to manage [icrond](https://linux.die.net/man/8/incrond) rules, but I did it by deploying a rule file with Ansible.

For example, I added a file called `/etc/incron.d/incrond.conf`:

```
/home/server/seafile/libs/FOOBAR-LIB/start.sh IN_ATTRIB find $@ -not -perm -u+x,g+x -exec chmod u+x,g+x {} \;
```

Note rules in `/etc/incron.d` are system tables and will be run with `root` permissions. There's user table options, too.

Per the manual:

> **IN_ATTRIB** Metadata changed (permissions, timestamps, extended attributes, etc.) (*)

So the `find` command will fire off for more things than just permission changes, but if the file's permissions aren't "broken" it won't match the `find` filters, so the `chmod` won't run on it. This also avoids infinite loops, where the `chmod` fires, which sets off `incron`, while fires `chmod`, etc.
