### ISSUE TITLE
Seafile windows client has problems with high resolutions

### ISSUE THREAD

**Issue by christianfl** [haiwen/seafile#1216]
![seafile_screenshot](https://cloud.githubusercontent.com/assets/11208965/7502619/83c43722-f43d-11e4-8d0d-22af35a6617e.png)

As you can see, the windows client has a very small UI on PCs with high resolutions (in this example 2560x1440). You can barely see anything on 13".

**Comment by Chilledheart** [comment]
It is a known issue and we are working on it. Temporarily, you can try the solution provided in https://github.com/haiwen/seafile/issues/895#issuecomment-72356357 .

**Comment by Chilledheart** [comment]
Duplicated with #895

**Comment by shoeper** [comment]
I cannot confirm this issue on a surface pro 3.
... strange.
