### ISSUE TITLE
while "/bin/which" does not exist, the install script can't find python binary on my server

### ISSUE THREAD

**Issue by hehongbo** [haiwen/seafile#1218]
i'm installing Seafile Server 4.1.2 on my VPS Host, and it is a OpenVZ Machine running CentOS 7.0 Minimal.

i'm sure i have python2.7 on my machine, and the executable runs properly. but the install script keeps saying something like this, and a $PATH variable does not work.

    Can't find a python executable of version 2.6 or above in PATH
    Please install python 2.6+ before continuing.

after reading the install script, i found the problem came from the absence of "/bin/which" on my server, and the install script would not dealing with it.

please fix.

**Comment by lins05** [comment]
Nowadays it's hardly to find a linux distro that has no `which` command. A
workaround for you is to set the PYTHON environment variable:

export PYTHON=/usr/bin/python
./setup-seafile.sh
