### ISSUE TITLE
Deploy non-root domain - windows desktop client stuck "connecting server..."

### ISSUE THREAD

**Issue by sjroe** [haiwen/seafile#1224]
Following the server manual I have successfully deployed seafile at non-root domain (for example https://example.com/sf/)

The website and android app work without an issue.  However the windows desktop client is unable to sync a library.  It appears to get stuck in the state "connecting to server..."  I have tried versions 4.1.4, 4.1.6 and 4.2.0.

seafile.log gives the following entry:

`[05/10/15 23:01:52] http-tx-mgr.c(774): Bad response code for GET https://example.com/seafhttp/protocol-version: 404.`

Of course, you would expect a 404 from that address as seafile is deployed at non-root domain.  It should instead be looking at https://example.com/sf/seafhttp/protocol-version.  I have checked this in my browser and it succesfully returns {"version": 1}  

I am running seafile server 4.1.2 on Debian wheezy behind nginx.

**Comment by shoeper** [comment]
The seafhttp path is hardcoded. Only the seahub path can get changed.

**Comment by mathieu-mp** [comment]
This hardcoded /seafhttp hurts much.
Could you add this to roadmap?

**Comment by PoGo606** [comment]
Hello,
I had the same problem as described and I think that the deployment under a "non-root domain" should include the /seafhttp path.
This is not explained well in the documentation, and I'm also wondering : what is the purpose of the `FILE_SERVER_ROOT` directive if the path is "harcoded" ?

I don't think this is a proper solution as **all** the HTTP calls should be done under the user-defined path.

**Comment by shoeper** [comment]
I do understand that there could be a better solution, but why does it "hurt" so much? I wouldn't hinder anyone, to deploy other software at the same root level. I is extremely unlikely, that another software will need /seafhttp.

**Comment by PoGo606** [comment]
Well IMHO, if every web software developper would think that way, we would face a real problem dealing with HTTP calls outside the path of the application where they belong.

Of course no one else will use /seafhttp... This is a matter of keeping a clean reverse proxy configuration and to got all the applications "sealed" inside their path.

**Comment by shoeper** [comment]
Maybe it will work at some day. But Seafile was designed to run under it's own domain/subdomain.

**Comment by PoGo606** [comment]
To quote mathieu-mp, I'll be glad too to see it as an enhancement in a further roadmap ;)

**Comment by marco-websource** [comment]
I run into this issue as well. It is very confusing that you can set `FILE_SERVER_ROOT = 'https://www.myseafile.com/subdir/seafhttp'` and `ProxyPass /subdir/seafhttp http://127.0.0.1:8082` etc. along with the server address in the client `https://www.myseafile.com/subdir`, but then it will not work because of the hardcoded /seafhttp path. Please add at least a comment to the documentation at http://manual.seafile.com/deploy/deploy_seahub_at_non-root_domain.html that the file server root MUST be /seafhttp because it is hardcoded in the clients. Thanks!

**Comment by shoeper** [comment]
> I ran into this issue as well. It is very confusing that you can set FILE_SERVER_ROOT = 
this is in seahub config. So it's afaik not related to the client.
