### ISSUE TITLE
Disable Users in Corp. Environment

### ISSUE THREAD

**Issue by antares2001** [haiwen/seafile#1225]
Hello,

for now it seems that when a user is deleted in our LDAP, they still have access to the Seafile libraries, e.g., through the Seafile client programs (OS X in this case last tried).

As there may be situations when a user needs to be immediately disabled, we use to do that with deactivating the user in LDAP. This propagates to Seafile as far as I can see in the admin surface, but the user's still sync the libraries to their local clients, as long as they do not log out / delete the connection.

As this can be crucial to data privacy and security, is there a chance to disable a user immediately and disconnect from all resources?

Thanks in advance!

**Comment by freeplant** [comment]
The v4.2 pro edition will contain LDAP syncing feature that inactivate users deleted in LDAP. Please consider to buy the pro edition.

**Comment by antares2001** [comment]
Hi. That's one option, though the problem seems to affect also non-LDAP users when they are deleted in Seafile but logged-in via the standalone client. The client doesn't seem to notice the user was deleted.

**Comment by freeplant** [comment]
Do you use the v4.2 version (both server and client)? The v4.2 will remove all the access tokens when a user is deleted. The clients will not be able to access the server again.
