### ISSUE TITLE
seaf-daemon running at 100% CPU load blocks starting the Client

### ISSUE THREAD

**Issue by sjentzsch** [haiwen/seafile#1226]
Hi Seafile-Team,

I have the following problem: I am trying to sync a folder which contains a chroot environment which should *not* be synced. Despite creating a "seafile-ignore.txt" in the root directory containing the line "BBU_ROOT_3/*", the seaf-daemon tries to index the folder and finds itself in a infinite loop of symbolic links etc:

```
[05/12/15 02:14:35] wt-monitor-linux.c(513): [wt mon] fail to stat /home/sjentzsch/RoboCup/BBU_ROOT_3/dev/fd/27/BBU_ROOT_3/dev/fd/27/BBU_ROOT_3/dev/fd/27/BBU_ROOT_3/dev/fd/27/BBU_ROOT_3/dev/fd/27/BBU_ROOT_3/dev/fd/27/BBU_ROOT_3/dev/fd/27/BBU_ROOT_3/dev/fd/27/BBU_ROOT_3/dev/fd/27/BBU_ROOT_3/dev/fd/27/BBU_ROOT_3/dev/fd/27/BBU_ROOT_3/dev/fd/27/BBU_ROOT_3/dev/fd/28/usr/share/xml/docbook/schema/dtd/4/ent: Too many levels of symbolic links
```

Even when I remove the library from seahub and unsync the library, every time I start the client, seaf-daemon continuously tries to index the folder, runs at 100% CPU and prevents the actual client to start. So I have to kill the seaf-daemon, but then the client program does not work anymore.

I am running Seafile Client 4.1.6 (Ubuntu).

Looking forward to a response in the near future!

**Comment by killing** [comment]
Removing the 'Seafile' folder completely should solve your problem.
For the ignore pattern, have you tried "BBU_ROOT_3/"?

2015-05-12 8:24 GMT+08:00 Sören Jentzsch <notifications@github.com>:

**Comment by sjentzsch** [comment]
Yes I also tried "BBU_ROOT_3/" as ignore pattern.
Removing the Seafile-folder might help (I solved it by just removing the problem-folder), but still this is a bug of Seafile related to the symbolic-link-following issues?

**Comment by killing** [comment]
I think it's a problem of the ignore logic. I'll have a look at it.

2015-05-12 20:34 GMT+08:00 Sören Jentzsch <notifications@github.com>:

**Comment by cortopy** [comment]
I'm experiencing this exact issue on generic Linux version of the client. Is there any progress on this? 

I've tried removing the seafile folder. Client starts again on boot but it crashes and I experience the same problem again. seaf-daemon runs and blocks any other attempts at openning the client
