### ISSUE TITLE
How to stop seafile from listening on ports 10001 and 12001

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1231]
I have upgraded seafile from 4.0.6 to 4.2.0.  It is sitting behind apache listening on 443 (80 redirects to 443).  My client is linux and running 4.1.6 (which should use https.).  My client has the enable file syncing with http protocol box ticked.  After upgrade seafile still listens on port 10001 and 12001.  Client connects and uses both ports to sync folders.  There does not appear to be any documentation on how to turn off these now unnecessary ports.

**Comment by caniwi** [comment]
Okay so upgrading the linux client to 4.2.1 solved the connection issue.   I guess the title now correctly reflects the issue in that while seafile is sync'ing over https, it is still listening on 10001 and 12001.  How do we turn them off?

**Comment by 3onyc** [comment]
Considering you closed this I assume you found the answer? If so could you add it for anyone that gets here through search engines with the same question?

Thanks!

**Comment by shoeper** [comment]
Afaik this is not possible so far. But you could block those ports via firewall instead.

I think listening on those ports will be dropped at some time in the future because the client support for syncing via port 10001 and 12001 has been dropped in version 4.2.

**Comment by killing** [comment]
The ports are kept open to be compatible with libraries created before 3.0.
They can only be synced with non http protocol.
We can provide an option to close the ports.

2015-05-15 11:50 GMT+08:00 caniwi <notifications@github.com>:

**Comment by caniwi** [comment]
Closing the issue was a mistake and don't recall doing that.  Sorry.  The ports should be closed given the current client no longer uses them.  It should be an option to open or close the ports IMHO.

**Comment by freeplant** [comment]
The ports are not listened if removing them from the config files.
