### ISSUE TITLE
Seafile: BAD response code of GET

### ISSUE THREAD

**Issue by samerafach** [haiwen/seafile#1236]
After I upgraded from Seafile 4.1x to 4.21, I got this error:

[05/18/15 19:49:34] http-tx-mgr.c(774): Bad response code for GET https://cloud.web.com/seafhttp/protocol-version: 500.
[05/18/15 19:49:34] clone-mgr.c(812): Transition clone state for 2089f543 from [connect] to [connect].

I wasn't able to resolve it in anyway without going back to 4.16. Someone else here 

https://forum.seafile-server.org/t/after-upgrade-server-4-0-6-to-4-1-1-clients-cant-connect/988

I'm using Seafile of windows, which is by definition 32-bit (since you don't provide a 64-bit version. Please do that!).

reported a similar problem.

**Comment by scottp** [comment]
I am now having this problem on my Mac OS X, but I get a 404 for that URL. I think I will try down grading my Client.

**Comment by killing** [comment]
4.2.x client use http sync exclusively. You should try to set it up if
you're using https. See
http://manual.seafile.com/deploy/deploy_http_sync.html

2015-05-26 8:12 GMT+08:00 Scott Penrose <notifications@github.com>:

**Comment by scottp** [comment]
OK it was because I have not updated my Seafile server. Which looked too hard to do in a hurry, so I switched back to 4.1 client, and that has fixed my problem. Thanks.

**Comment by allo-** [comment]
Happens here with client 4.2.3 and server 4.2.2

**Comment by samerafach** [comment]
I haven't tested the new version of Seafile anymore after the problem and went back 4.16, but I realized that my Apache didn't have proxy_http module enabled. So maybe that helps. Unfortunately I'm too busy to test that now.

**Comment by allo-** [comment]
Here it seems (i cannot test before this one is fixed) a problem with reverse proxies, which cannot rewrite ``/seafhttp/`` to ``/``.

**Comment by claasd** [comment]
Hi,

i could solve the Bad response code for GET https:://URL/seafhttp/protocol-version: 500. by enabling the module "proxy_http" in the apache configuration in addition to the "proxy" module

Claas

**Comment by TheQuantumPhysicist** [comment]
This problem happened with me recently so many times. I found eventually that the ccnet-server is not responding for some reason, so I did this and it works (many times, not only once):

```
sudo pkill ccnet
sudo service seafile-server stop
sudo service seafile-server start
```

**Comment by TheQuantumPhysicist** [comment]
@shoeper, I'm confused. I have the latest Seafile server (6.2.5), and it still uses `ccnet-server` on port 10001. Am I doing something wrong?

**Comment by shoeper** [comment]
Ah sorry, I've been at the client.
