### ISSUE TITLE
Seahub acccepts Wildcards in share.

### ISSUE THREAD

**Issue by cbergmann** [haiwen/seafile#1238]
Hi there,

we tried to share a library to all users in a domain. Our Seafile server is connected to LDAP and is not in Cloud mode. To our supprise Seahub accepted a share to the user `*@example.com` but it did not show the shared library in any user that has a Mail Address ending in `@example.com`.

We trace down the problem to a different interpretation of Strings in seahub and seafile-server.
In Seahub the code wich checks if the user is in the user list is found in the file [seahub/views/__init__.py in line 83](https://github.com/haiwen/seahub/blob/master/seahub/views/__init__.py#L83). This code accepts `*@example.com` as a valid user and the Address is added in the database to Table SharedRepo column 'to_email'.
In seafile in the file [server/share-mgr.c in line 208](https://github.com/haiwen/seafile/blob/master/server/share-mgr.c#L208) the SQL statement does not match this address to the address of the current user. In fact it will never match against any user except when there is a actual user with the Mail Address `*@example.com`.

There is a design decision to make here. If we want wildcards in shares we should match not with `WHERE to_email=?` but with `WHERE ? like to_email`. If we don't we have to adjust the filter in seahub.

**Comment by killing** [comment]
If you want to share to all users you can create or add a public library.
You can find this feature in the "organization" tab.
Yes, we don't want to accept wildcard in share.

2015-05-19 18:28 GMT+08:00 Clemens Bergmann <notifications@github.com>:

**Comment by cbergmann** [comment]
Hi there, the goal was not to share it with all users but only to the users whose mails end in a certain domain. There are users which have other domains. 


-------- Ursprüngliche Nachricht --------
Von: Jiaqiang Xu <notifications@github.com>
Gesendet: 20. Mai 2015 04:12:59 MESZ
An: haiwen/seafile <seafile@noreply.github.com>
CC: Clemens Bergmann <cbergmann@schuhklassert.de>
Betreff: Re: [seafile] Seahub acccepts Wildcards in share. (#1238)

If you want to share to all users you can create or add a public library.
You can find this feature in the "organization" tab.
Yes, we don't want to accept wildcard in share.

2015-05-19 18:28 GMT+08:00 Clemens Bergmann <notifications@github.com>:

> Hi there,
>
> we tried to share a library to all users in a domain. Our Seafile server
> is connected to LDAP and is not in Cloud mode. To our supprise Seahub
> accepted a share to the user "*@example.com" but it did not show the
> shared library in any user that has a Mail Address ending in "@example.com
> ".
>
> We trace down the problem to a different interpretation of Strings in
> seahub and seafile-server.
> In Seahub the code wich checks if the user is in the user list is found in
> the file seahub/views/*init*.py in line 83
> <https://github.com/haiwen/seahub/blob/master/seahub/views/__init__.py#L83>.
> This code accepts "
> *@example.com <http://example.com>" as a valid user and the Address is
> added in the database to Table SharedRepo column 'to_email'. In seafile in
> the file server/share-mgr.c in line 208
> <https://github.com/haiwen/seafile/blob/master/server/share-mgr.c#L208> the
> SQL statement does not match this address to the address of the current
> user. In fact it will never match against any user except when there is a
> actual user with the Mail Address '*@example.com'.
>
> There is a design decision to make here. If we want wildcards in shares we
> should match not with WHERE to_email=? but with WHERE ? like to_email. If
> we don't we have to adjust the filter in seahub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haiwen/seafile/issues/1238>.
>


---
Reply to this email directly or view it on GitHub:
https://github.com/haiwen/seafile/issues/1238#issuecomment-103726683
-- 
Diese Nachricht wurde von meinem Mobiltelefon gesendet.

**Comment by freeplant** [comment]
This feature is too specific. We will add it.
