### ISSUE TITLE
Slow Ethernet Performance (11MB/s)

### ISSUE THREAD

**Issue by githubtobi** [haiwen/seafile#1239]
Hi Seafile-Team,

I just added an S-ATA SSD to my Hummingboard and discovered, that the Client (Win 7) can only sync with max 11MB/s. Webdav is 1,5 - 2 MB/s.

I tested the speed with iperf and it shows around 45MB/s on the ethernet port.

Then I discovered with nmon that only one cpu core is used - see image. 
I use nginx as webserver and added "worker_processes 2;" to nginx can use 2 cores.

![seafile-nmon](https://cloud.githubusercontent.com/assets/10399188/7746784/7f135ef0-ffb5-11e4-9476-730b66138855.jpg)

So what can I do to improve the ethernet speed?

BTW: Great Application. Love to see how you improve the performance and features over and over again.

Tobi

**Comment by nicolas33** [comment]
This 11 MB/s is weird value. It looks like the standard limit with 100 Mb/s ethernet cards. Did you test the network bandwith with the exact same two end-points? Has the server or any device in between a 100 Mb/s physical limitation?
