### ISSUE TITLE
Selecting history for sub folders always shows full history of complete library

### ISSUE THREAD

**Issue by arnova** [haiwen/seafile#1240]
I tried to view the history of a subfolder in one of my Seafile libraries. In the web interface I navigated to the folder in question and clicked on the "History"-link (in the grey area right under the folder's path). Instead of showing me the history for this folder (and all its subfolders), it shows the history for the complete library.

**Comment by killing** [comment]
The proposed behavior has been implemented.

**Comment by arnova** [comment]
@killing : Mind telling me how? I don't see any history at all anymore for folders with the latest version.

**Comment by killing** [comment]
Sorry I made a mistake. I thought this is the "trash bin" feature. I'll reopen it.

**Comment by freeplant** [comment]
There are only history for the whole library and history for a single file. There are no history for a folder currently.

![screenshot](https://app.seafile.de/f/84f7e43e60/?raw=1)

**Comment by arnova** [comment]
Will this be fixed/implemented anytime soon? The functionality is already in GIT itself, so shouldn't this be trivial then?

**Comment by freeplant** [comment]
This will not be implemented.
