### ISSUE TITLE
Folders with space in front are duplicated with same name but without space in front (on Mac)

### ISSUE THREAD

**Issue by wolfgangbremer** [haiwen/seafile#1242]
Hi there,

I'm using some folders called " Ready" (with space in front), so that they always show up in Finder at the very top.

Now I suddenly see on Seafile (locally on my computer) another folder "Ready" (no space in front) in addition to the " Ready" (with space in front) folder. The content seems to be the same in most cases; sometimes the content seems not to be the same though. See screenshots:

![projects](https://cloud.githubusercontent.com/assets/1269595/7771396/5dbb5e8c-0097-11e5-936f-cbfe2c8a2098.png)

![projects](https://cloud.githubusercontent.com/assets/1269595/7771336/ed666500-0096-11e5-9d0d-4892d9b90305.png)

![projects](https://cloud.githubusercontent.com/assets/1269595/7771347/f645ceb8-0096-11e5-8bd4-edb7c78cd34f.png)

It's also interesting to note that all of the suddenly duplicated "Ready" (with no space in front) folders seem to have been created all around the same date and time: April 23, 2015, around 2:30pm (14:30).

When I log in to Seafile through my browser, the space in front of the folder name is disregarded completely and it shows two folders with exactly the same name "Ready" (no space in front). See screenshot:

![design_-_exported_files_-_private_seafile](https://cloud.githubusercontent.com/assets/1269595/7771267/719fee1e-0096-11e5-9d42-3ef45271a01a.png)

It would be great, if this could be fixed. Thank you!

I'm using Seafile Client 4.1.6 on Mac OS X 10.10.3.

Best wishes,
Wolfgang

**Comment by freeplant** [comment]
Please use the lastest version. If the problem still there, reopen the issue.
