### ISSUE TITLE
Windows Client 4.2.0 - 4.2.2 lost funktion sync existing folder

### ISSUE THREAD

**Issue by Semmelbroesel24** [haiwen/seafile#1245]
HI,

with Windows Client Version 4.2.0 - 4.2.2 the client lost the funktion sync an exitisting folder.
This is terrible, now i have no chance to sync folder with different bibliothek names.
Please bring it back soon.

Greetings Mario

**Comment by shoeper** [comment]
this is a statement from@freeplant some time ago on this

> Because as feedback to us, many non-tech users find it confusing to sync a library 'A' to 'A-1' automatically when there is an old folder 'A'. So in the new version, we prompt a dialog and notify the user library 'A' will be merged with local folder 'A'.
>
> We think syncing a library 'A' with folder with another name 'B' is very rare. 'A' can only sync with 'A' makes the concept simple.
https://github.com/haiwen/seafile-client/issues/571

But I think the same you do.

Maybe the standard option to create some folder at x should be changed to created one if not existing (needs also description change) and the old option for manual choosing could come back.

**Comment by Semmelbroesel24** [comment]
I have no change the folder structure and this was one of the best feature in seafile.

**Comment by Semmelbroesel24** [comment]
no i have a really big problem.

**Comment by britiger** [comment]
I had the same problem. After view in my apache server logs I found 417 Response codes. After adding the folowing line in my server configuration. 
<code>RequestHeader unset Expect early</code>

**Comment by shoeper** [comment]
@britiger your issue is not related to this.

**Comment by mbdevpl** [comment]
A workaround that I use for this is: I installed "Junction" from Microsoft https://technet.microsoft.com/en-us/sysinternals/bb896768.aspx and also http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html#download (the second one is just a convenience). Junction is similar to a hard link feature in Linux.

How I use it is:

1. I create in some central place (like C:\Users\user\Seafile) links (i.e. junctions) to all my Seafile folders and I name those exactly as they are named on the server.

2. When I "Sync" some existing library, I pick C:\Users\user\Seafile as the sync location - Seafile prompts me that the folders will be merged.

3. I have my files in exact folders I want, and Seafile has them in folders it wants. Done.

**Comment by shoeper** [comment]
Interesting solution.

By the way: Seafile brought this back. I can be enabled in the settings. Is had been dropped because they (Seafile Inc.) got feedback that many non tech users were overwhelmed by this feature. As a compromise it has now to be enabled via setting to allow more experienced users to use it.

**Comment by mbdevpl** [comment]
Thanks, good to know :)

I also use my solution for another reason - to store the same folder on multiple Seafile servers. Some time ago this was impossible, but when you create a junction, you fool Seafile into thinking these are two different folders. Is it also possible now without MS black magic?

**Comment by shoeper** [comment]
Unfortunately this is not possible. But good to hear that it is with your solution (I also ran into this issue some time ago)
