### ISSUE TITLE
Remove encryption of a library?

### ISSUE THREAD

**Issue by samerafach** [haiwen/seafile#1246]
Why is it not possible to decrypt a library? This option is very important to fix the date problem in Seafile, in which all dates appear as 01-01-1970. If it were possible to decrypt libraries, one could create a new library and move data to it, as it's now not possible to move data from encrypted libraries to others.

**Comment by shoeper** [comment]
You can sync the library via desktop client. And sync it to a new library. Once finished you can remove the old library.

**Comment by samerafach** [comment]
@shoeper Sir, did you really think this didn't occur to me or anyone talking in the language of encryption and holding his own Seafile server?

If I do that I'd lose the history of my files, which I still need.

All the best.

**Comment by shoeper** [comment]
Decrypting your library won't fix the 1970 problem as far as I am informed.
Your library has been created with 2.x?

**Comment by samerafach** [comment]
No, just decrypting the files won't solve the problem. But if I decrypt the files, I can create a new library and move them to the files new library through the Seafile web interface. Won't this solve the problem?

I think I've been with Seafile since 3.x. Don't remember precisely what the first version was.

**Comment by shoeper** [comment]
And where is the problem? Why can't you use the client to achieve this?

**Comment by samerafach** [comment]
The client can't do this, this can be done only with the web interface (moving from one library to another). And as I explained in my question, this can be only done with non-encrypted libraries.

**Comment by shoeper** [comment]
Why can't the client do this?

**Comment by samerafach** [comment]
@shoeper 

If you know how to do this with the client, please go ahead and tell me how.

**Comment by shoeper** [comment]
1. Sync the library with your pc/laptop.
 2. Unsync your library, your data will remain on you device
 3. Move the folder on the client to create a new library
 4. Wait until sync has finished

**Comment by samerafach** [comment]
@shoeper Sir, with all due respect, you need to read my question and my first reply to you 15 more times to understand why this doesn't help.

I have to say, again, that a person running Seafile on his own server and talking about encryption DEFINITELY KNOWS THIS LAME SOLUTION. Thank you for trying to help. 

I would like to say this in the nicest way possible because I honestly don't have time to chit-chat: If you're a Seafile developer I'd be shocked, and if you're not, please step aside and let some with more understanding of Seafile respond to me. Thank you again, Sir.

**Comment by shoeper** [comment]
I'm not a Seafile developer but I'm quite good informed about the software and the things going on here on Github.
Of course I agree, a better solution than this one would be nice but there is none (you could also use seafile-cli) and there's also no software to convert v2 libraries from v2 to v3 format. Furthermore such program won't come.
In addition I'm not sure if your requests  functionality will be implemented. On the the hand it shouldn't be too much work because the server is already able to decrypt data with the password on the other hand I don't think many people out there would ever need this (and that's what the developers look at).

Sorry if I've wasted your time.

**Comment by samerafach** [comment]
Well, developers have to find a way to fix this date problem, and I proposed a solution which is easily implementable. I'd love to hear one of the developers explain why this is not possible.
