### ISSUE TITLE
4.2.1 breaks link-shared subfolders

### ISSUE THREAD

**Issue by seidler2547** [haiwen/seafile#1248]
Just updated my Linux server to 4.2.1. When I share a subfolder (or access a previously shared subfolder), I can browse the share through the link alright, but I cannot access files in further subfolders, and for pictures there are no thumbnails. I can, however, download the files in question (I only tested with pictures - clicking normally on the filename generates:
> Page unavailable
> Sorry, but the requested page is unavailable due to a server hiccup.
> Our engineers have been notified, so check back later.

The logs say
> ../common/rpc-service.c(1500): Can't find seaf dir for /Subfolder

and

> ../common/peer.c(943): Local peer down

(although this doesn't necessarily has to be related).

Everything works as expected if I share the whole library.

Example:
 - whole library: https://files.teration.net/d/ba27bb44b8/
   - everything works
 - subfolder 1st level: https://files.teration.net/d/abc2206b30/
   - clicking through to the file doesn't work, downloading works, thumbnail doesn't show
 - subfolder 2nd level: https://files.teration.net/d/6325e4f670/
   - clicking through to the file does work again, thumbnail still doesn't show

**Comment by xiez** [comment]
Thanks @seidler2547 , fixed in https://github.com/haiwen/seahub/commit/78217254c25a467c3b7ab0b84820251a57423a67 and https://github.com/haiwen/seahub/commit/1fb3e10ea552d9e59f8ff1cedff715f6fe4c8b3d, will be included in next version.

**Comment by seidler2547** [comment]
I upgraded and everything works. Thanks!
