### ISSUE TITLE
Share by Name instead of by Email or group only

### ISSUE THREAD

**Issue by computaholic** [haiwen/seafile#1249]

**Comment by computaholic** [comment]
Hey,

Sharing for another user requires its Email address. However, sometimes the Mail address is completely different from the name of the user and is hard to remember. So it would be better to allow sharing by name, instead of email (and groups) only.

Thank you.

**Comment by freeplant** [comment]
We will add global address book. When it is done, you can type part of a user's name to search and share to that user.

**Comment by shoeper** [comment]
this is possible in v5
