### ISSUE TITLE
Upgrading 4.1 to 4.2 fails when seahub db host is a socket

### ISSUE THREAD

**Issue by alvaroaleman** [haiwen/seafile#1255]
```
Updating seafile/seahub database ...
[INFO] You are using MySQL
[INFO] updating seafile database...
[INFO] updating seahub database...
Failed to connect to mysql database seahub: Unknown MySQL server host '/var/run/mysqld/mysqld.sock' (0)
```

Steps to reproduce: Install Seafile 4.1.X, use ```'HOST': '/var/run/mysqld/mysqld.sock' ``` in seahub_settings.conf and run the upgrade script.

Workaround: Temporary set ```'HOST': '127.0.0.1' ```

Also, its somewhat annoying the upgrade script is not idempotent. After adjusting the Host setting, a second run failed with ``[ERROR] Failed to execute sql: Duplicate column name 'del_time'```. That error could only fixed by commenting out [line 111 in db_update_helper.py](https://github.com/haiwen/seafile/blob/52dad8e765acc680dcd8a12430716ae7df34869a/scripts/upgrade/db_update_helper.py#L111)

**Comment by lins05** [comment]
This issue was fixed in #1254, and would be included in the next release. For the "upgrade script is not idempotent" problem, we'll solve that later.

Thanks for reporting/feedback!
