### ISSUE TITLE
Chromebook client?

### ISSUE THREAD

**Issue by mark-hahn** [haiwen/seafile#1259]
Is anyone working on a chromebook client?  Google now has a file system provider API that allows installing a client that works just like google drive and shows the third-party client in the file-picker.

https://developer.chrome.com/apps/fileSystemProvider

I have moved my development entirely to my chromebook pixel, like many have.  This would be really nice.  It would also open up seafile to a fast-growing market.

**Comment by kwimberl** [comment]
I will second this suggestion.

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/chromebook-client/4356
