### ISSUE TITLE
hub using non-existant cache for css

### ISSUE THREAD

**Issue by mark-hahn** [haiwen/seafile#1261]
(this was previously in #1257)

I've got nginx https working.  Now I'm having a problem with the `https://mydomain.com` request.  It is loading all the files correctly except for one.  I am seeing this request get a `404`.  I checked and there is no `CACHE` folder in `media`.

```
https://mydomain.com/media/CACHE/css/999e7b4d6bb4.css
```

This is causing my page to look like ...

![screenshot 2015-06-01 at 7 35 35 pm](https://cloud.githubusercontent.com/assets/811455/7927478/6fa212ac-0895-11e5-8776-a893163ab3c2.png)

**Edit:** This url works fine ...

```
https://hahnca.com/sys/useradmin/
```

Also, I have reinstalled seafile and this still happens.

**Edit2:** I have also tried clearing my browser cache.

**Comment by andi-blafasl** [comment]
I had the same problem when installing a second instance for testing on the same server. I deleted the cache and it seems to fix the problem.

    stop seafile server
    delete the folder "/tmp/seahub_cache"
    start seafile server
    clear browser cache and cookies
    login again

**Comment by mark-hahn** [comment]
That fixed it.  Thanks.  I had reinstalled several times when chasing problems.  Apparently the install did not clear the cache properly.
