### ISSUE TITLE
functions code

### ISSUE THREAD

**Issue by dpkalu** [haiwen/seafile#1262]
help me!
what are ccnet-init.c, seaf-fsck.c, seafile-controller.c, seaf-server.c, seafserv-gc.c, ccnet-server.c, seaf-fuse.c, seaf-migrate.c and seaf-server-init.c function?

**Comment by dbruenig** [comment]
I suggest to use the repositories 
https://github.com/haiwen
to locate and read these files in order to understand what their purpose is.

**Comment by dpkalu** [comment]
file seaf-server.c : 
https://github.com/haiwen/seafile/blob/master/server/seaf-server.c
i don't understand function register_processors() and start_rpc_service (). please help me!

**Comment by lins05** [comment]
@dpkalu It's good to see you're interested in understanding how the code of seafile works. However, please note that github issues is not the proper place for learning/discussion the code line by line. It is meant to be used to report bugs, propose suggestions or feedbacks.

To learn the code these tools may help you:  

1. [cscope](http://cscope.sourceforge.net/)  
2. [gnu global](http://www.gnu.org/software/global/)

**Comment by dpkalu** [comment]
thank you rery much! i had understand
