### ISSUE TITLE
flowchart algorithm seafile server 

### ISSUE THREAD

**Issue by dpkalu** [haiwen/seafile#1263]
Could you please give me algorithm using flowchart of Seafile operational processes?
If so it can help me understand the following problem:
-      Where does the program begin running on server? Where the main() function?
-      If the client doesn’t connect to the server, what will the client do? How many the running flow?
-      When the client boot software, how to start the login process between the client and the server?
-      After login, what will the client and server exchange?
-      After exchanging information, what will they do?
-      When the client created the folder/file, what kinds of information will the client and server exchange?
Thanks!

**Comment by shoeper** [comment]
http://manual.seafile.com/develop/data_model.html
http://manual.seafile.com/develop/server-components.html
http://manual.seafile.com/develop/sync_algorithm.html
