### ISSUE TITLE
Ubuntu APT package / Update script

### ISSUE THREAD

**Issue by Pro** [haiwen/seafile#1264]
It would be nice to have seafile bundled into an apt package in a public repository for Ubuntu.
This would have different advantages:
- You can easily install it using `apt-get install seafile`
- Upgrading to a newer version can be automatically done using `apt-get upgrade`

Currently you have to check the versions page every now an then. If a new version is available, copy the url, then download it on the server, extract it and execute the correct upgrade script.

Gitlab switched to this new distribution method a few weeks ago and it is very comfortable to update and maintain gitlab.

Is there anything like that planned?

Or at least it would be nice to have a simple shell script which does the above steps (download new version and call upgrade script).

**Comment by shoeper** [comment]
I agree, I'd like to have one for debian.

But at least an announce mailing list would be nice (that only announces non beta versions).

**Comment by K-os** [comment]
Oh, a public debian repository (at least) for the client would be great! This should be easy, since the files are already hosted on bintray, which also supports debian and other distribution repositories.

**Comment by LeDistordu** [comment]
+1 ! And It will simplify seafile in docker !

**Comment by jonasbardino** [comment]
+1, that would really ease installation and upgrades

**Comment by LeDistordu** [comment]
something new ?

https://groups.google.com/forum/#!topic/seafile/GS8L9g_yY0I

**Comment by shoeper** [comment]
I don't think so. Maybe this could be done through bintray.

It think Seafiles quality could be improved by having multiple branches. E.g. stable (works), fast (should work, few minor bugs could be remaining) and dev/unstable/testing. Companies could install stable, normal users with at least some linux knowlegde could use fast (containing versions that were published in the past). Those could also report bugs and e.g. after 30 days without bugs stuff could be also put in stable. And a tasting branch for unstable stuff, but I'm not sure if this would be a real benefit.

Preferably stable and fast are also available for the client.
