### ISSUE TITLE
LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by dpkalu** [haiwen/seafile#1266]
LD_LIBRARY_PATH=$SEAFILE_LD_LIBRARY_PATH ${seaf_controller} --test -c "${default_ccnet_conf_dir}" -d "${seafile_data_dir}"
help me!
what's it mean?

**Comment by dbruenig** [comment]
it starts the seafile controller in test mode. It checks if the configuration found at directory denoted with **-c ** parameter is correct and if all processes could be started correctly. if all is correct, the process exist with error code 0 (no error).

See https://github.com/haiwen/seafile/blob/master/controller/seafile-controller.c function test_config for details

**Comment by dpkalu** [comment]
thank you very much!
now,  i want to add the synced features:
 - the first sync document files after sync audio files, video files
- the volume light files are synchronized before, the volume heavy files are synchronized later
   where are code edit? what's name code file must edit?

**Comment by dbruenig** [comment]
I cannot really figure out what you are up to, care to elaborate a bit more ?

**Comment by dpkalu** [comment]
hi. thank you very much! :+1:
