### ISSUE TITLE
seahub.sql REPLACE INTO mysql code doesn't create Value 44 and 45 

### ISSUE THREAD

**Issue by jobenvil** [haiwen/seafile#1267]
The shell script from update from R4.1 to 4.2 using following mysql code `/seafile-server-4.2.2/upgrade/sql/4.2.0/mySQL/seahub.sql` doesn't like to work for the following lines:

``` mysql
REPLACE INTO django_content_type VALUES(44,'client login token','base','clientlogintoken');
REPLACE INTO django_content_type VALUES(45,'org member quota','organizations','orgmemberquota');
```
The upgrade script  finished succesfully and doesn't show any error or indication but the values are not created in seahub-db. I insert the code manually on phpmyadmin and after that the values 44 and 45 are properly inserted in table django_content_type. I double check the seafile/seahub/ccnet-db user rights in mysql but they have all permissions without the exception of GRANT. This probably could have an impact on seahub functionality. 

![upgrade script 4 1 to 4 2 works](https://cloud.githubusercontent.com/assets/11994245/7954594/26d8a314-09d1-11e5-88cc-48ac7a07733e.PNG)

I can reproduce this with old `db_update_helper.py` and with new one using mysql databases with ports and with sockets configuration.

**Comment by lins05** [comment]
Thanks for reporting this!

This won't affect the usual functionality of seafile server. It's probably because the transaction is not committed. I'll take a look later today.
