### ISSUE TITLE
Enable https on Seahub: Access Issue

### ISSUE THREAD

**Issue by janisluetgemeier** [haiwen/seafile#1271]
Hello,

in your documentation Enable https with Apache2 on Seahub in the 000-default.conf is forgotten, that apache2 needs access to folder:
 <Location /media>
        Require all granted
    </Location>

It would be nice if you could add it in the documentation

**Comment by dbruenig** [comment]
The manual page 
http://manual.seafile.com/deploy/deploy_with_apache.html
states this configuration instruction.
