### ISSUE TITLE
git blob files missing from sync

### ISSUE THREAD

**Issue by mark-hahn** [haiwen/seafile#1273]
I am consistently seeing files missing from a sync of a `.git` folder.  The problem happens in both directions between two ubuntu 14.0.4 machines.  The files are all like ...

```
.git/objects/f7/81cdef1df954de68a3c64f5471860013aa46d9
```

A typical repo is missing 150 of these files.  The source `.git` folder is 3.3 Megs and the dest ends up with 2.6 Megs.

ubuntu 14.04
seafile-server 4.2.1
seafile-client 4.0.4

**Comment by mark-hahn** [comment]
P.S. I couldn't see anything in the log.

**Comment by killing** [comment]
Your client seems to be quite old. Have you tried the latest client?

2015-06-06 7:30 GMT+08:00 mark-hahn <notifications@github.com>:

**Comment by mark-hahn** [comment]
Can you point me to a file to download?  On `https://bitbucket.org/haiwen/seafile/downloads` the latest file I found that was a `.deb` or `.gz` was `seafile-cli_4.0.4_x86-64.tar.gz`.

**Comment by killing** [comment]
Cli client is not updated yet.

2015-06-06 10:03 GMT+08:00 mark-hahn <notifications@github.com>:
