### ISSUE TITLE
incoming message - sound notification

### ISSUE THREAD

**Issue by dijoje** [haiwen/seafile#1281]
Is there a possibility to play a sound on the Desktop, when a new message come in.

**Comment by mathieu-mp** [comment]
You want this on seafile-client, not seafile, don't you?

**Comment by dijoje** [comment]
Yes, I wish this for the seafile-client.

**Comment by mathieu-mp** [comment]
You should move it to the right issue queue and close this one. This one is
dedicated to seafile engine.

2015-07-21 18:02 GMT+02:00 dijoje <notifications@github.com>:

**Comment by dijoje** [comment]
Sorry, thank you for this information
