### ISSUE TITLE
Seahub with Apache on CentOS 6.6

### ISSUE THREAD

**Issue by 0x8DEADF00D** [haiwen/seafile#1284]
I've exactly followed the instructions in [this](http://manual.seafile.com/deploy/deploy_with_apache.html) guide but unfortunately it doesn't work. I'm always getting a 404 not found error.

The following line appears in my apache logfile:
`[Wed Jun 17 13:13:49 2015] [error] [client 192.168.181.1] File does not exist: /var/www/html/seahub.fcgi`

As your documentation states [here](http://manual.seafile.com/deploy/common_problems_for_setting_up_server.html), I should verify that the path matches with my document root and indeed, it does. (I took the virtual host config and set the document root to `/var/www/html`)

This problem is reproducable, just install a fresh copy of CentOS 6.6 and set up MySQL first. Then follow the instructions in the apache deployment guide.

**Comment by Mostey** [comment]
Ubuntu 14.04 with Apache 2.4.7 works with no problems so this either is an issue of CentOS or apache version 2.2 that CentOS 6.6 is using by default.

**Comment by shoeper** [comment]
Is /var/www/html/seahub.fcgi having the right permissions?

**Comment by Mostey** [comment]
> Is /var/www/html/seahub.fcgi having the right permissions?

Can you please define what the correct permissions are, @shoeper ?

**Comment by shoeper** [comment]
I've just found out it's no file (I'm not familiar with apache2).

But I could think of that you have altered some path leading to a wrong config.

Your root seems to be /var/www/html, so make sure you don't have this `FastCGIExternalServer /var/www/seahub.fcgi -host 127.0.0.1:8000` but this `FastCGIExternalServer /var/www/html/seahub.fcgi -host 127.0.0.1:8000`in your config.

**Comment by Mostey** [comment]
I had this already double checked and the path is correct as you've described. However, the file does not exists error still appears in my httpd log file

**Comment by toddpfaff** [comment]
Mostey, did you solve this problem yet?  I'm having the same problem, with centos 6.6 (apache 2.2)
and seafile 4.2.3.

**Comment by Mostey** [comment]
@toddpfaff No, I switched to Ubuntu where everything works with Apache 2.4.7

**Comment by toddpfaff** [comment]
I solved the problem this morning.

The centos 6.6 apache 2.2 default /etc/hhttpd/conf.d/fastcgi.conf has this setting:

  FastCgiWrapper On

Commenting out that line solved the problem for me.

tp

**Comment by Mostey** [comment]
Thanks for telling, would be great if someone could edit the docs so everyone knows what to do on CentOS 6.6.

**Comment by shoeper** [comment]
Can be done here: https://github.com/haiwen/seafile-docs
