### ISSUE TITLE
Update OpenSSL CA Certificates Store

### ISSUE THREAD

**Issue by mathieu-mp** [haiwen/seafile#1285]
Please update LibCurl CA Certificate Store

Currently, part of the client accepts my certificate* while LibCurl loops on "http-tx-mgr.c(639): libcurl failed to GET https://XXX/seafhttp/protocol-version: Peer certificate cannot be authenticated with given CA certificates"
I checked my certificate via digicert.com, sslshopper.com, various web browsers, and it is valid.

*: I can add an account, no certificate error. I can resume a sync, no certificate error. I cannot trigger a desync/resync, certificate error. Similar issues on Google all points to "update the client CA Cert Store".

Thanks.

**Comment by killing** [comment]
The client doesn't use the "bundled" CA store comes with libcurl. It reads
system CA store directly. Please make it clear which OS are you using.

2015-06-18 7:19 GMT+08:00 mathieu-mp <notifications@github.com>:

**Comment by mathieu-mp** [comment]
Thank you @killing .

I use Windows 8.1 x64.
I'm quite surprised as built-in Internet Explorer considers the cert as valid (and pretty sure this client uses system CA store).

**Comment by makkus** [comment]
I'm getting the same error, using Linux on the client, a Linux server with Apache on the server. I'm pretty sure I've got a certificate with the CRL distribution point embedded:

$ openssl x509 -text -in cacert.pem |grep -C 3 Distribution
            ...
            ...
            X509v3 CRL Distribution Points: 

                Full Name:
                  URI:http://crl.quovadisglobal.com/qvsslg2.crl

The weird thing is though, that I have another seafile server running, using the same certificate authority, the certificate looks the same except for the hostname. The main difference is that I'm using nginx on this one (there are a few other differences on how it's deployed too, though). And on this one everything works, using the same client machine. Not quite sure how that can be, must have something to do with the server setup, but at the moment I don't see what.

**Comment by makkus** [comment]
I'm having the same problem, using the Linux client, and Ubuntu 12.04 as server OS and Apache. QuoVadis issued certificate.
The strange thing is, I also run another seafile server in a docker-setup, that uses Ubuntu 14.04 as a base, and nginx as webserver. Same certificate authority. That one works fine, on the same client. Not quite sure what to make of that...

**Comment by makkus** [comment]
Ok, figured out (at least) my problem. Didn't have 

SSLCertificateChainFile myserver.crt.pem

in my site config on Apache.

**Comment by dersimn** [comment]
Same thing.. Seafile Client for macOS shows an error. In `~/.ccnet/logs` it says:

    libcurl failed to GET https://seafile.autlab.ei.hs-duesseldorf.de/seafhttp/protocol-version: Peer certificate cannot be authenticated with given CA certificates.

This occurred after updating the SSL certificate on Nginx. I'm using a "real" certificate, signed by DFN authority. This error occurs only for older clients that have been setup while the old cert was installed. Any client that was setup after deploying the new cert works totally fine.

Deleting `~/.ccnet` and `/User/.../Seafile/.seafile-data` doesn't fix the problem. There must be another cache storing the older cert that I'm not aware of.
