### ISSUE TITLE
garbage collection in pro edition

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile#1287]
Is the live gc automatically enabled in the pro edition or do I have to take some action to enable live gc.

This has not been documented very well in the manual which only says `Before running GC, you must shutdown the Seafile program on your server if you use the community edition. For professional edition, from version 3.1.11, online GC operation is supported. If you use Professional edition, you don't need to shutdown the Seafile program if you are using MySQL or PostgreSQL as database.`
Online gc is supported, yeah. But is it enabled by default?

**Comment by killing** [comment]
If you use MySQL, it's turned on by default.

2015-06-19 19:06 GMT+08:00 Sven <notifications@github.com>:

**Comment by shoeper** [comment]
I do. But I stopped the server, ran the gc and it deleted a few thousand 
blocks. Or does the live gc only cover blocks that "fall out" while pro 
edition is running (did run community edition till few days before now)?


Am 21. Juni 2015 03:52:52 schrieb Jiaqiang Xu <notifications@github.com>:

**Comment by shoeper** [comment]
One can run the garbage collection while the server is running in the pro edition.
