### ISSUE TITLE
Unable to connect to my server

### ISSUE THREAD

**Issue by Bingie** [haiwen/seafile#1288]
Hi,
I've set up seafile on my server.But after a while it shows "504 : Gateway time out".
How can I solve it？

**Comment by shoeper** [comment]
Read the manual.
http://manual.seafile.com/deploy/index.html

You have not set it up properly.

Make sure you have finished this steps:
http://manual.seafile.com/deploy/using_mysql.html (or the one with sqlite)
http://manual.seafile.com/deploy/deploy_with_nginx.html (or with apache)
http://manual.seafile.com/deploy/https_with_nginx.html (or with apache)

**Comment by Bingie** [comment]
Sorry I didn't make myself clear.
At first it can connect to my server and I can see my seafile profile.
But after a few minutes, it shows the problem there.

**Comment by shoeper** [comment]
Ok, then have a look at your logs (seafile/logs).
Those containing seahub in their name should be most relevant.

**Comment by Bingie** [comment]
Thank you.
I'll take a look at it.

**Comment by Bingie** [comment]
In the seahub.init.log file it just shows "Seahub is already running".

**Comment by shoeper** [comment]
So no other logs? e.g. seahub_django_request.log.
Then have a look at the other logs in the directory. And have a look at the webserver log.

**Comment by shoeper** [comment]
See https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#504
I'd try increasing timeouts.

**Comment by Bingie** [comment]
Thank you.
If you've updated please let me know.

**Comment by shoeper** [comment]
`If you've updated please let me know.`
I'm not a memeber of the team and this doesn't need an update. You've to set them in your webserver config.

**Comment by Bingie** [comment]
Now it has been solved:) Thank you.

**Comment by shoeper** [comment]
Great. It would be helpful for other people searching issues to find a solution for their problem if you could write down your solution (you knew how to increase timeouts, I do, but I think there are also people out not being able to do so).
