### ISSUE TITLE
Garbage Collector throws symbol lookup error

### ISSUE THREAD

**Issue by nopanic** [haiwen/seafile#1289]
After upgrading to 4.2.3, the garbage collector throws this error:

```
Starting seafserv-gc, please wait ...
/var/lib/seafile/haiwen/seafile-server-4.2.3/seafile/bin/seafserv-gc: symbol lookup error: /var/lib/seafile/haiwen/seafile-server-4.2.3/seafile/lib/libldap_r-2.4.so.2: undefined symbol: ber_sockbuf_io_udp
seafserv-gc run done

Done.
```

How can this be fixed? And why does the garbage collector need the LDAP-library?

**Comment by killing** [comment]
32-bit or 64-bit? What OS do you use?

2015-06-22 0:08 GMT+08:00 nopanic <notifications@github.com>:

**Comment by nopanic** [comment]
64bit, Debian 7.6
