### ISSUE TITLE
compatibility view with Internet Explorer Intranet Sites

### ISSUE THREAD

**Issue by andi-blafasl** [haiwen/seafile#1291]
We are using Seafile on a Server in our DMZ and we set up the IE Proxy Settings to bypass the Proxy for this DMZ Server. Because of this, the IE displays the seafile website in compatibility mode. Is it possible to add the meta header

    <meta http-equiv="X-UA-Compatible" content="IE=edge"/> 

to the Website? It would force the IE to not use compatibility mode.

I know I can change the file

    seafile-server-4.1.2/seahub/seahub/templates/base.html

but this change would be lost after an upgrade. Is there any way to implement this change in a way that survives an upgrade? Maybe like changing the logo?

Kind regards

**Comment by freeplant** [comment]
Please check our document on customization.

**Comment by andi-blafasl** [comment]
do you mean?

    http://manual.seafile.com/config/seahub_customization.html

As far as I can see, there is no way to customize the header of the seahub pages. I can specify a custom css file that is included in the header. And only the footer is a separate template. I don't want to replace the complete complete base.html ;-)

**Comment by freeplant** [comment]
You can create a file base.html in seahub-data/custom/templates to overwrite the default one.

**Comment by andi-blafasl** [comment]
ok, that would work to keep my customization across upgrades. But with every update I have to check the base.html for changes and replicate them in my custom one.
Checking about 220 lines of code would be easy with diff, but it is a separate step that is to be done. It would be much easier if there would be something like the footer.html or the branding.css

Inside the base.html there is a line:

    {% block extra_style %}{% endblock %}

Where does this extra_style come from? Is it possible to set the meta-Tag as an "extra style"?

Would be even nicer to have such a block for extra meta-tags ;-)

**Comment by andi-blafasl** [comment]
I just upgraded my server from Version 4.1.2 to 4.2.3 and it is no longer possible to overwrite the base.html with a custom version in seahub-data/custom/templates !!!

I tested the customization with a custom footer.html and the changes were show immediately.

**Comment by freeplant** [comment]
You should use base_for_backbone.html

**Comment by andi-blafasl** [comment]
thank you for the quick reply. I just found a even better option for setting compatibility mode.
Added the following to my apache config:

    Header set X-UA-Compatible "IE=Edge"

with active Apache module mod_headers, it add's the X-UA-Compatible flag to every request generated by the webserver. No more file changes needed!
