### ISSUE TITLE
Change the default collation of the libraries

### ISSUE THREAD

**Issue by andi-blafasl** [haiwen/seafile#1294]
All libraries in the web interface are sorted by "last changed column". Is it possible to change this behavior per user or per site?

I find it always confusing to see the little triangle after the name column and the libraries not sorted by name. It's even more confusing to the libraries with the same "last chang" not sorted by name.

attached screenshot of my default view after login:
![image](https://cloud.githubusercontent.com/assets/3586675/8356769/9bfdcede-1b57-11e5-962c-4d2ada2fa86b.png)

I think the "last change" column is stored with date and time but only date is displayed for older changes. But it is very confusing for the user to see "wrong sorting"

**Comment by shoeper** [comment]
It is not possible so far.

**Comment by balfred** [comment]
is that a feature on the roadmap?

**Comment by andi-blafasl** [comment]
This problem is "solved" in version 5.0.4
The default sort order is still "last change" but the little triangle is showing correct and you can change the sorting by clicking on the name column.
It would be nice to have a setting for the default sort column per user or per site. Butt this is no longer a bug, it is a feature request ;-)

**Comment by freeplant** [comment]
“It would be nice to have a setting for the default sort column per user or per site.” We will remember an user's last order-by choice in cookie. It will be done in 5.1.x.
