### ISSUE TITLE
mail server setup on debian seafile server

### ISSUE THREAD

**Issue by geist1** [haiwen/seafile#1296]
Hi,

i wanted to install a mail server on the same server that seafile is running on.

i am using this tutorial https://www.debinux.de/2013/10/mailserver-postfix-dovecot-ssl-und-sieve-mysql-spam-und-virenfilter-auf-debian-wheezy/

I have already setup a mail server on another server successfully following this tutorial, but this time i can't access the postfix web interface that's part of the installation (http://domain.tld/postfixadmin/setup.php)

it goes to my seafile web interface and tells me "Sorry, but the requested page could not be found."

how can i get seafile to not 'grab' this request?

thanks for the help!

p.s. i am using seafile-pro-server 4.1.2 on debian wheezy, with nginx

**Comment by shoeper** [comment]
Tell nginx where to search for postfixadmin.

Furthermore why are you opening a seafile issue therefor? It's absolutely unrelated.

**Comment by geist1** [comment]
i'm really sorry, i did not realize it was related to nginx until after i posted this. managing a webserver and nginx are both still pretty new to me

**Comment by tigerfoot** [comment]
@geist1 would be cool if you close the issue.
