### ISSUE TITLE
Client 4.2.5 unwanted file deletion - errors in logs "failed to stat"

### ISSUE THREAD

**Issue by gabriel-kropp** [haiwen/seafile#1298]
Dear all,
we are using Seafile to synchronize office, pdf and zip files between 100 users.

Some of them has reported to me a loss of folders, so I investigate the history on the server and found :
![image](https://cloud.githubusercontent.com/assets/13119407/8432180/b9c50c9e-1f3e-11e5-8d41-02e26177704c.png)

After contacting the users, noone has deleted the files (specially, the folder "United Kingdom"). They are not working on this part of the library.

I take a look at the logs of these clients, and found a similar pattern on each seafile.log:
```
06/30/15 12:19:12] sync-mgr.c(656): Repo 'Eur_North_2015' sync state transition from 'downloading' to 'synchronized'.
[06/30/15 12:19:14] sync-mgr.c(656): Repo 'Eur_North_2015' sync state transition from 'synchronized' to 'committing'.
[06/30/15 12:19:14] repo-mgr.c(2612): Failed to stat C:\Seafile.2015\Eur_North_2015\United Kingdom/ARQIVA LTD/101858 ARQ COM Test Mux/ARQIVA LTD - Shortcut.lnk~: No such file or directory.
[06/30/15 12:19:14] repo-mgr.c(2612): Failed to stat C:\Seafile.2015\Eur_North_2015\United Kingdom/ARQIVA LTD/101858 ARQ COM Test Mux/ARQIVA LTD - Shortcut).lnk~: No such file or directory.
```
I found one line "failed to stat" per removed file.
I am surprised by the ~ at the end of each entry : we don't have any file named like that.

Can you help me troubleshooting this issue ? It has appeared on 3.1.12 and continue after upgrade.

Environment :
 - server : CentOS 6.6 x64 / Seafile 4.2.3 / Apache with HTTPS (self signed certificate, authority deployed on each client)
 - client : Windows 7 x64 / Seafile 4.2.5 

Thanks for your support,
Gabriel Kropp

**Comment by killing** [comment]
I believe the "failed to stat" messages are irrelevant. They're printed out
when the client updates the overlay icons of file. The files ended with ~
is temp files created by the client when it downloads files.
Can you find out which user's client deleted the files? There is a bug in
some version of 4.0.x Mac client that can lead to this kind of deletion.
Check whether someone uses old Mac clients.

2015-06-30 21:53 GMT+08:00 gabriel-kropp <notifications@github.com>:

**Comment by gabriel-kropp** [comment]
Thanks for answering.
Yes, I know which users (shown on the screenshot), and they are on Windows 7, with seafile 4.2.5

No one has a Mac.

**Comment by killing** [comment]
OK, can you send me the seafile.log from the client? I need more context to
see what happened.
You can send it to my mail address.

2015-07-01 15:03 GMT+08:00 gabriel-kropp <notifications@github.com>:

**Comment by killing** [comment]
After reading your log, I see your problem now. It's also caused by an old bug. In 3.x version of Windows client (if I remember correctly), some folder and file names will be uploaded to the server in Windows 8.3 name format. The format replaces full file names with strings containing "~1", "~2". Windows has no problem handing it. But new clients may consider them non-existent and remove them.

You should be able to find the folders and files with 8.3 format on the server. But I think all the file names on the Windows clients should be still normal since Windows handles it transparently. So one solution is to delete the old library on server and create a new one from the files on the client.

**Comment by gabriel-kropp** [comment]
Ok, I understand the explanation.
>You should be able to find the folders and files with 8.3 format on the server.

Do you know if there is some automatic (script, search, etc...) way to find these files ? We have at least 10 libraries with more than 100+ folders in each, with a long hierarchy.

If there isn't an automatic way, can we try creating new libraries and tell the client to "sync with existing folder" ? With the option "different name" maybe ?

**Comment by gabriel-kropp** [comment]
I update this thread because it happens again.
It happens on folders which they don't have a 8.3 format name on the server.

The error is the same on the seafile.log logfile.

Can you help me ? I can send to you the new seafile.log if it can help.

Thanks,
Gabriel

**Comment by killing** [comment]
Sure. Please send me the seafile.log.
