### ISSUE TITLE
Full configuration without installer script?

### ISSUE THREAD

**Issue by knumor** [haiwen/seafile#1299]
Hi,

any thoughts on making seafile more suitable for use with configuration management tools like puppet, or possibly container based environments such as mesos/kubernetes?

The current configuration files seem to relay on "bootstrapping" by interactive scripts, inputing IP adresses etc.

I could not find any complete documentation of config file formats, so that we might construct a complete configuration from a template/environment and then just start the seafile components with a complete config?

If I have overlooked something, I apologize.

**Comment by shoeper** [comment]
Have you had a look at manual.seafile.com?
And I think there was a similiar issue some time before which I think hasn't been saved so far.

**Comment by freeplant** [comment]
You can give this a check: https://github.com/haiwen/seafile-server-installer

**Comment by knumor** [comment]
@shoeper I looked at the manual, can't find any complete docs on config file settings in there. For instance stuff like DB connection settings are not documented there (but set by the bootstrap script).

**Comment by shoeper** [comment]
Only section 5. And you're right there are some settings missing (afaik all those seafile sets on setup).

**Comment by gurvindersingh** [comment]
Documenting the missing setting will be good. Another thing which will be helpful to make setting up seafile more friendlier to new cluster manager e.g. kubernetes, mesos is making the configuration more streamlined and easy to setup values for IP addresses and other parameters. You can not accept to have these values enters manually, so it should be possible to add those values though environment variables or config mgmt. tools e.g. puppet, chef etc.
