### ISSUE TITLE
Sharing autocomplete shows only cached LDAP users

### ISSUE THREAD

**Issue by flomuedev** [haiwen/seafile#1301]
We have a Seafile server connected to our local LDAP. The autocomplete box for "Persons in the private sharing dialog does not show all users from the LDAP. 

However, users appear in the autocomplete box after they were displayed once on the organization tab page so I assume this is some kind of a caching issue.

**Comment by freeplant** [comment]
Yes, this is by design. Searching LDAP users is slow. Only imported users in local database will be searched.

**Comment by flomuedev** [comment]
How about displaying the known users - the ones from the local database - directly to the user (like you do it now) but keeping an indicator that the app keeps searching shown to the user. Then you can do the long running LDAP request and deliver the results to the users once it is done.

**Comment by vangual** [comment]
Please make /sys/useradmin/ldap/ also trigger the import then. (Just like /pubinfo/users/ currently does.) Like that I can at least mass-import all users with a manual url-call.

This is pretty confusing to our endusers that they only find *some* of the users and not all.

**Comment by freeplant** [comment]
You can use Seafile web API to list all users to trigger the import. Anyway, the LDAP user sync function in pro edition will be a even better solution.

**Comment by freeplant** [comment]
@flomuedev  Searching only imported users make the system simple and bug free.
