### ISSUE TITLE
A major bottleneck is causing very poor download speeds

### ISSUE THREAD

**Issue by bawNg** [haiwen/seafile#1311]
I found Seafile recently and it appeared to be very close to what I am looking for, I'd definitely trade in sync latency for binary delta compression and high throughput from an nginx server.

I need binary delta compression and to be able to maximize throughput speeds for downloads in order to be able to sync large server updates from a master server to many other boxes as quickly as possible.

Unfortunately after deploying a Seafile server with Nginx and the Seafile client on a bunch of servers with high throughput connections, the sync speeds have turned out to be very poor, downloads never go higher than around 350KB/s and often drop to much slower speeds. Each server has a minimum of 100Mbps/100Mbps throughput available and HTTP downloads from Nginx should be far higher than this.

Is this major bottleneck a known issue and are there plans to improve poor download speeds? I would love to be able to use Seafile but these speeds are completely unusable.

**Comment by killing** [comment]
Hi,

Are you syncing huge number of small files? If so, it's a known issue. The
syncing protocol is now single threaded, so a lot of time is wasted in stop
and wait if a lot of small files are transferred.

2015-07-11 7:02 GMT+08:00 bawNg <notifications@github.com>:

**Comment by bawNg** [comment]
I am currently syncing a directory containing a total of around 140 files across 300 directories. The total size is 1.85GB of which 1.68GB is contained by 28 files across 5 directories.

The number of files and directories probably causes the extremely low speed drops I have seen, but the highest speed is still very low when syncing the large binaries.

A single synchronous connection is definitely a huge bottleneck. Support for multiple HTTP connections when downloading is definitely needed here, HTTP pipelining could also help. A single download thread can still be used for multiple connections. IO-bound work should be implemented asynchronously as threading would only introduce unnecessary additional overhead.

**Comment by shoeper** [comment]
I cannot confirm these slow speeds. I sync about 30-40 libraries with lots of files and ~300 GiB data and get speeds of at least 15 MiB/s (average is about 25MiB/s) with ZFS Raid1 as storage. Previously I was using an SSD and got 80 MiB/s throughput (I mean MiB not mbit).

**Comment by bawNg** [comment]
@shoeper What latency do you have between your server and client host?

**Comment by shoeper** [comment]
<4ms

**Comment by bawNg** [comment]
Such a low latency requirement for usable speeds is not realistic unless Seafile is designed only for LAN usage.

The poor speeds I tested were between Seattle and Chicago in the US but I would like to be able to sync files as quickly as possible between servers hosted in the US, EU, Asia, Australia and South Africa. The latency between some of these servers will be very high and will definitely require multiple connections to sustain good speeds.

**Comment by ShonkyCH** [comment]
Latency shouldn't be such an issue with such a small number of files which would be quite large.

**Comment by shoeper** [comment]
Seafile uses blocks. So no metter how big your files are they will br 
splitup in blocks.

I'm not sure if the latency is the problem. But if not so seafile should 
definetly use multiple connections to get blocks.


Am 13. Juli 2015 05:20:18 schrieb ShonkyCH <notifications@github.com>:

**Comment by killing** [comment]
@bawNg Since you're not syncing lots of small files, it's not related to the issue I mentioned. It may be related to the classic long-fat channel performance in TCP (I assume you're testing in a WAN environment). Please provide more information about your OS and network.
- What OS do your use for the Seafile client?
- What's your bandwidth between the client and server?
- What's your network latency?
Seafile client uses libcurl for HTTP requests. It should have set proper TCP send buffer size.

**Comment by bawNg** [comment]
All servers are currently Windows Server 2008. Bandwidth available is between 100Mbps/100Mbps and 300Mbps/300Mbps. Latency between servers is between 50ms and 350ms depending on the locations, higher latencies will be introduced when new locations are added in the future.

Since Seafile downloads delta blocks when syncing changes for existing files, I assume each block makes a separate HTTP request, which would introduce the same overhead as many small files and would become a lot worse as latency increases.

This can't really be solved without multiple connections. Implementing HTTP pipelining support would help, but the only way to maximize throughput would be with concurrent connections.

Async requests are supported by the libcurl multi interface and shouldn't be too hard to implement for Seafile. I would implement it myself but I need to target Windows and I don't currently have time to get everything setup in order to be able to build the project on Windows.

**Comment by killing** [comment]
I think you may not get to the bottom of the problem. The average block
size for larger files is 1MB. Compared to the time used to transfer the
block content, the stop and wait latency is very small. Since you're using
Windows, my guess is that libcurl doesn't set big enough TCP send buffer.
Windows usually get into this problem since the default kernel TCP send
buffer is small. In your long-fat channel, the transfer speed is thus
limited. Anyway I'll do some testing.

2015-07-14 10:24 GMT+08:00 bawNg <notifications@github.com>:

**Comment by killing** [comment]
Yeah I think your opinion makes sense. But it doesn't explain why your speed can't go beyond 350KB/s. The average block size in Seafile is 1MB. Given your bandwidth, you should get higher speed like around 1MB/s. I still suspect it has something to do with libcurl's TCP send buffer size on Windows.
Using multiple connections is already in the plan. It should be available in a month or two.

**Comment by killing** [comment]
Have a look at the latest version. The performance should be better.

**Comment by jsl303** [comment]
I run client 4.2.8 on Windows and server 4.2.3 on Ubuntu, and I also have this problem.
I tested with a single file that is around 30mb. The speed stays around 100kB/s, but I get 2mB/s when I download the same file from the same server using ftp.
Previous versions didn't used to be this slow.

**Comment by shoeper** [comment]
> Have a look at the latest version. The performance should be better.

**Comment by jsl303** [comment]
I upgraded to both client and server to 4.3.2, and it works! 4mB-6mB/s!!!

**Comment by xili-h** [comment]
I have a similar problem with Seafile CE 10.0.1 due to terrible latency (200+ ms). I was only able to download in 1MB/s. In case anyone runs into the same problem. I solve it by increasing the worker_threads to 20+ in seafile.conf.
