### ISSUE TITLE
enhanced search

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile#1314]
It would be nice to be able to define where one wants to search for files.

E.g. only search in one library. Only search in a specific folder. If this is technically not possible filtering of the results by path could be helpfull.
This could work like this: path:Library/Folder
Leads to: Filtering out files and folders in that path only and hiding all other files.

**Comment by freeplant** [comment]
Searching in current library is already presented in the latest version.

**Comment by neurokrish** [comment]
Can this be extended to work on clients as well? At the moment in clients, we can search only all libraries. Am I missing something?
