### ISSUE TITLE
linux config folder (.ccnet)

### ISSUE THREAD

**Issue by ikcalB** [haiwen/seafile#1316]
placing config folders in the user's home directory (like `~/.ccnet`) is deprecated.
there is one folder called `~/.config` where each application should place its configuration folder (named like the application itself)

so I recommend changing `~/.ccnet` to `~/.config/seafile/ccnet`

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/linux-config-folder-ccnet/4357
