### ISSUE TITLE
MySQL user created during installation just allowed to access from localhost

### ISSUE THREAD

**Issue by FlorianLoch** [haiwen/seafile#1323]
Hi guys,
when generating a db user during setup this user is just allowed to login from localhost - this leads to access denied errors when trying to setup the databases. I am using a multi container docker setup and therefore had to change the host matching pattern of my newly created user manually after deleting the already generated configuration.
Perhaps the user should be generated using another pattern?

**Comment by shoeper** [comment]
It's defined here https://github.com/haiwen/seafile/blob/v4.3.0-server/scripts/setup-seafile-mysql.py#L594 and makes sense for many setups.

Because the database user is only created once it shouldn't be too hard to change it manually.

**Comment by FlorianLoch** [comment]
Of course it isn't to hard to change manually - but it might be a sticking point for many people using seafile inside a dockerized environment.

The problem actually isn't the change itself but that you need to delete the created configuration and start the setup allover again. So perhaps there should be the possibility to change "localhost" to "%" during the setup process?

**Comment by shoeper** [comment]
Ok maybe the script should just have a look if the ip is 127.0.0.1 or localhost and use % if not.

**Comment by FlorianLoch** [comment]
That would probably be the best solution! :+1:

**Comment by shoeper** [comment]
I've created a fix which hasn't been tested so far. Could you test it?
(will add link to it shortly)

**Comment by shoeper** [comment]
@FlorianLoch were you able to test the patch?

**Comment by waza-ari** [comment]
Hey, I have reported a [duplicate issue](https://github.com/haiwen/seahub/issues/798) (sorry I had not found this one!). First of all, thank you for your fix! I will be happy to test it. One note, though: is it wise to simply use "%", or could we use a mechanism to find out the IP address and just match on this? It might not be the best idea to allow access from anywhere.

What do you think?

**Comment by FlorianLoch** [comment]
I think setting the IP to a fixed value isn't a good idea although using
wildcard might be insecure in some setup scenarios. But having a fixed IP
might cause serious problems for example if you use Docker containers like
I do.

Cheers
Florian

--
Florian Loch
florian.loch@gmail.com
Mobil: +4917691354966
Tennesseeallee 28
76149 Karlsruhe

Gesendet von meinem Smartphone
Am 04.09.2015 21:04 schrieb "Daniel Herrmann" <notifications@github.com>:

**Comment by shoeper** [comment]
So best would be to ask the user. Default could be % and optional the user can set an own value. I'll try to improve the fix later.

**Comment by waza-ari** [comment]
I think this is a good idea! If server is "127.0.0.1" anyway, use this. Otherwise ask the user and use "%" as default. Thanks!

**Comment by shoeper** [comment]
I've written a fix. It can be found here: https://github.com/shoeper-forks/seafile/commit/cac272d097cfd2238c6e21fa1a9ba17ac4d7608c
The full script can be downloaded at https://github.com/shoeper-forks/seafile/blob/mysql-host/scripts/setup-seafile-mysql.py

**Comment by shoeper** [comment]
According to my tests this one should work https://github.com/shoeper-forks/seafile/commit/36face2972813e2d9e4e0c0115e1ae6aa98321e7

The full script can be downloaded at https://github.com/shoeper-forks/seafile/blob/mysql-host/scripts/setup-seafile-mysql.py

**Comment by waza-ari** [comment]
Going to test it later, I will give feedback.

**Comment by lins05** [comment]
@shoeper cool, can you create a PR?

**Comment by shoeper** [comment]
Of course, the thing is just I'm not sure if it's  a 100% working (that's why I haven't created one so far). But I'm going to create one now.

**Comment by shoeper** [comment]
@lins05 what about the PR? I'm not sure if it is still the best solution but the current behaviour leads to problems in some cases.

**Comment by FlorianLoch** [comment]
+1 for merging - the usecase leading to problems is, at least I assume this, quite straight forward and therefore popular. Also I see no real disadvantage with this solution - in case you have concerns about security issues you might add a warning if a not-local address is entered.
