### ISSUE TITLE
add support the get library download info from one revision to another revision

### ISSUE THREAD

**Issue by hepin1989** [haiwen/seafile#1324]
It's seems unsupported,which means this call will return a download info of the files changed between the two revision of the library.

这里我的想法是，获取library的两个版本之间的所有更改列表，然后可以打包下载。

**Comment by freeplant** [comment]
这个需求比较小众，暂时没有增加这个功能的计划。

**Comment by hepin1989** [comment]
@freeplant 其实这个需求还真不小众。
user case，游戏的差量更新，游戏的资源服务器，手游，需要差量更新资源，目前我自己写了一套，但是这种东西肯定很多人需要的。个人觉得可以加到schedule/enhancement里面试试。changels.reverse.scanRight 就可以拿到了。

thanks啦。

如果有这个功能了，我就基于你们的系统做。
