### ISSUE TITLE
markdown parser does not support atx-style header syntax

### ISSUE THREAD

**Issue by SvenBrunk** [haiwen/seafile#1329]
Usually Markdown supports 2 types of syntax for headers: setext and atx-style

Seafile works with setext:

<pre>
Headline
=======

Subheadline
---------------
</pre>

but not with atx-style:
<pre>
# Headline
## Subheadline
</pre>

which is not only much shorter in the document when viewed in source, but also much more convenient to type

**Comment by shoeper** [comment]
# 
##
###
####
#####
######
works for me.

**Comment by SvenBrunk** [comment]
now this is interesting... today it works... 
Thanks! I'll come back when I know under what exact circumstances it doesn't work...

**Comment by shoeper** [comment]
Maybe you did have a space in front. Afaik it doesn't work in that case

**Comment by SvenBrunk** [comment]
hm. that might be possible. I didn't intend to, but maybe. Thx for the hint
