### ISSUE TITLE
[Android Client] Camera Upload not working on Sony Xperia Z3 Compact

### ISSUE THREAD

**Issue by infinity85** [haiwen/seafile#1330]
Hello,

since I own an Sony Xperia Z3 Compact mobile phone, my camera upload is not working properly anymore. The first setup uploaded all the pictures, but since then it is not uploading anything new anymore. Even if I start the client manually, it won't sync the photos.

I used a Samsung Galaxy S2 until last week and there it was working flawlessly... sometimes I it was necessary to start the seafile client to begin the camera upload, but it uploaded every picture reliably.

Besides this I read in the playstore a vote which claimed to have the same issue on a similar Sony Z3 (not compact). [5/27/ 2015]. So apparently there is some kind of issue not only related to my specific device.

Anyways, fantastic product :)

**Comment by infinity85** [comment]
New v1.9 Client has the same issue. After installing it uploaded the pictures and afterwards it stopped and never uploaded again.

**Comment by mathieu-mp** [comment]
You'd better post there:
https://github.com/haiwen/seadroid/issues

But how come no one told you for 6 weeks?!?
