### ISSUE TITLE
 upgrade to 4.2 from 4.1 

### ISSUE THREAD

**Issue by confile** [haiwen/seafile#1331]
What does the following do? https://seacloud.cc/group/3/wiki/server-changelog/

```
COMPRESS_URL = MEDIA_URL
STATIC_URL = MEDIA_URL + '/assets/'
```

How do I know if it worked well?

**Comment by shoeper** [comment]
> If you deploy Seafile in a non-root domain, you need to add the following extra settings in seahub_settings.py:

**Comment by confile** [comment]
@shoeper What is a non root domain. I have home.mydomain.de. What is this?

**Comment by shoeper** [comment]
that's root domain. mydomain.de/seafile/ would be none root domain, but I wouldn't recommand that.

**Comment by confile** [comment]
I still cannot access my seafile from outside my home network.

**Comment by shoeper** [comment]
Did it work before?

**Comment by confile** [comment]
No. My problem is that I have seafile running on a RaspberryPi under a same router as my mac. Using the desktop client to sync data works fine. The problem occurs when I leave my network then I cannot access the files anymore.

**Comment by shoeper** [comment]
Have you opened port 443 in your router? Is traffic on that port being sent to your rpi? Have you setup ddns and cname record properly?

**Comment by confile** [comment]
port 443 is open: 

![fritz_box](https://cloud.githubusercontent.com/assets/64265/9028028/32b7328a-396b-11e5-98d6-b0f5b0cde61a.png)

I can upload in my browser when I use my dyndns which is like: 

```
myname.no-ip.biz:8001 
```

The upload fails when I use my other domain: 

```
home.myname.de
```

For this domain I set as you @shoeper described in an other thread the C-Name. 

For my C-Name config I set: 

Hostname: ``home.myname.de`` to target: ``myname.no-ip.biz``.


I suppose that there is some problem with my C-Name address. Although I can access and login with ``home.myname.de`` I cannot upload. 

Any idea?

**Comment by shoeper** [comment]
Have you used home.myname.de in your seafile configs?

**Comment by confile** [comment]
Which files do I have to set this in? I also use NGinx as proxy if this helps.

**Comment by shoeper** [comment]
in nginx you hostname must be home.myname.de as well.
ccnet.conf
seahub_settings.py maybe more.

**Comment by confile** [comment]
I posted my NGINX config here: https://github.com/haiwen/seafile/issues/1278 Beside the serverurl. Do oyu see any other problem? May be this is the only fault I made.

Thanks for help.

**Comment by shoeper** [comment]
Configs in that post look good.

**Comment by shoeper** [comment]
By the way: I assume you've set the right ports and use everything via port 443. It's not configured like that in the configs given in the other issue.

**Comment by confile** [comment]
@shoeper Here is my current seafile config. What did I miss?

```
server {
    listen 8001; # <--------------------------------------- NGINX PORT
    ssl on; # <-------------------------------------------- SSL

     ssl_certificate /etc/nginx/ssl/ssl-unified.crt; # <--------- SSL
     ssl_certificate_key /etc/nginx/ssl/ssl-key.key; # <----- SSL
     server_name home.myname.de; # <----------------- CHANGE THIS

    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
    server_tokens off;

    error_page 497  https://$host:$server_port$request_uri;

    location / {
        fastcgi_pass    127.0.0.1:8000;
        fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
        fastcgi_param   PATH_INFO           $fastcgi_script_name;

        fastcgi_param   SERVER_PROTOCOL $server_protocol;
        fastcgi_param   QUERY_STRING        $query_string;
        fastcgi_param   REQUEST_METHOD      $request_method;
        fastcgi_param   CONTENT_TYPE        $content_type;
        fastcgi_param   CONTENT_LENGTH      $content_length;
        fastcgi_param   SERVER_ADDR         $server_addr;
        fastcgi_param   SERVER_PORT         $server_port;
        fastcgi_param   SERVER_NAME         $server_name;
        fastcgi_param   HTTPS   on;
        fastcgi_param HTTP_SCHEME https;

        access_log      /var/log/nginx/seahub.access.log;
        error_log       /var/log/nginx/seahub.error.log;
    }
    location /seafhttp {
        rewrite ^/seafhttp(.*)$ $1 break;
        proxy_pass http://127.0.0.1:8082;
        client_max_body_size 0;
        proxy_connect_timeout  36000s;
        proxy_read_timeout  36000s;
    }

    location /media {
        root /home/seafile/seafile/seafile-server-latest/seahub; # <-- change: 2014-07-11
        # include /etc/nginx/mime.types; # <--- UNCOMMENT THIS IF CSS FILES AREN'T LOADED
    }
}
```

**Comment by shoeper** [comment]
According to that config you're using port 8001. Why are you opening port 443 in your fritz box?

**Comment by confile** [comment]
You are right I use port 8001 with SSL. So is the only port I have to open 8001 or does fast cgi needs other ports? Sorry for the stupid question I am a little bit lost here.

**Comment by shoeper** [comment]
Yeah, you need to open port 8001. Other ports are only used internally.

**Comment by confile** [comment]
Okay I checked it works. I check it event on my mobile browser when I am outside my home wlan. From 3G I could upload photos in mobile safari. Still the upload does not work in the seafile app. Maybe they do no like https or different ports.

**Comment by confile** [comment]
@shoeper acccording to my config. I use SSL on port 8001 right? Not 433?

**Comment by shoeper** [comment]
yes

Btw: You need to keep your server updated all the time when you're running it online to make it harder to hack it. Furthermore according to your screenshot above your pi is connected wireless. Why don't you connect it via wire (better performance and reliability)?

**Comment by confile** [comment]
The reason for wireless is that it will not be found in case of someone enters my flat.

**Comment by shoeper** [comment]
ok, that's a point :+1:

**Comment by confile** [comment]
:-) sure connection is stable. I still have it working very well. Thanks to your help.

**Comment by shoeper** [comment]
Does the app work, or doesn't it?

**Comment by confile** [comment]
No the ios app does not work. Download seems to be very slow and does not download everything. This is kind of buggy. 

Upload does not work. 

Note that from mobile Safari upload is no problem.

**Comment by shoeper** [comment]
Keep in mind that downloading a file can only be as fast as your upload speed of your connection at home is.

If the app still doesn't work it is likely, that something in your configs is still wrong. Let me have a look at your ccnet.conf and seahub_settings.py

**Comment by confile** [comment]
ccnet.conf : 

```
[General]
USER_NAME = home
ID = 9071234567898765c7c0d77ac8
NAME = home
SERVICE_URL = https://home.mydomain.de:8001

[Network]
PORT = 10001

[Client]
PORT = 13418
```

seahub_settings.py:
```
SECRET_KEY = "345678934567890somekey"
FILE_SERVER_ROOT = 'https://home.mydomain.de:8001/seafhttp'



EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'mymail@googlemail.com'
EMAIL_HOST_PASSWORD = 'mypw'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER


```

Is there anything you would change here?

**Comment by shoeper** [comment]
looks good to me.

**Comment by confile** [comment]
Would you add anything in to make it more secure?

**Comment by shoeper** [comment]
I'd disable SSLv3 in nginx and enable custom (more secure) ciphers + disable less secure ciphers (have a search on this, this is a topic for itself). And you should keep your system up to date. You could e.g. try to setup email notifications when there are new updates and you should check from time to time if there's a new seafile version. Keep in mind that updating is not always enough. Often some packages/services need to get restarted manual to use the updated binaries.

**Comment by confile** [comment]
> I'd disable SSLv3 in nginx and enable custom (more secure) ciphers

Do you have any point to start. Have you done this? Have you some samples?

**Comment by shoeper** [comment]
http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_protocols seems like this is properly configured by default (TLSv1.0,1.1,1.2) (but it could be that your used version is older so defining it yourself wouldn't harm but make sure expected options are used)

http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ciphers
Having a look a this http://security.stackexchange.com/questions/76993/now-that-it-is-2015-what-ssl-tls-cipher-suites-should-be-used-in-a-high-securit could be helpful. It also shows how complex it is.

You can use https://www.ssllabs.com/ssltest/ for testing, just make sure to tick the box `Do not show the results on the boards` if you don't want to have your address being published.
This document could also be quite helpful: https://www.ssllabs.com/downloads/SSL_TLS_Deployment_Best_Practices.pdf
