### ISSUE TITLE
seaf-fsck fails

### ISSUE THREAD

**Issue by Bran1** [haiwen/seafile#1333]
seaf-fsck.sh appears to have a bug.  I have been attempting to fix a corrupted library using seaf-fsck.sh -r. When I run the script, the following is reported:

<pre><code>
[07/28/15 22:40:45] fsck.c(88): Block b7fd8200f01a817658d753b201dxxxx6bd253 is missing.
[07/28/15 22:40:45] fsck.c(179): File /arree.pdf(2d7fxxed) is corrupted, recreate an empty file.
[07/28/15 22:41:11] fsck.c(304): Revert repo 90bxx593 status to commit f17fexxfb.
[07/28/15 22:41:11] fsck.c(596): Fsck finished for repo 90bxx593. </pre></code>

Running seaf-fsck.sh -sync--enable returns this:
<pre><code>
[07/29/15 08:35:45] Commit
213d5cdf1fcb13b12e03d762xxxxx14232e44f is missing  </pre></code>

I have run this series of commands approximately 10 times, but still receive the error that a commit is missing.

**Comment by killing** [comment]
Hi,

You have a few things to check:
1. Does the commit id in "fsck.c(304): Revert repo 90bxx593 status to commit f17fexxfb." matches the missing commit id? In your posted output, they're not the same. I'm not sure whether you're posting the output from the same run.
2. Do you use the same user to run the two commands? Is this user the one you use to run the seafile server? There may be permission problems.
3. Is the "missing" commit actually missing? Can you find it under seafile-data/storage/commits/repo-id/21 ?

**Comment by Bran1** [comment]
Hi.  Answers to your questions are below:

1) Yes, the output was from different runs.   

2)  The commands were both run with root.  

3) The "missing" commit is not actually missing.    

Hope this helps.  Thanks
