### ISSUE TITLE
SeaFile Windows Client 4.2.8 - Sync Overlay icons dont always show

### ISSUE THREAD

**Issue by RickoT** [haiwen/seafile#1337]
As the subject states, Sync status overlay icons are not always showing

OS : Windows 10 Enterprise
SeaFile Client : 4.2.8
SeaFile Server : 4.3.1

Please let me know what kind of logs I can provide to show you what is happening. Sometimes if I restart the client they will show up and then all disappear but mostly they dont show at all.

**Comment by ShonkyCH** [comment]
https://forum.seafile-server.org/t/windows-icon-overlays-not-working/2095

I didn't end up doing anything in particular but it started working one day and have kept work... Dunno.
