### ISSUE TITLE
复制 mp4 视频地址后, 不需要登录分享状态也能观看, 图片不会

### ISSUE THREAD

**Issue by fengqi** [haiwen/seafile#1341]
上传一个 mp4 视频
点击播放
点击右键复制视频地址
在隐身模式或其他没有登录状态的浏览器里打开能直接播放.

同样的方法测试图片会显示 `Bad access token`

**Comment by freeplant** [comment]
MP4 文件为了支持前进后退，生成的临时访问链接一个小时内有效。

**Comment by fengqi** [comment]
原来如此, 我以为是 Bug 呢.

**Comment by fengqi** [comment]
close
