### ISSUE TITLE
Client on Mac causes Finder to have high CPU utilisation

### ISSUE THREAD

**Issue by ghost** [haiwen/seafile#1345]
I recently switched from an older version of the client to version 4.2.8 and then to version 4.3.0. I think I was on version 4.2.6 before. 
The problem that is occurring is the following: 
As soon as I open Finder, navigate to my Seafile folder and Seafile is running, Finder goes up to 100% CPU utilisation or more. When I disable Seafile, everything is working fine and Finder has a normal utilisation. The high utilisation causes Finder to be very slow in responding, which makes it difficult to work with. My libraries are around 9 GB and have around 44k files, rather small.

**Comment by Kacha** [comment]
Quick update: It is the FinderSync extension. When I disable it, it works fine, but it is on by default.
