### ISSUE TITLE
Syncing problems with large directories

### ISSUE THREAD

**Issue by ulyasutay** [haiwen/seafile#1353]
I have a library on a Linux client (seafile-4.3.0-1.fc21.x86_64) synced to a server on the same box (server is generic Linux 4.3.2).  If I create a large directory in that library (around 150 files totalling 650Mb) a few of them are not uploaded.  If I delete those few files, I get a sync error, but if I resync the library and recreate them, they are uploaded correctly.
This happens with client 4.3.0 and server 4.3.1 or 4.3.2.  I did not happen with client 4.2.8 and server 4.2.2.
Please tell me what further information would be useful.

**Comment by freeplant** [comment]
It is a client side issue. See https://seacloud.cc/group/3/wiki/client-changelog/

**Comment by ulyasutay** [comment]
Thanks.  It seems to be fixed with client 4.3.3.
