### ISSUE TITLE
seaf-cli: Problem with the SSL CA Cert (path? access rights?)

### ISSUE THREAD

**Issue by novaflash** [haiwen/seafile#1360]
I'm having an issue on Debian 8 with the seaf-cli x86 (32bits) version 4.3.2 (on 32bits Debian 8).

[08/29/15 22:35:37] http-tx-mgr.c(653): libcurl failed to GET https://seafile.binair-ict.nl/seafhttp/protocol-version: Problem with the SSL CA cert (path? access rights?).
[08/29/15 22:35:37] clone-mgr.c(812): Transition clone state for 59227281 from [connect] to [connect].

It just keeps repeating this.

I've read here on the page below that a workaround needs to be applied to make it find the system's certificate store (or a copy of the necessary), but this doesn't fix the problem:
https://seacloud.cc/group/3/wiki/seafile-cli-manual/

Perhaps the paths are different again?

I have tried to start building the seaf-cli on Debian 8 but I run into a problem to retrieve the tags. I can only find up to version 3 here:
http://manual.seafile.com/build_seafile/linux.html

So that guide seems to be out of date.

Please note that my server uses a valid SSL certificate, not self-signed.
Clients on Windows and Mac work fine.

The option "seaf-cli config -k disable_verify_certificate" was set to None and I've switched it to True and restart seaf-cli, but it still produces this error.

Anyone got an idea on what I can try next?

Just wanted to add that when I installed the curl package and tried to retrieve the URL it went without a problem. All good on the SSL negotiation.

**Comment by novaflash** [comment]
Just wanted to add that when I installed the curl package and tried to retrieve the URL it went without a problem. All good on the SSL negotiation.

**Comment by novaflash** [comment]
Anyone? Some help would be greatly appreciated.

**Comment by killing** [comment]
You can try to compile the cli client. The documentation is not out of date. As noted in the documentation, you need to find the tags corresponding to the current version on github. Updating the documentation for each new version is overkill.

**Comment by novaflash** [comment]
I understand why the documentation doesn't have to get update to reflect the new version number every time, but I don't understand why I can only find version 3.0 while on the website it states version 4.something.

https://github.com/haiwen/libsearpc/tags

I can't find a version 4 there. So is version 3 released somewhere in august of 2014 truly the latest version there? How can I find version 4? Is there a version 4?
