### ISSUE TITLE
Link visits not counted properly

### ISSUE THREAD

**Issue by ShonkyCH** [haiwen/seafile#1362]
If I create a link to a file, the visits counter only counts if accessing the webpage. It also counts if refreshed.

If downloaded from that page, the count is not incremented.

If downloaded directly via the ?raw=1 link the count is not incremented.

I think the visits count for a file should count the number of times the file is actually downloaded rather than the number of times the download page is shown.

The same occurs for a shared folder but that is probably the (only) correct log of "visits"

Seafile server 4.3.2

**Comment by shoeper** [comment]
https://github.com/haiwen/seahub/issues/742

**Comment by ShonkyCH** [comment]
Ah. Searched but didn't find... You said 

"When the files is getting download with ?dl=1 via Browser it is counted as well."

However that is not correct. It does not count those downloads. It only counts loading the web page - not the actual file download after clicking on the button.

**Comment by ShonkyCH** [comment]
This still doesn't work in 4.4.1

**Comment by freeplant** [comment]
It should work in v4.4.1

**Comment by ShonkyCH** [comment]
Server version 4.4.1 CE still doesn't work 100% for me.

https://<host>/f/uid/ increments the counter. 

Clicking the download button or using the direct link (?dl=1 or ?raw=1 suffix) does work though (which didn't before) so it has been partly fixed.

Why does the link generator provide a ?raw=1 link whereas it seems ?dl=1 is used elsewhere to do the same thing including the non-direct link page when you click the Download button.

**Comment by freeplant** [comment]
?raw=1 with let the browser to open the file in the browser if possible. Use ?dl=1 will force the download.

What do not work for you now?

**Comment by ShonkyCH** [comment]
It still counts visits to the download page. Looks like github has chewed up the example link. As an example:

https://seafile.example.com/f/123456abcd/

This Increments the download counter.

It should only increment the counter when clicking the download button (i.e. a ?dl=1 or ?raw=1 link)
