### ISSUE TITLE
Updated files are deleted sometimes

### ISSUE THREAD

**Issue by opnoack** [haiwen/seafile#1365]
Seafile-Cli: seafile-cli_4.0.4_i386.tar.gz

System: Ubuntu 7.10

Expected behaviour: Files should be synced when they're updated

Actual behaviour: Files get deleted when they're updated

![2015-09-01-102141_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4449536/9599344/6ff03356-5093-11e5-8c17-09f1792bf95c.png)

Details: Both files in the picture were updated/replaced by newer versions via scp from an external source. It seems like the seafile-cli doesn't recognize the updated/new file and just pushes the deletion.

**Comment by shoeper** [comment]
Does that also happen with 4.3.2?
https://www.seafile.com/en/download/

**Comment by opnoack** [comment]
Yeah, I am not able to test the new version because of #1364.

**Comment by shoeper** [comment]
Could be related to https://github.com/haiwen/seafile-client/issues/737
