### ISSUE TITLE
Star documents in Cloud File Browser

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile#1366]
Hello,

We would consider it logical and useful to add this feature in the cloud file browser.
It would be appreciated if this would be considered.

We use the starring a lot for mobile reading of documents (star a pdf to quickly open it on the iphone when leaving the office).

I would be great being able to do that via the internal file browser,

Hope we are not the only one ;-)

KR, Chris

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/star-documents-in-cloud-file-browser/4358
