### ISSUE TITLE
seafile-pro-server-4.3.3 can't find openldap groups

### ISSUE THREAD

**Issue by gerardkok** [haiwen/seafile#1367]
During my evaluation of Seafile private server, I might have found a bug in the ldap group sync python code. A working ldap group sync feature is quite important to my organisation.

How to reproduce:
In ccnet/ccnet.conf, configure ldap. My settings:
[LDAP]
HOST = <ldap server>
BASE = <ldap suffix>
USER_DN = 
PASSWORD = 
LOGIN_ATTR = uid

[LDAP_SYNC]
SYNC_INTERVAL = 60
ENABLE_USER_SYNC = false
USER_OBJECT_CLASS = inetOrgPerson
ENABLE_GROUP_SYNC = true
GROUP_OBJECT_CLASS = posixGroup
GROUP_MEMBER_ATTR = memberUid

We use a very basic openldap server that allows anonymous binding. Although we store the email addresses in ldap, my users will be expecting to log in with their username, so I set LOGIN_ATTR to 'uid'. The 'memberUid' attribute also expects uid values. ENABLE_USER_SYNC has been set to false, otherwise I would go over the 3 license evaluation setting. I verified the ldap sync was working by importing one user through the web interface.

I then tried to sync the groups, by running ./pro/pro.py ldapsync as user 'seafile' from the 'seafile-server-latest' directory. This resulted in: [INFO] LDAP group sync result: add [0]group, update [0]group, delete [0]group (for completeness, I verified that the db table ccnet.GroupDNPair was still empty at this point, and this looked like a table that would be filled when using ldap).

After adding a few debug statements to seafile-pro-server-4.3.3/pro/python/seafevents/ldap_syncer/ldap_group_sync.py, I noticed that all groups were read from ldap, but then discarded. I think this is caused by line 99: 'mails = self.get_group_member_from_ldap(member, grp_data_ldap)', which I think should read 'mails = self.get_group_member_from_ldap(base_dn, grp_data_ldap)'. After changing this, I was able to sync our openldap groups (although this might not be the best fix) from the commandline (stdout listed all groups, the db table had entries, and the webinterface listed all of them).

Note that I couldn't find ldap_group_sync.py on github (probably because it's part of the licensed version), otherwise I would have made a pull request.

**Comment by killing** [comment]
After looking at the code, I think the reason is that the values in 'memberUid' attribute are 'uid's instead of DN. Our code only supports 'GROUP_MEMBER_ATTR' whose values are DNs. It is the case for 'member' attribute in AD and OpenLDAP. Can you change use 'member' attribute instead of 'memberUid'?
