### ISSUE TITLE
feature request: a progress bar for downloads through the website would be nice

### ISSUE THREAD

**Issue by BigAndini** [haiwen/seafile#1374]
I need to transfer large directories (2-5 GB) often. The users want to download them with the zip function, which is by the way really nice. :) It would be nicer to be able to show the users how much of their zip package was already build. Especially for users who are new to seafile and only get a download link.

With the correct proxypass settings in place the webserver is no problem anymore: 

```
ProxyPass /seafhttp http://127.0.0.1:8082 connectiontimeout=600 timeout=600
```

But the users just skip the download because the server needs the time to zip all the stuff. So the feed back I get is: Your filesharing service is not working until I'm going to get a cup of coffee, then is magically worked. :)

**Comment by iBigQ** [comment]
Requested for a long time now.
See https://github.com/haiwen/seahub/issues/267 and https://github.com/haiwen/seafile/issues/1253

Any plans for such a feature? Any kind of feedback to the user will make them actually wait for the download to start. Instead, they currently think something is broken.

**Comment by shoeper** [comment]
I agree that it would be helpful. Maybe for the first some icon indicating that there is progress with a notice that depending on the amount and size of the files the download can take several minutes to start would be enough. At a later point one could have a look at it could also be possible to add a more precise progress indicator.
