### ISSUE TITLE
Encryption password entry: Enter key opens file browser

### ISSUE THREAD

**Issue by nyanpasu64** [haiwen/seafile#1375]
When entering a password when syncing a library, pressing Enter opens the file browser window instead of submitting the dialog.

Seafile 4.3.3 on Windows 7 x64.

**Comment by lins05** [comment]
Thanks for reporting. We'll recheck and fix it.

**Comment by w0xz** [comment]
I can confirm this bug also existing in 4.4.2 on Windows 8

**Comment by shoeper** [comment]
Has it been fixed in v 4.4?

**Comment by shoeper** [comment]
On Fedora the select folder dialog is being opened, so it looks like this small usability issue is still there.
