### ISSUE TITLE
希望能增加 mov 文件的在线预览功能

### ISSUE THREAD

**Issue by fenbox** [haiwen/seafile#1377]
Android 录制的视频是 mp4 格式的，已经支持了。

而 iPhone 录制的视频都是 mov 格式，同步到 seafile 后无法直接在网页上预览，还得下载到本地再看，不是很方便，希望也能支持。

**Comment by freeplant** [comment]
We only add preview for files that native to HTML5

**Comment by chx007** [comment]
在文件存入服务器之前，应该提供文件格式转换扩展机制，让用户自行定制文件转换命令行。
这样可以满足各种文件格式的预览兼容需求。
