### ISSUE TITLE
Paths with Windows special characters breaks sync.

### ISSUE THREAD

**Issue by xelez** [haiwen/seafile#1379]
By special characters here I mean for example question mark. I don't use Windows regularly, so
maybe there are others.

So, if library has some folder with question mark it cannot be synced on Windows because seafile(well, anything) can't create paths with question marks in it. Library syncs forever and can't be unsynced (I'm not sure it's the same bug, though).

Not sure if it's a bug and how seafile must handle this situation. And I'm not sure if it must. But some error message would be nice.

**Comment by shoeper** [comment]
Normally Seafile should just not fetch those files on windows.

Does the issue still exist?

**Comment by killing** [comment]
Should has been fixed.
