### ISSUE TITLE
Move on folder with ignored files results in data loss

### ISSUE THREAD

**Issue by KenN7** [haiwen/seafile#1383]
Hi,

I just found myself in a very unconfortable situation.

Say you create a library A, synced on /home/me/A/ and a second one named B on /home/me/B/.
You add a folder to lib A named "foo" containing 2 files, "file.txt" and "file.big".

I create an ignore file containing : 
*.big

So A contains  : /home/me/A/
            /home/me/A/seafile-ignore.txt
            /home/me/A/foo/
            /home/me/A/foo/file.txt
            /home/me/A/foo/file.big

So only file.txt is synced online and you can access it on seahub, so far, it's ok.

Say now that a want to move folder "foo" to library B, without resyncing, so I go on seahub
and click on "Move" button of the webinterface.

Now the unfortunate part : 
Folder "foo" will be moved from A to B, resulting the client to delete folder "foo" in library A an,d create and sync folder "foo" on library B, problem is that "file.big" gets deleted in the process of moving ! The client deletes the moved folder from lib A without carring about ignored files !

Thanks,
Regards

**Comment by killing** [comment]
Yes this is a bug. We should check the ignore list when deleting the
content of a folder.

2015-09-16 15:59 GMT+08:00 Ken <notifications@github.com>:

**Comment by freeplant** [comment]
It is fixed in v5.0.0.
