### ISSUE TITLE
Downloading a single file from a shared folder gives 400: Invalid URL

### ISSUE THREAD

**Issue by Kaemmelot** [haiwen/seafile#1385]
When I try to share a library or a folder via Link for external users, single files cannot be downloaded, only the complete folder (using zip). When you click on "Download" or "Open in new tab" (for images) the server returns a 400: Bad Request with content "Invalid URL".
Direct download links for single files work.
Seafile Server 4.3.1 on Windows using IIS.
Any ideas? Can you reproduce this?
I could send an example via mail, if needed.

**Comment by shoeper** [comment]
Do the file names contain spaces? I think there was some problem with iis (which can be fixed by properly configuring iis).

**Comment by Kaemmelot** [comment]
Nope, no spaces.

**Comment by Kaemmelot** [comment]
Additional Information:
The URL looks like this (only domain was replaced)
https://prefix.mydomain.de/d/01d2dcf07a/files/?p=/seafile.png
web.config: http://pastebin.com/1zgwSaDT

Anyone?

**Comment by Kaemmelot** [comment]
I found my problem.
When rewriting "files/" to "seafhttp/files/" in IIS don't forget to add ^ at the beginning of the url match, preventing other urls to get rewrited.
So obvious...
