### ISSUE TITLE
Seafile doenst work after succesful installation on webfaction

### ISSUE THREAD

**Issue by OdhiamboMD** [haiwen/seafile#1388]
Hi,

I installed seafile on webfaction, "succesfully" - seafile server 4.3.2-  PROBLEM
I cant access the service over the browser via seafile.tatuweb.co.ke:8000 nor via seafile client on windows 7. What could I have missed?

my ccnet.conf is as
...........................................................................................................
[General]
USER_NAME = jayessmart
ID = d0078664c4b44959191608d224aca6a07057e403
NAME = jayessmart
SERVICE_URL = http://seafile.tatuweb.co.ke:8000
[Network]
PORT = 15406
[Client]
PORT = 13419
[Database]
ENGINE = mysql
HOST = 127.0.0.1
PORT = 3306
USER = jayessmart
PASSWD = #####
DB = ccnet_db
CONNECTION_CHARSET = utf8
...............................................................................................
.... and seafile.conf:

[fileserver]
port = 8082

[database]
type = mysql
host = 127.0.0.1
port = 3306
user = jayessmart
password = #####
db_name = seafile_db
connection_charset = utf8

[network]
port = 25124

[httpserver]
port = 25600
max_upload_size=500
max_download_dir_size=500

**Comment by shoeper** [comment]
Http_server_root or file_server_root is missing. Furthermore I highly recommend to enable TLS (with nginx).

See http://manual.seafile.com for details.

**Comment by OdhiamboMD** [comment]
Sorted this out by running a totally new installation, opening a port on webfaction which I used as substitute for port 8000 on the ccnet.conf SERVER_URL part.
Thanks
