### ISSUE TITLE
Seafile does not upload files, both from client or browser

### ISSUE THREAD

**Issue by OdhiamboMD** [haiwen/seafile#1390]
I can see and log into the web interface pretty well. That's about all. Running it on plain installation over webfaction.
seafile logs on client gives error as below

[09/30/15 11:42:26] http-tx-mgr.c(653): libcurl failed to GET http://seafile.tatuweb.co.ke:8082/protocol-version: Couldn't connect to server.
[09/30/15 11:42:26] clone-mgr.c(812): Transition clone state for 50b6b0cf from [connect] to [connect].
[09/30/15 11:42:30] http-tx-mgr.c(1051): Bad response code for GET http://seafile.tatuweb.co.ke/seafhttp/protocol-version: 404. 

... and my seahub_setttings.py.conf looks as below...

SECRET_KEY = "876372d7-db88-45e1-ab85-62cf168b261e3603"
DATABASES = {
		'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'seahub_db',
                'USER': '******',
		'PASSWORD': '********',
		'HOST': '127.0.0.1',
		'PORT': '3306',
		'OPTIONS': {
                'init_command': 'SET storage_engine=INNODB',
		}
     	}
}
FILE_SERVER_ROOT= 'http://seafile.tatuweb.co.ke/seafhttp'
HTTP_SERVER_ROOT = 'http://seafile.tatuweb.co.ke/seafhttp'

And my seafile.conf looks like this

[fileserver]
port = 8082
[database]
type = mysql
host = 127.0.0.1
port = 3306
user = tttttttt
password = rrrrrr
db_name = seafile_db
connection_charset = utf8

Thanks Guys

**Comment by freeplant** [comment]
Ask usage and config problem in the forum.

**Comment by OdhiamboMD** [comment]
Thanks.

I managed to sort it out.

Kind Regards.

On Mon, Oct 12, 2015 at 7:23 AM, Daniel Pan <notifications@github.com>
wrote:

> Ask usage and config problem in the forum.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haiwen/seafile/issues/1390#issuecomment-147289482>.
>



-- 
Regards,
Michael D. Odhiambo
Team Leader/ Founder, Tatuweb Media.

The common sense approach.
