### ISSUE TITLE
Share file with password doesn't work

### ISSUE THREAD

**Issue by dszymczuk** [haiwen/seafile#1392]
When I set password for PDF file, I can download this file **without** using password. :bug: 

When I set password for folder with this PDF, I have to fill password to enter to folder.

**Comment by shoeper** [comment]
> When I set password for PDF file, I can download this file without using password. :bug:
can't confirm this using Seafile Pro 4.3.3.

**Comment by freeplant** [comment]
This is surely not a bug. You can ask usage related questions in the Seafile forum.
