### ISSUE TITLE
how to run the seafile-server tests

### ISSUE THREAD

**Issue by akumria** [haiwen/seafile#1393]
Hi,

I am building the seafile server suite on an armhf machine, and I wanted to confirm that the the system had passed it's own self-tests.

How exactly do I run the tests in the 'tests' directory? 'make check' builds most of the binaries.

Thanks,
Anand

**Comment by freeplant** [comment]
For questions, go to the Seafile forum.

**Comment by akumria** [comment]
Well, considering that 'make check' results in a compilation error I believed it would be something you'd want to know here on github.

I wrote the question because I wasn't sure if:

 * 'make check' was the supported method
 * The documentation should be modified (via seafile-docs)
 * Or you'd like a PR with the fixes to the checking code.

**Comment by freeplant** [comment]
We don't use `make check` for running testing since a long time ago. We use Travis-CI to perform an integrated test with Seahub now.
