### ISSUE TITLE
Seafile Server CE 4.3.1 does not start seafserv-applet.exe when a Windows Service

### ISSUE THREAD

**Issue by sainokawara** [haiwen/seafile#1394]
After installing Seafile Server 4.3.1 as a Windows Service, "seafserv-applet.exe" does not automatically start at Windows Login.  It can be started manually but it would be much better if it were just started automatically at Login using the Windows Task Scheduler.  The only critical specification is to make certain that "Run with highest privileges" is checked when defined.  So, as one software engineer to another, does that make this a "Documentation Fix"?

Personal opinion: Other than that, a nice product.  I still believe that you are missing a potential business opportunity with Windows especially with the proliferation of Android Phones & Tablets.  In my opinion, with minor documentation improvements, home and small business users could easily install & maintain a Seafile Server with SQLlite on their Windows system accessible only from their Intranet using static IP addresses so they do not have to configure DHCP or DNS servers.  Perhaps, I overrate their technical ability and even with clear, well tested installation documentation they couldn't?  But if they could, they would love being able to "transfer" files so easily between their Windows & Android devices!  Of course, I was never in marketing so may be missing the big picture.

**Comment by shoeper** [comment]
Documentation improvements are always welcome at https://github.com/haiwen/seafile-docs/issues

I close this as I don't think there is a problem with the software itself.
