### ISSUE TITLE
Use systems default web proxy

### ISSUE THREAD

**Issue by dbeuchler** [haiwen/seafile#1395]
Hello together, im using the seafile client behind several web proxies. MacOS provides the option to set locations to update network settings which are needed for the location. 

Is it possible that the seafile client can use the systems configured proxy?

**Comment by killing** [comment]
Nope, it's not supported right now. May be we'll add this feature later.

**Comment by dbeuchler** [comment]
It would be nice if you can implement that feature. For the first time it would be helpful if the client will not lose the settings when i'm selecting "none" and go back to HTTP.

**Comment by erenoglu** [comment]
+1 for this. I'm taking my notebook to work and back home. Can't sync when I'm at work as each time it requires proxy adjustment. 

Even if you could provide a programmatical way to do it, I could run a script each time proxy changes. (Ie to seaf-applet.exe  - - set-proxy=....)

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/use-system-proxy-as-mostly-you-dont-know-the-proxy-address/2321
