### ISSUE TITLE
Changing certificate on server breaks client sync (linux)

### ISSUE THREAD

**Issue by draptik** [haiwen/seafile#1396]
After changing the ssl certificate from 'self signed' to a certificate from 'starttsl' some of my libraries will not sync with my client anymore.

Note: Some libraries sync ok, some others do not.

From the logs (seafile.log) on the client:

```
http-tx-mgr.c(653): libcurl failed to GET https://FOO:8001/seafhttp/protocol-version: Peer certificate cannot be authenticated with given CA certificates.
```

I don't understand why some libraries sync just fine and others complain about the certificate.

I have reinstalled seafile client (removing all config stuff by deleting the folders `~/.ccnet` and  `Seafile`). Did not help.

Is my seafile server corrupted? How would I go about finding out what is wrong?

Thankful for any pointers

Patrick

Setup: 
Server RPi (seafile 4.3.2) behind nginx
Client Arch (seafile 4.3.4)

**Comment by shoeper** [comment]
Although I think you did because some libraries do work, have you included the intermediate certificate (s)?

**Comment by draptik** [comment]
Yes, I included the intermediate certificate. But thanks for the pointer.

**Comment by shoeper** [comment]
Have some libraries been created before v 3.x (those that don't work)?

**Comment by shoeper** [comment]
Similar issues:
https://forum.seafile-server.org/t/solved-problem-sync-does-not-work-anymore-windows-client-4-1-4/1123?u=shoeper

https://forum.seafile-server.org/t/solved-client-sync-stopped-working/2151/3?u=shoeper

https://forum.seafile-server.org/t/ssl-connect-error-using-custom-ca/1342/7?u=shoeper

**Comment by draptik** [comment]
*All* libraries were created initially with version 2.1... (back then I even wrote a short article on my [blog](http://draptik.github.io/blog/2014/04/21/installing-seafile-on-raspberry-pi/))

Thanks for the links.

Yes, disabling the cert check in the client works, but as soon as I activate the cert check again I have the original scenario.

The last [link](https://forum.seafile-server.org/t/ssl-connect-error-using-custom-ca/1342/7?u=shoeper) has some info that I have not tried yet (libcurl). Thank you, I will try that tomorrow.

**Comment by draptik** [comment]
After excluding everything else, I had a closer look at the certificate again. It turned out that I placed the wrong file (without the intermediate certificates) in the `/etc/nginx/ssl/` folder.

So, @shoeper Thanks for pointing me in the right direction right from the start!

I am still surprised that some libraries synced just fine, and other did not...
