### ISSUE TITLE
[Android Client] Add feature to choose which files stay on device

### ISSUE THREAD

**Issue by jnwatts** [haiwen/seafile#1399]
# Feature Request
I would like (and have begun trying to hack) the client **not** to keep (some) of my files stored on my device. Particularly for encrypted libraries. I have sensitive information that I'd like reachable from a few places (my Android device, home and work desktops) but I don't want the sensitive information to *remain* on the machine after I close the Seafile client, but while it is open I expect that I can open the file from the client.

# Examples
For examples of how other services provide this feature, look at DropBox's mobile clients which uses a "pinned" state for individual files/folders to keep them on the mobile device. Wuala (prior to closing) used to do this for all files accessed: All files were downloaded on-the-fly and cleaned up after exiting.

Another possible facet of this feature might be to provide a lock/unlock state for encrypted libraries: Upon entering the locked state any "un-pinned" files are cleared from the device's storage.

(If I missed an existing feature request that overlaps with this, please let me know: I searched for ~15 min but couldn't find one)

**Comment by shoeper** [comment]
The only way to get what you want is to encrypt your phone. Everything else is insecure.

**Comment by jnwatts** [comment]
Yep, I'm aware of that: I accept the level of risk, and am just trying to limit the attack surface as much as I can.

For other people, this might have other uses too. Perhaps for space-constrained devices?

**Comment by shoeper** [comment]
The cache can get removed in the settings.
Btw. the android apps issues are located at https://github.com/haiwen/seadroid/issues

**Comment by jnwatts** [comment]
Oops! I saw other android client posting here, hadn't yet gotten to looking at the source. I'll close this and move it to seadroid.
