### ISSUE TITLE
listDirectoryEntries recursive files

### ISSUE THREAD

**Issue by CCosmo** [haiwen/seafile#1402]
Currently its only possible to list recursive folders with Filter "d" ans recursive=1.

It would ne nice when it is possible with Filter "f" and recursive=1 to get all files recursive (the folder names are in json properties too).

**Comment by shoeper** [comment]
http://manual.seafile.com/develop/web_api.html#list-directory-entries

**Comment by CCosmo** [comment]
There is nothing changed? And what i want is not possible when i look at the dokumentarion link.

**Comment by CCosmo** [comment]
recursive (optional): If set  t  argument as  d  AND  recursive  argument as  1 , return all dir entries recursively

Thats the text in documentation. 
What i want is Parameter t = f AND recursive = 1

**Comment by freeplant** [comment]
The feature is already added.
