### ISSUE TITLE
ccnet/mysql: underscore in database hostname raises sql exception

### ISSUE THREAD

**Issue by basti1253** [haiwen/seafile#1403]
Somewhat related to #336

I'm about automating the process of setting up seafile into a docker container. Here's the setup:
https://github.com/shoifele/seafile

If I change the db hostname from "db" to "seafile_db_1" (both valid if repo is checked out to a directory called seafile) ccnet breaks.

`failed to run "ccnet-server -t"
SQLException: Failed to start connection pool -- no database specified in URL
 raised in ConnectionPool_start at src/db/ConnectionPool.c:287`

best regards

**Comment by basti1253** [comment]
In case you have docker installed it's very easy to reproduce the error:

- clone the repository
- change https://github.com/shoifele/seafile/blob/master/docker-compose.yml#L17 to `SEAFILE_DB_HOST: seafile_db_1`
- run `make dev`
- follow logs with `docker logs -f seafile_seafile_1`

**Comment by lins05** [comment]
Seems underscore is illegal in hostnames, as someone pointed out in
http://stackoverflow.com/a/2183140/1467959 . And it's exactly how libzdb,
the database library used by ccnet/seafile, parses the hostname.

https://github.com/haiwen/libzdb/blob/a3e0dfaf4fb5bbc717e87a107d15fb67a433bcf2/src/net/URL.re#L109

**Comment by basti1253** [comment]
mea culpa. thanks for your fast response
