### ISSUE TITLE
client cannot open on OS X 10.11

### ISSUE THREAD

**Issue by maplewizard** [haiwen/seafile#1404]
I updated OS X to 10.11 and seafile cannot open. Is this often occur on OS X10.11?

**Comment by lins05** [comment]
I'm using 10.11 and seafile client works fine.

So nothing happened when you tried to launch seafile client? Can you paste
the log files in ~/.ccnet/logs/ ?

btw how do you launch seafile client? By clicking the seafile dock icon, or
in spotlight?

**Comment by maplewizard** [comment]
It seems that the gui encontered some problem. seafile itself works well, but when I clicked on my avatar, a menu appeared but when I move mouse a little, it disappeared. What's more the information dialog cannot be editted, I can only paste strings into it.
