### ISSUE TITLE
(initial) sync of many small files is slow (when using ceph backend)

### ISSUE THREAD

**Issue by egroeper** [haiwen/seafile#1406]
On a test run we synced a library with 100.000 10K files in a Seafile Pro cluster with ceph backend.
1/3 of the time was spent in "recv-fs" requests.

Looking at "post_recv_fs_cb" in http-server.c it seems to me, that the http-server receives all fs objects in a single byte stream and sequentially puts them into the object store (waiting for each write to finish).

I think we could get quite some performance improvement, if the http-server would write the fs objects asynchronously in parallel into the object store (and would wait for the writes to finish at the end of the call).

What do you think about this?

**Comment by shoeper** [comment]
It could also be helpful (if not possible so far) to add a bulk request for the client. E.g. instead of requesting blocks one by one the clients request 100 small blocks and get them with a single request.

**Comment by killing** [comment]
@egroeper I think this is a good idea. We'll try to use multiple threads to write to fs objects to the backend.
@shoeper The client already uses multiple threads to upload blocks. So there is no need to package blocks into one request.

**Comment by shoeper** [comment]
I'm not sure if that's the same. E.g. mysql allows to insert multiple values at the same time and I have in mind that it is much faster to make one query inserting 10000 values than making 10000 queries. But that depends on how much overhead per request there is.

**Comment by StefanKrauth** [comment]
I just want to throw a "+1" in here. I'm synchronizing an rdiff-backup folder using seafile. This is basically a whole linux file system plus metadata and versions. At the moment it's 133 GB in 803867 files. I saw in the change log that you have reduced the thread count. Would it make sense to make this configurable in the server config file? A speed bump for such libraries would be very welcomed, as the solution works pretty nice.

**Comment by freeplant** [comment]
The problem should have been solved with pro v5.0.4. If you still have the problem, leave a comment here.
