### ISSUE TITLE
seafile 4.4.3 web ui / seadroid download times out

### ISSUE THREAD

**Issue by monochromec** [haiwen/seafile#1407]
Hi there:

When installing version 4.4.3 on trusty (compiling from sources), I can't get the Web UI to work in terms of downloading a file. I get as far as the download button and then browser times out. Same goes for Seadroid clients (progress bar stalls at 0%). The configuration an nginx reverse proxy; configured as outlined in the manual. Please find the relevant files below (sensitive information being replaced with <...>); please let me know if you need more information. BTW: The same issue occurs on a 4.4.1 version of the server. Downloading / synchronisation via native Linux / Windows applets works fine.

access.log:

```
192.168.2.1 - - [16/Oct/2015:17:06:35 +0200] "GET /media/img/favicon.png?t=1398068110 HTTP/1.1" 200 3222 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/css/seahub.css?t=1398068110 HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/assets/css/select2-3.5.2.css HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/assets/css/backbone.css HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/assets/css/magnific-popup.css HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/favicon.png?t=1398068110 HTTP/1.1" 200 3222 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/loading-icon.gif HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/bell.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/seafile_logo.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/del.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/assets/scripts/i18n/en/djangojs.js HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/assets/scripts/lib/require.js HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/loading-new.gif HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/add.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/avatars/default.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/nav.png HTTP/1.1" 304 0 "https://<TLD>/media/css/seahub.css?t=1398068110" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/minus.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/close.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/assets/scripts/dist/main.js HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/bg.png HTTP/1.1" 304 0 "https://<TLD>/media/css/seahub.css?t=1398068110" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/setting.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/delete-orange.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/share-orange.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /media/img/sync-folder-20.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:18 +0200] "GET /media/img/file/file.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:18 +0200] "GET /media/img/more_op.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:18 +0200] "GET /media/img/download-orange.png HTTP/1.1" 304 0 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:18 +0200] "GET /media/img/multi-repo-op.png HTTP/1.1" 304 0 "https://<TLD>/media/css/seahub.css?t=1398068110" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:21 +0200] "GET /media/js/jq.min.js?t=1398068110 HTTP/1.1" 304 0 "https://<TLD>/lib/78d226c5-db07-4ebe-83fc-67c44a9ab3f3/file/freiesMagazin-2014-09-bilder.epub" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:21 +0200] "GET /media/css/seahub.css?t=1398068110 HTTP/1.1" 304 0 "https://<TLD>/lib/78d226c5-db07-4ebe-83fc-67c44a9ab3f3/file/freiesMagazin-2014-09-bilder.epub" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:21 +0200] "GET /media/js/base.js?t=1404370380 HTTP/1.1" 304 0 "https://<TLD>/lib/78d226c5-db07-4ebe-83fc-67c44a9ab3f3/file/freiesMagazin-2014-09-bilder.epub" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:21 +0200] "GET /media/img/favicon.png?t=1398068110 HTTP/1.1" 200 3222 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:58 +0200] "GET /seafhttp/files/a238c60b-5326-4510-bb8e-cce947ff94a5/freiesMagazin-2014-09-bilder.epub HTTP/1.1" 504 191 "https://<TLD>/lib/78d226c5-db07-4ebe-83fc-67c44a9ab3f3/file/freiesMagazin-2014-09-bilder.epub" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
```

error.log:
```
2015/10/16 17:07:58 [error] 7865#0: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.2.1, server: <TLD>, request: "GET /seafhttp/files/a238c60b-5326-4510-bb8e-cce947ff94a5/freiesMagazin-2014-09-bilder.epub HTTP/1.1", upstream: "http://127.0.0.1:8082/files/a238c60b-5326-4510-bb8e-cce947ff94a5/freiesMagazin-2014-09-bilder.epub", host: "<TLD>", referrer: "https://<TLD>/lib/78d226c5-db07-4ebe-83fc-67c44a9ab3f3/file/freiesMagazin-2014-09-bilder.epub"
```
nginx.conf:
```
user www-data;
worker_processes 2;
#pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

server {
    listen 80;
    server_name <TLD>;
    rewrite ^ https://$http_host$request_uri? permanent;    # force redirect http to https
}

server {
     listen 443;
     ssl on;
     ssl_certificate /etc/ssl/sfcacert.pem;        # path to your cacert.pem
     ssl_certificate_key /etc/ssl/sfprivkey.pem;    # path to your privkey.pem

    server_name <TLD>;
     
    proxy_set_header X-Forwarded-For $remote_addr;

    location / {
        fastcgi_pass    127.0.0.1:8000;
        fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
        fastcgi_param   PATH_INFO           $fastcgi_script_name;

        fastcgi_param    SERVER_PROTOCOL        $server_protocol;
        fastcgi_param   QUERY_STRING        $query_string;
        fastcgi_param   REQUEST_METHOD      $request_method;
        fastcgi_param   CONTENT_TYPE        $content_type;
        fastcgi_param   CONTENT_LENGTH      $content_length;
        fastcgi_param    SERVER_ADDR         $server_addr;
        fastcgi_param    SERVER_PORT         $server_port;
        fastcgi_param    SERVER_NAME         $server_name;
        fastcgi_param   REMOTE_ADDR         $remote_addr;
	fastcgi_param   HTTPS               on;
        fastcgi_param   HTTP_SCHEME         https;
        
	access_log      /var/log/nginx/seahub.access.log;
        error_log       /var/log/nginx/seahub.error.log;
    }

    location /seafhttp {
        rewrite ^/seafhttp(.*)$ $1 break;
        proxy_pass http://127.0.0.1:8082;
        client_max_body_size 0;
        proxy_connect_timeout  36000s;
        proxy_read_timeout  36000s;
        proxy_send_timeout  36000s;
    }

    location /media {
        root /mnt/disk/home/seafile/<TLD>/seafile-server/seahub;
    }
 }
}
```
seahub_settings.py:
```
SECRET_KEY = '<KEY>'
FILE_SERVER_ROOT = 'https://<TLD>/seafhttp
```

seahub.access.log: 
```
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET / HTTP/1.1" 200 62115 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:16 +0200] "GET /api2/repos/?type=mine&_=1445008036717 HTTP/1.1" 200 929 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:18 +0200] "GET /ajax/lib/78d226c5-db07-4ebe-83fc-67c44a9ab3f3/dir/?p=%2F&_=1445008036718 HTTP/1.1" 200 551 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:18 +0200] "GET /ajax/unseen-notices-count/?_=1445008036716 HTTP/1.1" 200 22 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:19 +0200] "GET /ajax/unseen-notices-count/?_=1445006809813 HTTP/1.1" 200 22 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:21 +0200] "GET /lib/78d226c5-db07-4ebe-83fc-67c44a9ab3f3/file/freiesMagazin-2014-09-bilder.epub HTTP/1.1" 200 38921 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:21 +0200] "GET /ajax/contacts/?_=1445008041683 HTTP/1.1" 200 27 "https://<TLD>/lib/78d226c5-db07-4ebe-83fc-67c44a9ab3f3/file/freiesMagazin-2014-09-bilder.epub" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:22 +0200] "GET /repo/78d226c5-db07-4ebe-83fc-67c44a9ab3f3/01bdf12239df301446920bfa34ef64c1e1396232/download/?p=/freiesMagazin-2014-09-bilder.epub HTTP/1.1" 302 5 "https://<TLD>/lib/78d226c5-db07-4ebe-83fc-67c44a9ab3f3/file/freiesMagazin-2014-09-bilder.epub" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:46 +0200] "GET /ajax/unseen-notices-count/?_=1445008036719 HTTP/1.1" 200 22 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:07:49 +0200] "GET /ajax/unseen-notices-count/?_=1445006809814 HTTP/1.1" 200 22 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:08:16 +0200] "GET /ajax/unseen-notices-count/?_=1445008036720 HTTP/1.1" 200 22 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:08:19 +0200] "GET /ajax/unseen-notices-count/?_=1445006809815 HTTP/1.1" 200 22 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:08:46 +0200] "GET /ajax/unseen-notices-count/?_=1445008036721 HTTP/1.1" 200 22 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
192.168.2.1 - - [16/Oct/2015:17:08:49 +0200] "GET /ajax/unseen-notices-count/?_=1445006809816 HTTP/1.1" 200 22 "https://<TLD>/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
```

**Comment by shoeper** [comment]
It would be helpful if you could put your logs and configs within three ` at the beginning and end to show them like code is.

A timeout with having these values in the config at the same time is interesting

```    proxy_connect_timeout  36000s;
    proxy_read_timeout  36000s;
    proxy_send_timeout  36000s;```

Maybe we've missed some timeout that is being hit instead. (504 = gateway timeout). Is there something in the Seafile server logs and do the Desktop clients?

**Comment by monochromec** [comment]
Updated the log / code information as requested. The timeouts are verbatim from the nginx config file in the manual. Gateway timeouts occur regardless of the actual timeout settings in the nginx configuration - it seems that the server doesn't send the data back to nginx and nginx is thus timing out. The server log doesn't contain any hints in that regard. Desktop clients work ok as indicated in the original description but seadroid downloads stall at 0 kb.

**Comment by monochromec** [comment]
Any updates on this? Feedback would be greatly appreciated as mobile clients are not working at all! More than happy to provide more information as required.

**Comment by shoeper** [comment]
Is there anything in the Seafile logs for this time [16/Oct/2015:17:07:58 +0200] (those in /seafile-root/logs)?

And could you run seaf-fsck (see manual.seafile.com).

**Comment by monochromec** [comment]
Hi Scott,
Here you go.
seafile.log:
'''
[10/16/15 17:22:45] ccnet_init: Connect to ccnet daemon error
[10/16/15 17:22:55] ccnet_init: Connect to ccnet daemon error
[10/16/15 17:23:05] ccnet_init: Connect to ccnet daemon error
[10/16/15 17:23:15] ccnet_init: Connect to ccnet daemon error
[10/16/15 17:23:34] ../common/mq-mgr.c(60): [mq client] mq cilent is started
[10/16/15 17:23:34] ../common/mq-mgr.c(106): [mq mgr] publish to hearbeat mq: seaf_server.heartbeat
'''
ccnet.log:
'''
[10/16/15 17:23:33] ../common/session.c(436): socket file exists, delete it anyway
[10/16/15 17:23:33] ../common/session.c(465): Listen on /mnt/disk/home/seafile/sfnaswobj32.monochromec.com/ccnet/ccnet.sock for local clients
[10/16/15 17:23:33] ../common/session.c(271): Update pubinfo file
[10/16/15 17:23:34] ../common/session.c(379): Accepted a local client
[10/16/15 17:23:34] ../common/session.c(379): Accepted a local client
[10/16/15 17:23:34] ../common/session.c(379): Accepted a local client
[10/16/15 17:23:34] ../common/session.c(379): Accepted a local client
[10/16/15 17:23:39] ../common/session.c(379): Accepted a local client
[10/16/15 17:24:15] ../common/session.c(379): Accepted a local client
[10/16/15 17:24:15] ../common/session.c(379): Accepted a local client
[10/16/15 17:24:16] ../common/session.c(379): Accepted a local client
[10/16/15 17:24:16] ../common/session.c(379): Accepted a local client
[10/16/15 17:24:16] ../common/peer.c(943): Local peer down
[10/16/15 17:24:16] ../common/peer.c(943): Local peer down
[10/16/15 18:31:42] ../common/session.c(379): Accepted a local client
[10/16/15 18:31:59] ../common/session.c(379): Accepted a local client
[10/16/15 18:32:03] ../common/session.c(379): Accepted a local client
[10/16/15 19:32:21] ../common/session.c(379): Accepted a local client
[10/16/15 19:37:20] ../common/session.c(379): Accepted a local client
'''
[10/16/15 17:23:33] seafile-controller.c(154): starting ccnet-server ...
[10/16/15 17:23:33] seafile-controller.c(73): spawn_process: ccnet-server -c /mnt/disk/home/seafile/<TLD>/ccnet -f /mnt/disk/home/seafile/<TLD>/logs/ccnet.log -d -P /mnt/disk/home/seafile/<TLD>/seafile-data/pids/ccnet.pid
[10/16/15 17:23:33] seafile-controller.c(88): spawned ccnet-server, pid 8316
[10/16/15 17:23:34] seafile-controller.c(557): ccnet daemon connected.
[10/16/15 17:23:34] seafile-controller.c(185): starting seaf-server ...
[10/16/15 17:23:34] seafile-controller.c(73): spawn_process: seaf-server -c /mnt/disk/home/seafile/<TLD>/ccnet -d /mnt/disk/home/seafile/<TLD>/seafile-data -l /mnt/disk/home/seafile/<TLD>/logs/seafile.log -P /mnt/disk/home/seafile/<TLD>/seafile-data/pids/seaf-server.pid
[10/16/15 17:23:34] seafile-controller.c(88): spawned seaf-server, pid 8319
[10/16/15 17:23:34] seafile-controller.c(530): seafdav not enabled.
'''
seaf-fsck output is inconclusive as there doesn't seem a problem with data storage on the server side:

'''
[10/24/15 09:09:00] fsck.c(548): Running fsck for repo c0fe6d2e-02a2-4302-90a5-dd0bb5cb5758.
[10/24/15 09:09:00] fsck.c(409): Checking file system integrity of repo seafile(c0fe6d2e)...
[10/24/15 09:09:00] fsck.c(612): Fsck finished for repo c0fe6d2e.

[10/24/15 09:09:00] fsck.c(548): Running fsck for repo 761ea93f-2cd4-435f-8bc5-20284edd15f4.
[10/24/15 09:09:00] fsck.c(409): Checking file system integrity of repo My Library(761ea93f)...
[10/24/15 09:09:00] fsck.c(612): Fsck finished for repo 761ea93f.

[10/24/15 09:09:00] fsck.c(548): Running fsck for repo 6f2af569-6c22-4592-96e5-d5525e2a9f4c.
[10/24/15 09:09:00] fsck.c(409): Checking file system integrity of repo seafile(6f2af569)...
[10/24/15 09:15:17] fsck.c(612): Fsck finished for repo 6f2af569.

[10/24/15 09:15:17] fsck.c(548): Running fsck for repo db273a2d-4876-434e-9981-5868e3ad32cd.
[10/24/15 09:15:17] fsck.c(409): Checking file system integrity of repo My Library(db273a2d)...
[10/24/15 09:15:17] fsck.c(612): Fsck finished for repo db273a2d.

[10/24/15 09:15:17] fsck.c(548): Running fsck for repo 99addf15-0e0a-407d-9b0f-c2be0cff94fb.
[10/24/15 09:15:17] fsck.c(409): Checking file system integrity of repo My Library(99addf15)...
[10/24/15 09:15:17] fsck.c(612): Fsck finished for repo 99addf15.

[10/24/15 09:15:17] fsck.c(548): Running fsck for repo df8ec7ad-5d16-4f63-aa70-89d34ccdd68f.
[10/24/15 09:15:17] fsck.c(409): Checking file system integrity of repo My Library Template(df8ec7ad)...
[10/24/15 09:15:17] fsck.c(612): Fsck finished for repo df8ec7ad.
'''
Please let me know if you need more information.

**Comment by arudat** [comment]
hi,

I have the same problem, it starts with server 4.4.0 for me, but still the same with 4.4.3 and I have NO log entries which I could post. With Linux Desktop Client all is fine just android stucks.

Thanks

**Comment by shoeper** [comment]
Desktop Client and Web/mobile clients work different. It is very likely a configuration issue.

**Comment by arudat** [comment]
you mean it could be really a nginx problem?

**Comment by shoeper** [comment]
A configuration issue. It does not mean that there is necessarily a nginx problem.

**Comment by monochromec** [comment]
So how do we track down the culprit given that the log information isn't that conclusive? How can we pinpoint the exact source of the issue when even DEBUG=True in the seahub configuration doesn't yield something useful? Or am I missing something?

**Comment by shoeper** [comment]
Everything I can recommend is to carefully check if everything is setup as described at manual.seafile.com

**Comment by monochromec** [comment]
Yes it has (cf., for example, the configuration of nginx). More comprehensive logging would probably solve the problem or at least give an indication to where the problem lies. At the moment, this software in this particular configuration is not usable. Apparently this has been a known issue since version 4.4.0 (cf. Arudat's post above). 

It would be great if somebody upstream could provide feedback of how to exactly pinpoint the problem bar analysing the code yourself.

**Comment by monochromec** [comment]
I find this lack of progress disconcerting. More support would mean a better acceptance of the software in general and a speedier issue resolution process in particular. :-(

**Comment by freeplant** [comment]
I can't find obvious reason for the problem. We'd like to help, but with limited man power, we can't support problems occurred when compiling from source code.

When Nginx receive the download request, it should pass the quest to seaf-server, from the Nginx log, the seaf-server does not give a respone.

```
192.168.2.1 - - [16/Oct/2015:17:07:58 +0200] "GET /seafhttp/files/a238c60b-5326-4510-bb8e-cce947ff94a5/freiesMagazin-2014-09-bilder.epub HTTP/1.1" 504 191 "https://<TLD>/lib/78d226c5-db07-4ebe-83fc-67c44a9ab3f3/file/freiesMagazin-2014-09-bilder.epub" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0 SeaMonkey/2.38"
```

The time of Nginx log is 17:07. Are there any log for seaf-server (in seafile.log) at this time? Does your seaf-server listen on port 8082?

**Comment by monochromec** [comment]
I triple-checked the config so all components are listening as they should be. I posted all log entries as requested. It was my interpretation as well that the seafile server does not return a response to nginx so the reverse proxy will eventually time out (that's exactly what's happening). 

In order to pinpoint the problem, more comprehensive logs entries as part of a future code release would be helpful; allowing a more detailed analysis why seaf-server doesn't return content to the nginx instance.

**Comment by Captain-Rage** [comment]
I've had Seafile up and running on a Raspberry Pi for a very long time without any noticable problems. Yesterday I discovered this problem on my system (a few weeks ago I am sure that downloading files through a browser was possible but not it's not and neither does the Android client work). The system is using nginx, Arch Linux ARM and Seafile 4.4.2 (compiled using Arch Linux's AUR).
Probably this occurred after some system update without getting noticed until now. I haven't fiddled around with any nginx or Seafile settings for the longest of time, however, so that's an unlikely cause of the issue.
When I get some time later on I can try to go through older logs. Other than that I'm not sure where to start troubleshooting. If you want me to post any specific logs, please write it here. For more info see:

https://forum.seafile-server.org/t/504-error-from-nginx-1-80-suddenly-appeared-for-seafile/3462/7

PS.
Changing the proxy timeout values in the seafhttp section in the seahub configuration file for nginx didn't change anything for me.

**Comment by Almin17** [comment]
Same as for user Captain-Rage goes for me.
I also have the issue and commented in the thread of the forum.
Seems to be something that started with 4.4 :( 
Solution would be greatly appreciated.

**Comment by mihav** [comment]
This is happening to me too. It started with 4.4.x on Arch linux (AUR PKGBUILDs). Also doesn't work with latest 5.0.3. I tried debugging it a bit further, but log files show nothing relevant even with debug mode enabled. Also doesn't work with new installs. I also tried installing fresh instance without nginx reverse proxy in front, but doesn't help - browser establishes connection, but then seaf-server simply doesn't send back anything over port 8082 when I try to download a file and connection eventually timeouts.

**Comment by freeplant** [comment]
What libevhtp version do you use? It is likely to be the problem of libevhtp.

**Comment by edacval** [comment]
Problem is with  libevhtp version >= 1.2.10. With 1.2.9 works as expected.

**Comment by mihav** [comment]
Yep. Works with libevhtp 1.2.9.
