### ISSUE TITLE
documentation about ignore.txt

### ISSUE THREAD

**Issue by Alukardd** [haiwen/seafile#1408]
On the page about ignore feature (https://www.seafile.com/en/help/ignore/) there is two different ignore filename: `seafile-ignore.txt` and `ignore.txt`
For me works only `ignore.txt`.
GNU/Linux Seafile Client 4.4.0

**Comment by killing** [comment]
It should be seafile-ignore.txt.

**Comment by Alukardd** [comment]
I don't know what name the **should** have, but as I said for me works only ```ignore.txt```
