### ISSUE TITLE
Merge conflicts pollute file tree, discard local state, and prevent manual merging

### ISSUE THREAD

**Issue by jimbo1qaz** [haiwen/seafile#1410]
When a merge conflict is encountered, Seafile destroys the local state. Instead, it syncs down all modified files from the server and renames all conflicting local files.

This makes it completely impossible to automatically restore to the old local state, because file names have changed.

It is also very difficult to restore a client to the old server state, as the history interface discards the local branch merged in, and provides no indication of which commits are conflicts.

These bugs together make it extremely difficult to recover after a failed merge. The local state is silently destroyed upon a failed merge, and all conflict files are renamed (hundreds or thousands to fix by hand). This makes it nearly impossible to restore local state, rather than server state, after a botched merge. Doing so requires manually scanning through and renaming HUNDREDS or THOUSANDS of files by hand.

The proper solution is to push the local branch to the server, then explicitly mark the merge commit, like Git.

A workaround is to push the previous local state to the server as a backup commit, while still performing a normal merge between previous server and local. This will make it possible to manually merge the two folder trees using a legitimate diff tool, rather than Seafile's butchery.

**Comment by jimbo1qaz** [comment]
bump

This is still a devastating issue!

Another alternative is to warn the user on merge conflict, and allow manual resolution. However, it seems like your software is too dumbed down for this to ever happen.

**Comment by jimbo1qaz** [comment]
I just got bitten by this bug again!

And to add insult to injury, you have the audacity to mock me with hundreds of "conflict" popup messages in my tray!!!

(Seafile 5.0.0)

How much longer must I wait for sanity?

**Comment by jimbo1qaz** [comment]
Why do you keep on unsyncing randomly anyway?

**Comment by killing** [comment]
Hi,

The goal of Seafile is to automate the syncing, unlike Git, which works better for technical users. So manual "merging" won't be added into Seafile's feature list in the future.
About "discarding" local changes, if you look it the other way, if your "local" changes are kept, another user may think you're discarding his local change. So both ways are the same. The rationale is that we should keep the first change that reach the server, first come first server.
About randomly unsyncing, is your local folder on NFS or network share? If so, you can disable this behavior in "settings" -> "advanced".

**Comment by jimbo1qaz** [comment]
I have a 1-person repository used by me only. Doesn't Seafile have the decency to p reserve both the local and remote state as separate commits which I can individually restore, instead of the current unusable state?

**Comment by jimbo1qaz** [comment]
I wrote a Python script to clean up after the mess, by detecting and renaming files. It doesn't delete files which have been deleted locally but restored by the server.

https://gist.github.com/jimbo1qaz/95ba9e768985a8a3e373

I'm still waiting for this bug to be fixed properly, by preserving local as a separate revision.

**Comment by killing** [comment]
Hi,
This is not a bug, but designed behavior. I don't think it will be "fixed" in any time.

**Comment by jimbo1qaz** [comment]
So... "it's not a bug, but a feature"... a feature that wrecks your file organization during the course of normal use...
