### ISSUE TITLE
Upgrading doc misses cache cleaning

### ISSUE THREAD

**Issue by galvanopus** [haiwen/seafile#1419]
Upgrading from seafile-server-a.b.c => seafile-server-x.y.z

Seafile Server creates ae2e9380b70c.css in seafile-server-a.b.c\seahub\media\CACHE\css\ae2e9380b70c.css when user first time logins in browser and receives libraries list.

After upgrading as described in http://manual.seafile.com/deploy_windows/upgrading_seafile_windows_server.html the same behavior as in #1261 occurs.

Workaround: either manually copy ae2e9380b70c.css from  seafile-server-a.b.c to seafile-server-x.y.z folder or delete seahub_cache folder before starting new server.

**Comment by galvanopus** [comment]
Is this correct that Seafile writes something to seafile-server-a.b.c folder?

**Comment by galvanopus** [comment]
@shoeper, should this issue be reopened as it is relevant for Windows? I have just checked seafile-server-6.0.7 for Windows. It still creates seahub\media\CACHE\css\1acfeda02a9a.css file.

So, there are two questions:

1. Should C:\seafile-server\seahub_cache be removed during upgrade?
2. For what folders should you grant modify rights in app folder if you using unprivileged user for Seafile service?

**Comment by galvanopus** [comment]
@shoeper, @killing, could you reopen the issue as it has not been fixed yet?

**Comment by galvanopus** [comment]
While dealing with new Seafile installation I found that at least the following directories should be writable:

seafile-server-6.0.7\seahub\media\avatars
seafile-server-6.0.7\seahub\media\CACHE
seafile-server-6.0.7\seahub\seahub\thumbnail\thumb

**Comment by galvanopus** [comment]
Issue @#1971 is for dealing with writable folders.

**Comment by shoeper** [comment]
From my point of view the hint hat the cache should be cleaned is included, now.
