### ISSUE TITLE
File modified date changes to current after moving or copying in web

### ISSUE THREAD

**Issue by galvanopus** [haiwen/seafile#1420]
Seafile server 4.3.1 for Windows.

Steps to reproduce:
1. Move or copy any file to another folder or library in web interface.
2. Check the file modification date. It will reset to the current, not retained.

**Comment by killing** [comment]
Yeah I think it should retain the timestamp. We'll improve it at some time.

**Comment by galvanopus** [comment]
Can this issue be related to #704?

**Comment by killing** [comment]
No, the client works differently from the web interface. With the latest client, you should not see the same problem.

**Comment by shoeper** [comment]
The problem has been fixed in v5.

**Comment by galvanopus** [comment]
Nice! Good reason for upgrade. Thank you!

**Comment by galvanopus** [comment]
@killing @shoeper The problem is back in 6.3.4.
