### ISSUE TITLE
Upload link does not work

### ISSUE THREAD

**Issue by mnellemann** [haiwen/seafile#1422]
Hi,

I've created a upload link and get this error when trying to add a file:

    [Exception... "<no message>" nsresult: "0x805e0006 (<unknown>)" location: "JS frame :: https://my-server/media/js/jq.min.js?t=1444896142 :: .send :: line 4" data: no]

Please see screenshot here:
![seafile-error](https://cloud.githubusercontent.com/assets/5939693/10782673/8ea95336-7d52-11e5-931a-10486ef41eb3.png)

This is seafile-server 4.4.3 and everything else works flawlessly.

**Comment by diggorygray** [comment]
Running seafile with fastcgi over https via apache and found the same problem.

Found that an upgrade had possibly changed the URIs in seahub_settings.py and ccnet.conf from https to http. 
Reverting this to the correct path in both config files and restarting seafile and seahub solved the issue.
We had the same error in Firefox but a different error when using IE (access denied).
Referred to: http://manual.seafile.com/deploy/https_with_apache.html

**Comment by mnellemann** [comment]
Hi,

I'm running nginx in front of seafile, terminating ssl - no http access.
The server address in ccnet.conf is w. https.

        listen 443 default_server;
        listen [::]:443 default_server ipv6only=on;

        server_name seafile;

        ssl on;
        ssl_certificate /etc/ssl/certs/seafile.pem;    # path to your cacert.pem
        ssl_certificate_key /etc/ssl/private/seafile.key;    # path to your privkey.pem

        location / {
                fastcgi_pass    127.0.0.1:8000;
                fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
                fastcgi_param   PATH_INFO           $fastcgi_script_name;

                fastcgi_param   SERVER_PROTOCOL     $server_protocol;
                fastcgi_param   QUERY_STRING        $query_string;
                fastcgi_param   REQUEST_METHOD      $request_method;
                fastcgi_param   CONTENT_TYPE        $content_type;
                fastcgi_param   CONTENT_LENGTH      $content_length;
                fastcgi_param   SERVER_ADDR         $server_addr;
                fastcgi_param   SERVER_PORT         $server_port;
                fastcgi_param   SERVER_NAME         $server_name;
                fastcgi_param   REMOTE_ADDR         $remote_addr;

                fastcgi_param   HTTPS               on;
                fastcgi_param   HTTP_SCHEME         https;

                access_log      /var/log/nginx/seahub.access.log combined buffer=16k;
                #access_log     off;
                error_log       /var/log/nginx/seahub.error.log;
        }

        location /seafhttp {
                rewrite ^/seafhttp(.*)$ $1 break;
                proxy_pass http://127.0.0.1:8082;
                client_max_body_size 0;
                proxy_connect_timeout  36000s;
                proxy_read_timeout  36000s;
        }

        location /media {
                root /home/seafile/seafile-server-latest/seahub;
        }
        location /seafdav {
                fastcgi_pass    127.0.0.1:8080;
                fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
                fastcgi_param   PATH_INFO           $fastcgi_script_name;

                fastcgi_param   SERVER_PROTOCOL     $server_protocol;
                fastcgi_param   QUERY_STRING        $query_string;
                fastcgi_param   REQUEST_METHOD      $request_method;
                fastcgi_param   CONTENT_TYPE        $content_type;
                fastcgi_param   CONTENT_LENGTH      $content_length;
                fastcgi_param   SERVER_ADDR         $server_addr;
                fastcgi_param   SERVER_PORT         $server_port;
                fastcgi_param   SERVER_NAME         $server_name;

                fastcgi_param   HTTPS               on;

                client_max_body_size 0;

                access_log      /var/log/nginx/seafdav.access.log;
                error_log       /var/log/nginx/seafdav.error.log;
        }

**Comment by shoeper** [comment]
I cannot reproduce these errors on v5.
