### ISSUE TITLE
Slash in Library-Name

### ISSUE THREAD

**Issue by w0xz** [haiwen/seafile#1424]
Hey! Thanks for Seafile!
When I created a library on a linux-server and named it "PC1/PC2"  and sync it with windows-client, seafile creates the library-directory named as PC1 with a subfolder PC2 in it.
I know Windows has problems with specialchars especially / and \ in foldernames, so maybe you should add a restriction an librarynames containing specialchars.
Best regards Eric!

**Comment by shoeper** [comment]
Using slashes it not possible on linux as well (at least not wanted).

I'd see it as a feature as it currently is because one can easily think with a folder structure by using slashes in the file name. If this is not wanted one can sync with an existing folder.

**Comment by freeplant** [comment]
You should not use slash in library name. Since it is quite a minor issue. I close it.
