### ISSUE TITLE
Client stops syncing, seaf-daemon.exe terminates

### ISSUE THREAD

**Issue by galvanopus** [haiwen/seafile#1425]
There are 3 machines:

Machine name | Configuration
--- | ---
nb | Windows 10 + Seafile Client 4.3.4
seafile | Windows Server 2012 R2 + Seafile Server 4.3.1
test | Windows Server 2012 R2 + Seafile Client 4.3.4

Chronological log:
1. I started to sync library from nb to seafile (about 150 GB).
2. In the middle of syncing I started to sync the same library from seafile to test.
3. Library sync from nb to seafile has finished successfully.
4. Some time passed.
5. seafile-applet.exe on test has terminated unexpectedly (with standard Windows error message).
6. If I launch client on test now it says "Downloading 0%", seaf-daemon.exe uses 1 CPU core and after ≈7 mins seaf-daemon.exe terminates, client stops syncing. After restarting client (with or without restarting OS) the behavior is the same.

Here the client logs: https://gist.github.com/galvanopus/461f03a6c8b4872f1eba

**Comment by shoeper** [comment]
Have you tried to restart the server? It looks like it doesn't respond like the client expects it to.

**Comment by galvanopus** [comment]
I can try to restart server, but I think that client reports about broken connection with seaf-daemon.exe, not a server. And I am able to sync a small library on test without restarting server.

**Comment by galvanopus** [comment]
Here are some experiments I have performed:

1. Stop client,
2. Delete ~/ccnet and ~/Seafile from test.
3. Launch client and connect to server.
4. Sync small library — OK.
5. Sync large library — seaf-daemon.exe terminates, only library folder with no subfolders is created.
6, Restart server.
7. Repeat steps 1 — 5. The result is the same.

**Comment by killing** [comment]
Hi,

Is the seafile.log you posted the complete one? I can't see why seaf-daemon terminates in that log. Can you send the complete seafile.log. Usually it's the most useful log file.

**Comment by galvanopus** [comment]
This is a full log, seaf-daemon terminates silently.

**Comment by galvanopus** [comment]
I am going to try to download the large library. I have deleted ~/ccnet and ~/Seafile from test. Should I delete something more?

**Comment by galvanopus** [comment]
11 GB has been transferred, seaf-deamon is not working.

Client logs: https://gist.github.com/galvanopus/cb787b13b51eb31ad322
Server logs: https://gist.github.com/galvanopus/9d171d304c5d6c32ffd8
Server access.log: https://gist.github.com/galvanopus/a7ef20a22a021898136c

**Comment by killing** [comment]
Can you check, after seaf-daemon terminates, is ccnet.exe still running? From the log it seems seaf-daemon terminates because ccnet.exe terminates. Do you have anti-virus software running on the computer? Maybe the anti-virus software is blocking the communication between seaf-daemon and ccnet.

**Comment by galvanopus** [comment]
ccnet.exe does not terminate. No anti-virus software is running on test. I have restarted seaf-applet.exe, here are the results:

1. seaf-deamon has terminated again after ≈3h.
2. storage/fs/ content is exactly the same content as it was after 1 fail (compared sha-1 and file listing).
3. storage/blocks has 47.9 GB size.
4. Downloaded library has 18.2 GB size.

**Comment by galvanopus** [comment]
After next seaf-applet restart.

1. seaf-deamon has terminated again after ≈1h.
2. storage/fs/ content is exactly the same.
3. storage/blocks has 38.5 GB size.
4. Downloaded library has 27.4 GB size.

Is there seaf-daemon debug build? Can I do something more to help to find the cause?

**Comment by galvanopus** [comment]
Can be related to #1212.

**Comment by galvanopus** [comment]
So, is this possible to turn seaf-daemon debug mode on?

**Comment by killing** [comment]
Unfortunately I don't see any way to debug the problem on Windows. Are you syncing huge amount of small files? If so seaf-daemon may be terminated due to memory constraint of the operating system. May be try to split the large library into smaller ones.

**Comment by galvanopus** [comment]
There are about 100 000 files taking 150 GB. Do you mean 2 GB per process constraint?

There is a long option called "debug" in [seaf-daemon.c] (https://github.com/haiwen/seafile/blob/master/daemon/seaf-daemon.c):
{ "debug", required_argument, NULL, 'D' }

How can I force seafile-applet to use it while launching seaf-daemon?

**Comment by killing** [comment]
You can turn on the debugging by setting SEAFILE_DEBUG=all environment variable on Windows. Just set the system wide environment variable. It should work.
But I don't know whether there will be any useful debugging information about this problem.

When seaf-daemon terminates, what message does the system tells you in the pop-up window? Can you give us a screenshot?

**Comment by galvanopus** [comment]
seaf-daemon terminates silently. Here are 3 Process Explorer screenshots at the termination moment:

![1](https://cloud.githubusercontent.com/assets/1897495/10904097/7e1af85c-8221-11e5-8e85-488889171abd.png)
![2](https://cloud.githubusercontent.com/assets/1897495/10904101/833230e4-8221-11e5-9412-db1c33b67e97.png)
![3](https://cloud.githubusercontent.com/assets/1897495/10904102/84ee5480-8221-11e5-8f61-1a8f66b17777.png)

I have set SEAFILE_DEBUG environment variable. Will check the result.

**Comment by galvanopus** [comment]
Here are last 20 log lines:

```
[11/03/15 12:17:49] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:50] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:50] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:50] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:50] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:50] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:50] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:53] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:53] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:53] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:53] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:53] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:53] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:53] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:53] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:53] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:53] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:53] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:17:53] repo-mgr.c(4839): Checkout empty dir <here was path to dir>
[11/03/15 12:36:04] read from connfd error: No error.
```

Nothing helpful.

**Comment by galvanopus** [comment]
What can be the next research step?

**Comment by galvanopus** [comment]
I have limited download speed to 1 MB/s, seaf-daemon is downloading library. seaf-applet has crashed, I have created an issue #1432 for it.

**Comment by galvanopus** [comment]
Library has been synced after limiting download speed to 1 MB/s (network link between test and seafile is virtual, so network throughput is much more than virtual disk one). How to find why exactly seaf-daemon terminates?

**Comment by galvanopus** [comment]
Does anyone have any suggestions?

**Comment by galvanopus** [comment]
@killing, may be this issue should be moved to seafile-client?

**Comment by killing** [comment]
Recently I've found a possible cause for the crash during download. Will be released in the next version.

**Comment by galvanopus** [comment]
@killing, fine! Could we close this issue after fix is released?

**Comment by galvanopus** [comment]
Thank you. I can test this issue after fix is released.

**Comment by killing** [comment]
Here is a test package containing the fix: https://app.seafile.de/f/2ccc2e94ae/?raw=1
Could you try it? We also added some more debug messages into the package. So the seafile.log would be interesting for us, no matter the bug is fixed or not.

**Comment by killing** [comment]
The fix has been released in 5.0.5. Have you tried it?

**Comment by shoeper** [comment]
Since there has been no feedback for one month I close it.

**Comment by galvanopus** [comment]
@killing I have just checked with server 6.0.6 + client 6.0.1. seaf-daemon.exe terminates under heavy disk usage.

**Comment by galvanopus** [comment]
@killing Could you reopen the issue? I am ready to provide debug info for seaf-daemon.exe if it is available. Btw, I found one more case when seaf-daemon terminates. I am uploading data (≈50 GiB) from mapped network drive, seaf-daemon has terminated several times. ccnet.exe is alive.

**Comment by killing** [comment]
I think it should be another problem. Could you open another issue? Could you find fresh dump files in C:\users\username\ccnet\logs\dumps after the crash? Make sure you use the latest version of client.
