### ISSUE TITLE
seafgc.sh should be able to run in dryrun mode without shutting down seafile

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1426]
For community edition seafile implementations, a garbage collection dryrun should be able to be run without shutting down seafile.  This allows users to verify the need to perform GC before shutting down seafile.  It can be irksome to shutdown seafile, run GC only to find out reclaimed space is minimal or none.  This is not possible in seafile community edition 4.4.3.

**Comment by lins05** [comment]
Sounds good to me. @killing
