### ISSUE TITLE
seahub issue: unknown command "createsuperuser"

### ISSUE THREAD

**Issue by monochromec** [haiwen/seafile#1427]
When giving version 5.0 a spin, I wasn't able to create an admin user by running seafile-admin create-admin. Django reported the following error:
'''
seafile-admin create-admin
Unknown command: 'createsuperuser'
Type 'manage.py help' for usage.
'''
Apparently this may be related to django.contrib.auth missing from the installed_apps array in seafile-server/seahub/seahub/settings.py.  Adding this causes a superuser to be created when setting up the seafile instance with seafile-admin setup but then caused the error message  "Error: <PATH>seahub.db not found" when trying to start the server with seafile-admin start --fastcgi. In my installation seahub.db is created in <PATH>/seafile-server/seahub/seahub.

**Comment by lins05** [comment]
In seafile server 5.0.0 seahub_settings is moved from `<top folder>/seahub_settings.py` to `<top folder>/conf/seahub_settings.py`, together with other config files. This may break the community maintained "seafile-admin" script you're using.

I guess you need to use the official "reset-admin.sh" script to do that for now.

**Comment by freeplant** [comment]
We will give the seafile-admin a check this week.

**Comment by lins05** [comment]
Should be fixed in @91d8712
