### ISSUE TITLE
Client (or server) renames library back to old name upon file change

### ISSUE THREAD

**Issue by qnxor** [haiwen/seafile#1428]
I have the Pro version v4.4.4 ona  Ubuntu x64 machine with 3 users, and I use the Windows client v4.4.2 on a Win Pro 8.1 x64 machine. I have 4 libraries, out of which 3 are encrypted.  I did the following:
- via the web interface, I renamed an encrypted library (click the gear icon, change its name, submit)
- in the Windows client, click the refresh button and I can see the new library name
- I changed a file in that library, the client reported the library is updated
- The library name is somehow renamed back to the old name ...

This feels like a bug. If not, how can I prevent the library name to be renamed back?

**Comment by qnxor** [comment]
Sorry, I meant to say v4.4.2 client

**Comment by qnxor** [comment]
Did some further testing. It appears that if I shutdown the client first, then go to the web interface, rename, and then launch the client, the client reports that the library has been renamed and updating files does not rename it back. Sounds like a bug.

**Comment by qnxor** [comment]
... and now it renamed it back to the old name again. I have also a Mac OS X client. I don't know which is the culprit (win client, os x client, or server). Any suggestions about what else I could try to do to keep it renamed without recreating the library?

**Comment by killing** [comment]
This should be a bug when the server merges the change from the client. The merge process doesn't consider the situation that the library name has been changed.
To avoid this problem, you can simply wait more than 30 seconds before uploading changes from the client. That way the client will first download the change from server before uploading changes. This will avoid merging.

**Comment by qnxor** [comment]
Ok, I'll try that in the future, thanks for the tip. Please do fix this bug though :)
