### ISSUE TITLE
Stronger lines/strokes in UI

### ISSUE THREAD

**Issue by lightonflux** [haiwen/seafile#143]
On monitors with bad contrast its really hard to see the lines which separates UI elements. Or think of people with visual impairment instead of bad monitors.

Github is a good example for a simple and modest UI with recognisable element borders.

Relevant talk: [*Beyond Alt Text What Every Project Should Know About Accessibility*](http://mirror.linux.org.au/linux.conf.au/2013/mp4/Beyond_Alt_Text_What_Every_Project_Should_Know_About_Accessibility.mp4)

Seafiles Design should be more practical for daily use and a broader user base.

**Comment by lightonflux** [comment]
Marked for what? Or do you mean tagged?  And what is the reason for closing this bug?

**Comment by freeplant** [comment]
I have watched the video. I closed the issue because the web UI has been changed a lot since the issue opened. If you can be more specific on "Stronger lines/strokes", it will help us to improve the web UI. Otherwise, I don't know what to change.

**Comment by lightonflux** [comment]
I rechecked and since the redesign this issue is fixed. The new design separates elements more clearly. 

Thank you for explaining why you closed the bug. It is always better to add a short comment why something is closed than closing without comment. Because it doesn't leave things in a unclear state. It is good practice to always explain the closing of a issue, even if its just a three word sentence.  

And thanks for your work on seafile. Since i used it back in 2013 some friends picked it up and are very happy with it.
