### ISSUE TITLE
Web Config in 5.0: Conflicts between config file and SQL setting

### ISSUE THREAD

**Issue by forouher** [haiwen/seafile#1431]
According to the changelog, with 5.0 people will be able to change settings via config file OR
via the web UI (which stores the settings in SQL).

I fear that this design will confuse people.

If a user changes a setting via UI even only once, modifying that setting in the config file later will no longer have any effect. This is not obvious. And even if you would put a notice into the manual, I think many people might still be surprised by this.

Instead I'd suggest to have each setting value *either* in the config *or* in the web UI. Exclusively.

E.g.:

* Settings which are absolutely necessary to get the Web UI running belong to the config files.
* *Everything else* belongs to the web UI, and the web UI only.

**Comment by freeplant** [comment]
This is a good suggestion. Let's wait and see how people use the feature before we modifying the document.

**Comment by shoeper** [comment]
I agree with @forouher

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/web-config-in-5-0-conflicts-between-config-file-and-sql-setting/4359
