### ISSUE TITLE
Question about scaling of seafile

### ISSUE THREAD

**Issue by kopax** [haiwen/seafile#1435]
I want to vertical scale seafile.
I have tried hard  finding a good docker image for seafile, all were not fully dockerized images and more a wrapper without good data persistence.
I want to deploy seafile server with mesosphere/marathon, could anyone help me with that ?

**Comment by shoeper** [comment]
You can use this script to install Seafile https://forum.seafile-server.org/t/seafile-server-installer-for-production-ready-seafile-ce-and-pro-installations/1464

**Comment by kopax** [comment]
I have tried already the manual install on a fresh debian, all the docker seafile image on github, I have also tried to build my own docker image but there are too many installation step and it's anoying every time i have to rebuild and fix the config.

The link you provided me doesn't fit for a Dockerfile needs (interactive)

I have seen another library already ported on Docker called owncloud, too bad seafile never ported their soft into a docker

**Comment by lins05** [comment]
To run seafile in a cluster mode you need to use the pro edition. Check this thread if you're interested: https://forum.seafile-server.org/t/lb-with-ce-version/3357

**Comment by kopax** [comment]
Thanks a lot. I have decided to give up on Seafile until they release a true Dockerized app.
