### ISSUE TITLE
seafile-ignore.txt doesn't work at all

### ISSUE THREAD

**Issue by AlexFrost** [haiwen/seafile#1436]
Ubuntu 14.04 x64 seafile client 4.4.2

I sync ~/Documents as library. I read https://www.seafile.com/en/help/ignore/ and put "seafile-ignore.txt" to  ~/Documents with:

Anki/
Anki/*
1/
1/*
1*

Restart client. Than copy to ~/Documents dir "1" and file 11 and they are syncing to server

correct behavior: dir "1" and file 11 aren't syncing

**Comment by freeplant** [comment]
The problem should have been solved in the latest version.

**Comment by AlexFrost** [comment]
I have latest linux client 5.0.6 and it still sync all excluded files
