### ISSUE TITLE
bad crc seafile-server_4.4.6.tar.gz

### ISSUE THREAD

**Issue by EBII** [haiwen/seafile#1438]
donwload the 9 november 2015 

gzip -d exit with 

gzip: seafile-server_4.4.6_x86-64.tar.gz: invalid compressed data--crc error

tar -zxvf exit with 

gzip: stdin: invalid compressed data--crc error
tar: Child returned status 1
tar: Error is not recoverable: exiting now

regards

**Comment by ShonkyCH** [comment]
I am seeing the same.
