### ISSUE TITLE
Messages Module removed

### ISSUE THREAD

**Issue by ecoitsolutions** [haiwen/seafile#1440]
Are you really going to remove this module for good or it is just for the latest version or planed for upgrade? We rely on this module and removing it made seafile pretty much useless for us.
Thank you

**Comment by shoeper** [comment]
Hi,

are you referring to the one to one message module or the communication features in general (e.g. comments)? This could be interesting for you https://forum.seafile-server.org/t/file-comments-are-gone/3053.

- Sven

**Comment by ecoitsolutions** [comment]
Hi Sven and thanks for the reply, i am referring to the one to one messages module. It is gone completely and downgrading toe the latest version that has it seams impossible.
We really need that module back...

**Comment by shoeper** [comment]
@freeplant

**Comment by freeplant** [comment]
I'm sorry we will not add private messages between two users back. This is a redundant feature for most users. Keeping it there will confuse other users.

**Comment by shoeper** [comment]
As an alternative you might want to have a look at http://www.mattermost.org/.
