### ISSUE TITLE
apache cpu load goes to max (again)

### ISSUE THREAD

**Issue by ftribrunn** [haiwen/seafile#1441]
look at:#1370

same problem again with v4.4.6

![image](https://cloud.githubusercontent.com/assets/4007655/11060540/377f1e98-87a1-11e5-8e35-cd9e8328c479.png)

after few mins cpu load goes to 100%

it might depends on the client 4.4.2?

any idea?

[update:2015-11-11 / 00:34]
I tried realy many things. 
- change apache2 config
- setup new server 4.4.5
- setup new server 4.4.6
- try different clients 4.3.4 and 4.4.2
- add a second CPU

nothing helped!
the cpu load goes to 100% each cpu with the apache2 -k start

I have found a lot of errors in the apache2 error log:
```
[Wed Nov 11 00:37:42 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:37:47 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:37:54 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:37:55 2015] [error] proxy: pass request body failed to 127.0.0.1:8084 (127.0.0.1) from x.x.x.184 ()
[Wed Nov 11 00:37:55 2015] [error] proxy: pass request body failed to 127.0.0.1:8084 (127.0.0.1) from x.x.x.184  ()
[Wed Nov 11 00:37:55 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:37:56 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:38:09 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:38:10 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:38:10 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:38:18 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:38:27 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:39:12 2015] [error] (105)No buffer space available: proxy: HTTP: attempt to connect to 127.0.0.1:8084 (127.0.0.1) failed
[Wed Nov 11 00:39:12 2015] [error] ap_proxy_connect_backend disabling worker for (127.0.0.1)
[Wed Nov 11 00:39:13 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:39:14 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:39:14 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:39:15 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:39:15 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:39:15 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:39:15 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:39:15 2015] [error] proxy: pass request body failed to 127.0.0.1:8084 (127.0.0.1) from x.x.x.184 ()
[Wed Nov 11 00:39:15 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:39:15 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)
[Wed Nov 11 00:39:15 2015] [error] proxy: HTTP: disabled connection for (127.0.0.1)

```

suggestions highly appreciated :-)

**Comment by ftribrunn** [comment]
i ve testet around a bit. i think it depends not on the server. its about the client 4.4.2?
with 4.3.4 the problem doesnt come up.
can u check that pls.
thx in advance

**Comment by shoeper** [comment]
Does apache use request buffering?

**Comment by ftribrunn** [comment]
Loaded Modules:
 core_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 mpm_prefork_module (static)
 http_module (static)
 so_module (static)
 alias_module (shared)
 auth_basic_module (shared)
 authn_file_module (shared)
 authz_default_module (shared)
 authz_groupfile_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cgi_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 fastcgi_module (shared)
 headers_module (shared)
 mime_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_http_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 ssl_module (shared)
 status_module (shared)
Syntax OK

**Comment by shoeper** [comment]
I do not work with apache and I won't check what each of those modules does.
Does it use request buffering, or doesn't it? If it does not you could try setting up request buffering and see if that solves the problem.

**Comment by freeplant** [comment]
This is Apache related config problem. We can't help on this issue.
