### ISSUE TITLE
Files with spaces in name can't get preview.

### ISSUE THREAD

**Issue by tarrinr** [haiwen/seafile#1443]
I'm running seafile on centos 7 with the fastcgi work around.  If I have a space in the name of the file, the icon disappears and the preview says "File does not exist."  Quotes forgotten somewhere?

**Comment by shoeper** [comment]
I cannot confirm this using Debian Wheezy and Seafile Pro 4.3.3. Maybe you have a wrong url encoding?

**Comment by tarrinr** [comment]
After posting, I found this...  https://github.com/haiwen/seafile/issues/1258. It confirms my suspicion that mod_proxy_fastcgi is to blame.
