### ISSUE TITLE
Webdav directory names are cryptic when duplicates are present

### ISSUE THREAD

**Issue by ricardoteixeiraduarte** [haiwen/seafile#1444]
Say a user has a folder named "My Library", and another user shares a "My Library" folder with him.
When usind webdav, user will see two My Library-<hash>  on their account, and is not able to know what is each.
As a way to fix this, you could keep the user Library with the original name and add "-<user that shared the library>" to the library name, instead of the cryptic hash.

**Comment by lins05** [comment]
Good suggestion - when the is a name confliction, the user-owned library should have a high priority of using the original name.

**Comment by shoeper** [comment]
Maybe on duplicate libraries from other users could be named as user-library.

**Comment by kampde** [comment]
Well, a user could create 2 libraries with the same name, so having own libraries take precedence over shared libraries to keep the name is not the right solution.

On a semi-related note, is there any way of having the "webdav name" of a library via its id?

**Comment by shoeper** [comment]
No, I don't think so. That's possible via API.

**Comment by kampde** [comment]
@shoeper great! Could you point me to the method to use, or at least what should I be searching for? I haven't seen anything in the examples of the web api or the python api to get this info.

**Comment by shoeper** [comment]
http://manual.seafile.com/develop/web_api_v2.1.html#list-libraries
http://manual.seafile.com/develop/web_api_v2.1.html#upload-file

**Comment by kampde** [comment]
Well, neither `/api2/repos/` nor `/api2/repos/{repoid}` returns the name with the hash, so I guess I'll have to get all libraries, see if the want I want has the name duplicated and then append the first 6 chars of the Id.
