### ISSUE TITLE
Can't start seahub

### ISSUE THREAD

**Issue by AlexFrost** [haiwen/seafile#1445]
After untar seafile I get
```
# ls seafile-server-latest/runtime
drwxrwxr-x 2 500 500   ./
```
and I can' start seahub until 
```
# chown seafile:seafile seafile-server-latest/runtime 
```
because  seahub can't create pid file, I think 
```
# ls seafile-server-latest/runtime
total 20
drwxrwxr-x 2 seafile seafile   ./
drwxrwxr-x 6     500     500   ../
-rw-r--r-- 1 seafile seafile     access.log
-rw-r--r-- 1 seafile seafile   error.log
-rw-rw-r-- 1     500     500   seahub.conf
-rw-r--r-- 1 seafile seafile    seahub.pid
```

Could you please add this to install documents 
Could you please move seahub.conf to another dir because after  chown it's insecure and seahub need write access to this dir.

Thanks

**Comment by shoeper** [comment]
I could bet your permissions are just horribly wrong. Close this issue and figure this out yourself or ask for help at https://forum.seafile-server.org. This is an issue tracker and no personal support platform.
