### ISSUE TITLE
Locked files must not be directly deleted/ renamed/ modified

### ISSUE THREAD

**Issue by shoconsult** [haiwen/seafile#1449]
With a reference to the discussion here:
https://forum.seafile-server.org/t/file-lock-not-working-together-with-local-sync/

When files are locked, the lock is shown (after sync) to other users. If they ignore the signs and modify, rename or delete the file locally, these changes must not be synced back to the server. Instead a conflict file should be generated.

**Comment by killing** [comment]
Please re-open this issue on haiwen/seafile-client project. This project is for reporting server issues.

**Comment by shoconsult** [comment]
Sorry. Done.
https://github.com/haiwen/seafile-client/issues/749
