### ISSUE TITLE
seaf-fuse won't start with lots of options

### ISSUE THREAD

**Issue by ulyasutay** [haiwen/seafile#1450]
If you try to start seaf-fuse with lots of options, it fails because it thinks you have invalid arguments.  This is because the check for the number of arguments is incorrect.  The following fixes it:

    --- seaf-fuse.sh~       2015-10-17 15:13:31.000000000 +0100
    +++ seaf-fuse.sh        2015-11-15 17:26:27.412702337 +0000
    @@ -24,7 +24,7 @@
         exit 1;
     fi
     
    -if [[ ($1 == "start" || $1 == "restart" ) && $# < 2 ]]; then
    +if [[ ($1 == "start" || $1 == "restart" ) && $# -lt 2 ]]; then
         usage;
         exit 1
     fi

**Comment by shoeper** [comment]
Has been merged, can be closed.
https://github.com/haiwen/seafile/commit/8bd4c05626bbf358fce8ad7384c8eb8ec4c141e9
