### ISSUE TITLE
Modify history days in web interface does not work when using postgresql

### ISSUE THREAD

**Issue by elratt0r** [haiwen/seafile#1452]
You can set the parameter once in the webinterface (INSERT into repohistorylimit is successfull), but on change the UPDATE statement thows a database error. Patch attached.

[history_patch.txt](https://github.com/haiwen/seafile/files/34981/history_patch.txt)

**Comment by killing** [comment]
Thanks. We'll fix it in the next version.

**Comment by shoeper** [comment]
Has it been fixed?

**Comment by killing** [comment]
Fixed.
