### ISSUE TITLE
Accept anchors in markdown documents

### ISSUE THREAD

**Issue by roipoussiere** [haiwen/seafile#1453]
Seafile markdown documents should accepts anchors and internal links, especialy to create a mini table of content.

Syntax:

    ## Table Of Contents

    [Part 1. Foo](#foo)
    [Part 2. Bar](#bar)

    <a name="foo"></a> ## Part 1. Foo
    [...]
    <a name="bar"></a> ## Part 1. Bar
    [...]

or even better:

    [Part 1. Foo][]
    [Part 2. Bar][]

    ## Part 1. Foo
    ## Part 2. Bar

See http://stackoverflow.com/questions/6695439/how-do-you-create-link-to-a-named-anchor-in-multimarkdown

**Comment by shoeper** [comment]
> MMD is a superset of the Markdown syntax
http://fletcherpenney.net/multimarkdown/

Afaik seafile only has markdown so far. So I'm not sure if that would fit in well.

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/accept-anchors-in-markdown-documents/4360
