### ISSUE TITLE
Meet a `CSRF verification failed. Request aborted` error when login with the MS IE browser

### ISSUE THREAD

**Issue by foool** [haiwen/seafile#1455]
When I login the seahub website for the first time with the admin's account, I meet a `CSRF verification failed. Request aborted` error as follow: 

    Forbidden(403) 
    CSRF verification failed. Request aborted.
    Help
    Reason given for failure:
        CSRF cookie not set.

The seafile version is seafile-server-4.4.6.
The OS is Ubuntu-14.04.3 with apache2.4.
The browser is IE8.

seafile and seahub can be started normally. 

P.S. I just try the chrome instead of IE, and I can login normally, so I think there must be a compatible problem.

**Comment by shoeper** [comment]
IE8 isn't supported by Microsoft anymore.

**Comment by jankapunkt** [comment]
Got the same with Firefox 65.0.1 on OSX 10.12.6
