### ISSUE TITLE
sym/hard links in two libraries pointing to the file 

### ISSUE THREAD

**Issue by qnxor** [haiwen/seafile#1458]
I'm experiencing a strange behaviour (I'm not sure it's necessarily a bug). Using the Mac OS client 4.4.2 and the Pro server 4.4.6 on Ubuntu with SQLite.

I have 2 libraries, both encrypted. Consider the following different scenarios, which behave the same:
- in each library I created a sym/hard link pointing to the same file that resides outside of the Seafile folders.
- in the 2nd library I created a sym/hard link to a file that resides in the 1st library. 

When the target file changes, Seafile detects it but syncs only the 1st library. It does not **automatically** sync the 2nd library. However, I can sync it **manually** -- if I right click the 2nd library in the client, and select "Sync now", it immediately sees the changes and syncs the 2nd library sending the synced file as well.

The reason I'd like to be able to do this is that the 2nd library is shared with someone and I could selectively share only some files/folders from my 1st (personal and encrypted) library so that they are updated at the same time and I don't have to maintain two copies on my machine.

**Comment by shoeper** [comment]
It looks like symlink support has not explicitly been implemented to cover all cases.

https://stackoverflow.com/questions/28769503/use-inotify-to-watch-a-file-with-multiple-symlinks shows that it can be very tricky.
