### ISSUE TITLE
Change server address in Windows Client bug

### ISSUE THREAD

**Issue by larsmm** [haiwen/seafile#1463]
When I change the serveraddress of an existing account in windows client (for example from foo.dyndns.org to 10.1.0.5) the seafile client saves this setting and displays the new address in the interface. The new address is used for the list of libraries shown in the client. The address for data transfer is still the old one (verified with wireshark). The bug is reproducable on different systems and seafile client versions (tested windows 4.3.4 and 5.0.0 on server 4.4.6).

Edit: It concerns the initial sync of a library only. If you start a initial sync new entries including the server address are made in seafile-data\clone.db: CloneTasks and CloneTasksMoreInfo. If you change the server address in the client while initial sync is running, the server address in clone.db is not changed. It is possible to change the server address while initial sync by editing the server address in clone.db by hand and start seafile client again.

**Comment by killing** [comment]
We'll fix it. Thanks for reporting. Can you reopen it in haiwen/seafile-client project?

**Comment by larsmm** [comment]
Yes, sorry.
