### ISSUE TITLE
Support custom sorting (by date, size, name; ascending/descending) in RPC

### ISSUE THREAD

**Issue by moritzschaefer** [haiwen/seafile#1464]
In order to support custom ordering of directory entries (by size, name, ...; ascending, descending) the RPC seaf_repo_manager_list_dir_with_perm (https://github.com/haiwen/seafile/blob/master/server/repo-perm.c) doesn't provide enough functionality:
It just orders by name. Though it supports other "high level" parameters for pagination. 
In order to properly support ordering for clients (seahub, seadroid, ...) either the RPC should be changed or another RPC, supporting filtering, should be added. 

As nobody wants to break the RPC/API I suggest adding an RPC list_dir_sorted_with_perm

seafile_list_dir_sorted_with_perm (in rpc-service.c)
and registering it in (seaf-server.c) like this:
    searpc_server_register_function ("seafserv-threaded-rpcserver",
                                     seafile_list_dir_sorted_with_perm,
                                     "list_dir_sorted_with_perm",
                                     searpc_signature_objlist__string_string_string_string_int_int_string_int()); # note _string_int at the end for the field to be filtered and for the ascending/decsending switch.

The new RPC could use a modified version of seaf_repo_manager_list_dir_sorted_with_perm (in repo-perm.c) which could serve well for both RPCs.

If contribution to this repository is welcome, I would be happy to implement a solution in a fork and make a pull request. 

Regarding issue in seahub project: https://github.com/haiwen/seahub/issues/257

**Comment by moritzschaefer** [comment]
<push>
still willing to boost the API, just confirm.

**Comment by freeplant** [comment]
What we plan to do is retrieving all directory entries and sorting in the python code.

**Comment by moritzschaefer** [comment]
If this is performance-wise acceptable. Is there some ETA (without any warranty) for this feature? I ask, because I want to improve the android client if possible (haiwen/seahub#257)

**Comment by freeplant** [comment]
Do you mean you want to improve the Seahub? I don't see any related issue for the Android client.

**Comment by moritzschaefer** [comment]
Yeah I mean Seahub (sorry for confusion).

**Comment by freeplant** [comment]
I think the performance will have no problem because sorting in Seahub only add an extra cost of transferring the data from  C to Python, which is done locally. We will remove old unused code (URLs start with `ajax/repos/`)  this month. In the next month we will be able to add the file sorting.

**Comment by freeplant** [comment]
In v5.1, the server simply return all files and the client do the sorting.
