### ISSUE TITLE
SERVER :  libevhtp not installed properly

### ISSUE THREAD

**Issue by 100305** [haiwen/seafile#1471]
I am having an fatal error while installing the SERVER Seafile on an Ubuntu Server 14.04.LTS i386 and following the instructions of the official Website.
It occurs when reaching the step of the installation of Libevhtp (Build libevhtp by :..)

Before reporting, I am still wondering if i have really did so good by installing the Libzdb.
Even if it's still pretty obvious, and taht everything went fine,  I don't know.
(I installed it in an new repository as explained in its READ note :
sudo ./configure
make
make install
)

This is now the error :
Your CXX Compiler : "CMAKE_CXX_COMPILER-NOT FOUND".
Please set CMAKE_CXX_COMPILER to a valid compiler path or name.

**Comment by killing** [comment]
Here is for bug tracking. Please post questions on the forum instead.
