### ISSUE TITLE
Garbage Collection Cleanup issues

### ISSUE THREAD

**Issue by torrentkino** [haiwen/seafile#1473]
Hello,

the Seafile harddrive is filling up and I tried to figure out, who has the most stuff in his/her libraries.

1. du -sm /var/lib/seafile/haiwen/seafile-data/storage/blocks/* | sort -n
2. Log into the Admin-Page and find the Library containing the abcd-1234-efgh-... string.

So, that particular library contains 35GB while the user has a quota at 2GB.

I ordered him to set a smaller history for that particular library. And now I wait for some kind of shrinking event. I do run a gc-script every night (seaf-gc.sh run). And yes I stop the seafile-server before running this gc-job.

 Should it shrink or do I have some misconception about it?

Kind regards,
Aiko Barz

**Comment by killing** [comment]
Please move questions to the forum. Here is for bug tracking only.

**Comment by torrentkino** [comment]
Just leaving a short notice: I fixed it.

The seaf-gc.sh syntax has changed between Seafile-3.x and Seafile-4.x. And my old script did not reflect this change. "seaf-gc.sh run" did not do anything, but It did not throw some kind of command line error either:

> Starting seafserv-gc, please wait ...
> [12/09/15 05:00:35] gc-core.c(456): === GC is finished ===
> seafserv-gc run done

Carefully reading this [document][1] again was the key to this problem. I could free a lot of disk space by now.

Thanks,
Aiko Barz

[1]: http://manual.seafile.com/maintain/seafile_gc.html
