### ISSUE TITLE
Broken UI: Share to user wrongly appears to work for external users

### ISSUE THREAD

**Issue by nidico** [haiwen/seafile#1474]
As of my understanding, it is not possible to use the "share to user" function in order to share with an external user (without seafile account). I didn't find that information in the official documentation, but some external German documentation (not the English translation though) contains the sentence:

> Hiermit sind ausschließlich Benutzer gemeint, die im System registriert sind. (This only means users which are registered in the system)

However the share UI (in Seafile 4.4.x) allows to enter arbitrary email addresses (same as for upload and download links, where this actually works) - Seafile even seams to create a share and a an ad-hoc profile, which states "Has not accepted invitation yet". This suggests that an invitation has actually been sent, however it hasn't, as this is simply not supported.

There are two possibilities to solve this issue:

- Actually allow to share to external users (would be nice, but isn't necessary if #987 is implemented)
- Fix the UI in a way that it doesn't let you create shares for non-existing email addresses

**Comment by freeplant** [comment]
Thanks for the suggestion. We disabled sharing to non-existing email addresses. It will be included in the next release.
