### ISSUE TITLE
Building 5.0.2-server seaf-daemon.c:311:5: error: too many arguments to function 'ccnet_client_load_confdir'

### ISSUE THREAD

**Issue by tigerfoot** [haiwen/seafile#1477]

**Comment by tigerfoot** [comment]
same with 4.4.6 version :-(

**Comment by hetisthijs** [comment]
Having the same error. What solved yours?

**Comment by tigerfoot** [comment]
Well my fellows didn't give me the fullstack at first time, once ccnet, lib and then seafile seafile client build all.
