### ISSUE TITLE
ImportError no module named caches

### ISSUE THREAD

**Issue by amof** [haiwen/seafile#1483]
Hi,

I'm running seafile on ReadyNas OS6.4.1 with Linux 4.1.13 on an ARMv7.

I wanted to install the version of seafile 5.0.3. 
All the compilation of all seafile-ccnet-libsearpc succeed.

When i do the seafile-admin setup, it fails:

    Now initializing seahub database, please wait...

    ImportError: cannot import name caches
    Error: Seahub syncdb failed

I installed python-memcached but I got still the error.

Have you any ideas to solve the problem ?

Thanks !

*Note*: I had previoulsy installed the seafile v4.4.5 and it was working perfectly. So what have changed ?

**Comment by haoglehaogle** [comment]
I have same issue. did you solve it?

**Comment by amof** [comment]
Not yet.
Please join us on this conversation [here](https://forum.seafile-server.org/t/importerror-cannot-import-name-caches/3540).

**Comment by haoglehaogle** [comment]
I have solve this issue,
change :
 /usr/local/bin/seafile-adin, line 166,
         proc = subprocess.Popen(argv,
                                cwd=cwd,
                                stdout=stdout,
                                stderr=stderr,
                                env=env)

to
        proc = subprocess.Popen(argv,
                                cwd=cwd,
                                stdout=stdout,
                                stderr=stderr,
                                env=env,
                                shell=False) <--- add this parameter
any question, let me know!

**Comment by amof** [comment]
I will definitely try it !

Yes, I got a question : can you explain me how you solve it ? 

Thx !

**Comment by haoglehaogle** [comment]
I use pdb trace this issue, and found other Popen with shell=True, but here without this parameter, so I add shell=Falese, it work well after add it, but I don't know why. I use python 2.7. I guess root cause maybe is Popen's usage.

If without this parameter, this issue will be generated after Popen return.

**Comment by amof** [comment]
Ok, don't know it !
Thanks for the explanation !

**Comment by ollux** [comment]
well, it's a version problem with django constance : 
sudo pip install django-constance=="1.0.1"
you'll have the same kind of problem later with "utils", and this time it's compressor :
sudo pip install django-compressor=="1.6"
Basically, the newest versions installed by pip dont support django 1.5 which is required by seafile.

**Comment by amof** [comment]
Thank you for your comment.

I'll take a look when I can !
