### ISSUE TITLE
Support for the Open Graph protocol

### ISSUE THREAD

**Issue by samczsun** [haiwen/seafile#1486]
Hey,

I'd like to request the ability to enable og tags for images, so that URLs like https://seacloud.cc/f/0a8d8e64f8/ will automatically preview in apps like Slack and Discord.

I've managed to implement this hackily by adding these lines into file_content_html.html

```html
<meta property="og:title" content="{{ file_name }}">  
<meta property="og:url" content="{{ raw_path }}">  
<meta property="og:type" content="article">  
<meta property="og:image" content="{{ raw_path }}">
```

However, I think official support would be much appreciated.

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/support-for-the-open-graph-protocol/4349
