### ISSUE TITLE
sort by date does not work

### ISSUE THREAD

**Issue by paulfab** [haiwen/seafile#1487]
In the web interface, when we are in a folder with imagine 100 files.
Only the first 50 files (for example) are displayed, in first
if we want to get the newest files of the folder and click on sort by date, it will only sort the current listed files. If we want the real sort, we need to list all files, by scrolling at the bottom of the page many times, and then sort

**Comment by freeplant** [comment]
It should work in v5.1.

**Comment by jowolf** [comment]
I just upgraded to 6.04, specifically to fix this exact problem, yet it seill persists - and I have cleared my browser's cache, etc.

I have camera folders with thousands of files (1.5+ years worth) and cannot see the most recernt ones without the tedious and laborious process of repeatedly scrolling to the bottom (tens or hudreds of times) and *then* sorting by date.

Please advise.
