### ISSUE TITLE
Sharing files from encrypted libraries results in error

### ISSUE THREAD

**Issue by ingjardt** [haiwen/seafile#149]
If you use generate a share link in an encrypted library, the recipient will get an error message.

If you share an image, the recipient will only see an "missing image"-thumbnail, if you share a text file, he will get the error message "HTTPError: failed to open file online"

**Comment by shuhaowu** [comment]
Has this been resolved? I don't see a share link in the seafile web ui from encrypted libraries.

**Comment by shoeper** [comment]
Imho sharing files in encrypted libraries makes no sense because one has to expose it's private key therefor.
