### ISSUE TITLE
Create a new user kind

### ISSUE THREAD

**Issue by Salzem** [haiwen/seafile#1493]
Hello, 
the work done on this project is great.
Nevertheless, I would like to ask you if it was possible to implement a new kind of user, that couldn't upload anything (in his library), and could only see and download things in the shared libraries. And he shouldn't be able to erase the account.
It would kinda be like a "guest" account, and it would be great :-)
Thank you.

**Comment by freeplant** [comment]
We don't quite interested in this feature. Unless it is required in the future by our customers, we will not add it.
