### ISSUE TITLE
Cannot rename or move items in web interface since 5.0.3

### ISSUE THREAD

**Issue by MacLemon** [haiwen/seafile#1495]
Since upgrading Seafile server from 4.4.2 to 5.0.3 it's no longer possible to rename or move items in the webinterface.
Renaming files in the Mac client causes it to sync the file twice doubling the data.

Host: Debian Jessie, Seafile 5.0.3
Client: OS X El Capitan, 10.11.2, Seafile Mac 4.4.2

**Comment by shoeper** [comment]
> Since upgrading Seafile server from 4.4.2 to 5.0.3 it's no longer possible to rename or move items in the webinterface.

Works here as it should (I can copy, move and rename files)

> Renaming files in the Mac client causes it to sync the file twice doubling the data.

So they aren't moved but copied on the server?
