### ISSUE TITLE
Thrash expire time

### ISSUE THREAD

**Issue by swennijboer** [haiwen/seafile#1498]
Hello all,
I've recently started to use Seafile and I really love it, however I would like to request a feature.
From what I've understood and was able to find is that if you remove a file it will stay in the thrash for 90 afther which it can be removed by the garbage collection.
Could you make it an option to set the time for the thrash, so that I could say that you could have, for example only 30 days of thrash? Just like you have done with file history.

Keep up the awesome work and I hope to hear from you soon :)

**Comment by freeplant** [comment]
It is already configurable in the library settings.

**Comment by swennijboer** [comment]
Could you tell me where?
When I'm in in the webclient administrator part and go the settings, there is no option to set the expirery time for the thrash (I mean the normal files, not a fully deleted library but files withing a library that are deleted).

**Comment by levinus** [comment]
Maybe see here: http://manual.seafile.com/config/seafile-conf.html under "Default history length limit"

**Comment by swennijboer** [comment]
Thanks a lot, I thought this was only for the file revision history but it indeed works for the thrash can.
Sorry for making an unnecessary issue and thanks a lot for the solution :)
