### ISSUE TITLE
nginx https file up-/download not working & debugging not working.

### ISSUE THREAD

**Issue by neo-luddite** [haiwen/seafile#1499]
hey there,

I'm using ubuntu 14.04, seafile 5.0.3 and nginx as https reverse proxy.
I can access seafile, browse around, create directories and files but I cannot upload and download any. I followed the manual for nginx https.

uploading results in the following message:
> [Exception... "<no message>" nsresult: "

pressing the download button results in a `connection failed` message, which is logical, because the browser tries to access:

> https://xy.example.net:8082/files/9bf...f83/test

and port 8082 is closed. 

if I hover over the download button the following link is shown:

> https://xy.example.net/lib/d93a927...ad87-f4725e646b5b/file/test?dl=1

if I remove port 8082 from the url I get

> Page not found (404)
> Using the URLconf defined in djblets.util.rooturl, Django tried these URL patterns, in this order: 
> [...]

opening port 8082 in the firewall results in a "failed encrypted connection".

the relevant parts of the config files look as follows:

seahub_settings.py:
>FILE_SERVER_ROOT = 'https://xy.eample.net/seafhttp'
>DEBUG = True

seafile.conf:
> [fileserver]
> port = 8082

the nginx conf is c&p the complete sample config from the manual, I only changed the domain name.
removing `/seafhttp` from FILE_SERVER_ROOT doesn't change anything.

the seahub.log file is empty, no matter if I set `DEBUG = True` or not!? no messages in the terminal in which I (re)started seahub.sh. no error messages in the other seafile logs or nginx logs.

any held much appreciated!

**Comment by shoeper** [comment]
https://forum.seafile-server.org/

**Comment by neo-luddite** [comment]
oh.... so many projects use github not only for propper bug reports nowadays. I read the forum before but posted here without thinking. Sorry!
