### ISSUE TITLE
Wildcard / erroreous labels in windows client 5.0.2 at librarys contextmenu

### ISSUE THREAD

**Issue by infinity85** [haiwen/seafile#1503]
Hi,
after installing the new Windows Client v5.0.2. I noticed "%" and "%1" signs in the context menu of my librarys if I use the right-mouse-button.

This happens at least on the german localization. Take a look at my screenshot, which is showing this optical issue:

![11-01-_2016_13-34-17](https://cloud.githubusercontent.com/assets/11557459/12233658/f3d272aa-b868-11e5-84f6-e7b211392d28.png)

**Comment by lins05** [comment]
Fixed in https://github.com/haiwen/seafile-client/commit/60b358e
