### ISSUE TITLE
Can't view PDFs when library is encrypted via the web interface.

### ISSUE THREAD

**Issue by florihupf** [haiwen/seafile#1505]
It talks about not available due to encrypted library.

Does not make sense, because I just provided my password.

**Comment by shoeper** [comment]
It does make sense and is the expected behaviour. Encrypted files are not further being processed on server side.

**Comment by florihupf** [comment]
Hi Sven,

not 100% sure if I can follow you there... Because I can nicely read the
PDF from the same library using the iOS app.

Why can't the web viewer do the same thing?

**Comment by shoeper** [comment]
The iOS device just downloads the file.

**Comment by florihupf** [comment]
Great!  Could the web viewer just download the file as well and then
display it?

;-)

**Comment by levinus** [comment]
The webviewer is generated on the serverside. To view a file on the PC you have to download & open it in a viewer too.

**Comment by florihupf** [comment]
Couldn't you run the that on the client side?

Anyways, I found a way to hack the python to fix this defect.

Since it is possible to fix this by commenting out two lines of python I am
not sure what the initial motivation is for this?

Is it to avoid transferring the pdf over the web?

Because hitting the download button (recommended workaround) does the same,
right?

Seems to me there this is just adding an obstacle for no real benefit?

Or do I miss something?

Thanks for the quick responses!

**Comment by shoeper** [comment]
Some people did have concerns about their super private data. That's why it was disabled for encrypted library. So it's no defect but the implemented and aspected behaviour.
