### ISSUE TITLE
[seafdav] Request entity too large with nginx as reverse proxy

### ISSUE THREAD

**Issue by hillbicks** [haiwen/seafile#1508]
Hey guys,

I'm having trouble uploading bigger files to seafile, while using nginx as an reverse proxy. Now, I already set client_max_body_size 10000M; in the server config for nginx without any luck. The thing is, even with the error log set to debug, the only thing I see in the logfiles are 

client 192.168.1.20 closed keepalive connection

messages, which is fairly normal I guess. I tried two different clients on android. Foldersync, which actually prints the above mentioned error und webdav file manager. 

I'm able to upload a file of 17MB, but a file of 31MB size fails.

From my research I already gathered that this is not an error of seafile but rather nginx. I thought I still ask here, since it seems to come up a bit and nginx is not really showing any error messages.

Any ideas what could cause this issue?

**Comment by lins05** [comment]
Have you tried to set it to 0? i.e. "client_max_body_size 0;"

**Comment by hillbicks** [comment]
Yeah, sorry, forgot to mention that. That was actually how I tried it first, but I had no luck with that setting either. 

btw. uploading these files via the webinterface actually works, but I think this doesn't utilize seafdav, correct?

**Comment by lins05** [comment]
Yeah, upload in web browser is not related to the webdav server.

**Comment by hillbicks** [comment]
Ok, I just came a bit closer. This is definitely not an issue of nginx. I used cadaver to connect directly to the seafile webdav instance without having nginx acting as the reverse proxy. 

Result looks like this:
dav:/seafdav/Test/> put /home/hillbicks/Downloads/raring-preinstalled-armel+grouper.zip 
Uploading /home/hillbicks/Downloads/raring-preinstalled-armel+grouper.zip to `/seafdav/Test/raring-preinstalled-armel%2bgrouper.zip':
Progress: [=============================>] 100.0% of 33105588 bytes failed:
413 Request Entity Too Large

Another test with davfs revealed that I can copy the file to the mounted directory and it shows as successfully uploaded, but after a minute or so, the file is there but only with a size of 0 bytes.

Is there a specific max_filesize option for the webdav option? It can't be the general seafile config, since I'm able to upload bigger files either via the client from a desktop/mobile or via the webinterface.

**Comment by hillbicks** [comment]
Is there anything I can do about that? Is it reproducible for others? Would be really nice to get this working.

Thanks again for the help.

**Comment by killing** [comment]
What can you see in logs/seafdav.log on the server?

**Comment by hillbicks** [comment]
Soooo, turns out it was my fault, sorry about that. 

I forgot to adjust the second nginx instance I had running. Change the setting and the upload is working now.

Closing this issue now.

**Comment by liyizu** [comment]
Hi, what did you mean by the second nginx instance? I am facing the same issue..

**Comment by shoeper** [comment]
> Hi, what did you mean by the second nginx instance? I am facing the same issue..

He likely did have / has a cluster with multiple frontend nodes and forgot to increase the maximum upload size for one of them.

**Comment by shoeper** [comment]
Please ask usage questions in the forum. https://forum.seafile.com/
