### ISSUE TITLE
Same LDAP account opens several Seafile users

### ISSUE THREAD

**Issue by jschaeff** [haiwen/seafile#1510]
Hi there,

I connected Seafile to a university LDAP directory, with the config : 
LOGIN_ATTR = mail

This "mail" attribute is unique in any LDAP entry and of the form "name.surname@domain". Authentication works great this way.

But if a user logs in using "uid@domain", she also connects to seafile, but with another account, which is very annoying and confusing.

I'm not sure if this is a configuration problem or a bug. Anybody has an idea ?

**Comment by killing** [comment]
If you set 'mail' as login attribute, Seafile shouldn't look at other attributes. Does the user have multiple values for the mail attribute in LDAP server?
Can you use ldapsearch with '(mail=uid@domain)'? Does it return any results?

**Comment by jschaeff** [comment]
Yes, the search is like ldapsearch -x -h annuaire-iuem  -b ou=people,dc=domain '(mail=jonathan.schaeffer@domain)', I get only one result.

But in our LDAP registry, there are also other atributes beginning with "mail", like mailLocalAdress, and a search with any of the values in mailLocalAdress as '(mail=)' filter will return this same person.

In other words, I guess this is a LDAP configuration problem. I have to work this out.

Thanks for your help.
