### ISSUE TITLE
Update Manual for installation with correct directory layout.

### ISSUE THREAD

**Issue by hillbicks** [haiwen/seafile#1512]
Another issue I just found:

After installing 5.0.4 tree lists the following output

```
ree seafile -L 2
seafile
|-- ccnet
|   |-- mykey.peer
|   `-- seafile.ini
|-- conf
|   |-- ccnet.conf
|   |-- seafdav.conf
|   |-- seafile.conf
|   `-- seahub_settings.py
|-- installed
|   `-- seafile-server_5.0.4_x86-64.tar.gz
|-- seafile-data
|   `-- library-template
|-- seafile-server-5.0.4
|   |-- check_init_admin.py
|   |-- reset-admin.sh
|   |-- runtime
|   |-- seaf-fsck.sh
|   |-- seaf-fuse.sh
|   |-- seaf-gc.sh
|   |-- seafile
|   |-- seafile.sh
|   |-- seahub
|   |-- seahub.sh
|   |-- setup-seafile-mysql.py
|   |-- setup-seafile-mysql.sh
|   |-- setup-seafile.sh
|   `-- upgrade
|-- seafile-server-latest -> seafile-server-5.0.4
`-- seahub-data
    `-- avatars

13 directories, 17 files
```

However, the output of the same command lists different directories and files, which apparently changed from the version 1.8.2 that was used as an example.

http://manual.seafile.com/deploy/using_mysql.html

EDIT :I just saw that there is an additional chapter referring to the directory changes in version 5, but still think this should be mentioned in the installation chapter. :)

**Comment by shoeper** [comment]
feel free to submit a pr

**Comment by shoeper** [comment]
The direcory structure is not really of importance. It's more a technical documentation, than a guide.
