### ISSUE TITLE
`GLIBC_2.15' not found, and `GLIBC_2.17' not found

### ISSUE THREAD

**Issue by Nindaleth** [haiwen/seafile#1514]
I can't start seahub/seafile after update from 5.0.3 to 5.0.4 on Raspberry Pi 2 - using Raspbian.

```
$ cat /etc/issue
Raspbian GNU/Linux 7
$ uname -rm
4.1.13-v7+ armv7l
$ ./seafile.sh start

/home/admin/seafile/seafile-server-5.0.4/seafile/bin/seafile-controller: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.15' not found (required by /home/admin/seafile/seafile-server-5.0.4/seafile/lib/libevent-2.0.so.5)
/home/admin/seafile/seafile-server-5.0.4/seafile/bin/seafile-controller: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.17' not found (required by /home/admin/seafile/seafile-server-5.0.4/seafile/lib/libevent-2.0.so.5)
/home/admin/seafile/seafile-server-5.0.4/seafile/bin/seafile-controller: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.15' not found (required by /home/admin/seafile/seafile-server-5.0.4/seafile/lib/libglib-2.0.so.0)
/home/admin/seafile/seafile-server-5.0.4/seafile/bin/seafile-controller: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.17' not found (required by /home/admin/seafile/seafile-server-5.0.4/seafile/lib/libglib-2.0.so.0)
```

**Comment by shoeper** [comment]
https://forum.seafile-server.org

**Comment by Nindaleth** [comment]
The only advice I found in the forums is to upgrade from Debian Wheezy to Debian Jessie. Doing a major Linux distribution upgrade because of a maintenance release is unreasonable.

I found this exact issue being discussed in a more proper place: https://github.com/haiwen/seafile-rpi/issues/12

**Comment by shoeper** [comment]
I use Seafile on wheezy here and it works. Github is an issue tracker and no support platform. So if there is a problem with your setup discuss it on the forums and if it really is a bug you can open a ticket here (in 90% < of the cases it is no bug).

**Comment by Nindaleth** [comment]
I agree with you. 
However, this is a bug specific to Raspberry Pi which was already confirmed by the official developer/package maintainer. More details can be seen in the link I posted in my previous comment.

**Comment by shoeper** [comment]
Yes so this can get closed because there is another issue at the right place.
