### ISSUE TITLE
Accept certificates after cert change

### ISSUE THREAD

**Issue by Loris1123** [haiwen/seafile#1518]
I just added a new domain to my lets encrypt certificate and pointed the certificate location in nginx to the new one.  
Now the seafile clients (android and Linux)  ask my multiple times to accept the new certificate. After I told to accept it, the client asks me again...and again... and again... Even when I tell toaccept the certificate permanently, It asks me again.

**Comment by shoeper** [comment]
The problem is likely to be a missing chain on server site. Because of that the certificate is untrusted.

https://forum.seafile-server.org/

**Comment by Loris1123** [comment]
Oh damn I'm sorry. I just recognized, the message didn't come from seafile. It was just a simple Dialog-box without an app name. So It was hard to see. I'll close this.
