### ISSUE TITLE
Full drive causes >failed to run "ccnet-server -t". Not able to start MySQL database, nor seaf-gc.sh

### ISSUE THREAD

**Issue by infinity85** [haiwen/seafile#1521]
Hello,
today I stumbled over a very serious issue, as this makes it impossible for me to recover my seafile database:

```
root@bananapi:~# service seafile start
failed to run "ccnet-server -t"
```
The reason is shown by starting MySQL manually:

```
root@bananapi:~# service mysql start
[FAIL] /etc/init.d/mysql: ERROR: The partition with is too full! ... failed!
```
After syncing my library on my testsystem yesterday (don't worry, no important data) and restarting my server, seafile could not be startet anymore. Starting seafile manually pointet me to the above shown code quote blocks.

Well... the problem is now, that the drive is completely full without any warning before. Now I can't even start seaf-gc.sh to clean up, thus to free some space to be able starting seafile again:

root@bananapi:/srv/seafile/seafile-server-latest# ./seaf-gc.sh

```
Starting seafserv-gc, please wait ...
SQLException: Failed to start connection pool -- Can't connect to MySQL server on '127.0.0.1' (111)
 raised in ConnectionPool_start at src/db/ConnectionPool.c:287
seafserv-gc run done
```

Fortunately this is only a testsystem, but I would freak out if this happened on my 250GB seafile Server, which has data of more than a year. 

Why could that happen without a warning or so? As the system is freshly installed I can't even delete something to free some space. So what shall I do in such a case to recover my data? I can't dump the MySQL databases as you can see :(. 

Please add some kind of fail-safe system (and warnings) to avoid this serious behaviour.

(Running Server 5.0.4 and Client 5.0.4)

**Comment by freeplant** [comment]
You can remove logs and other unused files to reclaim space. It is a nice to have feature for Seafile to add a disk monitor feature. But there are other tools can do this better.
