### ISSUE TITLE
Seahub down due to server hiccup

### ISSUE THREAD

**Issue by magarto** [haiwen/seafile#1522]
After testing my Seafile server with a server security scanner suite called Arachni, seahub crashes with this message "seahub down due to server hiccup".
https://github.com/Arachni/arachni
I cannot restart service, only a reboot fixes it. I'm using last Seafile raspberry server release.

**Comment by lins05** [comment]
Please refer to http://manual.seafile.com/faq.html#website-displays-page-unavailable-what-can-i-do
