### ISSUE TITLE
provide library-access via network protocols (smb/nfs)

### ISSUE THREAD

**Issue by ikcalB** [haiwen/seafile#1525]
I think some developers mentioned, that acces via smb/nfs was not possible. Lately I tried out the fuse-webdav approach, which is unusably slow.

I cannot see, why providing nfs/smb server-side endpoints should not be possible: As for webdav and the webinterface you need an API which is able to
- list files & dirs
- is able to get a copy of a file as soon as it is requested

Wouldn't that suffice, to mount a seafile library as nfs/smb/whatever network-share?

**Comment by shoeper** [comment]
Properly implementing this would take too much time. It won't be implemented in foreseeable future.
