### ISSUE TITLE
Huge IOPS (READ) on storage when finishing upload.

### ISSUE THREAD

**Issue by Yotouille** [haiwen/seafile#1526]
Hi there,

I've encountered monstruous read IOPS on disk when benchmarking seafile upload. We're using a Debian (jessie) VM at 2x3Ghz / 2GB ram (ESX). Seafile is deployed with nginx fastcgi.  
During the test, the VM create one huge IOPS peak __reading__ on storage, this happen when Seafile is "saving" an uploaded file weighing ~1GB or more. The highest peak climbed at __+9619 IOPS__ (!!!) for an humble 3,7GB file...  
Test: doubling ram (total: 4GB) => same results  
  
IOPS Graph from vSphere Client:  
![iops_seafile](https://cloud.githubusercontent.com/assets/17159346/12949528/aea0fc3a-d008-11e5-8104-98eb4039f35f.jpg)  

Do you think I can optimize this ?  
  
_nb: the "little" peak corresponding to 650MB file test, climbed up to 200 IOPS, even this is not acceptable..._

**Comment by shoeper** [comment]
It is very likely that you'd upload those through the webinterface. Just read on Seafile architecture and you know where those peaks do come from and that Seafile wasn't designed to upload multi gigabit files through the webinterface or WebDAV (through the Desktop clients this is going to work well also for big files e.g. 100 GiB) in the beginning (but there were already huge improvements in the past).

**Comment by Yotouille** [comment]
Hello Sven,

Forgive me, for my post might not be explicit. All the tests were made
through Seafile Client (win 5.0.4), and each time with one and a lonely
file from 0,6 to 3,5GB.

**Comment by killing** [comment]
Hi,

I guess you're using the cloud file browser to upload file. This is the same as uploading from the web interface. Syncing a file up to the file won't have such high IOPS.

**Comment by Yotouille** [comment]
Ok !

Thanks a lot for your help !!

**Comment by Yotouille** [comment]
I've forgotten to ask you a question, if I may,

About these IOPS peaks, is it some behaviour related to Seafile, or
something external related to web servers or browsers,etc..?

The real question is, do you plan to optimize this IOPS behaviour in the
future, or you cannot do much about it ?


Thanks again.

**Comment by killing** [comment]
This is because Seafile first store the uploaded file as a temp file, then read the temp file to divide it into blocks. There is not much room for optimization.
