### ISSUE TITLE
Is it possible to use seafile server with LDAP by davmail?

### ISSUE THREAD

**Issue by shiquanwang** [haiwen/seafile#153]
I want to setup a seafile server with accounts from the company accounts.
The company uses exchange server so davmail can be used to do the translation.

Is it possible?
If yes, then how to set the ccnet.conf for below sections, e.g., company email is: username@companyname.com

```conf
HOST = ldap://192.168.1.123/
BASE = ou=users,dc=example,dc=com
USER_DN = cn=admin,dc=example,dc=com
PASSWORD = secret
LOGIN_ATTR = mail
```

**Comment by neohob** [comment]
@ronakbanka I got the same problems: user-mgr.c(360): ldap_search failed: Bad search filter, could u pls paste working [LDAP] properties in ccnet.conf to me ?  I searched whole google only here maybe has solution to fix this problem; holp u can see my text, thanks!
