### ISSUE TITLE
Seafile linux client 5.0.5 disappears synced folder from main window

### ISSUE THREAD

**Issue by dancebeatfm** [haiwen/seafile#1531]
Hello Seafile team.
I'm using Seafile client 5.0.5 with seafile pro server.
In client, when i choose from file cloud browser one folder from library to sync, client shows me in main window that folder is synchronizing, when i push the refresh button in client, folder disappears from main window, but client is still synchronizing the folder in background. 
When client is synchronized the folder, the folder is still invisible in main window, but when i choose one more time exactly that folder to sync in file cloud browser, then folder shows up in main window.

**Comment by shoeper** [comment]
https://forum.seafile-server.org/t/seafile-linux-client-5-0-5-disappears-synced-folder-from-main-window/4158

**Comment by lins05** [comment]
Fixed in https://github.com/haiwen/seafile-client/commit/9716101
