### ISSUE TITLE
.DS_Store => create/delete folder wars

### ISSUE THREAD

**Issue by gerardkok** [haiwen/seafile#1532]
We're seeing folders in certain libraries that are deleted by a user automatically resurrected a few minutes later, seemingly by another user that uses the same library. I haven't tested it extremely thoroughly, but I think this is related to .DS_Store files that exist in the second user's library, and, although they are not synced, prevent folders that contain those .DS_Store files from being deleted. Presumably this causes those folders to reappear in the Seafile folder of the first user.

.DS_Store files are artefacts from the OS X Finder. On local disks you cannot prevent them from appearing (there are some options on OS X < 10.11, but on El Capitan, System Integrity Protection doesn't allow you to prevent those .DS_Store files from being created on local disks).

Environment:
server: 4.4.7 Pro on Ubuntu 14.04
client: 5.0.3 on OS X 10.11.3

Steps to reproduce:
- construct a library with access for two users ('Alice' and 'Bob')
- have both users sync the library to their OS X laptop/desktop
- have Alice construct a folder inside this library, for good measure construct a test file in this folder ('test.doc')
- wait till the library has been synced to Bob
- have Bob create a '.DS_Store' file inside the folder (if you can't get the Finder to create one, just 'touch' it in the Terminal)
- have Alice delete the folder
- watch Bob's folder... 'test.doc' will be deleted, but the folder won't
- watch Alice's library: the folder will reappear, but without the 'test.doc' testfile

Workaround:
- remove .DS_Store files from all Seafile synced folders regularly. We're doing that now with puppet every half hour. I'm not sure if this will upset users, but we'll see.

A better fix might be to allow Seafile to delete folders from synced libraries that:
- have been deleted on the server
- are empty, or only contains files that are on Seafile's ignore list.
Admitted this might have unintended consequences that I do not realise, but it seems to me this can better be fixed in the Seafile client than through the above workaround.

**Comment by killing** [comment]
This is bug. We'll fix it in the next release.

**Comment by freeplant** [comment]
It should be fixed in v5.0.6.
