### ISSUE TITLE
New account passwords are sent in cleartext over email

### ISSUE THREAD

**Issue by gdm85** [haiwen/seafile#1534]
I noticed that when creating a new account through an existing admin account, the user will receive the password in cleartext.

This is a bad practice (random google hit: http://security.stackexchange.com/a/17981) and when evaluating applications for security it gives them a negative score.

Would it be desirable and possible to not send cleartext passwords and rather send a password reset link?

**Comment by coloradomountain** [comment]
I'll take a look at the code, you should always use a reset link. At no point should anyone but the user know the plaintext password.

**Comment by shoeper** [comment]
This has been solved in v5.1 by forcing the user to change his password on first login.

https://seacloud.cc/group/3/wiki/server-changelog

**Comment by gdm85** [comment]
@shoeper sorry, this is not solved. If the password is sent in cleartext (even once) it can still be intercepted and an impersonator can login instead of the supposed recipient.

The vulnerability is the same if you do it once or 1000 times.

**Comment by shoeper** [comment]
The same can be done sending a link to set a new password.

What do you propose instead?

**Comment by gdm85** [comment]
@shoeper I thought that by assigning a time validity (like the link is valid for x hours), the issue is reasonably covered. Not sure that would be viable/desirable with a password?

**Comment by shoeper** [comment]
But in that case if an attacker would be able to intercept the traffic he'd simply use the reset password function to get a valid link.

So I don't think there is a much better solution. Not using email is also no solution because it won't be easy enough without email. If of large importance an administrator could configure the smtp server to only deliver mail via smtps.
