### ISSUE TITLE
JPG File Preview with Seafile 5.0.4 in IE 11 not working

### ISSUE THREAD

**Issue by andi-blafasl** [haiwen/seafile#1535]
Preview of JPG Files in IE 11 is not working with Seafile Server 5.0.4. You only get the message "The Image could not be loaded." If you click on the link "The Image" the file is downloaded and displayed localy. With Chrome there is no such problem!
I digged a bit deeper in to the Problem with the "F12" Tools of IE and Chrome. 
In chrome:

1. A GET request to the image file with path /repo/xxx/raw/path/image.jpg with the respons http 302 found with the url /seafhttp/files/xxx/image.jpg
2. A GET request to the image with path /seafhttp/files/xxx/image.jpg with a http 200 ok

In IE 11:

1. A GET request to the image file with path /repo/xxx/raw/path/image.jpg with the result http 302 found with the url /seafhttp/files/xxx/image.jpg
2. A GET request to the image with path /seafhttp/files/xxx/image.jpg with the result (canceled)

After disableing HTTPS on the server for the network sniffer tests, I also get a respons 200 within IE.

The server log files reveal no errors and the access.log of the webserver shows that all requests where received normaly and the respons to all looks identical.

I digged a little bit deeper with wireshark to see the requests on the wire. And I found the following:

Request in chrome:

    GET /repo/xxx/raw/path/image.jpg HTTP/1.1
    Host: example.com
    Connection: keep-alive
    Accept: image/webp,image/*,*/*;q=0.8
    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
    Referer: http://example.com/
    Accept-Encoding: gzip, deflate, sdch
    Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
    Cookie: sessionid=xyz; csrftoken=xyz

Request in IE:

    GET /repo/xxx/raw/path/image.jpg HTTP/1.1
    Accept: image/png, image/svg+xml, image/*;q=0.8, */*;q=0.5
    Referer: http://example.com/
    Accept-Language: de-DE
    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
    Accept-Encoding: gzip, deflate
    Host: example.com
    Connection: Keep-Alive
    Cookie: sessionid=xyz; csrftoken=xyz

And both browsers are receiving the JPG File from the server with a http 200 ok! As far as I can see, the only difference is the "Accept" line in the headers.
It's very strange behavior of IE that it doesn't show the Image. Maybe it has something to do with the java script that is loading the Image overlay?
I'm a network admin and not a programmer. So from here I'm a bit lost. Maybe some one can check this functionality within IE. 
It would be very nice to have a woking Preview again!

**Comment by freeplant** [comment]
We have received report that the JPG preview can work with IE11 with v4.4 server and can't work since v5.0.4 server? Actually we haven't change related code.

Can you help us testing the v4.4 server and check what's the difference from HTTP request/response? This can save the developer quite a lot time.

**Comment by andi-blafasl** [comment]
Fast replay as always! Thank you. I will set up a v4.4 server and do the the test. No problem.

**Comment by andi-blafasl** [comment]
Just installed Seafile Server v4.4.5. Could not install v4.4.6 because the download is corrupt. gzip throws error "invalid compressed data--crc error"

v4.4.5 is setup behind apache with mod_proxy_fcgi, exactly the same as on my v5.0.4 server, but with sqlite db instead of mysql.

The Preview of JPG files is working in IE11 out of box.

There is no difference in the request from IE11 to v4.4 vs v5.0 Server

Request/Response v4.4:

    GET /repo/xxx/raw/image.jpg HTTP/1.1
    Accept: image/png, image/svg+xml, image/*;q=0.8, */*;q=0.5
    Referer: http://v4.example.com/
    Accept-Language: de-DE
    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
    Accept-Encoding: gzip, deflate
    Host: v4.example.com
    Connection: Keep-Alive
    Cache-Control: no-cache
    Cookie: csrftoken=xyz; sessionid=xyz
    
    HTTP/1.1 302 FOUND
    Date: Wed, 24 Feb 2016 16:59:04 GMT
    Server: Apache
    Vary: Accept-Language,Cookie
    Content-Language: de
    Location: http://v4.example.com/seafhttp/files/xxx/image.jpg
    Keep-Alive: timeout=5, max=100
    Connection: Keep-Alive
    Transfer-Encoding: chunked
    Content-Type: text/html; charset=utf-8
    
    0
    
    GET /seafhttp/files/xxx/image.jpg HTTP/1.1
    Accept: image/png, image/svg+xml, image/*;q=0.8, */*;q=0.5
    Referer: http://v4.example.com/
    Accept-Language: de-DE
    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
    Accept-Encoding: gzip, deflate
    Host: v4.example.com
    Connection: Keep-Alive
    Cache-Control: no-cache
    Cookie: csrftoken=xyz; sessionid=xyz
    
    HTTP/1.1 200 OK
    Date: Wed, 24 Feb 2016 16:59:04 GMT
    Server: Apache
    Last-Modified: Wed, 24 Feb 2016 16:59:04 GMT
    Cache-Control: max-age=3600
    Access-Control-Allow-Origin: *
    Content-Type: image/jpg
    Content-Length: 133333
    Content-Disposition: inline;filename="image.jpg"
    Keep-Alive: timeout=5, max=99
    Connection: Keep-Alive

request/response v5.0:

    GET /repo/xxx/raw/image.jpg HTTP/1.1
    Accept: image/png, image/svg+xml, image/*;q=0.8, */*;q=0.5
    Referer: http://v5.example.com/
    Accept-Language: de-DE
    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
    Accept-Encoding: gzip, deflate
    Host: v5.example.com
    Connection: Keep-Alive
    Cache-Control: no-cache
    Cookie: csrftoken=xyz; sessionid=xyz
    
    HTTP/1.1 302 FOUND
    Date: Wed, 24 Feb 2016 17:24:44 GMT
    Server: Apache
    Vary: Accept-Language,Cookie
    Content-Language: de
    Location: http://v5.example.com/seafhttp/files/xxx/image.jpg
    Content-Length: 0
    Keep-Alive: timeout=5, max=100
    Connection: Keep-Alive
    Content-Type: text/html; charset=utf-8
    
    GET /seafhttp/files/xxx/image.jpg HTTP/1.1
    Accept: image/png, image/svg+xml, image/*;q=0.8, */*;q=0.5
    Referer: http://v5.example.com/
    Accept-Language: de-DE
    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
    Accept-Encoding: gzip, deflate
    Host: v5.example.com
    Connection: Keep-Alive
    Cache-Control: no-cache
    Cookie: csrftoken=xyz; sessionid=xyz
    
    HTTP/1.1 200 OK
    Date: Wed, 24 Feb 2016 17:24:44 GMT
    Server: Apache
    Last-Modified: Wed, 24 Feb 2016 17:24:44 GMT
    Cache-Control: max-age=3600
    Access-Control-Allow-Origin: *
    Content-Type: image/jpg
    Content-Length: 133333
    Content-Disposition: inline;filename="image.jpg"
    X-Content-Type-Options: nosniff
    Keep-Alive: timeout=5, max=99
    Connection: Keep-Alive

I can only see two differences, but this are two different servers as well. And v4.4 was quick and dirty setup without exactly the same apache setup on both servers ;-)

I think the Problem have nothing to do with the "network layer".

BTW: preview of PNG files is working with IE11 and v5.0 server !

**Comment by andi-blafasl** [comment]
I upgraded my Test v4.4 server to 5.0.2 to test if the problem was there from the beginning. And yes, v5.0.2 -> no preview of JPG in IE11

BTW my IE11 is running in EDGE mode without compatibility Settings for Intranet Sites or something.

If I can do any further test, let me know,

**Comment by freeplant** [comment]
Okay, we find the problem. It is actually caused by the line

    X-Content-Type-Options: nosniff

which was intended to improve the security. Adding an exception for JPG should solve the problem.

**Comment by freeplant** [comment]
The fix is here: https://github.com/haiwen/seafile/commit/2ba649666171a230b3450ea066299f462ab70834

**Comment by andi-blafasl** [comment]
Are you sure about the option? The `X-Content-Type-Options: nosniff` is also present when previewing a PNG file. And this is displayed with v4.4 and v5.0.x

**Comment by freeplant** [comment]
Yes. After the fix, JPG can work again on my IE 11. It is IE11's problem in handling JPG with nosniff.

**Comment by andi-blafasl** [comment]
Perfect! Where can I get updated bineries with the fix? I don't want to downgrade to v4.4 and my users realy need the preview in IE because this is our default browser on the terminal servers.

**Comment by freeplant** [comment]
We will release an updated version in the next week.

**Comment by andi-blafasl** [comment]
I can confirm that the problem is fixed with version v5.0.5. You can update the download link on your homepage ;-)

If someone still encounters the error with v5.0.5 try to clear the browser cache. I had this issue with one of my installations.

Thank you very much for the fast fix!

**Comment by abenum** [comment]
Hi!
How can I fix this issue in v5.0.3 for Windows Server?
Which file am I supposed to change?
Appreciate Your help!


Running v5.0.3 on Windows 7 With HTTPS.
