### ISSUE TITLE
Webdav not working - Blank page

### ISSUE THREAD

**Issue by dbeuchler** [haiwen/seafile#1539]
I tried to run seafdav with the current seafile version (5.0.4) on ubuntu 14.04 server. I added the FastCGIExternalServer to my apache.conf:

`FastCGIExternalServer /var/www/%path_to_document_root%/seafdav.fcgi -host 127.0.0.1:8080`

and also configured the vhost_ssl.conf as follows:
```
Alias /media /var/haiwen/seafile-server-latest/seahub/media

RewriteEngine On

<Location /media>
    Require all granted
</Location>

#
# seahub
#
SetEnvIf Request_URI . proxy-fcgi-pathinfo=unescape
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
ProxyPass / fcgi://127.0.0.1:8000/

#
# seafile fileserver
#
ProxyPass /seafhttp http://127.0.0.1:8082
ProxyPassReverse /seafhttp http://127.0.0.1:8082
RewriteRule ^/seafhttp - [QSA,L]

#
# seafile webdav
#
RewriteCond %{HTTP:Authorization} (.+)
RewriteRule ^(/seafdav.*)$ /seafdav.fcgi$1 [QSA,L,e=HTTP_AUTHORIZATION:%1]
RewriteRule ^(/seafdav.*)$ /seafdav.fcgi$1 [QSA,L]
```

If I connect via Chrome or Firefox, I only get a blank page. My apache log says:
`[27/Feb/2016:17:10:27 +0000] "GET /seafdav HTTP/1.0" 400 314 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"`

also with a webdav client: 
`[27/Feb/2016:17:17:24 +0000] "OPTIONS /seafdav HTTP/1.0" 400 314 "-" "ReaddleDAV Documents/5.5.5.218 (redirects)"`

Installed Apache: Apache/2.4.7

With my old server (Apache/2.2.22) everything was fine.

Any suggestions?

**Comment by killing** [comment]
Please post configuration related issues on the forum. Here is only for bug tracking. https://forum.seafile-server.org/
