### ISSUE TITLE
feature request: list of changed files + selective pause/resume

### ISSUE THREAD

**Issue by qnxor** [haiwen/seafile#1541]
I have been on a metered connection for a while so I have to pause sync'ing when I work or else it eats all my bandwidth due to frequent updates (i know I can also set a sync interval). When I resume sync'ing it sometimes has too much to upload from a single library. I sometimes want a single file uploaded so my collaborators can get it, but it doesn't get uploaded because tons of other (sometimes bigger) files are being uploaded first and I have no control over the process.

Two suggestions:

1. While on Pause, or not, It would be great if I could see the list of all changed files since the last sync. That way I could temporarily exclude some of the large files form Sync'ing so that the ones I'm interested in get uploaded first.

1. Secondly, when listing the changed files, it would be great to have a checkbox next to each file and folder that would pause sync'ing for it ... it could be as simple as adding/removing a line in `seafile-ignore.txt` for the library.

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.

**Comment by qnxor** [comment]
Ok, I'll contact you via email. I posted in the forum too nonetheless.
