### ISSUE TITLE
add ldap user(s) to seafile group not working

### ISSUE THREAD

**Issue by neo-luddite** [haiwen/seafile#1542]
I try to add ldap users to a seafile group. If I press "Add members" and search for the according user, the user is shown, I can select him/her and press "submit", seafile announces "successfully added" (in green) but the user doesn't show up in the according group.

I can add local users to the group. the format of the ldap users is not "example@test.net" but only "example".

browser reload doesn't help, no error messages in seafile logs, userlogin via ldap works.
I'm using  seafile-5.0.5 64bit-CE on ubuntu 14.04

**Comment by freeplant** [comment]
As in our document, only email or userPrincipleName is supported as login attribute. Other non-email like field can't work.

**Comment by neo-luddite** [comment]
ah, ok thanks!
groups are working with "mail" as ldap filter. 
 "uid" works for login, but not for groups  :)
