### ISSUE TITLE
Admin misreports file counts until user updates their library

### ISSUE THREAD

**Issue by tomchiverton** [haiwen/seafile#1545]
Logged in as admin in /sys/seafadmin/ several libraries report sizes (some several gigs) but zero files.

Seafile Pro 5.0.6 on Fedora 23 64bit.

**Comment by killing** [comment]
The file count is only updated when a library is updated. For existing libraries, the file count will remain 0. Is this your case?

**Comment by tomchiverton** [comment]
Yes

**Comment by shoeper** [comment]
It is the expected behaviour.
