### ISSUE TITLE
SF5.0.3 Paths for garbage collector doesn't match

### ISSUE THREAD

**Issue by Lillecarl** [haiwen/seafile#1552]
> C:\SeafileProgram\seafile-server-5.0.3\seafile\bin>seafserv-gc.exe -c D:\seafile-server\conf
-------------------------------------------------------------------------------------
> [03/14/16 15:45:00] seafile-session.c(41): Config dir dir D:\seafile-server\conf\seafile-data does not exist
> [03/14/16 15:45:00] seafserv-gc.c(152): Failed to create seafile session.
> 
> C:\SeafileProgram\seafile-server-5.0.3\seafile\bin>

> C:\SeafileProgram\seafile-server-5.0.3\seafile\bin>seafserv-gc.exe -c D:\seafile-server\
-------------------------------------------------------------------------------------
> [03/14/16 15:46:27] Can't load config file D:\seafile-server/ccnet.conf.
> [03/14/16 15:46:27] seafserv-gc.c(143): Read config dir error
> 
> C:\SeafileProgram\seafile-server-5.0.3\seafile\bin>

> C:\SeafileProgram\seafile-server-5.0.3\seafile\bin>seafserv-gc.exe -c D:\seafile-server\conf -d D:\seafile-server\seafile-data
-------------------------------------------------------------------------------------
> [03/14/16 15:47:37] seafile-session.c(61): Failed to load config file.
> [03/14/16 15:47:37] seafserv-gc.c(152): Failed to create seafile session.
> 
> C:\SeafileProgram\seafile-server-5.0.3\seafile\bin>

However i set the config parameters it doesn't seem to be satisfied. 

There's no good guide for doing garbage collection on Windows either, so i'm stuck here. I'd like to run the garbage collector weekly.

Best Regards
Carl Hjerpe

**Comment by lins05** [comment]
You should use the `gc.bat` script (with admin account) instead of running `seaf-gc.exe` manually. The script takes care of setting up the environement, and calling into the `seafserv-gc` program

 You can find the script in `seafile-server-5.0.3` folder. Right click on it, and choose "run as administrator".

**Comment by pvagner** [comment]
I am on Arch linux running Seafile server 5.1.4. installed as an [AUR package](https://aur.archlinux.org/packages/seafile-server/). I was a bit confused on how to run seafserv-gc according to the [documentation](http://manual.seafile.com/maintain/seafile_gc.html). I am not sure this is the correct place to post this but I was directed here from a google search so other people might see this as well.
Although there is a gc.sh / gc.bat script, it may not well suit all the configurations, so it's good idea to know how to run seafserv-gc binary manually.
The AUR package installs seafile-server to the standard locations e.g. /usr/bin /usr/lib /usr/share and so on, so all the binaries are in the system path.
My path reffered to as the top directory of this seafile server instance is at /srv/seafile/myexampledomain.com
I can run seafserv-gc like this:
# ROOT_SF_DIR="/srv/seafile/myexampledomain.com"
# cd $ROOT_SF_DIR
# sudo su seafile seafserv-gc --dry-run -c $ROOT_SF_DIR/ccnet -d $ROOT_SF_DIR/seafile-data -F $ROOT_SF_DIR/conf
