### ISSUE TITLE
Feature Request - Libraries - multiple owners

### ISSUE THREAD

**Issue by programster** [haiwen/seafile#1555]
Seafile is a fantastic tool that I have been making personal use of for a long time now. It's been so good and stable that I have gotten others at my workplace to use it as well. The encryption functionality, along with the ability to have full control over our own data by hosting it ourselves is the big reason we aren't just using a provider like Dropbox. So a big thank you for open sourcing it and continuing to offer this free solution.

### The Problem
An issue that keeps coming up for us over and over is that a library can only be owned by one person, and only that person can grant others access. Even I, as the admin, cannot grant access to a library on another person's behalf. This can cause issues mainly because our staff work in different time zones, so an access request can take hours to be actioned. Also, people tend to take holidays, and may not think about transferring the libraries that they own to somebody else before going on leave. Please can we allow a library to be owned by multiple people, or at least allow admin's to grant access to other people?

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.
