### ISSUE TITLE
fuse mount option ro

### ISSUE THREAD

**Issue by hungerburg** [haiwen/seafile#1557]
When looking at the output of "mount" I see the seaf-fuse as "rw"
Thankfully seaf-fuse allows to pass mount options, eg. -o ro
`seaf-fuse.sh start -o ro -o uid=1000 -o allow_other /home/samba/seafile/`
As long as seaf-fuse only provides for ro-access, that might be good to hardcode?

**Comment by killing** [comment]
This is a good point. We'll add it.

**Comment by hungerburg** [comment]
Thank you, good to learn I did not do something stupid. I use the mount, mostly so disk backup contains the seafile data in its expanded, plain view - just in case, that is. One can also chain options like in fstab:
`seaf-fuse.sh start -o ro,uid=1000,gid=100,allow_other /home/samba/seafile/`
