### ISSUE TITLE
Consume the Web Api with a JavaScript WebApp

### ISSUE THREAD

**Issue by enguerran** [haiwen/seafile#1559]
I am building a JavaScript WebApp (using AngularJS).

I add the following header to the request "Authorization: Token _accesstoken_" but  I cannot request `/auth/ping` as I get an 403 status code on the preflight OPTIONS.

I do not know where to find. Any tips?

**Comment by enguerran** [comment]
The issue was closed, but no comment was given.
I guess it's due to an oversight, I am available for more detail.

**Comment by freeplant** [comment]
I have answered your question in the forum.

**Comment by enguerran** [comment]
Oh, thank you very much. I put the link here if it can help people: https://forum.seafile-server.org/t/cors-et-cross-origin-allow-access/4368
