### ISSUE TITLE
Documentation apache mod_proxy_fcgi version

### ISSUE THREAD

**Issue by mb-dbc-dk** [haiwen/seafile#1563]
In issue #1258 there's referenced from http://manual.seafile.com/deploy/deploy_with_apache.html

There is discussion about version 2.4.10 of apache, however a note about "unescaped" first appearance in official version 2.4.12 (some distributions like ubuntu, has backports to their 2.4.10 version, as I read it) would be nice.

2.4.12 changelog:
http://svn.apache.org/viewvc/httpd/httpd/tags/2.4.18/CHANGES?revision=1718693&view=markup#l457
fcgi mention:
http://svn.apache.org/viewvc/httpd/httpd/tags/2.4.18/CHANGES?revision=1718693&view=markup#l502

Having spend quite some time trying to resolve the #1258 issue on debian jessie with 2.4.10 from backports,which hasn't got the patch. I would like others not to waste their time on the same issue.

/Bøgeskov

**Comment by shoeper** [comment]
Thanks for the hint, it's actually 2.4.11 or did I miss something?

**Comment by mb-dbc-dk** [comment]
From the changelog.

Changes with Apache 2.4.11 (not released)

I just assumed (I know I shouldn't, I should check), that there's  2.4.11 version
Checked archive and, Yep no 2.4.11 changelog in http://archive.apache.org/dist/httpd/

**Comment by nuxwin** [comment]
See also:

- https://i-mscp.net/index.php/Thread/16921-Seafile-Apache2-mod-proxy-fcgi-PATH-INFO-handling/?postID=54464#post54464

for patching Apache 2.4.10 on Debian Jessie. The script is attached below.
[apache2_postinst.sh.zip](https://github.com/haiwen/seafile/files/1073084/apache2_postinst.sh.zip)
