### ISSUE TITLE
Issues migrating to s3

### ISSUE THREAD

**Issue by psalaberria002** [haiwen/seafile#1564]
Hei,

I have some issues when migrating an existing seafile storage to s3.

I uploaded blocks, fs and commits to s3 using `aws s3 cp . s3://... --recursive`. It created a folder structure similar to the one in the disk. However Seafile server keeps saying "Commit c3685afe-ba8d-45a4-a2df-051f1da91ae7:cc57c9304acfc72ec8bb5b39ea983834f1da8712 is missing". There is a file in s3 under c3685afe-ba8d-45a4-a2df-051f1da91ae7/cc/57c9304acfc72ec8bb5b39ea983834f1da8712.

If I create a new library, the file structure in s3 is different. "cc" folder does not exist anymore, and it becomes part of the name of the object. e.g. "c3685afe-ba8d-45a4-a2df-051f1da91ae7/cc57c9304acfc72ec8bb5b39ea983834f1da8712"

I find this really confusing. Is there an easy way to migrate existing libraries to s3? And from s3 back to disk?

Thank you.

**Comment by shoeper** [comment]
You need to combine the folder and filename to be the new object name. On the file system the first to characters of the file name are used as foldername, to not have too many files in the same folder.

So e,g, c3685afe-ba8d-45a4-a2df-051f1da91ae7/cc/57c9304acfc72ec8bb5b39ea983834f1da8712 on fs needs to be c3685afe-ba8d-45a4-a2df-051f1da91ae7/cc57c9304acfc72ec8bb5b39ea983834f1da8712 on s3,

**Comment by psalaberria002** [comment]
Thanks you for the fast reply.

Yes, I understood that already. My question was if there is any fast way to migrate an existing library (18.5GB) to s3. I could write a script that does the migration, but I was wondering if there is already an existing tool.

**Comment by yield65** [comment]
@psalaberria002 
Hi, I just hit that wall, tried to migrate my local storage to S3, did you have any tips that can help me?

**Comment by psalaberria002** [comment]
@yield65  I had some issues trying to migrate to s3, so I decided to upload all the files from scratch after setting up s3 as the storage backend. 

However, I created a python script for uploading the files in the expected format. I am not sure if this will work, but you could give it a try.

```
import boto
import os
from boto.exception import S3CreateError

#Make sure you run the script from the storage directory. The one containing fs, blocks and commits folders.

#CHANGE THE VALUES!!!
#The buckets need to have unique names
fsBucketName="unique-seafile-fs-objects"
commitsBucketName="unique-seafile-commit-objects"
blocksBucketName="unique-seafile-block-objects"
awsProfileName="your-aws-profile"
awsRegion="eu-west-1"

s3=boto.s3.connect_to_region(awsRegion,profile_name=awsProfileName)
def get_bucket(bucketname):
    try:
        print "Creating bucket " + bucketname
        bucket=s3.create_bucket(bucketname,location=awsRegion)
    except S3CreateError:
        print "Already exists. Getting existing bucket " + bucketname
        bucket=s3.get_bucket(bucketname)
    return bucket

def uploadDirectory(path,bucketname):
    bucket=get_bucket(bucketname)
    for root,dirs,files in os.walk(path):
        for file in files:
            x = os.path.join(root,file)
            newFileName=root.split("/")[-1]+file
            print "Uploading " + newFileName + " to " + bucketname
            key=bucket.new_key(newFileName)
            key.set_contents_from_filename(x)

uploadDirectory("fs",fsBucketName)
uploadDirectory("commits",commitsBucketName)
uploadDirectory("blocks",blocksBucketName)
```
