### ISSUE TITLE
localhost e-mail service fails?

### ISSUE THREAD

**Issue by clayt0nk** [haiwen/seafile#1568]
Per http://manual.seafile.com/config/sending_email.html I am using this config snippet (blank USER/PASSWORD for no authentication)

EMAIL_USE_TLS 		= False
EMAIL_HOST 			= '127.0.0.1'	# SMTP server
EMAIL_HOST_USER 	= ''    		# username and domain
EMAIL_HOST_PASSWORD = ''    		# password
EMAIL_PORT 			= 25
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

in eahub_settings.py. All I get back is

"Sending shared link failed. Email service is not properly configured, please contact administrator".

There is nothing in logs/seahub.log

**Comment by freeplant** [comment]
Please ask installation problems in our forum.

**Comment by clayt0nk** [comment]
Nah, I will just assume either the software or the documentation is broken.
