### ISSUE TITLE
Preview & wiki svg support option

### ISSUE THREAD

**Issue by rabits** [haiwen/seafile#1572]
Hello, Guys

As I realized, SVG preview support disabled in Seafile v2.1.1, but it makes no option to enable it if required. I have wiki pages with linked svg to show charts with dynamic links - and it is not working properly.

Can be added an option to enable system, lib or wiki svg preview?

**Comment by shoeper** [comment]
Please post feature requests at https://forum.seafile-server.org/ on the wishlist.
