### ISSUE TITLE
Why Seafile can not work in the corporate intranet

### ISSUE THREAD

**Issue by voup-w** [haiwen/seafile#1573]
If i use bras, the seafile works very well.

if i disconnect bras,the seafile Mail-module done. nginx error 504
/var/log/nginx/seahub.error.log
2016/03/25 09:49:47 [error] 1417#0: *48 upstream timed out (110: Connection timed out) while reading response header from upstream, client: *.*.*.*, server: , request: "GET /api2/ping/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:8000", host: "*.*.*.*"

also,when i upload big files(such as OS iso),seafile shows "Unknown error"
i did not modify seafile.conf,and i can not find the code such as:
[fileserver]
max_upload_size=200
then i change the code to: 
max_upload_size=4096
the problem still exists.

**Comment by killing** [comment]
Deployment issues are more appropriate on the forum (https://forum.seafile-server.org/). Here is only for bug tracking. Once it's confirmed as a bug, you can open an issue here.
I'm closing this issue.

**Comment by voup-w** [comment]
Okay
 
 
------------------ Original ------------------
