### ISSUE TITLE
FieldError: Unknown field(s) (a, l, _) specified for Contact

### ISSUE THREAD

**Issue by hufeiya** [haiwen/seafile#1575]
hufeiya@hufeiya-VirtualBox:/data/haiwen$ seafile-admin setup
-----------------------------------------------------------------
This script will guide you to config and setup your seafile server.
Make sure you have read seafile server manual at

        https://github.com/haiwen/seafile/wiki

Press [ENTER] to continue
-----------------------------------------------------------------

check python modules ...
checking sqlite3
checking python imaging library(PIL)
checking django 1.5
checking djblets

It seems there already exists ccnet config files in /data/haiwen/ccnet, Do you want to use them?
[yes or no]  yes
Where do you want to put your seafile data?  (Please use a volume with enough free space)
[default /data/haiwen/seafile-data ]  

It seems there already exists seafile data in /data/haiwen/seafile-data, Do you want to use them?
[yes or no]  yes
This is your configuration
------------------------------------------
ccnet config:        use existing config in /data/haiwen/ccnet
seafile:             use existing config in /data/haiwen/seafile-data
------------------------------------------
Press ENTER if the config is right, or anything else to re-config 

Now initializing seahub database, please wait...

FieldError: Unknown field(s) (a, l, _) specified for Contact
Error: Seahub syncdb failed

Could some body help me?TX alot.

**Comment by killing** [comment]
The forum (https://forum.seafile-server.org/) is more appropriate for this issue. You can get more help from the community there. Here is only for bug tracking. When it's confirmed as a bug, it can be added here.
I'm closing this issue.
