### ISSUE TITLE
Clean database and directories periodically

### ISSUE THREAD

**Issue by Aendrew87** [haiwen/seafile#1579]
Hi,

is there a possibility to clean the database and the directories periodically?

I have some users which upload files and leave them on the server for months without using it.
So my idea is, that i could remove all the uploaded files older then, for example, 14 days.
But for that i need to know which databases/tables and directories i have to clean.

The current registered users should not be removed.
The configuration of the user should also be deleted (libraries, folders etc.).

If there is no possibility to do that, could i set the server in the initial condition (but without losing the registered users)?

**Comment by shoeper** [comment]
There is no such possibility and there won't be one.

The only thing you can do is to implement something yourself using the api.
