### ISSUE TITLE
Request: change Content-Disposition header

### ISSUE THREAD

**Issue by deseven** [haiwen/seafile#1581]
Can you please change Content-Disposition header from attachment to inline for direct links (dl=1)?

For example:
```Content-Disposition: attachment;filename="example.jpg"```
To:
```Content-Disposition: inline;filename="example.jpg"```

That way browsers will be able to show supported files directly and to open save dialog for other files.

**Comment by shoeper** [comment]
Afaik there is also ?raw which would be a better place imho.

**Comment by deseven** [comment]
Yeah, raw=1 redirects to file directly and returns Content-Disposition: inline.
Then it'll be nice to have an option in Seafile client to get this link.

**Comment by shoeper** [comment]
The problem is that it would confuse many people because they don't know what it is.
