### ISSUE TITLE
List libraries of all users

### ISSUE THREAD

**Issue by Aendrew87** [haiwen/seafile#1582]
I tried to get a list of all libraries from all users.
The token i used was from a admin account.

I used the webapi (https://cloud.seafile.com/api2/repos/) but only got my libraries.

How could i get all libraries?

**Comment by shoeper** [comment]
You did try to use the WebAPI from cloud.seafile.com?

**Comment by shoeper** [comment]
I''m not sure if there is a way, but if there is you would like first have to use http://manual.seafile.com/develop/web_api.html#list-accounts to receive all accounts and receive the library of each account in the next step. But I'm not sure if one can pass a different user to the repos api call.

**Comment by Aendrew87** [comment]
@shoeper it is not possible to pass a different user to the repos api call

So it seams that there is no solution for ticket 1579 :(
Whould i be possible to do this implementation in a further release?

**Comment by shoeper** [comment]
You can open a feature request in the forum at https://forum.seafile-server.org

**Comment by Aendrew87** [comment]
created a feature request: https://forum.seafile-server.org/t/more-flexibility-web-api/4510
