### ISSUE TITLE
Github-like markdown for Wiki

### ISSUE THREAD

**Issue by mmahmoudian** [haiwen/seafile#1584]
There are minor but useful advancements in Github version of markdown that it would be amazing to have also in Seafile. The most useful one would be the checklist and section linking.

In Github square brackets can be used to create checklists:
<https://help.github.com/articles/basic-writing-and-formatting-syntax/#task-lists>

example markdown checklist
- [ ] item1
- [x] item 2

And the section linking is automatic for every heading (the chain sign appears in the left side of the heading name (in the link above you can see that as well)

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.
