### ISSUE TITLE
Upgrade from 5.0 to 5.1 fails (MySQL)

### ISSUE THREAD

**Issue by jbbr** [haiwen/seafile#1585]
I tried to upgrade my Seafile server from 5.0.5 to 5.1.1 by runinng the upgrade_5.0_5.1.sh script. Unfortunately the database upgrade failed:

```
$ upgrade/upgrade_5.0_5.1.sh
-------------------------------------------------------------
This script would upgrade your seafile server from 5.0 to 5.1
Press [ENTER] to contiune
-------------------------------------------------------------
Updating seafile/seahub database ...

[INFO] You are using MySQL
[INFO] updating seafile database...
[INFO] updating seahub database...
[ERROR] Failed to execute sql: (1146, "Table 'c2seahub.sysadmin_extra_userloginlog' doesn't exist")

Failed to upgrade your database
```

I've installed this server back in Seafile 2.x days and upgraded since then without any problems. So thanks for providing great and smooth experience so far :)

**Comment by jbbr** [comment]
As a workaround for others having this problem:

I created the missing table manually by applying the "CREATE TABLE" code from current initial sql dump from git. There doesn't seems to be any Seafile upgrade script which adds this table.

https://github.com/haiwen/seahub/blob/a07a959fa4787d41131ba1fb0cf6efc004d43220/sql/mysql.sql#L1239

**Comment by MrEasy** [comment]
Can confirm this, coming from 5.0.5 to 5.1.1
The upgrade scripts contain an ALTER TABLE on this table, but not the CREATE.

@jbbr Thanks for pointing to the CREATE statement. :+1:

**Comment by MrEasy** [comment]
Changing seafile-server-5.1.1/upgrade/sql/5.1.0/mysql/seahub.sql to attached file, fixes the issue.
[seahub.sql.txt](https://github.com/haiwen/seafile/files/210345/seahub.sql.txt)

**Comment by shoeper** [comment]
https://forum.seafile-server.org/t/error-upgrading-seafile-ce-from-5-0-4-to-5-1-beta/4483

**Comment by freeplant** [comment]
Solved.
