### ISSUE TITLE
Feature Request: Upload and replace for multiple files

### ISSUE THREAD

**Issue by escoreal** [haiwen/seafile#1586]
Currently, when uploading multiple files through the web interface, with the same names as existing files, the new files will be given the names "file_1 (1).ext" and "file_2 (1).ext".
It would be great to instead have an option for Seafile to overwrite the old files. Like when you upload just one file (see #1061).

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.
