### ISSUE TITLE
Community Edition v5.0.1 and v5.1 api2/events/ returning "error_msg": "Events not enabled."

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1587]
Get the above response to making a a request to get file events as described in  http://manual.seafile.com/develop/web_api.html#get-file-activities but only get the above response.  I can not see anywhere to enable this feature in the server documentation.

**Comment by shoeper** [comment]
File activities are a pro feature.

**Comment by caniwi** [comment]
Hi Shoeper,
    After playing with it, that is what I figured but needed to ask to be sure.  Is the documentation going to be updated to indicate which API's are PE as opposed to CE or for a more meaningful error message.  Something like "feature not available in CE mode"

**Comment by shoeper** [comment]
I'm not sure. I think better/other error messages are unlikely to come.

If the api documentation gets updated depends on whether there is time to 
do so (it would definetly make sense), but documentation in general is 
something we plan to improve.


Am 11. April 2016 02:43:32 schrieb caniwi <notifications@github.com>:
