### ISSUE TITLE
Seafile apis do not allow valid characters in email address.

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1588]
I have tried to get an auth-token using an email address with a +.  This fails with message
{"non_field_errors":["Unable to login with provided credentials."]}

Although the user can login to the web interface.

For the record, the email address is of the form name+something@domain which is a valid email address according to the RFC.

**Comment by shoeper** [comment]
Has the plus sign been encoded?

Having a look at http://stackoverflow.com/a/1374456 it seems like the correct encoding is `%2B`

**Comment by caniwi** [comment]
You are correct.  The plus sign was not encoded and doing so works.  Thanks.

**Comment by Noxalus** [comment]
Hello, I have the exact same problem, but encoding the email doesn't work for me.

I request directly the API, and when I try with the non-encoded address, I obtain this:

```
{
  "non_field_errors": [
    "Unable to login with provided credentials."
  ]
}
```

And with the encoded one:
```
{
  "non_field_errors": [
    "username is not valid."
  ]
}
```

I currently use an old version of Seafile (v4.3.1), is that the reason why it doesn't work for me?

@caniwi: Which version of Seafile do you use?

**Comment by caniwi** [comment]
I was using 5.0.1 and 5.1.
