### ISSUE TITLE
Video file preview in 5.1.1 not working

### ISSUE THREAD

**Issue by andi-blafasl** [haiwen/seafile#1589]
Opening a MP4 File in version 5.0.5 you get a video player and can preview the file direct in the browser. 
If you are doing this after the upgrade to 5.1.1 the preview is no longer working. In Chrome if you open the developer tools console you see the attached errors.
![seafile-5 1 1-error](https://cloud.githubusercontent.com/assets/3586675/14421177/6be942ba-ffd0-11e5-8bca-f136ec7c6746.JPG)

**Comment by freeplant** [comment]
I can't reproduce the problem. Can you try refresh the browser?

**Comment by andi-blafasl** [comment]
Just tried it with IE 11 and clean cache. Same Error as in Chrome.

**Comment by freeplant** [comment]
Does the seafile-server-latest correctly point to v5.1.1?

**Comment by andi-blafasl** [comment]
Yes, it does point to v5.1.1

But if I view the source of the Video preview page, there is no jquery loaded:

```
</div><!-- wrapper -->

<script type="text/javascript" src="/media/js/jq.min.js?t=1434226335"></script>
<script type="text/javascript" src="/media/js/base.js?t=1434226335"></script>
<script type="text/javascript">
$.jstree._themes = '/media/js/themes/';
function ajaxErrorHandler(xhr, textStatus, errorThrown) {
    if (xhr.responseText) {
        feedback($.parseJSON(xhr.responseText).error, 'error');
    } else {
        feedback("Fehlgeschlagen. Bitte überprüfen Sie die Netzwerkverbindung.", 'error');
    }    
}
</script>
```

In the file: `seafile-server-5.1.1/seahub/seahub/templates/base.html` there is a line for jquery:

```
</div><!-- wrapper -->

<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.12.1.min.js"></script>
<script type="text/javascript" src="{% static "scripts/lib/jquery.simplemodal.js" %}"></script>
<script type="text/javascript" src="{% static "scripts/lib/jquery.ui.tabs.js" %}"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/jq.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/base.js?t=1460037602"></script>
<script type="text/javascript">

```

Is this finally delivered page cached anywhere?

**Comment by freeplant** [comment]
No, it should not be cached. Do you use a customized copy of base.html?

**Comment by andi-blafasl** [comment]
my bad...

you are right, there was a custom `base.html`

I created it some time ago to test something with the "X-UA-Compatible" header. 

Many thanks for your quick help!
