### ISSUE TITLE
[enhancement] Authentication using REMOTE_USER

### ISSUE THREAD

**Issue by neo-luddite** [haiwen/seafile#1590]
Beeing able to use external authentication sources, specifically HTTP Authentication basic
(where the Web server sets the REMOTE_USER environment variable) would be amazing. 

If running multiple services on one domain, people wouldn't have to authenticate multiple times. also many more backends for authentification could be used, independently from what seafile provides, depending on what your webserver is able to handle. 

thanks!

**Comment by killing** [comment]
Currently we already support Shibboleth. It uses REMOTE_USER. Do you know other external authentication mechanisms using this way?

**Comment by neo-luddite** [comment]
http auth is supported e. g. by trac, redmine, git, roundcube, drupal, wordpress and many others. so integrating seafile with a bunch of other services would be really easy and you wouldn't have to set up Shibboleth just for integrating seafile with the other services (I for my part am not using shibboleth).
also using the debian or ubuntu repos you have to recompile nginx for the shibboleth module.

**Comment by shoeper** [comment]
I don't think the question was which software allows using basic auth the question was: 

> [Seafile] uses REMOTE_USER. Do you know other external authentication mechanisms using this [(REMOTE_USER)] way?

**Comment by neo-luddite** [comment]
I see, sorry.

mod_authnz_ldap , CAS, Cosign, WebAuth, mod_auth_sspi

**Comment by kforner** [comment]
I also would like to have this feature. From what I understand, the job is almost done since you are already using REMOTE_USER for Shibboleth. You would just have to generalize it a bit.

**Comment by vascorppor** [comment]
I would like to chime in here. Supporting REMOTE_USER would allow for quite flexible  authentication. For example, one could configure mod_auth_openidc in an Apache Reverse Proxy.
