### ISSUE TITLE
Seafile generated links randomness and length

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1591]
With the publishing of "Short URLs Considered Harmful for Cloud Services" at http://arxiv.org/abs/1604.02734#, will the length of generated download links be increased?

**Comment by freeplant** [comment]
Seafile's download link tokens use 10 characters. The article says short URLs with 6 and 7 characters are problematic.

**Comment by caniwi** [comment]
Indeed but going to 16 characters would improve things dramatically without being onerous to produce or overtly ugly to end users.

**Comment by shoeper** [comment]
I agree that making the links a bit longer would be great.

Maybe instead of changing it you could just add a config option being used for all new links. In this case the admin can decide how long a link should (< varchar.length or similar) be while the default length is 10 characters.
