### ISSUE TITLE
Trash Tab in System Admin/Libraries not available

### ISSUE THREAD

**Issue by yyli** [haiwen/seafile#1593]
sys/seafadmin/repo-trash/ link shows:

```
Page unavailable
Sorry, but the requested page is unavailable due to a server hiccup.
Our engineers have been notified, so check back later.
```

Not sure if it ever did this before but I was just checking out the settings and noticed this.

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.
