### ISSUE TITLE
Move file, then upload with same name -> file already exists

### ISSUE THREAD

**Issue by Pro** [haiwen/seafile#1595]
Server Version: 5.0.2

If you move a file through the web interface to a subfolder and then upload a new file with exactly the same name to the old location, the message pops up that the file already exists.

How to reproduce:
1. Create a file called foo.txt in your library root `/foo.txt`
2. Open the web interface and move `foo.txt` to the subfolder `/bar`. Results in `/bar/foo.txt`
3. Without reloading the page upload a file with the same name `foo.txt` through the webinterface into '/foo.txt'
4. You will get the popup that the file already exists and if you want to replace it.

The popup should not be shown since the file was already moved out of the way.
This problem doesn't occur if you use rename.

**Comment by shoeper** [comment]
I can confirm this behaviour using Seafile Pro 5.0.7.

**Comment by freeplant** [comment]
Can't reproduce the problem on the latest version v5.1.2.

**Comment by shoeper** [comment]
The bug can be reproduced on seacloud.cc.
