### ISSUE TITLE
Seahub "Page unavailable" after upgrade 5.0.5 to 5.1.1

### ISSUE THREAD

**Issue by kusmierz** [haiwen/seafile#1602]
After upgrade 5.0.5 to 5.1.1, and migrate from sqlite to mysql, I've an error on webUI:

> **Page unavailable**
> Sorry, but the requested page is unavailable due to a server hiccup.
> Our engineers have been notified, so check back later.

**seafile.conf**
```ini
[fileserver]
port=2082
max_indexing_threads = 10
# Set maximum upload file size to M.
max_upload_size=2048
# Set maximum download directory size to M.
max_download_dir_size=4096

[database]
type=mysql
host=127.0.0.1
user=yyy
password=xxx
db_name=seafile-db
CONNECTION_CHARSET=utf8

[seahub]
port=8880
```

**seahub_settings.py**
```ini
SECRET_KEY = "zzz"

FILE_SERVER_ROOT = 'https://xxx/seafhttp'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

SERVE_STATIC = False
MEDIA_URL = '/media/'
COMPRESS_URL = MEDIA_URL
STATIC_URL = MEDIA_URL + 'assets/'

# ...

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.mysql',
         'USER' : 'aaa',
         'PASSWORD' : 'bbb',
         'NAME' : 'seahub-db',
         'HOST' : '127.0.0.1',
         'OPTIONS': {
             "init_command": "SET storage_engine=INNODB",
         }
     }
 }
```

**seahub_django_request.log**
```log
2016-04-24 13:38:06,365 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-server-5.1.1/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-5.1.1/seahub/seahub/base/decorators.py", line 39, in _decorated
    return func(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-5.1.1/seahub/seahub/views/__init__.py", line 877, in libraries
    'enable_encrypted_library': config.ENABLE_ENCRYPTED_LIBRARY,
  File "/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/utils/functional.py", line 226, in inner
    return func(self._wrapped, *args)
  File "/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/django_constance-1.0.1-py2.7.egg/constance/base.py", line 17, in __getattr__
    result = self._backend.get(key)
  File "/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/django_constance-1.0.1-py2.7.egg/constance/backends/database/__init__.py", line 67, in get
    value = self._cache.get(key)
  File "/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/cache/backends/memcached.py", line 84, in get
    val = self._cache.get(key)
  File "/usr/lib/python2.7/dist-packages/memcache.py", line 1089, in get
    return self._get('get', key)
  File "/usr/lib/python2.7/dist-packages/memcache.py", line 1073, in _get
    return _unsafe_get()
  File "/usr/lib/python2.7/dist-packages/memcache.py", line 1061, in _unsafe_get
    value = self._recv_value(server, flags, rlen)
  File "/usr/lib/python2.7/dist-packages/memcache.py", line 1235, in _recv_value
    val = int(buf)
ValueError: invalid literal for int() with base 10: 'True'
```

But, when I comment out `CACHE` section from `seahub_settings.py` file, it works fine. Clearing Memcache server (`echo flush_all | nc localhost 11211` nor restarting memcached service, even restarting whole server doesn't help). It works fine before.

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.

**Comment by freeplant** [comment]
@shoeper  This is a bug. We will look into the problem.

**Comment by shoeper** [comment]
Ok. Under which circumstances does it occur (am also using memcached and don't have any errors in my log)?

**Comment by kusmierz** [comment]
@shoeper but it seems to be a bug! @freeplant thanks.

I had version 5.0.5 installed with (accidentally) sqlite. I've downloaded 5.1.1 .tar.gz, run `seafile-server-5.1.1/upgrade/upgrade_5.0_5.1.sh` script and it shows me that I'm using sqlite. I thought I was using mysql earlier (but don't), so I migrated from sqlite to mysql using http://manual.seafile.com/deploy/migrate_from_sqlite_to_mysql.html. Dunno if it's important too.

I started seafile and seahub services. seahub's webui shows me a 500 error page, on login page (default redirect from `/`). When I remove `CACHES` section from `seahub_settings.py` (and restart seahub service), browser shows me webUI normally, and seahub creates `/tmp/seahub_cache` directory. I logged in to webUI and then readded `CACHES` section (+restart). I had the same 500-error page problem on each and every page I've requested with the exception as above. The thing is, I haven't changed configs (despite sql database sections), so it worked with memcached before update.

```bash
$ ps aux | grep memcache
memcache   977  0.0  0.1 329620  2116 ?        Ssl  13:15   0:00 /usr/bin/memcached -m 64 -p 11211 -u memcache -l 127.0.0.1
$ sudo netstat -lanp | grep 11211
tcp        0      0 127.0.0.1:11211         0.0.0.0:*               LISTEN      977/memcached   
$ aptitude search '~i!~M' | grep python | grep memcache
i   python-memcache                 - pure Python memcached client      
$ pydoc modules | grep memc
Tkdnd               configobj           memcache            strop
```

**Comment by shoeper** [comment]
I'm using Seafile Pro 5.1.2 and also am using memcached. Didn't even restarted it after the upgrade and don't have errors (of course that doesn't mean there can't be a bug). Here are my python / memcached versions.

```
root@home /seafile/conf # aptitude versions python-memcache ^python$ ^memcached$
Paket memcached:                                  
i   1.4.13-0.2+deb7u1                                    oldstable                         500 

Paket python:
i   2.7.3-4+deb7u1                                       oldstable                         500 

Paket python-memcache:
i   1.48-1                                               oldstable                         500 
```

**Comment by freeplant** [comment]
@kusmierz do you write `ENABLE_ENCRYPTED_LIBRARY = "True"` in your seahub_settings.py?

**Comment by freeplant** [comment]
@kusmierz Can you try add CONSTANCE_DATABASE_CACHE_BACKEND = None to seahub_setting.py

**Comment by freeplant** [comment]
This is a bug of python memcache. https://github.com/linsomniac/python-memcached/issues/75

Update the library to the latest version should solve the problem.

**Comment by kusmierz** [comment]
@shoeper 

```bash
$ aptitude versions python-memcache ^python$ ^memcached$
Package memcached:                              
i   1.4.24-2ubuntu1                                                              wily                                                      500 

Package memcached:i386:
p   1.4.24-2ubuntu1                                                              wily                                                      500 

Package python:
i   2.7.9-1                                                                      wily                                                      500 

Package python-memcache:
i   1.56-1                                                                       wily                                                      500 

Package python:i386:
p   2.7.9-1                                                                      wily                                                      500 
```

@freeplant No, I haven't added `ENABLE_ENCRYPTED_LIBRARY`. Should I?

@freeplant I have python-memcache@1.56 (as you can see above). Setting `CONSTANCE_DATABASE_CACHE_BACKEND = None` resolves it to me. So it looks like this is a bug [linsomniac/python-memcached#75](https://github.com/linsomniac/python-memcached/issues/75). Maybe it would be worth to add this info in seafile doc? python-memcache@1.56 is installed by default on [Ubuntu 15.10](http://packages.ubuntu.com/wily/python-memcache)... Xenial has [1.57-1](http://packages.ubuntu.com/xenial/python-memcache).

**Comment by tinkumanoj** [comment]
In Centtos i resolved this issue with below steps:-
1) Stop the services
2) Run the following command: 
rm -rf /tmp/seahub_cache
3) Start the services
