### ISSUE TITLE
TOPDIR is one path deeper than INSTALLPATH

### ISSUE THREAD

**Issue by pjlg** [haiwen/seafile#1604]
Hi,

"seafile.sh start" and "/seahub.sh start" ends with message
> Error: there is no ccnet config directory.
> Have you run setup-seafile.sh before this?

I have debugged the source and see, that 
> TOPDIR is one path deeper than INSTALLPATH

So I changed the source and add the line:
> TOPDIR="${INSTALLPATH}" # $(dirname "${INSTALLPATH}")
to get the right path and start the scripts...

Is it a bash-script bug, because TOPDIR should get the same path as INSTALLPATH (in my case)

Greets,
Peter

**Comment by killing** [comment]
It's not a bug. This script assumes the directory layout of our distributed package and you follow our documentation to install Seafile.
For example, seafile.sh is located at "~/haiwen/seafile-server-latest/seafile.sh". So INSTALLPATH is "~/haiwen/seafile-server-latest" and TOPDIR is "~/haiwen". And ccnet directory is located at "~/haiwen/ccnet". Nothing is wrong.

**Comment by pjlg** [comment]
Thanks for reply. 

My mistake was caused by the wrong starting point "~/haiwen/seafile.sh".

Greets
