### ISSUE TITLE
Wrong avatar symlink

### ISSUE THREAD

**Issue by pjlg** [haiwen/seafile#1607]
> user@server ~/seafile/seahub-data $ vdir
> insgesamt 0
> lrwxrwxrwx 1 beda beda 28 Apr 25 14:36 avatars -> ../../../seahub-data/avatars
> user@server ~/seafile/seahub-data $ 

This couldn't be the right avatar path.
Cause of this, the avatar picture is not found on seafile-webpage and couldn't be changed.

[Server version is a new installed 5.1.1]

**Comment by shoeper** [comment]
It is correct.

seafile/seafile-server-latest/seahub/media

.. -> seafile/seafile-server-latest/seahub
.. -> seafile/seafile-server-latest
.. -> seafile
seahub-data/avatars -> seafile/seahub-data/avatars

**Comment by Irrealist** [comment]
Just installed 5.1.1 and I'm having the same issue.

seafile/seafile-server-latest/seahub/media/avatars points to ../../../seahub-data/avatars, which is seafile/seahub-data/avatars - so far so good.

But seafile/seahub-data/avatars is also a symlink, and it also points to ../../../seahub-data/avatars, which would (in my case) be /home/seahub-data/avatars. That is definitely not correct.

**Comment by racemouse83** [comment]
Any progress on this? I'm experiencing exactly the same with version 6.0.4 on CentOS 7 - I've got a symlink in seafile-server-latest/seahub/media/avatars that points to ../../../seahub-data/avatars which is ALSO a symlink that points to the same path once again ../../../seahub-data/avatars. To work, that would require a seahub-data in my folder root, which I of course do not have...

How did you guys solve this?

**Comment by xiez** [comment]
hi @racemouse83 , could u please show the steps to reproduce the problem ? maybe it's a bug in our setup script.

**Comment by racemouse83** [comment]
Sorry, I've been messing with this setup for a few days so true reproducing of my steps may be difficult. However, I have not messed around with the paths, moved around the directories etc etc and I set up my installation by just using the setup-seafile-mysql.sh so I guess the directory must have been created by that script or when just extracting the original tarball...

if you can specify any specific file, log etc you wanna see just tell me and I'll look it up for u!

Regards,

Rasmus

**Comment by xiez** [comment]
can u re-install seafile to a separate folder or even another machine to see whether this issue still exists ?

**Comment by racemouse83** [comment]
Done! I performed the installation manually but basically took the steps out of this script and adopted to my environment: https://github.com/haiwen/seafile-server-installer-cn/blob/master/seafile-server-centos-7-amd64-http

This time it worked out fully while on http, but when I switched over on https the css fails as soon as the cache is in action - no matter if I try to reach it from my local network or through my reverse proxy (which it is configured for).

Ideas? (Maybe I should move this into another thread if it gets long...)

**Comment by xiez** [comment]
yeah, seems there is something wrong with your https config, plz double check that.

Is the avatar path correct in this newly installation ?

**Comment by racemouse83** [comment]
Avatar path seems correct, yes. No symlink in seahub-data, just a folder and the default files!

Sure about the https config, but have no clue what that would be. I've been using the steps in https://manual.seafile.com/deploy/https_with_nginx.html to enable it.

**Comment by racemouse83** [comment]
I'm not sure about this https config thing. Everything else works except the css. And if I look into the cache folder I can see the correct css file, which is empty though. It also seems I get served this file, but I get it empty so no styles are applied...

I've tried to restart memcached and then the servers, but that doesn't make it.

**Comment by xiez** [comment]
take a look at nginx access log and error log, you can also check http requrests in Chrome developer panel

**Comment by racemouse83** [comment]
Thanks. I see nothing related in nginx error log, seahub.error.log or anywhere else. If I look at the request I can see it first requests the http version, gets redirected to https version and there I get an empty response... Just like the file found in seahub/media/CACHE/css... Empty.

**Comment by racemouse83** [comment]
If I remove the seahub/media/CACHE contents and then restart all servers (nginx, seafile, seahub, memcached) then I get the correct css once - because then I got the original ones instead of a cached one. But as soon as I move on or reload the page, it uses the cache and then I get the empty stylesheet out of CACHE.

**Comment by xiez** [comment]
that's weird,  it doesn't make sense that http works while https does not work for the css cache.
u may paste the content of your seahub_settings.py.

Also u can try reinstall or just find a clean machine, and use our installer script.

**Comment by racemouse83** [comment]
The mysql installer? Tried that last time without luck :(
seahub_settings.py coming soon.

If I enable debug mode (disabling cache) it seems to work! I get the impression the cache makes some error when trying to compress all styles into one and therefore the file gets empty. I think it's something similar to what's described a bit down (not on top!) in this thread: https://forum.seafile.de/t/solved-invalid-http-cache-in-windows-4-2-3-server/2011/5

**Comment by racemouse83** [comment]
SECRET_KEY = "removed-for-forum"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'seahub_db',
        'USER': 'seafile',
        'PASSWORD': 'removed-for-forum',
        'HOST': '127.0.0.1',
        'PORT': '3306'
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
    'LOCATION': '127.0.0.1:11211',
    }
}

# EMAIL_USE_TLS                       = False
# EMAIL_HOST                          = 'localhost'
# EMAIL_HOST_USER                     = ''
# EMAIL_HOST_PASSWORD                 = ''
# EMAIL_PORT                          = '25'
# DEFAULT_FROM_EMAIL                  = EMAIL_HOST_USER
# SERVER_EMAIL                        = EMAIL_HOST_USER

TIME_ZONE                           = 'Europe/Stockholm'
SITE_BASE                           = 'removed-for-forum'
SITE_NAME                           = 'Seafile Server'
SITE_TITLE                          = 'Seafile Server'
SITE_ROOT                           = '/'
ENABLE_SIGNUP                       = False
ACTIVATE_AFTER_REGISTRATION         = False
SEND_EMAIL_ON_ADDING_SYSTEM_MEMBER  = True
SEND_EMAIL_ON_RESETTING_USER_PASSWD = True
CLOUD_MODE                          = False
FILE_PREVIEW_MAX_SIZE               = 30 * 1024 * 1024
SESSION_COOKIE_AGE                  = 60 * 60 * 24 * 7 * 2
SESSION_SAVE_EVERY_REQUEST          = False
SESSION_EXPIRE_AT_BROWSER_CLOSE     = False
FILE_SERVER_ROOT                    = 'removed-for-forum/seafhttp'

#DEBUG = True; # ENABLING THIS DISABLES CACHE AND MAKES EVERYTHING WORK!

**Comment by racemouse83** [comment]
May it be a problem with users and the cache?
I'm running seafile/seahub as user: seafile
Running nginx as user: seafile
Running memcached as user: seafile (recently tried changing to this instead of memcached, none of them helps)

My installation dir is recursively owned by seafile:seafile and the CACHE dir too.
