### ISSUE TITLE
Compilation under DD-WRT

### ISSUE THREAD

**Issue by skayred** [haiwen/seafile#161]
Hello!

I've tried to compile Seafile under DD-WRT on my Netgear WNR-3500l with 'mips' architecture, but './config' failed because it didn't know such architecture. Is it possible to build Seafile for DD-WRT?

**Comment by valentt** [comment]
There is a port of seafile to openwrt...
https://github.com/kissg1988/seafile-openwrt

**Comment by freeplant** [comment]
Thank you very much.
