### ISSUE TITLE
Clicking on Group Wiki Icon Leads to 404 not found

### ISSUE THREAD

**Issue by mrcybermac** [haiwen/seafile#1610]
I have installed seafile at myserver/seafile, so /seafile is my resource path.

I have edited seahub_settings.py with:
SITE_ROOT = '/seafile/'

It seems as though every link in the software works fine except the group wiki icon which lead to, for example:

<myserver>/group/5/wiki/   <---- 404 not found

If I then edit the URL like so it works:

<myserver>/seafile/group/5/wiki/   <---------  works

I have also tried editing the 'service url' in admin settings with many possible combos without success.

Is this a bug?  What am I missing?

Thanks

**Comment by shoeper** [comment]
What's your service_url?

**Comment by mrcybermac** [comment]
I've tried

http://<myserver>:8000

http://<myserver>:8000/seafile

http://<myserver>/seafile

I don't see any difference. It doesn't seem to affect any of the other links as well which appear to be obeying SITE_ROOT.

What is the service_url used for?
