### ISSUE TITLE
Can't upload file named `; #.odt` (semicolon-space-hash.odt)

### ISSUE THREAD

**Issue by kampde** [haiwen/seafile#1613]
When trying to upload a file named '; #.odt` the upload files with message "Unknown error".

Tested on seafile-server-5.0.5 on linux-x64.

**Comment by shoeper** [comment]
seafile.og says:
```
[04/29/2016 04:32:15 PM] upload-file.c(2053): [upload] Invalid mime param filename=".
[04/29/2016 04:32:15 PM] upload-file.c(2145): [upload] No filename given.
```

So it is likely some kind of encoding error already happening in the js code on client side. I've reproduced this with Seafile Pro 5.1.3.
