### ISSUE TITLE
Uploaded file with weird chars in name shows filename as (empty string) in file list

### ISSUE THREAD

**Issue by kampde** [haiwen/seafile#1614]
Uploading a file named `bla " ; - %7F ; # foo.odt` shows an empty string as filename. See http://i.imgur.com/TjJkqzc.png (the mouse was located in the download link).

Tested on seafile-server-5.0.5 on linux-x64

**Comment by kampde** [comment]
Trying to rename a file to `bla " ; - %7F ; # foo.odt` works, so it seems the problems lies somewhere in the upload process.

**Comment by shoeper** [comment]
Uploading `bla " ; - %7F ; # foo.odt` does not work here.

**Comment by kampde** [comment]
In #1613 the upload failed. In this bug the upload succeeds but the filename is shown empty. I reproduced both bugs in https://seacloud.cc/#my-libs/lib/ab3cb896-2223-4fde-800e-f105695bacab just now (only an (empty string) file is shown).

**Comment by shoeper** [comment]
The given url is not accessable (requires login). I've tested it as well last week and the filename wasn't empty but wrong after upload.

**Comment by shoeper** [comment]
Uploading a file with that name I get

```
bla " ; - %7F ; # foo.odt
Unknown error
```

**Comment by kampde** [comment]
I'm using fedora 21 (EOL'ed, I know...) + Firefox 42.0

**Comment by shoeper** [comment]
Yes, but Fedora isn't the issue. There is some difference between Chrome and Firefox but Seafile shouldn't accept an emtpy file name anyway.
