### ISSUE TITLE
ENABLE_USER_CREATE_ORG_REPO setting in seahub_settings.py does not work

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1615]
I have tried to turn off ordinary users creating organisation repos by setting

 # Disable normal user to create organization libraries
 ENABLE_USER_CREATE_ORG_REPO = 'False'

in seahub_settings.py.  This gets ignored when seafile starts  and the setting in the Web UI admin settings has the box ticked indicating it is still possible.  Testing shows that an ordinary user can still create organisational repos.  I have tried using both plain FALSE and 'FALSE' with no change in behaviour.

This is in Seafile Server 5.1.1 on Ubuntu 14.04

**Comment by shoeper** [comment]
> This gets ignored when seafile starts and the setting in the Web UI admin settings has the box ticked indicating it is still possible.

Then the setting has been overwritten by the admin settings.

**Comment by caniwi** [comment]
This is a dangerous precedent.  If you are using configuration management tool (puppet, chef, ansible etc), then you need to be able to set these from the configuration files and have that override the UI setting.  Also, if it was set from config file and someone overrode it in the UI then, you would have no way of knowing that the option was not in force.

Either both need to be the same and update the other or only 1 way of specifying the option.  Having it set in one place but ignored is just plain bad practice.

I would like you to reconsider your response, as uptake of seafile in a large deployment of possibly many instances will not occur if there is not a way of automating the configuration and its management.

**Comment by caniwi** [comment]
I would also like to add that no one set this in the admin settings in our installation.  It was assumed to be on by seafile and when the option appeared we quickly put it in the config file, only to have it ignored.  

I re-iterate, config options need to be able to be set in the config file.

**Comment by shoeper** [comment]
I didn't judge this. I just pointed out what the currently implemented behaviour is.

I think the same as you do and if I understood daniel correctly a switch to turn the webconfig off is planned.

**Comment by caniwi** [comment]
Sorry if I seemed a bit brash.... think this should be proirity.

Thanks.
