### ISSUE TITLE
The seafile service does not always shutdown for a restart

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1616]
It looks like a busy seafile server, when issued with a restart, is not always successful.  We have noticed this intermittently from seafile-server 4.x and just recently had it on 5.1.1.  From the seafile.sh script, a restart issues a stop_seafile_server, a sleep 2 followed by a start_seafile_server.

We sometimes get the message "Seafile controller is already running" which appears to come from the validate_already_running function as part of the start_seafile_server call.  

It would be better if the restart function issued a stop_seafile_server, validate_stopped and then a start_seafile_server.

We experience this situation most frequently, with a restart being performed by a config mgmt tool such as puppet or chef.

**Comment by hydrandt** [comment]
I can confirm this, sometimes seafile takes longer to exit, and then the first attempt to start it is unsuccessful.

**Comment by caniwi** [comment]
pull request submitted add check_stopped on stop command #1637
