### ISSUE TITLE
修改群组名称报错 403

### ISSUE THREAD

**Issue by fenbox** [haiwen/seafile#1617]
<img width="249" alt="2016-05-04 10 12 30" src="https://cloud.githubusercontent.com/assets/360618/15003670/d62154f2-11e0-11e6-9e30-b2a52059554b.png">

服务器版本：5.1.1

**Comment by xingduan** [comment]
遇到了和 @fenbox  同样的问题
I met same problem with @fenbox .

重命名群组名称时没有传递CSRF Token
No CSRF Token was sent to server during renaming group.

服务器版本 5.1.1
Server version 5.1.1

**Comment by xiez** [comment]
@fenbox  @xingduan  5.1.1 里群组重命名和转移是有问题，下版本里会修复。
Thx
