### ISSUE TITLE
support syncing of hfs+ extended attributes

### ISSUE THREAD

**Issue by squiddle** [haiwen/seafile#1619]
This would among others enable syncing of the tags and additional keywords the mac finder can add.

I know that extended attributes are filesystem specific and they should only be restored on sync for the same filesystem, as it probably won't work or is even incompatible between different filesystems. But all users on our team use the same desktop machines (macs) so having them synced would be fine.

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.
