### ISSUE TITLE
Android App: Scrolling/Navigation issue

### ISSUE THREAD

**Issue by Flowmatix** [haiwen/seafile#1620]
**Description:**
When scrolling down in a folder and navigating to a subfolder, the list of files is also displayed in a scrolled down state.
It might only be a minor bug, but the behaviour of the navigation could be better on that point.

**Steps to reproduce:**
1. Start the Android App.
2. Navigate to a folder that has a few subfolders.
3. Scroll down to the last subfolder.
4. Open the subfolder.
5. Observe the behaviour.

**Expected result:**
List of files is displayed with the first file in the folder on the top.

**Actual result:**
List of files is displayed, but the site is scrolled down to the same point, as it was scrolled down in Step 3.

Android App Version 2.0.6
Tested on a OnePlus One (Android 6.0.1)

Thank you!

**Comment by killing** [comment]
This should be opened in the SeaDroid repository.
