### ISSUE TITLE
Files containing a pipe character `|` in the filename are not accessible via webDAV

### ISSUE THREAD

**Issue by kampde** [haiwen/seafile#1622]
When uploading a file containing a pipe (`|`) in the filename, this file doesn't show up via webDAV. All other files appear correctly.

Tested against seafileServer 5.0.5 in linux-x64, using `mount.davfs2` in ubuntu 15.10 as the webDAV client.

**Comment by shoeper** [comment]
But the file is being served by seafile. Navigate to your-seafile/seafhttp in your webbrowser and you'll see that the file is there, can be downloaded & won't be corrupted.
