### ISSUE TITLE
wrong share link generation

### ISSUE THREAD

**Issue by akoscomp** [haiwen/seafile#1623]
I install my seafile server version 5.1.1 with apache and https.
I generate a public share link, but the link contains the port, and is with http:
http://xxxx.io:8000/d/72b907614b/
the correct url can be:
https://xxxx.io/d/72b907614b/

If I manually correct the URL, I can view the file list, but when I try to downlod the files, I give wrong URL:
https://xxxx.io:8082/files/b2973502-5269-467c-82df-aa08bad4742e/01Writer.webm
I try to delete the port from URL, but do not work.

 ccnet.conf
SERVICE_URL = https://xxxx.io

**Comment by freeplant** [comment]
Please check the SERVICE_URL setting in the web interface (admin panel)
