### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [haiwen/seafile#1627]
I would like to point out that identifiers like "[`_SEAFILE_RPC_H`](https://github.com/haiwen/seafile/blob/f295cf6693e246e58de512bc96b7c351261d97a1/include/seafile-rpc.h#L2)" and "[`_SeafileSession`](https://github.com/haiwen/seafile/blob/9e94246e0b0ce4b62a38a68450ebfd24787562a5/server/copy-mgr.h#L6)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by killing** [comment]
It's not planned. BTW, Seafile is written in C, not C++.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by elfring** [comment]
Would you find a standard compliant software implementation also nicer?
