### ISSUE TITLE
Seafile behind NAT and nginx: very slow download

### ISSUE THREAD

**Issue by alextreib** [haiwen/seafile#1628]
Hello,
my configuration of seafile is behind a NAT and uses proxy_pass like described in the official manual of seafile.
I have no problem with uploading to the server from a client, but downloading from the server is causing speed problems (60kBit).
This doesn't happen with clients in the same network. 
Moreover, I am using a dyndns service (NoIP) for setting up the configuration.

Has anyone an idea what could be wrong?

Please see my configuration files.

[nginx.txt](https://github.com/haiwen/seafile/files/252826/nginx.txt)

[ccnet.conf.txt](https://github.com/haiwen/seafile/files/252827/ccnet.conf.txt)

[seahub_settings.txt](https://github.com/haiwen/seafile/files/252829/seahub_settings.txt)

Thanks in advance!

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.
