### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [haiwen/seafile#1629]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [seafile_curl_init](https://github.com/haiwen/seafile/blob/9e94246e0b0ce4b62a38a68450ebfd24787562a5/common/curl-init.c#L20)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html) ⇒ [create_wt_status](https://github.com/haiwen/seafile/blob/9e94246e0b0ce4b62a38a68450ebfd24787562a5/daemon/wt-monitor-structs.c#L38)

**Comment by killing** [comment]
That's a good suggestion. Memory allocation errors are not very consistently handled in Seafile. But we consider that a minor issue. So we don't plan to change them in near future.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more. Would you like to detect every error situation as early as possible?

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for this software?

**Comment by killing** [comment]
Yes we've been using coverity for static code analysis.

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by elfring** [comment]
Would you like to care for the remaining open issues in this software?
