### ISSUE TITLE
Delete Share Link fault

### ISSUE THREAD

**Issue by jack-fd** [haiwen/seafile#1633]
Unable to remove shared files

server version：5.1.1 64bit

web api v 2.1

**Comment by killing** [comment]
Can you provide more details? Such as details request and response.

**Comment by Jack-fd** [comment]
URL：http://172.17.186.130:8000/api/v2.1/share-links/3787852c45

**Comment by shoeper** [comment]
Could it be that there is a slash missing at the end?

**Comment by Jack-fd** [comment]
Not the end is missing a slash
