### ISSUE TITLE
分享出去的文件夹，修改了改文件夹名，但分享里的名字没有更新

### ISSUE THREAD

**Issue by fenbox** [haiwen/seafile#1635]
分享出去了一个文件夹名字叫 "Doc"，后来文件夹名字改为 "Dev Doc"，但在【共享管理—>文件夹】下，分享的文件夹名字还是叫 "Doc"

删除该分享，重新再分享 "Dev Doc"，但在【共享管理—>文件夹】显示的名字仍然是 "Doc"

![image](https://cloud.githubusercontent.com/assets/360618/15172972/cbee88be-178b-11e6-9628-bfd8b8bd25c2.png)

服务器版本：5.1.1

**Comment by freeplant** [comment]
这个需要重新分享一次名字才会更新。

**Comment by fenbox** [comment]
@freeplant 重新分享仍然不会更新

**Comment by freeplant** [comment]
最新的版本中已解决该问题。
