### ISSUE TITLE
Local cache idea

### ISSUE THREAD

**Issue by fr500** [haiwen/seafile#1636]
Hey
I have been thinking, is there any way to make seafile work like a transparent local cache?
For example say users browses to his library but it wouldn't be a synced library but a local cache library, it would list all the files, and when windows tries to open the file the seafile client daemon would retrieve it transparently and the file would be treated as a local file.

Benefits are obvious, better than webdav support (several apps I have tried fail when trying to open files on webdav shares) and less local space usage.

I guess it would require some complex low level hooks though.

Just an idea.

**Comment by shoeper** [comment]
Thanks for your feedback. I think something like that is somehow on the roadmap. But:

> Please only submit bugs in GitHub issues (Pro customers should contact us via Email).
> Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/
