### ISSUE TITLE
html file preview

### ISSUE THREAD

**Issue by kforner** [haiwen/seafile#1638]
Currrently, if I'm not mistaken, it is not possible to view/preview a html file hosted by seafile, i.e. a html file uploaded in a library.
If you click on a html file, you will see the html source code, but not the rendered preview.

**Comment by shoeper** [comment]
This is extremely unlikely to be changed because it involves security risks.

**Comment by kforner** [comment]
Hmm indeed I had not think about this aspect, thanks.
