### ISSUE TITLE
seafile uses too many inotify watches (Ubuntu 16.04)

### ISSUE THREAD

**Issue by untom** [haiwen/seafile#1640]
I use seafile 5.1.1 on Ubuntu 16.04. The seafile applet starts automatically at startup, but it appears to use too many inotify watches. Meaning that all other processes that use inotify (e.g. pulseaudio, or also a simple `tail -f`) do not work properly while seafile is running.

For example, when seafile is running, `tail -f` will produce the following error:

    $ tail -f /dev/null
    tail: inotify resources exhausted
    tail: inotify cannot be used, reverting to polling

Also, pulseaudio will not start up properly, and there are most probably a lot of other processes that do not work as expected. If I stop the seafile applet, everything works fine, as expected.

Increasing the default number of watches to 65536 (from Ubuntu's default of 8192) alleviates the problem. However, I do not remember this being necessary on Ubuntu 15.10 (I was using seafile 4.3.x at the time if I recall correctly), even though the number of files being synched hasn't really changed since then.

**Comment by killing** [comment]
I don't remember there is any change that will increase inotify usage. Seafile only monitor folders for notification. So theoretically there shouldn't be so many usage.

**Comment by Crafter6432** [comment]
Same issue there

**Comment by shoeper** [comment]
Did not have any problems on Fedora 23 so far.

How much data / files do you synchronize?

What's your limit of watches?

**Comment by Crafter6432** [comment]
My Intellj Idea projects directory which contains a lot class files even though I added the build directory to my seafile-ignore.txt
