### ISSUE TITLE
Seafile folder not visible in cmd.exe or in Total Commander

### ISSUE THREAD

**Issue by imbehind** [haiwen/seafile#1641]
Windows 10

Seafile folder is not visible using cmd.

I cannot cd ./seafile and the folder is not listed using dir command. Total Commander also not showing seafile folder.

Otherwise, everything works OK, normal access is possible via explorer

![cmd ss](https://cloud.githubusercontent.com/assets/2964658/15230487/3a06f560-1896-11e6-99ad-c4801195e2fa.PNG)
![explorer ss](https://cloud.githubusercontent.com/assets/2964658/15230488/3a08e622-1896-11e6-9a41-df3a1bddd289.PNG)

**Comment by dbruenig** [comment]
check d:\users\kolja\.ccnet\seafile.ini which should contain the path to the seafile-data directory

**Comment by mgieseki** [comment]
I guess the problem is that the seafile folder is there but it's not listed by `dir`. Also TAB completion doesn't find it either. If you want to `cd` into it, you have to type the folder name completely.

**Comment by shoeper** [comment]
Does dir /a return it?

**Comment by mgieseki** [comment]
@shoeper Yes, is does.

**Comment by freeplant** [comment]
This is not within our support range.

**Comment by JannSchulte** [comment]
The seafile folder seems to be marked as a system-folder. Those are hidden by default in the Total Comander. Enabling them in the options, the Seafile folder will appear. 
![grafik](https://user-images.githubusercontent.com/3199186/69916119-19748b80-1457-11ea-987a-5c88b5b2d96f.png)
