### ISSUE TITLE
seafile server Error occured during setup.  Please fix possible issues and run the script again.

### ISSUE THREAD

**Issue by ZamanOof** [haiwen/seafile#1642]
after change configuration of seafile server  show this message 

Seahub is the web interface for seafile server.
Now let's setup seahub configuration. Press [ENTER] to continue
-----------------------------------------------------------------
Creating seahub database now, it may take one minute, please wait... 
**Failed to sync seahub database.
Error occured during setup. 
Please fix possible issues and run the script again.**
Best Regards

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
