### ISSUE TITLE
Seahub won't start after upgrade to 5.1.2

### ISSUE THREAD

**Issue by LarsKumbier** [haiwen/seafile#1643]
I have setup seafile on ubuntu 16.04 with nginx and mariadb and upgraded from 5.1.1 to 5.1.2. by downloading the new release, unpacking it and running /upgrade/minor-upgrade.sh. The symlink was correctly set to the new release, `seafile.sh start` runs as expected, but `seahub.sh start-fastcgi`. The log-file does not show any information on what's wrong:

```
LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub (fastcgi) at 127.0.0.1:8000 ...
Error:Seahub failed to start.
```

I haven't found any way of getting a higher debug level or something similar going. I was able to revert back to 5.1.1 for now, which works as expected.

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
