### ISSUE TITLE
Sorting numbers

### ISSUE THREAD

**Issue by XiteHosting** [haiwen/seafile#1645]
Hi,

Could it be possible to make sorting numbers like on Windows?

Right now it sorts it like in the old days (1, 10, 11, 2, 3)
This is both on the web as in the cloud file browser.

![cloud browser](https://cloud.githubusercontent.com/assets/13287521/15316420/3572dc1e-1c1d-11e6-87ce-6cf654d3f4a4.PNG)
![web interface](https://cloud.githubusercontent.com/assets/13287521/15316446/4d633c4c-1c1d-11e6-9251-2d9d5f462e5a.PNG)

thanks,
Stijn

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
