### ISSUE TITLE
seaf-cli execution problem

### ISSUE THREAD

**Issue by sophone1** [haiwen/seafile#1646]
Hello,

I have installed the seafile command line with all its dependencies (latest version), but I have met an error which occurs everytime when I run:
`seaf-cli start`

It retruns the following:
`File "/usr/bin/seaf-cli", line 151, in _conf_dir
    if args.confdir:
NameError: global name 'args' is not defined`

I have used an older version of seaf-cli and it runs correctly (except for syncing  with server)
Any solutions please ?

Thanks

**Comment by killing** [comment]
It seems you're running the wrong seaf-cli? If you use our package, seaf-cli should not be located in /usr/bin.

**Comment by sophone1** [comment]
I have just place it there, I am sur it is the fine release of the seaf-cli

**Comment by craftyguy** [comment]
I also see this, though seafile was [installed from AUR.](https://aur.archlinux.org/pkgbase/seafile-server/#news)

%  seaf-cli status
Traceback (most recent call last):
  File "/usr/sbin/seaf-cli", line 832, in <module>
    main()
  File "/usr/sbin/seaf-cli", line 828, in main
    args.func(args)
  File "/usr/sbin/seaf-cli", line 626, in seaf_status
    conf_dir = _conf_dir()
  File "/usr/sbin/seaf-cli", line 151, in _conf_dir
    if args.confdir:
NameError: global name 'args' is not defined

%  seaf-cli status
Traceback (most recent call last):
  File "/usr/sbin/seaf-cli", line 832, in <module>
    main()
  File "/usr/sbin/seaf-cli", line 828, in main
    args.func(args)
  File "/usr/sbin/seaf-cli", line 626, in seaf_status
    conf_dir = _conf_dir()
  File "/usr/sbin/seaf-cli", line 151, in _conf_dir
    if args.confdir:
NameError: global name 'args' is not 


 %  seaf-cli -h    
usage: seaf-cli [-h]
                {init,start,stop,list,list-remote,status,download,download-by-name,sync,desync,create,config}
                ...

optional arguments:
  -h, --help            show this help message and exit

subcommands:

  {init,start,stop,list,list-remote,status,download,download-by-name,sync,desync,create,config}
    init                Initialize config directory
    start               Start ccnet and seafile daemon
    stop                Stop ccnet and seafile daemon
    list                List local libraries
    list-remote         List remote libraries
    status              Show syncing status
    download            Download a library from seafile server
    download-by-name    Download a library defined by name from seafile server
    sync                Sync a library with an existing foler
    desync              Desync a library with seafile server
    create              Create a library
    config              Configure seafile client

**Comment by edacval** [comment]
Pull request created:  https://github.com/haiwen/seafile/pull/1664

**Comment by craftyguy** [comment]
Any chance we'll see a release soon with this fix included? I've been unable to use seafile client on my headless system for several weeks now!

**Comment by YevKov** [comment]
Hi,

I'm using Fedora 24 (pkerling/seafile) and I see that 5.1.3 is still not available through this yum repository. Also I couldn't find 5.1.3 version for Linux in "Downloads" at seafile.com.

Is this repository an official one so seafile contributors maintain it?
