### ISSUE TITLE
MySQL 5.7 migration documentation

### ISSUE THREAD

**Issue by Toxantron** [haiwen/seafile#1647]
In the [documentation for MySQL migration](http://manual.seafile.com/deploy/migrate_from_sqlite_to_mysql.html) it says in the last snippet

```py
"init_command": "SET storage_engine=INNODB"
```

For MySQL 5.7 shipped with Ubuntu 16.04 it must be changed to 

```py
"init_command": "SET default_storage_engine=INNODB"
```

As you can see [here](https://dev.mysql.com/doc/refman/5.7/en/storage-engine-setting.html) the variable was renamed.

**Comment by killing** [comment]
Fixed. Thanks.

**Comment by benni336** [comment]
Even though marked as fixed here, [this Version of the Manual](https://manual.seafile.com/deploy/migrate_from_sqlite_to_mysql.html), which should be the latest Version, doesn't referre to `default_storage_engine`.

This "important" fact should also be documented in [Backup and Recovery](https://manual.seafile.com/maintain/backup_recovery.html) as a Backup/Recovery is mostly needed for a change of MySQL-Version.
