### ISSUE TITLE
Video + audio cannot be view online if > max preview size

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile#1653]
Video and audio files cannot be viewed online if they are bigger than the max preview size.

See https://app.seafile.de/f/d6529faf85/?raw=1.

I see that there is a need to limit the size of documents that can be viewed online, but I don't think that limit should also apply for video and audio files because they are not computed in a special way on server side (as e.g. pdf or docx documents are).

**Comment by urgerestraint** [comment]
Yes, the Video preview is an extremely valuable feature - hampered by the single file preview size limit which also applies to small document files...

**Comment by kusmierz** [comment]
Is it fixed in 6.0.4?

**Comment by freeplant** [comment]
Yes. Fix in 6.0.4.
