### ISSUE TITLE
Using "username" instead of email with LDAP

### ISSUE THREAD

**Issue by BirknerAlex** [haiwen/seafile#1654]
Hello,

we are using LDAP as auth mechanism. All LDAP integrated applications in our company using the username instead of email address as login. 

But it seems Seafile requires at some points a valid email address. The field in the database structure is also called "email".

```
mysql> select * from LDAPUsers;
+----+--------+----------+----------+-----------+-------------+
| id | email | password | is_staff | is_active | extra_attrs |
+----+--------+----------+----------+-----------+-------------+
| 1 | marcel | | 0 | 1 | NULL |
| 2 | tyrola | | 0 | 1 | NULL |
+----+--------+----------+----------+-----------+-------------+
2 rows in set (0.00 sec)
```

But the login itself with username is working fine (no valid checks for email address) but some checks of the username are failing if it's not a valid email address: 

Sharing a file with a user:

The user is found via autocomplete but can't be used:
![2016-05-23_21-31-58](https://cloud.githubusercontent.com/assets/779751/15482180/86a454d0-212e-11e6-8aab-81324948ed10.png)

Regards,
Alexander

**Comment by freeplant** [comment]
If you use pro edition, you can sync username from LDAP to Seafile database. The user can then login via username. See more here: http://manual.seafile.com/deploy_pro/using_ldap_pro.html  (syncing the  UID_ATTR)
