### ISSUE TITLE
seaf-cli - https cert auto-signed - unable to skip verifying certificate

### ISSUE THREAD

**Issue by ychab** [haiwen/seafile#1656]
Unfortunetly, the documentation is wrong about disabling certificate checks (https://seacloud.cc/group/3/wiki/seafile-cli-manual#Enable-HTTP-sync).

I'm using the 5.0.7 seaf-cli script but it seems to be the same with current master version. I apply a quick and dirty fix with the following diff (credits to https://groups.google.com/forum/#!topic/seafile/67HJ9ol6Hw0) : 

````
--- seaf-cli.orig       2016-05-24 10:49:22.801895064 +0200
+++ seaf-cli    2016-05-24 10:52:49.892011158 +0200
@@ -78,6 +78,7 @@
 import sys
 import time
 import getpass
+import ssl
 import urllib
 import urllib2
 from urlparse import urlparse
@@ -179,8 +180,14 @@
     if data:
         data = urllib.urlencode(data)
     headers = headers or {}
+ 
+    ctx = ssl.create_default_context()
+    ctx.check_hostname = False
+    ctx.verify_mode = ssl.CERT_NONE
+
     req = urllib2.Request(url, data=data, headers=headers)
-    resp = urllib2.urlopen(req)
+    resp = urllib2.urlopen(req, context=ctx)

     return resp.read()

````

Of course, I supposed that a first better approach would be to get the client config (i.e : ``disable_verify_certificate``) and if set to ``true``, set the ignore cert flag...

It should be nice if it could be fixed. I can try to do the PR if someone points me to the right direction?

Thanks

**Comment by shoeper** [comment]
Has the certificate been issued for the correct hostname?

**Comment by ychab** [comment]
@shoeper  Yes, the CN is correct. But I didn't have imported the certificate as trusted on client side (didn't know I have to do it)!! Thanks to points me to the right direction! I supposed that urllib rely on system certs trusted to verify self signed certificate. Indeed, once you got the certificate locally, no reason to skip this check afterall...And everything works like a charm.

Anyway, I was wondering if ``disable_verify_certificate`` is really needed for cli client because obviously, it isn't used, right? If true, Wiki may need to be up-to-date because is it a little bit confusing :-s

Just to share with other ignorants like me ;-), you can get the certificate in that way (thanks to http://stackoverflow.com/questions/22509271/import-self-signed-certificate-in-redhat#answer-31124750) :

````
openssl s_client -connect <HOSTNAME>:443 <<<'' | openssl x509 -out <CERTFILENAME>
````

Then import it as **trusted**. Of course, tt depends on your system. For Fedora, just do **as root**:

````
# cp <CERTFILENAME> /etc/pki/ca-trust/source/anchors/
# update-ca-trust enable; update-ca-trust extract
````

That's it. You can still check if it was imported properly by taking a look at ``/etc/pki/tls/cert.pem``.

**Comment by killing** [comment]
The `disable_verify_certificate` is used by the syncing engine. Your problem is urllib doesn't find the certs in system. It's not related to this option.

**Comment by shoeper** [comment]
@killing you could add http://stackoverflow.com/questions/22509271/import-self-signed-certificate-in-redhat#answer-31124750 to the wiki page to directly give users a source on how to import a self signed certificate.
