### ISSUE TITLE
wrong quota calculation

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile#1658]
The quota calculation is currently wrong. Instead of checking whether the actual storage being used + the size of the file one wants to upload, it just checks if the quota already has been exceeded. Depending on the max upload size this allows to exceed the quota more or less.wr

**Comment by freeplant** [comment]
A summary for the latest version:

* The desktop syncing client will check the quota before upload files via sycing.
* For Web UI and mobile clients, the server will check the quota after receiving the file. If the remaining quota is not enough, the file is not saved to Seafile.
