### ISSUE TITLE
Option to change username or choose whether distinguish lower-case and upper-case letters

### ISSUE THREAD

**Issue by shiquanwang** [haiwen/seafile#166]
I set username with the email address copied from address book, with upper-case and lower-case letters.

It is really unconvinient to login with the username, because people are used to input all lower-case email address(doesn't matter uppper-case or lower-case when used as email address)

So, if we can do one of the two:
1. Option to change username by the user so to set to all lower-case letters.
2. Option to choose whether distinguish lower-case and upper-case letters.

**Comment by kun-zhou** [comment]
It seems like there is still no option to change username? (sometimes a user's email address becomes defunct)
