### ISSUE TITLE
User search is case sensitive... AGAIN

### ISSUE THREAD

**Issue by egroeper** [haiwen/seafile#1660]
Hi,
after you fixed this based on https://github.com/haiwen/seahub/pull/958, the new search implementation introduced in commit https://github.com/haiwen/seahub/commit/0e43a099ff11fd8c067e27fcf7827e85fa3d2ece makes the search case sensitive again.

Is there a reason for not removing the old (dead?) code?
When "testing" this on my production system, it doesn't work (search is case sensitive).
But when running the tests (which have testcases for this) everything seems to be fine.
Could it be, that the old (dead?) implementation gets tested and the new one is used in production?

Please fix this. Users are annoying me.

**Comment by freeplant** [comment]
We will check the problem today.

**Comment by freeplant** [comment]
This fix is here: https://github.com/haiwen/seahub/pull/1210/files . You can replace seahub/api2/endpoints/search_user.py with the new one for quick fix.

Sorry for the inconvenience.

**Comment by freeplant** [comment]
The auto testing is using SQLite database, which is case insensitive, so it can't find the bug.
