### ISSUE TITLE
seafile.com SSL certificate has expired

### ISSUE THREAD

**Issue by cstewart90** [haiwen/seafile#1661]
Go to https://seafile.com/ and you will get a warning in your browser. The google search results for "seafile" link to the https site which is currently invalid.

> www.seafile.com uses an invalid security certificate. The certificate expired on 25 May 2016 13:00. The current time is 25 May 2016 13:23. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by shoeper** [comment]
solved
