### ISSUE TITLE
Accessing a library without access blocks access to all libraries until logging out and in again.

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile#1662]
Steps to reproduce:

1. Login
2. Get a valid library address from another account that has not been shared with you. It says `access denied.`
3. Try to access any of your libraries.
4. Seahub is just going to say `access denied.` for all of them
5. Logout and in again
6. Everything works again.

Seems to be some kind of caching issue but I could be wrong. Experienced on app.seafile.de with Chrome (50.x...).

**Comment by freeplant** [comment]
This should be a UI problem. You don't need to logout. Refresh the page should solve the problem. It should be fixed in https://github.com/haiwen/seahub/pull/1223

**Comment by shoeper** [comment]
Refreshing the page did not work, only logging out & in.
