### ISSUE TITLE
Official docker

### ISSUE THREAD

**Issue by kforner** [haiwen/seafile#1666]
Hello,

I think an official seafile docker, tagged by version, and distributed through docker hub would be extremely valuable, for the customers foe ease of installation, and for the developers to have easily reproducible installations. 
That's what gitlab does for example (https://hub.docker.com/r/gitlab/gitlab-ce/).

Best,

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
