### ISSUE TITLE
"is not a library" message when desyncing

### ISSUE THREAD

**Issue by bcnx** [haiwen/seafile#1669]
Two libraries remain in the state "downloading" and no progress is made. While trying to desync and sync again, we get on the desync command:

/mnt/VOL1/users/ is not a library

for these two problematic libraries, so we cannot desync or start again. 

Client: 5.1.1 on Ubuntu 14.04
Server: Seafile Pro 5.1.3 

seafile.log on the client shows very frequently for one library:

Worktree for repo 'Communication'(7b68967c) is not set

for the other library we get: 

No master branch found for repo users(00a51182)

Is there a way to desync and start over again without having to sync everyting all over?

Thank you,

BC

**Comment by freeplant** [comment]
You can try delete the corresponding local folder and restart Seafile client.

**Comment by bcnx** [comment]
That is not an option for us as we use the local folder to be the source for Seafile sync, as we use Seafile as a backup solution. It is a read-only mapping of a data folder. We sync it then to the Seafile server where users can get to their files when the main fileserver is down.
Is it an option that we open the local SQLite databases do delete the problematic library so we can start over? If so, what tables would that be?
Thank you!

BC
