### ISSUE TITLE
Support for Amazon S3 Transfer Acceleration

### ISSUE THREAD

**Issue by bcnx** [haiwen/seafile#1670]
This recent developed technology allows for much faster S3 storage. Details are to be found on:

[http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html]

It involves creating new bucket versions of the existing ones. Not all S3 commands are supported in this mode though, so my major question is whether Seafile with S3 is supporting this accelerated version of S3. Seeing that using S3 with Seafile results into a somewhat slower system, it might a good solution to speed things up. 
But does it work?

Thank you,

BC

**Comment by freeplant** [comment]
Seafile does not upload files to S3 directly, but upload to the Seafile node first. So this acceleration can't be used in Seafile currently.

**Comment by bcnx** [comment]
Does this mean that Seafile does some sort of mapping to S3? How does Seafile communicate with S3 then?
