### ISSUE TITLE
[seahub] Create wiki, library ownership check

### ISSUE THREAD

**Issue by jeroen92** [haiwen/seafile#1674]
Just like when sharing a library, the ownership check is also insufficiently performed when assigning a library to store your Wiki pages. You may forge this POST request to point to any repo ID. I was not able to download any files from the library, but you may pollute the affected user's library with arbitrary _.md_ files.

**Comment by freeplant** [comment]
Thanks for reporting the issue. The fix is here: https://github.com/haiwen/seahub/commit/30ef613a502c7d63791b34e9289fc0a2ad13907c .It will be included in the next release.
