### ISSUE TITLE
Qt 5.5 dependency on Ubuntu 14.04

### ISSUE THREAD

**Issue by K-os** [haiwen/seafile#1679]
The 5.1.2 bugfix release of the seafile-client Debian package suddenly requires Qt >=5.5, which is not provided by Ubuntu 14.04 (trusty). The previous version only required Qt 5. I think this is not a change that should be included in a simple bugfix release - especially since it is not mentioned in the changelog.

Do you use any specific features from Qt 5.5? If not, it would be good to link the client against an older version (e.g. 5.2.1, which is included in Ubuntu 14.04) and it should still run with newer Qt versions.

"[Qt] Minor releases are backwards binary and source compatible." (see: https://wiki.qt.io/Qt-Version-Compatibility)

**Comment by shoeper** [comment]
Please reopen in seafile-client repository.
