### ISSUE TITLE
Seafile 5.1.3 "unkown error"

### ISSUE THREAD

**Issue by WeWin55** [haiwen/seafile#1693]
Hello,

ive just installed and configured my seafile server (nginx + ssl + 5.1.3). But my uploud isnt working the error message is "unknown error". The permissions of the seafile-data folder is right, because i can create files in seafile and download them.
Ive got this problem since last week, but cant find a solution and the other users with the same problem cant help me either.

(ive blanked the user specific things out)
ccnet:
[General]
USER_NAME = 
ID = 
NAME = 
SERVICE_URL = https://domain.de:8000

[Client]
PORT = 13419

[Database]
ENGINE = mysql
HOST = 127.0.0.1
PORT = 3306
USER = root
PASSWD = 
DB = ccnet-db
CONNECTION_CHARSET = utf8

seafile.conf:
[fileserver]
port = 8082

[database]
type = mysql
host = 127.0.0.1
port = 3306
user = root
password = 
db_name = seafile-db
connection_charset = utf8

seahub_settings.py:
SECRET_KEY = ""
HTTP_SERVER_ROOT = 'https://domain.de/seafhttp'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'seahub-db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306'
    }
}

Thanks in advance for helping me!

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
