### ISSUE TITLE
Natural sorting & Remember sorting on seahub?

### ISSUE THREAD

**Issue by fr500** [haiwen/seafile#1694]
Is it possible to implement natural sorting on file and library listings on seahub?
Right now my projects look like this
1. Project 1
2. Project 10
3. Project 11
4. Project 2

Also it seems seahub doesn't remember the sorting preferences, it seems it's always sorted on modification date by default?

**Comment by freeplant** [comment]
The latest version remember sorting. We will look into the first problem.

**Comment by fr500** [comment]
Thanks a lot!
