### ISSUE TITLE
Windows client - Local worktree not getting deleted if "do not unsync" is checked.

### ISSUE THREAD

**Issue by Lonsarg** [haiwen/seafile#1696]
Hi, i think i found a little bug. I had "Do not automatically unsync a library" checked, which should only prevent unsynching if local directory is missing. But what this setting was also cousing was A LOT of warning in log(and probably wasting CPU time): 
repo-mgr.c(760): Failed to access worktree C:/Users/rober/Seafile\Šodr for repo 'Šodr'(8096df76)

After i removed this checkbox and restarted Seafile i got this:
repo-mgr.c(7085): Worktree for repo "Šodr" is invalid, delete it.

After this even if i checked setting again warning did not produce itself anymore, so i have concluded that a side effect of this setting is preventing local worktrees for deleted libraries(it was deleted on both client and server) from clearing.

**Comment by shoeper** [comment]
This is not a bug. It is exactly what the feature should do.

**Comment by Lonsarg** [comment]
Ok i may have not completely understood the issue. Now i see my case is very rare, because i had both unsync prevention(local and server) set when library was deleted and only later unchecked the server one. If i had this settings from begining everything would work as intended.

Still, first setting(prevent unsync if local folder missing) could be smart to check if library exists on server and not fire up if it does not, cause we already have second setting for that(prevent unsync if server library missing). But since this case is rare, it is probably not worth the time.
