### ISSUE TITLE
Can't open files in Seahub (Page unavailable)

### ISSUE THREAD

**Issue by DerEnderKeks** [haiwen/seafile#1697]
If I try to open a file in Seahub following error occurs:

>**Page unavailable**
>Sorry, but the requested page is unavailable due to a server hiccup.
>Our engineers have been notified, so check back later.

OS: Debian 8 (`3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux`)
Seafile: 5.1.6 (Pro)
Seafile is configured behind Nginx and with Sqlite3.

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
