### ISSUE TITLE
Reverse proxy with Caddy, seafhttp rewrite issue

### ISSUE THREAD

**Issue by arvdsn** [haiwen/seafile#1698]
I'm trying to move over from nginx proxy to caddy, and seafile is running fine but they are requiring a separate proxy for /seafhttp to allow uploads through the web interface. Below is a working excerpt from my nginx config.

```
location / {
    proxy_pass http://10.0.1.29:8000;
    sub_filter_once off;
}
location /seafhttp {
    rewrite ^/seafhttp(.*)$ $1 break;
    proxy_pass http://10.0.1.29:8082;
    client_max_body_size 0;
    proxy_connect_timeout  36000s;
    proxy_read_timeout  36000s;
    proxy_send_timeout  36000s;
    send_timeout  36000s;
}
```

I'm very new to this and the above config (as with my other proxies) is a result of trial and error. I'm guessing it's the rewrite line that gets this to work but I don't have the knowledge to write the same in Caddy. Below is my caddy file.

```
xx.xxxxxxx.xx {
    proxy / 10.0.1.29:8000
    proxy /seafhttp 10.0.1.29:8082
    rewrite /seafhttp {
        regexp ^(.*)
        to     /
    }
}
```
Looking at the django log file, I'm seeing this:

` #[WARNING] django.request:98 _reject Forbidden (CSRF token missing or incorrect.): /`

Been googling like a crazy person and I need some help to get this working. What am I missing? 
For reference, here are the Caddy directives: https://caddyserver.com/docs/proxy & https://caddyserver.com/docs/rewrite

Thank you!

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
