### ISSUE TITLE
Unlimited quota does not work anymore

### ISSUE THREAD

**Issue by giga** [haiwen/seafile#1699]
We had seafile server version 5.0.5. We had in conf/seafile.conf

```
[quota]
# default user quota in GB, integer only
default = 0
```

After upgrading to version 5.1.3, all users without a specific quota got “out of quota” error message when trying to upload files. Changing the above line in conf/seafile.conf to

```
[quota]
# default user quota in GB, integer only
default = 10TB
```

fixed the problem, but it seems to be a dirty work-around.

**Comment by shoeper** [comment]
I do not have the problem using Seafile Professional Server 5.1.8 which uses very much of the Seafile CE code.

Are you sure there was no other problem? E.g. a space at the end of the line?

**Comment by giga** [comment]
I tried again. Using `default = 0` does not work, but `default = 0B` does work.

**Comment by shoeper** [comment]
This could be a bug. Just noticed that I don't have any entry for quota in my config and the default seems to be unlimited.

**Comment by killing** [comment]
If you want unlimited quota, just remove the quota section in seafile.conf.
