### ISSUE TITLE
seaf-cli: no upload progress

### ISSUE THREAD

**Issue by jaltek** [haiwen/seafile#1704]
Hi,

I'm using the ```seaf-cli``` and I don't see any "progress" during the upload
```
$ seaf-cli status
# Name  Status  Progress

# Name  Status
Pictures  uploading
```

Is this normal?

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem and questions should be asked in the forum https://forum.seafile.de/.

**Comment by jaltek** [comment]
Hi @shoeper,

IMHO as the progress is working during the download this is either a bug, a "display" issue or the documentation is incomplete :)
