### ISSUE TITLE
Unnecessary LOCKs in initial dump stop me installing Seafile

### ISSUE THREAD

**Issue by egroeper** [haiwen/seafile#1707]
Hi,
my database admin doesn't give us LOCK permissions, because this is unnecessary when using InnoDB and could harm backup.

Since commit 0d57b3f060c133df3991044117956b78b436a213 (2016-03-19) you introduced LOCK statements in seahub/sql/mysql.sql.
Please remove them.

This file is used on initiial setup so there should be no parallel writes.
If you nevertheless want to protect against concurrent writes, you could perhaps use transactions (--single-transaction in mysqldump?) since you are only using innodb tables.

**Update**: I just saw, that everything would be fine, if you used the command in README.md in the same directory. So it seems, that this was simply by mistake.

**Comment by xiez** [comment]
@egroeper  fixed in https://github.com/haiwen/seahub/commit/532ae5357d23ada37d77468aeb92b2d8751ef161 many thanks!
