### ISSUE TITLE
Multiple domains / multiple service_urls?

### ISSUE THREAD

**Issue by kooimens** [haiwen/seafile#1710]
I'm running seafile on a vm with apache reverse proxy on the same vm and domain = seafile.example.com (non-ssl), for local sync clients.

However, from outside I like to use example.com/seafile (ssl). Running as a apache service on a different vm.

Is this possible? If yes, how do I have to set my FILE_SERVER_ROOT, SITE_ROOT, SERVICE_URL?

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
