### ISSUE TITLE
Feature Request: Sorting the lists under 'Share Admin'

### ISSUE THREAD

**Issue by geugen** [haiwen/seafile#1711]
Currently, under the directory tree 'Share Admin' it is not possible to sort columns of the lists contained in 'Libraries', 'Folders' and 'Links'. As long as the list is not too long, it is not a problem; otherwise it becomes difficult keep the overview. So, why not implement a column sorting feature as already available under e.g., Files -> Mine?

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
