### ISSUE TITLE
Filenames with whitespace bug in webbrowser 

### ISSUE THREAD

**Issue by guido-osict** [haiwen/seafile#1715]
Hi,

If I open a library ( View on Cloud from OSX client) in the webbrowser I see a list of files. The filenames with a whitespace don't show a thumbnail image and opening the file (double click) give me the error: "File does not exist". 
Opening the same file in the Client is working ok.

Tested in FF, IE, Safari and Chrome  on OSX and Windows10
Server Version: 5.1.3 on CentoS

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.

**Comment by guido-osict** [comment]
In my opinion this is a bug so I post it here ( submit bugs in GitHub issues)

**Comment by freeplant** [comment]
This is most likely a configuration problem.

**Comment by kforner** [comment]
just to add that I have the same problem with seahub 5.1.3. I am a pro customer and also sent a mail to support.

**Comment by shoeper** [comment]
This is an Apache 2.4.7 issue. See http://manual.seafile.com/deploy/deploy_with_apache.html#troubleshooting

2. possible Solutions:
Either upgrade Apache to at least 2.4.12 (in some distributions it has been backported to 2.4.10) or switch to Nginx.
 * http://manual.seafile.com/deploy/deploy_with_nginx.html
 * http://manual.seafile.com/deploy/https_with_nginx.html

**Comment by guido-osict** [comment]
same whitespace problem with Apache/2.4.6

latest apache on centos 7:
yum:
httpd.x86_64        2.4.6-40.el7.centos.4                     @updates 

Server Version: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9
Server MPM: prefork
Server Built: Jul 18 2016 15:30:14
