### ISSUE TITLE
Using the API to upload to specific Folder broken?

### ISSUE THREAD

**Issue by robinrossow** [haiwen/seafile#1718]
Hey!

I'm trying to use the api to upload a file to a specific folder but it always ends up in the root folder.
My URL ends like this: 
`../upload-link/?p=/foldername`

This should be ok shouldn't it? 

I've tried using the folder ID instead and other varations but the parameter seems to be ignored.

Kind regards

**Comment by robinrossow** [comment]
Nevermind. I didn't use the right path in the parent_dir= parameter in the curl call. 
I think the example could be improved there.

**Comment by shoeper** [comment]
Could you submit a PR to https://github.com/haiwen/seafile-docs?
