### ISSUE TITLE
seaf-fsck.sh --export should preserve modification times

### ISSUE THREAD

**Issue by nascheme** [haiwen/seafile#1719]
It would be really handy for backup purposes if "seaf-fsck.sh --export" would set the modification time on files it creates.  That would make incremental backup software work more efficiently.

I think the fix is pretty easy.  I'm not very familiar with the code but it looks like the info is inside the seafile repo and it would just be a matter of calling utime() with the correct timestamp.

**Comment by freeplant** [comment]
Why do you use `seaf-fsck.sh --export` for backup purpose. You can use the fuse interface.

**Comment by shoeper** [comment]
Even if it is possible using fuse I'd agree that modification time should be preserved on export.

**Comment by nascheme** [comment]
If find the fuse interface very slow.  I like my --export solution better.  Attached is a first attempt at a fix.  It uses the utime() system call, giving it seaf_dent->mtime.  That appears to work.

BTW, building seafile from source code is difficult.  I spent a lot of time trying to build a seaf-fsck binary that I could test.  I never did figure out how to build a "server" package.
[seaf-fsck-mtime.txt](https://github.com/haiwen/seafile/files/542829/seaf-fsck-mtime.txt)

**Comment by milosivanovic** [comment]
Any progress with this?

**Comment by nascheme** [comment]
I would be happy if it got fixed.  My attached patch is pretty simple and seems to work.
