### ISSUE TITLE
What is the password of the mysql root user?

### ISSUE THREAD

**Issue by stone453** [haiwen/seafile#1721]
HI:

I use the [1] to initialize the seafile databases,
[1] Create new ccnet/seafile/seahub databases
[2] Use existing ccnet/seafile/seahub databases

When ask me to input the root password, it encounters the following problem
Failed to connect to mysql server using user "root" and password "***": Can't connect to MySQL server on '127.0.0.1' (111)

Could anyone help me on this?
thanks!

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
