### ISSUE TITLE
Uploading folders is not working in most browsers

### ISSUE THREAD

**Issue by replug** [haiwen/seafile#1724]
The upload feature for folders is not working in Firefox (Ubuntu, Mac and Windows), Safari and Internet Explorer; the dropdown menu for the advanced upload does not work, except in Chrome.

In Chrome the dropdown works: 
![seafile-seahub-upload-folder-files](https://cloud.githubusercontent.com/assets/1543409/17017648/821d9942-4f34-11e6-9322-d4db9df56c2a.jpg)

All other browsers open directly the dialogue for the file upload of the local system and one can not select folders only files.

**Comment by replug** [comment]
moved this issue to: https://github.com/haiwen/seafile/issues/1724

**Comment by freeplant** [comment]
This is not a bug. As far as I know, only Chrome support folder selection so far.

**Comment by kzahel** [comment]
I don't see the dropdown for upload. Is there a configuration setting I need to enable this?
