### ISSUE TITLE
Using search for user when creating a share fails to find user

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1729]
We have seafile server 5.1.3 and are experiencing randomness when searching for other users of the system.  We use LDAP authentication and it appears that unless a user profile has their name filled in then the search for user does not find them.  The admin interface can find them but a normal user can not.

As an example we have 3 peters

peter1@company.com
peter2@company.com
peter3@company.com

When sharing a library, a folder or a file using search, it fails to find any peter because they have not updated their profile.  As soon as peter2@company.com enters his name into his profile, he can be found.  All users are actively using seafile.  

I am about to upgrade to Seafile server 5.1.4, but the changelog does not indicate this was fixed.  I will update the ticket if the situation is the same.

Is there anything you need to figure out the issue?

**Comment by P4R4DiSi4C** [comment]
Same problem here. Please fix.

**Comment by freeplant** [comment]
Seafile only searches users that has been imported to Seafile internal database.

I think the user don't need to update this profile to let it be searched. As long as he/she login into Seafile, he/she can be searched.

**Comment by caniwi** [comment]
Hi Daniel,
   We are using LDAP authentication to seafile.  The user has logged in
many times but unless they fill in these details they do not appear in a
search.  This occurs on seafile server 5.1.4 on Linux Ubuntu 14.04.  These
details do not appear to be automatically imported during LDAP
authentication.
