### ISSUE TITLE
Image preview should not be in full size

### ISSUE THREAD

**Issue by grasshide** [haiwen/seafile#1734]
Hi there,
I'v been using Seafile for a long time now. When the gallery feature was added, a preview/slideshow for images was also introduced. At that time a parameter was available - I believe it was PREVIEW_DEFAULT_SIZE where it was possible to resize the resolution of pictures to save bandwith. Somewhere I read that this parameter "moved internally". Unfortunatelly the slideshow is no longer usable.  It takes to long to even show the 5-10MB pictures from my phone.
Did I miss something? Is the parameter available somewhere?
Thanks in advance!

**Comment by freeplant** [comment]
Do you mean the slide show at the iOS/Android client?

**Comment by grasshide** [comment]
No. I use Firefox and open my seafile homepage. Then I click on a picture. Seafile shows this picture in full screen. But instead of a resized picture (lets say 1000x1000pixels max) I get the picture in full resolution. I use Seafile 5.1.4 - community edition and Firefox in the latest version.

**Comment by freeplant** [comment]
I understand now. This part will be improved in the future.

**Comment by grasshide** [comment]
Ok Thanks. I'm looking forward to get this feature back ;-)

**Comment by grasshide** [comment]
How do you track this? Should I put this on the wishlist?

**Comment by freeplant** [comment]
Yes,  it is better if you post a wishlist at forum.seafile.com.

**Comment by grasshide** [comment]
I put it on the wishlist. It's available here: https://forum.seafile.com/t/resize-image-preview-for-web-interface/203

**Comment by LeonardoGentile** [comment]
Indeed, the slideshow is unusable as it is now considering an average 5 to 15 MB per pictures!
Any update on this?

**Comment by pixup1** [comment]
Why was this closed ?
