### ISSUE TITLE
libssl1.0.0 dependency problem

### ISSUE THREAD

**Issue by mesutevin** [haiwen/seafile#1735]
I am trying to install `seafile-client` on `debian-stretch`.
my install code: `dpkg --install seafile_5.1.3_amd64.deb`
but I got an error: 
```
 seafile depends on libssl1.0.0 (>= 1.0.0); however:
  Package libssl1.0.0 is not installed.
```
But the `llibssl1.0.2` library is already installed on my debian.

How can I fix this problem?

**Comment by freeplant** [comment]
You should follow this instruction to install the client on debian: https://github.com/haiwen/seafile-user-manual/blob/master/en/desktop/install-on-linux.md#-debian

**Comment by mesutevin** [comment]
When i changed the `stretch` instead of `jessie` in this code 
> echo deb http://dl.bintray.com/seafile-org/deb jessie main | sudo tee /etc/apt/sources.list.d/seafile.list

I got following error, of course: 
```
The repository 'http://dl.bintray.com/seafile-org/deb stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://dl.bintray.com/seafile-org/deb/dists/stretch/main/binary-amd64/Packages  404  Not Found [IP: 159.122.18.156 80]

```

When I tried the your default instruction directly,

```
echo deb http://dl.bintray.com/seafile-org/deb jessie main | sudo tee /etc/apt/sources.list.d/seafile.list
sudo apt-get update
sudo apt-get install seafile-gui
```

I got a dependency error again as follows:

```
The following packages have unmet dependencies:
 seafile-gui : Depends: libccnet0 (>= 5.1.2) but it is not going to be installed
               Depends: libssl1.0.0 (>= 1.0.0) but it is not installable
               Depends: ccnet (>= 5.1.2) but it is not going to be installed
               Depends: seafile-daemon (>= 5.1.2) but it is not going to be installed
```

It is going to the dependency hell :-1:

**Comment by mesutevin** [comment]
## Working solution for me

* [Download](https://packages.debian.org/jessie/libssl1.0.0)
 the `libssl1.0.0`
* `sudo dpkg -i [downloaded_libssl_file]`
* `sudo dpkg --install seafile_5.1.3_amd64.deb`
Here dependency problem again. (but only `libqt5test5` and `libqt5webkit5`)

* `sudo apt-get -f install`
And try install seafile again:
* `sudo dpkg --install seafile_5.1.3_amd64.deb`

The seafile is installed. Working now for me.

**Comment by ericndunn** [comment]
Worked for me also:
Linux 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13) x86_64 GNU/Linux
 Download the libssl1.0.0
sudo dpkg -i [downloaded_libssl_file]
sudo apt-get install seafile-gui

Working well.  I share between Linux, OSX, iPhone, iPad

**Comment by Plexiate** [comment]
I am using Ubuntu 20.04, below steps work for me:

Add 18.04's main repository using
echo "deb http://security.ubuntu.com/ubuntu bionic-security main" | sudo tee -a /etc/apt/sources.list.d/bionic.list

Update repository cache and check if libssl1.0-dev is now available.
sudo apt update
apt-cache policy libssl1.0-dev

Install libssl1.0-dev.
sudo apt-get install libssl1.0-dev
