### ISSUE TITLE
Windows Seafile clients need to be officially certified at Microsoft

### ISSUE THREAD

**Issue by replug** [haiwen/seafile#1736]
Users who are downloading the Windows Seafile (Shibboleth) client via your website https://www.seafile.com/en/download are complaining about the installation process. 
They are confused by a warning message by the Windows "SmartScreen" (see screenshot - in German). 
To install the client, they need to allow an exception within the Windows "SmartScreen" dialogue (see screenshot - in German).
This happens because the client software has no official certification by Microsoft. 
It concerns Windows 8, Windows 8.1, and Windows 10.

Please check the following websites to get an official certification for Seafile in the Windows App store: https://msdn.microsoft.com/en-us/library/windows/desktop/mt637086.aspx
https://msdn.microsoft.com/en-us/library/windows/apps/hh694081.aspx

Thanks!

![seafile-client-windows8-smartscreen-weitere-infos](https://cloud.githubusercontent.com/assets/1543409/17559242/d581b192-5f1d-11e6-94ee-4df8953e5c68.jpg)

![seafile-client-windows8-smartscreen-hinweis](https://cloud.githubusercontent.com/assets/1543409/17559251/e1722914-5f1d-11e6-8b23-34b07160673f.jpg)

**Comment by lins05** [comment]
Thanks for reporting this. We've already noticed it and are in the progress of updating the packaging/releasing process so the windows installer and binaries would be signed with windows authenticode.

**Comment by egroeper** [comment]
Is this already fixed? Couldn't reproduce the issue anymore today.

**Comment by freeplant** [comment]
fixed already.
