### ISSUE TITLE
localhost:8000 site refuses to connect after deploying with mysql on windows

### ISSUE THREAD

**Issue by gaoag** [haiwen/seafile#1741]
Hi seafile community,

I am setting up seafile and running into problems with MySQL deployment on windows. When I do the initial download and setup and go to localhost:8000 on my browser, the website appears and I can log in just fine. 

Then, after I move to the next step (MySQL deployment) and do what it asks exactly, I can no longer access the localhost:8000 page. It says that the site refused to connect and that localhost:8000 can not be reached. 

My error logs for seahub_django_request is completely empty, so I thought it may be a firewall issue of some sort. However, even turning off the firewall completely doesn't solve the problem. What should I do? I will post my other logs here for reference, although none of them show any error. 

[ccnet.txt](https://github.com/haiwen/seafile/files/429021/ccnet.txt)
[seafserv.txt](https://github.com/haiwen/seafile/files/429024/seafserv.txt)
[seafserv-applet.txt](https://github.com/haiwen/seafile/files/429023/seafserv-applet.txt)
[seahub.txt](https://github.com/haiwen/seafile/files/429025/seahub.txt)

[seafile.txt](https://github.com/haiwen/seafile/files/429026/seafile.txt)

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com

**Comment by mastersuv** [comment]
Hi gaoag, I'm having this exact problem right now... Did you managed to solve it out? Thanks
