### ISSUE TITLE
File does not exist error in web interface

### ISSUE THREAD

**Issue by alvinwng** [haiwen/seafile#1747]
In the Seafile web interface, if the filename contains a space, you will see "File does not exist" when you click into it. Normally you would see a download button.

How to reproduce: In the default library "My Library", I copied the file seafile-tutorial.doc to "copy of seafile-tutorial.doc". In the web interface, the file shows up, but clicking into it resulted in the error.

**Comment by guido-osict** [comment]
same problem 
https://forum.seafile.de/t/seafile-in-ff-osx-webbrowser-white-space-in-filename-bug/5044

**Comment by focmb** [comment]
Same issue here on Seafile Server CE 6.0.6 on Raspberry Pi 3.

**Comment by killing** [comment]
If you're using Apache, you may be hitting the same issue as https://forum.seafile.com/t/text-file-with-spaces-in-file-name-file-does-not-exist/855

**Comment by focmb** [comment]
Thanks for that hint. But I switched to Nginx and now all is fine.

**Comment by qnxor** [comment]
This is happening again. I have Apache 2.4.20. Any clues?
