### ISSUE TITLE
Tray icon not showing up in Seafile Client 5.1.4 under Xfce

### ISSUE THREAD

**Issue by alvinwng** [haiwen/seafile#1748]
I have a computer running Debian Jessie using Xfce. After installing seafile-gui, I found that running seafile-applet does not create the tray icon as in older version. Also, in the dialog asking which folder to sync to, only a small portion of the textbox and label is visible. It seems the form components are blocking each other.

I also downloaded Seafile Client 5.1.4 for another Windows machine. The resolution of my screen is 1920 by 1200, but the height of the Seafile window was so big that it goes under the Windows task bar.

I had to reinstall the clients because all of a sudden, one folder won't sync on my Windows laptop. FYI, the windows laptop is sharing 2 libraries, "Windows1" and "Window2", with my other Linux laptops. All of a sudden, "Window2" won't sync and there is no explanation (as always as with other hiccups of using Seafile). Downloading files took forever at 0% and I had to remove the library and upload the 10.2GB folder through my home wifi once again (at 3-4MB/s...). Then after this finished after 2 hours, I found that the client on the Linux side won't sync the same folder. And I had to install the client 5.1.4 to solve the issue. That's why I found the GUI and tray icon problems. Now I downgraded to 5.0.6 and it looks like it's working fine.

It was lucky that I still had the older .deb packages. I do not appreciate changing the names of the packages and putting things to Bintray now. The old versions are all gone. At this quality, I highly doubt if this would have very successful commercial use. I have used Seafile for 3 years and I think it's still not reliable in my opinion. There is no self-diagnosis built into the server. From my experience, if the files were corrupted on the server, the clients would not know without using seaf-fsck. This is very bad for protecting and ensuring the integrity of user data, which should be Seafile's top priority.

**Comment by dbruenig** [comment]
Are there any indicators from the log files regarding the synchronization failure ?

**Comment by alvinwng** [comment]
I don't think I saw anything meaningful in the logs. I was in the process of moving Seafile server to Apache with SSL. Before that I used seaf-fsck to fix all the errors and synchronized everything. The error happened after I moved the server from a Raspberry Pi running Debian Wheezy to one with newly installed Debian Jessie. I forgot if I was using Apache already, but nothing in that folder has been changed after synchronizing.

**Comment by dbruenig** [comment]
Regarding missing tray symbol in xfce: Which syslog messages are produced after seafile-applet is executed?

**Comment by alvinwng** [comment]
If you are asking for messages I saw when I ran it from a terminal simulator, I did not see any message at all.

**Comment by dbruenig** [comment]
the system log / journal (/var/log or journalctl)

**Comment by alvinwng** [comment]
Unfortunately I did not check those. I can try to check them if I have an opportunity next time. But my system is a standard Xfce install from the debian-8.1.0-amd64-netinst.iso image. It should be fairly easy to reproduce.

**Comment by dahabakuk** [comment]
hi,
im on gnome3 with ubuntu 16.04 - i had to remove the package appmenu-qt5 to get the icon to show..
maybe this does help you?

**Comment by dbruenig** [comment]
@dahabakuk 
On Debian 8.6 there is only appmenu-qt and it does not make a difference there. Good to know that it works on Ubuntu.

**Comment by derschueddi** [comment]
I had the same issue with the tray icon not showing up in Debian Jessie + MATE and a simple:

apt-get install --reinstall seafile-gui

solved the problem for me.

**Comment by camlafit** [comment]
Hi

On gnome3/Jesssie, seafile gui is not displayed on tray icon bar. I don't why but it lost also synch with seafie repo. I must run an unsync and sync to get updated status. I must also redo all updates step by step to get a correct change status.

Now I must always seafile interface open to ensure sync is done.

**Comment by dbruenig** [comment]
@camlafit 
For gnome3 see https://github.com/haiwen/seafile-client/issues/797
For sync problem check your log files.

**Comment by c0d1ng** [comment]
@dahabakuk worked for me!
In my case, I was using the seafile client in gnome, working fine. Then installed KDE Plasma, still working fine. But after switching back to gnome the icon didn't show anymore. 
Guess that KDE package messed up with gnome/GTK somehow.
