### ISSUE TITLE
Can only display 100 files, and the rest of the show does not come out

### ISSUE THREAD

**Issue by BenVim** [haiwen/seafile#1749]
Can only display 100 files, and the rest of the show does not come out。

I uploaded 1000 files.
but
only display 100 files

**Comment by freeplant** [comment]
It should have already been solved in version 6.0.1.

**Comment by sagarbehere** [comment]
I am on Seafile server 6.1.2 and am facing exactly the same problem. Can not scroll past the first 100 displayed files/folders.

Tried on Ubuntu Xenial 16.04 amd64 with both Firefox 55.0.2 (64-bit) as well as Google Chrome Version 60.0.3112.113 (Official Build) (64-bit). No output in the Console under Developer Options on these browsers.

The issue does not happen with the same browsers on my macbook air ?!

**Comment by shoeper** [comment]
On Windows with Chrome the issue also occurs.

**Comment by aydindemircioglu** [comment]
still not fixed correctly.
