### ISSUE TITLE
[mkdir with parent] Invalid relative path / - Firefox developper

### ISSUE THREAD

**Issue by unixfox** [haiwen/seafile#1750]
I upgraded my server from Seafile 5.1.3 to 5.1.11 (Professional version) and when I tried to upload something, it failed with this error (seafile.log):

```
[09/05/2016 08:33:29 AM] repo-op.c(2559): [mkdir with parent] Invalid relative path /.
[09/05/2016 08:33:29 AM] upload-file.c(499): [upload folder] Invalid relative path.[09/05/2016 08:34:08 AM] repo-op.c(2559): [mkdir with parent] Invalid relative path /.
[09/05/2016 08:34:08 AM] upload-file.c(499): [upload folder] Invalid relative path.
```

I don't know why I've the issue because it worked fine before I upgraded !

**Comment by lins05** [comment]
Have you tried with another browser, or using chrome's incognito mode?

**Comment by unixfox** [comment]
You've right, I'm using Firefox developper edition (50.0a2 (2016-09-03)) and it doesn't work on it but works on Chrome. I didn't realised that just after the upgrade I changed my default browser to Firefox 50.

**Comment by freeplant** [comment]
This error should only occur if you try to upload a folder via Firefox/IE

**Comment by unixfox** [comment]
@freeplant I'm not uploading a folder but just one file using the button `Import files`.

**Comment by xiez** [comment]
yes, this is a known issue in firefox developer version, we'll try fix it.

**Comment by gauburtincc** [comment]
Hi,
I also have this bug (files and folder)
Hope it will be checked soon ;-)
Regards

**Comment by freeplant** [comment]
It has been fixed.
