### ISSUE TITLE
UI suggestion: group interface

### ISSUE THREAD

**Issue by david-oswald** [haiwen/seafile#1755]
In Seafile server 6.0.3, the interface for groups has become more less intuitive. For example, important pages like "Wiki" or "Discussion". For example, accessing the Wiki requires now: Click "shared with groups", then click group name, click on Wiki icon (which does not have textual description, so is hard to locate when you do not now where to look for it). I would suggest to have a "Groups" entry in the left-hand menu bar on the start page. Then, clicking the group name there leads to a (configurable) page, e.g. Wiki or Discussion. Can such a behaviour be achieved by customising the interface (http://manual.seafile.com/config/seahub_customization.html), and, if so, in which files?

**Comment by freeplant** [comment]
Thanks for the suggesion. I will keep it in mind.

For customize the web interface, you can overwrite the file `templates\js\templates.htmp`. The side nav is controlled by the template with id `side-nav-tmpl`.

**Comment by david-oswald** [comment]
OK, I will have a look if I can achieve this. Do you accept pull requests for such cases?

**Comment by freeplant** [comment]
I'm afraid we will not accept pull request for this case. The new navigation system is file centric, which is more intuitive to most users that only use the file related functions.
