### ISSUE TITLE
Seahub using non-existent cache after upgrade

### ISSUE THREAD

**Issue by TexasDex** [haiwen/seafile#1758]
I upgraded from 4.1.2 to 6.0.3, and now the seahub web interface is broken, and when I inspect the site it's attempting to load things from the /media/CACHE folder, which doesn't exist.  It also didn't exist in the older seahub dir.

I tried stopping seahub and clearing out /tmp/seahub_cache (as mentioned in #1261) but the directory still hasn't been created on either my nginx server or my seahub/seafile server.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
