### ISSUE TITLE
Provided libraries still not working for LDAP 

### ISSUE THREAD

**Issue by TI-Admin** [haiwen/seafile#1760]
On Ubuntu 14.04 I still have to move/rename these libraries from seafile/lib to make LDAP working.
I already had this problem with 12.04 but thought it would be ok for 14.04 but it is not.

liblber-2.4.so.2
libldap-2.4.so.2
libsasl2.so.2

**Comment by freeplant** [comment]
Please refer to our document, there are four so files need to be removed.
