### ISSUE TITLE
After selective sync of a subfolder by any user, this folder shows as an individual library in the admins' “My Libraries” section of the iOS Seafile App and SeaDrive Client

### ISSUE THREAD

**Issue by SeanGriffith** [haiwen/seafile#1763]
Since the introduction of selective sync of subfolders in the Community Edition I am experiencing a peculiar phenomenon. If another user selectively syncs a subfolder of a folder that is shared to him (through a group), this subfolder appears as an individual library in the “My Libraries” overview in the iOS Seafile App of the server admin and also in the new SeaDrive Client.

My setup is as follows:
- Seafile Server Community Edition (V. 6.0.3) running on a Raspberry Pi 
- Administrator Admin1 is the owner of a folder “data” with many subfolders
- User1 and User2 are no admins, just regular users
- User1, User2 and Admin1 are members of “datagroup”
- Folder “data” is shared to group “datagroup”

The strange behavior arises, when **User1 or User2** install the Seafile Client on their PC ( I tested Win10 Client and MacOSX Client ) and selectively sync one of the subfolders ( e.g. dataset1 ) from the folder “data”. After that this subfolder “dataset1” appears as an individual library in the “My Libraries” section **for Admin1** in the iOS Seafile Client and in the new SeaDrive Client, but not in the webinterface and not in the Windows 10 Seafile Client.

Even after the synced subfolder is unsynced by User1 or User2, they are still present in the admins' "My Libraries" section, which leads to an accumulation of (anyways unwanted) libraries in this section and makes it very crowded.

**Comment by freeplant** [comment]
There is because you had turned on "show sub-libraries" in an old version. Anyway, in next release, we will fix the problem regardless whether "show sub-libraries" had been turned on.
