### ISSUE TITLE
MySQL error on seaf startup

### ISSUE THREAD

**Issue by mastercake10** [haiwen/seafile#1764]
Hello,
seafile isn't working for me anymore.
I get the following error when starting **./seafile.sh**:
`SQLException: Failed to start connection pool -- Access denied for user 'seafile'@'5.3.51.44' (using password: YES)
 raised in ConnectionPool_start at src/db/ConnectionPool.c:287
failed to run "ccnet-server -t"
`
The mysql user is setup correctly in the configs, its possible for me to login in with **mysql -u seafile -p**.
It doesn't matter using root user or seafile user for mysql, the error is still there.

Using **Debian GNU/Linux 7.11 (wheezy)** and **Seafile 5.0.4**.

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com
