### ISSUE TITLE
Invalid directory of seafile-data after moving to different location

### ISSUE THREAD

**Issue by patrykkalinowski** [haiwen/seafile#1765]
I have changed name and location of my seafile server folder.
I'm using MySQL, settings are the same.

When trying to execute `./seafile.sh start` I'm getting error:
`" is invalid or doesn't exits.tory "/home/patryk/Public/cloud.patrykkalinowski.com/seafile-data
Please check it first, or create this directory yourself.
`

The problem is, directory exists and have full permissions for current user. What might be the cause?

**Comment by LeonardoGentile** [comment]
I'm having the same problem, I've moved the data directory to another path, changed the `ccnet/seafile.ini`  but I receive that error message and server won't start
