### ISSUE TITLE
Concflicting files with seafile-server

### ISSUE THREAD

**Issue by eolianoe** [haiwen/seafile#1766]
As discussed on the [forum](https://forum.seafile.com/t/seafile-server-and-seafile-client-packaging-guidelines/662) there are some conflicting files between those provided by this repository and the [seafile-server repository](https://github.com/haiwen/seafile-server).
These conflicts prevent to install both seafile (as a dependency of seafile-client) and seafile-server.

**Comment by eolianoe** [comment]
Any updates on a clean structure of the various seafile components ?

**Comment by killing** [comment]
With the latest client, ccnet is no longer needed. So I think this solves the conflicts.

**Comment by eolianoe** [comment]
Yes, as ccnet is now "deprecated" everything is ok
