### ISSUE TITLE
New feature : Generate link to view file in browser

### ISSUE THREAD

**Issue by matteli** [haiwen/seafile#1771]
First, i want to tell you that your work is fantastic. 

I can't find the possibility to generate a public link for a file for a direct view in the browser (for a pdf file or a html file for example).
Is it a feature that you plans to add to seafile ?

Thanks

Matthieu

**Comment by freeplant** [comment]
You can add `?raw=1` to a public link.

For more usage questions, please ask in our forum forum.seafile.com.
