### ISSUE TITLE
Video File Upload from iOS to Seafile 6.0.4 - corrupted Video Files from iOS

### ISSUE THREAD

**Issue by agilastic** [haiwen/seafile#1773]
Uploading videos from iOS to SeafileServer 6.0.4 (6.0.2 also doesn't work) the videos are uploaded completely but are not playable. Every media player says file incorrect file format. Sending the same video via E-Mail and identical size, they are playable....
  
Infos:
Linux  3.16.0-4-amd64 
Debian 8u3
seafile-server Version: 6.0.2
Client: iOS 10

Really short MOV Videos are playable ... the Rest is unplayable on the Desktop.. (maybe random luck...)

Auto Upload: ON
Upload Videos: ON
Background Upload: ON

Example: 
IMG_1040.mov was transfered via Seafile  (corrupted)
IMG_1040_2.mov was transfered via E-Mail (working)

 ls -nl IMG_1040.mov
Size: 34747761  1 Okt 20:23 IMG_1040.mov
ls -nl IMG_1040_2.mov
Size:  34747761  1 Okt 20:31 IMG_1040_2.mov
-> Filesize looks the same...

Looking the head content via hexdump:

hexdump -n60 IMG_1040.mov
0000000 ad c4 d4 5d 54 09 72 ec 8c ae 7d de 91 18 db cb
0000010 6d 74 cd a2 11 49 ed a7 ed 23 86 f8 17 e0 f0 2f
0000020 4c 22 62 b6 11 7e e3 d1 3f 57 ad 4d ed 68 49 6d
0000030 42 fb c4 c7 ce 1c 43 fb ad 1a dd be
000003c

hexdump -n60 IMG_1040_2.mov
0000000 00 00 00 14 66 74 79 70 71 74 20 20 00 00 00 00
0000010 71 74 20 20 00 00 00 08 77 69 64 65 02 11 f1 f6
0000020 6d 64 61 74 9a ff 9a ff 64 ff 64 ff 61 ff 61 ff
0000030 43 ff 43 ff 2b ff 2b ff 32 ff 32 ff
000003c
 

-> So the HEX-Content looks totally different....

**Comment by killing** [comment]
This turns out to be a server side bug. Files larger than 10MB uploaded from iOS client will be corrupted on the server. The block order of these files is incorrect. This will be fixed in the next version of server. However uploaded videos have to be re-uploaded.

**Comment by sentientnebula** [comment]
It's still not fixed.  It's gone in the other direction.  All files over 2GB are corrupted on 6.0.13 Pro, and 6.1.0 Pro Beta.

**Comment by sentientnebula** [comment]
Oops, I meant files > 2MB get corrupted, not 2GB.  I could live with a 2GB limit. :)
