### ISSUE TITLE
LDAP over TLS does not work

### ISSUE THREAD

**Issue by dak-csis** [haiwen/seafile#1774]
Hi,
I've been trying to debug LDAPS and I'm stumped -- i hope someone here can help with a solution or further debugging steps.

First, to demonstrate LDAP:// works

ccnet.conf:

```
[LDAP]
HOST = ldap://ldapauth1.xxx.xxx
BASE = ou=Users,ou=xxx,dc=xxx,dc=local
USER_DN = xxx@xxx.local
PASSWORD = xxx
LOGIN_ATTR = mail
```

ccnet.log shows this when I authenticate with my AD credentials:
`[10/04/16 13:30:16] ../common/session.c(398): Accepted a local client`

Now, simply adding "s" to ldap:// i get this:

```
[LDAP]
HOST = ldaps://ldapauth1.xxx.xxx
BASE = ou=Users,ou=xxx,dc=xxx,dc=local
USER_DN = xxx@xxx.local
PASSWORD = xxx
LOGIN_ATTR = mail
```

I now get rejected at login and get this in the logs:

```
[10/04/16 13:32:58] user-mgr.c(277): ldap_bind failed for user xxx@xxx.local: Can't contact LDAP server.
[10/04/16 13:32:58] user-mgr.c(361): Please check USER_DN and PASSWORD settings.
```

I've already done the suggested step in documentation and moved away the libraries from the lib directory:

```
root@seafile:/opt/seafile/xxx/seafile-server-latest/seafile# ls 
bin  disabled_libs  docs  lib  lib64
root@seafile:/opt/seafile/xxx/seafile-server-latest/seafile# ls disabled_libs/
liblber-2.4.so.2  libldap-2.4.so.2  libldap_r-2.4.so.2  libsasl2.so.2
root@seafile:/opt/seafile/xxx/seafile-server-latest/seafile# 
```

What more can I do to fix this?

Using ldapsearch i can bind fine using both ldap:// and ldaps://

**Comment by killing** [comment]
What OS are you using?

**Comment by dak-csis** [comment]
Debian Jessie

dak@seafile:~$ uname -a
Linux seafile 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux

The AD server is running Windows something.

**Comment by qk4l** [comment]
I have several installations with ldaps (AD) all of them works perfect.

I suggest you to test your TLS connectivity first by using `openssl s_client` and check if FQDN match CN  and your system has required CA certificate.

**Comment by deric** [comment]
Having same issue on Debian 8.

```
apt install ldap-utils
```
I'm able to run queries from the same machine with TLS:
```
ldapsearch -H ldaps://ldap.example.com  -w PASSW0RD -x -b "ou=people,dc=example,dc=com" -D "uid=search,dc=example,dc=com"
...
# search result
search: 2
result: 0 Success
```
In seafile the only working configuration is with `ldap://`.

**Comment by imwhatiam** [comment]
We tested Seafile with ldaps integration on Debian 8.6 this afternoon, it works well.

As the manual (https://manual.seafile.com/deploy/using_ldap.html#using-tls-connection-to-ldapad-server) says, we should use these 4 files (liblber-2.4.so.2, libldap-2.4.so.2, libsasl2.so.2, libldap_r-2.4.so.2) from system (NOT from Seafile installation).

But I noticed that `libldap_r-2.4.so.2` is missing in your paste, could you check it again?

**Comment by deric** [comment]
@imwhatiam Thanks, that solves the issue. Sorry, I've overlooked that.
