### ISSUE TITLE
Unexpected folder permissions behaviour

### ISSUE THREAD

**Issue by rabb1t** [haiwen/seafile#1775]
# Environment

Operating system: `CentOS Linux release 7.1.1503 (Core)`
Seafile release: `seafile-pro-server-5.1.11`
Database: `mysql  Ver 15.1 Distrib 10.0.27-MariaDB, for Linux (x86_64) using readline 5.1`
# Description

User can not upload files to group shared folder even when your remove the _Read-Only_ permission on this folder afterwards
# Steps to reproduce
- Create new group `group_j`
- Create new library `lib_j` and go inside it
- Create new folder `folder_j`
- Set folder `folder_j` group permissions to _Read-Only_ for the group `group_j` and go inside it
- Create new folder `folder_j_subfolder`
- Share folder `folder_j` to group `group_j` with _Read-Only_ permission
- Go to `group_j` and open _Manage Members_ window
- Add user `user_j` as a member of `group_j`
- In the left-hand pane inside the **Group** menu select group `group_j` and go to folder `folder_j`
- Set _User Permission_ for user `user_j` to _Read-Write_ on folder `folder_j_subfolder`
- (OPTIONAL) Remove the _Read-Only_ group permission on folder `folder_j` inside the `lib_j` library
### Expected behaviour:

User `user_j` is able to upload files to folder `folder_j_subfolder`
### Actual behaviour:

User `user_j` can't upload files to folder `folder_j_subfolder`

**Comment by killing** [comment]
This is a minor bug in the web interface. The interface should not allow you to set folder permission in the Group view. If you set the folder permission from inside the library "lib_j" directly, you'll get the expected behavior.

**Comment by rabb1t** [comment]
In addition to that I think the interface should not allow user to set the permissions onto unshared folder. Because it is useless.

**Comment by freeplant** [comment]
Fix in version pro 6.0.3
