### ISSUE TITLE
Can't reset user password

### ISSUE THREAD

**Issue by hurelhuyag** [haiwen/seafile#1779]
I'm recently deployed seafile 6.0.4. I followed guide. Now I can't reset any user's password. This dialog freezed.
![screenshot from 2016-10-14 17-23-38](https://cloud.githubusercontent.com/assets/1059242/19382484/0ae35032-9233-11e6-8233-1e9c367bd13e.png)

**Comment by freeplant** [comment]
It is likely that the web is blocked in sending email to the user and the email server you use is very slow.

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com

**Comment by hurelhuyag** [comment]
I'm using sendgrid.net. My many projects use it. It has no issue. What is requirement of email server? Maybe documentation should be improved.

**Comment by freeplant** [comment]
Can check seahub.log and seahub_django_request.log to see if there are any corresponding errors?

**Comment by hurelhuyag** [comment]
Nothing useful in log. But It worked after I changed SSL port to TLS port. Maybe email sender's timeout is too high.
