### ISSUE TITLE
Linux Server - Enabling Https with Apache

### ISSUE THREAD

**Issue by GerhardK90** [haiwen/seafile#1780]
Hello,

I just ran into problems with the webinterface after following this tutorial:
https://manual.seafile.com/deploy/https_with_apache.html 

I was not able to preview/download files with the webinterface. 
The error message were "File does not exist" when attempting the download and "The image could not be loaded" when attempting to preview an image. 

After reviewing the configuration suggested in the manual, I could fix the error by changing 

`  <Location /media>`
    `   ProxyPass !`
    `   Require all granted`
  `</Location>`

to 

`  <Location /media>`
  `    Require all granted`
 ` </Location>`

Everything seems to work now, but I am not sure if my seahub is setup correctly now. 

Thank you for your advises.

**Comment by freeplant** [comment]
Thank you very much. I removed ProxyPass.
