### ISSUE TITLE
Download Directory via API does not work

### ISSUE THREAD

**Issue by qk4l** [haiwen/seafile#1782]
Hi,

Downloading Directory via WEB API v.2.1 does not work. Link which Seafile generates after calling `/repos/{repo_id}/dir/download/'` returns 400 `Bad access token` error.

Files downloading works perfect.

Tested on follow versions: 6.0.0, 6.0.4, 6.0.5

**Comment by caniwi** [comment]
This does not in 6.0.6 either but does work in 5.1.4

**Comment by imwhatiam** [comment]
Api for downloading directory is no more used, we have updated the manual recently: https://manual.seafile.com/develop/web_api_v2.1.html#download-directory
