### ISSUE TITLE
Wrong Content-Type is returned by seafhttp daemon for jpeg image

### ISSUE THREAD

**Issue by rabb1t** [haiwen/seafile#1783]
Hi guys,

Users can not view jpeg images because of wrong Content-Type while using Internet Explorer. Here you can see that mime type for jpeg image is `image/jpg` rather than `image/jpeg` (https://www.w3.org/Graphics/JPEG/):

https://github.com/haiwen/seafile/blob/60b8f9dd9b7c0862c90441319dbb65ecd632ddf1/server/access-file.c#L123

Internet Explorer aborts images with the wrong mime-type so the user can't view image contents.

**Comment by andi-blafasl** [comment]
seafile is sending image/jpg as mime type in my installation, but IE is displaying the images in the Preview, in new Windows and even if I request the image direct via it's url it is displayed.

I'm running seafile 6.0.4 on Ubuntu 14.04 behind apache

**Comment by rabb1t** [comment]
Issue is not present if we're talking about Microsoft Edge browser. But the lower versions of IE starting from IE11 didn't work properly as you can see here: ![wrong_jpeg_mime_type.png](https://www.dropbox.com/s/rzfgiunah61d1qi/wrong_jpeg_mime_type.png?dl=0)

**Comment by killing** [comment]
Fixed in https://github.com/haiwen/seafile-server/pull/8

**Comment by rabb1t** [comment]
Hi, the bug is still present in `seafile-pro-server v6.0.4`

**Comment by cuihaikuo** [comment]
What is your IE version?  My test on IE8 and IE10 is OK

**Comment by rabb1t** [comment]
Hi, reproduced on IE11. Here is the screenshot: https://www.dropbox.com/s/q45q7el0v0qzl4q/seafhttp_jpg_ie_problem.png?dl=0
