### ISSUE TITLE
Manage Group Members: No GUI Element to add users to groups

### ISSUE THREAD

**Issue by schwerg** [haiwen/seafile#1785]
After updating form 6.0.3 o 6.0.4 the GUI Element to add users to a Group vanished. There is no means to add users to groups.

**Comment by andi-blafasl** [comment]
I just search some time to find the "add user to group" function in the new GUI:

- click "Shared with groups" on the left panel
- click "All Groups" on the left panel
- either create a new Group with Button on in the top right corner
- or click on the name of an existing group in the lower right panel
- now there are there icons on the top right corner
- 1. Gear = Settings
- 2. Person = Members
- 3. Speechbubbles = Discussions
- click the Gear Icon and select "Manage Members"
- type the user or email address you want to add

Hop that helps
