### ISSUE TITLE
Readonly sync of seafile library with overwriting local changes from server

### ISSUE THREAD

**Issue by MurzNN** [haiwen/seafile#1788]
I have the main computer, that contains library with files, and many client computers, that must have copy of files from server. So I shared library from main computer to client computers as read-only.
First sync finishes normally - I see copy of files from main computer.
But when users on client computers changes or remove files, they was not restored from server.

How can I force seafile-cli to resync library from server? 

Can I add option for automatically restore file from server on local changes?

**Comment by killing** [comment]
Please post questions on our forum: https://forum.seafile.com

**Comment by MurzNN** [comment]
Ok, sorry for wrong issue, because I was think that this is issue, not discussion. Here is forum topic about this problem https://forum.seafile.com/t/read-only-seafile-library-sync-breaks-if-local-files-changed/992 but with no solution at now. And here is feature request: https://github.com/haiwen/seafile/issues/1791
