### ISSUE TITLE
seaf-cli http-tx-mgr.c(653): http://   Couldn't resolve host name.

### ISSUE THREAD

**Issue by ncp1237** [haiwen/seafile#1794]
Linux 16
Server: PRO 6.0.2
desktop client Win7 seafile 6.0 -Ok!
console client 4.3.2   - Bad 

Show log:
> [04/25/16 08:31:24] clone-mgr.c(812): Transition clone state for xxx from [connect] to [connect].
> [04/25/16 08:31:24] http-tx-mgr.c(653): libcurl failed to GET http://xxx/seafhttp/protocol-version: Couldn't resolve host name.

On `curl http://xxx/seafhttp/protocol-version:` return html page "Sorry, but the requested page could not be found."`

What is it?

**Comment by killing** [comment]
Are you using https or http?

**Comment by ncp1237** [comment]
http

**Comment by ncp1237** [comment]
It's work!

It is necessary to clean the old (previous) config

**Comment by ncp1237** [comment]
it's need "rm .ccnet" && "rm seafile-data"
