### ISSUE TITLE
Seafile Client Ubuntu PPA - seafile-gui file missing for Ubuntu 12.04 

### ISSUE THREAD

**Issue by replug** [haiwen/seafile#1795]
Hello, 
at the PPA https://code.launchpad.net/%7Eseafile/+archive/ubuntu/seafile-client 
there is no file for "seafile-gui" for Ubuntu 12.04. 
https://launchpad.net/~seafile/+archive/ubuntu/seafile-client?field.series_filter=precise 
Is the file just missing or does it not exist?
Thanks!

**Comment by killing** [comment]
Launchpad no longer supports building for 12.04. So it is not built. For 12.04 users, they need to compile from source I think.

**Comment by lins05** [comment]
I think the reason is ubuntu 12.04 has no package for qt5, which is required by seafile-gui package.  So as @killing said the only way to use seafile client on ubuntu 12.04 is to build from source.

**Comment by replug** [comment]
Thank you for your information!
