### ISSUE TITLE
iPhone client doesnt work properly, if you specify relative path for FILE_SERVER_ROOT in seahub_settings.py

### ISSUE THREAD

**Issue by jumpgh** [haiwen/seafile#1796]
iPhone client cannot download files,  if you specify relative path for FILE_SERVER_ROOT in seahub_settings.py . However web UI works fine. Maybe not a bug, bot documentation doesnt point directly on this fact.

**Comment by freeplant** [comment]
FILE_SERVER_ROOT doesn't support relative path.
