### ISSUE TITLE
Problems with filename when uploading a file via the WEB/REST API

### ISSUE THREAD

**Issue by royrwood** [haiwen/seafile#1799]
I'm uploading a file using the WEB/REST API and have found a couple of problems:

1) If I specify an empty filename, the upload is accepted, but then I have an empty filename, which is bad!  The web client can't show the contents of the Library/folder, and there's no way to delete that file!  I still haven't figured out how to fix this (probably will just have to delete the entire Library).

2) The API requires that an additional "filename" parameter be included as part of the "file" section of the multipart data POST.  Omitting this additional parameter will result in a 400 error, and lots of frustration on your part.  This is very confusing, since the API call has a very obvious "filename" parameter that is entirely separate from the "file" section of the multipart.  See the next point for additional problems with these parameters.

3) The API expects a separate "filename" parameter in addition to the "file" parameter, but the separate filename parameter is ignored.  Rather than using the separate filename parameter, the additional "filename" parameter that is part of the "file" section of the multipart data is used.  See the HTTP request sample below, taking note of the occurrences of "filename="this_filename_is_used.txt"" and "this_filename_is_ignored.txt".

POST /seafhttp/upload-api/8d1ce633-208b-4e02-a249-75bcb9f3875a HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Token 1a296960586d90dafc9aebab2d74f4ddf556343c
Content-Type: multipart/form-data; boundary=340c7f40-16e0-4451-be8b-5512aeb9872b
Content-Length: 450
Host: localhost:7777
Connection: Keep-Alive

--340c7f40-16e0-4451-be8b-5512aeb9872b
Content-Disposition: form-data; name="file"; filename="this_filename_is_used.txt"
Content-Type: application/octet-stream

This is a test
--340c7f40-16e0-4451-be8b-5512aeb9872b
Content-Disposition: form-data; name="filename"
Content-Type: text/plain

this_filename_is_ignored.txt
--340c7f40-16e0-4451-be8b-5512aeb9872b
Content-Disposition: form-data; name="parent_dir"
Content-Type: text/plain

/
--340c7f40-16e0-4451-be8b-5512aeb9872b--

**Comment by royrwood** [comment]
Interesting-- to deal with the empty filename, the WEB/REST API actually allows me to rename the file!  That's also a little disturbing....

**Comment by killing** [comment]
Hi,
The server code doesn't require a "filename" field in the form. It should be documentation error. If you check the upload form in browser console, you'll find only parent_dir and file field are created.

**Comment by royrwood** [comment]
Thanks— that makes sense then.


Another question I have is whether an admin account should be able to create folders and upload files to a user account.  That would be very useful for us, but currently does not work that way in Seafile.  I can see that it would be very easy to implement this (just a one or two line change to check_folder_permission( ) in seahub/views/__init__.py), but is that a patch you would accept?  Or is it a deliberate design decision to NOT allow admin accounts to read/write user account data?

**Comment by killing** [comment]
There is an option to allow admin to read users libraries. If that's useful for you, you could change the code and provide a patch. We'll merge it when appropriate.
