### ISSUE TITLE
[pgsql] ccnet.conf ignores PORT setting

### ISSUE THREAD

**Issue by biodiv** [haiwen/seafile#1801]
```
[Database]
ENGINE=pgsql
HOST=localhost
PORT=6432
USER=seafile
PASSWD=seafile
DB=ccnet_db
```
the port setting is ignored and the default port 5432 is used. Seafile 6.0.6.
```
HOST=localhost:6432
```
gives the error of an invalid host

**Comment by dakira** [comment]
The host variable is actually not used in the code. This should be an easy fix, just three files to change. Go for it. ;)

https://github.com/haiwen/seafile/search?utf8=%E2%9C%93&q=seaf_db_new_pgsql&type=Code

**Comment by freeplant** [comment]
Fixed. Will be included in the next release.
