### ISSUE TITLE
seafile 6.0.6 Web api does not allow + character as part of username

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1804]
When trying to get an auth token using an email address with a + in it.  Seafile responds with an error.  It does accept the email address with the + in the UI.

A plus sign (+) is a vaild email address character.

eg
curl -d "username=doug+admin@some.domainname.com&password=someverysecretpassword" https://test-seafile.somoe.domaininame.com/api2/auth-token/
{"non_field_errors":["Unable to login with provided credentials."]}

**Comment by adrium** [comment]
Usually, the plus sign is interpreted as a space. Have you tried `%2b`?

**Comment by imwhatiam** [comment]
you should add `--data-urlencode` if you want to  process some special characters properly.

```
lian@lian:~$ curl -d password=1 --data-urlencode username=1+1@1.com http://192.168.1.124:8000/api2/auth-token/
{"token":"265757b0a5aaf5d6b2e266d0c21791121ce6cdec"}
```

**Comment by caniwi** [comment]
The %2b is a satisfactory response and works. The --data-urlencode is perhaps the correct way for curl but can cause issues with passwords using special characters.
