### ISSUE TITLE
File upload via Seafile web-GUI with Firefox version 50 fails

### ISSUE THREAD

**Issue by replug** [haiwen/seafile#1805]
With the new, stable Firefox version 50, the file upload via the Seafile web GUI fails. 
We tested with Seafile server version 5.1.10 and 6.03, and we need a workaround for both server versions.

The problem seems to be the "/" (slash) in the relative path, as already described in issue #1750 

Test upload with the file "OpenStack_Config.pdf":
-----------------------------1897726291315
Content-Disposition: form-data; name="parent_dir"
/
-----------------------------1897726291315
Content-Disposition: form-data; name="relative_path"
/
-----------------------------1897726291315
Content-Disposition: form-data; name="file"; filename="OpenStack_Config.pdf"
Content-Type: application/pdf

Firefox 50 sets a / (slash) to the relative path and so the object can not be uploaded and is not found:
excerpt from Seafile.log: 
repo-op.c(2572): [mkdir with parent] Invalid relative path /.
upload-file.c(502): [upload folder] Invalid relative path.

If one changes in Firefox about:config the "dom.webkitBlink.dirPicker.enabled" to "disabled", the file upload works:
-----------------------------85843070129348
Content-Disposition: form-data; name="parent_dir"
/
-----------------------------85843070129348
Content-Disposition: form-data; name="file"; filename="OpenStack_Config.pdf"
Content-Type: application/pdf

FYI - the Firefox 50 changelog: https://developer.mozilla.org/en-US/Firefox/Releases/50#Changes_for_Web_developers
Files and directories - A subset of the File and Directory Entries API has been implemented, to improve compatibility with sites that were previously only compatible with Google Chrome
File.webkitRelativePath has been implemented; this contains the path of the file relative to the root of the containing FileSystemDirectoryEntry that was among the items in the list returned by 
HTMLInputElement.webkitGetEntries().

Could you please provide a solution for the Seafile server version 5.1.10 and 6.03?
We are still using 5.1.10 for our productive setup and our users can not upload with Firefox; so this is a quite urgent issue to us. Many Thanks!

**Comment by replug** [comment]
See also here: https://forum.seafile.com/t/error-uploading-files-with-firefox-50/1265

**Comment by freeplant** [comment]
Solved in 6.0.4.
