### ISSUE TITLE
Feature: Seafile Server Federation

### ISSUE THREAD

**Issue by dakira** [haiwen/seafile#1806]
Users of a Seafile server should be able to share files or folders with users of other servers much like the owncloud/nextcloud federation:

https://nextcloud.com/federation/

By now I have many Seafile servers around me and it just doesn't make sense to have dozens of accounts just to collaborate with people in other companies. Another grievance regarding this, is the distinction between upload- and download-links (see [here](https://forum.seafile.com/t/upload-links-should-have-an-option-to-allow-downloads-too/1267)).

For discussion I created a forum post:
https://forum.seafile.com/t/ability-to-share-files-with-users-of-other-servers/1268

**Comment by unendingPattern** [comment]
Bump! In support of this, would love to be able to share files between other Seafile servers hosted by friends and project collaborators. Seafile is way more robust and has individually passworded (+ encrypted) libraries.

**Comment by schmittlauch** [comment]
The protocol (actually just a bunch of REST calls + a WebDAV mount) has been standardised now as [Open Cloud mesh](https://wiki.geant.org/display/OCM/Open+Cloud+Mesh) and is adopted by Owncloud, Nextcloud and Pydio.

Seafile is listed as an interested stakeholder, so I assume this is somewhere on the roadmap?

**Comment by schmittlauch** [comment]
Nevermind, already spotted this on the road map :+1:

**Comment by sstretchh** [comment]
> Nevermind, already spotted this on the road map 👍

Where is this spotted on the roadmap ? I was looking at it and have not seen it. 

https://www.seafile.com/en/roadmap/

**Comment by moschlar** [comment]
FWIW, Seafile Server Community Edition added Open Cloud Mesh support in 8.0.1 Beta: https://manual.seafile.com/changelog/server-changelog/#801-beta-20210104

**Comment by dakira** [comment]
Thank you so so much to everyone involved! I'm finally closing this. ;-)
