### ISSUE TITLE
Seafile 6.0.x API Download Multiple Files/Directories does not work

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile#1807]
The https://cloud.seafile.com/api/v2.1/repos/%7Brepo-id%7D/dirents/download-link/?parent_dir={parent_dir}&dirents={dirents} API call produces a valid download link but when the link is used, you get 

Invalid URL

 response from seafile when using curl 

Can not see anything in the logs.

**Comment by caniwi** [comment]
a wget on the link gets 
400 Bad Request
2016-11-25 11:30:36 ERROR 400: Bad Request.

**Comment by imwhatiam** [comment]
This api which is used for downloading Multiple Files/Directoriesis is no more used, we have updated the  manual recently: https://manual.seafile.com/develop/web_api_v2.1.html#multiple-files-directories-download
