### ISSUE TITLE
Share file password protection doesn't work from file view

### ISSUE THREAD

**Issue by thallada** [haiwen/seafile#1808]
I created a markdown file in one of my folders. If I am in the folder view and click the share icon on the row for this file and password protect, it works fine. However, if I click through to view the rendered markdown file and then click the share icon in the upper right corner and try to password protect it, I'm able to access the file without entering a password.

I'm using Seafile server version 6.0.5.

**Comment by freeplant** [comment]
Thanks. Fixed in https://github.com/haiwen/seahub/pull/1412.
