### ISSUE TITLE
No File Audit Infomation

### ISSUE THREAD

**Issue by RM4G00** [haiwen/seafile#1809]
Hello,

Cento7 x64  - seafile-pro-server_6.0.3 & 6.0.4 using using script install - all installed normally ... no audit information for file upload..access or permission.

Auditing enabled in conf seafevents file.

Any suggestions?

**Comment by freeplant** [comment]
Change [AUDIT] to [Audit] should solve the problem. We will fix the bug in the next release.

**Comment by RM4G00** [comment]
No luck...
