### ISSUE TITLE
RFE: Support SecurePass/RADIUS

### ISSUE THREAD

**Issue by gpaterno** [haiwen/seafile#181]
Hi! Aside the LDAP support, it would be great to have RADIUS authentication.
I'd love to use it with SecurePass (www.secure-pass.net) to have two factor. SecurePass answer RADIUS, so a generic RADIUS implementation would be great. Thanks.

**Comment by seppi91** [comment]
Any progress on this?

**Comment by shoeper** [comment]
Don't think so.

**Comment by freeplant** [comment]
We have already implemented many authentication methods over the years. This feature is not interested by most of the user. We will not implement it.
