### ISSUE TITLE
Issue: Seafile does not determine new file in mounted folder

### ISSUE THREAD

**Issue by GlebPoljakov** [haiwen/seafile#1812]
I have three hosts: Server, Client and Storage.

Server - is a Seafile server;
Client - is a Seafile CLI client
On Client:
* i mounted folder /home/user1/Folder1 from Storage into /home/user1/Documents/Folder1 by SMB(CIFS) or SSH-FS;
* i setup library sync to /home/user1/Documents/Folder1.

Then do the following:
1. on Storage i create big file (200MB) "file1" in folder /home/user1/Folder1.
2. wait for several minutes or several hours - it does not matter, result is the same;
3. on Client check status of the library by seaf-cli status - it is "syncronized";
4. open web-portal of Seafile on Server, view the library - there is no the "file1";
5. on Client invoke seaf-cli stop, wait and then invoke seaf-cli start;
6. continuously check library status - it change through the following states: "syncronized" -> "commiting" -> "uploading" -> "syncronized".

Summary: Seafile-Client can determine Remote Storage file changes only on startup.

Is there any posibility to make Seafile-Client able to determine Remote Storage file changes on the fly?

Thanks in advance!

**Comment by shoeper** [comment]
The storage needs to support inotify, otherwise you need to specify a sync intervall - I'm not sure if this currently works in the cli client.

**Comment by GlebPoljakov** [comment]
Dear @shoeper!

Thanks in advice!

Today im try to implement inotify events by using tool [watchntouch](https://pypi.python.org/pypi/watchntouch/1.0).

Watchntouch displays, that it sees events, generate local inotify events, but there is no reaction from Seafile side. Seafile still does not sees any file changes on Storage side.

**Comment by GlebPoljakov** [comment]
Recently we checked Seafile-client for Windows.
We mount network-share as a disk, sync folder from that disk with SF-library.
Seafile-client for Windows does not determine storage-side file events... It has the same problem as client version for Linux.

**Comment by shoeper** [comment]
> Watchntouch displays, that it sees events, generate local inotify events, but there is no reaction from Seafile side. Seafile still does not sees any file changes on Storage side.

Did you restart Seafile after setting up watchntouch? I'm also not sure if watchntouch works in all cases.

> We mount network-share as a disk,
Same issue as above. Most "network shares" do not properly / reliably throw inotify events (if they do at all).

**Comment by GlebPoljakov** [comment]
> Did you restart Seafile after setting up watchntouch? I'm also not sure if watchntouch works in all cases.

For the first i start watchntouch, and only then i start seafile-client.
