### ISSUE TITLE
6.0.5: Missing files while having many files in a folder

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile#1817]
Today I found out that when there are many files in one folder not all are shown, but the files are there. Sorting the files using a different column showed the files but others were missing.

The problem seems to be that no additional files are being loaded when scrolling.

I'm using Chrome on Linux and Seafile Professional 6.0.5 on Debian.

**Comment by freeplant** [comment]
Can't reproduce the problem in pro 6.0.7.
