### ISSUE TITLE
Ubuntu 14.04 64bits & seafile-server_6.0.7_x86-64.tar.gz = OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by dorogarcia** [haiwen/seafile#1820]
Hello,

I am installing 64b package in 64b SO:

verifying user "seafile_usr" access to database seahub_db ...  done

---------------------------------
This is your configuration
---------------------------------

    server name:            Test
    server ip/domain:       test.com

    seafile data dir:       /opt/seafile/seafile-data
    fileserver port:        8082

    database:               use existing
    ccnet database:         ccnet_db
    seafile database:       seafile_db
    seahub database:        seahub_db
    database user:          seafile_usr

---------------------------------
Press ENTER to continue, or Ctrl-C to abort
---------------------------------

Generating ccnet configuration ...

Traceback (most recent call last):
  File "setup-seafile-mysql.py", line 1458, in <module>
    main()
  File "setup-seafile-mysql.py", line 1411, in main
    ccnet_config.generate()
  File "setup-seafile-mysql.py", line 810, in generate
    if Utils.run_argv(argv, env=env_mgr.get_binary_env()) != 0:
  File "setup-seafile-mysql.py", line 84, in run_argv
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
root@cloud:/opt/seafile/seafile# uname -a
Linux test.test.com 4.4.0-53-generic #74~14.04.1-Ubuntu SMP Fri Dec 2 03:43:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@cloud:/opt/seafile/seafile# md5sum ../installed/seafile-server_6.0.7_x86-64.tar.gz
2b3dc8b07075b42071adc43b8c6ddbf5  ../installed/seafile-server_6.0.7_x86-64.tar.gz
root@cloud:/opt/seafile/seafile# python --version
Python 2.7.6

Thanks.

**Comment by dorogarcia** [comment]
Hello,

The problem was that i was trying install into /opt/seafile instead /opt/haiwen. If you use default directory like the manual instructions, it will work.

Regards.

**Comment by freeplant** [comment]
I think it is caused by a problem in extracting seafile-server_6.0.7_x86-64.tar.gz. The folder name ` /opt/seafile` or `/opt/haiwen` should not be relevant.
