### ISSUE TITLE
seafile-cli from current dpkg package (5.1.3-1ubuntu) not working

### ISSUE THREAD

**Issue by maximilianduell** [haiwen/seafile#1822]
I get the following error

```
$ seaf-cli status
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 85, in <module>
    import ccnet
ImportError: No module named ccnet
```

I could not find a package in the repository which included the required python bindings.

**Comment by lins05** [comment]
The latest version is 6.0.1. Check https://github.com/haiwen/seafile-user-manual/blob/master/en/desktop/install-on-linux.md

**Comment by maximilianduell** [comment]
I followed the instructions under the debian section.

**Comment by lins05** [comment]
Can you check the output of `dpkg-query -L  libccnet0` ? 

Also do you have python3 as the default? If so you can edit the first line of the seafile-cli script to use python2 explicitly.

**Comment by maximilianduell** [comment]
Sorry, I was wrong, I have 6.0.1 for libccnet0. Python version is correct (2.7.12+ from debian).


```
$ dpkg-query -s libccnet0
Package: libccnet0
Status: install ok installed
Priority: extra
Section: libs
Installed-Size: 142
Maintainer: Ondřej Surý <ondrej@debian.org>
Architecture: amd64
Multi-Arch: same
Source: ccnet
Version: 6.0.1+git20161217.155820f-1
Depends: libc6 (>= 2.14), libevent-2.0-5 (>= 2.0.10-stable), libglib2.0-0 (>= 2.37.3), libjansson4 (>= 2.0.1), libsearpc1 (>= 3.0.7), libsqlite3-0 (>= 3.5.9), libssl1.0.2 (>= 1.0.2d), libuuid1 (>= 2.16)
Description: framework for writing networked applications in C
 The Ccnet framework provides the following basic services:
  * Peer identification
  * Connection Management
  * Service invocation
  * Message sending
 .
 This package contains shared library.
Homepage: https://github.com/haiwen/ccnet
```

```
$ dpkg-query -L libccnet0
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libccnet.so.0.0.0
/usr/share
/usr/share/doc
/usr/share/doc/libccnet0
/usr/share/doc/libccnet0/changelog.Debian.gz
/usr/share/doc/libccnet0/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/libccnet0
/usr/lib/x86_64-linux-gnu/libccnet.so.0
````

```
$ dpkg -s seafile-cli
Package: seafile-cli
Status: install ok installed
Priority: extra
Section: utils
Installed-Size: 65
Maintainer: m.eik michalke <meik.michalke@hhu.de>
Architecture: amd64
Source: seafile-daemon
Version: 6.0.0
Depends: python, libseafile0 (>= 6.0.0), ccnet (>= 5.1.2), seafile-daemon (>= 6.0.0)
Conflicts: seafile
Description: Seafile command line interface.
 This package contains the command line interface to manage Seafile libraries.
Homepage: http://seafile.com
```

Maybe I should just write directly to the debian maintainer?

**Comment by lins05** [comment]
Ah, so you're not using our debian repo hosted at bintray but using the official one packaged by @oerdnj for debian. Then it sgtm to report this problem there.

The reason seaf-cli doesn't work for you is beacuse the libccnet0 package you installed doesn't have the necessary ccnet python files included. Maybe one possible reason is debian package policy requires the python files to be in a separate pacakge, like python-libccnet?

**Comment by maximilianduell** [comment]
There is no such python-ccnet package in this repo. I checked before submitting the issue here.

**Comment by maximilianduell** [comment]
Solution was manual downgrade to official ccnet packages.
```
sudo apt-get install libccnet0=6.0.0 ccnet=6.0.0
```

**Comment by killing** [comment]
I removed python files in the ccnet project in the recent code clean-up for debian packaging. I didn't recognize that would make cli clients not working. I'll fix this.

**Comment by openpaul** [comment]
Same bug is in official debian unstable repro. So I can install seafile-cli but get the same error uppon starting.
