### ISSUE TITLE
Feature Req.: Streaming Download via tar

### ISSUE THREAD

**Issue by xkpd3** [haiwen/seafile#1826]
Hello,

As a photographer, I'm often doing free projects with other photographers and we share our RAW files completely afterwards. This means we have folders in the size of 15 to 30GB containing thousands of raw image files.

Downloading a folder that big can not really be downloaded. I raised the download size on server side, but it takes very, very long to pack the files. Not to mention the server load when more than one person clicks on the download button at the same time.

I wonder if it would be possible to provide some sort of a streaming download. Something like "tar" or "tar.gz" that can start immediately and would not required the space and time to "pre-pack" the files. 

What do you think? I could think of a configuration switch to change from zip to tar mode. Or maybe download files up to 200M via zip and switch to tar when it's bigger.

Best Regards,
Stefan

**Comment by shoeper** [comment]
The issue is not zip here.

There is one library being used (that cannot be exchanged easily) that has a bug (which is hard to fix) that disallows streaming of data.
