### ISSUE TITLE
Check already running seaf-daemon and reuse it in seafile-applet instead of starting new instance

### ISSUE THREAD

**Issue by MurzNN** [haiwen/seafile#1828]
I use console seaf-daemon (seaf-cli) on Linux for background syncing process without gui - it starts as system daemon (systemd or upstart) with my user permissions.

But sometimes I want to change settings (add library, change sync process, etc) and run seafile-applet in GUI, because use seaf-cli commands is not so comfortable.

But if I load seafile-applet gui - it immediatly kills already running seaf-daemon and ccnet, and runs new instance of seaf-daemon and ccnet. And when I unload seafile-applet - it kills those processes, so I got seafile sync process totally stopped, and must start system daemon again by hands.

Please add checking of already exists seaf-daemon and ccnet processes in start of seafile-applet, and use those processes instead of starting new. And don't kill seaf-daemon if it was exist before seafile-applet started.

**Comment by Jip-Hop** [comment]
I'm using seaf-cli and the seafile-applet gui in the same way as @MurzNN describes. But I've ran into issues when running seaf-cli and the seafile-applet gui at the same time. The GUI would show no libraries are synced, even though they are configured. To get it working I first need to stop seaf-cli and then open seafile-applet gui.

It would be very convenient if the GUI could be running side by side the cli version.

**Comment by freeplant** [comment]
This feature is beyond our range of support.

**Comment by MurzNN** [comment]
Why? This is very easy to implement! As example, Dropbox works like described - cli daemon and GUI that connects to it. But in Seafile users can't mix seaf-cli and seafile-applet, because starting seafile-applet will break work of seaf-cli, this is very annoying!
