### ISSUE TITLE
Error occured during setup. Please fix possible issues and run the script again

### ISSUE THREAD

**Issue by maikebing** [haiwen/seafile#1829]
If you are OK with the configuration, press [ENTER] to continue.

Generating ccnet configuration in //ccnet...

done
Successly create configuration dir /ccnet.

Generating seafile configuration in /mnt/ ...

Done.

-----------------------------------------------------------------
Seahub is the web interface for seafile server.
Now let's setup seahub configuration. Press [ENTER] to continue
-----------------------------------------------------------------

Creating seahub database now, it may take one minute, please wait... 

Failed to sync seahub database.

Error occured during setup. 
Please fix possible issues and run the script again.

**Comment by maikebing** [comment]
Linux version 4.1.13-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015

**Comment by killing** [comment]
I believe this is an environmental problem. You could post this on our forum. There you can find more people to help. Github is for bug reporting.
