### ISSUE TITLE
Files deleted after migration.

### ISSUE THREAD

**Issue by DavidAPC** [haiwen/seafile#1830]
I've been using Seafile for quite a while now. About a month ago my Seafile server on my Raspberry Pi went kaput due to hardware problems. For about a month I used the same folders without Seafile doing any syncing, before I fixed the hardware problems and restarted the server, later doing an upgrade from 5.0.4 to 6.0.7. I sync things up on my main PC and laptop.
A day or two later (now), I notice some files missing, remembering that the Seafile sync on the laptop even mentioned deleting a file. I go over to the history logs and find out that on the same history commit that synced the new files I'd created in the month absence, it also deleted files created about a month or tow before the Seafile server first went down.

So for instance in the Pictures library: "Added or modified "WatchDogsCard6.jpg" and 17 more files. Deleted "tracememorypuzzle.png" and 26 more files" WatchDogsCard6.jpg was a file I'd created a few days ago while the server was down and was quite rightly being synced now that the server was back up again, but tracememorypuzzle.png was a file I'd created a month before the Seafile server went down and had been successfully synced, but now was being deleted for no reason.

Thankfully, the Seafile does let me restore the files, but it's a bit tricky and I have to ensure I don't accidentally delete the recently synced files when I do it.

Finally, as an additional annoyance, if a single update both adds files and deletes files in one go, then checking the history using the web interface (by clicking "Details" link) will give you a list of the added/modified files, but not a list of the deleted ones. Makes it harder to know what files went missing. (EDIT: Created a new bug for this issue: #1831 )

**Comment by killing** [comment]
Seafile client shouldn't delete a file if the user doesn't. Are you sure you didn't delete the files somehow on one of your computers?
