### ISSUE TITLE
Web interface does not give list of deleted files if files are added of modified in the same update

### ISSUE THREAD

**Issue by DavidAPC** [haiwen/seafile#1831]
Reproduction steps:

1. Pause the syncing on Seafile Client
2. In a library, add one file, modify another, and delete a 3rd file.
3. Resume syncing.
4. Go to the web interface and view the history for that library.
5. Find the update that deals with the changes you've just made (should be the most recent update)
6. Click "Details" for that update.

Expected:
The "Details" panel that opens up should display the name of the added file, the modified file, and the deleted file.

Actual:
The "Details" panel only displays the name of the added and modified files, the deleted file name is not included.

The above makes it harder to keep track of what files have been deleted.

Note: If the update consists solely of files being deleted, the "Details" panel will display the deleted file name as expected.

**Comment by killing** [comment]
What client and server version do you use? I cannot reproduce with Windows client and the latest server. What files do you create and delete? Empty?
