### ISSUE TITLE
seaf-cli: Desync destroys library

### ISSUE THREAD

**Issue by Ninerian** [haiwen/seafile#1833]
While trying seafile and the cli tool, I discovered a behavior which destroys a library without log entries.

## Expected behavior
Desync a folder, leaves the folder unchanged and the library in the last state.

## Actual behavior
Folder stays the same, but the library is marked as broken in the web ui and the directories in the storage are gone.

![broken-library](https://cloud.githubusercontent.com/assets/117885/22067370/43603ebc-dd91-11e6-92e6-8275e73eb69a.jpg)

## Recreation steps
1. Create a library
2. Create a folder on the system with some dummy files
3. Call `seaf-cli sync -c {path to config} -s {URL} -u {Username} -p {password} -d {path to directory} -l {library-id}`
4. Copy some files into and delete some to see the sync is working and the files are created in the storage.
5. Call `seaf-cli desync -c {path to config} -d {path to directory}`
6. Check the webui and the storage

## Environment
Ubuntu 14.04
Seafile: seafile-pro-server_6.0.7_x86-64_Ubuntu
Installed and run by user seafile
Served via Fast-CGI & nginx

**Comment by freeplant** [comment]
We can't reproduce the problem.
