### ISSUE TITLE
Is there a way to only push files and not sync?

### ISSUE THREAD

**Issue by OmgImAlexis** [haiwen/seafile#1834]
I'd like to use this to backup my phone's photos and then delete them client side, is this currently supported at all?

**Comment by shoeper** [comment]
Is it an android phone? In that case you can access Seafile using WebDAV (seafdav) and use the app FolderSync on your phone.

**Comment by OmgImAlexis** [comment]
It's an iPhone and I was hoping to get a reply on here as the forums seem to be hit and miss at times.

**Comment by shoeper** [comment]
On the iPhone the same could work, I just don't know which apps are available to sync content there. When you find an app to synchronize data using webdav it should work (and I'm confident there is one available)

**Comment by OmgImAlexis** [comment]
From the looks of it most of them are just file browsers and require manually syncing the files. Is there any chance seafile will add this in natively?

**Comment by shoeper** [comment]
Two way sync possibly one way sync unlikely if you ask me.

Both are everything else than easy to implement.

**Comment by OmgImAlexis** [comment]
One way sync should be relatively easy to add as it'll just require the client to push but not pull files. This way it'll be treated like a backup service.

**Comment by kleinfe** [comment]
We would be happy about that feature as well! Very nice idea to name it 'One Way Sync', in that case it could even be possible to define if this is a pull only or a push only.

**Comment by shoeper** [comment]
> in that case it could even be possible to define if this is a pull only or a push only

And in both cases it should overwrite on conflict? Sounds doable to me. Would add two options - first only pull / push when powered and second only when connected with wifi / always.

Having the full sync protocol on Android would allow 2 way sync but that would be quite some work (I think). Especially optimizing it to not waste battery while also synchronising often enough to avoid conflicts.

**Comment by OmgImAlexis** [comment]
Since there's file history I don't see there being an issue with overriding files but maybe also add an option to change "override on conflict" to "rename on conflict". This would be good for things like android phones where if you delete all photo files it starts back at DSC_001 for example.

Personally I really want this for iOS and the mac client as I'd like to use Seafile as a cloud blackhole where I can just drop files into a directory and have them move from my laptop to my server without needing to manage anything. This would then allow me to open the files anywhere I want as long as I have access to the webui or a seafile client.

**Comment by freeplant** [comment]
iOS has no concept of file system. You can already backup the photos with Seafile iOS client.
