### ISSUE TITLE
Avatars directory missing – default avatars broken

### ISSUE THREAD

**Issue by blu2lz** [haiwen/seafile#1836]
Hi,

the avatars directory in seahub-data is missing in a fresh 6.0.7 install, so the default avatars all return a 404. It seems you are just copying the symlink from the ${INSTALLDIR}/seahub/media/avatars.

`lrwxrwxrwx 1 seafile seafile 28 Feb  1 13:10 seafile-server-latest/seahub/media/avatars -> ../../../seahub-data/avatars`

`lrwxrwxrwx 1 seafile seafile 28 Jan 31 10:21 seahub-data/avatars -> ../../../seahub-data/avatars`

**Comment by yyjdelete** [comment]
+1, `seahub-data/avatars` is linked to itself when I install seafile for the second time.(For the first time I have some cfg wrong, and remove all datas and try again)
I think the install should touch the installer files, just copy instead of move.

**Comment by denisrosenkranz** [comment]
Just installed the 6.2.5 versions and got the same issue.

I just deleted the link seahub-data/avatars -> ../../../seahub-data/avatars and created a folder **avatars** inside the **seahub-data** folder.

**Comment by mrbesen** [comment]
I have the same issue with seafile 6.3.4
i did not have a avatars folder in seafile-data so i created one and added this picture
```https://demo.seafile.com/media/avatars/4/7/4454e19c88a8f6f8d0982c2deee8ac/resized/160/771ec6b8ac656c1fcbf3208092b6d143_Mji589P.png```
and renamed it to default.png
still no profile picture
