### ISSUE TITLE
bintray repo for Debian doesn't have stretch

### ISSUE THREAD

**Issue by mrjovanovic** [haiwen/seafile#1837]
The bintray repository for Debian doesn't have stretch (the current candidate for testing). Considering it is going into Full Freeze tomorrow (and hence becoming a viable alternative to jessie, it should be an option.

**Comment by killing** [comment]
We are going to support Stretch soon. There will be some code changes needed.

**Comment by woffs** [comment]
I managed to compile a working seafile client for stretch today. I had just to replace libssl-dev with libssl1.0-dev in the requirements and circumvent #1842. Carry on!
