### ISSUE TITLE
Intensive 100% CPU load on server while broswing some folder with many images

### ISSUE THREAD

**Issue by bagage** [haiwen/seafile#1839]
I opened a folder in a library that contains only photos - in this specific folder there are 3000 photos with 5MB size each on average. 
If I open this folder via a webbrowser, seahub/manage.py consumes 100% CPU almost all the time (with spikes). 
See the graph activity:

![image](https://cloud.githubusercontent.com/assets/1451988/22755124/160f93ce-ee42-11e6-8de1-6262964377ab.png)

I am running seafile-server 6.0.4 on a Debian stable server.

**Comment by shoeper** [comment]
It is the expected behaviour. Thumbnails are being generated.

**Comment by bagage** [comment]
OK, thanks for the confirmation - I guess it's fine then :).
