### ISSUE TITLE
Sorting in Web GUI Doesn't Update Properly

### ISSUE THREAD

**Issue by thereisnouser** [haiwen/seafile#1840]
Just noticed a bug with file sorting in the web gui this morning

If I have 5 files like this:

File1.png
File2.png
File3.png

And then sort by last update so that the order becomes:

File2.png
File3.png
File1.png

If I then click on File3.png, it will open File2.png instead until I refresh the page.

I'm running Seafile server 6.0.7 and browsing in chrome 56.0.2924.87 on Windows 8.1. I have also tried this in Palemoon 27.1.0.

**Comment by freeplant** [comment]
This will be fixed in the next release.
