### ISSUE TITLE
Office preview seems to be malfunctioning

### ISSUE THREAD

**Issue by clayauld** [haiwen/seafile#1841]
I've been using Seafile since 2015 and have implemented many of the features in the Pro version. I've implemented the office preview feature a while back, but only recently noticed that the previews for Libreoffice are no longer working.

When I attempt to open any of these files I get a multiple page document with nothing showing.
![screen shot 2017-02-12 at 12 21 23 am](https://cloud.githubusercontent.com/assets/2290528/22860963/47194388-f0b9-11e6-92b3-bb888802da65.png)

[seafevents.log.txt](https://github.com/haiwen/seafile/files/769182/seafevents.log.txt)
[seafile.log.txt](https://github.com/haiwen/seafile/files/769183/seafile.log.txt)
[seahub.log.txt](https://github.com/haiwen/seafile/files/769184/seahub.log.txt)

**Comment by lins05** [comment]
I don't find anything special in the log files. Can you open the chrome/firefox debug console and check if there is any errors displayed?

**Comment by shoeper** [comment]
```
00:15:48,511] [INFO] unoconv process will use python 3
[2017-02-12 00:15:48,511] [DEBUG] Running command: "/usr/bin/python3" "/home/seafile/seafile-pro-server-6.0.7/pro/python/seafevents/office_converter/unoconv.py" "-vvv" "--pipe" "seafilepipe" "-l", cwd = /home/seafile/seafile-pro-server-6.0.7/pro/python/seafevents/office_converter
```
Look like python 3 is being used, Is it python 3 compatible?

**Comment by clayauld** [comment]
Attached are screenshots from Firefox and Chrome's consoles. It appears that two errors are stopping things.
![chrome](https://cloud.githubusercontent.com/assets/2290528/22869311/792199de-f14a-11e6-9647-13da1c2a57b6.png)
![firefox](https://cloud.githubusercontent.com/assets/2290528/22869312/7923a292-f14a-11e6-935e-40e9a1637592.png)

**Comment by shoeper** [comment]
You've got a wrong X-Frame-Options header.

**Comment by clayauld** [comment]
Changing the X-frame options in nginx fixed the issue. Thanks for your help!
