### ISSUE TITLE
Seafile 6.0.7 Pro On Archlinux: Internal Server Error

### ISSUE THREAD

**Issue by reee** [haiwen/seafile#1845]
I have install the seafile server 6.0.7 professional edition on my htpc witch runs archlinux.

I follow the guide on the wiki: https://manual-cn.seafile.com/deploy/using_sqlite.html
and install libselinux(2.6-2) from aur to satisfy the requirement.
And i can start the server by:
    ./seafile.sh start
    ./seahub.sh start

with no error output.
But when i try to access the server though Web Browser, I get the 500 error:

    Internal Server Error

And no ERROR in any log file in the dir ./conf

by the way, the mail daemon for bbs.seafile.com may have been broken. I receive no activation email  with email from both gmail, 163 and qq.com.

**Comment by freeplant** [comment]
Arch linux is not officially support by pro edition.
