### ISSUE TITLE
[upload]failed open temp file

### ISSUE THREAD

**Issue by zhanghqgit** [haiwen/seafile#1850]
windows 2008
seafile-server-6.0.7

when i upload file through web api and file size bigger than 600kb, it cannot work.

httpclient write some data but not finished ,and then nothing,

i find logs in seafile.log

```
upload-file.c(1962): [upload] Failed open temp file.
```
use web ui or desktop client work correctly ,only with web api not work.
thanks

**Comment by zhanghqgit** [comment]
```
public static String filePost(String url,String token,FilePart fp,StringPart sp) {
    	PostMethod method = new PostMethod(url);
    	Part[] part = {fp,sp};
    	MultipartRequestEntity mre = new MultipartRequestEntity(part,method.getParams());
    	method.setRequestEntity(mre);
    	method.addRequestHeader("Authorization",token);
        method.addRequestHeader("Accept","application/json; charset=utf-8; indent=4");
    	 HttpClient client = new HttpClient();
        
         try {
 			client.executeMethod(method);
 			if(method.getStatusCode() >= 400){
 	        	 throw new Exception("执行请求报错....<<" + method.getStatusCode() + ">>");
 	         }
 	        return method.getResponseBodyAsString();
 		} catch (Exception e) {
 			e.printStackTrace();
 			Email4SelfUtils.errorReport(new Exception("访问url报错: " + url,e),
 					"[貔貅web系统]调用url访问错误报告");
 		}
         
         return null;
    }
```

**Comment by zhanghqgit** [comment]
and nginx  error log

```
2017/03/02 23:21:41 [error] 19014#19014: *172 readv() failed (104: Connection reset by peer) while reading upstream, client: 192.168.1.8, server: seafile.example.com, request: "POST /seafhttp/upload-api/b08055c9-95a5-4700-b936-2aa4f1cd5dd0 HTTP/1.1", upstream: "http://127.0.0.1:8082/upload-api/b08055c9-95a5-4700-b936-2aa4f1cd5dd0", host: "seafile.example.com"
```

**Comment by zhanghqgit** [comment]
can anyone help me ?  thanks

**Comment by zhanghqgit** [comment]
I test many times and every Possibility, at last, it's the parent_dir problem . this param can not be Chinese , even i  use `URLEncoder.encode(str, "UTF-8")` to encode it .

**Comment by andreiperciun** [comment]
I faced same problem on rapberry pi 3 with `Seafile server 6.0.8`. Several files were uploaded but some did not. As @zhanghqgit pointed files with bigger size were not uploaded. I don't use any Chinese file name, dir names or system settings so it may not be related to encoding stuff.

Thanks!

**Comment by andreiperciun** [comment]
@zhanghqgit found what is the problem in my case. RPI console was opened during upload and it was throwing errors related to read/write errors on mounted HDD. So I ran `fsck` to scan and fix disk errors.

After this procedure upload started to work. In your case try to scan the disk and check windows `Event Log` for possible disk error messages.

It would be great to have a better error message for such messages, or, at least, add possible solutions/problems in seafile documentation.

Thank you!

**Comment by killing** [comment]
Please post questions to the forum. Github is for bug or feature requests.
