### ISSUE TITLE
seafile-cli init fails: 'ccnet-init not found in PATH. Have you installed seafile?'

### ISSUE THREAD

**Issue by laur89** [haiwen/seafile#1854]
Running on Debian testing, installed via package manager, version *6.0.4*.

Only place I found *ccnet-init*, was under server, but surely server isn't required for client?

**Comment by christmart** [comment]
Version 6.0.4-2 of ccnet in unstable fixes this issue.

**Comment by killing** [comment]
You can also use the seafile repository on bintray, which contains usually the latest version of Seafile client.

**Comment by laur89** [comment]
> You can also use the seafile repository on bintray, which contains usually the latest version of Seafile client.

[bintray](https://bintray.com/seafile-org/deb/seafile-cli) contains only the release versions (available through **stable**); eg 6.0.4-2 is not listed there, only 6.0.4.

**Comment by christmart** [comment]
Debian versions always append a Debian subversion.

Version 6.0.4-2 was uploaded 28th of februar to Debian unstable. Maybe your mirror is out of sync.

**Comment by laur89** [comment]
[Are you sure?](https://packages.debian.org/sid/seafile-cli)

**Comment by laur89** [comment]
Huh. Thought that `seafile-cli` had to be installed.

For anyone else in same position:

    aptitude install libccnet0/unstable ccnet/unstable

Cheers guys.

**Comment by christmart** [comment]
seafile-gui depends on seafile-daemon
seafile-daemon depends on ccnet and libccnet0.
So it should get automatically installed via dependencies.
