### ISSUE TITLE
Android client and WPS Office issue causes runaway data use with repeated failed uploads

### ISSUE THREAD

**Issue by SenorLAN** [haiwen/seafile#1856]
For the past few months (and releases of Seafile Android client), I have encountered an issue that causes the Seafile client to constantly try to re-upload a file that was previously opened in WPS Office.

Here is the scenario. I have WPS Office as my default file viewer for Office and PDF documents. I browse to my encrypted library in the Seafile Android client, click to open a file and open it in WPS Office. I am only viewing the document and when done I exit the WPS Office app. After a few days time, Seafile decides that this file I opened in WPS Office must be changed and needs to be uploaded to update what is on the server. It then attempts to upload the file, but fails at around 99% uploaded and then tries again..and again..and again. It does this until I notice my phone is warm and that a few hundred megabytes of my data plan have been chewed up in 30 minutes by Seafile repeatedly trying to upload the same file. This has happened on multiple occasions. 

It could be an issue with the encryption key no longer being stored in and Android client and then it failing, but there is also something else at play. One time I made sure to open the library it was failing to upload to and I could not get it to succeed until I renamed the file on the actual server so it wasnt trying to do a replace. There is also the issue that Seafile decides this file which I viewed in WPS Office, is changed after many days or even weeks have passed. 

Today is about the 4th time it has happened. It occurred with a 7Mb Power Point presentation that I opened from Seafile in WPS Office over two weeks ago. Today for some reason, in the middle of the day, it decided this file was changed and must be uploaded while I was on mobile data. It managed to chew through 1.32GB of data in probably less than an hour. Kind of a pain in the butt when I only have 2GB of data available on my cell plan. 
![screenshot_20170307-202106](https://cloud.githubusercontent.com/assets/8877311/23685942/bed5ef8e-0374-11e7-9538-3f51560c0845.png)

I am using a Moto G (3rd gen) phone which is running android 6.0. I have Seafile 2.1.10 and WPS Office 10.1.2. My server version was 5.1.3 (on linux) when I first noticed this and have since upgraded to 6.0.7.

Only fix I know at this point is to disable background data or remove WPS Office. I dont really mind if Seafile were to thing the file is changed and upload it, but only if that upload would work and not fail after transferring 99% of the file and repeatedly try and fail every second after.

**Comment by freeplant** [comment]
Thanks for reporting the issue. We will release a version that don't try to re-upload for ever in this week.
