### ISSUE TITLE
compilation of seafile-server failed due to missing includes

### ISSUE THREAD

**Issue by sh-dvl** [haiwen/seafile#1861]
error is: http-server.c:15:19: fatal error: evhtp.h: No such file or directory

same error for upload-file.c and access-file.c

this is somehow irritating, because configure checks for libevent > 2.0 (is 2.0.19), but this include-file seems to be part of libevhtp, but using this instead leads to compilation-errors of other files.

because I don't know the intention of the includes and don't know, if both libs are compatible/exchangeable, I can't fix this by myself

**Comment by lvedie** [comment]
Same issue here. 
Unsuccessfully tried to correct the links, then dumbly copy-past the headers from /usr/local/include/evhtp to the ..src/seafile-server-6.1.1-server/server. It allowed me to compile http-server.c, but it create empty declaration and deprecation for upload-file.c and access-file.c
Any news ?

**Comment by Ant-lib** [comment]
Solve this problem by installing libevhtp-dev package:
`sudo apt-get install libevhtp-dev`
and then..
`sudo cp /usr/local/include/evhtp/*.* /usr/local/include/`
