### ISSUE TITLE
Found Vulnerability (ClickJacking Vulnerability)

### ISSUE THREAD

**Issue by coderahsan** [haiwen/seafile#1863]
Hi,
This is AhsanKhan,An Ethical Hacker.

I Have Found Clickjacking Vulnerability In Your Site :)

Sites ==    1   https://demo.seafile.com/accounts/login/?next=/
![capture](https://cloud.githubusercontent.com/assets/26425352/23933553/950b63a4-08fc-11e7-90bf-627831665728.PNG)

An Attacker Can Spoof Emails With ClickJacking Mehotd Checkout the Login Area in the Iframe :)

An Attacker Can hack User's Account With ClickJacking Vulnerability :) 

If You Want to Resolve or Read More About it Then Checkout this Site :)
Site == https://www.owasp.org/index.php/Clickjacking

I Hope You Will Understand it ;)
Best Regards,
AhsanKhan
coderahsan@gmail.com

**Comment by coderahsan** [comment]
Any Update Buddy ?

**Comment by xiez** [comment]
Hi @coderahsan , already added `X-Frame-Options HTTP`, could you please take a test again ?

Thanks!

**Comment by coderahsan** [comment]
Buddy this is Clickjacking Vulnerability :) I Have Already Showed :) You

**Comment by coderahsan** [comment]
What You Want Now :)

**Comment by coderahsan** [comment]
????

**Comment by coderahsan** [comment]
Any Update Buddy ?

**Comment by shoeper** [comment]
Adding X-Frame-Options: SAMEORIGIN should have solved the issue as it denies framing. https://github.com/haiwen/seafile/issues/1863#issuecomment-287712494

**Comment by coderahsan** [comment]
Yes,
Is it eligible for any reward ?

**Comment by shoeper** [comment]
I don't know.

**Comment by coderahsan** [comment]
Ohh so you are not the employee of the site ?
I said because i thought you are from seafile programe !
