### ISSUE TITLE
SeaFile doesn't work with Fail2Ban

### ISSUE THREAD

**Issue by IssueFindings** [haiwen/seafile#1867]
Hello,
Fail2Ban uses seahub.log to bannish IP. But seahub uses UTC time zone and Fail2Ban the system time zone. When the system time zone is different than UTC, especially in advance, Fail2Ban doesn't care about "old" alerts in seahub.log and so never bannish any IP.

To fix it, I try to add TIME_ZONE = 'Europe/Paris" in seahub_settings.py. This doesn't work. So, could you explain me how to fix this bug (and definitively fix it in the next release) ?

Have a nice day.

**Comment by shoeper** [comment]
Please discuss it on the forums. https://forum.seafile.com/

**Comment by IssueFindings** [comment]
Hello Shoeper,
If I well understand my problem, this issue is directly link with the 6.0.8 SeaFile release (especially : "Change time_zone to UTC as default") because previously SeaFile and Fail2Ban work correctly. Now, they use 2 different time zones (in fact SeaFile doesn't use anymore the time zone of the system). It's a security issue (because Fail2Ban can't work with SeaFile). So, for me this issue is in the right place. What do you thing ?

**Comment by welpo** [comment]
For anyone finding this through a search engine:
Adding the line TIME_ZONE = 'Europe/Paris' (or whatever timezone your system is on) on seahub_settings.py does work. You just need to restart seafile (as discussed in [this forum thread](https://forum.seafile.com/t/seafile-doesnt-work-with-fail2ban/2377)).

That said, I see no reason why seafile shouldn't use the system timezone for logs.
