### ISSUE TITLE
./seaf-fsck.sh use cases

### ISSUE THREAD

**Issue by IssueFindings** [haiwen/seafile#1868]
Hello,
When we only have seafile-data directory and lose all other SeaFile directories (especially conf files), it appears that "./seaf-fsck.sh --export" command can export all the uncrypted libraries (many thanks for your answer Daniel Pan).

I reinstall a completly new SeaFile (with new passwords). Unfortunately, the command "./seaf-fsck.sh --export ./storage/blocks/*" gives this error : (...) fsck.c(589): Invalid repo id (...)

So where is the "repo id" in the directory seafile-data ?

**Comment by shoeper** [comment]
Please discuss it on the forums. https://forum.seafile.com/

**Comment by IssueFindings** [comment]
Done. Have a nice day.
