### ISSUE TITLE
LC_ALL issue

### ISSUE THREAD

**Issue by IssueFindings** [haiwen/seafile#1869]
Hello,

Each time I run ./seahub.sh, I have this alert : "LC_ALL is not set in ENV, set to en_US.UTF-8". How I can fix it ? And how I can customize the value of LC_ALL (because your script enforce the value en_US.UTF-8) ?

Have a nice day.

**Comment by shoeper** [comment]
This is no Seafile issue. Please discuss it in the forum: https://forum.seafile.com/.

**Comment by IssueFindings** [comment]
Done. Have a nice day.
