### ISSUE TITLE
[pro/rfe] add the ability to have a shared quota per organisation instead of users

### ISSUE THREAD

**Issue by turbomettwurst** [haiwen/seafile#1871]
Running Seafile in Multi Tenancy Mode.

It would be great if i could simply set a single Quota for an organisation instead of setting quotas per account.
Currently i can set a quota of e.g. 100GB for an Organisation and all the users within that org will have 100GB Accounts each. It would be beneficial if those 100GB would be a Teamlimit that is not explicitly alloted to certain accounts but shared.

**Comment by freeplant** [comment]
You can set quota for an organization.
