### ISSUE TITLE
CANCEL CREATE TABLE QUERY

### ISSUE THREAD

**Issue by zhanghqgit** [haiwen/seafile#1873]
for some reason,I do not have permissions to create or drop  database or table;

i just backup whole database to production environment. In this ,I only have insert \ update \ delete \select permissions.

do you have some way to fix this issue? 

for example , configure something, when setup,cancel some create table query

thank you

**Comment by shoeper** [comment]
Please use the forum (forum.seafile.com) for questions.

**Comment by killing** [comment]
I don't completely understand you question. But you can create the tables first, then start seafile. Seafile won't try to create them if they exist.
