### ISSUE TITLE
How can I "wget" a shared file ?

### ISSUE THREAD

**Issue by LemonLight** [haiwen/seafile#1878]
Hi everyone, 

I have got a question, is it possible to generate a link, when I share a file, that we can use with wget ? 
Because, for example, when I tried to download a file with these kinds of link : `http://10.1.2.3/f/059809cd57/` or `http://10.1.2.3/f/059809cd57/?raw=1` with my browser there is no problem, but when I want to get my shared file with wget I got this an `index.html` destination folder.. :/

Thanks in advance for help !

**Comment by shoeper** [comment]
This is an issue tracker. Please use the [forum](https://forum.seafile.com/) for questions.

To directly answer your question. Run `wget --content-disposition "url?raw=1"` (or dl=1)

**Comment by LemonLight** [comment]
Ok thank you :)
