### ISSUE TITLE
PVS-Studio: CWE-467 Use of sizeof() on a Pointer Type

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [haiwen/seafile#1881]
We have found a bug using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

We suggests having a look at the emails, sent from @pvs-studio.com.

Analyzer warning: [V568](https://www.viva64.com/en/w/V568/) It's odd that 'sizeof()' operator evaluates the size of a pointer to a class, but not the size of the 'ce' class object. index.c 949

**common/index/index.c:**
```
int add_index_entry(...., struct cache_entry *ce, int option)
{
  ....
  /* Add it in.. */
  istate->cache_nr++;
  if (istate->cache_nr > pos + 1)
      memmove(istate->cache + pos + 1,
              istate->cache + pos,
              (istate->cache_nr - pos - 1) * sizeof(ce)); // <=
  ....
}
```
There are two such fragments in the code, here are some of them:

- V568 It's odd that 'sizeof()' operator evaluates the size of a pointer to a class, but not the size of the 'ce' class object. index.c 1489
- V568 It's odd that 'sizeof()' operator evaluates the size of a pointer to a class, but not the size of the 'down' class object. cache-tree.c 103

**Comment by freeplant** [comment]
This issue is beyond our support range.
