### ISSUE TITLE
Correct way to sync to existing folder

### ISSUE THREAD

**Issue by droidzone** [haiwen/seafile#1886]
I have a folder /me/SeafileLocalSync containing the library 'My Library' in a folder 'My Library'.

If I do:
`seaf-cli sync -l "id" -d /me/SeafileLocalSync -s  "https://cloud.me.in" -u "me@me.su"`

It creates all the library folders under /me/SeafileLocalSync, ignoring that I have the files already under a folder /me/SeafileLocalSync/My Library

If I do:
`seaf-cli sync -l "id" -d /me/SeafileLocalSync/My\ Library -s  "https://cloud.me.in" -u "me@me.su"`

It creates another folder "My Library" under the existing folder named /me/SeafileLocalSync/My\ Library

So what is the correct way to sync?

**Comment by killing** [comment]
Please ask questions on the forum: https://forum.seafile.com
