### ISSUE TITLE
Customize links for upload.

### ISSUE THREAD

**Issue by kun-zhou** [haiwen/seafile#1887]
I want to use Seafile to upload files from other public computers I might be using when I travel. Hence, I do not want to log into my Seafile account on these computers for security reasons. All I want is an upload link. I understand Seafile support this functionality, but the link is way too long for human to memorize (these links really only work when you can copy-paste) Is it possible to provide some sort of customizations for the these links (such as length control or even complete url link customization)?

**Comment by shoeper** [comment]
This is more a question for the forum than an issue.

There currently is no such feature. You can manipulate the link in the database. Currently not 100% sure if the changed one also needs exactly 10 characters. It could be the case.
