### ISSUE TITLE
seafile 6.0.9: web interface only shows first 100 files in directory

### ISSUE THREAD

**Issue by flokli** [haiwen/seafile#1890]
It seems like something broke the automatic pagination in the seafile web interface.

I only see the first 100 files inside a share. Scrolling to the end doesn't load the next 100.

**Comment by sagarbehere** [comment]
I am on Seafile server 6.1.2 and am facing exactly the same problem. Can not scroll past the first 100 displayed files/folders.

Tried on Ubuntu Xenial 16.04 amd64 with both Firefox 55.0.2 (64-bit) as well as Google Chrome Version 60.0.3112.113 (Official Build) (64-bit). No output in the Console under Developer Options on these browsers.

The issue does not happen with the same browsers on my macbook air ?!

**Comment by flokli** [comment]
ping @freeplant

**Comment by shoeper** [comment]
I also have the same issue.

**Comment by aydindemircioglu** [comment]
same here. really cant believe such a bug.

**Comment by eriktews** [comment]
I can confirm that behaviour with Firefox 57 and Seafile 6.2.4.
