### ISSUE TITLE
download link for file with password

### ISSUE THREAD

**Issue by janstuemmel** [haiwen/seafile#1892]
seafile server verison: **5.1.1**

* if i create a link for a download file with a password, i get a link like follws:
`https://seafile.example.com/f/12345678/`, when i open the link, i have to enter the password

* if i open `https://seafile.example.com/f/12345678/?raw=1`, the download starts immediately without asking for a password

expected behavior: open the raw link -> ask for password -> download 

possible workaround: 
add password param: `https://seafile.example.com/f/12345678/?raw=1&pw=s3cret`

**Comment by shoeper** [comment]
Have you opened it in a new session? The password is being cached for some time.

**Comment by janstuemmel** [comment]
i opened that in two seperate incognito windows

**Comment by janstuemmel** [comment]
ok, the thing is...

* if i open the raw link in incognito, seafile asks for a password
* if i enter the password in another incognito window, the file displays as expected
* if i go to the first window and hit reload, seafile doesnt ask for a password

i dont understand this, because i thought separate incognito windows have separate sessions ...

... but no security issue atm
