### ISSUE TITLE
Unreadable text/messed up font

### ISSUE THREAD

**Issue by nichii124** [haiwen/seafile#1895]
I opened the seafile client just now and was greeted by a messed up font. I was going through the server setup and all the text is unreadable. The text also displays like this when I type something into it. I don't believe it's an issue on my side because I checked and this isn't happening to me on any other program. I've attached a screenshot of the messed up text. I'm using Linux by the way if that  helps.

![screenshot_2017-05-02_19-53-49](https://cloud.githubusercontent.com/assets/23606915/25644049/4e513c68-2f71-11e7-9f49-2a07e57d51d2.png)
![screenshot_2017-05-02_19-53-14](https://cloud.githubusercontent.com/assets/23606915/25644048/4e50b856-2f71-11e7-9016-02b7c675d2b2.png)

**Comment by shoeper** [comment]
Probably a missing font. Don't know which one though.

**Comment by nichii124** [comment]
Well I just installed all the microsoft fonts and it didn't fix anything. If it is a font issue then I don't know what font it could be either.

**Comment by lins05** [comment]
What is your linux distro? What qt version have you installed?

**Comment by nichii124** [comment]
@lins05 I have Manjaro Linux installed which is based off of Arch Linux. The qt version I'm using is 5.8.0. My seafile client was updated today and the problem still remains. I also tried deleting my seafile config folder and reinstalling seafile, but that didn't work either.

**Comment by nichii124** [comment]
This issue can be closed now because it isn't something wrong with Seafile. I found the same error happening on two other programs, so it's not an issue that only affects Seafile.
