### ISSUE TITLE
MySQL crashing

### ISSUE THREAD

**Issue by lordwardave** [haiwen/seafile#1897]
Hello ppl,

I have an issue with MySQL crashing on Seafile server.

In log **/opt/seafile/logs/seahub.log**
OperationalError: (2006, 'MySQL server has gone away')

In log **/opt/seafile/logs/ccnet.log**
[05/06/17 15:48:17] ../common/ccnet-db.c(630): Error get next result from prep stmt: mysql_stmt_fetch failed: Commands out of sync; you can't run this command now.

- It causes very randomly, i dont understand why is this happening.

There is no other services on server. Clean updated CentOS 7 + Seafile installed by Autoinstaller.

**Comment by lordwardave** [comment]
Autoinstaller script installs version 6.0.2, does anyone knows how to install latest version by this script?
Thank you for any help

**Comment by shoeper** [comment]
Ask your questions in the forum instead of the issue tracker, please.

https://forum.seafile.com/
