### ISSUE TITLE
Seafile works only with IE

### ISSUE THREAD

**Issue by mtrempoltsev** [haiwen/seafile#1899]
https://cloud.trempoltsev.ru/
user: seafile@test.com
pass: seafiletest

After login Seafile works only with Internet Explorer. With any other browser (Edge, Safari, Firefox, etc) I get the next js error:
SCRIPT5009: 'app' is undefined
main.1babd36004c3.js (221,331822)

**Comment by mtrempoltsev** [comment]
I waited for an any response during the week. But I can't wait any longer so I was uninstalled your product. Your account is no longer available. Sorry.

**Comment by shoeper** [comment]
Please close the issue.

**Comment by mtrempoltsev** [comment]
Are you joking? To fix the bug it is not enough to close issue.

**Comment by shoeper** [comment]
This is no bug.

**Comment by mtrempoltsev** [comment]
Then what is it?

**Comment by xiez** [comment]
Maybe something wrong during the installation.
Please try our demo site (https://demo.seafile.com/demo), works on all browsers.
