### ISSUE TITLE
IOS client does not use SITE_NAME

### ISSUE THREAD

**Issue by shpokas** [haiwen/seafile#1902]
Issue:
when a link is shared through Seafile IOS client, e-mail message is composed with hard-coded string 'Seafile' instead of what is set in SITE_NAME in seahub_settings.py.

IOS client version:
2.5.9
IOS version:
10.3.2

How to repeat:
1) set SITE_NAME to some value, different from 'Seafile' in  seahub_settings.py.
2) share a link via e-mail using Web GUI;
3) share a link via e-mail using IOS client;

Expected result:
SITE_NAME value is used in e-mail coming from IOS client, same as shared from WEB UI.

Observed result:

Subject:
File 'file' is shared with you using **Seafile**.

Body:
Hi,

Here is a link to 'file' in my **Seafile**:

Note 'Seafile' above.

**Comment by Miller101** [comment]
Interesting,

probably all related to:

https://forum.seafile.com/t/seafile-client-file-preview/2924
https://forum.seafile.com/t/issue-with-ios-10-3-2/2848
https://forum.seafile.com/t/dateien-offnen-unter-ios-seafilepro-funktioniert-nicht/2846
https://forum.seafile.com/t/ios-cache-problem-with-pdf-files/1852

**Comment by freeplant** [comment]
As it is a minor used feature, I'm afraid we will not fixed the issue (use SITE_NAME in iOS share).
