### ISSUE TITLE
icon link broken in 6.1.0

### ISSUE THREAD

**Issue by shpokas** [haiwen/seafile#1903]
Issue:
Link to icon is broken in v6.1.0

Setup:
Seafile v6.1.0 with Nginx and HTTPS, using MySQL on Centos 7.3.

How to reproduce:
1) Go to "My Libraries";
2) choose any library;
3) click on "Share links"

Expected result:
File icon displayed correctly

Obtained result:
Broken link in Web UI
Nginx error message:
2017/05/25 22:00:48 [error] 15158#15158: *4194 open() **"/opt/seafile/seafile-server-latest/seahub/media/img/file/file.png" failed
 (2: No such file or directory)**, client: a.b.c.d, server: sf.cfi.lu.lv, request: "GET /media/img/file/file.png HTTP/2.0", host: "ho.st", referrer: "https://ho.st/"
<img width="1040" alt="screen shot 2017-05-26 at 11 19 24" src="https://cloud.githubusercontent.com/assets/1006081/26482668/4c589468-4206-11e7-944a-7047e2ae3e4a.png">
<img width="402" alt="screen shot 2017-05-26 at 11 19 46" src="https://cloud.githubusercontent.com/assets/1006081/26482669/4ca8c23a-4206-11e7-8d89-a6531f43ea53.png">

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
