### ISSUE TITLE
Android client Version 2.1.12 crashes on opening a file

### ISSUE THREAD

**Issue by chkarg** [haiwen/seafile#1905]
Hello, I am using the seafile on a Google Pixel C tablet and a Google Pixel XL smartphone (Android 7.1.2). If I want to open a file in the Seafile app, the app crashes. Any ideas on that issue? Christoph

**Comment by 92lleo** [comment]
Please post your issue here: [](https://github.com/haiwen/seadroid).
Attach a log or detailed steps to reproduce (like action steps, filetype, ..) if possible.

**Comment by chkarg** [comment]
I found and installed the Seafile client 2.1.12a Beta and the problem is gone. :-)

**Comment by 92lleo** [comment]
could you provide the link to 2.1.12a beta?

**Comment by chkarg** [comment]
Sure! https://github.com/TMHBOFH/seadroid/releases/tag/2.1.12a
