### ISSUE TITLE
Error 0x8007045D when copying directories into Seadrive

### ISSUE THREAD

**Issue by Rojetto** [haiwen/seafile#1908]
Sorry if this is the wrong repository, I couldn't find one for the Seadrive client that wasn't specifically for the UI.

I'm mounting my Seafile libraries with Seadrive 0.6.2. For every directory that I copy into the mounted folders I get a Windows error 0x8007045D. When copying a nested directory structure I get the error for every subdirectory. Then clicking retry on every popup makes the copy work.

![seadrive_eafehler_anon](https://cloud.githubusercontent.com/assets/777285/26800302/1963171e-4a39-11e7-8c51-21e5d81dcb6e.png)

**Comment by killing** [comment]
Sorry but I can't read German directly. Can you translate the message?

**Comment by Rojetto** [comment]
Title: 1 interrupted action

You can't copy the directory because of an unexpected error. If this error occurs again, you can search for help using the error code.

Error 0x8007045D: The demand could not be executed (?) because of an I/O-device-error. (This sentence doesn't really make sense in German as well)

Retry             Skip           Cancel

**Comment by killing** [comment]
When this error happens, you  can check the seadrive.log for any error messages.

**Comment by Rojetto** [comment]
https://pastebin.com/SN81MijA

This is what the log looks like when I copy a Dropbox directory into Seadrive, which triggers the Windows error. I can't see any errors in the log.

**Comment by vryy** [comment]
This is really annoying, does anyone has solution to copy/move Dropbox folder to Seafile flawlessly?

**Comment by shoeper** [comment]
It should work using Seafile client. Just choose to synchronize an existing folder.

**Comment by monkeydri** [comment]
to me the problem was no space left on device (C:\)
