### ISSUE TITLE
"File in use" when trying to delete directory in Seadrive

### ISSUE THREAD

**Issue by Rojetto** [haiwen/seafile#1910]
Using Seadrive 0.6.2 on Windows 10.

I tried copying a directory into my mounted Seadrive, but had to cancel it because of #1908. When I then wanted to delete the partially copied directory, Windows popped up an error that it wasn't possible because the files were still "in use". At first I thought this had to do something with syncing, but deleting still wasn't possible after letting it finish. I then had to remove the directory via the web UI.

Edit: After further experimentation I realized that this only happens, when I copy a directory from Dropbox into SeaDrive. #1908 occurs, I click retry, the copy seemingly finishes properly, but then I can't delete the new directory.

**Comment by freeplant** [comment]
The latest version should fixed the problem.
