### ISSUE TITLE
Network Change Stalls Client (Server 6.0.4, Client 6.0.6)

### ISSUE THREAD

**Issue by Imburr** [haiwen/seafile#1913]
First off, this has been happening for a long time, several versions back. I run Seafile server as a guest on ESXi 6.5 at home. When I am home, client is connected and syncs. I go to work, client is connected and syncs. I connect from work VPN to home, client shows exclamation mark and the server is unavailable. I can still connect to website and upload/download, etc.

I then leave work and go home, and client remains with exclamation mark, it does not reconnect. I manually sync, I pause and re-eneble sync, nothing. If I exit Seafile client, then restart it, everything works and begins to sync all changes.

I can make a video of behavior, screenshot it, and offer logs is that is helpful. I have tried resinstallng client, etc. Client is on Windows 10.

**Comment by freeplant** [comment]
The latest version should fixed the problem.
