### ISSUE TITLE
Fails to start on Fedora 24 (undefined symbol)

### ISSUE THREAD

**Issue by tomchiverton** [haiwen/seafile#1914]
```
# sudo -u seafile /home/seafile/seafile-server-latest/seafile.sh start

** Message: seafile-controller.c(1091): loading seafdav config from /home/seafile/conf/seafdav.conf

License file /home/seafile/seafile-license.txt does not exist, allow at most 3 trial users
ccnet-server: symbol lookup error: /usr/lib64/libnssutil3.so: undefined symbol: PR_GetEnvSecure
failed to run "ccnet-server -t"
```

**Comment by tomchiverton** [comment]
This is seafile-pro-server-6.0.13.

**Comment by tomchiverton** [comment]
Workaround 

```
cd ...../seafile-pro-server-6.0.13/seafile/lib
mv libnspr4.so libnspr4.so.old
```

Seems seafile package their own libnspr but not their own libnssutil so the versions conflict with the system ones. These libraries are co-dependant so Seafile should ship both.

**Comment by zacharyrs** [comment]
I face this issue too on Arch Linux, all up to date. Solved using the above workaround as well.

It was working fine for a while but I suspect the system update introduced a compatibility error.

**Comment by paapereira** [comment]
Having the same issue on Arch Linux. 
Found it on versions seafile-pro-server_6.1.4 and seafile-pro-server_6.1.7. Probably a compatibility error as already said.

**Comment by freeplant** [comment]
This is not within our support range.

**Comment by zacharyrs** [comment]
Would you not be able to ship a version of libnssutil with seasile, thus meaning those running on arch with (likely newer) system builds don't need to apply the above fix?

**Comment by freeplant** [comment]
The issue reported in this thread is about seafile-pro-server-6.0.13, which is a pro edition. For pro edition, we build for Ubuntu 16.04 and CentOS 7.x. If you use other distribution, you can use the docker version.

Removing the bundled libraries will cause other issues.

**Comment by zacharyrs** [comment]
I understand that, and I'm very grateful that the pro is offered for free to those with three or less users. I personally run an arch server (love to tinker), but there's no reason for me to containerise if it runs locally.

I believe @tomchiverton suggested not removing anything, but bundling libnssutil, as it is the lack of this that causes the issue.

If that's not the case, I apologise.
