### ISSUE TITLE
Case Sensitivity: windows client dominates the server and linux client

### ISSUE THREAD

**Issue by KarlZeilhofer** [haiwen/seafile#1917]
We have set up a fresh seafile server V6.1.0 and we are 2 users now: one on windows 10 with and one on linux mint 18.1. 

after putting a existing folder structure into a seafile library, we decided to write all the folder names in lower case letters, since we saw some spurious file confilcts. 

First I tried to rename all the folders on my local machine (the linux side) to lower case. A few moments later, they were renamed back to their old name. 

2nd attempt: I renamed the folders on the server, which worked as long as the windows client wasn't online. As the windows client got online again, it renamed all the folders back to mixed case. 

How can we solve this problem?

Has the windows client any cache where it remembers files of a removed library? The windows client removed the library temporarily, until every folders were renamed to lower case, and synced them again - with no luck!

**Comment by arjones85** [comment]
Remove the account completely from the Windows client. Remove all files from the seafile folder. Fix up your casing how you want it, then reconfigure the client on the Windows system and resync.

**Comment by KarlZeilhofer** [comment]
Was this solved or just closed?

**Comment by freeplant** [comment]
This kind of usage case is very special. We don't have a better way to handle such case. So the issue is closed.

@arjones85 already provides a way to solve the problem. That is, remove the library from Seafile. Change files locally, then recreate library and resync.

**Comment by KarlZeilhofer** [comment]
@freeplant  
I don't understand, what is very special here. Windows and Linux clients for one library? The workaround may work for small libs, but with large and essential libraries for the daily work that doesn't seem doable. 

I don't think it should be closed. Then at least other users can find it as an open issue and apply the workaround.
