### ISSUE TITLE
Connected status ruined after hibernatation

### ISSUE THREAD

**Issue by samerafach** [haiwen/seafile#1918]
After hibernation, I keep seeing the status of Seafile client on the taskbar icon as "some servers not connected" with an exclamation mark. Just FYI I have only 1 server. When opening Seafile (by double-clicking on the icon), the connected icon (the paper clips icon on bottom-left) is red and says "no server connected". This happens while everything is connected and synchronization works fine. The only solution is to restart Seafile.

**Comment by lins05** [comment]
It's fixed in haiwen/seafile-client@3aeacdc2fecd125f7de14fae3c66ea892fc10ba9, and would be included in the next seafile client release.
