### ISSUE TITLE
restricted user account with elevation

### ISSUE THREAD

**Issue by darkdragon-001** [haiwen/seafile#1921]
In order to limit damage on a compromised device in combination with big libraries, I would like to see something similar to the way root access is handled by modern operating systems:
- default user has read-only access or even only access to meta data (file name, size, ...)
- when a user wants to _access_/_checkout_/_sync_ a folder/file, root password must be entered, permission is then granted to the user
- when the access is no longer needed (or after some sort of timeout), permission is revoked

I think most of it should already be supported by the backend so that only client modifications are needed:
- permission granting/revoking can use existing sharing functionality

My questions so far:
1. What do you think of this idea?
2. Is there any backend modification necessary?

**Comment by freeplant** [comment]
We don't have a plan to add such a feature.
