### ISSUE TITLE
icon/image typo broken after refresh on IE with SSL

### ISSUE THREAD

**Issue by lucasevabou14** [haiwen/seafile#1923]
Hi,

I lost image/icon typo when I refresh my IE browser when I use SSL. 
Problem only with IE. OK with chrome or Firefox. and OK in http only 
![lost logo](https://user-images.githubusercontent.com/16068326/27339908-5c8ae5c0-55d9-11e7-832b-83e588714de1.png)

Thanks for help.
server 6.0.9
IE: 11.0.96

**Comment by lucasevabou14** [comment]
Reproduced, with Seafile server 6.2.5
seems to be related to SSL exchange

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
