### ISSUE TITLE
Performance of big Files with small Changes 

### ISSUE THREAD

**Issue by Lordroran** [haiwen/seafile#1924]
The Performance of synchronizing Outlook Files is currently low. It seems like the client has to upload the whole file again when a change in the file has been made. I don't know if such an improvement is possible for binary files but I look forward to hearing about this issue.

**Comment by shoeper** [comment]
It depends on the file. Generally there already is delta uploading in the client, but if the file changes too much that isn't of help. Do you know how outlook files work?

**Comment by Lordroran** [comment]
No i don't sorry

**Comment by shoeper** [comment]
It is documented at https://msdn.microsoft.com/en-us/library/ff385210(v=office.12).aspx

But I won't further look into it as it doesn't affect me.

**Comment by freeplant** [comment]
This usage case is beyond our support range.
