### ISSUE TITLE
Seafile version 6.0.7 for macos doesn't work at all

### ISSUE THREAD

**Issue by kuyper** [haiwen/seafile#1925]
It says something about "broken package" after installation (see screenshot).
![bildschirmfoto 2017-06-26 um 08 26 29](https://user-images.githubusercontent.com/1135395/27526931-55c99cb2-5a49-11e7-84f9-40a173a5357f.png)

Is there a way of downloading an older version of seafile? I cannot sync anymore...

**Comment by kuyper** [comment]
Found version 6.0.4 to be working. For everyone having the same problem: here is the download link

https://bintray.com/seafile-org/seafile/seafile-client-mac/6.0.4#files

**Comment by freeplant** [comment]
I don't have this problem. Maybe the original file is okay, but the downloaded file is broken in the downloading process.

**Comment by shoeper** [comment]
@freeplant it has been happened in the past that bintry broke files. Maybe you could private sha256 checksums.
