### ISSUE TITLE
path is not exist did't return 404

### ISSUE THREAD

**Issue by zhanghw89** [haiwen/seafile#1926]
when i try to List Directory Entries use the api:
GET https://cloud.seafile.com/api2/repos/{repo-id}/dir/p=/abc/def/hgk
when the path hgk exist return http status code 200, when it change hgk to hgk-1  it return http status 403 and msg is："error_msg": "Forbid to access this folder."  ,but when i change def to def-1 (not exist) it return http status 500. however the official document says :

Errors
404 The path is not exist.
440 Repo is encrypted, and password is not provided.
520 Operation failed..
----------------
i think all of them should return :404 The path is not exist.
is it a bug?

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
