### ISSUE TITLE
Downloading install file: 403 Forbidden

### ISSUE THREAD

**Issue by edouard-lopez** [haiwen/seafile#1927]
Downloading seafile-server file from your [website page](https://www.seafile.com/en/download/) now return a Forbidden error message:

![selection_084](https://user-images.githubusercontent.com/1212392/27684311-d05d9712-5cc9-11e7-90b8-32fdbd82ce3f.png)

Same with `6.1.1`.

### Question

What's the matter ?

**Comment by freeplant** [comment]
The limit of free plan of bintray is reached. We have switched to another download address as a workaround.
