### ISSUE TITLE
setup-seafile-mysql.sh

### ISSUE THREAD

**Issue by mickey35us** [haiwen/seafile#1930]
Fresh install Ubuntu 16. Ran this script and got error but have no idea what caused the error. Unable to continue on with the configuration/installation of Seafile.

Here is the log:

---------------------------------
This is your configuration
---------------------------------

    server name:            xxxx
    server ip/domain:       192.168.1.6

    seafile data dir:       /home/userxxxx/seafile/seafile-data
    fileserver port:        81

    database:               use existing
    ccnet database:         ccnet-db
    seafile database:       seafile-db
    seahub database:        seahub-db
    database user:          seafile

---------------------------------
Press ENTER to continue, or Ctrl-C to abort
---------------------------------

Generating ccnet configuration ...

Traceback (most recent call last):
  File "setup-seafile-mysql.py", line 1471, in <module>
    main()
  File "setup-seafile-mysql.py", line 1424, in main
    ccnet_config.generate()
  File "setup-seafile-mysql.py", line 815, in generate
    if Utils.run_argv(argv, env=env_mgr.get_binary_env()) != 0:
  File "setup-seafile-mysql.py", line 85, in run_argv
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Both OS and Seafile are 64 bit. Any help is greatly appreciated.

**Comment by MBarrows20** [comment]
I'm also having this issue. Is there a solution yet?

**Comment by PeoceWang** [comment]
same issue too...

**Comment by steffenfritz** [comment]
Same issue, too. If I searched for this issue there were a lot of different causes for this error. It _might_ be a good idea to implement better error messages by handling errors...

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
