### ISSUE TITLE
Vertical images are displayed as horizontal in web interface

### ISSUE THREAD

**Issue by teklabania** [haiwen/seafile#1931]
When browsing photos in a web interface all horizontal images are displayed as vertical. Bottom and top of the image is cropped and black frame is added on both sides ([example](https://cloud.kantyka.net/f/458e00d34cb24acb8c18/)). Thumbnails are generated with no issue.

seafile server 6.1.1, centos 6

**Comment by freeplant** [comment]
Can you share me one of the image?

**Comment by teklabania** [comment]
I've put several photos here:
https://cloud.kantyka.net/d/7d189d838e0044c5b883/?p=/&mode=grid
I noticed that in some galleries vertical photos are displayed correctly.

**Comment by freeplant** [comment]
Fixed in https://github.com/haiwen/seahub/pull/1700
