### ISSUE TITLE
Space used showed differently in web UI

### ISSUE THREAD

**Issue by zeeqy** [haiwen/seafile#1935]
Did anyone encounter the issue like this?

In the web UI, the upper right corner shows "Used 48GB", but the two libraries I have, one shows the size 44GB, and another shows 20MB.

The total does not match, any idea about this?

**Comment by freeplant** [comment]
In the library, the space is calculated by 1MB = 1024KB = 1024 * 1024B. In the right corner, the space is calculated by 1MB = 1000KB = 1000 * 1000B

**Comment by zeeqy** [comment]
Now I know it's something wrong in the file system, thanks.
