### ISSUE TITLE
General Seafile Log issues

### ISSUE THREAD

**Issue by RM4G00** [haiwen/seafile#1939]
Seafile pro edition - centos 7 x64 - 6.0.4

Logs have simply stopped writing to the seafile db -

Can anyone advise the credentials and connection settings are fine - issue seems to have stemmed from a system wide update.

Thanks

**Comment by killing** [comment]
Hi,

Please ask deployment questions on forum: https://forum.seafile.com. There are more active community users there. Github is used for bug tracking or feature requests.

Thanks.
