### ISSUE TITLE
Show and hide deleted files/folders instead of one big trash

### ISSUE THREAD

**Issue by kpstolk** [haiwen/seafile#194]
A possibility to show and hide deleted files/folders in the current folder you're viewing (ala Dropbox) instead of one big trash folder.

It would also be nice to restore complete folders or parts of it. (with checkboxes for example)

**Comment by shoeper** [comment]
>A possibility to show and hide deleted files/folders in the current folder you're viewing (ala Dropbox) instead of one big trash folder.

is possible for some time now.

>It would also be nice to restore complete folders

this has also been implemented
