### ISSUE TITLE
Internal Server Error When Uploading favicon.ico

### ISSUE THREAD

**Issue by whao** [haiwen/seafile#1940]
I get an error when changing the favicon.ico
![screen shot 2017-08-08 at 1 31 51 am](https://user-images.githubusercontent.com/3475813/29038238-97d73dd8-7bd9-11e7-943a-2c79cf8a1121.png)
But changing logo is fine.

**Comment by killing** [comment]
Can you check logs/seahub.log and logs/seahub_django_requests.log?

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
