### ISSUE TITLE
Deleted folder restores with no contents when you create a new folder with the same name

### ISSUE THREAD

**Issue by rabb1t** [haiwen/seafile#1941]
Hi,

### Problem:
Lose the ability to restore contents of a removed folder

### Environment:
* Operating system:
`CentOS Linux release 7.1.1503 (Core) / 3.10.0-514.21.2.el7.x86_64`

* Seafile release:
`version:    6.1.4 pro edition`

### Description:

Removed folder restores in the library with no content if you create a new folder of exactly the same name as removed

### Steps to reproduce:

1. Create a folder inside any library

2. Upload any content to that folder

3. Remove the folder

4. Ensure that you have a possibility to restore it from the trash can

5. Create a new folder of exactly the same name as removed one

6. Ensure that you can't restore removed folder any more (because it disappeared from the trash can)

### Results:
* Actual: Contents of a removed folder are lost
* Expected: You can restore removed folders with it's contents from the trash either way.

**Comment by freeplant** [comment]
This is a designed behaviour. It is a limitation from how trash is implemented in Seafile. To restore old version of the folder, you can go to snapshots list, find a snapshot containing the folder, restore old folder from that snapshot.
