### ISSUE TITLE
Disable saving of device name and last login IP into database

### ISSUE THREAD

**Issue by ge-fa** [haiwen/seafile#1942]
As per the subject: Both information might be sensitive. If these are needed for debugging, enable automatic clean up after a specified time and / or only save these if debugging is enabled.

**Comment by killing** [comment]
The information is saved for the users to know where the access to their accounts happened. This is useful for detecting abnormal access to accounts.

**Comment by shoeper** [comment]
Currently cleanup is only possible by executing SQL queries to remove the data (or maybe replace it with default values).

**Comment by freeplant** [comment]
You can clean the database regularly. If you still have clean user data related issue, just open another issue.
