### ISSUE TITLE
Cannot upload/access files correctly.

### ISSUE THREAD

**Issue by lug-gh** [haiwen/seafile#1943]
Hi,
i just installed seafile and got some problems.

First of all my setup:
seafile is installed on a vm (ubuntu 16.04) with NAT internet access. (ip 192.168.123.1)
to access the seahub i use nginx reverse proxy like this:

```
server {
        listen 443;
        ssl on;
        ssl_certificate         /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key     /etc/nginx/ssl/privkey.pem;

        server_name             mydomain.example.org;

        location / {
                proxy_pass http://192.168.123.1:8000;
        }
}
```
and to access the seafile server i created a nat rule to forward incoming port 8082 tcp on the external ip to the port 8082 on 192.168.123.1

So when i directly access the seahub by entering http://192.168.123.1:8000/ i can use everything just perfect.

Entering the page by https://mydomain.example.org/ i can download files (port forwarding of 8082 works) but not upload files. I get unknown error on the seahub.

The Android app works perfectly, i can download and upload.
Windows Drive Client login does work, but it only shows a folder "my library" without contents, file upload not possible.
error log: ```[08/15/17 11:11:09] http-tx-mgr.c(1214): Bad response code for GET https://mydomain.example.org/seafhttp/protocol-version: 404.```
gui error log: 
```
[08/15/17 11:12:42] Unable to get config value download_limit: Config not exists
[08/15/17 11:12:42] Unable to get config value upload_limit: Config not exists
```

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com
