### ISSUE TITLE
Latest Stable Seafile doesn't start under Debian Stretch

### ISSUE THREAD

**Issue by jmbromley** [haiwen/seafile#1944]
Current stable seafile server won't start under Debian Stretch, but it starts fine under Debian 8 (Jessie).

## Minimal Steps To Reproduce

Easiest way to reproduce is to use docker as then you can quickly compare two versions of Debian.

If I run:

```
docker run -t -i debian:latest /bin/bash
apt-get update; apt-get install -y wget python2.7 libpython2.7 python-setuptools python-imaging python-ldap python-urllib3 sqlite3
wget https://download.seadrive.org/seafile-server_6.1.2_x86-64.tar.gz
tar -zxvf seafile-server_6.1.2_x86-64.tar.gz
seafile-server-6.1.2/setup-seafile.sh auto -n testing -i testing.com
seafile-server-latest/seafile.sh start
```

Then I get:

> [08/20/17 08:19:31] ../common/session.c(132): using config file /conf/ccnet.conf
> Starting seafile server, please wait ...
> Failed to start seafile server

Although repeated cycling of stop/start can sometimes (unreliably) get success.

However if I replace `debian:latest` with `debian:8` the seafile server starts fine.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
