### ISSUE TITLE
Memcached error handling / ha not working

### ISSUE THREAD

**Issue by egroeper** [haiwen/seafile#1946]
If the memcached server ever gets rebooted or has a small network outage, the clients (Seafile server components) stop using it. This currently means, that major functionality isn't working.
You even can't download a file using the webinterface or access encrypted libaries.

Therefore we now tried to use a cluster setup like [mentioned in the docs](https://manual.seafile.com/deploy_pro/memcached_mariadb_cluster.html). But this doesn't seem to work.

Bringing one of the cluster nodes down results in the following, when trying to access an encrypted library (or similar, when trying todownload a file):
```
[08/22/2017 08:37:02 AM] ../common/obj-cache.c(106): Failed to set c4fcfdf9-b942-4c7d-8884-7f0c9767b484-173a620dca33b7096ffe36e7b0e69fb0aa6d82a0 to memcached: SERVER IS MARKED DEAD.
[...]
[08/22/2017 08:37:21 AM] ../common/obj-cache.c(106): Failed to set Passwordaa1ea5a39f40eb9bfa5ab7e1c35d0fbcf29c9b03 to memcached: SERVER IS MARKED DEAD.
[08/22/2017 08:37:21 AM] passwd-mgr.c(215): Failed to set decrypt key for c4fcfdf9-b942-4c7d-8884-7f0c9767b484.h37762hf@hu-berlin.de.
```

This even happens, when providing these settings in seafile.conf:
`--POOL-MIN=10 --POOL-MAX=100 --DISTRIBUTION=consistent --HASH=MD5 --REMOVE_FAILED_SERVERS=1`

To my knowledge these settings should result in a similar behaviour to the one [configured for seahub](https://manual.seafile.com/deploy/add_memcached.html):
```
        'OPTIONS': {
            'ketama': True,
            'remove_failed': 1,
            'retry_timeout': 3600,
            'dead_timeout': 3600
        }
```

Ketama hashing together with remove_failed should result in moving the key to the fallback server immediatly on failure. `retry_timeout`should get ignored, because we mark the server dead after the first failure / timeout.

Which Memcached settings are used for seaf-server? I'm especially interested in the value of server_failure_limit. The default should be 5, but without any custom settings from our side it seems like the server fails immediately instead of doing 5 iterations of waiting for 2 seconds (default retry timeout). `--REMOVE_FAILED_SERVERS=1` should set server_failure_limit to 1.

I'm currently not sure, if our settings provided in seafile.conf ever reach libmemcached. But at least seafile doesn't start, if we provide invalid settings. We weren't able to get the expected behaviour...

Any ideas? Since nowadays memcached is quite important for Seafile to work, I would really like to get HA working here.
Instead of using ketama hashing, we thought about using the replication feature of libmemcached. This would avoid possible inconsistency problems (stale values) with dead_timeout > 0.

**Comment by egroeper** [comment]
It seems like the problem is in libmemcached. Key redistribution on failure doesn't work with dead_timeout of 0.

I have written a [small test script](https://gist.github.com/egroeper/fd998c8089ffd2ba863c75f503418dcb). There I try to get ketama hashing with key redistribution on failure to work. It serves as a minimal example.
Just to be sure (problem could be in using parameters from config string), I use the specific behaviour settings as well.

With dead_timeout 0 the result is:
```
get success
get success
get success
set error: 3, CONNECTION FAILURE
get error: 35, SERVER IS MARKED DEAD
get success
get success
set error: 35, SERVER IS MARKED DEAD
get error: 35, SERVER IS MARKED DEAD
set error: 35, SERVER IS MARKED DEAD
get error: 35, SERVER IS MARKED DEAD
set error: 35, SERVER IS MARKED DEAD
get error: 35, SERVER IS MARKED DEAD
set error: 35, SERVER IS MARKED DEAD
```

It goes to the backup server for 2 iterations and then goes back to the dead server and stays there.

With dead_timeout 5 it works as expected:
```
get success
get success
get success
set error: 3, CONNECTION FAILURE
get error: 35, SERVER IS MARKED DEAD
get success
get success
get success
get success
get success
set error: 47, SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY
get error: 35, SERVER IS MARKED DEAD
get success
```

The dead server is retried every 5 seconds.


I have tested this with libmemcached.so.11 from Ubuntu 16.04 and the one bundled with Seafile pro 6.1.4 with same results.

**Comment by killing** [comment]
Hi @egroeper 

Sorry for the late reply.

The configuration used in seaf-server and seahub are actually the same. In the C code,

```
    memcached_pool_behavior_set (cache->mc_pool, MEMCACHED_BEHAVIOR_KETAMA, 1);
    memcached_pool_behavior_set (cache->mc_pool, MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS, 1);
```

And then we allow the user to set appropriate retry_timeout for the dead node. In the cluster documentation:

```
[cluster]
enabled = true
memcached_options = --SERVER=192.168.1.134 --SERVER=192.168.1.135 --SERVER=192.168.1.136 --POOL-MIN=10 --POOL-MAX=100 --RETRY-TIMEOUT=3600
```

So the end result would be the same as your testing example. But we suggest to set larger value for retry_timeout. If seafile tries too frequently on the dead node, it would result in more user visible errors.

The above settings should work for the scenario that a memcache server is down for relatively long time.

**Comment by egroeper** [comment]
Sorry. I have to respectfully disagree. I'm pretty sure, that retry_timeout is not used when we talk about DEAD nodes. It is only used for nodes in the temporary_timeout state (the state before the dead state).
We really need dead_timeout here. I don't have my notes here, but I think REMOVE_FAILED_SERVERS with a value of 1 means, that the server is marked dead after the first problem. So retry_timeout should be of no use here.

We first tested with retry_timeout, but had no success. Please reinvestigate the issue.

**Comment by killing** [comment]
This should be consider resolved since we've changed the recommended memcached architecture to use a single memcached server with keepalived for HA.
