### ISSUE TITLE
Seafile as Backup Server (unidirectonal sync)

### ISSUE THREAD

**Issue by cdn123** [haiwen/seafile#1953]
Hi, 

we are using Seafile on some clients for just doing backups of local files. Right now there is a bidirectonal sync. We would like to just upload the files from clients to server and not the other way round. 

Reason: If the seafile server got hijacked or there is any bug in the system, there is a possibilty that the local files on the client get removed. With just one copy of local files the files are lost. 

Is there a feature(request) or a workaround for this scenario?

Thanks in advance
cdn123

**Comment by freeplant** [comment]
We don't have a plan to support such usage case.
