### ISSUE TITLE
Eager thumbnail generation

### ISSUE THREAD

**Issue by skuzzle** [haiwen/seafile#1954]
Hi,

it would be great if seafile would provide an option for eager thumbnail generation (maybe in as a low priority background task or while importing new images). When browsing libraries with many (big) images, thumbnail generation takes pretty long right now (I must admit though that I'm running seafile on a rather slow V-Server). It would greatly improve user experience if thumbnails would not need to be generated on the fly.

**Comment by freeplant** [comment]
We don't have a plan to implement such feature.
