### ISSUE TITLE
Add Caddy as a server too besides Apache Httpd and Nginx

### ISSUE THREAD

**Issue by aadrian** [haiwen/seafile#1956]
Please add Caddy https://caddyserver.com/ too as a server besides Apache and Nginx.

Especially for Home/Personal use, Caddy is fantastic and much more simple to manage than Apache and Nginx. It's also handling automatically HTTPS with Let's Encrypt certificates. 

Thank you.

**Comment by shoeper** [comment]
Feel free to submit a PR on how to configure caddy to be used with Seafile.
