### ISSUE TITLE
Admin can not disable 2FA for user on password reset

### ISSUE THREAD

**Issue by 92lleo** [haiwen/seafile#1957]
Community Edition 6.2.0 beta:
First; Thanks for porting 2FA into community edition!
I wondered how the two factor auth behaves when the password is reset by the admin and tested it: Currently it just resets the users password but leaves 2FA intact. From my opinion it would be good to 
1.  disable 2fa when password is reset or 
2. Give the admin the choice to reset 2fa. It's more likely that a user somehow messes up 2fa (eg. phone reset and no backup codes) than forgets his password

**Comment by 92lleo** [comment]
Update: i just noticed that 2FA can be disabled in user detail view.
Please bring password reset and 2FA setting together somewhere

**Comment by freeplant** [comment]
The feature has been implemented.
