### ISSUE TITLE
OSX: Client does not recognise file changes in symlinked directories

### ISSUE THREAD

**Issue by fazakis** [haiwen/seafile#1959]
When changes occur in symbolic linked folders into a seafile shared folder e.g. Shared folder: Shared1, shortcut folder: Link1 full path: Shared1/Link1. When changes occur into Link1 seafile does not sync them, if you quit and open again seafile then it syncs them. Can this be fixed? OS: OSX

**Comment by freeplant** [comment]
This is not within our range of support.
