### ISSUE TITLE
Error when downloading a file from the web control panel

### ISSUE THREAD

**Issue by paulocoghi** [haiwen/seafile#1960]
**Install and OS details**
Seafile Server version: 6.1.2 64bit
OS: Ubuntu 16.04 64bit
Install method: [haiwen/seafile-server-installer](https://github.com/haiwen/seafile-server-installer) and `bash seafile_centos 6.1.2`

**Problem**
Everything is working flawlessly, except the downloads from the web control panel.

**How the problem happens**
When I try to download a file, the link after the redirect becomes invalid, as in this hypothetical example below:

https://my-domain.com%20my-domain.com/seafhttp/files/79f2adb3-bb24-42bd-992d-16f1abda4e55/my-file.pdf

**The current workaround**
There is an additional `%20my-domain.com`. Removing this redundant domain and this "coded space" `%20`, the link works perfectly.

---

**Nginx config file**
https://hastebin.com/ipatajopeb.nginx

**Comment by shoeper** [comment]
Wrong configuration. Please use the forum to ask questions.
