### ISSUE TITLE
Webinterface displayed wrong since latest release (Com. 6.1.2)

### ISSUE THREAD

**Issue by Jasper-Ben** [haiwen/seafile#1961]
Right side of the interface is blocked by a white bar. Is this a known error?

![screenshot from 2017-09-22 01-12-13](https://user-images.githubusercontent.com/12223583/30722784-5657fba4-9f33-11e7-9908-37bf61c48292.png)

**Comment by shoeper** [comment]
Likely due to customized design. Please use the forum to ask questions.

**Comment by Jasper-Ben** [comment]
Thanks for your reply. Just did a test installation and the problem doesn't occur. So yes, probably the custom css.

**Comment by Jasper-Ben** [comment]
For anyone experiencing the same issue with custom css. here is the solution:
https://forum.seafile.com/t/seafile-server-6-1-2-sidebar-issue/3802/7
