### ISSUE TITLE
memory leak when syncing lots of data?

### ISSUE THREAD

**Issue by paolostivanin** [haiwen/seafile#1962]
Using Synchronize Ultimate (and thus the web api), I sync my WhatsApp folder (~1.8 GB). The memory used by the seafile process went up to 800 MB and I had to restart it in order to free the memory.
Is this expected (like, for example, Seafile does memory cleanup once day) or is it a memory leak?

**Comment by freeplant** [comment]
The memory usage depends on the number of files. There is an in memory index for every file.
