### ISSUE TITLE
File name with 128 non ASCII chars is not uploaded

### ISSUE THREAD

**Issue by galvanopus** [haiwen/seafile#1966]
Server 6.0.7 Windows

Steps to reproduce:
1. Create Test library.
2. Upload any file.
3, Try to rename it to "яяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяя"

The same file cannot be uploaded via client,

seafile.log contains the following entry:
```[10/01/17 11:14:32] repo-op.c(2758): [rename file] Invalid filename яяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяя.```

I suggest 255 bytes are allocated for file name. If using UTF-8 128 chars require 256 bytes.

**Comment by killing** [comment]
Yes the seafile server cannot accept file names longer than 256 bytes. That's why it's not uploaded.

**Comment by shoeper** [comment]
It could also be the same as with special characters, upload it and only downloading as long as the filename length is supported on the os.

**Comment by galvanopus** [comment]
@killing I understand, but it would be much better if Seafile would upload a file is OS supports its name. Exactly like it deals now with names containing colon. It is not accepted in Windows, but Seafile allows uploading such files.
