### ISSUE TITLE
OSX: Seafile forces use of discrete GPU

### ISSUE THREAD

**Issue by ehoppmann** [haiwen/seafile#1967]
Seafile forces the use of the discrete GPU on MacBook Pro models which have a discrete GPU, reducing the battery life of any of these laptops while running Seafile. 

A simple solution is to add this key to the Info.plist file in the OSX distribution: https://developer.apple.com/library/content/qa/qa1734/_index.html

Before the change:
<img width="458" alt="before" src="https://user-images.githubusercontent.com/1176078/31081452-f970b032-a759-11e7-920c-039ba908cf74.png">

After editing Info.plist:
<img width="458" alt="after" src="https://user-images.githubusercontent.com/1176078/31081457-fbd648a0-a759-11e7-829a-597c1d0fef12.png">

**Comment by shoeper** [comment]
Duplicate

**Comment by killing** [comment]
Duplicated with https://github.com/haiwen/seafile-client/issues/984
