### ISSUE TITLE
Crosspost: Update Underlying OS?

### ISSUE THREAD

**Issue by Imburr** [haiwen/seafile#1968]
**Sorry for duplicate, my first post is not in the right spot I assume.**

[https://github.com/haiwen/seafile-server/issues/78](https://github.com/haiwen/seafile-server/issues/78)

I am running Seafile 6.1.1 ons Ubuntu 14.04 LTS.

Can I safely upgrade "do-release-upgrade" without destroying Seafile?

If not, what is my best bet? I could actually drum up a second VM and install a new OS and migrate over if that will be better, just dont want to lose my shares and access.

**Comment by shoeper** [comment]
I guess you can.

But the proper place to ask would be forum.seafile.com

**Comment by killing** [comment]
I personally have no experience of directly upgrading Ubuntu. It's better to ask on the forum.
