### ISSUE TITLE
X-CSRFToken: null

### ISSUE THREAD

**Issue by Gronkdalonka** [haiwen/seafile#1969]
On seafile server 6.2.0 and 6.2.2 (ce) while using wsgi and an apache2 proxy (https) the X-CSRFToken is null, but the valid crsftoken is in the cookie. 
This results in a 403 forbidden with the message "CSRF Failed: CSRF token missing or incorrect." when you try to access an encrypted library or try to delete a share link.

Does not occur when using fastcgi.

If sent with the token from the cookie as  X-CSRFToken the request succeeds.

**Comment by Gronkdalonka** [comment]
Issue can be closed, it was a apache2 misconfiguration.
"Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure" was set which caused my trouble.

**Comment by shoeper** [comment]
Secure is ok but HttpOnly obviously disallows access for JavaScript.

**Comment by omkarnathsingh** [comment]
Thanks, this issue solved my lots of time.
