### ISSUE TITLE
邮件发送失败，提示user_reset ‘ascii’ codec can’t decode byte 0xe5 in position 0: ordinal not in range(128) 

### ISSUE THREAD

**Issue by ywooer** [haiwen/seafile#1970]
按照教程在 seahub_settings.py 中配置邮件服务器后，发送邮件会打印如下错误日志：
[ERROR] seahub.views.sysadmin:1048 user_reset ‘ascii’ codec can’t decode byte 0xe5 in position 0: ordinal not in range(128)

**Comment by Nine-Tailed** [comment]
After I setup the mail server and add the user to setup the following error message appears in the log file (Seafile 6.2.5).  
seahub.view.sysadmin:1150 user_add 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

**Comment by Nine-Tailed** [comment]
The reason for the error is Russian letters in the key SITE_NAME in seahub_settings.py
