### ISSUE TITLE
High CPU usage on every refresh if seafile-server app directory is read only

### ISSUE THREAD

**Issue by galvanopus** [haiwen/seafile#1971]
Seafile server 6.0.7 for Windows running under limited account.

If ```seafile-server-6.0.7\seahub\media\CACHE``` is read only, server uses 100% CPU for a few seconds on every refresh. I suggest it generates CSS every time and then fails to put it in CACHE folder.

Why the default setup requires some folder in app dir to be writable? What other folders should be writable? I have found the following ones:
```
seafile-server-6.0.7\seahub\media\avatars
seafile-server-6.0.7\seahub\media\CACHE
seafile-server-6.0.7\seahub\seahub\thumbnail\thumb
```

Is it possible to redirect them outside the app folder?

**Comment by galvanopus** [comment]
@killing Has this been fixed or you are closing old issues to check whether they are obsolete?

**Comment by killing** [comment]
I'd say this is not a bug in the system. It looks more like a usage question, which belongs to the forum.

**Comment by galvanopus** [comment]
@killing I think this can be considered as a bug. Software should not require write rights to the program directory or at least that rights should be specified explicitly in the documentation.
