### ISSUE TITLE
Creating admin user non-interactivity?

### ISSUE THREAD

**Issue by soakes** [haiwen/seafile#1974]
I am trying to create a Docker container to setup seafile pro as there isn't really currently a good one available and have run into a small problem.

The issue I am having is, I can't seem to create the admin user (email address and password) by setting some environment vars or by some flags.  The actual install is perfect using non-interactive config at the bottom of this page https://manual.seafile.com/deploy/using_mysql.html but nowhere tells you how to create the admin user which is created when you first run the seahub.sh scrpt.

I have searched high and low for the answer but have come up blank and so I thought I would ask directly here.  I hope that's ok.

Are there an ENV or options somewhere that I have missed? or is there a workaround on creating this without prompting the user for it?

**Comment by shoeper** [comment]
You could have a look at https://github.com/haiwen/seafile-server-installer/blob/master/seafile_debian

It has been somehow implemented there.

**Comment by soakes** [comment]
Thanks this is a big help.
