### ISSUE TITLE
Cannot install on Ubuntu 17.10

### ISSUE THREAD

**Issue by dakira** [haiwen/seafile#1976]
There are packages for 17.10 in the PPA, but they depend on a libevent version that is not available in Ubuntu 17.10.

It should be enough to update the dependency in the package.

**Comment by davidfialho14** [comment]
Be sure to update the seadrive package as well, since this issue also affects that package.

**Comment by sinxwal** [comment]
+1

**Comment by fuelflo** [comment]
I have seafile still installed because I upgraded to 17.10, but it's not working. Not syncing properly... =/

**Comment by sinxwal** [comment]
For now, there is a hack for making it work. See https://github.com/haiwen/seafile/issues/1955#issuecomment-333798732

**Comment by dakira** [comment]
@killing any update on compilation on artful?

**Comment by digital-spinner** [comment]
@sinxwal Thanks for this! It is working as for now.

**Comment by theliquid** [comment]
+1

**Comment by killing** [comment]
We're working on this issue and will update when it's ready.

**Comment by rumplstielz** [comment]
+1

**Comment by aacebedo** [comment]
+1

**Comment by vbeffara** [comment]
+1

**Comment by digital-spinner** [comment]
@killing Hey! Is there an ETA for the patch / new package? Just curious - I have to wait for it anyway cause I'm not going back to older distros..

**Comment by lins05** [comment]
It has been fixed and the PPA has been updated. You can now install seafile client on ubuntu 17.10 by:

```sh
sudo apt-get update -q
sudo apt-get install -y seafile-gui
```

**Comment by davidfialho14** [comment]
The issue occurs with the seadrive client. When installing `seadrive-gui`, apt complains about a missing dependency that is not going to be installed. That dependency is `seadrive-daemon`. When trying to install `seadrive-daemon` apt complains about the same thing:
           
    The following packages have unmet dependencies:
    seadrive-daemon : Depends: libevent-2.0-5 (>= 2.0.10-stable) but it is not installable

Can you fix this please?

**Comment by lins05** [comment]
We've updated the seadrive packages for ubuntu 17.10. You can try again:

```sh
echo deb http://deb.seadrive.org artful main | sudo tee /etc/apt/sources.list.d/seafile.list
sudo apt-get update -q
sudo apt-get install seadrive-gui
```

**Comment by davidfialho14** [comment]
Tried it and it is working perfectly.
Good job. Thank you.

**Comment by wsw70** [comment]
@lins05 : This also works for 18.04 bionic, thanks.

It may be worthwhile to update the documentation
