### ISSUE TITLE
Markdown : Include image in folder or relative to folder

### ISSUE THREAD

**Issue by LeDistordu** [haiwen/seafile#1981]
Hi,

for now I can only add an image from an url but I need this :

Example 1 : 

Library01/collection01/image.jpg
Library01/collection01/test.md

How to include image in my markdown document ?

Example 2 : 

Library01/collection01/image.jpg
Library01/test.md

How to include image in my markdown document ?

**Comment by hofingermarkus** [comment]
Looks as if Seafile doesn't support relative Filepaths for images in markdown (yet)
Please fix!

**Comment by mircsicz** [comment]
Just tried it with:

`![TEXT](img.png "ALT")`

with the markdown file in the same folder as the img...

**Comment by fgrsnau** [comment]
The only way around is to "share" the images to get a static URL and to add the `?raw=1` parameter. This is pretty complicated.

**Comment by freeplant** [comment]
It will be solved in version 7.0.

**Comment by julozi** [comment]
This is still not solved. Relative path for image are not supported.

**Comment by xjtu-blacksmith** [comment]
Right now it is not supported ... MUCH needed 😞
