### ISSUE TITLE
mobile  browser  download error

### ISSUE THREAD

**Issue by zouzongning** [haiwen/seafile#1987]
open link and download file,seafile will tell you “ERROR_MESSAGE_MAIN  ERROR_MESSAGE_REASON”,

My own server and demo server has this problem。

**Comment by zouzongning** [comment]
pc browser is normal，only mobile browser。

**Comment by shoeper** [comment]
Can you have look  at the access log of your server while downloading the file with your mobile browser? Some browsers to a head request first and request the file in a second request. As I recall this does not work as the access token is being expired on the first call.
