### ISSUE TITLE
Pulseaudio not working when seafile is running

### ISSUE THREAD

**Issue by openpaul** [haiwen/seafile#1989]
Seafile uses to many inotify sessions. Same issue as here: https://github.com/haiwen/seafile/issues/1640
Pleae consider re opening the first bug repot! 
```
Nov 25 18:26:22 kahlua pulseaudio[8065]: [pulseaudio] module-systemd-login.c: Failed to create session monitor: No space left on device
Nov 25 18:26:22 kahlua pulseaudio[8065]: [pulseaudio] module.c: Failed to load module "module-systemd-login" (argument: ""): initialization failed.
Nov 25 18:26:22 kahlua pulseaudio[8065]: [pulseaudio] main.c: Module load failed.
Nov 25 18:26:22 kahlua pulseaudio[8065]: [pulseaudio] main.c: Failed to initialize daemon.
Nov 25 18:26:22 kahlua pulseaudio[8062]: [pulseaudio] main.c: Daemon startup f
```

When terminating seafile-cliet I can start pulseaudion without problems.

I use version `seafile-gui  (6.1.1-1).` on debian sid.

**Comment by shoeper** [comment]
To solve this you can do two things

1. sync less libraries - as you likely don't want to do that see 2
2. increase the inotify limit. See https://unix.stackexchange.com/a/13757
