### ISSUE TITLE
seahub.log empty

### ISSUE THREAD

**Issue by timppa-tenfour** [haiwen/seafile#1993]
I had a Pro server 6.1.8 running on Ubuntu 16.04 LTS. When setting up fail2ban for it i noticed that seahub.log has nothing in it and looks like its been like that for over a month now. I couln't find any info where to set log locations or log levels or any other info about similar behaviour. The file exists and is writeable by the server. Restarting the server didn't help either, nor did the upgrading to 6.1.9.

**Comment by shoeper** [comment]
It is no problem. It only has content in case some error occurred.

**Comment by timppa-tenfour** [comment]
I think there was some problem before... I tried to trigger bad logins, and they worked in a way that the user got unactivated by seafile, but still nothing in the log. However after upgrading to Ubuntu server 17.10, the log started working, so i guess there was some issue that got self-solved.
