### ISSUE TITLE
编辑报错subscripted value is not an array

### ISSUE THREAD

**Issue by tianzhiqing** [haiwen/seafile#1994]
repo.c:879:11: error: subscripted value is not an array, pointer, or vector
        self->_id[36] = '\0';

![image](https://user-images.githubusercontent.com/2231669/33535304-69458cb8-d872-11e7-9240-6a7138f61e57.png)

**Comment by freeplant** [comment]
能把你具体的编译过程说一下吗？

**Comment by tianzhiqing** [comment]
你好，我编译的过程是这样的

 参照https://manual.seafile.com/build_seafile/osx.html 这个文档，前面都没有问题，然后到seafile的时候到make这一步的时候报错：

![Uploading 下载.png…]()
