### ISSUE TITLE
Seadrive does not move or copy files instantly between libraries

### ISSUE THREAD

**Issue by 4ley** [haiwen/seafile#2000]
If moving or copying files between libraries in Seadrive, the `mv` command returns success immediately even though it takes sometimes seconds for the files to appear in the other directory.

Check out this example:

`touch seadrive/lib1/file.txt ; mv seadrive/lib1/file.txt seadrive/lib2/ ; ls -la seadrive/lib2/`

This results in an empty directoy. Doing this without Seadrive, but on an normal volume, it works just fine.

I use Seadrive 0.8 headless on Ubuntu 16.

**Comment by freeplant** [comment]
Can you report the problem to https://github.com/haiwen/seadrive-gui/issues

**Comment by 4ley** [comment]
Sure, its moved [Seadrive Issue #48](https://github.com/haiwen/seadrive-gui/issues/48)
