### ISSUE TITLE
Nginx proxy buffer

### ISSUE THREAD

**Issue by dofl** [haiwen/seafile#2001]
Please add the following to the Nginx [manual](https://manual.seafile.com/deploy/deploy_with_nginx.html):

`proxy_buffering off;`

As this disables the nginx server caching the files on disk before sending them to the user. 
For example, The seafile server server reads a block, pushes it to nginx. nginx saves the file on the disk as it exceeds his proxy buffer. The result is then read and send to the user. With the proxy_buffering off, this writing to disk is prevented. My server has an IO limit, which means that I can now send twice as fast.

> http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering
> 
> Enables or disables buffering of responses from the proxied server.
> 
> When buffering is enabled, nginx receives a response from the proxied server as soon as possible, saving it into the buffers set by the proxy_buffer_size and proxy_buffers directives. If the whole response does not fit into memory, a part of it can be saved to a temporary file on the disk. Writing to temporary files is controlled by the proxy_max_temp_file_size and proxy_temp_file_write_size directives.
> 
> When buffering is disabled, the response is passed to a client synchronously, immediately as it is received. nginx will not try to read the whole response from the proxied server. The maximum size of the data that nginx can receive from the server at a time is set by the proxy_buffer_size directive.

Discussion: https://forum.seafile.com/t/nginx-proxy-buffering/4903

**Comment by killing** [comment]
We don't recommend this settings for busy deployments. The seafile server is based on threads. If there are many connections connected to Nginx and send large files, the thread pool in seafile server will be used up. Nginx uses an event driven architecture. So it can handle a lot of long connections.
