### ISSUE TITLE
Restricting registration to specific email domains

### ISSUE THREAD

**Issue by Bosek** [haiwen/seafile#2002]
Hello,
 I'd like to use Seafile for sharing study materials on my uni and restrict registrations to allow only users with my uni's emails(domain) to sign up. Is there any way to set this up? I didn't find anything about it in docs though. Thanks!

**Comment by turbomettwurst** [comment]
Not possible to my knowledge. Manual Activation after signing up might be your best bet.

**Comment by freeplant** [comment]
We don't have a plan to support such usage case.
