### ISSUE TITLE
Question: Can I disallow apps to access Seafile?

### ISSUE THREAD

**Issue by nan008** [haiwen/seafile#2004]
I have Seafile Community 6.2.3 - is there anyway to disallow access to the Server from any mobile device? I want to allow only Mac laptops and disallow the rest.

**Comment by turbomettwurst** [comment]
Not to my knowledge, but you can always filter on your reverse proxy based on the user agent. 
Might be somewhat tedious to configure but is better security wise since the invalid request will never reach your sf instance.

**Comment by freeplant** [comment]
If you use the pro edition, you can use the role feature to define whether a role can access from mobile device.
