### ISSUE TITLE
Usage of SeaFile

### ISSUE THREAD

**Issue by merisahakyan** [haiwen/seafile#2005]
I installed SeaFile , created admin account and choosed a local disc D for file storage. Now when I'm uploading file with admin account ,I can't find that file on my D disc. How can I find it? Maybe I need to deploy SeaFile with MySQL? only I'm using MSSQL, can I deploy it with MSSQL?

**Comment by zMingGit** [comment]
i guess file will divide into smaller files. you can't find file with complete.  i guess seafile can't support mssql.

**Comment by merisahakyan** [comment]
file is a pdf document. When I'm uploading it,can't I see it on the server?

**Comment by shoeper** [comment]
You can only view it using Seahub, download it using Seahub, SeaDrive, the client or export it using seaf-fsck as long as the library isn't encrypted.

**Comment by merisahakyan** [comment]
and need I to deploy any database or it can work without deploying?

**Comment by shoeper** [comment]
The community edition also works with sqlite.


Am 16. Januar 2018 7:38:28 nachm. schrieb Meri Sahakyan 
<notifications@github.com>:

**Comment by marcusm1009** [comment]
Please only submit bugs in GitHub issues.

Feature requests and installation/usage problem should be asked here: https://forum.seafile.com/
