### ISSUE TITLE
Activated user creation

### ISSUE THREAD

**Issue by 23degrees** [haiwen/seafile#2008]
I can create a working and active account via web browser by accessing one URL. Can I report this here or by email is better?

**Comment by freeplant** [comment]
It is better to report the issue to info@seafile.com

**Comment by 23degrees** [comment]
I'll send it there.

**Comment by freeplant** [comment]
The problem is fixed in version CE 6.2.5 and PRO 6.2.7

**Comment by freeplant** [comment]
Thank you very much.
