### ISSUE TITLE
Different start page than default?

### ISSUE THREAD

**Issue by Wurzelmann** [haiwen/seafile#2009]
Hi, I'd like to set up my Seafile installation in a way that the first page after the login isn't the default start page, but the "Shared with all" page, with the "#org/" suffix. Where can I configure this? I did not find anything about this...

Community Edition 6.2.3
Ubuntu Server 16.10.

**Comment by turbomettwurst** [comment]
To my knowledge, this isn't configurable.
I'm sure you can hack some forwarding into the login process, but as of now, that is your best bet...

**Comment by Wurzelmann** [comment]
Damn, I feared as much... thank you!
