### ISSUE TITLE
How to change SERVICE_URL in database?

### ISSUE THREAD

**Issue by bebob1** [haiwen/seafile#2011]
Hey there.

Using the Web Interface, I edited the Service URL. I wanted to change it from the Server IP to it's hostname. 

Without success. 

Now after restarting I cannot access neither Seafile nor the Seahub Web Interface via the former IP anymore.

Every help is much appreciated!

Regards
bebob

**Comment by gr01d** [comment]
If you have shell access you can edit the file in the **conf/** directory **ccnet.conf** and edit the SERVICE_URL also edit the **seahub_settings.py FILE_SERVER_ROOT**

**Comment by bebob1** [comment]
Unfortunately that doesn't solve the problem as the entry in the database has higher priority :(

**Comment by shoeper** [comment]
Simply disable the shitty web config. `ENABLE_SETTINGS_VIA_WEB = False`

**Comment by bebob1** [comment]
Too bad, I saw this too late and completely set up seafile again. But for next time, I know what to do, thanks!
