### ISSUE TITLE
seafile-applet on Linux can be started twice, leading to database lock errors, mysterious conflicts and corruption(?)

### ISSUE THREAD

**Issue by etc0de** [haiwen/seafile#2013]
seafile-applet on Linux can be started twice, leading to database lock errors, mysterious conflicts and corruption(?). Since this is an easy mistake to make, the client should really be changed to detect this and not start twice, but instead give a proper error.

I would like to give you the client version but I'm not sure how to find out what it is:
```
jonas@cyberman:~$ seafile-applet --version
seafile-applet: unrecognized option '--version'
jonas@cyberman:~$ seafile-applet --help
seafile-applet: unrecognized option '--help'
```

**Comment by killing** [comment]
Do you have this issue with the latest client?
