### ISSUE TITLE
Seafile server + onlyoffice documentserver, file not edited on download

### ISSUE THREAD

**Issue by shurik09** [haiwen/seafile#2015]
Hi, I'm using Seafile server as a local fileserver, and connected Documentserver as online editing tool, and both servers are connected through ssl, which documentserver is running as a subdomain of seafile server.

There's a problem when I download the file after editing on onlyoffice documentserver, which is the downloaded (edited) document is not changed (still stays as original version). And when I click on the document link on seafile server and open it on the onlyoffice documentserver (browser) it shows me the edited version of the document.

Does someone has similar issue? I'm guessing I misconfigured something in the conf files, but I could not find the misconfiguration

**Comment by killing** [comment]
This is most likely a configuration issue. You may find help on our forum.
