### ISSUE TITLE
slash in library name causes Server Error

### ISSUE THREAD

**Issue by xerces8** [haiwen/seafile#2016]
using client 6.1.3 on Windows

If I create a new library by adding (DnD) a folder and then enter a slash character in the library name, eg. _project/A_ 
then it gives an error dialog after clicking OK:

---------------------------
Seafile
---------------------------
Failed to create library on the server:
Server Error
---------------------------
OK   
---------------------------

**Comment by shoeper** [comment]
It's an invalid character for a library.

**Comment by xerces8** [comment]
Where is that documented? Are there other invalid characters?

It would look better to report the problem as such (in the client GUI) instead of a generic "Server Error". That makes people think there is some problem on the server.

**Comment by shoeper** [comment]
Yes, it would be better to report it as such. The "server error" in this case is that the server rejected the request because of an invalid library name. It is not allowed since / is the path separator and not allowed within folder names.

**Comment by xerces8** [comment]
library names==folder names?
Other characters than the slash are allowed?

**Comment by shoeper** [comment]
> library names==folder names?

No, but when downloading a library the name is the proposed local folder name. If I remember correct some customer complained and they forbid the /

> Other characters than the slash are allowed?

@freeplant

**Comment by xerces8** [comment]
The client could simply filter out the slash. Or create a two level folder (so "keeping" the slash). Or do whatever it does for all other invalid chars in folder names. Well, I guess this is history now...

**Comment by shoeper** [comment]
> Or create a two level folder (so "keeping" the slash).

This was the behavior before. Personally I liked it.

**Comment by killing** [comment]
The latest seahub UI prevents from creating libraries with / in name.
