### ISSUE TITLE
Webdav circumvents 2FA

### ISSUE THREAD

**Issue by spacemule** [haiwen/seafile#2017]
With 2FA and webdav enabled, users can still access the webdav URLs without supplying additional credentials other than user and password.

There's not an easy fix for this, but perhaps webdav could use a separate password so that it could be used on trusted devices.

**Comment by shoeper** [comment]
Yes, WebDAV should use an application token.

**Comment by shoeper** [comment]
@freeplant

**Comment by andrin55** [comment]
Is there any progress on this issue?

**Comment by freeplant** [comment]
We have already a separate password for webdav. In version 7.1, we will disable webdav access via normal password if 2FA enabled.

**Comment by andrin55** [comment]
I've enabled the webdav access password with: ENABLE_WEBDAV_SECRET = True

2FA is also enabeled for the user. However I'm still able to login to webdav with my normal LDAP password. Even after I restarted the seafile/seahub services. The webdav password was set in the webinterface settings.

**Comment by freeplant** [comment]
> In version 7.1, we will disable webdav access via normal password if 2FA enabled.

I mean this feature is not implemented yet.

**Comment by andrin55** [comment]
ok
