### ISSUE TITLE
How to Change Seafile Data location ?

### ISSUE THREAD

**Issue by fileadda** [haiwen/seafile#2020]
Hi...Techies..

installed seafile server on Cent OS 7 under /var/www/html folder. 
now all files which were uploaded to seafile server are stored in seafile data folder in encrypted format. and storage was full. 

so, i want to move this seafile storage folder to another mount point, which is high storage available. 

what is the process ? and where i should change settings for storage access ? 

please can anyone help me? step by step. because i am new to Seafile

Thanks

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
