### ISSUE TITLE
[feature-request] Access library history from log file, database or CLI

### ISSUE THREAD

**Issue by monkeydri** [haiwen/seafile#2022]
The library history is accessible from history icon on web interface for each library, but it is not really convenient (cannot quickly filter items or search), plus it is not accessible from admin account (if library is not share with admin user).

Is it possible to either :
- access it directly from command line on seafile-server ?
- have a log file ?
- query it from the database ?

My apologies of it is in the docs but I searched for a while.

**Comment by shoeper** [comment]
It is only available via API. See https://manual.seafile.com/develop/web_api_v2.1.html#get-library-history
