### ISSUE TITLE
Android - Images from encrypted libraries are visible in other applications

### ISSUE THREAD

**Issue by Vitani** [haiwen/seafile#2025]
1. On desktop/web, create an encrypted library, specify a password
2. Add a jpg to the library
3. On an Android device, sync the library
4. Open the library and enter the password
5. Preview/open the jpg file
6. Close the Seafile app
7. Open your "gallery" app and the picture will be visible in an album, alternatively open a messaging app and attach a picture to a message to see the "encrypted" picture.

Note this works with either server- or client-side deyption set in the Android app settings.

**Comment by shoeper** [comment]
It is designed behavior. The files are only being stored encrypted on the server.
