### ISSUE TITLE
Allow restricting HTTPS connections to specific certificates

### ISSUE THREAD

**Issue by instantname** [haiwen/seafile#2030]
A safety issue of Seafile is that there is no good authentication of the servers. HTTPS can be used, but it is commonly accepted that it does not provide enough privacy for any kind of cloud system. This is because, with so many trusted CAs, unreliable certificates may end up being signed and used for malicious purposes.

To mitigate this issue, I think that the Seafile clients could provide the possibility to authenticate servers in a more restrictive way than just having a valid SSL certificate. More precisely, in the settings of an account that uses HTTPS, three options could be proposed:

> Allow connections with:
>   - Any valid SSL certificate
>   - Only certificates from the following CA: [select .crt file]
>   - Only this certificate: [select .crt file]

**Comment by freeplant** [comment]
We don't have a plan to support such feature yet.
