### ISSUE TITLE
Fix Travis Build system

### ISSUE THREAD

**Issue by omkarnathsingh** [haiwen/seafile#2031]
Travis build fails in master branch. Please fix it.

**Comment by shoeper** [comment]
@freeplant

**Comment by shoeper** [comment]
Last successful build was https://travis-ci.org/haiwen/seafile/builds/184709324

One script that was used is not even available anymore or was moved (build-server.py).

**Comment by freeplant** [comment]
The Travis build for this project is no longer used. It moved to seafile-server and seafile-client repo.
