### ISSUE TITLE
Open https must port 443? Can i use custom port for https?

### ISSUE THREAD

**Issue by ky0ncheng** [haiwen/seafile#2033]
By default the ports 8000 and 8082 need to be opened in the firewall for incoming TCP connections.
If you run Seafile behind Nginx/Apache with HTTPS, you only need to open port 443 TCP.

https://manual.seafile.com/deploy/using_firewall.html

Can i use custom port for https?

**Comment by shoeper** [comment]
Should be possible although there are zero advantages.

**Comment by ky0ncheng** [comment]
@shoeper My 80/433 has benn blocked by ISP , I will use any other port to host a website.

**Comment by shoeper** [comment]
In which country do you live and which ISP?

**Comment by worldskat** [comment]
@ky0ncheng you can set custom port on nginx, or use firewall to dnat,  but i'm found some bugs with this config (for example admin panel not work, because it's redirect you to 443 port dispate of settings)

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
