### ISSUE TITLE
Repository for new Ubuntu Bionic not exist ?

### ISSUE THREAD

**Issue by florentlagoda** [haiwen/seafile#2034]
Hi,
In new version of Ubuntu 18.04 LTS Bionic Beaver :
```
sudo add-apt-repository ppa:seafile/seafile-client
sudo apt-get update
sudo apt-get install seafile-gui
```

`Repository=>  http://ppa.launchpad.net/seafile/seafile-client/ubuntu bionic Release have not file Release`

Workaround : replace bionic by xenial

Possible to create bionic repository ?

Regards

**Comment by omkarnathsingh** [comment]
I am facing same issue. :(

**Comment by ajeandet** [comment]
Same here. Now that 18.04 is officially released, it would be good to update the repo if possible.
For information, `do-release-upgrade` is aborting due to this problem. User has to remove the Seafile repository for the Ubuntu upgrade to go on.
Thanks!
