### ISSUE TITLE
"argument can't be null" error while sync library

### ISSUE THREAD

**Issue by worldskat** [haiwen/seafile#2035]
![_025](https://user-images.githubusercontent.com/24825418/38749528-95f8a908-3f5a-11e8-8653-6e3f5f4e00e2.png)
Today i start geting  "argument can't be null" error in clients while sync library with one of my server. I upgrade server & clients, but it doesn't work.  With same client on another server syncing work properly. I try to remove .seafile-data and .ccnet dirs, it's not help. Problem affect all clients who work with thos server. Problem start after tune server to run via nginx, but i get error even if connect directly  (servername:8000). 
SERVICE_URL and FILE_SERVER_ROOT set properly, i can upload and download files via webinterface
I found the same issue in forum (https://forum.seafile.com/t/error-when-trying-to-sync-libraries-argument-cant-be-null/5595) but there is no answer there. 
Is the "reinstall all"  is only solution?:(

**Comment by worldskat** [comment]
problem started when i make changes in SERVICE_URL & FILE_SERVER_ROOT via web interface. Settings was correct. I`m truncated table seahub-db/constance_config and make the same settings via config files, problem are gone

**Comment by dryo** [comment]
@worldskat You truncated the whole table? Or did you delete or empty file_server_root and service_url?

**Comment by dryo** [comment]
@cuihaikuo @killing Could you please have a look at this? This seems to be a problem with seafile server core so the issue is in the wrong code repository. As it seems there is some problem with the settings in ccnet.conf and the database regardless of using mySQL or SQLite.

**Comment by worldskat** [comment]
@dryo  `You truncated the whole table?` - yes, whole table
