### ISSUE TITLE
Seafile won't upload index.js file

### ISSUE THREAD

**Issue by Matgenius04** [haiwen/seafile#2039]
Hi. I am trying to upload a folder, but whenever it tries to upload specific files, it tells me it can't upload it. Any help would be appreciated.

**Comment by Matgenius04** [comment]
the specific file is index.js

**Comment by shoeper** [comment]
I cannot reproduce the issue.

It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
