### ISSUE TITLE
Seafile client (Ubuntu) - The issuer certificate of a locally looked up certificate could not be found

### ISSUE THREAD

**Issue by simonhessner** [haiwen/seafile#2040]
I am using Seafile for over two years now but suddenly get this message when Seafile starts (Ubuntu client):

> Warning: The ssl certificate of this server is not trusted, proceed anyway?

When I click on details:
> The issuer certificate of a locally looked up certificate could not be found

When I go to the Seafile via Firefox and view the certificate, all seems fine (still valid, green lock in Firefox). Chromium also accepts the certificate.
I also did not change anything in the config.

What could be the reason for this warning?

**Comment by shoeper** [comment]
Chrome and Firefox both likely have their own certificate store.

Are you sure the root - and if not served immediate - certificate is part of your systems certificate store (possibly qt even has its own?)?

**Comment by simonhessner** [comment]
Hi,
I am nut sure how to check this. I am using a standard certificate of Let's encrypt on my server. Shouldn't these certs work without a problem? At least it worked in the past.

My android Seafile client does not show any warning.

Only the Seafile client on my Ubuntu 16.04 system shows the warning.

**Comment by raimue** [comment]
Have you verified with an [SSL checker](https://www.ssllabs.com/ssltest/) that you configured your server correctly? For example, the SSL certificate chain could be incomplete in some cases if you do not serve the intermediate certificate for Let's Encrypt. It would work in Firefox or Chrome, though, because they have Let's Encrypt in their trust stores.

**Comment by simonhessner** [comment]
I get rating A with this SSL checker. The certificate is rated with 100%. Only DNS CAA is "no" but I think that is not the issue here.

**Comment by freeplant** [comment]
The certification check has been improved in the latest version. We have also helped a few customers with the certification problem. In most of the case, it is a server side problem of missing including the intermediate CA.
