### ISSUE TITLE
Need help to migrate FROM mysql TO sqlite

### ISSUE THREAD

**Issue by mo-han** [haiwen/seafile#2041]
I'm not familiar with database operations, but chose mysql when I first deplyed my seafile service just for curiosity's sake. For a long time everything has been going well, except that I prefer sqlite for the simplicity on maintenance and backup. So I decide to migrate from mysql to sqlite, but cannot find the docs (neither from official nor on the internet). Although I'm not professional in database field, the migration seems viable (even simple, with some optimism), I just need some help or instructions to tell me the right way.

Any information would be appreciated, than you for your time.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
