### ISSUE TITLE
Several Problems in Raspberry Pi Server Build Documentation

### ISSUE THREAD

**Issue by mikeazausky** [haiwen/seafile#2042]
Hi all! 

While trying to install the Seafile server on my Raspberry Pi 3 B, I found some problems and inconsistencies in the documentation (https://manual.seafile.com/build_seafile/rpi.html). I tried to summarize them all here. 

I am sorry if this is the wrong place to post this and if these fixes and problems are not relevant. 

Caution: I am still a beginner with Linux systems and am by no means a good source for provided fixes! Hopefully a more experienced person can help fix these errors.

**Install packages section:**

`sudo apt-get install libmysqpclient-dev`

resulted in error 

> Package 'libmysqlclient-dev' has no installation candidate

possible fix by replacing with 

`sudo apt-get install default-libmysqlclient-dev`

**Install Python libraries section:**

When installing the Django package with:

`easy_install -d . /tmp/django-1.8.10.tar.gz`

got the error:

> Not a URL, existing file, or requirement spec: '/tmp/Django-1.8.10.tar.gz

as the link in the document actually downloads another version: Django-1.8.18. Possible fix by installing the downloaded version instead:

`easy_install -d . /tmp/Django-1.8.18.tar.gz`

**Prepare seafile source code section**

This section had problems with the nomenclature of the folders. The code on the documentation refers to the ccnet and seafile folders differently than how they are created in the system. 

Following commands have to be replaced:
`export PKG_CONFIG_PATH=/home/pi/dev/seafile/lib:$PKG_CONFIG_PATH`
`export PKG_CONFIG_PATH=/home/pi/dev/ccnet:$PKG_CONFIG_PATH`
`cd ccnet`
`cd seafile`

with: 
`export PKG_CONFIG_PATH=/home/pi/dev/seafile-server/lib:$PKG_CONFIG_PATH`
`export PKG_CONFIG_PATH=/home/pi/dev/ccnet-server:$PKG_CONFIG_PATH`
`cd ccnet-server`
`cd seafile-server`

**CCNET Installation**

By the ccnet installation, the `./configure` command could not find the openssl packages. The packages should theoretically have been installed at the start of the process (install packages section). The following `make dist` command would result in an error, that no makefile could be found, as the `./configure` never actually created the file.

Fixed by manually installing openssl before running `./configure`with:

`sudo apt-get install libssl-dev`

**Seahub Installation**

When trying to run the command:

`./tools/gen-tarball.py --version=6.0.1 --branch=HEAD`

I got following error:

> [ERROR] django-admin scripts not found in PATH

The django-admin script inside `/dev/seahub_thirdpart` was not configured in the PATH. Fixed by adding it:

`export PATH=/home/pi/dev/seahub_thirdpart:$PATH`

**Run the packaging script**

The command of the documentation:

`~/dev/seafile/scripts/build-server.py --libsearpc_version=<libsearpc_version> --ccnet_version=<ccnet_version> --seafile_version=<seafile_version> --seahub_version=<seahub_version> --srcdir=  --thirdpartdir=/home/pi/dev/seahub_thirdpart --srcdir=/home/pi/seafile-sources --outputdir=/home/pi/seafile-server-pkgs`

Contains many inconsistencies: 

1. For some reason, the build-server.py script is not located inside the folder indicated in the documentation. The start of the command has to be changed from:

`~/dev/seafile/scripts/build-server.py`

to

`~/dev/seafile/scripts/build/build-server.py`

2. The script does not accept the seahub_version option and outputs following error:

> build-server.py: error: no such option: --seahub_version

I looked at the code, and it seems that the seahub_version is automatically derived from the seafile_version option. So it is possible that the separate input of the seahub_version is not needed and can be left out.

3. Leaving the seahub-version option out results in another error:

> [ERROR] version must be specified.

Fixed by adding the version to the options with 

`~/dev/seafile/scripts/build/build-server.py --version=<version> ...`

4. With these corrections, the script starts to run, but stops with the error:

>(...)checking for postgresql... yes
checking for pg_config... no
configure: WARNING: pg_config is required to build seafile server with postgresql
checking for ldap_init in -lldap... no
configure: error: *** Unable to find ldap client library
[ERROR] error when running command: ./configure --prefix=/tmp/seafile-server-build/seafile-server/seafile --enable-ldap

Apparently the script can't find this pg_config file. Solved by installing libpq package:

`sudo apt-get install libpq-dev`

5. I came across another error and couldn't solve it:

>checking for pg_config... /usr/bin/pg_config
checking libpq-fe.h usability... yes
checking libpq-fe.h presence... yes
checking for libpq-fe.h... yes
found postgresql client library
checking for ldap_init in -lldap... no
configure: error: *** Unable to find ldap client library
[ERROR] error when running command:./configure --prefix=/tmp/seafile-server-build/seafile-server/seafile --enable-ldap

**Comment by shoeper** [comment]
Submit a PR at https://github.com/haiwen/seafile-docs, please.

**Comment by walkerwzy** [comment]
I stoped here too

**Comment by walkerwzy** [comment]
after I delete the `--enable-ldap`, then I come across the ccnet issue:
```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I../include -I../include/ccnet -I../lib -I../include -DG_LOG_DOMAIN=\"Ccnet\" -pthread -I/tmp/seafile-server-build/seafile-server/seafile/include -I/tmp/seafile-server-build/seafile-server/seafile/include/searpc -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -Wall -DLIBICONV_PLUG -I/tmp/seafile-server-build/seafile-server/seafile/include -g -O2 -MT db.lo -MD -MP -MF .deps/db.Tpo -c db.c  -fPIC -DPIC -o .libs/db.o
utils.c: In function ‘ccnet_encrypt_with_key’:
utils.c:1056:20: error: storage size of ‘ctx’ isn’t known
     EVP_CIPHER_CTX ctx;
                    ^~~
utils.c:1056:20: warning: unused variable ‘ctx’ [-Wunused-variable]
utils.c: In function ‘ccnet_decrypt_with_key’:
utils.c:1141:20: error: storage size of ‘ctx’ isn’t known
     EVP_CIPHER_CTX ctx;
                    ^~~
utils.c:1141:20: warning: unused variable ‘ctx’ [-Wunused-variable]
Makefile:595: recipe for target 'utils.lo' failed
make[3]: *** [utils.lo] Error 1
make[3]: *** 正在等待未完成的任务....
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I../include -I../include/ccnet -I../lib -I../include -DG_LOG_DOMAIN=\"Ccnet\" -pthread -I/tmp/seafile-server-build/seafile-server/seafile/include -I/tmp/seafile-server-build/seafile-server/seafile/include/searpc -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -Wall -DLIBICONV_PLUG -I/tmp/seafile-server-build/seafile-server/seafile/include -g -O2 -MT db.lo -MD -MP -MF .deps/db.Tpo -c db.c -o db.o >/dev/null 2>&1
mv -f .deps/db.Tpo .deps/db.Plo
make[3]: Leaving directory '/tmp/seafile-server-build/ccnet-6.0.1/lib'
Makefile:453: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/tmp/seafile-server-build/ccnet-6.0.1/lib'
Makefile:496: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/seafile-server-build/ccnet-6.0.1'
Makefile:405: recipe for target 'all' failed
make: *** [all] Error 2
[ERROR] error when running command:
        make -j2

[INFO] remove builddir before exit
```

**Comment by towa48** [comment]
Solved. You should try
```
apt-get install ldap-client libldap-dev
```
