### ISSUE TITLE
Allow removing (read/read-write) permission for sub-folders

### ISSUE THREAD

**Issue by eicoelle** [haiwen/seafile#2043]
I want to suggest to enhance the fine-grained access control for sub-directories to allow the removal of permissions. Currently, permissions can be changed from the share default to read-only or read-write for groups and users. However, there is no way to remove the permission for a sub-directory. This would be a great addition when storing data in a project based structure, e.g.

    |--- Project A
       |--- Common Data
       |--- Account Staff Only Data
       |--- Management Only Data
    |--- Project B
       |--- Common Data
       |--- Account Staff Only Data
       |--- Management Only Data
    |--- ...

Given three groups (Common, Accounting, Management) when sharing I would share all directories (i.e. the library) read-only to all groups, allow read-write for `Common Data` to all groups, read-write for `Account Staff Only Data` for the Accounting and Management groups and read-write for `Management Only Data` to the Management group. It would be great if the other (not explicitly specified) groups would not inherit the read-only permission from the share and instead have no access at all. Alternatively, allow to explicitly remove the permission for these folders similar to adding read-only or read-write permissions. This would maybe look something like this:

![2018-05-01-011623_1920x1080_scrot](https://user-images.githubusercontent.com/38870391/39454759-72cbf6de-4cdd-11e8-9f65-3ab51e477094.png)

Is this idea viable at all? It would make sharing data with fine-grained access control much easier.

**Comment by freeplant** [comment]
I'm afraid we don't have a plan to add "non visible" permsision.
