### ISSUE TITLE
Building on Raspberry Pi fails (searpc-signature.h: No such file or directory)

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [haiwen/seafile#2048]
The error I'm getting is:
```
seaf-daemon.c:73:30: fatal error: searpc-signature.h: No such file or directory
```
When I compile Seafile with `./autogen.sh` then `./configure --prefix=/path/to/target/`.

This is definitely a bug because the file `searpc-signature.h` exists *only* in `tests` and `demo`. It doesn't exist as a part of libsearpc installed files.

Is there a specific version I should revert to or something?

Please advise.

(I'm on Ubuntu 16.04).

**Comment by TheQuantumPhysicist** [comment]
I've been trying the whole day to get this to work, by copying these files from other places, and it doesn't work. Please tell me how to fix this and provide a straight recipe to fix this.

Also a suggestion is to simply provide Raspberry Pi binaries for Seafile client.

Another suggestion is to use Travis CI on github to ensure that compilation is OK on every commit.

**Comment by shoeper** [comment]
https://travis-ci.org/haiwen/seafile-client

**Comment by TheQuantumPhysicist** [comment]
@shoeper I said seafile client, but I still mean this terminal client. The travis script is not for the C++ code in the repository.

**Comment by freeplant** [comment]
Compiling issue is not in our support range.
