### ISSUE TITLE
WebDaw upload is forbidden.

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [haiwen/seafile#2049]
Hello all, 

Thanks for the work you put into this. I have seafile running behind nginx and it works perfectly. Lately tho I tried to set up the webdav feature following the guide. I can successfully log into the webdav server but I cannot write anything in it. Giving 
```
ps -eo pcpu,pid,user,args | sort -k 1 -r | head -30
```

I noticed that while seahub is just run by python2.7, as in
```
python2.7 /mypath/seafile-server-6.2.5/seahub/thirdpart/gunicorn seahub.wsgi:application -c /mypath/seafile-server-6.2.5/runtime/seahub.conf -b 0.0.0.0:8000 --preload
```

The same does not happen for seafdav, for which I see:
```
/usr/bin/python2.7 -m wsgidav.server.run_server runfcgi --log-file /mypath/logs/seafdav.log --pid /mypath/pids/seafdav.pid --port 8081 --host localhost
```

Interestingly, the log file in `/mypath/logs/seafdav.log` is empty. I am surely no expert in this but I suspect that seafile is using the wrong python version when trying to spawn the webdav service. How can I fix this?

**Comment by shoeper** [comment]
python2.7 vs /usr/bin/python2.7 both run the same version and most likely using the same binary/path (/usr/bin/python2.7)...

**Comment by FabrizioRomanoGenovese** [comment]
Then I don't know what I'm doing wrong >.< I can definitely log in with webdav, but I cannot upload anything.

When I log in via browser I get an index page, which has the following last line:

Authenticated user: 'xxx', realm: 'Seafile Authentication'.

Seafile WebDAV Server, based on WsgiDAV/1.2.0.pre - Tue, 08 May 2018 16:16:44 GMT

So seafdav is responsive. But via browser there is no way to upload stuff (which I suppose is to be expected).
If I try to connect to webdav, say, via nautilus or dolphin, the webdav folder is created successfully, but when I try to put anything into it I receive a 'HTTP Client Error: Forbidden' message. 
Could this have something to do with permissions?

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
