### ISSUE TITLE
Seafile is renaming, deleting, reverting, restoring files by itself.

### ISSUE THREAD

**Issue by sourmood** [haiwen/seafile#2051]
a couple of weeks ago, we had a new starter in our company. I installed the latest(at the time) version of seafile to his machine. 6.1.7, all other users were on 6.1.1. We are a Mac environment (latest version of OS High Sierra)

I created his Seafile folder inthe Shared user folder in Mac so that any user can use the same library (to save having to download multiple copies of libraries for each user)

as soon as I did this and started to sync existing libraries, I had users email me saying that lots of files they had added recently were missing. Even after re-adding the files, they would be deleted from the server. This is what I saw when I checked the modification history for some of the libraries:

![modification 1](https://user-images.githubusercontent.com/25228615/40070919-59599f04-5867-11e8-89b6-be896b3b225e.PNG)
![modification 2](https://user-images.githubusercontent.com/25228615/40070920-59703714-5867-11e8-92a5-3202120fcb72.PNG)
![modification 3](https://user-images.githubusercontent.com/25228615/40070921-59896dce-5867-11e8-8434-83f4219aa996.PNG)
![modification 4](https://user-images.githubusercontent.com/25228615/40070922-59a1c248-5867-11e8-9e5d-2468e639297a.PNG)

This is just one instance of over 10 instances of this users seaflie client mass deleting hundreds of files by itself. the guy wasnt even at his desk when alot of this happened.

This is happening while we are trying to restructure our seafile library. thousands of files that are being moved to different folders are disappearing, being moved back to their old file location, being deleted completly by themseles or renamed.

one library alone has 55GB of data reverted. Thats alot of hours of moving files be wasted due to whatever is causing this massive glitch

**Comment by shoeper** [comment]
Do you still have the client logs? Can you upload them to https://download.seafile.com/u/d/e4dee994c0a64e35a63c/
