### ISSUE TITLE
Web API with angular 

### ISSUE THREAD

**Issue by dwlyz** [haiwen/seafile#2052]
Hi, I am trying to get JSON data from the web API. I added 'authorization: Token accesstoken' to my HTTP request header, but it returns a 403 status code on the preflight OPTIONS. Is there any solution to this problem?

![image](https://user-images.githubusercontent.com/36812768/40225417-8a2783c0-5abb-11e8-932a-e2cce23a7182.png)

Any solution?

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
