### ISSUE TITLE
Using another attribute than mail for LOGIN_ATTR in the LDAP config in ccnet.conf gives error messages when sharing folders

### ISSUE THREAD

**Issue by bcnx** [haiwen/seafile#2053]
Hi,

when you use another attribute than "mail" in ccnet.conf for LOGIN_ATTR, you receive error messages when sharing folders and picking users. The error messages indicate that only the mail attribute will work. 

More info on https://forum.seafile.com/t/why-it-always-prompts-username-invalid/3861,

thanks,

BC

**Comment by shoeper** [comment]
It is documented at https://manual.seafile.com/deploy/using_ldap.html
