### ISSUE TITLE
Can not run it by docker on CentOS7

### ISSUE THREAD

**Issue by CHN-STUDENT** [haiwen/seafile#2058]
I am trying to run it on my server,its OS is CentOS7.
And i follow the guidebook on here https://manual-cn.seafile.com/deploy/deploy_with_docker.html.
I use the official config like this:
```
docker run -it -d --name seafile \
  -e SEAFILE_SERVER_LETSENCRYPT=true \
  -e SEAFILE_SERVER_HOSTNAME=my.domain.com \
  -e SEAFILE_ADMIN_EMAIL=my@domain.com \
  -e SEAFILE_ADMIN_PASSWORD=mypassword\
  -v /home/cloud:/shared \
  -p 80:80 \
  -p 443:443 \
  seafileltd/seafile:latest
``` 
But i find it can not work normally,the docker logs is here:
```
[root@VM_6_201_centos seafile]# docker logs -f seafile
*** Running /etc/my_init.d/01_create_data_links.sh...
rm: cannot remove '/opt/seafile/seafile-server-6.2.5/seahub/media/avatars': Directory not empty
rm: cannot remove '/var/lib/mysql': Directory not empty
*** /etc/my_init.d/01_create_data_links.sh failed with status 1

*** Killing all processes...
*** Running /etc/my_init.d/01_create_data_links.sh...
rm: cannot remove '/opt/seafile/seafile-server-6.2.5/seahub/media/avatars': Directory not empty
rm: cannot remove '/var/lib/mysql': Directory not empty
*** /etc/my_init.d/01_create_data_links.sh failed with status 1

*** Killing all processes...
*** Running /etc/my_init.d/01_create_data_links.sh...
mv: cannot remove '/opt/seafile/seafile-server-6.2.5/seahub/media/avatars/groups': Invalid argument
*** /etc/my_init.d/01_create_data_links.sh failed with status 1

*** Killing all processes...
*** Running /etc/my_init.d/01_create_data_links.sh...
rm: cannot remove '/opt/seafile/seafile-server-6.2.5/seahub/media/avatars': Directory not empty
rm: cannot remove '/var/lib/mysql': Directory not empty
*** /etc/my_init.d/01_create_data_links.sh failed with status 1

*** Killing all processes...

```
Also,i am trying to remove the directory by `rm -rf /opt/seafile/seafile` and `rm -rf /var/lib/mysql
` then i try to start it `docker start seafile` ,but it does not work.

![_20180526181451](https://user-images.githubusercontent.com/21209416/40575085-c08bb87c-6110-11e8-9657-2688e42dd610.png)

Here are my docker version:
```
[root@VM_6_201_centos seafile]# docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

So,could you help me to solve it ?
Thanks!

**Comment by CHN-STUDENT** [comment]
Does it not support now? I want to get anyone's help...

**Comment by shoeper** [comment]
I think the issue is misplaced, here.

I've just tried it out, though and didn't run in the issue above. I think it has been fixed. If it still doesn't work for you, make sure that the container can actually write to /home/cloud.

**Comment by shoeper** [comment]
Are you on the latest version? Can you run `docker pull seafileltd/seafile:latest`. Does it download a newer version?

**Comment by wjangelking** [comment]
@CHN-STUDENT 你好，请问你的问题解决了么？我遇到同样的问题在Centos7上，在Windows docker下正常运行

**Comment by shoeper** [comment]
(just to have it mentioned, I don't understand any Chinese language)

**Comment by CHN-STUDENT** [comment]
@shoeper Thanks! It can work normolly now. i tried to del the image and downloaded the lateset version by `docker pull seafileltd/seafile:latest` and then started it then it can use. I guess may i get wrong or old version image. 
There are a people meet same issue @wjangelking , and he ask do i solve it. He may not know in there we need to use English to talk. Sorry. I will tell him about your suggestion and my test.
Thanks! thanks for your help.

@wjangelking 作者说让我们重新下载一个最新版镜像试试，我删掉了原来镜像并且重装后就可以使用了，我觉得可能是网络影响下错了镜像或者我们下的过老了，你也可以试试这样的方式。
另外作者说他不懂中文，因此希望我们可以用英语交流，以后建议在开源社区希望我们可以用英语交流。
（Translate: The author @shoeper tell us can download the lastest image and retry, and you can see i solve it by tring it. So can you do this? And he said hope we can use English to talk instead of Chinese in there.)

**Comment by wjangelking** [comment]
@shoeper @CHN-STUDENT Thank you for your help. My English is not very good. I'm sorry, but I will try to use English to clearly describe the problem.
The problem has now been solved.
