### ISSUE TITLE
FR: support SSHFS as backend

### ISSUE THREAD

**Issue by yatesco** [haiwen/seafile#2060]
Hi - first off, seafile is amazing at what it does, just fantastic so thank you all.

There are a number of 'cloud archive' services (e.g. https://www.hetzner.com/storage-box - no affiliation) that expose large amounts of storage over SSH, webdav etc. 

It would be awesome if seafile itself were able to support SSH, webdav etc. as a backend the same way it supports CEPH and S3.

Alternatively, I could get a small VPS which mounted the storage using SSHFS or webdav and then ran seafile pointing the mounted directory. However, this makes me nervous as I can't find any references to anybody trying this.

Is this something you would consider, even if it were only available in the commercial version? Have you any thoughts around running seafile on a VPS which mounted SSHFS underneath?

Thanks!

**Comment by freeplant** [comment]
We haven't tried with SSHFS mounted on a VPS. In theory it should work if you point seafile-data folder to SSHFS using a symbolic link. The database should still be saved on a local file system for performance reason.

**Comment by yatesco** [comment]
Thanks @freeplant, I will close this and raise any issues I encounter as separate issues.
