### ISSUE TITLE
How to upload FOLDERS using the webapi

### ISSUE THREAD

**Issue by IvanTurgenev** [haiwen/seafile#2063]
curl -H "Authorization: Token k9sdfasdfs7d1e2332cioe5v45b0fd3d343d1a253c9b" -F file=@examplefile -F filename=examplefile -F parent_dir=SeaFIleFolderexample/ https://XXXXX.com/seafhttp/upload-api/034fs581-b347-4354-4be-efeasdfcc

works for files but can i upload folders?

i am trying to transfers some files from the same server to the docker seafile instance... any idea how?

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
