### ISSUE TITLE
Still ccnet dependency in the Seafile python package

### ISSUE THREAD

**Issue by moschlar** [haiwen/seafile#2070]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/seafile/__init__.py", line 2, in <module>
    from rpcclient import SeafileRpcClient as RpcClient
  File "/usr/lib/python2.7/dist-packages/seafile/rpcclient.py", line 2, in <module>
    import ccnet
ImportError: No module named ccnet
```
https://ci.debian.net/data/autopkgtest/unstable/amd64/s/seafile/527031/log.gz

**Comment by lins05** [comment]
Thanks for catching this! We have recently removed the ccnet component from the seafile client program to simplify the architecture, but seems there is still some missing pieces . We'll fix them in the following weeks.

**Comment by moschlar** [comment]
Thanks.

**Comment by moschlar** [comment]
Hi there,
how's the status of this?

I'm currently still holding back on the updates of the official Debian Packages because I think the `seaf-cli` tool is somewhat vital for command line heavy users but it is currently still broken (cf. #2079).

Regards,
Moritz

**Comment by lins05** [comment]
@monksy we're working on it - there are work to be done with both libsearpc and seaf-cli to accommodate with the new architecture. Hopefully we can get that done within next week.

**Comment by moschlar** [comment]
That would be great, thanks!

Moritz Schlarb (Mobil)

**Comment by lins05** [comment]
@moschlar We've removed ccnet from the deps of seafile-daemon/seafile-cli and seafile-gui.
