### ISSUE TITLE
FR: seaf-cli pushing to the server without syncing?

### ISSUE THREAD

**Issue by yatesco** [haiwen/seafile#2071]
I have a central Seafile server and want various servers to back up to it. However, the libraries are encrypted which means WEBDAV is out. There isn't enough disk space on the client servers to synchronise the backup so I can't use `seaf-cli sync`.

Is there something like `seaf-cli upload`, which only pushes the data in a particular directory to a library, or even better to a particular folder in the library?

The various servers are headless Linux servers so I can't use Seafile Drive either.

Any thoughts?

Thanks.

P.S> Seafile is _awesome_ - many thanks!

**Comment by killing** [comment]
Actually you can use seadrive in headless linux server. The GUI is not required. Have a look at our documentation: https://help.seafile.com/en/drive_client/drive_client_for_linux.html

**Comment by yatesco** [comment]
That is awesome - thanks @killing .
