### ISSUE TITLE
No File Audits

### ISSUE THREAD

**Issue by wambowams** [haiwen/seafile#2077]
OS: Ubuntu 16.04.5 LTS
Seafile-Version: 6.2.13
Problem: No audits are generated

Hi, I'm using seafile and everything works fine, except the file auditing.  The Audit section in the  seafevents.conf is enabled and the tables in the mysql database exist, but are not getting filled. 
In the logs I can't find any hint what's going wrong.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
