### ISSUE TITLE
 OFFICE_WEB_APP_BASE_URL dosen't work while using collabora

### ISSUE THREAD

**Issue by chenfeichen** [haiwen/seafile#2078]
While I preview the docs file via collabora, the browser shows **Unauthorized WOPI host**, 
![](http://p4.cdn.img9.top/ipfs/QmYKgU6FiFda33i4umAab7b8MrkKkBgbGoCEErWc6iRVgL?4.png)

though I have modified the `seahub_settings.py` and delete `seahub_settings.py` and restart seafile( I even reboot my serve). 【Of course, I also set up my collabora server.】
![](http://p0.cdn.img9.top/ipfs/Qmc8RNiGkh7bgwj4NAoEDqaev4jyR5EJ4AngbbwmrYVek8?0.png)

When I tracked the error through the F12 console, I found that although I have modified the  `seahub_settings.py`, the browser will still download resource from `https://collabora-online.seafile.com`, I guess the modification of `seahub_settings.py` makes no effect.
![](http://p4.cdn.img9.top/ipfs/QmXVY55d8BqX1X8oyyDT6LS8HH2Rwbh78RBsUCJ7XSwgGX?4.png)

PS：To be honest, I prefer to discuss this issue in the forum, but our forum seems to be malfunctioning?（https://bbs.seafile.com/）

**Comment by kazh000** [comment]
I have the same problem: I had changed the content (not URL) of xml what returned from OFFICE_WEB_APP_BASE_URL. But seafile don't try to get a new xml. I tried to disable and enable OFFICE_SERVER, to change URL, but seafile always uses the once remembered xml. How to force seafile load the xml again? Is there any workaround?

**Comment by camlafit** [comment]
Hello

I know it's old but as I've an working use case. Maybe could be help in these cases.

Here I use CODE without problem with seafile 7.0.x
In my **conf/seahub_settings.py**
```
OFFICE_SERVER_TYPE = 'CollaboraOffice'
ENABLE_OFFICE_WEB_APP = True
OFFICE_WEB_APP_BASE_URL = 'https://code.domain.tld/hosting/discovery'
WOPI_ACCESS_TOKEN_EXPIRATION = 30 * 60   # seconds
OFFICE_WEB_APP_FILE_EXTENSION = ('odp', 'ods', 'odt', 'xls', 'xlsb', 'xlsm', 'xlsx','ppsx', 'ppt', 'pptm', 'pptx', 'doc', 'docm', 'docx', 'rtf')
ENABLE_OFFICE_WEB_APP_EDIT = True
OFFICE_WEB_APP_EDIT_FILE_EXTENSION = ('odp', 'ods', 'odt', 'xls', 'xlsb', 'xlsm', 'xlsx','ppsx', 'ppt', 'pptm', 'pptx', 'doc', 'docm', 'docx', 'rtf')
```

And https://code.domain.tld is avalaible. To check its state https://code.domain.tld/loleaflet/dist/admin/admin.html

You can delete seahub_settings.pyc It's should be redo on seafile restart.
I use /seafile.sh and seahub.sh command to restart them.
