### ISSUE TITLE
seahub doesn't use custom port

### ISSUE THREAD

**Issue by pr0xima1** [haiwen/seafile#2083]
When I start seahub and define a custom port ( ./seahub.sh start custom_port) seahub still uses the default port 8000. 
Maybe because of [this change](https://github.com/haiwen/seafile-server/commit/df546983cecf4a9e5cafad412ae1e0fca68b51dd#diff-04d06500a1d315cc8e34fee7f01467bcL161) in seahub.sh?

![grafik](https://user-images.githubusercontent.com/42304546/43995927-b6303a9e-9db8-11e8-9c67-0e0f7f1a7cb7.png)

EDIT: Seafile server version 6.3.2 upgraded from 6.2.3

**Comment by freeplant** [comment]
In the new version, you need to modify the conf/gunicorn.conf to change port.
