### ISSUE TITLE
Install pip libraries (e.g. pillow, moviepy, django-pylibmc) using 'pip install --user'?

### ISSUE THREAD

**Issue by carlosfilhoadm** [haiwen/seafile#2085]
I installed Seafile on my home server (running Ubuntu 16.04) by following the official instructions at manual.seafile.com, and I use a separate, non-privileged user account to launch the service through systemd.
Since I only install the required pip libraries (e.g. pillow, moviepy, django-pylibmc) because of Seafile, and in order to contain things even further, could I install such libraries to the user home directory using 'pip install --user' instead of installing system-wide?
Would Seafile (or even systemd) have any difficulty detecting and running those libraries, because of them being installed only for the user that runs the Seafile service?

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
