### ISSUE TITLE
Misleading warning on hotspot with captive portal

### ISSUE THREAD

**Issue by dreua** [haiwen/seafile#2087]
When connecting to a Wifi-Hotspot, e.g. in a cafe or a train, I am instantly greeted with a warning from Seafile:
"Warning: The ssl certificate of this server is not trusted, proceed anyway?"
Options are: "Show Details", "No", "Yes"
I know that this happens because the Hotspot tries to redirect all http/s requests to a landing page, a so called captive portal and that I just have to open this in my browser and let Seafile try again. But it is annoying for me and totally misleading for regular users not aware of the technical details. 

Proposed resolution: Have a captive portal detection like in Firefox or Gnome and do not prompt the user with warning dialogs while a captive portal is present.

Seafile Client 6.1.6 on Linux (Fedora 28)

**Comment by dreua** [comment]
Additional issue: Clicking "no" just results in the same dialog reappearing instantly.

**Comment by shoeper** [comment]
Move to https://github.com/haiwen/seafile-client, please.

**Comment by dreua** [comment]
Sorry for not paying enough attention :/
Turns out it is already there: https://github.com/haiwen/seafile-client/issues/894 (I did search for existing bugs, but in the wrong repository.)
