### ISSUE TITLE
NTP and Two-Factor Auth feature suggestion/request

### ISSUE THREAD

**Issue by ChuckHL** [haiwen/seafile#2091]
First of all, have to say it. I love Seafile much more than any other self-hosted cloud service.

That been said, I have a suggestion/request for improvement. Some people are fortunate enough to have a spare server to host their Seafile on a machine they can fully control. Some other people (like myself) use a VPS to host Seafile (and this way to make sure the server is always avaible online). The problem with VPS providers is that sometimes their servers' system time is out of sync with any NTP server and NTP update commands are not allowed by the server. 

I would suggest for a Seafile function that enables the option to ignore the server time and instead reach an NTP server to get the right time when validating Two-Factor  Authentications so that the generated code wont be out-of-sync with the server.

Regards

**Comment by shoeper** [comment]
Sorry, I don't think this will be considered.

Please contact your provider and ask him to install an ntp service.
