### ISSUE TITLE
Zipped download of large folders hits url length limit

### ISSUE THREAD

**Issue by Corwitep** [haiwen/seafile#2094]
Trying to download large folders zipped quickly triggers browser limits on url length because Seafile uses GET to transfer the list of selected files. Common browsers support urls of up to 2000 chars which is easily exceeded by trying to download a folder with several hundred files.

Seafile should use POST instead of GET to transfer the list of files to be zipped.

**Comment by ToxicMushroom** [comment]
zips seem to be made via POST now, should this not be closed ?
