### ISSUE TITLE
Seafile randomly deleting files as they're created

### ISSUE THREAD

**Issue by chiralhat** [haiwen/seafile#2098]
For the past couple months, we have been experiencing an intermittent problem where random files are deleted as soon as they are created, apparently. Our self-hosted server is running Pro 6.1.8.

In the history log for the library, we periodically get message chains similar to this (in chronological order):

Added or modified "File 1.txt"     5 minutes ago   username     Computername / 6.1.8
Deleted "File 1.txt"                      5 minutes ago   username     API / --

No user action is involved in deleting the files, and there doesn't seem to be any discernible pattern to which files are deleted and which are left alone. We can restore them from the trash bin via the web interface, but that is not a sustainable solution. We had previously seen this same deletion pattern attributed to other computers running both Linux and Windows, where again no user action was involved, which suggests that it is not some other running service (no common services running on the different machines).

I am attaching a log file that includes times when files were deleted; I did not see anything abnormal about them, and could not pinpoint exactly when the deletions occurred. Please let me know if I can provide more information that would be useful, or if there is something that I can do to stop this behavior.
[seafile.log](https://github.com/haiwen/seafile/files/2380561/seafile.log)

**Comment by freeplant** [comment]
If in the log `Deleted "File 1.txt" 5 minutes ago username API / --`, the file should be indeed deleted via API, not via the clients.

**Comment by freeplant** [comment]
You can try to update all clients to the latest version. There is a bug with 6.2.1 and 6.2.2 clients that will lead to file loss. But it will generate a different history entry (not `Deleted "File 1.txt" 5 minutes ago username API / --`)

You can paste the screenshot of the history page to provide more information.

**Comment by chiralhat** [comment]
Thanks for your reply. I'm attaching a screenshot of a relatively recent chain of these deletions happening. Right now we've been forced to move off of Seafile because so many files were being deleted, so I don't have anything more recent.

![seafile_history](https://user-images.githubusercontent.com/20075319/47725759-85226e80-dc2f-11e8-914f-4d930558099f.png)

**Comment by freeplant** [comment]
From the screenshot, you have both the Linux client and the Windows client syncing the same library. Did the user ever have rename some folder from upper case to lower case? Because the Windows system can't handle case rename, it will cause some problems.
