### ISSUE TITLE
WebDAV Exception raised when 3rd party app attempts to create folders

### ISSUE THREAD

**Issue by Eamou** [haiwen/seafile#2100]
Summary:
Notability, an app on iOS, is unable to create folders in the server via WebDAV.

Steps to reproduce:
Using Raspberry Pi server 6.3.2 with WebDAV enabled exactly to the Seafile tutorial. Using the Notability app, enabling Auto Backup and signing in to the WebDAV server. The app then attempts to upload the notes and will eventually fail due to being unable to create a folder representing a subject in which notes are contained.

Expected behaviour:
The app will try to backup the files and will succeed in uploading any files that are not contained within a 'subject', which functions exactly as a folder in the app. However, the app is unable to create folders on the server and so fails to upload any notes contained within a subject. The upload is not completed and the app reports the backup has been "Stopped", likely due to a timeout.

Observed behaviour:
Exactly as above. Upon reading seafdav.log, the following error is present and repeated hundreds of times, recurring every 0.005 seconds:

[2018-09-18 18:08:56,963]:  ErrorPrinter: caught Exception
[2018-09-18 18:08:56,965]:  Traceback (most recent call last):
  File "/home/seafile/mycloud/seafile-server-6.3.2/seahub/thirdpart/wsgidav/e$
    for v in app_iter:
  File "/home/seafile/mycloud/seafile-server-6.3.2/seahub/thirdpart/wsgidav/r$
    for v in app_iter:
  File "/home/seafile/mycloud/seafile-server-6.3.2/seahub/thirdpart/wsgidav/r$
    app_iter = method(environ, start_response)
  File "/home/seafile/mycloud/seafile-server-6.3.2/seahub/thirdpart/wsgidav/r$
    elif not parentRes.isCollection: # TODO: allow parentRes==None?
AttributeError: 'NoneType' object has no attribute 'isCollection'

[2018-09-18 18:08:56,968]:  ErrorPrinter: caught Exception
[2018-09-18 18:08:56,970]:  Traceback (most recent call last):
//traceback is exactly as above

**Comment by mdovey** [comment]
I'm having exactly the same problem with enpass 6.0. Is there any update on a resolution, or why this only seems to be a problem with some webdav clients and not others?

**Comment by wepanx** [comment]
Same problem using Threema Safe (as webdav client)

**Comment by goodnewz** [comment]
I can confirm I am facing the same issue. I am also  using Notability App on iPad. I have also tested using FolderSync for Android. FolderSync has no problem creating folders. As @mdovey said its odd it happens with some clients but not others. 

P.S. If you manually create the folders, Notability will backup your data successfully.

**Comment by caixiangyue** [comment]
We will fix this bug in 7.1.
