### ISSUE TITLE
seaf-daemon.exe - Application Error 0xc0000142 

### ISSUE THREAD

**Issue by sublack** [haiwen/seafile#2102]
Our Seafile Client 6.2.4 works well, except when Shutting Down on Windows 7. When Shutting Down Windows 7 an Error-Message is displayed for a short time with the title   "seaf-daemon.exe - Application Error" and text telling "The application was unable to start correctly (0xc0000142). Click OK to close the application." 
On Windows 10 we don´t have this error. 

Thank you very much for any help.

**Comment by freeplant** [comment]
We can't reproduce the problem.
