### ISSUE TITLE
seafile official website https://www.seafile.com/ showing "SEC_ERROR_EXPIRED_CERTIFICATE"

### ISSUE THREAD

**Issue by bhzhu203** [haiwen/seafile#2106]
seafile official website https://www.seafile.com/ showing "SEC_ERROR_EXPIRED_CERTIFICATE"

![_573](https://user-images.githubusercontent.com/3523160/46252013-ba9f3500-c494-11e8-9340-99f2e4f6b0b9.jpg)

**Comment by freeplant** [comment]
It has been fixed already.
