### ISSUE TITLE
Comments lost when doc is moved

### ISSUE THREAD

**Issue by bretif** [haiwen/seafile#2110]
Summary:
Comments are losts when file/doc is moved

Steps to reproduce 
- From Web UI
- Add comment on a doc
- Move file to another folder in the same library
- Comments are lost. you do not see them anymore
- If you move back doc where it was before, comments are back.

Expected behaviour:
- Comments to follow the doc when it is moved

**Comment by freeplant** [comment]
The Pro edition has a background process that fixing the file paths associated with comments.

**Comment by bretif** [comment]
We are using the Pro edition and we get the issue.
Where can I report error for the pro edition?

**Comment by bretif** [comment]
We use 6.2.9 version...
So I guess I need to upgrade to 6.3.x and test if we still have the issue

**Comment by freeplant** [comment]
The feature is added in 6.3.x.
