### ISSUE TITLE
sync dry-run

### ISSUE THREAD

**Issue by eleaner** [haiwen/seafile#2111]
Hi,

I have a massive 10TB library I would like to sync again with seafile server.
I could run rclone on webdav to get rid of differences before resyncing

How can I make sure that resyncing library won't mess it up? (e.g. due to strange timestamps set by webdav)
is there a dry-run option for resyncing?

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
