### ISSUE TITLE
Switch to Python 3

### ISSUE THREAD

**Issue by Jenselme** [haiwen/seafile#2112]
Hello,

As you probably know, Python 2 end of life is approaching (https://pythonclock.org/) and some linux distributions (like [fedora](https://fedoraproject.org/wiki/Changes/Mass_Python_2_Package_Removal) for which I maintain seafile) are starting to deprecate Python 2.

Can you port seafile (and related project like seahub) to Python 3 (even without removing Python 2 support)? I can help a bit if needed.

**Comment by freeplant** [comment]
We will begin the porting in 2019.

**Comment by hailfinger** [comment]
@Jenselme AFAICS the master branches in all Seafile related repos have Python 3 support now. Could you please try to package this for Fedora? Thanks.

**Comment by Jenselme** [comment]
@hailfinger thanks for the notification. Is ccnet compatible with Python 3? I see no recent updates in this repository and when I try to compile it with Python 3, it fails.

**Comment by Jenselme** [comment]
Do you know how to select the Python version to force the build on Python 3?

**Comment by hailfinger** [comment]
For ccnet, I was looking at https://github.com/haiwen/ccnet-server which seems to have Python 3 support. There also is an official announcement of Seafile Client 7.0.3 with Python 2/3 support and associated RHEL packages: https://forum.seafile.com/t/seafile-client-7-0-3-is-ready/10286

**Comment by hailfinger** [comment]
@Jenselme I have no idea how to force Python 3 support. My idea would be to remove all Python 2 packages from the build environment, then add the necessary Python 3 packages and hope for the best. The current code seems to support both.
