### ISSUE TITLE
CSRF verification failed

### ISSUE THREAD

**Issue by yeungtuzi** [haiwen/seafile#2118]
I am using a linux-vm (ubuntu 18.04 server, with internal IP 192.168.100.6) with latest docker seafile (everything default) and manually set the SSL certificates。 

While accessing https://192.168.100.6:443, I always get a CSRF error with "Referer checking failed - https://192.168.100.6/accounts/login/?next=/ does not match any trusted origins.".

While mapping 192.168.100.106:443 to external IP address:8989 on the router and visit that address, I get a CSRF error with  "CSRF cookie not set".

Please help.

**Comment by yeungtuzi** [comment]
The same error with mozilla firefox or microsoft edge

**Comment by yeungtuzi** [comment]
In this case, when I am trying to access https://my-external.ip:8989, the request will be mapped to  https://192.168.100.6:443 by the router, then mapped to https://172.17.0.2:443 by docker.

**Comment by Sirclicksalot** [comment]
I had the same issue, although not with the Docker setup; I am running Seafile behind an nginx reverse WSGI proxy with Letsencrypt certs, following the guide here: https://manual.seafile.com/deploy/https_with_nginx.html.

The resolution that worked for me was setting the following in the nginx main(443) server block;

`location / {`
`    proxy_pass               http://127.0.0.1:8000;`
`    proxy_pass_header  Set-Cookie;    <--line missing from Seafile manual`
`    proxy_set_header .   Host $host;`

**Comment by yeungtuzi** [comment]
What a pity that doesn't work for me. For a temp solution, I edit seahub/seahub/auth/views.py and disable csrf manully.

from django.views.decorators.csrf import csrf_exempt
...
#@csrf_protect
@csrf_exempt
@never_cache
def login(request, template_name='registration/login.html',
          redirect_if_logged_in=None,
          redirect_field_name=REDIRECT_FIELD_NAME,
          authentication_form=AuthenticationForm):

**Comment by omkarnathsingh** [comment]
@yeungtuzi By disabling CSRF, you are not using the security features should be in place. Better modify your cookie set properly.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.

**Comment by JPaulMora** [comment]
I am having this problem too, I even set `proxy_pass http://127.0.0.1:8000;` on Nginx config too. I checked that the cookie is indeed sent from browser to Nginx and from Nginx to the app yet the error still shows.

**Comment by looric** [comment]
> I am having this problem too, I even set `proxy_pass http://127.0.0.1:8000;` on Nginx config too. I checked that the cookie is indeed sent from browser to Nginx and from Nginx to the app yet the error still shows.
> 
> **Update** Fixed, had to add `CSRF_TRUSTED_ORIGINS = ['drive.growthengineai.com']` to my `/opt/seafile/seafile-server-7.0.4/seahub/seahub/settings.py` file.

if change port to for example 23456 and enable ssl, enable port forward from firewall,
need to do this 
 `CSRF_TRUSTED_ORIGINS = ['seafile.example.com:23456']`

**Comment by gerroon** [comment]
> > I am having this problem too, I even set `proxy_pass http://127.0.0.1:8000;` on Nginx config too. I checked that the cookie is indeed sent from browser to Nginx and from Nginx to the app yet the error still shows.
> > **Update** Fixed, had to add `CSRF_TRUSTED_ORIGINS = ['drive.growthengineai.com']` to my `/opt/seafile/seafile-server-7.0.4/seahub/seahub/settings.py` file.
> 

This does not work with local installs anymore :(

**Comment by noslenjunior** [comment]
Same here

**Comment by cvschaefer** [comment]
Same here

**Comment by noslenjunior** [comment]
> Same here, latest docker

https://forum.seafile.com/t/6-39-pro-with-docker-cannot-login-csrf-error-403/8013/4

**Comment by gerroon** [comment]
> > Same here, latest docker
> 
> https://forum.seafile.com/t/6-39-pro-with-docker-cannot-login-csrf-error-403/8013/4

That cant be the issue. I have been using exact same docker compose for years. This has started after the last docker pull.
