### ISSUE TITLE
SSO not working

### ISSUE THREAD

**Issue by omkarnathsingh** [haiwen/seafile#2120]
I have a Keycloak server, What happens is when I click on Single Sign on link in seafile login page, it redirects me to my Keycloak server and then after authentication it only puts me back to login page of seafile, no error is thrown. While i see via system admin account, that account gets added already in seafile. What should I do? I want that it should login inside seafile also, it just authenticates and make new account and put on login page.

**Comment by freeplant** [comment]
This is likely a configuration problem.
