### ISSUE TITLE
Repo [...] is version 0 library. Syncing is no longer supported

### ISSUE THREAD

**Issue by telepath** [haiwen/seafile#2128]
Since a few days my Seafile does not sync many of my libraries anymore, the status always stays on "waiting for sync".
Then I noticed, that the ccnet log fill with these entries:
```
[11/05/18 23:06:58] sync-mgr.c(2003): Repo [...] is version 0 library. Syncing is no longer supported.
```
How can I upgrade the library version?

**Comment by freeplant** [comment]
The only way is to create new library and copy files from the old library to the new library. You can copy files in the web interface. Or if you downloaded the files, you can re-upload them via the client.
