### ISSUE TITLE
Storage folder used a lot more space than reported in Seafile Web interface

### ISSUE THREAD

**Issue by NeverUsedID** [haiwen/seafile#2134]
The Web interface is reporting 19 GB used space in Admin panel, but on disk the strorage folder is using 56 GB. I removed any history files and whiped any recycle bin. I used seaf-fuse and seaf-fsck to check size and corruption. All is fine. Still I have no idea why the storgaefolder is so big

`
 

> /srv/seafile/seafile-data/storage/blocks 
>    19.2GiB [##########] /76122da7-03cb-4c76-9bd4-5cc730f0d228
>     8.1GiB [####      ] /66783a03-5862-453a-bdd7-a1a49070e404
>     8.1GiB [####      ] /3916e5ea-f13f-433e-ba82-7a711b385926
>     7.3GiB [###       ] /ada7c860-140a-4d25-bc29-1e2aac8b6efd
>     6.7GiB [###       ] /b6f55987-56d2-4d2f-b8d7-89280a9c350c
>     1.1GiB [          ] /91fe7f41-3119-48a4-9e4d-49b38bf2ceac
>   943.6MiB [          ] /1199c5b2-07fc-4c88-9426-94a847195f3d
>   755.4MiB [          ] /a52477e7-0aff-4db3-844b-cd894554c56d
>   598.6MiB [          ] /9f132626-379c-45d5-912e-79d2f1fee0ff
>   578.5MiB [          ] /9090a0b4-ae6e-444d-8e91-6673fe591244
>   408.2MiB [          ] /4317f6ec-ef55-4b80-872a-ac43cb022cab

`

I have multiple instances running, this is the only one with this bug. 

if  /76122da7-03cb-4c76-9bd4-5cc730f0d228 is the library id, this library with 19.2 GB has only 6.3 showing on the web interface (the 6.3 gb are correct). There are also some shared links on that library

**Comment by shoeper** [comment]
Seafile web interface reports the storage used without history.

**Comment by NeverUsedID** [comment]
thanks a lot for fast response.
Adding 

> [history]
> keep_days = 3

solved it instantly (after using gc) :)

Good to know that history also means "trash"
