### ISSUE TITLE
Seafile-daemon CLI locks folders on Linux

### ISSUE THREAD

**Issue by Svarto** [haiwen/seafile#2140]
Hi,

I installed Seafile-daemon yesterday on my Debian 9 machine through command line. I then tried to navigate to the virtual-drive-dir, however I found it locked (permission denied).

Checking logs I only see that all my seafile folders have been synchronized, no errors.

Is this expected behaviour? 

I'm a little confused, what's the point of the Seafile Drive Client if it locks the folder you mount it on? I expected it to work similarly to a Samba share...

**Comment by killing** [comment]
What's the permission of the mounted folder? I guess it's a local permission problem.
