### ISSUE TITLE
TIME_ZONE Setting won't apply

### ISSUE THREAD

**Issue by mab5vot9us9a** [haiwen/seafile#2145]
I am starting to lose my mind over this. I want to configure fail2ban for my seafile docker container, and as stated in the [docs](https://manual.seafile.com/security/fail2ban.html) I am setting the timezone to the appropriate one for me. But it just won't take that setting.

I start my docker container running this:
```
docker run -d --name seafile \
    -e SEAFILE_SERVER_HOSTNAME=seafile.mydomain.com \
    -e SEAFILE_ADMIN_EMAIL=seafile@mydomain.com \
    -e SEAFILE_ADMIN_PASSWORD='hard_password' \
    -v /opt/seafile-data:/shared \
    -p 8082:80 \
    seafileltd/seafile:latest
```

All the files get created, I can access the site. So far so good.

I then go into the settings under `/opt/seafile-data/seafile/conf/seahub_settings.py` and configure Email as well as the `TIME_ZONE`:
```
# [...] Stuff above omitted
# TimeZone
TIME_ZONE = 'Europe/Berlin'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.mydomain.com' # smtp server
EMAIL_HOST_USER = 'seafile@mydomain.com'
EMAIL_HOST_PASSWORD = 'hard_password'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
```

I remove the `seahub_settings.pyc` just for good measure and I restart the container: `docker restart seafile`.

I know the configuration gets read, because I get notification emails when adding new users for example. But the logs STILL use UTC. 
My Host system has the correct time. The Docker Container uses UTC, so is currently 1 hour behind. 
But the log files under `/opt/seafile-data/logs/seafile/seahub.log` still use the wrong time as well (also 1 hour behind). Which in turn causes fail2ban to not be triggered.

Any help would be appreciated.

**Comment by shoeper** [comment]
"django configure timezone"
...
"Time zone support is disabled by default. To enable it, set USE_TZ = True in your settings file. Time zone support uses pytz, which is installed when you install Django."

https://docs.djangoproject.com/en/2.1/topics/i18n/timezones/
