### ISSUE TITLE
Seafile Build on Windows

### ISSUE THREAD

**Issue by PlentyBrony** [haiwen/seafile#2147]
Is there a supported way of building Seafile for Windows? The build-msi.py script doesn't seem to work, and I was unable to find any documentation on the issue.

**Comment by iosifpeterfi** [comment]
Testcase description 

While working on a shared library, somebody uploads a file/folder containing in it's name a character that is not supported by Windows. This file/folder is later deleted from the web client. Later, the files/folders pops back into the library. 

Carried out from 

Windows 7 Laptops,  Seafile Clients 6.2.11 

Date of Testing 

2019-06-25 

Description of SetUp 

User 

Windows 7 SP 1 

Seafile Client 6.2.11 for Windows
[00-seafile-index-update-fix.patch.txt](https://github.com/haiwen/seafile/files/3329737/00-seafile-index-update-fix.patch.txt)

 

 

Result of Testing 

How to reproduce: 

User creates a file/folder with a name that contains unsupported characters for windows (ie: 'Test?' - notice the question mark) through the web interface 

User syncs the library with the client – file is added to the library index 

User deletes the file/folder with the name that contains unsupported characters from the web interface 

User syncs the library with the client. 

Expected result: The client deletes the file from the library index 

Actual result: The client does not delete the file from the library index 

User closes the Keeper/Seafile client. 

User modifies the worktree 

User starts the  Keeper/Seafileclient 

The  Keeper/Seafile client starts a scan dir process for the library 

Expected result: Only the changes to the worktree committed and uploaded 

Actual result: The changes to the worktree + the missing unsupported named file/folder are committed and uploaded 

Workaround: 

After step 3, have all the clients with access to the library run the following task on the library: 

Right Click -> Resync this library 

 
Permanent fix: 

Apply a patch that handles the index file properly on deletion of files/folders with unsupported names on Windows.
