### ISSUE TITLE
[feature request] Option for syncing folders in web GUI

### ISSUE THREAD

**Issue by Wurzelmann** [haiwen/seafile#2148]
I'd love an option in the web GUI to sync a local folder with a library, just like the Seafile Desktop Client is able to.
My goal is to create a library in the web GUI and sync it with a folder on the underlying server, which is not possible as of yet.

Is this possible at all?

Thanks in advance!

**Comment by r4dh4l** [comment]
So do you want that a *web interface* is doing the job of a sync client running in the background? Why?

> My goal is to create a library in the web GUI and sync it with a folder on the underlying server, which is not possible as of yet.

So do you want to sync files already existing on the same server running the seafile-server to the seafile-server? Did you try the seafile command line client to do this?

**Comment by Wurzelmann** [comment]
In the seafile desktop client it is possible to sync a library with a local folder and everything that gets copied to that folder is then automatically synced to my Seafile server. I want the same mechanism for my Seafile server: define a library and the exact path to the underlying file system and whenever I move files to this folder on the disk, Seafile automatically indexes it and adds it to the library. Is that possible with the command line client?

**Comment by r4dh4l** [comment]
Sure, it would be possible with the "desktop client" as well. So if your server has a desktop you can just install the desktop client. If it is a "headless" server use the command line client. The usage of the command line client is a little bit tricky but it works very well.

**Comment by Wurzelmann** [comment]
It's a headless server, yes. Thank you for the usage documentation, I will try to make this work.
