### ISSUE TITLE
File modified date changes to current after moving or copying in web

### ISSUE THREAD

**Issue by galvanopus** [haiwen/seafile#2149]
Seafile server 6.3.4.

Steps to reproduce:
1. Move or copy any file to another folder or library in web interface.
1. Check the file modification date. It will reset to the current, not retained.

This is the same issue as #1420.

**Comment by galvanopus** [comment]
I am not sure if this issue should belong to https://github.com/haiwen/seafile/, https://github.com/haiwen/seafile-server or https://github.com/haiwen/seahub.

**Comment by killing** [comment]
Fixed in https://github.com/haiwen/seafile-server/pull/203
