### ISSUE TITLE
Sublibrary "Last Update" date is not updated

### ISSUE THREAD

**Issue by galvanopus** [haiwen/seafile#2150]
Seafile Server 6.3.4.

Steps to reproduce:

1. Create a library L and a folder S inside it.
1. Share folder S to someone.
1. Wait for a few minutes.
1. Upload a file to S.
1. Login as user for whom you shared S.
1. Verify the "Last Update" date for S has not been updated after uploading a file.

**Comment by marcusmysc** [comment]
I can confirm that on Pro 6.3.7 - No error message in logs

**Comment by marcusmysc** [comment]
+ The uploaded files / changed files aren't shown in the users Acitives view and i think the size of the shared folder is not updated too.

**Comment by freeplant** [comment]
> The uploaded files / changed files aren't shown in the users acitives view

This is a known limitation.

>  think the size of the shared folder is not updated too

This may be a bug.

**Comment by freeplant** [comment]
Fixed in https://github.com/haiwen/seafile-server/pull/202

**Comment by galvanopus** [comment]
Thank you very much!
