### ISSUE TITLE
"Create library failed" if syncing a directory in a shared folder

### ISSUE THREAD

**Issue by galvanopus** [haiwen/seafile#2151]
Seafile Server 6.3.4.

Steps to reproduce:
1. Create a library L and a folder S1 inside it.
1. Create a folder S2 inside S1.
1. Share folder S1 to someone.
1. Login as user for whom you shared S1.
1. Try to sync folder S2.
1. Get the error "Create library failed!".

Client applet.log:
```
request failed for https://seafile.example.com/api2/repos/b1cc8914-1c6f-4546-8a59-aea18e109039/dir/sub_repo/?p=%2FS2&name=S2: {"error_msg":"Internal Server Error"}
Create library failed!
```
Server seahub.log:
```
[ERROR] seahub.api2.views:2863 get Cannot create sub-library from a sub-library
```

**Comment by AlexVonB** [comment]
Hi all,

I am experiencing the same issue with the same steps to reproduce and the same logs. I am on 6.3.4 CE.

Best

**Comment by freeplant** [comment]
This is a known limitation. A sub-folder of a shared sub-folder can't be selectively synced.

**Comment by AlexVonB** [comment]
Alright, thank you!

**Comment by galvanopus** [comment]
@freeplant This would be very desirable feature.

**Comment by killing** [comment]
Fixed in https://github.com/haiwen/seafile-server/pull/204
