### ISSUE TITLE
Seafile client redownloads chunks after network glitches

### ISSUE THREAD

**Issue by galvanopus** [haiwen/seafile#2152]
Seafile client 6.2.9

Steps to reproduce:
1. Start syncing large file on a slow network (1 Mbit/s) while monitoring
``seafile-data\storage\blocks\<GUID>\``
and
``seafile-data\tmpfiles\``
1. When chunks for 100 MiB are downloaded disconnect and connect network or quit and start Seafile client.
1. Verify that Seafile client starts downloading to ``seafile-data\storage\blocks\`` the same chunks that already exist in ``seafile-data\storage\blocks\<GUID>\``.

Due to this issue it is hard to download large file when using unstable network.

Expected behavior:
Seafile client should verify the checksums for files in ``seafile-data\storage\blocks`` and do not download them again.

**Comment by killing** [comment]
Seafile does check whether a block exist before downloading it. How do you check that the existing blocks are downloaded again?

**Comment by galvanopus** [comment]
Thank you!

**Comment by hachre** [comment]
I am affected by this problem also. In my case I'm not able to download a 5 GB file through the sync client. However the drive client downloads it just fine. The sync client (both Windows as well as Linux seaf-cli) keep rotating in an endless loop saying 'network error' and then redownloading the chunks for this file again and again. Would be nice if this could be fixed indeed.

**Comment by killing** [comment]
This is fixed.
