### ISSUE TITLE
Seafile client 400 bad request after changing password

### ISSUE THREAD

**Issue by pw-k** [haiwen/seafile#2153]
I've change my password via web interface so Seafile client asked me to login again.
So without changing username or server address in my client, just entering new password I cannot log in:
![screenshot_2019-01-02_12-39-32](https://user-images.githubusercontent.com/30859757/50590480-810f0900-0e8b-11e9-88fc-5bbdd1cb9dc6.png)

Log says:
```
[02.01.2019 12:32:48]Failed to login: Incorrect email or password
[02.01.2019 12:34:58]request failed for https://MY_ADDRESS/api2/auth-token/: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>

[02.01.2019 12:34:59]Failed to login: Incorrect email or password
```

But **I do can log in with web interface** with new password without any issues.

- I've tried change to shorter password - no luck
- I've tried change to simpler password - no luck
- I've even changed to old password (that was working before) - no luck

I'm using **Seafile Client 6.2.9** under Ubuntu 18.04 LTS 64bit.

Any suggestions?

**Comment by shoeper** [comment]
Logout, login

**Comment by pw-k** [comment]
You mean from my OS? I've done it, nothing changes.
Also done logout/login through web interface. Nothing changes.

Client app won't let me login so I'm already logged out ... and can't login.

What should I check next?

**Comment by pw-k** [comment]
Rebooting etc didn't help so I've deleted ~/.seafile-data folder. 
Running clean client app and pointing to synced folder woks without an issue though it seems kinda problematic way of changing passwords.
