### ISSUE TITLE
Upload fails with "Network error" in Web UI

### ISSUE THREAD

**Issue by SystemOverlord** [haiwen/seafile#2156]
I installed Seafile 6.3.4 on ubuntu 18.04.

When I use the desktop client everything works fine but when I'm using the web UI I can't upload anything. I tried small and big files as well as folders, I always get "Network error".

**Comment by mikob** [comment]
Might be related to: https://forum.seafile.com/t/fresh-install-ios-photo-sync-not-working/8059/13 can you check the linked discussion there and report back?

**Comment by SystemOverlord** [comment]
Yes, I checked it and it solved my problem thank you. 

[bionade24](https://forum.seafile.com/u/bionade24) wrote:
> Did you configured SERVICE_URL and FILE_SERVER_ROOT correctly? You can find it in the WebUI under System Admindistration -> Preferences. Should be https://example.com and https://example.com/seafhttp 

A miss configuration in the  FILE_SERVER_ROOT caused the problem. 

SERVICE_URL started with **https://**
FILE_SERVER_ROOT started with **http://**
