### ISSUE TITLE
Was the v6.2.10 release tag repointed?

### ISSUE THREAD

**Issue by jonafato** [haiwen/seafile#2158]
When attempting to update Seafile on my NixOS system, my build failed due to a hash mismatch. After further investigation, the hash was correct for [this commit](https://github.com/haiwen/seafile/commit/b7f2be78c1d979ff1242c3b65b41228e31427843), but not for the `v6.2.10` tag that the package manager fetched from GitHub, which currently points to [this commit](https://github.com/haiwen/seafile/commit/ea8f5e2b45612d77fee9934f942d1d7d55560dad). Is it possible that this tag was moved after being first released?

**Comment by freeplant** [comment]
It is overwritten by an accident.

**Comment by dotlambda** [comment]
So you're saying you used `--force` by accident??
