### ISSUE TITLE
Add Permissions for allowing/denying seafile sync for specific libraries and/or users

### ISSUE THREAD

**Issue by skuep** [haiwen/seafile#2161]
The idea would be that you could nicely control what libraries can be synced by what users to their local disks. 
If you store sensitive information in the libraries you maybe don't want anyone to have a copy on the harddrive. Instead it should only be possible to use seadrive or seahub to view them while you're on the network.
Maybe this could be integrated into the role model, however I would like this feature to be bound to the user's group since we are using a lot of LDAP.

**Comment by freeplant** [comment]
In version 7.0 (pro edition), you can share a library as view-online-only or modified-online-only, both will prevents users from sync or download files.
