### ISSUE TITLE
A huge load of ffmpeg processes after some days of runtime (Seafile 6.3.4)

### ISSUE THREAD

**Issue by DorianVasco** [haiwen/seafile#2171]
Hey, i discovered that there are a lot of instances of ffmpeg after seafile is active for a longer time. Can somebody reproduce this issue? Shouldn't there a kind of garbage collection taking care of ffmpef?

![grafik](https://user-images.githubusercontent.com/6312198/55071497-11bf4480-5089-11e9-94a9-ec9a3c974e2f.png)

Please, let me know if you need any more details.

**Comment by mumpitzstuff** [comment]
See #2168 

It is a moviepy bug. Just replace the utils.py file in your installation with my small patch to get the video thumbnail feature working.
