### ISSUE TITLE
Seafile incorrectly marks an empty folder as synchronized and deletes files in the library.

### ISSUE THREAD

**Issue by ikvidev** [haiwen/seafile#2172]
The following behavior is observed.

1. A new folder is created and synced with the Seafile client for Linux to a library with files in it, but permissions for the seafile-client are not set to that folder (permissions 770, Seafile-client not in the group).
2. Syncing the folder is done via `seaf-cli sync -l <library-id> -s <seahub-server-url> -d <existing-folder> -u <username> [-p <password>]` as recommended here https://help.seafile.com/en/syncing_client/linux-cli.html .
3. In the current case the seafile-client user doesn't have permissions to access the folder, but it still shows the library as "Downloading". 
4. After some time it marks the folder as **Synchronized**. Upon restarting the service and correcting the permissions now it starts **uploading** the folder to the library, syncing it so everything not matching the local folder in the library is **deleted**.

This is noted successfully in the log, however it doesn't stop it form deleting the files in the library:
```

[03/28/19 09:22:06] wt-monitor-linux.c(539): [wt mon] fail to add watch to /testdir: Permission denied.
[03/28/19 09:22:07] repo-mgr.c(1396): Failed to open dir /testdir: No such file or directory.
```

I think that in no point should a failed download cause deletion on the server.

OS: Ubuntu 16.04.6 LTS
Server version: 6.2.5
Client version: 6.2.9

**Comment by killing** [comment]
Unfortunately we cannot reproduce your case in our environment.

**Comment by ikvidev** [comment]
> 
> 
> Unfortunately we cannot reproduce your case in our environment.

What happens in your environment if you add a folder with 770 and the seafile-client is not in the group with '7' permissions ?

**Comment by sdotb** [comment]
Confirm than user must be in the group of GID otherwise a permission error message will manifest
