### ISSUE TITLE
File Locking Issues

### ISSUE THREAD

**Issue by empire-genomics** [haiwen/seafile#2173]
Running SeaDrive on Windows and Mac version 1.0.3
Pro Server running on Ubuntu/Docker Image version 6.3.13

Can open the same file with multiple computers, and edit them. Auto file locking does not work.
Tried to manually lock a file, appears to be locked, but get an error in the log.
If you lock the file in the web clients, other clients will not update with the locked status

**Comment by freeplant** [comment]
Auto file locking does not work with the latest Word yet. There is an error with manual locking in v1.0.3. You can try v1.0.4.
