### ISSUE TITLE
[Feature Request] Persistent share links (even after renaming folders)?

### ISSUE THREAD

**Issue by r4dh4l** [haiwen/seafile#2182]
Dear Seafile devs,

the problem was already mentioned in https://github.com/haiwen/seafile/issues/435 but I think it would be a great usability feature if share links would "survive" renaming the corresponding folder.

As always: Thx for Seafile!

**Comment by freeplant** [comment]
This feature is already presented in  pro edition and SeafileDocs branch of CE edition.

**Comment by r4dh4l** [comment]
Thx @freeplant for your answer. Does this mean that persistent share links won't be part of Seafile (standard) CE?

**Comment by freeplant** [comment]
It will not be part of standard CE.

**Comment by r4dh4l** [comment]
Okay, thx for clarification!
