### ISSUE TITLE
files deleted and folder no synchronized

### ISSUE THREAD

**Issue by mouarfff** [haiwen/seafile#2185]
Hello,

I use seafile in a homeserver just for me in debian, with 2 laptop and 1 smartphone (linux/win/android)

I use Seafile since some month and in some case, some folde"decide" to never sync. I must delete and recreate it.
Sometime a folder in pc1 don't sync, sometimes, another folder in pc2 don't sync.
Sometimes, it's sync just after launch seafile, sometimes, i can wait very long time before syncing.

And today, for the first time, i loose a folder in pc2, but in pc1, i see all file and the folder...
In windows, i can see logo say "synchronized" but nothing happend, i go to the web interface and seafile say there nothing in the folder.
Before this, i just uploaded a file from pc1 in this folder.... I waited seafile to finish sync but this morning i loose the folder.

After :
When i try to restore my folder (i'm very paranoiac with backup....), from pc1, the sync started but it stopped for no reason and the folder is always empty ........
Seafile just DELETE a folder i just put ... (8go)

**Comment by mouarfff** [comment]
I'm very afraid, i have some very old and important folder and files. I manage it with "old scholl" method with out database or "virtual"/cloud system (no bdd, just sync software very good has rsync or freeefilesync), since more than 15 years, now, my question is :

if i keep a old folder for a long time, but one time i put one file into it, maybe, i will loose the folder ? I need to alway verify in the server if the file is ok ? I must create a very very big backup with a lot of diff with date/time/size ?

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com
