### ISSUE TITLE
[Feature Request] Multithreading folder compression in seaf-server

### ISSUE THREAD

**Issue by YanzheL** [haiwen/seafile#2186]
When user requests to download a directory, `seaf-server` is used in background to compress the directory.

I observed that it is a single thread process, which can only utilize one CPU core at a time.

Since there are some open source programs that have the ability to do multithread compression, for example, `pxz`, `p7zip` and etc. So maybe this can be integrated into Seafile backend.

**Comment by Redsandro** [comment]
Preferably no `xz`, it's unreasonably resource intensive.
Honorable mention: `[pigz](https://github.com/madler/pigz)`

**Comment by freeplant** [comment]
The Seafile's golang file server can be used to solve the issue.
