### ISSUE TITLE
can't install, libselinux.so.1 problem

### ISSUE THREAD

**Issue by brizou** [haiwen/seafile#219]
Hello, I have a problem installing seafile, when i do a ./setup-seafile.sh I end up with 
/home/clement/seafile/seafile-server-1.6.0/seafile/bin/ccnet-init: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
python-selinux is installed, libselinux1 also...

**Comment by Pistos** [comment]
To get past this issue on Gentoo, I emerged libselinux .

**Comment by theminor** [comment]
This worked for me on archlinux as well - libselinux is in the aur. Please add this requirement to the installation instructions!
