### ISSUE TITLE
[FeatureRequest] Seafile Drive Show Shared Libraries split up by group

### ISSUE THREAD

**Issue by rehwanne** [haiwen/seafile#2193]
It would be nice to be able to distinguish between shares if they have the same name but are shared for different groups when using the Drive client.

Right now the directory structure is like this:

Shared with groups/
               Library A/
               Library B/
               Library C/

It would be better like this:

Shared with groups ->
               Group A/
                              Library A/
                              Library B/
               Groub B/
                              Library C/

**Comment by freeplant** [comment]
We don't have a plan to implement such a feature yet.
