### ISSUE TITLE
[Bug] Browser high memory load when opening "large" files

### ISSUE THREAD

**Issue by BlackLotus** [haiwen/seafile#2198]
Seafile version: 6.3.14 pro
When opening large text files (8mb+) in the web gui, firefox becomes unresponsive fast and after 1-2mins it can take up all 32gb of my ram.
Chromium doesn't load the file at all and only takes up cpu cycles while doing nothing.

**Comment by freeplant** [comment]
This is not a bug, but a limitation.

**Comment by BlackLotus** [comment]
Oh come on it is not a bug that your computer freezes/browser crashes/tab crashes when clicking on a file?
What is the difference between a bug and a limitation when the limiation can be solved? If a 8mb file can bring down my 32gb ram workstation that's a bug!
Partial file loading would be a solution.
The default maximum file size is 30mb if this is too much for machines I would even count reducing t he default as a solution.
I can rename the issue to [Feature Request] if that helps
