### ISSUE TITLE
Failed to connect to mysql database ccnet_db

### ISSUE THREAD

**Issue by frank-dudet** [haiwen/seafile#2203]
when I use docker-compsoe to deploy seafile 7.x, I can't start the seafileltd/seafile-mc container. And I check the docker logs, got the error below:
`Jun 12 08:22:15 8129e387518e cron[39]: (CRON) INFO (pidfile fd = 3)
Jun 12 08:22:15 8129e387518e cron[39]: (CRON) INFO (Running @reboot jobs)
[2019-06-12 08:22:31] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.
[2019-06-12 08:22:31] Running scripts /opt/seafile/seafile-server-7.0.1/upgrade/upgrade_6.3_7.0.sh
waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' (111)")
waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' (111)")
waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' (111)")
waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' (111)")
waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' (111)")
waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' (111)")
waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' (111)")
waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' (111)")
[06/12/2019 08:22:31][upgrade]: Running script /opt/seafile/seafile-server-7.0.1/upgrade/upgrade_6.3_7.0.sh

This script would upgrade your seafile server from 6.3 to 7.0
Press [ENTER] to contiune

Updating seafile/seahub database ...
[INFO] You are using MySQL
[INFO] updating ccnet database...
[ERROR] Failed to connect to mysql database ccnet_db: Can't connect to MySQL server on '127.0.0.1' (111)`

my docker-compose.yaml:
`version: \'2.0\'
services:
  db:
    image: mariadb:10.1
    container_name: seafile-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/mariadb/db:/var/lib/mariadb  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "8092:80"
'#     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - /opt/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev  # Requested, the value shuold be root's password of MySQL service.
'#      - TIME_ZONE=Asia/Shanghai # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=***@126.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=aaa123     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=10.211.55.5 # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:`

**Comment by renfeipeng** [comment]
You should upgrade from 6.3 to 7.0 . You should follow the upgrade documentation to deploy. 

https://download.seafile.com/published/support/docker/6.3%20upgrade%20to%207.0.md
