### ISSUE TITLE
wrong url for avatar url

### ISSUE THREAD

**Issue by walkerwzy** [haiwen/seafile#2204]
I run the docker with `-p 7000:80` which expose port 80 as 7000, so I use http://192.168.1.33:7000 to use the seafile web service, so far so good.
but since the service actually run at 80, some of urls are concatenate with default `:80` port, such as the avatar `http://192.168.1.33/media/avatars/1/9/249ac254115d791b6f519c4f65b408/resized/72/a17b91caeb048bc6143e07601e786210.png`

perhaps it's the `/media` directive of nginx configs, but is there a way to fix this? all url can concatenate with the host shown on the address bar (which means use the relative url, but not use parameters)

**Comment by martwalter** [comment]
Got the same issue here.
But running on an debian server.
Seafile 7.0.2

Link to the avatar picture shown as: `http://127.0.0.1:8000/media/avatars/3/4/e201bbe4b17e109f5e898520dd3e4f/resized/72/48d5f3d4053f3e756eb9185564f3905f_XUr19nd.png`

Logo Image is shown correctly with `/media/custom/mylogo.png`

If I remove the `http://127.0.0.1:8000/` part it also shows the avatar.

**Comment by imwhatiam** [comment]
@walkerwzy

**Comment by imwhatiam** [comment]
@walkerwzy 
Hello.
Can you update some codes on your Seafile server for a test. The step is:

1. open `seafile-server-latest/seahub/seahub/avatar/templatetags/avatar_tags.py`

2. change code as following:

```
diff --git a/seahub/avatar/templatetags/avatar_tags.py b/seahub/avatar/templatetags/avatar_tags.py
index b89b2847d..c21122e3f 100644
--- a/seahub/avatar/templatetags/avatar_tags.py
+++ b/seahub/avatar/templatetags/avatar_tags.py
@@ -41,13 +41,17 @@ def avatar_url(user, size=AVATAR_DEFAULT_SIZE):
 
 @cache_result
 def api_avatar_url(user, size=AVATAR_DEFAULT_SIZE):
+    from seahub.utils import get_service_url
+    service_url = get_service_url()
+    service_url = service_url.rstrip('/')
+
     avatar = get_primary_avatar(user, size=size)
     if avatar:
         url = avatar.avatar_url(size)
         date_uploaded = avatar.date_uploaded
-        return url, False, date_uploaded
+        return service_url + url, False, date_uploaded
     else:
-        return get_default_avatar_url(), True, None
+        return service_url + get_default_avatar_url(), True, None
```

3. clear cache seahub used.

4. restart Seafile.

Thanks.

**Comment by dylanhall** [comment]
Thanks, that fixed it for me.

**Comment by freeplant** [comment]
The fix will be included in the next release.

**Comment by walkerwzy** [comment]
> 3. clear cache seahub used.
how ? I've already restart the whole docker, but the avatar's url still the same, perhaps the cache reason?

**Comment by dylanhall** [comment]
I'm not sure about Docker, but for my Ubuntu installation I had to delete the cache, it's located in /tmp/seahub_cache. I just deleted the whole directory and it was recreated next time seahub was started.

**Comment by forresthopkinsa** [comment]
Is there an ETA for the next server release?

**Comment by freeplant** [comment]
New version has already been released.

**Comment by forresthopkinsa** [comment]
I'm on server version 7.1.5 and I'm having this same issue.

**Comment by dervomsee** [comment]
I istalled the last hours a new 7.1.5 CE server and i have the same issue.
@forresthopkinsa have you solved the issue in version 7.1.5?

**Comment by forresthopkinsa** [comment]
@dervomsee No, it's working for me, but I don't recall how I fixed it. It *looks* like the only change I've made to my installation since by previous comment was in `gunicorn.conf.py`:

```patch
--bind = "localhost:8000"
++bind = "0.0.0.0:8000"
```

**Comment by abstractvector** [comment]
I'm running into the same issue running Seafile Pro v7.1.9 (fresh install yesterday). Everything is working fine _except_ loading the avatar in the upper right corner. It renders correctly on the profile page, but the URL for the avatar in the upper right is trying to use port 8000 (on HTTPS). My setup is using the official Docker image (exposing port 80) running behind a reverse proxy (Traefik) on port 443.

My `SERVICE_URL` is correct in the admin area (although I swear I've had to set it back correctly numerous times) and the only other change I've checked that the `SERVICE_URL` is correct in `conf/ccnet.conf`.

I can also see the correct `SERVICE_URL` in the database (`seahub_db.constance_config`). I have restarted the Docker container, but not sure if there's a cache I should be clearing too...

**Comment by forresthopkinsa** [comment]
@abstractvector Out of curiosity – what does your `gunicorn.conf.py` look like?

**Comment by abstractvector** [comment]
```
import os

daemon = True
workers = 5

# default localhost:8000
bind = "127.0.0.1:8000"

# Pid
pids_dir = '/opt/seafile/pids'
pidfile = os.path.join(pids_dir, 'seahub.pid')

# for file upload, we need a longer timeout value (default is only 30s, too short)
timeout = 1200

limit_request_line = 8190
```

Do you think changing the bind address to `0.0.0.0:8000` will fix it?

**Comment by forresthopkinsa** [comment]
I really don't know how it would, but it looks like that's the only change I made. Worth a shot.

**Comment by abstractvector** [comment]
> I really don't know how it would, but it looks like that's the only change I made. Worth a shot.

Just updated it and restarted Seafile....no change, the avatars still have the wrong URL. Ah well, thanks for the suggestion - maybe there's a cache somewhere that I don't know about...?

**Comment by forresthopkinsa** [comment]
I looked pretty hard but couldn't find any other changes I made, so I guess it must have resolved itself on its own? Not sure.
