### ISSUE TITLE
Upgrade from 6.3 to 7.0 throws some SQL warnings

### ISSUE THREAD

**Issue by vmario89** [haiwen/seafile#2206]
Hey, i did the upgrade from 6.3.4 to 7.0.2 and noticed warnings about missing tables in seahub database:

[INFO] You are using MySQL
[INFO] updating ccnet database...
[INFO] updating seafile database...
[INFO] updating seahub database...
[WARNING] Failed to execute sql: (1146, "Table 'seahub-db.TotalStorageStat' doesn't exist")
[WARNING] Failed to execute sql: (1146, "Table 'seahub-db.TotalStorageStat' doesn't exist")
[WARNING] Failed to execute sql: (1146, "Table 'seahub-db.TotalStorageStat' doesn't exist")
[WARNING] Failed to execute sql: (1146, "Table 'seahub-db.TotalStorageStat' doesn't exist")
[WARNING] Failed to execute sql: (1146, "Table 'seahub-db.FileOpsStat' doesn't exist")
[WARNING] Failed to execute sql: (1146, "Table 'seahub-db.FileOpsStat' doesn't exist")
[WARNING] Failed to execute sql: (1146, "Table 'seahub-db.UserActivityStat' doesn't exist")
[WARNING] Failed to execute sql: (1146, "Table 'seahub-db.UserActivityStat' doesn't exist")
[WARNING] Failed to execute sql: (1146, "Table 'seahub-db.UserActivityStat' doesn't exist")
[WARNING] Failed to execute sql: (1146, "Table 'seahub-db.UserActivityStat' doesn't exist")
[WARNING] Failed to execute sql: (1146, "Table 'seahub-db.UserActivityStat' doesn't exist")
[WARNING] Failed to execute sql: (1051, "Unknown table 'seahub-db.UserTrafficStat'")
[WARNING] Failed to execute sql: (1091, "Can't DROP 'profile_profile_contact_email_0975e4bf_uniq'; check that column/key exists")
Done

migrating avatars ...

Done

everything seems working so far.

regards, Mario

**Comment by freeplant** [comment]
The warning can be ignored. These tables are used in Pro edition. But the upgrade script for community edition and pro edition is the same.
