### ISSUE TITLE
Migration script doesn't use unordered bucket listing for Ceph radosgw

### ISSUE THREAD

**Issue by emmericp** [haiwen/seafile#2215]
The migration script tries to list all objects in S3 buckets but doesn't care about the order. 
Setting the allow-unordered query parameter would speed up listing significantly when using to Ceph radosgw as S3 backend. A cluster I'm working on currently takes several hours to list a bucket, a lot of the time is very likely being spent sorting the query result due to the large number of shards.

see: http://docs.ceph.com/docs/master/radosgw/s3/bucketops/#get-bucket

**Comment by killing** [comment]
I see the point. But boto library doesn't allow adding such request parameters.

Instead we'll add an option to the script that can load object list from a file. The object list can be output to the file in the initial migration process. That would avoid fetching object list from destination again.
