### ISSUE TITLE
deepin15.10下初次安装，ip设置不对

### ISSUE THREAD

**Issue by wphu** [haiwen/seafile#2219]
deepin15.10下初次安装，ip设置不对。conf下配置文件中的ip没有设置成安装时设定的ip，在网页端设置也不生效，而默认设置的是127.0.0.1:8000。因此只能用这个ip访问，外网访问不了。
当将配置文件中的ip手动更改后，外网才能访问。

**Comment by killing** [comment]
你需要在管理员界面的设置里面去修改这个 IP 地址，在安装手册里面是有说明的。

**Comment by wphu** [comment]
> 
> 
> 你需要在管理员界面的设置里面去修改这个 IP 地址，在安装手册里面是有说明的。

我是在管理员界面设置的，没修改了，可能是个例？ 有时间可以在deepin测试一下，15.10。
