### ISSUE TITLE
KeyError: 'salt' in Seafile CLI

### ISSUE THREAD

**Issue by jangrimm** [haiwen/seafile#2222]
I have been successfully (and thankfully!) using the Seafile CLI client for data exchange and migration between Seafile Servers on Debian 9 machines. Now I merely wanted to download a library to my server, but I absolutely can't. Very unfortunately, it appears to be a unknown bug (no Google results whatsoever).

I downloaded and installed the Seafile CLI as per the documentation referred to in https://help.seafile.com/en/syncing_client/linux-cli.html. This guide I also used before to setup download/sync and did exactly alike this time.

`seaf-cli download -l 28d6f4d7-720d-4a76-9ad5-859c4c5ad5e8 -s https://resources.somedomain.com -d libs/webdev -u m@igra.te`

This is what I run.

**Expected behaviour**: The CLI downloads the library, obviously.
**Actual behaviour**: The CLI errors:

> Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 883, in <module>
    main()
  File "/usr/bin/seaf-cli", line 879, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 459, in seaf_download
    repo_salt = tmp['salt']
KeyError: 'salt'

Server Version: 6.3.7

This exact server wasn't updated and the CLI worked with it before. The CLI client doesn't work for newer Seafile Pro versions either.

**Comment by marcusmysc** [comment]
This is a known bug and will be fixed soon.

**Comment by eltonit** [comment]
I have the same error. Is there any update?

**Comment by marcusmysc** [comment]
@freeplant

**Comment by jrmagots** [comment]
Same error here! Anyone know if there is this error on 7.0.4?

**Comment by freeplant** [comment]
A new version 7.0.2 have been published. what version do you use now?

**Comment by jrmagots** [comment]
I’ve upgrade to 7.0.4 and works. I was afraid to upgrade from 6.3 to 7.0 but with this error I was forced to upgrade hehhee. But everything went right.

**Comment by eltonit** [comment]
Same here. I thought it was a seaf-cli error. I updated to 7.0.7 and now it works again.
