### ISSUE TITLE
Last modified timestamp not preserved if upload is interrupted

### ISSUE THREAD

**Issue by Daniel15** [haiwen/seafile#2228]
Seafile 7.0.4
Seafile Drive Client 1.0.6, Windows 10

When I copy files into SeaDrive, it correctly preserves the modification timestamp. 

However, if I copy a file and restart SeaDrive while the file is uploading, the upload does complete the next time SeaDrive is started, however the last modification timestamp is wrong (it shows the upload time). Deleting the file from SeaDrive then copying it again correctly sets the timestamp to the correct one.

**Comment by Daniel15** [comment]
Was this resolved? I don't see any commits attached to this issue.

**Comment by killing** [comment]
If you use 2.0.x client, this issue should not happen again.
