### ISSUE TITLE
Split huge data set into multiple commits

### ISSUE THREAD

**Issue by killing** [haiwen/seafile#224]
When indexing huge data sets, Seafile client needs to scan all the files before starting upload. This can take up many resources (CPU, disk space) and take a long time. One way to improve this is to commit in multiple batches. Each commit can be uploaded immediately.

**Comment by ikcalB** [comment]
has there been any progress on this topic, so far?
I want to backup my whole data partition (700GB+) at once. (Because I don't want to deal with a dozen libraries)

**Comment by freeplant** [comment]
This feature is already added in latest version.
