### ISSUE TITLE
Download file in wiki

### ISSUE THREAD

**Issue by bloedersack** [haiwen/seafile#2242]
There are two download buttons for a file taht can not be previewed in the wiki. This buttons have different paths and the bottom one (In the preview area) is not working. 

Is working (Top):
https://<DOMAIN>/d/<ID>/files/?p=<FILE>&dl=1

Is not working (Bottom):
https://<DOMAIN>/d/<ID>/files/?dl=1

![Capture](https://user-images.githubusercontent.com/8217500/64350137-77303d80-cff8-11e9-9580-e49e248ae2b3.JPG)

**Comment by freeplant** [comment]
It will be fixed in the next release.
