### ISSUE TITLE
Error: Failed to generate ccnet configuration

### ISSUE THREAD

**Issue by simagdo** [haiwen/seafile#2243]
Hello,

i tryed to setup the Seafile Server on a Raspberry Pi. When i run the script setup-seafile-mysql.sh and insert all necessary values and click enter to finish the script, i am getting the error Failed to generate ccnet configuration.
I entered the following values:
---------------------------------
This is your configuration
---------------------------------

    server name:            Test
    server ip/domain:       192.168.178.40

    seafile data dir:       /media/Backup/seafile/seafile-data
    fileserver port:        8082

    database:               use existing
    ccnet database:         ccnet-db
    seafile database:       seafile-db
    seahub database:        seahub-db
    database user:          seafile

**Comment by killing** [comment]
Perhaps you use special characters in the values you input.

**Comment by simagdo** [comment]
I didn't used any special characters. The configuration above are my input values i used to test the configuration.
