### ISSUE TITLE
Support encrypted MySQL connections out-of-the-box

### ISSUE THREAD

**Issue by tingvold** [haiwen/seafile#2254]
Seafile does not currently support encrypted MySQL connections out-of-the-box. It utilizes libraries that should support encrypted database connections.

Seafile should support encrypted connections, at least the minimal one (i.e. where the client only verifies the server certificate with a CA).

**Comment by tingvold** [comment]
Proper issues in the respective repos should probably be made, but progress thus far;

 * ccnet supports SSL natively, via undocumented configuration flag. Set `USE_SSL = true` in `conf/ccnet.conf`.
 * Both seafile and seahub needs changes in the code.
 * There seems to be an arbitrary number of standalone files doing direct database connections. Some of them are tools (i.e. for migration, etc), but some seems to be part of the system (`ldap_user_sync.py` comes to mind).

**Comment by tingvold** [comment]
Currently I've tried to set relevant parameters in the following files;

* `pro/python/seafevents/db.py`
* `pro/python/seafes/repo_data/db.py`
* `pro/python/seafes/seafes_data/db.py`
* `pro/python/seafevents/ldap_syncer/ldap_user_sync.py`
* `pro/python/seafevents/virus_scanner/db_oper.py`

... which seems to work partly fine, however, seafevents seems to be in a restart-loop, and seahub refuses to start (without logging any specific errors in the logs, at least not without debug flags enabled).

```==> logs/controller.log <==
[09/29/19 04:51:18] seafile-controller.c(594): pid file /srv/seafile/pids/seafevents.pid does not exist
[09/29/19 04:51:18] seafile-controller.c(625): seafevents need restart...
[09/29/19 04:51:18] seafile-controller.c(94): spawn_process: /usr/bin/python2.7 -m seafevents.main --config-file /srv/seafile/conf/seafevents.conf --logfile /srv/seafile/logs/seafevents.log -P /srv/seafile/pids/seafevents.pid
[09/29/19 04:51:18] seafile-controller.c(109): spawned /usr/bin/python2.7, pid 15476

==> logs/seafevents.log <==
[2019-09-29 04:51:18,437] [INFO] [seafevents] database: mysql, name: seafile1-seahub
[2019-09-29 04:51:18,447] [INFO] remove pidfile /srv/seafile/pids/seafevents.pid```

**Comment by tingvold** [comment]
Current changes: https://gist.github.com/tingvold/339ec21a84e6797b3ca329e7d28cef5d

**Comment by tingvold** [comment]
...and bingo! Got it! Things seems to be working thus far. The missing culprit was wrapping the `ssl` dict into `connect_args` for `create_engine()`.

Current changes: https://gist.github.com/tingvold/11346bdae4a79ce970ce2116da662e29

**Comment by tingvold** [comment]
Slight change to get LDAP user- and group sync working;

https://gist.github.com/tingvold/7d3e1c36cb1d76f6943e3a6c052590de

**Comment by tingvold** [comment]
@killing, closure of this issue means it's implemented? If so; in what version?

**Comment by killing** [comment]
As I understood, mysql client library and LDAP client library support TLS connections. I can't see why there is need to implement encryption in Seafile itself.

**Comment by tingvold** [comment]
Did you even read the proposed changes? There is no "encryption in Seafile itself". However, in order for Seafile to encrypt  it's MySQL-connections, you need to pass certain parameters to the libraries it uses in order to achieve this. That is what my proposed changes implements.

`seafile-pro-server-7.0.9/pro/python/seafes/repo_data/db.py` and `seafile-pro-server-7.0.9/pro/python/seafevents/db.py` uses `create_engine()` to establish the MySQL connection.

`seafile-pro-server-7.0.9/pro/python/seafes/seafes_data/db.py`, `seafile-pro-server-7.0.9/pro/python/seafevents/virus_scanner/db_oper.py` and `seafile-pro-server-7.0.9/pro/python/seafevents/ldap_syncer/ldap_user_sync.py` uses `MySQLdb.connect()`.

All of those methods needs additional parameters in order to achieve encryption on the MySQL connection.

If you want me to do PRs on the respective repos, please let me know.
