### ISSUE TITLE
能否在官网放上centos8 手动安装的说明

### ISSUE THREAD

**Issue by Fr33raNg3r** [haiwen/seafile#2262]
CentOS8出来这么久了，7也要过期，因此想直接部署到8上，希望能尽快出安装说明或者一键脚本，谢谢。

**Comment by killing** [comment]
CentOS 8 默认使用 Python 3，这个支持我们要在年底前才能发布。

**Comment by Fr33raNg3r** [comment]
> CentOS 8 默认使用 Python 3，这个支持我们要在年底前才能发布。

期待尽快见到你们的新产品。同时，希望安装手册能够更完善一些。
