### ISSUE TITLE
Avatars not showing in seafile-pro docker

### ISSUE THREAD

**Issue by mpiorowski** [haiwen/seafile#2277]
Using seafile-pro 7.x version with docker deployment.

When entering home page, the avatar in the right-up corner is showing the default one (:8000/media/avatars) instead of the added one, even though the added one shows correctly under settings/Profile Setting option.

There is only one place where the avatar is showing correctly, on the System Admin page (/sys/useradmin/).

**Comment by mpiorowski** [comment]
It also shows corecctly on /download_client_program/ page.

**Comment by freeplant** [comment]
Make sure you are using the latest version and SERVICE_URL is set correctly.
