### ISSUE TITLE
Zip-Download Internal server error caused by + character in filenames

### ISSUE THREAD

**Issue by syca87** [haiwen/seafile#2280]
Having a file in a library with a "+" in its filename and then downloading multiple files (including the one with the "+") causes an "internal server error" during the ZIP-process followed by log entries:
> seafile.log:[10/30/2019 07:14:37 AM] zip-download-mgr.c(342): Failed to get dirent for 190916_ Perspektive 5 DE.pptx in dir

> 
The filename in the library is '190916_ Perspektive 5+DE.pptx'
All functions work properly if the "+" is removed.

**Comment by killing** [comment]
Which version are you using? We tested with 7.0.11 Pro version and cannot reproduce this issue.

**Comment by syca87** [comment]
It is 7.0.2 community edition.

**Comment by syca87** [comment]
Updated to 7.0.5 CE
Problem solved in this version.
