### ISSUE TITLE
Ignore folder that starts with '#'

### ISSUE THREAD

**Issue by schoenpat** [haiwen/seafile#2285]
I have a folder which have to be named #recycle, but i don't want it to sync with seafile. Already tried to add \#recycle/ to the seafile-ignore.txt . This doesn't work. The restrictive variant I found is ?recycle/ , but this is too broad for me.
If I could limit an ignoring to just the root dir it would be also fine for me.

**Comment by labor4** [comment]
did you try \#
?

**Comment by schoenpat** [comment]
Yes, that was what I have written before, but github doesn't display it.
I tried `\#recycle/` and it didn't work.
