### ISSUE TITLE
Missing ppa for Ubuntu 19.10

### ISSUE THREAD

**Issue by cbruchert** [haiwen/seafile#2287]
ppa for eoan is not available in https://launchpad.net/~seafile/+archive/ubuntu/seafile-client

**Comment by s6s8** [comment]
> ppa for eoan is not available in https://launchpad.net/~seafile/+archive/ubuntu/seafile-client

+1

**Comment by wgjtyu** [comment]
need support for ubuntu19.10

**Comment by s6s8** [comment]
As of 05JAN2020

In Ubuntu 19.10 (eon) running:

`sudo` apt install seafile-gui

Installs and runs perfectly

No need to add any PPA

**Comment by Lupul** [comment]
yes, but it will install version 6.2.11 while the ver. on ppa is 7.0.4

**Comment by rumplstielz** [comment]
and you have to change your sources.list entry resp. in the seafile sources file to disco, as eoan is not there...

**Comment by Lupul** [comment]
I can confirm @rumplstielz , changing 'eoan' to 'disco' in `/etc/apt/sources.list.d/seafile-ubuntu-seafile-client-eoan.list` and `apt update && apt install seafie-gui` installed latest seafile version

**Comment by rumplstielz** [comment]
> I can confirm @rumplstielz , changing 'eoan' to 'disco' in `/etc/apt/sources.list.d/seafile-ubuntu-seafile-client-eoan.list` and `apt update && apt install seafie-gui` installed latest seafile version

nice to hear... but, IMHO there should be a eoan ppa there...

**Comment by deragon** [comment]
Ubuntu 20.04 LTS "Focal Fossa" is just around the corner.  Might as well create both PPA for _eon_ and _fossa_ right a way, in one step.  A simple copy of _disco_ should do it.

**Comment by darkdragon-001** [comment]
Ubuntu 20.04 LTS "Focal Fossa" will be release today. Still no package in the PPA :disappointed:

**Comment by darkdragon-001** [comment]
Nearly two months after this LTS release, still not available...

**Comment by killing** [comment]
PPA is no longer maintained. Please refer to the latest documentation to use official repositories. However only two recent LTS and the latest non-LTS version is supported.
