### ISSUE TITLE
Seafile doesn't sync files after quota overrun was resolved

### ISSUE THREAD

**Issue by PocketSam** [haiwen/seafile#2289]
Seafile server 7.0.4
Seafile Client 7.0.4

Hello. I've noticed several times that seafile client doesn't sync folder with a library if quota limit was exceeded even after folder content occupied space was reduced.
1. Set user quota limit.
2. Try to sync more data than you can and get library error about storage limit exceeded.
3. Remove some files to reduce folder size.
4. For now I expect Seafile Client to sync folder with a library but it won't do it.

**Comment by PocketSam** [comment]
Here is a state of library on server and local directory. 
As you can see Seafile doesn't delete files that were already removed locally. 
There is enough space due to quota to upload those files on the image.
![image](https://user-images.githubusercontent.com/1718821/69600301-adeb8200-1042-11ea-928d-9921dca44a79.png)

**Comment by killing** [comment]
You will have to resync the library in this case.

**Comment by PocketSam** [comment]
> You will have to resync the library in this case.

Ok, I would follow your advice. Thanks.
