### ISSUE TITLE
PDF version of manual

### ISSUE THREAD

**Issue by x-0n** [haiwen/seafile#2292]
I'm sorely missing a **PDF version** of the manual. This would allow offline access among other neat things (like annotating the PDF for your own personalized copy; i.e. my ereader supports this, which kicks ass for adding quick notes about gotchas encountered during installation or site-specific settings...).

Since the manual is already available on _readthedocs.org_, the effort should be _minimal_ - they support generating a PDF OOTB.

Can I please haz PDF? Kthx.

**Comment by freeplant** [comment]
I'm sorry the manual is not in readthedocs. We don't have a PDF version.
