### ISSUE TITLE
Avatars not showing after update

### ISSUE THREAD

**Issue by monte-monte** [haiwen/seafile#2299]
I hate to duplicate closed issue, but it seems to be a common problem Somehow the one I have is different from everyone else's, I've found online. My issue is perfectly described here: https://github.com/haiwen/seafile/issues/2277
I am running Seafile CE 7.0.5 docker image with 80 port exposed on 8000 port of the host. I don't use SSL as I run this instance locally. But for some reason avatart address points to https:// instead of http://
So far I've tried every solution for missing avatars that I've found on forum and github. SERVICE_URL is set correctly to http://host_IP:8000

**Comment by billxllid** [comment]
seam issue but I use CentOS7.1
