### ISSUE TITLE
Library names missing from libraries tab

### ISSUE THREAD

**Issue by santosh-sharma-pro** [haiwen/seafile#2305]
After migrating seafile from one server to other everything works fine but not able to access libraries. Under My libraries when i click on any library it give error "Library does not exist.". Under Libraries tab name of libraries are missing. seaf-fsck also didn't worked and saying Repo xxxxxxxx HEAD commit is damaged, need to restore to an old version. Can you suggest to fix this issue or best way to transfer seafile from one server to other.

**Comment by freeplant** [comment]
Our document on migrating should be fine. It is probably some steps are wrong in your procedure. You can ask support questions in our forum, giving more details about the steps you used.
