### ISSUE TITLE
Seafile Community Edition error replacing file with the same name

### ISSUE THREAD

**Issue by 7Darius** [haiwen/seafile#2319]
![ddea6a3baffe17e30b96060f1245392a049a6ad6_1_690x300](https://user-images.githubusercontent.com/56182099/76380183-1b6eb480-638d-11ea-9bce-e0078dc2317a.png)

**Comment by Bruce-hunter** [comment]
![ddea6a3baffe17e30b96060f1245392a049a6ad6_1_690x300](https://user-images.githubusercontent.com/56182099/76380299-64266d80-638d-11ea-8171-d2892e8230e2.png)
