### ISSUE TITLE
Retry upload does not upload to the same directory.

### ISSUE THREAD

**Issue by yuyichao** [haiwen/seafile#2322]
Reported to here as per https://github.com/haiwen/seahub/issues/840 even though it's unclear whether that's still meant to be followed. (It's impossible find.....)

When an upload failed, the retry link will upload it to the repo and directory currently being viewed rather than the one originally used.

This seems to be caused by `onUploadRetry` and `onUploadRetryAll` reading the repo and path from the current property since they are not saved along with the `resumableFile` in `file-uploader.js`.

**Comment by yuyichao** [comment]
@killing  Was this fixed?

**Comment by StefanMallia** [comment]
Hi! I noticed that this still seems to be an issue. Should it be re-opened?
