### ISSUE TITLE
Excessive notifications when syncing a large(ish) folder

### ISSUE THREAD

**Issue by salomvary** [haiwen/seafile#2330]
Hey, first of all, thanks for this great piece of software!

I noticed this during my first tests on a new local setup. When adding a new folder with many files and the syncing takes several minutes (which is expected), the desktop notification is repeated many times. This is unnecessary and annoying in my opinion, all I want is a single notification when the newly added folder has finished syncing. 

It is not a huge issue, still, I thought it's worth reporting.

Using macOS with the latest Seafile client and server.

<img width="250" alt="Screenshot 2020-04-28 at 15 04 55" src="https://user-images.githubusercontent.com/193923/80490812-322f9180-8962-11ea-9f54-43fcc0c5ed23.png">

<img width="344" alt="Screenshot 2020-04-28 at 15 10 17" src="https://user-images.githubusercontent.com/193923/80491016-71f67900-8962-11ea-9a8e-8c3e5c0bea1a.png">

**Comment by killing** [comment]
We don't have plan to change this behavior.
