### ISSUE TITLE
Please update seafile installation docs about ubuntu 20.04 LTS 

### ISSUE THREAD

**Issue by h0wardch3ng** [haiwen/seafile#2339]
Please update seafile installation docs about ubuntu 20.04 LTS, Thanks

https://cloud.seafile.com/published/seafile-manual-cn/deploy/using_sqlite.md

https://cloud.seafile.com/published/seafile-manual-cn/deploy/using_mysql.md

https://download.seafile.com/published/seafile-manual/deploy/using_sqlite.md

https://download.seafile.com/published/seafile-manual/deploy/using_mysql.md

**Comment by killing** [comment]
Usually we don't update our docs unless there are fundamental differences. It's recommended to use auto installation script instead of manual install.
