### ISSUE TITLE
Seafile Client for Ubuntu 20.04

### ISSUE THREAD

**Issue by changsijay** [haiwen/seafile#2341]
try to use the ppa for `ubuntu 20.04 focal`

```bash
sudo add-apt-repository ppa:seafile/seafile-client
```

got error

```
E: The repository 'http://ppa.launchpad.net/seafile/seafile-client/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by changsijay** [comment]
BTW, if I only need `seaf-cli` on my server, is there easy way to install the cli without QT GUI?

**Comment by killing** [comment]
The PPA is no longer maintained. You should follow the latest documentation: https://download.seafile.com/published/seafile-user-manual/syncing_client/install_linux_client.md
