### ISSUE TITLE
Error building deb package

### ISSUE THREAD

**Issue by dongbowh** [haiwen/seafile#2351]
dpkg-buildpackage -us -uc
dpkg-buildpackage: info: source package seafile-daemon
dpkg-buildpackage: info: source version 7.0.8
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Jonathan Xu <jonathan.xu@seafile.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
 fakeroot debian/rules clean
dh clean --with python3 --with autotools_dev
dh: Compatibility levels before 9 are deprecated (level 7 in use)
dh: The autotools-dev sequence is deprecated and replaced by dh in debhelper (>= 9.20160115)
dh: This feature will be removed in compat 12.
   dh_autotools-dev_restoreconfig
dh_autotools-dev_restoreconfig: Compatibility levels before 9 are deprecated (level 7 in use)
dh_autotools-dev_restoreconfig: dh_autotools-dev_restoreconfig is deprecated; please see dh_autotools-dev_restoreconfig(1) for a replacement
dh_autotools-dev_restoreconfig: This feature will be removed in compat 12.
   dh_clean
dh_clean: Compatibility levels before 9 are deprecated (level 7 in use)
 dpkg-source -b .
dpkg-source: error: can't build with source format '3.0 (quilt)': non-native package version does not contain a revision
dpkg-buildpackage: error: dpkg-source -b . subprocess returned exit status 255

**Comment by killing** [comment]
Which Debian version do you use?

**Comment by az0** [comment]
Did you figure this out? With another project, I get the same error building on OpenSUSE for Ubuntu 20.10 but not for 20.04.

**Comment by feiniks** [comment]
Which Debian version and seafile client version do you use?
