### ISSUE TITLE
waiting for mysql server to be ready: %s (1130, "Host '' is not allowed to connect to this MariaDB server")

### ISSUE THREAD

**Issue by chendelin1982** [haiwen/seafile#2359]
I use docker composer file: https://docs.seafile.com/d/cb1d3f97106847abbf31/files/?p=/docker/docker-compose.yml
All docker containers are running, but error for seafile docker container:

*** Running /etc/my_init.d/01_create_data_links.sh...
*** Booting runit daemon...
*** Runit started as PID 14
*** Running /scripts/start.py...
*** Shutting down /scripts/start.py (PID 15)...
*** Shutting down runit daemon (PID 14)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
*** Init system aborted.
*** Killing all processes...
*** Running /etc/my_init.d/01_create_data_links.sh...
*** Booting runit daemon...
*** Runit started as PID 14
*** Running /scripts/start.py...
waiting for mysql server to be ready: %s (1130, "Host '172.20.0.4' is not allowed to connect to this MariaDB server")
waiting for mysql server to be ready: %s (1130, "Host '172.20.0.4' is not allowed to connect to this MariaDB server")
waiting for mysql server to be ready: %s (1130, "Host '172.20.0.4' is not allowed to connect to this MariaDB server")
waiting for mysql server to be ready: %s (1130, "Host '172.20.0.4' is not allowed to connect to this MariaDB server")

Below is the content of my file

version: '2.0'
services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/seafile-mysql/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "80:80"
      - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - /opt/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=Asia/Shanghai # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=me@example.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=asecret     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether use letsencrypt to generate cert.
      - SEAFILE_SERVER_HOSTNAME=seafile.example.com # Specifies your host name.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:

**Comment by chendelin1982** [comment]
it's ok

**Comment by buzhangjiuzhou** [comment]
@chendelin1982 How do you solved this question?
