### ISSUE TITLE
Creating or renaming folders from Nautilus on a Seafile Webdav server fails with "Bad gateway"

### ISSUE THREAD

**Issue by arnova** [haiwen/seafile#2361]
I've been trying to get Seafile's Webdav to work with my Mint 19.3 (MATE version) laptop. I've used Nautilus's native Webdav connection ability. All is fine (listing files/folders, reading/writing files etc.) except for creating new folders and renaming folders. On the server side I'm running Debian 10 with Seafile 7.1.4. I'm not 100% what the culprit is as Webdav with WinSCP on Windows seems to work fine. Another pointer may be that when one tries to create a folder and assigns a name to it, actually a folder called "untitled folder" is created. Afterwards renaming it results in "Bad gateway" again.

**Comment by killing** [comment]
You should check the forum: https://forum.seafile.com/t/seafdav-move-command-causing-502/11582

Also in the doc: https://download.seafile.com/published/seafile-manual/extension/webdav.md

**Comment by arnova** [comment]
> You should check the forum: https://forum.seafile.com/t/seafdav-move-command-causing-502/11582
> 
> Also in the doc: https://download.seafile.com/published/seafile-manual/extension/webdav.md

Thanks for your reply. Unfortunately I already tried that and it doesn't fix the problem....

**Comment by killing** [comment]
This should be configuration issue. Please post on our forum: https://forum.seafile.com.

**Comment by arnova** [comment]
@killing: 7.1.5 fixes this probably because of "[fix] Fix WebDAV error if a file is moved immediately after uploading"
