### ISSUE TITLE
seahub website profile photo source path is not correct

### ISSUE THREAD

**Issue by ldjts** [haiwen/seafile#2367]
I'm using seafile 7.1.4 and nginx reverse proxy. I've changed both SERVICE_URL and FILE_SERVER_ROOT, but when I login to my seahub the profile photo src path still redirect to http://***.com:8000/media/avatars/default.png. Even after I uploaded my photo!
please fix this bug.

**Comment by ldjts** [comment]
![pic](https://user-images.githubusercontent.com/18499389/92042579-15421980-edad-11ea-8803-36b031b49c79.png)

**Comment by killing** [comment]
This should be configuration issue. Please post on our forum: https://forum.seafile.com.
