### ISSUE TITLE
Navigation item "Wikis" is not displayed under "Tools"

### ISSUE THREAD

**Issue by mknet** [haiwen/seafile#2370]
Hello everbody,

according to a [German manual page](https://de.seafile.com/wikis/) there should be a "Tool" called "Wikis". After starting the Community and Pro version based on docker, I am not able to find this "Tool" to setup a Wiki instead of an ordinary library.
Is this a former feature and no longer supported?

Thanks for any hint

**Comment by freeplant** [comment]
Wikis are now changed to be called public libraries.

**Comment by mknet** [comment]
Thanks for your response. Could you give me another hint on how I can change the nav on the let to not show the MD file names but a custom structure like you did  under https://download.seafile.com/published/seafile-manual/home.md

Thanks, again
