### ISSUE TITLE
OnlyOffice: JWT broken for public shared links / PR for fix available

### ISSUE THREAD

**Issue by pronichev** [haiwen/seafile#2372]
Hello,

if you configure Seafile with OnlyOffice and use JWT, public shared links do not work. The reason for that is that Seahub does not include the JWT token in the link. A fix is available: [#4558](https://github.com/haiwen/seahub/pull/4558)

Can you please merge this Pull Request in order to fix this bug.

Thank you!

**Comment by killing** [comment]
This issue has been fixed.
