### ISSUE TITLE
How to change sidebar in "public libraries"?

### ISSUE THREAD

**Issue by mknet** [haiwen/seafile#2381]
Hello everbody,

how could I change the nav on the left to not show the markdown file names but a custom structure like you did under https://download.seafile.com/published/seafile-manual/home.md

Thanks for your help and take care
Marcel

**Comment by killing** [comment]
You can add an index.md file into the library. Use unordered list to organize the directory structure.

**Comment by mknet** [comment]
Cooooool! I love this feature! Many thanks, @killing
