### ISSUE TITLE
Seafile-Server upgrade to 7.1.5 sqlite3.OperationalError: duplicate column name: headers

### ISSUE THREAD

**Issue by whowantsmybigdata** [haiwen/seafile#2391]
Hi,
I'm running Seafile 7.0.5 CE on my Raspberry Pi with Raspbian/Debian 10 Buster.
Everything is running well but when I was trying to upgrade to 7.1.5

<details><summary>I get this error:</summary>

```
[INFO] updating seahub database...
Traceback (most recent call last):
  File "/home/seafile/seafile-server-7.1.5/upgrade/db_update_helper.py", line 384, in <module>
    main()
  File "/home/seafile/seafile-server-7.1.5/upgrade/db_update_helper.py", line 379, in main
    db_updater.update_db()
  File "/home/seafile/seafile-server-7.1.5/upgrade/db_update_helper.py", line 275, in update_db
    super(SQLiteDBUpdater, self).update_db()
  File "/home/seafile/seafile-server-7.1.5/upgrade/db_update_helper.py", line 129, in update_db
    self.update_seahub_sql(seahub_sql)
  File "/home/seafile/seafile-server-7.1.5/upgrade/db_update_helper.py", line 299, in update_seahub_sql
    self.apply_sqls(self.seahub_db, sql_path)
  File "/home/seafile/seafile-server-7.1.5/upgrade/db_update_helper.py", line 289, in apply_sqls
    conn.execute(line)
sqlite3.OperationalError: duplicate column name: headers
```

</details>

So far I tried:
- seaf-fsck.sh 
- seaf-gc.sh
- seahub.sh python-env seahub/manage.py clearsessions
- seahub.sh python-env seahub/manage.py clear_invalid_repo_data
- manually checked integrity of all databases (in ccnet, seafile.db and seahub.db) with <code>PRAGMA integrity_check;</code>
- checking for any missing or outdated packages and modules regarding the doc
- of course rebooting 

everything without errors, only while upgrading...
Thanks!

**Comment by feiniks** [comment]
The seahub database don't have a column named headers on seafile 7.0,it's added on 7.1.So you need delete this column in seahub database and rerun this script.The table's name is 'post_office_attachment' which include column of headers.

**Comment by whowantsmybigdata** [comment]
Thanks for the reply, could you give me the commands how to achieve that? I have absolutely no idea of database management and internet-searching for it only made my confusion worse.

**Comment by whowantsmybigdata** [comment]
> The seahub database don't have a column named headers on seafile 7.0,it's added on 7.1.So you need delete this column in seahub database and rerun this script.The table's name is 'post_office_attachment' which include column of headers.

Thanks for the reply, could you give me the commands how to achieve that? I have absolutely no idea of database management and internet-searching for it only made my confusion worse.

**Comment by feiniks** [comment]
> > The seahub database don't have a column named headers on seafile 7.0,it's added on 7.1.So you need delete this column in seahub database and rerun this script.The table's name is 'post_office_attachment' which include column of headers.
> 
> Thanks for the reply, could you give me the commands how to achieve that? I have absolutely no idea of database management and internet-searching for it only made my confusion worse.

Maybe you can use the following commands in seahub.db，but I suggest you to understand the syntax of sqlite.
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "temp_post_office_attachment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "file" varchar(100) NOT NULL, "name" varchar(255) NOT NULL, "mimetype" varchar(255) NOT NULL);
INSERT INTO temp_post_office_attachment SELECT id, file, name, mimetype from post_office_attachment;
DROP TABLE post_office_attachment;
ALTER TABLE temp_post_office_attachment RENAME TO post_office_attachment;
COMMIT;

**Comment by whowantsmybigdata** [comment]
wow, worked flawlessly! Probably you are right, it would help a lot if I would understand this... cant do everything at the same time!
Thanks a lot!
