### ISSUE TITLE
Recommended method to access Seafile data on the server itself

### ISSUE THREAD

**Issue by IngwiePhoenix** [haiwen/seafile#2395]
I migrated to Seafile after breaking my OwnCloud install and since the feature to add folders from outside the installation itself as a shareable folder, I need to move those previously shared folders into my own library instead. Which is cool - but this also means that I have to transfer 200GB of files from the raw FS into Seafile's storage system.

Right now, I am using `davfs2` on `/mnt/seafile`. Using `rsync --progress -ar /some/folder/ /mnt/seafile/myLib/`, I get about 5MB/s transfer speed. That...is slow, very slow.

Is there a better method to directly access the Seafile datastore?

I have Seafile installed through Docker for an ease of deployment.

**Comment by feiniks** [comment]
Hello, this should be a issue about the useage of seafile. You can ask questions on our seafile forum to get the corresponding answer.https://forum.seafile.com/

**Comment by killing** [comment]
You can use the Linux client to sync the files to Seafile.
