### ISSUE TITLE
Shared direct download link only opens directory - Seafile-Server 7.1.5 on Raspian 10

### ISSUE THREAD

**Issue by whowantsmybigdata** [haiwen/seafile#2397]
_Seafile-Server 7.1.5 for Raspberry Pi
Raspbian 10 Buster
SQLite database
Nginx 1.14.2_

If I share a download link to a folder with e.g. about 150 pictures (roughly 500mb) and click "direkt download" it correctly adds the `/?dl=1` to the link but the result is the same as without the `/?dl=1` - its just opening the folder showing the thumbnails of every single picture (which I wanted to avoid).

Inside the folder I can easily either download a specific picture or click on "ZIP" in the upper right corner.

I tried it on different browsers (Firefox, Safari, Chrome), with and without addons activated - its always the same problem...

I also tried to add
```
max_upload_size=10240
max_download_dir_size=10240
web_token_expire_time=36000
```
to the `[fileserver]` section of `conf/seafile.conf`and restartet - same result...

If I pack the pictures to a zip file myself before uploading/syncing them to the seafile-library and afterwards share a direct download link of the zip, it works flawlessly, downloading it directly after clicking on the link.

**Comment by feiniks** [comment]
Sorry,you can't add  the /?dl=1 to the link.Because the download link to a folder don't support "direct download".You can see the "direct download link"  in the sharing link interface when you share a picture.

**Comment by whowantsmybigdata** [comment]
> Sorry,you can't add the /?dl=1 to the link.Because the download link to a folder don't support "direct download".You can see the "direct download link" in the sharing link interface when you share a picture.

Ah ok, didn't know that, sorry...
