### ISSUE TITLE
Seafile CE 8.0.2 breaks OnlyOffice integration with security token

### ISSUE THREAD

**Issue by Tjelfe** [haiwen/seafile#2417]
After Upgrading to CE 8.0.2 (from 7.1.5) OnlyOffice integration is broken when secured via security token.
Configuration in  seahub_settings.py:
`ONLYOFFICE_JWT_SECRET = ‘mySecret’`

OnlyOffice is deployed using docker with a custom local.json where the security token is defined.

Accessing an office dokument from Seafile web interface leads to an error message 'The documents security token is not correct. Please contact your system administrator.'

OnlyOffice integration with disabled security token still works.

**Comment by alexw1982** [comment]
are you upgrading inside the container (as there is no official seafile 8 container yet)?

**Comment by alexw1982** [comment]
and is pyjwt install on the seafile container - see also [haiwen/seafile-docker #231](https://github.com/haiwen/seafile-docker/issues/231)?

**Comment by jobenvil** [comment]
@killing Can somebody confirm that it works with 8.0.3? Now I get [following errors](https://forum.seafile.com/t/broken-onlyoffice-in-seafile-ce-8-0-2/13564/11). I found out while testing the rpi version with tags `8.0.3-server`

**Comment by chendelin1982** [comment]
I use Seafile8.0.4 community, connect OnlyOffice by http (not https), the error below
![image](https://user-images.githubusercontent.com/16741975/116044773-e5c97f80-a6a3-11eb-9467-f96dad284f6d.png)
