### ISSUE TITLE
Encounter an issue with Seafile permission

### ISSUE THREAD

**Issue by wh-leong** [haiwen/seafile#2421]
Hi all. I'm encountered an issue where when I assigned the permission right to a specific folders, the assigned group was suddenly removed when I return back to the folder. It only happens on some folders. One thing that I saw was that there was a red dot on the folder icon. May I know what is the cause of the issue? Thanks.

**Comment by wh-leong** [comment]
![Folder](https://user-images.githubusercontent.com/78142564/106117801-5a1c8180-618e-11eb-90eb-076d21264819.JPG)

This is the icon that I see on the folder. The folder cannot be edited or deleted. We have not yet shared it to anyone else. Please advise. Thanks.

**Comment by feiniks** [comment]
The icon like that indicates that the directory is read-only,so you can't edit or delete it.This should be a library shared to you by others and permission right have been set.The group may be deleted by the owner,so you see that the group was suddenly removed.

**Comment by wh-leong** [comment]
Thanks. May I know is there any way we can remove this file? Thanks.

**Comment by feiniks** [comment]
The folder only can be deleted by the owner,you need to ask the owner who shared repos to you  to delete it.

**Comment by wh-leong** [comment]
Thanks.
