### ISSUE TITLE
Network Error: Connection Refused error

### ISSUE THREAD

**Issue by wh-leong** [haiwen/seafile#2423]
Hi all. I was setting up the Seafile when I encountered this error - "Network Error: Connection Refused". May I know what would be the cause of the issue? Please note that there is no firewall blocking as I was able to install the same installer within the same network on a different laptop with a different ID. Please advise. Thanks.

![dialog box](https://user-images.githubusercontent.com/78142564/106259657-7b4aa400-625a-11eb-9133-f27e2939b0d8.JPG)

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com
