### ISSUE TITLE
The save path is different  between normal with s3 backend

### ISSUE THREAD

**Issue by rayer4u** [haiwen/seafile#2426]
我一直使用seafile作为网盘，近来想切换存储为minio，基于s3配置，通过配置新建文件都正常。在迁移已有数据时，发现seafile在minio上的目录和普通目录的路径不一致。  
普通本地磁盘的目录是
`local.../blocks/44cda982-395c-47b5-915d-f25ce6d375f4/86/63a70ef30a5987b440a621483af2044bae1e0a`
直接按照相应的结构迁移过去，会提示404错误。需要把相应的二级目录（示例的**86**）拼接到文件，才能正确识别。
`minio/seafile-block/44cda982-395c-47b5-915d-f25ce6d375f4/8663a70ef30a5987b440a621483af2044bae1e0a`
虽然我做了个[工具](https://github.com/rayer4u/rayer4u.github.io/blob/master/omv/seafile/seafile_minio_mv.sh)，批量做这个转换，不过当数据量很大时，性能很差，因此想问一下，是否有相关配置能够规避此问题？

seafile版本：docker版本的seafile-pro-server-7.1.8
seafile.conf：
```seafile.conf
[commit_object_backend]
name = s3
bucket = seafile-block
key_id = 123456
key = 123456
host = minio:9000
path_style_request = true
memcached_options = --SERVER=memcached --POOL-MIN=10 --POOL-MAX=100
...
```

**Comment by feiniks** [comment]
我们有专门迁移数据的脚本，如果想要从本地存储切换到s3，需要将本地的数据迁移到s3，你可以参考下这篇文档https://cloud.seafile.com/published/seafile-manual-cn/deploy_pro/migrate.md

**Comment by rayer4u** [comment]
知道了。谢谢！
