### ISSUE TITLE
"Permission denied" error uploading via password protected upload links

### ISSUE THREAD

**Issue by r4dh4l** [haiwen/seafile#2429]
Hi,

I don't know if this issue belongs here or to https://github.com/haiwen/seahub - however: Since I've upgraded to Seafile CE 8.0.3 I can not upload files via Seahub using password protected upload links anymore. Seahub reports "permission denied". The upload works fine using non-protected upload links.

**Comment by magneticcoffee** [comment]
Hey,

using the patched `upload_links.py` from haiwen/seahub#4810 resolved the issue for us.

**Comment by r4dh4l** [comment]
Thank you, so I hope this will be part of the next Seafile CE version.

**Comment by killing** [comment]
This is fixed in 8.0.4 version.
