### ISSUE TITLE
lib/seafile-object.h 会造成编译失败

### ISSUE THREAD

**Issue by mlkt** [haiwen/seafile#2433]
> cb877e00d9e037e9a4a58084ee635ac8d2aae616
> portable visual studio 2019 (#2378)

这个commit引入的 lib/seafile-object.h 使我在树莓派(arm 32位，ubuntu 14.04，gcc 4.8)上编译时失败，应该是因为优先用了 lib 里面的头文件所以导致没有使用自动生成的 seafile-object.h，我把 lib/seafile-object.h 手动删除后编译就成功了

> make[2]: Entering directory '/root/seafile-8.0.1/lib'
> make  all-am
> make[3]: Entering directory '/root/seafile-8.0.1/lib'
> /bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include   -I../include -I../lib -I../common -pthread -I/opt/usr/include -I/opt/usr/include/searpc -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -Wall   -g -O2 -MT seafile-rpc-wrapper.lo -MD -MP -MF .deps/seafile-rpc-wrapper.Tpo -c -o seafile-rpc-wrapper.lo seafile-rpc-wrapper.c
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I../include -I../lib -I../common -pthread -I/opt/usr/include -I/opt/usr/include/searpc -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -Wall -g -O2 -MT seafile-rpc-wrapper.lo -MD -MP -MF .deps/seafile-rpc-wrapper.Tpo -c seafile-rpc-wrapper.c  -fPIC -DPIC -o .libs/seafile-rpc-wrapper.o
> In file included from seafile-rpc-wrapper.c:17:0:
> seafile-object.h:177:45: error: expected declaration specifiers or '...' before 'g_object_unref'
>  G_DEFINE_AUTOPTR_CLEANUP_FUNC (SeafileRepo, g_object_unref)
>                                              ^
> seafile-object.h:292:49: error: expected declaration specifiers or '...' before 'g_object_unref'
>  G_DEFINE_AUTOPTR_CLEANUP_FUNC (SeafileSyncTask, g_object_unref)
>                                                  ^
> seafile-object.h:308:52: error: expected declaration specifiers or '...' before 'g_object_unref'
>  G_DEFINE_AUTOPTR_CLEANUP_FUNC (SeafileSessionInfo, g_object_unref)
>                                                     ^
> seafile-object.h:315:50: error: expected declaration specifiers or '...' before 'g_object_unref'
>  G_DEFINE_AUTOPTR_CLEANUP_FUNC (SeafileDiffEntry, g_object_unref)
>                                                   ^
> seafile-object.h:328:55: error: expected declaration specifiers or '...' before 'g_object_unref'
>  G_DEFINE_AUTOPTR_CLEANUP_FUNC (SeafileEncryptionInfo, g_object_unref)
>                                                        ^
> seafile-object.h:350:54: error: expected declaration specifiers or '...' before 'g_object_unref'
>  G_DEFINE_AUTOPTR_CLEANUP_FUNC (SeafileFileSyncError, g_object_unref)
>                                                       ^
> seafile-object.h:372:45: error: expected declaration specifiers or '...' before 'g_object_unref'
>  G_DEFINE_AUTOPTR_CLEANUP_FUNC (SeafileTask, g_object_unref)
>                                              ^
> seafile-object.h:403:50: error: expected declaration specifiers or '...' before 'g_object_unref'
>  G_DEFINE_AUTOPTR_CLEANUP_FUNC (SeafileCloneTask, g_object_unref)
>                                                   ^
> make[3]: *** [seafile-rpc-wrapper.lo] Error 1
> make[3]: Leaving directory '/root/seafile-8.0.1/lib'
> make[2]: *** [all] Error 2
> make[2]: Leaving directory '/root/seafile-8.0.1/lib'
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory `/root/seafile-8.0.1'
> make: *** [all] Error 2

**Comment by killing** [comment]
14.04 的版本太老了吧。

**Comment by mlkt** [comment]
> 14.04 的版本太老了吧。

文档里用的就是这个版本
https://manual.seafile.com/build_seafile/linux/
而且因为我的cpu是arm 32位的，ubuntu只有这个版本有arm 32位的版本
