### ISSUE TITLE
Ignore file does not work.

### ISSUE THREAD

**Issue by cupcakearmy** [haiwen/seafile#2434]
The .git folders seem to always be included. I tried `.git/` and `.git*`, but none of them actually works. Client is on macOS version 8. Server also 8. Any ideas?

`seafile-ignore.txt` is in the root of the library.

```
node_modules/
.venv/
venv/
.git/
*.asd
```

**Comment by killing** [comment]
Are the files under .git/ folder already synced before you updated the seafile-ignore.txt?

**Comment by cupcakearmy** [comment]
At first not, but I deleted the directories, waited to sync them. Then I added `.git` to the ignore file, waited that to sync and addded the directories back in.
I also set up an empty library to play around and directories starting with a dot seem have issues.

**Comment by cupcakearmy** [comment]
@killing so the issue ist that `.git/` only works for root level directories. Should be in the docs I think, as most people (including me) would treat it more like a `.gitignore` file.
`*/.git/` works

**Comment by cupcakearmy** [comment]
@killing the problem was that `.git/` only excludes the directory at the root, which is very counter intuitive. `*/.git/` seems to work. Maybe a little node in the docs could help a lot of people as i think most (me included) will think of it more like a gitignore file.
