### ISSUE TITLE
RepoId 泄漏导致资料泄漏

### ISSUE THREAD

**Issue by lianghongkey** [haiwen/seafile#2436]
我发现只要知道 repo id ，就可以直接下载repo里面的文件，而不需要认证。
不知道这个是允许的，还是不正常。
比如 ： http://xxxx:xxxx/seafhttp/files/xxxxxxxx-xxxx-xxxx-xxxx-xxxx96f51995/aa.md

**Comment by feiniks** [comment]
files后面跟着的不是资料库ID，而是该资料库的access token，这个token就是用来认证的。

**Comment by lianghongkey** [comment]
哦哦，我确认一下，确实是。 我看错了。 谢谢！！
