### ISSUE TITLE
seafile-object.h       G_DEFINE_AUTOPTR_CLEANUP_FUNC  not found  ！！！！

### ISSUE THREAD

**Issue by drip-hailin** [haiwen/seafile#2437]
![image](https://user-images.githubusercontent.com/51024883/114050129-97a03800-98be-11eb-86c7-da57c2a3037d.png)

G_DEFINE_AUTOPTR_CLEANUP_FUNC  not found 

why

**Comment by drip-hailin** [comment]
glib 2.26.1

**Comment by drip-hailin** [comment]
You've seen this before

**Comment by vsudhakar05** [comment]
I'm Getting same error. Please help me how you resolved.
