### ISSUE TITLE
Avatar not rendering correctly on clean install/SERVICE_URL incorrect

### ISSUE THREAD

**Issue by munrobasher** [haiwen/seafile#2438]
Clean install v7.1.5 on Mint v20 and it gets SERVICE_URL right:

[https://i.imgur.com/zz8x9aB.png](url)

Clean install v8.0.4 on same system and it misses the port off the end:

[https://i.imgur.com/jayDypw.png](url)

Fix is to edit the SERVICE_URL in system settings and restart.

**Comment by munrobasher** [comment]
Apologies if I've not reported it correctly, not really used Github...

**Comment by killing** [comment]
How do you install seafile?

**Comment by munrobasher** [comment]
Using the instructions here:

[https://manual.seafile.com/deploy/using_sqlite/](https://manual.seafile.com/deploy/using_sqlite/)

But I guess the key step is running the **./setup-seafile.sh** script and then starting the services using **./seafile.sh start** and **./seahub.sh start**  

The same process is used for both version installs.

**Comment by killing** [comment]
You should install with the installation scripts or Docker. Configuration issues can happen if you follow the manual install guide, depending on your environment.

**Comment by munrobasher** [comment]
I am installing with the install scripts?? seafile.sh is the script supplied in the package for installing.
