### ISSUE TITLE
seafile cannot listen on IPv6 address

### ISSUE THREAD

**Issue by imp1sh** [haiwen/seafile#2439]
It doesn't seem to be possible to listen on an IPv6 address for the seafile service.
When I configure the service to bind to an IPv6 adress or to [::] in seafile.conf like this:
```
port = 8082
host = [::]
```
It results in a service listenting on a broadcast address, i.e:

```
ss -ltpn|grep 8082
LISTEN   0        128             255.255.255.255:8082           0.0.0.0:*       users:(("seaf-server",pid=1160,fd=15))    
```

Instead of [::] I also tried a specific IP address that is assigned to the interface but the result is identical.
Please give full support for IPv6.

**Comment by killing** [comment]
For such use case, you should configure nginx to listen on IPv6. seafile can work behind nginx.

**Comment by imp1sh** [comment]
On the public facing side nginx already is configured to serve IPv6 but that's not my point. In order for the reverse proxy to reach the seafile service I need IPv6, too. The seafile host is at another site than the proxy and the traffic needs to cross several routers. As a workaround I setup NAT rules on a router, because it's mixed public IP and RFC1918. 
The seahub service is already reachable via v6 from the proxy only the seafile service can not, because it lacks support.
Please implement IPv6 support.

**Comment by killing** [comment]
Currently we have no plan to support IPv6 in seaf-server. Nginx is always needed.

**Comment by imp1sh** [comment]
That's sad. I hope you will reconsider. Maybe this will help.
https://tools.ietf.org/html/bcp177

**Comment by imp1sh** [comment]
Is there a commit or pull request regarding that issue? In what version will this be available?
