### ISSUE TITLE
请支持webp格式的图片预览

### ISSUE THREAD

**Issue by williamyan1024** [haiwen/seafile#2441]
摘要：请支持webp格式的图片预览
重现步骤：上传一张.webp结尾的图片文件,然后web端在线预览
预期的行为：能显示图片
观察到的行为：提示"文件编码无法识别"

测试图片已上传,抱歉github也不支持上传.webp扩展名的文件,已压缩zip
[mmexport5ad0239921f4340786b26bbeaf0a28bd.zip](https://github.com/haiwen/seafile/files/6302690/mmexport5ad0239921f4340786b26bbeaf0a28bd.zip)

**Comment by qwe624758472** [comment]
你应该把这个问题提到seahub里边吧！

**Comment by williamyan1024** [comment]
已提,谢谢
