### ISSUE TITLE
Seafile CE 8.0.4 breaks logout page when running under non-root context

### ISSUE THREAD

**Issue by itac-abaldauf** [haiwen/seafile#2443]
I have configured seafile server to run under the non-root context /seafile

With CE 8.0.4, when logging out from the web site, /accounts/logout/ is being used as logout URL - resulting in a 404 error. The correct URL would be /seafile/accounts/logout/ (which is being shown when entered manually). For 8.0.3 and earlier versions this worked and and used correct URL.

**Comment by itac-abaldauf** [comment]
Same behaviour still occurs with CE 8.0.5

**Comment by dawansv** [comment]
Confirming this problem as well. I ended up adding a "Redirect permanent /accounts/logout/ /seafile/accounts/logout/" to my apache conf file but it's not exactly the cleanest way to fix this (and it's a good thing that the /accounts/logout/ url is not actually used by something else)

**Comment by itac-abaldauf** [comment]
Just as for the login url, the logout url is being loaded from the default settings.py file since 8.0.4, and can be overriden in the conf/seahub_settings.py just like this for a non-root context:

SITE_ROOT = '/seafile/'
LOGIN_URL = '/seafile/accounts/login/'
LOGOUT_URL = '/seafile/accounts/logout/'

After adding the LOGOUT_URL in the same manner, logging out works correctly.
