### ISSUE TITLE
Database may contain duplicate entries within VirtualRepo table

### ISSUE THREAD

**Issue by ss23** [haiwen/seafile#2449]
While investigating haiwen/seahub#4897, I observed that our database contains duplicate entries in the VirtualRepo table:
```sql
mysql> SELECT COUNT(*) as qty,origin_repo,path,base_commit FROM VirtualRepo GROUP BY path,origin_repo,base_commit HAVING qty > 1;
+-----+--------------------------------------+---------+------------------------------------------+
| qty | origin_repo                          | path    | base_commit                              |
+-----+--------------------------------------+---------+------------------------------------------+
|   2 | 5beed6b1-fa3e-45da-9f5f-796f3ffed3bd | /xxx    | 1f6bf24d24643e66a500f35f46dbf49d28b40d7b |
[...]
110 rows in set (0.01 sec)
```

Manually inspecting them shows they are duplicates:
```sql
mysql> select * from VirtualRepo where path = '/xxx';
+------+--------------------------------------+--------------------------------------+---------+------------------------------------------+
| id   | repo_id                              | origin_repo                          | path    | base_commit                              |
+------+--------------------------------------+--------------------------------------+---------+------------------------------------------+
| 1453 | 76500198-7e19-4a28-afa6-b54029018f3a | 5beed6b1-fa3e-45da-9f5f-796f3ffed3bd | /xxx    | 1f6bf24d24643e66a500f35f46dbf49d28b40d7b |
| 1507 | fb500ab4-b146-4781-9949-1327a36d099d | 5beed6b1-fa3e-45da-9f5f-796f3ffed3bd | /xxx    | 1f6bf24d24643e66a500f35f46dbf49d28b40d7b |
+------+--------------------------------------+--------------------------------------+---------+------------------------------------------+
```

The code to prevent this happening looks to be in https://github.com/haiwen/seafile-server/blob/master/server/virtual-repo.c#L349, where `get_existing_virtual_repo` is used before creating the new repository in `seaf_repo_manager_create_virtual_repo`.

From what I can tell, there should not be duplicate entries here, and may be related to the issue I am having in the bug mentioned above.

A quick fix for this issue going forward is to add a UNIQUE index or constraint to the table, however this won't fix the issue in previous databases.

Assuming this is a bug, is there a way to "fix" the database to ensure it's in a consistent state? I imagine the VirtualRepo ID is used in a lot of places, but it's a relatively small database, so I wonder if it wouldn't be too hard to write a migration that resolves it?

**Comment by killing** [comment]
Perhaps this duplicated entry was created in some older version. The latest code ensures that there is only one entry.

**Comment by ss23** [comment]
@killing It is possible, but I know that haiwen/seahub#4897 is still occurring on the latest version. I just noticed this while investigating the issue.

Do you think it would be easy to "clean" the database to resolve this issue? That way I can be sure it's unrelated to the issue I am trying to investigate. It wasn't clear to me whether I could just remove the duplicates and update the parts of the database.
