### ISSUE TITLE
[Bug] FORCE_PASSWORD_CHANGE does not force the new user to change their password

### ISSUE THREAD

**Issue by AlexVonB** [haiwen/seafile#2453]
Hi!

**Problem**:
Accounts that are created by an API call have to be given a password. The new user is not forced to change this password.

**Usecase**:
The usecase is creating Seafile accounts for users instead of them creating the accounts themselves. The password has to be mailed to the new user in plain text. This leads to the usage of compromised passwords, because users usually do not change the passwords on their own.

**Suggested Solutions**:
- Fix the `FORCE_PASSWORD_CHANGE` setting to work properly.
- Alternatively, an API-endpoint to reset a user's password would be just as good. This only is possible by GUI interaction right now and thus not automatable.

Thanks, Alex

**Comment by schlagi123** [comment]
Hi,

First of all, I find the same issue in my installation. I set the configuration "FORCE_PASSWORD_CHANGE = True" and create a new User in seahub. After the first login this new user wasn't forced to change his password.

The Documentation:
```
# Force user to change password when admin add/reset a user.
# Added in 5.1.1, deafults to True.
FORCE_PASSWORD_CHANGE = True

```

If I reset the user password, the user was forced to change his password, but by adding not.

I think, this is not a feature request. It is a bug in the functionality or in the documentation.

**Comment by AlexVonB** [comment]
Was closed by https://github.com/haiwen/seahub/commit/968e4b5051797e30e7fe6f67b12c092fb6fccba6, thank you very much!
