### ISSUE TITLE
What is a valid filename on Windows

### ISSUE THREAD

**Issue by ygramoel** [haiwen/seafile#2455]
Since 8.0.2,  Seafile client checks (even on Linux) that filenames in synced folders are valid for Windows.

How precisely does Seafile check filenames?  Whether a filename is valid on Windows is not just a question of flagging illegal characters.  For example, spaces are allowed but not at the start or end of a filename,  and a name like 'COM1' or 'NUL' is not allowed.  See https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names

**Comment by killing** [comment]
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file This is the official documentation.
