### ISSUE TITLE
seafdav partial download fails: ''SeafBlockManager' object has no attribute 'obj_store''

### ISSUE THREAD

**Issue by why-1998** [haiwen/seafile#2456]
server version 7.1.18 with wsgidav

HTTP 500: **Source exception: ''SeafBlockManager' object has no attribute 'obj_store''** is the error when downloading partial content via seafile webdav and the byte range does not start at 0.

test script to reproduce the misbehavior:

```
#!/bin/bash
BASIC_AUTH_USER="user@seafile.domain.tld"
BASIC_AUTH_PASSWORD="seafdavpassword"
AUTH=$(echo -ne "$BASIC_AUTH_USER:$BASIC_AUTH_PASSWORD" | base64 --wrap 0)
curl -v --header "Authorization: Basic $AUTH" --header "Range: bytes=0-1023" --header "Referer: https://seafile.domain.tld/seafdav/" "https://seafile.domain.tld/seafdav/mylibrary/thefiletodownloadpartial.dat" --output thefiletodownloadpartial.dat_part_OK
curl -v --header "Authorization: Basic $AUTH" --header "Range: bytes=1-1023" --header "Referer: https://seafile.domain.tld/seafdav/" "https://seafile.domain.tld/seafdav/mylibrary/thefiletodownloadpartial.dat" --output thefiletodownloadpartial.dat_part_NOTWORKING
```
the first curl will get the correct bytes from the server, the second one catches an exception and results in the HTTP 500 error saying:
**Source exception: ''SeafBlockManager' object has no attribute 'obj_store''**

possibly the error is in seafobj/blocks.py where stat_block only considers obj_store but fails if obj_stores is required?

please have a look for pull request [#53](https://github.com/haiwen/seafobj/pull/53) at seafobj, may be that could solve the problem?

**Comment by killing** [comment]
Thank you we'll have a look.

**Comment by why-1998** [comment]
Thanks!
