### ISSUE TITLE
WebDav appears to erase individual file history

### ISSUE THREAD

**Issue by matejdro** [haiwen/seafile#2461]
Whenever WebDav updates the file it appears to delete the file and then recreate it. This seems to delete the history of individual files. For example, following file has been created months ago and was only edited by WebDav yesterday. But it appears as if history of the file has just started yesterday:

![image](https://user-images.githubusercontent.com/507922/122596141-ba429000-d069-11eb-8d04-1b4b5e2633cc.png)

Repo is set to "Keep full history". This bug does not appear to affect history of the whole repo (I can still restore old snapshots for the entire repo).

**Comment by killing** [comment]
That may be a behavior your webdav client.

**Comment by matejdro** [comment]
That may be, but isn't Seafile supposed to keep entire history of the files, even through deletions?

**Comment by killing** [comment]
Seafile doesn't keep history for deleted files.

**Comment by killing** [comment]
I'm closing this issue at the moment, as it's not supposed to be supported by Seafile.
