### ISSUE TITLE
Large file transfer stuck

### ISSUE THREAD

**Issue by simonflick** [haiwen/seafile#2467]
Large file upload of 122 files (17.2 GB) stopped half way through. Already happened in the past on another large upload queue.
This is frustrating as there is no "retry" or "skip existing files" function.

![image](https://user-images.githubusercontent.com/19348971/123523490-2fded980-d6c4-11eb-9328-3e3104ef0131.png)
![image](https://user-images.githubusercontent.com/19348971/123523461-fb6b1d80-d6c3-11eb-85d1-02d7e928ac73.png)

Using Chrome 91.0.4472.114 on Windows 10 21H1.

**Comment by feiniks** [comment]
Hello,this may be due to your upload time exceeding one hour, causing web access token to expire. You can choose to upload separately or add expire time of web access token.
