### ISSUE TITLE
Dumps directory is not created within set CCNET_CONF_DIR

### ISSUE THREAD

**Issue by jfastnacht** [haiwen/seafile#2473]
In https://github.com/haiwen/seafile/blob/eed7fa2250e7e13e4ac98ec519e044ce892ca508/daemon/seaf-daemon.c#L372 and https://github.com/haiwen/seafile/blob/eed7fa2250e7e13e4ac98ec519e044ce892ca508/daemon/seaf-daemon.c#L374 the DUMPS_DIR is set directly, ignoring the CCNET_CONF_DIR set as an environment variable. This causes the creation of a new folder (`ccnet`) within the user directory.

The path for the DUMPS_DIR should consider the configuration set for CCNET_CONF_DIR or provide a new configuration option.

(relates to https://github.com/lukesampson/scoop-extras/pull/4793)

**Comment by killing** [comment]
This is intentional to make it easy for the users to find dump files.
