### ISSUE TITLE
Postgres Support in 8.0?

### ISSUE THREAD

**Issue by justjanne** [haiwen/seafile#2481]
Previously, with custom migration scripts it was possible to use Seafile under Postgres.

In fact, we have our own customized docker image of Seafile where we replace the python dependencies and the migration scripts so we can run it on postgres. This has worked fine with every version of seafile until 8.0.

The error given is `2021-08-16 14:49:22 ../common/seaf-utils.c(218): Unsupported db type pgsql.` which is caused by https://github.com/haiwen/seafile-server/blob/d1e57781b5aaae1f798db9b4fa997d46414e66cb/common/seaf-utils.c#L212-L220

**Suggested Fix** Compile the seafile-server binary with postgresql, as it was in the past.

For now we’re holding out on upgrading due to this issue.

**Comment by killing** [comment]
Hi,

Unfortunately PG was never officially supported. The code was there but we don't maintain it. After a refactor of code in 7.1 or 8.0 version, the original code for PG no longer works. So we mark it as unsupported.

**Comment by justjanne** [comment]
> Hi,
> 
> Unfortunately PG was never officially supported. The code was there but we don't maintain it. After a refactor of code in 7.1 or 8.0 version, the original code for PG no longer works. So we mark it as unsupported.

Okay, then we’ll have to stop using Seafile, if I understand this right?
