### ISSUE TITLE
Force ccnet listenning on local ip

### ISSUE THREAD

**Issue by camlafit** [haiwen/seafile#2496]
Hello

ccnet/rpc service following documentation need to listen only to local usage, then could be interresting to change behavior and listen only on 127.0.0.1
Actually I have **/seafile-server-7.1.4/seafile/bin/ccnet-server 0.0.0.0:10001** and I've added an iptables rules to restrict it :
```
iptables -A INPUT -p tcp --dport 10001 -s 127.0.0.1 -j ACCEPT
iptables -A INPUT -p tcp --dport 10001 -j REJECT
```

Could be maybe also a configuration on **/conf/ccnet.conf** with for example 
```
[Network] 
IP = 127.0.1.1
```
but as PORT is no more used, I'm not sure about this configuration suggestion.

thanks a lot

**Comment by feiniks** [comment]
Hello，may be you'd better to update seafile to 8.0.The version of 8.0 don't need ccnet.

**Comment by camlafit** [comment]
Hello

Perfect, I'll try this in next days. If it's ok I'll close this issue or provide more information.

Thanks
