### ISSUE TITLE
Why does personal account on cloud.seafile.com need weChat?

### ISSUE THREAD

**Issue by Dedsd** [haiwen/seafile#2497]
Why do you need to log in with weChat to create a personal account on cloud.seafile.com? I ended up creating an "organization" where login was better.

**Comment by Mateus-Cavalcanti** [comment]
WeChat isn't safe, neither a good application nor used in other countries... it's a massive mistake ask to people create a WeChat account to log in seafile, it isn't right. Its the same thing ask asking us to download a spyware at your mobile to log in your services. Change it.

**Comment by killing** [comment]
cloud.seafile.com is for Chinese users. It's normal to have WeChat login.

**Comment by Dedsd** [comment]
@killing So for other countries do you recomend just self hosting?
