### ISSUE TITLE
Cannot assign group on a library if not member, as Administrator

### ISSUE THREAD

**Issue by perkooo** [haiwen/seafile#2501]
On the administration page, we cannot assign a group to a library where we aren't member of.

Ex: I want to assign group **People** to the library **Welcome**, as my user isn't a member of the People group, I can't list it.
I'm only able to list the group where I am, but I'm indeed logged as Administrator.

The option "ENABLE_SHARE_TO_ALL_GROUPS" fixes it but all simple users will have the possibility.
Only the administrator should be able to do this with the option disabled.

**Comment by perkooo** [comment]
Up

**Comment by freeplant** [comment]
You can use the department feature. A department is a special group that admins can add members and add libraries in the admin panel. The added libraries are belong to the department.

For normal groups, a library must belong to a specific user.
