### ISSUE TITLE
Markdown - Collaborative edition

### ISSUE THREAD

**Issue by JeanLouPtflbx** [haiwen/seafile#2502]
Hi,
I would be so nice to have collaborative edition on markdown documents, any chance to see that in roadmap for 9.0 ?

Thanks

**Comment by killing** [comment]
Currently we have no plan to add this feature.

**Comment by freeplant** [comment]
Markdown cannot support collaborative editing due to the format restriction.

**But**, you can use sdoc format for collaborative editing in Seafile v11.
