### ISSUE TITLE
Seafile Desktop Client error

### ISSUE THREAD

**Issue by ALBERTANGalbert** [haiwen/seafile#2503]
Hi,

Always face with this issue. what are the possible causes, and how can we overcome them.

Please advice.
![image (2)](https://user-images.githubusercontent.com/93034296/138551729-66425ec8-102f-4c51-b2d7-b0283517b783.png)

Regards,

**Comment by killing** [comment]
This is a limitation in Windows. Paths longer than 256 characters cannot be handled. You should shorten your paths.
