### ISSUE TITLE
I cannot upload more than 1000 files at once

### ISSUE THREAD

**Issue by mawi675lr81** [haiwen/seafile#2509]
Just setup seafile with nginx and docker. I am not able to upload more than 1000 files at once. It gives me error "Please upload no more than 1000 fiiles at a time". 

How do I circumvent this and upload as many files as I want?

**Comment by killing** [comment]
This limit is hard code and cannot be changed. If you upload too many files you should use the client instead. There are limitations in the web browser.

**Comment by PrzemekSkw** [comment]
Hi, @killing I just install Seafile with docker and also have that problem.
I try copy to my `/home/user/Seafile` folder but it don't sync with my server - nothing happen.
Then I just drag to library folder to my client window, whole folder that have more than 1000 files and it start copying but after a while it stops.
When I drag to main window to sync that folder I have error: `The file path contains symbols that not supported by Windows system`

There's no way to just copy my files in linux terminal?
Regards.
