### ISSUE TITLE
[Feature] - Auto update of client

### ISSUE THREAD

**Issue by viktorlindgren** [haiwen/seafile#251]
Hi

A way to automatic update the client when new releases comes. 

What is the best way to do this? I specfic looking for this feature for windows,

Edit: I found that one can install it using:
msiexec /passive /quiet /i seafile-1.6.1-en.msi

I could easily implement the above with a python script. Would you include it then?

**Comment by tvollstaedt** [comment]
+1, just adding a automatic download / execution of the MSI file would add a lot more comfort and match up "modern" application designs.
