### ISSUE TITLE
Seadav try to access

### ISSUE THREAD

**Issue by tome9111991** [haiwen/seafile#2510]
Hello.
After hours i get to work my seafiele and seahub.
I install on my ubuntu server 20.04 with apache2 with installations script.
After install some pip3 modules it works so far.
Is there a documentation whats pip3 modules i need?

Ok but main main issue ist.
I try to access seafile via seadav/webdav
But if i open the URL via webbrowser i got this:
![20211108_145739](https://user-images.githubusercontent.com/57866234/140755893-e79854f3-d274-427d-af38-4cf30ce44fc1.jpg)

With a Webdav client i cant connect.

Seafdav.conf
```
[WEBDAV]
enabled = true
port = 8189
share_name = /seadav
```

Apache2 Vhost.conf
```
<VirtualHost *:443>
    ServerName tld.domain.de
  
    SSLProxyEngine On
    AllowEncodedSlashes On

    RewriteEngine On

    <Location /media>
        Require all granted
    </Location>
    
  # WCGI  / PROXY
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
ProxyPass /seadav https://127.0.0.1:8189/seadav
ProxyPassReverse /seadav https://127.0.0.1:8189/seadav


    #
    # seafile fileserver
    #
    ProxyPass /seafhttp https://127.0.0.1:8082
    ProxyPassReverse /seafhttp https://127.0.0.1:8082
    RewriteRule ^/seafhttp - [QSA,L]

    #
    # seahub
    #
    SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
      ProxyPreserveHost On
       ProxyPass / https://127.0.1.1:8000/
    ProxyPassReverse / https://127.0.1.1:8000/





		
		SSLEngine on
		SSLCertificateFile ....

		SSLCertificateKeyFile .......

		SSLCertificateChainFile .......

</VirtualHost>
```

Anyone an idea what the issue is?

**Comment by tome9111991** [comment]
Maybe i found the issue.

The proxypass dosent work with a subdomain.

I have add
```
<Location /seadav>
        ProxyPass "https://127.0.0.1:8189/seadav"
    </Location>
```

to main vhost.conf like domain.de

Is there a workaround to use seadav with a subdomain?

**Comment by killing** [comment]
I think this is a configuration issue. You may ask on the forum. Github is for bug reporting.

**Comment by tome9111991** [comment]
I Switch to ngnix works great.
