### ISSUE TITLE
Building from source: is ccnet-server required?

### ISSUE THREAD

**Issue by olof-nord** [haiwen/seafile#2516]
Hello Seafile Team!

I am trying to build seafile from source.
Currently following this guide:
https://manual.seafile.com/develop/env/

I have seen in [other issues](https://github.com/haiwen/seafile/issues/2496#issuecomment-940768882), that `ccnet-server` is not required for v8.

Is the guide up to date, or are there any other information available for building from source?

I cannot use the prebuilt binaries or docker images as I am using the risc-v architecture, for which there are neither images nor prebuilt binaries.

Many thanks in beforehand!

**Comment by feiniks** [comment]
Hello, this document can still be used, but when building version 8.0, you don't need to compile and install ccnet, and there are no other changes.

**Comment by olof-nord** [comment]
Thanks for the feedback!

In the quest of building, I do have a followup question.

I am wondering if there is any further information to the `seaf-server -c conf -d conf/seafile-data -f -l -` command. When executed, I simply get a `Segmentation fault (core dumped)`.

I understand that the `seaf-server` takes two arguments (seaf-server [-c config_dir] [-d seafile_dir]), but what I am wondering is what the last few arguments are for. (the `-f -l -` part). Is there a good way to debug this segmentation fault further? Any log files, or verbose mode possible? (or the place in the source code where the parameters are interpreted)?

If it is to any help, my full log output looks like this:
```log
$ seaf-server -c conf -d conf/seafile-data -f -l -
2021-12-10 23:30:55 ../common/seaf-utils.c(333): Use database Mysql
2021-12-10 23:30:55 http-server.c(192): fileserver: worker_threads = 10
2021-12-10 23:30:55 http-server.c(206): fileserver: fixed_block_size = 8388608
2021-12-10 23:30:55 http-server.c(221): fileserver: web_token_expire_time = 3600
2021-12-10 23:30:55 http-server.c(236): fileserver: max_indexing_threads = 1
2021-12-10 23:30:55 http-server.c(251): fileserver: max_index_processing_threads= 3
2021-12-10 23:30:55 http-server.c(273): fileserver: cluster_shared_temp_file_mode = 600
Segmentation fault (core dumped)
```

**Comment by feiniks** [comment]
Hello，you can generate a coredump, and then use gdb to debug the issue.

**Comment by olof-nord** [comment]
Thanks for the feedback!

I will close this issue for now, as my initial question was answered.
