### ISSUE TITLE
[Feature request] Notification for Desktop Drive Client version updates

### ISSUE THREAD

**Issue by sherryrshk** [haiwen/seafile#2517]
Hi,

There is no notification for desktop drive client version updates. And, when we click "Check For Updates", it will always show "You're up to date! Seafile Drive Client X.X.XX is currently the newest version available" even though it's not. 

Will you add a pop up notification for drive client version updates?

**Comment by sherryrshk** [comment]
Hi,

There is no notification for desktop drive client version updates. And, when we click "Check For Updates", it will always show "You're up to date! Seafile Drive Client X.X.XX is currently the newest version available" even though it's not.

Will you add a pop up notification for drive client version updates?

**Comment by sherryrshk** [comment]
![image (2)](https://user-images.githubusercontent.com/95728911/148872760-a0e58e2e-11c4-4e23-948c-6acd5d9c7c46.png)

**Comment by killing** [comment]
We no longer update the latest client version on our notification server. So you have to check new versions manually on our website.
