### ISSUE TITLE
seafile go fileserver prevents sync of virtual repos

### ISSUE THREAD

**Issue by mbosner** [haiwen/seafile#2518]
After upgrading to 9.0.2 i enabled the go fileserver. In first place everything seems to be fine but then some people told me that they have failed sync tasks (server error) on their desktop sync clients.

On the server i see a lot of these messages (i reduced some parts of the ids):

``2021/12/15 18:07:29 path /repo/-e6b5-45f1-bce3-a69172b57f2c/fs-id-list/ internal server error: Failed to get fs id list: Failed to find dir -e6b5-45f1-bce3-a69172b57f2c:2e6eacf3049334da7eed9a6713e13a34c598
2021/12/15 18:10:41 path /repo/-e6b5-45f1-bce3-a69172b57f2c/fs-id-list/ internal server error: Failed to get fs id list: Failed to find dir -e6b5-45f1-bce3-a69172b57f2c:2e6eacf3049334da7eed9a6713e13a34c598
2021/12/15 18:10:41 path /repo/-e368-435d-94b2-8facf0bef5ab/fs-id-list/ internal server error: Failed to get fs id list: Failed to find dir -e368-435d-94b2-8facf0bef5ab:f505b1b301947c11fdceef41b06c14d3889b
2021/12/15 18:11:02 path /repo/-e223-4dd2-8e22-dc51485f7012/fs-id-list/ internal server error: Failed to get fs id list: Failed to find dir -e223-4dd2-8e22-dc51485f7012:00ca98112881f3ecef124abf34bfe6444f6s
``

After switching back (removing go server switch in the config file) everything starts working again. It does not effect all shared virtual repos.

If you need more information please drop me a comment.

Server: ubuntu 18.04.6
Desktop:  Mac OS (11.x and 12.x) Desktop Clients with client versions 8.0.4 and 7.0.x

**Comment by feiniks** [comment]
Hello, through this log, I think it may be that go fileserver does not support the version of the fs object. This fs object may be created by the previous version of seafile, you can use the new version of the server to shar virtual repos to see if this issue still exists.

**Comment by mbosner** [comment]
I cannot recreate the library with its content since there are hundreds of shared directories. So technically it is possible but the afford to do so is just too much. Any way i can convert the fs to the latest generation?

**Comment by feiniks** [comment]
Hello,I will re-check this issue, I think this may be a bug for sharing virtual repos using go fileserver.

**Comment by TheCloneMaster** [comment]
I had a similar issue, upgraded to 9 from 7.3, and everithing went smooth... until I enabled the go fileserver...
After that, trying to share repos failed, and in the fileserver.log it showed "Failed to get fs id list: failed to call dir callback: request canceled"
Turned off the go server, and everything started working again...

**Comment by Dan-Sun** [comment]
I have similar problems. From time to time I get this error just for one repo which has around 300gb.
Turning off the go server doesn't work either. I might need to reupload it again, which I already did a month ago, but I'm going to disable the go server straight away. Hopefully it'll help.

**Comment by killing** [comment]
It's fixed in newer versions.
