### ISSUE TITLE
IMAP Authentication

### ISSUE THREAD

**Issue by ghost** [haiwen/seafile#252]
Hi,

is the Authentication against an IMAP-Server planned as feature for a future release?

Best wishes,
André

**Comment by vascorppor** [comment]
I'm facing the same problem. Is there some way to implement an own authentication provider?

**Comment by andresnnn** [comment]
Any news on this request? :)

**Comment by freeplant** [comment]
We don't have a plan to add the support yet.

**Comment by corradofiore** [comment]
I would be interested in sponsoring the development of this feature.  If interested, please contact me privately and I'll be happy to discuss.

**Comment by shoeper** [comment]
@freeplant

**Comment by freeplant** [comment]
We have already implemented many authentication methods over the years.. The feature (IMAP) is not interested by most of the users. It will not be implemented.
