### ISSUE TITLE
Docker image seafile:latest doesn't point to the latest version

### ISSUE THREAD

**Issue by ArnoNuyts** [haiwen/seafile#2521]
The latest-tag in docker hub is not up-to-date. At the moment it points to version 8.0.7 although 8.0.8 and 9.0.2 are published.

![image](https://user-images.githubusercontent.com/16191147/146903111-72ab8b21-a3c6-44cf-99e0-d01a40fa3e89.png)

**Comment by darrencrossley** [comment]
This is still a problem with v9.0.3 and is especially annoying as the docker-compose referenced in the manual here: 
https://manual.seafile.com/docker/pro-edition/deploy_seafile_pro_with_docker/#download-and-modify-docker-composeyml
 uses the latest tag and therefore pulls the v8 image.

This makes the entire setup invalid as for example it pulls the v8 image tagged :latest and the docker-compose specifies a standard elasticsearch v7 image meaning search doesn't work correctly (there may be other problems too).
