### ISSUE TITLE
ModuleNotFoundError: No module named 'seaserv'

### ISSUE THREAD

**Issue by munrobasher** [haiwen/seafile#2524]
Upgrading from Pro v8.0.14 to v8.0.16 following maintenance release process of running **./minor-upgrade.sh**. Seafile starts fine but on starting Seahub, I get this error:

```
# ./seahub.sh start    

LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub at port 8000 ...
Traceback (most recent call last):
  File "/data/seafile/seafile-pro-server-8.0.16/check_init_admin.py", line 19, in <module>
    from seaserv import ccnet_api
ModuleNotFoundError: No module named 'seaserv'

```
Running on a Hyper-V VM running Centos v7.9. Supplemental note: upgrade to to v8.0.15 works fine but then fails with same error when doing next upgrade to v8.0.16

**Comment by killing** [comment]
This is likely a configuration issue. Please re-post usage questions on our forum.
