### ISSUE TITLE
Script install for seafile version 9 on Ubuntu 20 gives internal server error

### ISSUE THREAD

**Issue by GogoFC** [haiwen/seafile#2530]
I used this https://github.com/haiwen/seafile-server-installer

Version 8 works fine on Ubuntu 20

Version 9 gives error. Installed fine and server runs on localhost, but 
![Screenshot 2022-01-16 172005](https://user-images.githubusercontent.com/9360410/149668716-1205b1eb-13b7-4b5a-9450-c3373eee1501.png)

**Comment by GogoFC** [comment]
Closing. docker-compose version 1.29.2 works fine. Thanks for awesomeness :)

**Comment by papahausa** [comment]
The same error.
Clean ubuntu 20.04, seafile 9.0.0 
Internal Server Error

**Comment by GogoFC** [comment]
I never figured that one out, looks like Nginx settings. I just moved away to docker versions.

**Comment by papahausa** [comment]
> I never figured that one out, looks like Nginx settings. I just moved away to docker versions.

can u send installation link with docker?

**Comment by GogoFC** [comment]
https://manual.seafile.com/docker/deploy_seafile_with_docker/
