### ISSUE TITLE
Python version check error

### ISSUE THREAD

**Issue by hydrogenium2020** [haiwen/seafile#2533]
when i using python 3.10,it doesn't work and showed "The current version of python is not 3.x.x, please use Python 3.x.x .".I found where the problem appened finally.Just the checker only thinks python has one point number.Here is the code.
`function check_python_executable() {
    if [[ "$PYTHON" != "" && -x $PYTHON ]]; then
        return 0
    fi

    if which python3 2>/dev/null 1>&2; then
        PYTHON=python3
    elif !(python --version 2>&1 | grep "3\.[0-9]\.[0-9]") 2>/dev/null 1>&2; then
        echo
        echo "The current version of python is not 3.x.x, please use Python 3.x.x ."
        echo
        exit 1
    else
        PYTHON="python"$(python --version | cut -b 8-10)
        if !which $PYTHON 2>/dev/null 1>&2; then
            echo
            echo "Can't find a python executable of $PYTHON in PATH"
            echo "Install $PYTHON before continue."
            echo "Or if you installed it in a non-standard PATH, set the PYTHON enviroment varirable to it"
            echo
            exit 1
        fi
    fi
}`

**Comment by imwhatiam** [comment]
Hello.

Do you have `python3` command on your server ?

What is the output of `python --version` ?

**Comment by eisengrau** [comment]
Can confirm the same on my end as well.
`sh-5.1# python --version
Python 3.10.10`
