### ISSUE TITLE
[9.0.2] & [9.0.4] - login_id is not set in the API of Add User

### ISSUE THREAD

**Issue by BloodOfPanda** [haiwen/seafile#2540]
Summary: login_id is not set in the API of Add User.
Version: 9.0.2

Try: curl -X POST -d "email=aaabbb@666aaabbb.com&password=aaabbb&login_id=666" -H "Authorization: Token MYTOKEN" -H 'Accept: application/json; charset=utf-8; indent=4' "https://cloud.example.de/api/v2.1/admin/users/"

Response:
{
    "email": "aaabbb@666aaabbb.com",
    "name": "aaabbb",
    "contact_email": "",
    "login_id": "", <- Is empty
    "is_staff": false,
    "is_active": true,
    "reference_id": "",
    "quota_usage": 0,
    "quota_total": -2,
    "create_time": "2022-01-29T07:53:56+00:00",
    "has_default_device": false,
    "is_force_2fa": false,
    "role": "default",
    "add_user_tip": "Successfully added user aaabbb@666aaabbb.com."
}

**Comment by PandaBLN** [comment]
In version 9.0.4 the error is still present.

**Comment by imwhatiam** [comment]
Hello, we don't support set `login_id` when sysadmin create user.

You can update user's `login_id` by this web api: https://download.seafile.com/published/web-api/v2.1-admin/accounts.md#user-content-Update%20User%20Info

**Comment by BloodOfPanda** [comment]
I have also realized this via the update. However, the documentation also says that you can also realize this with the Add User.
