### ISSUE TITLE
CFFI version 1.15 causes crashes, but there is a workaround

### ISSUE THREAD

**Issue by jeffmikels** [haiwen/seafile#2543]
The latest version of python `cffi` is 1.15, but seahub will crash if that version is installed. Furthermore `cffi` 1.14 will not build on certain systems (my Archlinux system running python 3.10).

Workaround: by deleting the cffi library from `seahub/thirdpart` seahub will start just fine.

Perhaps cffi can be removed from the thirdpart directory?

**Comment by killing** [comment]
You can use docker to install Seafile, to avoid such problems.
