### ISSUE TITLE
System Admin covered by menu on mobile devices

### ISSUE THREAD

**Issue by twx99** [haiwen/seafile#2547]
Using webgui on a phone. Navigating to System Admin. The left menu covers almost the entire screen. Touching outside of it does not close it.

https://user-images.githubusercontent.com/8458093/155257238-170d9650-1594-4ea2-8c48-5aa2973e47ce.MOV

Tries on IOS. Same thing in Safari and Firefox, both latest versions to date.

**Comment by Nine-Tailed** [comment]
Confirm on android in Chrome

**Comment by freeplant** [comment]
The problem will be fixed in version 10.0.
