### ISSUE TITLE
Predictable random numbers used

### ISSUE THREAD

**Issue by mtausig** [haiwen/seafile#2556]
The `ClientID` in the Seadrive code [is generated][1] by using the predicable random number generator `srand`. Since other parts rely on this number being unguessable for security purposes, this call needs to be replaced with a CSRPNG (Cryptographically Secure Pseudo Random Number Generator) e.g., `getrandom()` on Linux and `BCryptGenRandom()` on Windows.

[1]: https://github.com/haiwen/seadrive-gui/blob/8a1e459f1c42a24eec6fcce482398bebf6459e1c/src/seadrive-gui.cpp#L812

**Comment by killing** [comment]
This ID is not used in security related context. So it's not necessary to use strong random number.

**Comment by mtausig** [comment]
I would still suggest to make the change, as it is neither a complicated nor an expensive change but might still prevent future security issues.
