### ISSUE TITLE
Failed to configure Let's Encrypt with Docker installation

### ISSUE THREAD

**Issue by edebernis** [haiwen/seafile#2560]
Hello,

I am using the docker-compose.yml file to install Seafile on linux server. When setting environment variable ```SEAFILE_SERVER_LETSENCRYPT=true```, I get the following error :

    seafile | 2022-03-22 12:19:49 Nginx ready
    seafile | 2022-03-22 12:19:49 This is a idle script (infinite loop) to keep container running.
    seafile | Certificate will expire
    seafile | fatal: remote error:
    seafile | The unauthenticated git protocol on port 9418 is no longer supported.
    seafile | Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
    seafile | [2022-03-22 12:19:49] Preparing for letsencrypt …
    seafile | [2022-03-22 12:19:49] Found existing cert file /shared/ssl/************.crt
    seafile | [2022-03-22 12:19:49] Starting letsencrypt verification
    seafile | Traceback (most recent call last):
    seafile | File “/scripts/start.py”, line 86, in
    seafile | main()
    seafile | File “/scripts/start.py”, line 51, in main
    seafile | init_letsencrypt()
    seafile | File “/scripts/bootstrap.py”, line 80, in init_letsencrypt
    seafile | call(’/scripts/ssl.sh {0} {1}’.format(ssl_dir, domain))
    seafile | File “/scripts/utils.py”, line 70, in call
    seafile | return subprocess.check_call(*a, **kw)
    seafile | File “/usr/lib/python3.8/subprocess.py”, line 364, in check_call
    seafile | raise CalledProcessError(retcode, cmd)
    seafile | subprocess.CalledProcessError: Command ‘/scripts/ssl.sh /shared/ssl *****************’ returned non-zero exit status 1.

Thanks for your help !

**Comment by HTSpecOps** [comment]
see below topic. you probably need to manually edit the script file
https://github.com/haiwen/seafile-docker/issues/290
