### ISSUE TITLE
Clarify that ElasticSearch is only relevant in Pro Edition in upgrade-to-9.0.x docs

### ISSUE THREAD

**Issue by nidico** [haiwen/seafile#2561]
The [Upgrade notes for 9.0](https://manual.seafile.com/upgrade/upgrade_notes_for_9.0.x/) mention that ElasticSearch needs to be updated and some lines need to be added to `seafevents.conf`.

As I don't have a `seafevents.conf` file in my Community Edition and the docs hint that this is only relevant in the Pro Edition, I got suspicious, [asked in the forum](https://forum.seafile.com/t/seafevents-conf-in-community-edition/16201/3) and got the answer that ES is (most likely) only relevant in the Pro Edition.

So if this is confirmed, I'd suggest to:

- Clarify in the [Upgrade to 9.0 release notes](https://manual.seafile.com/upgrade/upgrade_notes_for_9.0.x/) that the ES part is only relevant for Pro Edition users, same for the `seafevents.conf` part.

- Add an introducing note in the [seafevents.conf config option docs](https://manual.seafile.com/config/seafevents-conf/) that this is only relevant for the Pro Edition.

**Comment by freeplant** [comment]
The document has been updated. Thanks for the suggestion.
