### ISSUE TITLE
Seadrive-gui 2.0.21 Cmake build error in archlinux

### ISSUE THREAD

**Issue by Hydrogenium2022** [haiwen/seafile#2562]
https://github.com/haiwen/seadrive-gui CMakeLists.txt:618 `QT5_USE_MODULES(seadrive-gui ${USE_QT_LIBRARY})` USE_QT_LIBRARY should be  replaced to USE_QT_LIBRARIES in archlinux, qtdiag version info `Qt 5.15.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 11.2.0) on "xcb"`

**Comment by killing** [comment]
Thanks for pointing out. We'll fix it.
