### ISSUE TITLE
Image thumbnails not generated

### ISSUE THREAD

**Issue by SizerSong** [haiwen/seafile#2568]
Hi
When I open an image in the seafile, it says ”The image could not be loaded“.
when i check seahub.log, i found:
```
[ERROR] seahub.thumbnail.utils:149 generate_thumbnail cannot identify image file <StringIO.StringIO instance at 0x7f49f8c41c20>
```

The png file was 13000*9600 pixel and 39.4Mb.
Seafile version: seafile-server-7.0.5(docker)
Seafile searver OS: Debian 10

**Comment by killing** [comment]
Please post on the forum for usage questions or configuration problems.
