### ISSUE TITLE
[Feature request] WebAuthn

### ISSUE THREAD

**Issue by BirdInFire** [haiwen/seafile#2572]
Do you think you can add a Passwordless connection only user (like nextcloud but actually let us "disable" the password connection).

Seafile is more secure than nexcloud (since your E2E work unlike their), so maintaining your "advace" on them by adding that can be very useful.

And since Apple, Microsoft, Google, have annonced bring it in the year "into their own account/OS" adding this can prevent some "sucurity first" user of your to move to them for more passwordless.

thanks !!

**Comment by killing** [comment]
What do you mean by passwordless connection only user?

**Comment by BirdInFire** [comment]
> What do you mean by passwordless connection only user?

enter our username / email, and instead of using password, it ask us a webauth enabled connection (usb key, internel key of the os) etc.

Since one or two version nextcloud propose it, so hoped to see it on seafile too "connection only" mean (for me) letting the admin of the instance "force" that on all user (by disabling the user/password connection).

And it reduce code on the client side (open a web page auth in the browser) and the client is connected.

So the client doesn't have to implement "connection code"

**Comment by m4k5ym** [comment]
I'd recommend changing the issue topic to "[Feature Request] WebAuthn".

More clearly and quicker to identify.
