### ISSUE TITLE
Is there a way to specify an upload file size limit for web browser only?

### ISSUE THREAD

**Issue by zldrobit** [haiwen/seafile#2577]
In the manual, there are two options for upload size limits:
```
[fileserver]
# Set maximum upload file size to 200M.
# If not configured, there is no file size limit for uploading.
max_upload_size=200

# Set maximum download directory size to 200M.
# Default is 100M.
max_download_dir_size=200
```

As I understand, these two options are for both web browsers and the seafile client. Is there a way to specify an upload file size limit for web browser only? So users are forbidden to upload large files (e.g. 2GB) in web browsers, while they could upload large files with a client.

**Comment by killing** [comment]
The cloud file browser in the sync client uses the same API as web browsers to upload files. So they're subject to the same restriction. The restriction is technical and won't be changed. If users want to upload large files, they should use file syncing or SeaDrive client.
