### ISSUE TITLE
Go fileserver: Folder or File is not deletable when there is a spurious utf-8 char inside the filename.

### ISSUE THREAD

**Issue by kiorky** [haiwen/seafile#2584]
Env: Seafile 9.0.4 + mariadb  (docker) + Go fileserver ON.

For the next examples, `é` is not the regular `é`, (another utf8 char), so please copy and paste the name to reproduce the bug

Ex : (USE FileSystem drag'drop, with online creation the bug does not occur)
- Create folders: `a` and inside `a`: `a/b`, `a/c`
    - In `b`, Create a folder named `Tés_test1_eaccentuated_is_not_regular` with a file `toto.md` inside.
    - In `c`, Create a folder `toto` with inside a file named `Tés_test1_eaccentuated_is_not_regular.md`.
    ```
    mkdir a a/b a/c 'a/b/Tés_test1_eaccentuated_is_not_regular' 'a/c/toto'
    for i in "a/c/toto/Tés_test1_eaccentuated_is_not_regular.md" "a/b/Tés_test1_eaccentuated_is_not_regular/toto.md"  ;do echo 123 > "$i";done
    ```    
- Drag'n'drop this `a` folder inside your seafile test library to upload it 

- Both the folder & file `Tés_test1_eaccentuated_is_not_regular` wont be deletable  (it will say "OK" but both they will soon "reappear").  

In any of those case, the GrandParents folders `b`, and `c` can be deleted without problem

**Comment by kiorky** [comment]
The problem does not occur with the classical C based fileserver (the uploaded files are deletable).

If we switch back to the C fileserver, the broken accentued folder and file are still not deletable.

**Comment by feiniks** [comment]
Hello, this issue will be fixed in the next release.
