### ISSUE TITLE
iOS photo upload bugs

### ISSUE THREAD

**Issue by erikboberg** [haiwen/seafile#2585]
Hi!
Thank you for a wonderful application! I am using it to sync files between several computers and it is fast and has a super nice history feature. 

The problem I have is with photo sync from my iphone. It frequently stops syncing new photos even though I have background upload turned on. If I turn photo upload off and on again I can make the upload start but then it starts to upload all the 2200 photos on my iphone again even though they are already in the folder on the server.

**Comment by Spaenny** [comment]
Having the same issue on 2.9.19 App and Server 9.0.7.

**Comment by JannSchulte** [comment]
Same here.

**Comment by freeplant** [comment]
It should have been fixed in the latest iOS client.
