### ISSUE TITLE
Updating/Removing SeaDrive Client with GPO

### ISSUE THREAD

**Issue by superwinni2** [haiwen/seafile#2587]
Hello

I would like to Update and/or to remove  Seafile with GPOs.
It doesn't work because of all the message boxes like "Would you like to uninstall the product?" or "Would you like to delete the informations for your SeaDrive Account?"
Is there a way to set the boxes via MsiExec.exe ?

Thanks and Greetings

**Comment by killing** [comment]
You can refer to this FAQ: https://help.seafile.com/faq/
