### ISSUE TITLE
Windows 11 Beta version22622.590 File Explorer Extension Not Working

### ISSUE THREAD

**Issue by szw0407** [haiwen/seafile#2603]
All icons are just shown without any difference. The file explorer extension is not working properly. No sync status can be seen.

**Comment by killing** [comment]
You can follow this FAQ: https://cloud.seatable.io/dtable/external-links/7b976c85f504491cbe8e/?tid=78wK&vid=0000&row-id=BVxTix6QQi2EGRLqFv5d2g

**Comment by szw0407** [comment]
However, when I use Everything(an application) to search the folders, the icons are just correct with a green ✓. Perhaps Windows 11 22H2 has a different way of showing icons in explorer.exe . Thus, please look into the problem.

**Comment by killing** [comment]
Everything may have its own way to show the icon. But explorer.exe stays the same.
