### ISSUE TITLE
Please give a file upload/download status dashboard

### ISSUE THREAD

**Issue by szw0407** [haiwen/seafile#2604]
When uploading large files or many files, we cannot know how much has been uploaded and how much is still to be done.
Please give a window which shows things like:
---File sync status---
FILE 1: ---_____100kB/1024kB
FILE 2: -_______20MB/1.2GB
......
1.3KB/s  114514  seconds left

**Comment by killing** [comment]
For sync client it's not possible to implement this feature. It's already implemented in SeaDrive.
