### ISSUE TITLE
In-browser Markdown editor does not save file 

### ISSUE THREAD

**Issue by yhtang** [haiwen/seafile#2611]
When I'm using the built-in Markdown editor, it frequently happens that the editor would indicate the file has been successfully saved, even though the login to the server has actually expired. As a result, the file was **NOT** saved although the UI indicates otherwise. This has caused a loss of work several times for me.

**Comment by killing** [comment]
This should be a problem on your server, but not in the code. You can check your log files for error messages and post on the forum.
