### ISSUE TITLE
Docker: Why not using latest version of mariadb and memcached?

### ISSUE THREAD

**Issue by KeenMaron** [haiwen/seafile#2613]
Hello,

I'm just wondering why the docker-compose.yml contains specific versions for mariadb (10.5) and memcached (1.6)?

https://download.seafile.com/d/320e8adf90fa43ad8fee/files/?p=/docker/docker-compose.yml

Is there any risk to use always the latest docker version of mariadb and memcached?

**Comment by freeplant** [comment]
You can use a newer version by modifying the version in docker-compose.yml. However, the latest version may not have been tested with Seafile.
