### ISSUE TITLE
pro (docker image): acme.sh no longer working, bad permissions for /var/www/.well-known

### ISSUE THREAD

**Issue by draeath** [haiwen/seafile#2617]
I pulled fresh container images today and Let's Encrypt integration is now broken.

I have narrowed this down to the children of `/var/www/.well-known` being owned by root:root with directory modes 0750. Files are 0644, so that's fine. It appears that `/scripts/ssl.sh` sets the correct permissions, but (I'm unable to figure out where) after this, they are being reset.

This causes nginx to be unable to serve the challenge file, resulting in a verification failure (HTTP 404).

I have attempted to add `umask 022` into `/root/.acme.sh/acme.sh.env` such that www-data could still read the content, but this does not help, so somewhere it seems to be explicitly setting or changing the permissions. (I did this via `docker exec -it seafile bash` then re-tested by running `/scripts/ssl.sh /shared/ssl REDACTED-FQDN` from inside the same shell environment)

    root@6182e4892272:~# ~/.acme.sh/acme.sh --version
    https://github.com/acmesh-official/acme.sh
    v3.0.2

Affected docker image: `docker.seadrive.org/seafileltd/seafile-pro-mc` (`8e7379629efc`)

    [root@ip-10-172-2-121 shared]# docker image inspect docker.seadrive.org/seafileltd/seafile-pro-mc:latest
    [
        {
            "Id": "sha256:8e7379629efcd056c553ff51363fbf1fdc65c6609c31b716e89ca9001a6d3ff9",
            "RepoTags": [
                "docker.seadrive.org/seafileltd/seafile-pro-mc:latest"
            ],
            "RepoDigests": [
                "docker.seadrive.org/seafileltd/seafile-pro-mc@sha256:66fb88e97333ece86a4fba664897fb9bbd74f6f49d38840193e50c01e10e50f4"
            ],
            "Parent": "",
            "Comment": "",
            "Created": "2022-11-04T06:48:45.705310129Z",
            "Container": "14751c8eb3b1685a1efc250c18bf68bc6604578c62e4ad561f6876397b4f8b5a",
            "ContainerConfig": {
                "Hostname": "14751c8eb3b1",
                "Domainname": "",
                "User": "",
                "AttachStdin": false,
                "AttachStdout": false,
                "AttachStderr": false,
                "ExposedPorts": {
                    "80/tcp": {}
                },
                "Tty": false,
                "OpenStdin": false,
                "StdinOnce": false,
                "Env": [
                    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                    "DEBIAN_FRONTEND=teletype",
                    "LANG=en_US.UTF-8",
                    "LANGUAGE=en_US:en",
                    "LC_ALL=en_US.UTF-8",
                    "SEAFILE_SERVER=seafile-pro-server",
                    "SEAFILE_VERSION=9.0.12"
                ],
                "Cmd": [
                    "/bin/sh",
                    "-c",
                    "#(nop) ",
                    "CMD [\"/sbin/my_init\" \"--\" \"/scripts/enterpoint.sh\"]"
                ],
                "Image": "sha256:71a7fb1f16fc14f8ca01a90299822a6a0d0ba37d3f909e0e22282a3382694c68",
                "Volumes": null,
                "WorkingDir": "/opt/seafile",
                "Entrypoint": null,
                "OnBuild": null,
                "Labels": {}
            },
            "DockerVersion": "20.10.8",
            "Author": "",
            "Config": {
                "Hostname": "",
                "Domainname": "",
                "User": "",
                "AttachStdin": false,
                "AttachStdout": false,
                "AttachStderr": false,
                "ExposedPorts": {
                    "80/tcp": {}
                },
                "Tty": false,
                "OpenStdin": false,
                "StdinOnce": false,
                "Env": [
                    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                    "DEBIAN_FRONTEND=teletype",
                    "LANG=en_US.UTF-8",
                    "LANGUAGE=en_US:en",
                    "LC_ALL=en_US.UTF-8",
                    "SEAFILE_SERVER=seafile-pro-server",
                    "SEAFILE_VERSION=9.0.12"
                ],
                "Cmd": [
                    "/sbin/my_init",
                    "--",
                    "/scripts/enterpoint.sh"
                ],
                "Image": "sha256:71a7fb1f16fc14f8ca01a90299822a6a0d0ba37d3f909e0e22282a3382694c68",
                "Volumes": null,
                "WorkingDir": "/opt/seafile",
                "Entrypoint": null,
                "OnBuild": null,
                "Labels": null
            },
            "Architecture": "amd64",
            "Os": "linux",
            "Size": 2708114989,
            "VirtualSize": 2708114989,
            "GraphDriver": {
                "Data": {
                    "Dataset": "seafile/docker/5ee88df372b0f226b9d9004ddce36a34ad278f5331c8f4439e1338f4154e2fbe",
                    "Mountpoint": "/zpools/seafile/docker/zfs/graph/5ee88df372b0f226b9d9004ddce36a34ad278f5331c8f4439e1338f4154e2fbe"
                },
                "Name": "zfs"
            },
            "RootFS": {
                "Type": "layers",
                "Layers": [
                    "sha256:ccdbb80308cc5ef43b605ac28fac29c6a597f89f5a169bbedbb8dec29c987439",
                    "sha256:63c99163f47292f80f9d24c5b475751dbad6dc795596e935c5c7f1c73dc08107",
                    "sha256:2f140462f3bcf8cf3752461e27dfd4b3531f266fa10cda716166bd3a78a19103",
                    "sha256:facb372d15a2803dbfa9ad07a61a285259921d00fa1dfd321fa70bc33cce7568",
                    "sha256:4e9f53ea2e18e61785192741422c9b51ff992fbfca3c2ddbb2d61b5daad91d5f",
                    "sha256:3b6418367581c8d72dcc18256d286a3598a8d30acb2aa66b98dc9b06a6b0f652",
                    "sha256:3fc68fbce3bd76c84b21ee57c524d50da7c685eab78d421e63f8b5a06e3e5ad8",
                    "sha256:9697e26dd8c8afb8ec9765c68b454c73333a0dc4cff5b108858a955571a9937c",
                    "sha256:c40098459e2e118702aa20961c19738eae0e9884d78a7b37433f362923289577",
                    "sha256:e91720e772e7cd4971d76a7ab530e71d276c8c80936d92e2b1f6550b04f46034",
                    "sha256:bc2879052f5647bc673985bb8ea37fa7e21d350eab34e052c27ca9faa26826e4",
                    "sha256:6df4cd9836d4d70e11d3c79721b47cba743293116f07a76eba4812859972380f",
                    "sha256:abab884245c565128bd2fa6c3d034543c331e45c646132c398c280023bfc727e",
                    "sha256:bbaf910dca7cf7043369cf805897b534d4f01f2637e7e3dc409ec8b5a99ad51d",
                    "sha256:b19b8e08e55d64e8975202acd1b6247d83065a3d48b2e09e548a3e113bb47a35",
                    "sha256:b17c4493552e4ff6ee2e78fa8aee79e5f16586bee68e8944de6872bd3ed1a09d",
                    "sha256:3978ebcf27cc3e7ae7d707061aa6412121f4a71dcbd208f54246d027cce60253",
                    "sha256:6ecf3c7b5f648fef92d78eefb7384d6e6d8e386e8a8d67994f9fd0789dd63708",
                    "sha256:71fa6393860b89f3cb684d9f3236d9f9105b9d1b75f4c3f8f50219af7a702ff5",
                    "sha256:337f98d01be30e41cade1b611c2ce5560a202049fae2ef4e241c69f14ce86687",
                    "sha256:1546e2cc9a4f7f3d4d704719873ee610d6c71601bd5727137b36ca04c533ccb0"
                ]
            },
            "Metadata": {
                "LastTagTime": "0001-01-01T00:00:00Z"
            }
        }
    ]

In the meantime, my existing LE cert is valid for another couple of weeks, so I've just switched `SEAFILE_SERVER_LETSENCRYPT` to false in my docker compose YAML.

**Comment by draeath** [comment]
As a workaround I am using certbot on the host, and I have attached a python script I slapped together in certbot's renewal timer's service so that it runs after the renewal is processed.

If anyone else runs into this, you might find this an inspiration. The only non-standard python module is the [docker SDK](https://pypi.org/project/docker/). It was written for Python 3.6 but should run on later versions just fine.

Be forewarned, this code is ugly as hell and is most certainly provided here as a suggestion. It seems to work for me, _but it might well destroy your server._

```python
#!/bin/env python3

# syncs certificate files from /etc/letsencrypt on host into the shared path, and if the container is running and any of the certs changed, reloads nginx inside the container.
#
# this could be written better, but i just wanted it done fast. if needed i can rewrite later.
# this whole thing is because of https://github.com/haiwen/seafile/issues/2617


import hashlib
import sys
from os import umask
from pathlib import Path
from functools import lru_cache
import docker


key_file = {
    "s": Path("/etc/letsencrypt/live/REDACTED-FQDN/privkey.pem"),
    "d": Path("/zpools/seafile/seafile/shared/ssl/privkey.pem"),
    "differ": None,
}
cert_file = {
    "s": Path("/etc/letsencrypt/live/REDACTED-FQDN/fullchain.pem"),
    "d": Path("/zpools/seafile/seafile/shared/ssl/fullchain.pem"),
    "differ": None,
}


umask(0o22)


# utility function I stole from StackExchange ages ago, just a print() wrapper that goes to STDERR.
def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


@lru_cache(maxsize=32)
def hexdigest(path):
    with open(path, "rb") as input_file:
        try:
            return hashlib.blake2b(input_file.read()).hexdigest()
        except FileNotFoundError:
            return ""


@lru_cache(maxsize=32)
def get_container(name="seafile"):
    try:
        docker_client = docker.from_env()
        container = docker_client.containers.get(name)
        if container.status != "running":
            raise RuntimeError("Unable to validate container runtime status.")
        return container
    except Exception as e:
        eprint("Something is wrong with the container!")
        eprint(e)
        try:
            docker_client.close()
        except Exception:
            pass
        return None


def main():

    seafile_container = get_container()

    for file in [key_file["s"], cert_file["s"]]:
        if not file.is_file():
            eprint(f"Source file '{str(file)}' is not a file!")
            sys.exit(2)  #  No such file or directory

    we_changed_a_file = False
    for file_pair in [key_file, cert_file]:
        file_pair["differ"] = hexdigest(file_pair["s"]) != hexdigest(file_pair["d"])
        if file_pair["differ"]:
            with open(file_pair["s"], "rb") as input_file, open(
                file_pair["d"], "wb"
            ) as output_file:
                output_file.write(input_file.read())
                we_changed_a_file = True

    if seafile_container and we_changed_a_file:
        reload_status = seafile_container.exec_run(
            "/usr/sbin/nginx -s reload", demux=True
        )
        if reload_status.exit_code != 0:
            exit_code = reload_status.exit_code
            stderr = reload_status.output[1]
            if stderr is None:
                stderr = ""
            else:
                stderr = stderr.decode()
            stdout = reload_status.output[0]
            if stdout is None:
                stdout = ""
            else:
                stdout = stdout.decode()
            eprint("Something went wrong when reloading nginx in the container!")
            raise RuntimeError(
                {
                    "container_exit_code": exit_code,
                    "container_stderr": stderr,
                    "container_stdout": stdout,
                }
            )


if __name__ == "__main__":
    main()
```

... and the systemd overrides:

```text
[root@ip-10-172-2-121 ~]# cat /etc/systemd/system/certbot-renew.service.d/update-certs-script.conf
[Service]
ExecStartPost=-/zpools/seafile/seafile/update-certs/venv/bin/python3 /zpools/seafile/seafile/update-certs/update_certs.py
```

**Comment by SkywalkerSpace** [comment]
Thanks for your feedback. The reason is that the folder owner  (www-data)  is reset when cron is executed. The solution is to set the folder owner to root and permissions to 755

**Comment by draeath** [comment]
Hi. Thanks for the response.

I want to note that is one of the first things I tried when I figured out what was going on.

The permissions are reset somewhere during the process. It doesn't seem to matter what I set them to, they will be changed.

**Comment by SkywalkerSpace** [comment]
```
mkdir -p /var/www/.well-known/acme-challenge/
chmod 755 /var/www/.well-known/acme-challenge/
```

`drwxr-xr-x root root acme-challenge/`

After testing, executing the above command, acme.sh --renew will not reset the folder permissions.

**Comment by fph** [comment]
I am affected by this bug, too.

[SkywalkerSpace's workaround](https://github.com/haiwen/seafile/issues/2617#issuecomment-1314933576) works as a manual workaround, but still executing `/scripts/ssl.sh` fails, possibly because it uses `acme.sh --create` rather than `acme.sh --renew` and does different things with permissions.

**Comment by draeath** [comment]
It is now a year later :/

**Comment by SkywalkerSpace** [comment]
We have fixed [ssl.sh](https://github.com/haiwen/seafile-docker/blob/master/scripts_9.0/ssl.sh) in seafile-docker.

**Comment by draeath** [comment]
Thank you!
