### ISSUE TITLE
Seafdav : renaming files with space in directory names doesn’t work

### ISSUE THREAD

**Issue by thoka** [haiwen/seafile#2619]
Quoting flobiree:

I’m using Seafile 9.0.8, and I have a problem with the webdav access to the files (the webdav client is Nextcloud).

The problem appears when I try to rename a file inside the webdav client, only when there is a least on space in the name of the library or in the name of one directory of the path of the file (no problem if there is a space in the name of the file). If no spaces in the library or directories names, it works.

see https://forum.seafile.com/t/seafdav-renaming-files-with-space-in-directory-names-doesnt-work/16950

**Comment by imwhatiam** [comment]
@thoka Hello, I wasn't able to reproduce this issue locally. I think it may be a problem with the Nextcloud WebDAV client you're using, as this client performs an additional URL encoding step. Could you try using a different WebDAV client to see if you can rename successfully?

**Comment by thoka** [comment]
Hm. I'm using davfs.

I solved the issue using a different docker-image: 
https://github.com/ggogel/seafile-containerized
