### ISSUE TITLE
[BUG] Data loss: local changes overwritten and lost after sync 

### ISSUE THREAD

**Issue by yhtang** [haiwen/seafile#2620]
I have a markdown file saved in my Seafile folder and keep editing it throughout the day. At around 5 pm, the file suddenly reverted by Seafile to a previous version dated around 2 pm.  No version history can be found between 2 to 5 pm on the web interface, even though my text editor has an autosave feature that checkpoints every few seconds. As such, my three hours of work are now nowhere to be found.

**Comment by feiniks** [comment]
Hello, if you can't find version history during this time,  the file was not uploaded to the server. Maybe you can check seafile.log between 2 to 5 pm.

**Comment by yhtang** [comment]
> Hello, if you can't find version history during this time,  the file was not uploaded to the server. Maybe you can check seafile.log between 2 to 5 pm.

This is probably true. However, what is not understandable is why the file was rolled back to its last synced state at 5 pm. Shouldn't the Seafile client at least create a 'conflict' file if it was going to overwrite anything?

**Comment by feiniks** [comment]
> > Hello, if you can't find version history during this time,  the file was not uploaded to the server. Maybe you can check seafile.log between 2 to 5 pm.
> 
> This is probably true. However, what is not understandable is why the file was rolled back to its last synced state at 5 pm. Shouldn't the Seafile client at least create a 'conflict' file if it was going to overwrite anything?

When the client updates a locally modified file that has not been uploaded, a conflict file will be generated, so in your case it may be that the editor's auto-save does not take effect, so the local modification is not uploaded.
