### ISSUE TITLE
"Unknown error" and failure to upload folders and multiple files at once in both Web UI and Seafile Client

### ISSUE THREAD

**Issue by kirisakow** [haiwen/seafile#2632]
(This is a duplicate of an unresponded Dec 7 2022 issue, https://forum.seafile.com/t/unknown-error-and-failure-to-upload-folders-and-multiple-files-at-once-in-both-web-ui-and-seafile-client/17281)

I have a managed instance of Seafile running on a Ubuntu 22.10 and Nginx reverse proxy, installed with Docker Compose (`seafile-mc:latest`, `mariadb:10.5`, `memcached:1.6`), which works — except for a sync fail with an "Unknown error" message which occurs on uploading either folders or multiple files, with both Web UI and Seafile Client for Linux.

I can provide any log or config file.

**Comment by kirisakow** [comment]
Finally I found the solution here: https://forum.seafile.com/t/unknown-erorr-and-server-error-status-syncing-libraries-since-seafile-server-ce-7-0-5/10777/2

1. Outside the container, add `client_max_body_size 0;` to every `server { ... }` block of the Nginx config file for the reverse proxy. Normally there are two such server blocks: one for port 80 and one for port 443.
2. Test Nginx config and, if no error is found, restart Nginx: `sudo nginx -t && sudo systemctl restart nginx.service`

**Comment by trb** [comment]
@kirisakow Thank you so much for posting your solution here, I ran into the same issue and did not find the forum post. Your update here really helped me out.
