### ISSUE TITLE
Wrong unsync behaviour on windows

### ISSUE THREAD

**Issue by santo74** [haiwen/seafile#2633]
On linux, when syncing an encrypted libary, the library folder is made accessible on the filesystem and when unsyncing it again, it's removed completely from the filesystem. This is expected behaviour.

But on windows, when you unsync it again, the folder remains accessible in the local filesystem (but it doesn't sync any changes anymore).
This doesn't seem correct and not in line with the behaviour on linux.

Edit: This is related to the SeaDrive client.

**Comment by freeplant** [comment]
This is because SeaDrive Linux client use FUSE interface while Windows client using a different technology.
