### ISSUE TITLE
8.0.10: notif-mgr.c:726:5: error: 'LWS_PROTOCOL_LIST_TERM' undeclared here (not in a function)

### ISSUE THREAD

**Issue by draeath** [haiwen/seafile#2634]
I am attempting to build the following for RHEL8 using gcc-toolset-12 and am experiencing the following build error. Note I am not a RH employee or Fedora maintainer, I am doing this locally for my own use.

    notif-mgr.c: At top level:
    notif-mgr.c:726:5: error: 'LWS_PROTOCOL_LIST_TERM' undeclared here (not in a function)
      726 |     LWS_PROTOCOL_LIST_TERM
          |     ^~~~~~~~~~~~~~~~~~~~~~

The struct in question:

    static const struct lws_protocols protocols[] = {
        { "notification.seafile.com", event_callback, 0, 0, 0, NULL, 0 },
        LWS_PROTOCOL_LIST_TERM
    };

- https://src.fedoraproject.org/rpms/libsearpc/tree/cbcd95b942facc949268a95163c568dd615aeaa0
- https://src.fedoraproject.org/rpms/seafile/tree/9536e3f47b65c6699257a1a348862fe58b53bf82
- https://src.fedoraproject.org/rpms/seafile-client/tree/7a6e9214ce0cb7cab3bc81d2ae0cf793d2a34270

----

This object appears to not be present in the version of libwebsockets I have available (4.0.1) and the required version of this does not appear to be documented anywhere.

Please amend documentation to include this or amend usage so that (presumably) older versions of the library may be used.

**Comment by draeath** [comment]
libwebsockets-4.3.2 satisfies this dependency it seems, though versions prior to but newer than 4.0.1 may also suffice.

**Comment by jhonny-oliveira** [comment]
I'm also facing the same issue in Ubuntu Jammy (libwebsockets 4.0.20) and Kinetic (libwebsockets 4.1.6). Is there a way to workaround (patch) without using (libwebsockets 4.3.2)?
