### ISSUE TITLE
Error during open empty Markdownfile 

### ISSUE THREAD

**Issue by canchanchara** [haiwen/seafile#2636]
I cannot open an empty markdown file in, see gif in attachment, depending on the "view". If I change the view, it works.

![open empty markdown](https://user-images.githubusercontent.com/47896059/211806343-e0d97c41-793e-4a37-92e2-cb27f3a6532d.gif)

Seafile version 9.0.10
Browser: Firefox 108

**Comment by freeplant** [comment]
The problem will be fixed in version 10.0.

**Comment by GhaziTriki** [comment]
Hello,

In seafile 12.0.14 you cannot edit empty markdown. I guess it is related to seadoc. Any fix for 12.0.15 ?
