### ISSUE TITLE
2FA forced + SSO leads to redirect loop

### ISSUE THREAD

**Issue by mkretzer** [haiwen/seafile#2637]
We are currently using Seafile with LDAP + Seafile 2FA. For external users we also have local seafile-internal users. 

We now want to replace LDAP with SSO via Azure AD (OAuth) which works well as long as "force 2FA" is not active. But since we still have seafile-internal users we still need "force 2FA" for those users.

When we enable "force 2FA" after login we get a redirect loop:
/profile/two_factor_authentication/setup/ -> /profile/two_factor_authentication/backup/tokens/ -> /profile/two_factor_authentication/setup/ and so on after SSO login (tokens are already existing for that user).

With SSO 2FA should be disabled automatically for the SSO users, but not for local seafile users.

**Comment by freeplant** [comment]
The bug will be fixed in version 10.0, where 2FA will not be used when login via SSO.

**Comment by mkretzer** [comment]
We tried it, but problem is not fixed. However, we found a way to make it work - maybe this can be included in the official v10 release?

Changed line 92:

```
if ENABLE_FORCE_2FA_TO_ALL_USERS or UserOptions.objects.is_force_2fa(user.username):
    return HttpResponseRedirect(reverse('two_factor:setup'))
```

to:

```
if (ENABLE_FORCE_2FA_TO_ALL_USERS or UserOptions.objects.is_force_2fa(user.username)) and not request.session.get('is_sso_user'):
    return HttpResponseRedirect(reverse('two_factor:setup'))
```

in seahub/two_factor/middleware.py

**Comment by imwhatiam** [comment]
@mkretzer Hello, the issue you encountered is because you set up mandatory two-factor authentication for users when using LDAP. When switching to SSO, you did not cancel mandatory two-factor authentication for these users. The code changes you submitted can solve this problem, and we will merge them into the next version.

**Comment by suslovweb** [comment]
This still exists on some custom oauth servers.
request.session.get('is_sso_user') could be None in seahub/oauth/views.py oauth_callback function.
Shouldn`t we add request.session['is_sso_user'] = True like following? 


`   line 203

    request.user = user

    auth.login(request, user)

    request.session['is_sso_user'] = True
`
