### ISSUE TITLE
Potential memory leak in seafile/daemon/seafile-session.c

### ISSUE THREAD

**Issue by rachyyyy** [haiwen/seafile#2639]
Potential memory leak in [seafile-session.c](https://github.com/haiwen/seafile/blob/master/daemon/seafile-session.c) line 189. Calling event_base_new() in line 189 without calling event_base_free() to free the memory will cause a memory leak. [Doc](https://libevent.org/doc/event_8h.html#a91f9deb12c37f2ff586e65e8b9a46641) says "event_base_free() deallocates all memory associated with an [event_base](https://libevent.org/doc/structevent__base.html), and free the base."
![image](https://user-images.githubusercontent.com/57169201/212619222-6046c18a-42ef-478b-af4e-a48d6630cd68.png)

**Comment by killing** [comment]
This is just a one-time loss. So it won't harm.
