### ISSUE TITLE
Almalinux/Rocky Linux Support

### ISSUE THREAD

**Issue by darkdecoy** [haiwen/seafile#2640]
I know that Centos used to be a supported operating system but was dropped in Seafile 9.0.  I was wondering whether you would consider Almalinux or Rocky Linux as a replacement for Centos?  Thanks.

**Comment by brianclemens** [comment]
+1 for Rocky Linux, I'm obviously biased but I need to get around to migrating a Seafile server off a CentOS 7 machine.

**Comment by freeplant** [comment]
Since version 9.0, we recommend a docker based deployment. This will significantly reduce supporting and testing work on our side.
