### ISSUE TITLE
Deprecated feature is not marked as deprecated in the manual

### ISSUE THREAD

**Issue by mikob** [haiwen/seafile#2641]
When you google "seafile encryption" you get this help page: 

https://manual.seafile.com/deploy_pro/seaf_encrypt/

but it seems this feature is deprecated (as it states here: https://manual.seafile.com/deploy_pro/migrate/#decrypting-encrypted-storage-backend) so there should be a warning on that page. And perhaps a link to the encrypted libraries part of the manual.

**Comment by freeplant** [comment]
Thanks for the notification. I have add a deprecated notice.
