### ISSUE TITLE
How do I delete tags?

### ISSUE THREAD

**Issue by henryk-radoslaw-rychlik** [haiwen/seafile#2644]
Hello,

I have been using Seafile for a while and started using tags recently.

The problem is, I don't seem to find a way to delete an existing tag from a tag list. Can you help? What am I missing? Tried web and seafile-client.

**Comment by Michael18811380328** [comment]
Hey, you can press "Tags" in the drop down menu, then click on the selected tag again to remove this tag, just like this.
![tags](https://user-images.githubusercontent.com/37589122/224944013-48a17668-08ea-421b-8178-9a52588b362d.gif)

**Comment by feiniks** [comment]
Hello, if you want to delete the tag itself, you can click on the position on the picture to delete it.
<img width="317" alt="企业微信截图_ec760e54-7081-4554-aa53-f0b96420d68c" src="https://user-images.githubusercontent.com/36756310/224974540-ce42c433-ef8a-44bc-8a9c-472cc2d56048.png">
