### ISSUE TITLE
Create library endpoint documentation

### ISSUE THREAD

**Issue by bastiencyr** [haiwen/seafile#2647]
Hello, 

I post an issue here because it doesn't seem that there is an official repo for the documentation. Feel free to move this issue.

Server information: {"version": "9.0.12", "encrypted_library_version": 2, "features": ["seafile-basic", "seafile-pro", "office-preview", "file-search"]}
Curl version: 7.85.0 (x86_64-pc-linux-gnu)

The documentation about creating library at https://download.seafile.com/published/web-api/v2.1/libraries.md#user-content-Create%20Library is inconsistent with the example. 
The endpoint is "POST ﻿[https://cloud.seafile.com/api2/repos/](https://cloud.seafile.com/api/v2.1/repos/)" but the curl command uses api version 2.1.
 
Moreover, the curl command for the version 2.1 doesn't work for me :
```shell
curl -d "repo_name=new_repov2.1" -H 'Authorization: Token  ********************' -H 'Accept: application/json; indent=4' https://seafile.cloud.fr/api/v2.1/repos
```

However, the old version works very well but is not documented at all:
```shell
curl -d "name=new_repov2" -H 'Authorization: Token  **************' -H 'Accept: application/json; indent=4' https://seafile.cloud.fr/api2/repos/?from=web
```

**Comment by freeplant** [comment]
The document has been fixed.
