### ISSUE TITLE
API documentation seems to contain errors

### ISSUE THREAD

**Issue by unalignedcoder** [haiwen/seafile#2648]
For example, If I want to get the details of a file, according to the documentation I have to enter:

`curl -H 'Authorization: Token f2210dacd3606d94ff8e61d99b477fd' -H 'Accept: application/json; charset=utf-8; indent=4' https://cloud.seafile.com/api2/repos/dae8cecc-2359-4d33-aa42-01b7846c4b32/file/detail/?p=/foo.c`

the above however doesn't work; it returns the 404 html message of the seafile front-end.

After a lot of poking around, I figured that the correct request doesn't have the "/detail" part in it:

`curl -H 'Authorization: Token f2210dacd3606d94ff8e61d99b477fd' -H 'Accept: application/json; charset=utf-8; indent=4' https://cloud.seafile.com/api2/repos/dae8cecc-2359-4d33-aa42-01b7846c4b32/file/?p=/foo.c`

As I'm trying to build my own system to keep files in sync with Android via automation (given how the Android client cannot do its most basic job), I'll update this thread when/if I find more mistakes...

**Comment by unalignedcoder** [comment]
The api to get a download link for a file, really retrieves the details of the file, as shown in the first post above:

`curl  -v  -H 'Authorization: Token f2210dacd9c6ccb8133606d94ff8e61d99b477fd' -H 'Accept: application/json; charset=utf-8; indent=4' 'https://cloud.seafile.com/api2/repos/dae8cecc-2359-4d33-aa42-01b7846c4b32/file/?p=/foo.c&reuse=1'`

I have no idea how to get the download link via API. 
The "smart link" seems to work, although there is no explanation what that is.

**Comment by imwhatiam** [comment]
> For example, If I want to get the details of a file, according to the documentation I have to enter:
> 
> `curl -H 'Authorization: Token f2210dacd3606d94ff8e61d99b477fd' -H 'Accept: application/json; charset=utf-8; indent=4' https://cloud.seafile.com/api2/repos/dae8cecc-2359-4d33-aa42-01b7846c4b32/file/detail/?p=/foo.c`
> 
> the above however doesn't work; it returns the 404 html message of the seafile front-end.
> 
> After a lot of poking around, I figured that the correct request doesn't have the "/detail" part in it:
> 
> `curl -H 'Authorization: Token f2210dacd3606d94ff8e61d99b477fd' -H 'Accept: application/json; charset=utf-8; indent=4' https://cloud.seafile.com/api2/repos/dae8cecc-2359-4d33-aa42-01b7846c4b32/file/?p=/foo.c`
> 
> As I'm trying to build my own system to keep files in sync with Android via automation (given how the Android client cannot do its most basic job), I'll update this thread when/if I find more mistakes...

Hello, which version of Seafile are you using?

I you use the latest 9.0.x version, you can get file detail via this two web api

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/3793639/221073507-8e587449-db89-4bbd-88b4-25c7759bc0d7.png">
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/3793639/221073713-9bda3869-f1da-458d-bc9a-1272eae3cf5b.png">

**Comment by imwhatiam** [comment]
`https://your-seafile-domain/api/v2.1/admin/libraries/{repo_id}/dirents/?parent_dir={parent_folder_path}` can works too.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/3793639/221076068-a05ed7c5-3aa9-4f20-ba5c-5fdc0bc24568.png">

**Comment by imwhatiam** [comment]
`https://your-seafile-domain/api2/repos/{repo_id}/file/?p={file_path}&reuse=1`

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/3793639/221077270-84ac8f3a-0171-4f72-bdcc-9ed33492ad3c.png">
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/3793639/221077293-e455d457-23df-4174-8a68-7a881cfc11bd.png">

**Comment by unalignedcoder** [comment]
> @unalignedcoder
> 
> Hello, which version of Seafile are you using?
> 
> I you use the latest 9.0.x version, you can get file detail via this two web api
> 
> `https://your-seafile-domain/api2/repos/{repo_id}/file/detail/?p={file_path}`
> 
> <img alt="image" width="1439" src="https://user-images.githubusercontent.com/3793639/221073507-8e587449-db89-4bbd-88b4-25c7759bc0d7.png">
> 
> `https://your-seafile-domain/api/v2.1/repos/{repo_id}/file/?p={file_path}`
> 
> <img alt="image" width="1426" src="https://user-images.githubusercontent.com/3793639/221073713-9bda3869-f1da-458d-bc9a-1272eae3cf5b.png">

The first one doesn't work, returns the 404 web error page.

**Comment by unalignedcoder** [comment]
using `/api2/` definitely returns different results from `/api/v2.1/`
My bad I didn't notice this detail.

However, here is what 

> for `https://your-seafile-domain/api2/repos/{repo_id}/file/?p={file_path}&reuse=1`
> 
> <img alt="image" width="1433" src="https://user-images.githubusercontent.com/3793639/221077270-84ac8f3a-0171-4f72-bdcc-9ed33492ad3c.png">
> 
> <img alt="image" width="1429" src="https://user-images.githubusercontent.com/3793639/221077293-e455d457-23df-4174-8a68-7a881cfc11bd.png">

using `/api2/` definitely returns different results from `/api/v2.1/`
I guess this is my bad, because I hadn't noticed this detail, so this seems to be at the origin of my mistakes. 
Or did you just make this change in the documentation? Funny because I copied-pasted all directives.

> for `https://your-seafile-domain/api2/repos/{repo_id}/file/?p={file_path}&reuse=1`
> 
> <img alt="image" width="1433" src="https://user-images.githubusercontent.com/3793639/221077270-84ac8f3a-0171-4f72-bdcc-9ed33492ad3c.png">
> 
> <img alt="image" width="1429" src="https://user-images.githubusercontent.com/3793639/221077293-e455d457-23df-4174-8a68-7a881cfc11bd.png">


using `/api2/` definitely returns different results from `/api/v2.1/`

I hadn't noticed this detail, so this seems to be at the origin of my mistakes. 
Or did you just make this change in the documentation? Because I thought I had copied-pasted all directives. Anyway, thank you for the help.
