### ISSUE TITLE
use_go_fileserver = true results uploading error in web

### ISSUE THREAD

**Issue by lilarcor** [haiwen/seafile#2652]
docker version 9.0.10
added "use_go_fileserver = true" into seafile.conf, I found files are not uploading or stuck at saving from web , sometimes stopped at 20% or 70%. Removed  "use_go_fileserver = true" from config file solved this issue.

**Comment by feiniks** [comment]
Hello, through the development mode of the browser, can you see that the request returns an error? Are there any errors reported in seafile.log and fileserver.log?
