### ISSUE TITLE
I can't upload files to encrypted library by api token 

### ISSUE THREAD

**Issue by anarchical** [haiwen/seafile#2656]
I generated a api token in encrypted library，I hope to upload files to the encrypted library.
![image](https://user-images.githubusercontent.com/35455406/224216697-efff9e05-b7f7-482e-808a-c88e4e620a74.png)
But I got `Internal error`
![image](https://user-images.githubusercontent.com/35455406/224217278-21f9fa47-361f-40fe-99f1-cb2c7febadfb.png)

But I can do that for a unencrypted library

# I hope to upload files to an encrypted library by api token, please tell me how to do that.

**Comment by anarchical** [comment]
![image](https://user-images.githubusercontent.com/35455406/224268695-6f474d09-cb60-4276-9931-65e9a083dd90.png)
An error occurred because the password was not set
But it looks like no way to set password by api token call，at least the api documentation doesn't

**Comment by feiniks** [comment]
Hello, you need to enter the password of the encrypted library in the web UI. Then use the api to upload files.

**Comment by anarchical** [comment]
> Hello, you need to enter the password of the encrypted library in the web UI. Then use the api to upload files.

However, if I do this, I need a username and password for the login operation to obtain the login token, not the library api token

**Comment by feiniks** [comment]
Hello, the encrypted library will only allow access to the content after entering the password, so before the password is not entered, it cannot be uploaded through the token of the library, which is a limitation of the encrypted library.

**Comment by anarchical** [comment]
> Hello, the encrypted library will only allow access to the content after entering the password, so before the password is not entered, it cannot be uploaded through the token of the library, which is a limitation of the encrypted library.

Ok, I made the call like you said, thanks~
