### ISSUE TITLE
Mac client notifications dissapear quickly, not visible in notification center

### ISSUE THREAD

**Issue by GeorgFleig** [haiwen/seafile#2661]
Hi,

I've recently switched from Linux to Mac and I'm struggling with the notifications from the Seafile client. On Linux I was used to the notifications being visible for a few seconds and then being placed in the notification center of my system. On Mac they are also visible for a few seconds but then disappear completely. I am not able to see them in the notification center afterwards (where all other notifications of my chat and mail clients are listed).

I tried different notification settings in my system, also changing the type from banner to alert, but they still disappear within seconds. This is makes it hard to track changes done by me or others in my libraries. As the notification center works for all other apps I suspect this is an issue of the seafile client. Or am I missing something?

Or is there another way to track changes in my libraries?

- Seafile client versions tested: 8.0.10, 9.0.1
- MacOS Ventura 13.2.1

**Comment by killing** [comment]
We'll have a look at this issue. I remember it works for older versions of macOS.

**Comment by rumtid** [comment]
Hi, GeorgFleig. Thanks for the reporting.

I've tested the notifications of Seafile client on macOS, and they do disappear after a few seconds. It is expected since a timeout parameter will be set along with notifications.

Also, there is a "Activities" tab in Seafile client that shows recent file changes.

**Comment by GeorgFleig** [comment]
Thanks for taking a look at this @rumtid! Is there a downside of not sending a timeout parameter along with the notification? Any other notifications I receive from my browser, mail client or other apps show up for a few seconds, then disappear but I can see them all in the notification center until I clear them there. To me this is the most convenient way and seems to be common behavior for other apps. Would be great if the Seafile client did the same.

You mentioned the "Activities" tab in the Seafile client. I double checked my MacOS client and also updated to the latest version (9.0.3), but I am unable to find the activities tab 🤔  I only see the libraries and favorites tabs (see attached screenshot). Am I looking in the wrong place?

<img width="507" alt="Screenshot 2023-07-12 at 15 51 43" src="https://github.com/haiwen/seafile/assets/11178272/c6d61320-6a33-4ac2-849d-0ac43ec3d921">

Thank you!

**Comment by rumtid** [comment]
> To me this is the most convenient way and seems to be common behavior for other apps. Would be great if the Seafile client did the same.

The suggestion is quite reasonable. We'll consider it.

> I only see the libraries and favorites tabs (see attached screenshot). Am I looking in the wrong place?

You're looking in the right place. However the "Activities" tab requires a Pro-edition server. Library changes can also be found at Seafile Web without requiring the Pro-edition server. ([Library History and Snapshots](https://help.seafile.com/file_folder_managing/library_history_and_snapshots/))
<img width="418" alt="截屏2023-07-20 14 24 40" src="https://github.com/haiwen/seafile/assets/3798047/71245d08-3fd8-473a-a28d-2d0bacf2176f">

**Comment by GeorgFleig** [comment]
Thanks for considering removing the timeout of the notification.

So far the free edition of the server was sufficient for me. Setting up pro for just the activities tab feels a bit overkill to me at the moment. I appreciate the hint with the activities view in the web UI. However it would require me to have the tab open and look at it regularly. Therefore I hope the timeout change will make it to the client at some time in the future :)

Out of curiosity: I've never looked at the source code of the desktop client. Would you be open for a PR in case I manage to find the right place in the code and change it myself?
