### ISSUE TITLE
applet won't synchronize: not enough RAM

### ISSUE THREAD

**Issue by ilka-schulz** [haiwen/seafile#2669]
My Seafile Applet under Windows 10 won't synchronize and says:

> Nicht genüngend Arbeitsspeicher

(engl.: not enough RAM)

The device has 16 GB RAM with 8 GB available and 1 GB free. Does Seafile perhaps confuse free with available RAM?

### Seafile version
8.0.6 under Windows 10 (64 bit)

The share contains 239549 files and is 32.3 GiB large.

**Comment by feiniks** [comment]
Hello @ilka-schulz , can you screenshot where this error is displayed? In addition, is there any error in seafile.log?

**Comment by ilka-schulz** [comment]
I restarted the device and Windows installed some updates. After the reboot, Seafile claimed that no shares are synchronized. I deleted the synchronized directory from the disk and resynchronize now. It seems to work. It looks to me like this can only be a workaround.

btw: I encountered quite a few bugs in Seafile on the way:
- Seafile claims that it cannot synchronize bc the path "is already used by the system".
- Seafile claims some network error which I cannot remember even though there were no network issues.

I'll come back to this issue as soon as I re-encounter the bug...

**Comment by ilka-schulz** [comment]
> Seafile claims that it cannot synchronize bc the path "is already used by the system".

I rebooted again and Seafile broke the sync again. I click `Download and synchronize` *again*, choose `use an existing directory` and select the existing partially synced directory. When I click OK to sync again, Seafile says:

> Download konnte nicht eingerichtet werden:
> Der Pfad "C:/MEasurement Data " [sic! with an additional space] wird bereits vom System verwendet

engl.:
> Download could not be established
> The path "C:/MEasurement Data " [sic! with an additional space] is already used by the system

**Comment by feiniks** [comment]
Hello @ilka-schulz, this system path conflict error is because the directory you are synchronizing has an inclusiveness with the path of seafile system path, for example, this directory is the parent directory or subdirectory of the seafile-data directory or worktree directory. You'd better change a directory to sync.
