### ISSUE TITLE
seaf-fsck deletes existing files

### ISSUE THREAD

**Issue by VanLampe** [haiwen/seafile#2682]
Hi,

I just executed the seaf-fsck.sh script to check corrupted libraries.

The command output showed some corrupted files e.g.:

`Repo[xxx] file /path/img.jpg(35f07b83) is damaged.`

Via web ui the file could be shown and downloaded correctly without any errors.

After running the `seaf-fsck.sh` with the `repair` option, the "corrupted" file was removed or recreated with an empty file:

`file /path/img.jpg(35f07b83) is damaged, recreate an empty file`

After that the file/image was completely broken and could not be recovered.

Why does the script show such files as damaged, although they are obviously retrievable intact? How can I protect such files from being simply overwritten with an empty file?

Thanks and best regards,
Frank

**Comment by VanLampe** [comment]
Running the command with the `-s/--shallow` option does not report any damaged files. Could anyone please explain the difference?

**Comment by feiniks** [comment]
Hello @VanLampe , the` --shadow` option does not check the integrity of the block. When the blocks of the file are damaged, this option will not report the damage of the file because it does not check the block.
