### ISSUE TITLE
wrong url for avatar url (again)

### ISSUE THREAD

**Issue by t-h2o** [haiwen/seafile#2689]
# Avatar URL not secure

> I found a similar problem into this issue: https://github.com/haiwen/seafile/issues/2204

All my connection with the server are secure but not with the avatar...

Firefox try a `GET` on
```
http://subdomain.example.com/media/avatars/7/9/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resized/72/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.png
```

> I dislike send screenshot, was there another solution ?

On this screenshot, we can see, all connections are secure but not the one with the avatar.

![devtool-issue-seafile](https://github.com/haiwen/seafile/assets/90759286/21c9df98-a330-4e3f-b82a-bf192b5c86ca)

### Server version

> I found this information in about (down/left) on the web page

I'm using the `Server Version: 10.0.1` with docker image.

### Docker-compose

I use a custom port to run the docker image

```yaml
seafile:
  image: seafileltd/seafile-mc:latest
  container_name: seafile
  ports:
    - "${CUSTOM_PORT}:80"
```

### Environment variables

Environment variable of the container:

* disable let's encrypt
* set a domain name

```
SEAFILE_SERVER_LETSENCRYPT=false
SEAFILE_SERVER_HOSTNAME=subdomain.example.com
```

### Nginx

I give the whole nginx configuration because I do not wich part is important

```nginx
server {
  server_name subdomain.example.com;
  client_max_body_size 0;

  proxy_set_header X-Forwarded-For $remote_addr;

  location / {
    proxy_pass     http://127.0.0.1:${CUSTOM_PORT};

    proxy_set_header Host $host;

    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Host $server_name;
    proxy_set_header   X-Forwarded-Proto https;
    proxy_read_timeout 1200s;
  }

  location /seafhttp {
    rewrite ^/seafhttp(.*)$ $1 break;
    proxy_pass http://127.0.0.1:8082;

    proxy_connect_timeout  36000s;
    proxy_read_timeout  36000s;
    proxy_send_timeout  36000s;
    send_timeout  36000s;
    proxy_request_buffering off;
  }

  location /media {
    root /srv/seafile/seafile-server-latest/seahub;
  }

  location ~ / {
    proxy_pass http://127.0.0.1:${CUSTOM_PORT};
  }

  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/subdomain.example.com/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/subdomain.example.com/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
  if ($host = subdomain.example.com) {
      return 301 https://$host$request_uri;
  } # managed by Certbot

  listen 80 ;
  server_name subdomain.example.com;
  return 404; # managed by Certbot
}
```

**Comment by t-h2o** [comment]
I cannot reproduce the error anymore

**Comment by dsiebel** [comment]
I just updated to 11.0.3 and experienced the same issue.
I'm using https://github.com/haiwen/seafile-docker, no config changes, with traefik in front, which responds to `http://` requests with a `301 Moved Permanently`. Still Firefox tells me the website is "insecure" because of that one request for my avatar.
