### ISSUE TITLE
clamav crash produces huge cloud storage traffic

### ISSUE THREAD

**Issue by publiccloudgroup** [haiwen/seafile#2696]
- clamav crashed (because of low resources)
- seafile started to increase egress traffic from cloud storage provider massively (azure, high costs, storage size ~538 GiB -> traffic in 7 days: ~1,7 TiB)
- no downloads from clients in that period of time
- after disabling clamav and restarting seafile the egress traffic from cloud storage stopped immediately
-> the reason must have been the missing/wrong clamav scan results, which forces seafile to increase scanning etc.!?

**Comment by killing** [comment]
Seafile doesn't create any traffic when running virus scan. It may due to the behavior of clamav. You can check it yourself.
