### ISSUE TITLE
clear_invalid_repo_data seems to delete *all* upload links

### ISSUE THREAD

**Issue by moschlar** [haiwen/seafile#2699]
We discovered that running clear_invalid_repo_data as described in https://manual.seafile.com/maintain/clean_database/#outdated-library-data seems to be always deleting all upload links, not just those that belong to deleted repos as expected.

From reading through the code, it isn't immediately clear to me why this could happen in the first place...

Please have a look at that.

---

Ah, it seems UserStarredFiles are being deleted, too...

**Comment by moschlar** [comment]
From some printf-debugging it seems to me that there is an issue with getting all repos in this line:
https://github.com/haiwen/seahub/blame/master/seahub/base/management/commands/clear_invalid_repo_data.py#L16

**Comment by freeplant** [comment]
Hi @moschlar,

Thanks for reporting the issue.

What make you think getting all repos have an issue?

**Comment by moschlar** [comment]
@freeplant - because when I add `print(len(self.all_repo))` I get something like 1700 where according to `/sys/info` we have 193000 :wink:

**Comment by freeplant** [comment]
@moschlar We have rewritten the script clear_invalid_repo_data to make it more reliable and more easy to debug.

https://github.com/haiwen/seahub/pull/5599
https://github.com/haiwen/seahub/pull/5604

And a `--dry-run` option has also been added. The fix will be included in version 10.0.9 pro edition.
