### ISSUE TITLE
What is mykey.peer ? What is it used for? 

### ISSUE THREAD

**Issue by bernardgut** [haiwen/seafile#2712]
What is `./seafile/ccnet/mykey.peer` ? And what is this RSA private key used for ?

Nobody seems to ever want to answer that question. There is nothing in the docs. There was a couple of threads before but the maintainers always seem to doge the question.

**Comment by feiniks** [comment]
Hello @bernardgut , `mykey.peer` is no longer in use as of seafile 7.1.
