### ISSUE TITLE
seafile 上传，分片上传

### ISSUE THREAD

**Issue by HarvestMoonNotEmpty** [haiwen/seafile#2713]
需求为，取消分片上传，通过一些ai推荐我在一些配置文件中配置 max_upload_size=0 或者在seafile.conf中配置[fileserver]
enable_upload_chunk = false,可是，配置重启之后，我上传的文件依旧是在block文件夹中，并且是分片的形式，我该如何设置能使得我上传的文件是完整的未被修改的文件呢。

**Comment by feiniks** [comment]
seafile 所有上传的文件都是分块保存的。不支持不分块。

**Comment by HarvestMoonNotEmpty** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
