### ISSUE TITLE
Seafile 11 + LDAP makes quota infinite and history endless

### ISSUE THREAD

**Issue by HenriWahl** [haiwen/seafile#2714]
Hey there,

aside thanks for a great product I use over years now I think I found an issue:

I use Seafile 11.0.1. I defined a default quota for users. As soon as I connect my Seafile instance to Active Directory, no quota at all is effective anymore and all quota limits are gone. Is this intended?

Best regards
Henri

**Edit:**  I noticed that the same applies to the default history of 30 days I set for libraries - this setting is gone too after activating LDAP authentication. Looks like the entries of seafile.conf are completely ignored?

**Comment by freeplant** [comment]
We can't reproduce the issue. Users login via LDAP will create new account in Seafile without quota settings for this specific account and the default global quota will be applied.

There is a global settings for history and no way to specify a different value for a specific user. So it should not be affected by LDAP at all.

Maybe you accidentally delete the settings in seafile.conf?

**Comment by HenriWahl** [comment]
@freeplant thanks for your fast reply.

What a magic do you use? Right now, when I wanted to show you my `seafile.conf` IT JUST WORKS! Thanks for that...
