### ISSUE TITLE
Client app main window does not update (9.0.4, on Mac OS Sonoma 14.1.1). Sync still works.

### ISSUE THREAD

**Issue by gn0rr** [haiwen/seafile#2716]
Using the Seafile client 9.0.4 on MacOS Sonoma 14.1.1 on an M1 CPU, the main window does not show any volumes, just the "waiting" animation. The actual Seafile syncing process in the background continues to work, though.

**Comment by killing** [comment]
You should check seafile.log for any errors.

**Comment by killing** [comment]
You should check seafile.log for any errors.
