### ISSUE TITLE
Ubuntu 23.04 (Lunar Lobster) not supported in APT release repository

### ISSUE THREAD

**Issue by samvv** [haiwen/seafile#2722]
I just noticed that the latest version of Seafile is not installable from the APT package repository in Ubuntu 23.04. I am not the only one. See [this thread](https://forum.seafile.com/t/seafile-client-on-ubuntu-23-04/18040) on the forum where the same issue is being discussed.

When running `sudo apt update`, I get the following result:

```
E: The repository 'https://linux-clients.seafile.com/seafile-deb/lunar stable Release' does not have a Release file.
```

There is a version of [seafile-cli](https://packages.ubuntu.com/lunar/seafile-cli) and [seafile-daemon](https://packages.ubuntu.com/lunar/seafile-daemon) available in the standard Ubuntu package repository but it is fixed at version 8.0.10.

Would it be possible to make a release for the latest Ubuntu version(s)?

**Comment by killing** [comment]
We only build official packages for LTS versions. For 23.04 you may need to wait for the updates from community or build from source code.

**Comment by samvv** [comment]
Oh ok thanks for the info.
