### ISSUE TITLE
How to get repo token for websocket notifications

### ISSUE THREAD

**Issue by FluffyDiscord** [haiwen/seafile#2725]
Hi, I am trying to subscribe to websocket file notifications to listen to file changes outside the official client. So far I found the endpoint, the `subscribe` payload, but I cannot find how I cant get the `jwt_token` for a `repo`. I found some gRPC mentions, but they all use local sockets, so I have no idea how can client get this token. I am running seafile in docker. Would you mind adding an example, please?

**Comment by killing** [comment]
We'll add documentation about the API of notification server.

**Comment by FluffyDiscord** [comment]
> We'll add documentation about the API of notification server.

I am afraid to ask - will the documentation be available by the end of this year? I would like to surprise my friends on Christmas or at lest New year.

**Comment by FluffyDiscord** [comment]
Any news please? Just a simple example/explanation would do. I think I can do the rest.

**Comment by feiniks** [comment]
> Any news please? Just a simple example/explanation would do. I think I can do the rest.

Hello @FluffyDiscord , if you have deployed seafile locally and the fileserver port is 8082, you can follow these steps to get a jwt-token:
```

1. curl -d 'username=useremail&password=password' http://127.0.0.1:8000/api2/auth-token/ Get a user token `use_token`.
2. curl -H 'Authorization: Token {user_token}' http://127.0.0.1:8000/api2/repos/{repo_id}/download-info/ Get a library sync token `repo_token`.
3. curl -H 'Seafile-Repo-Token: {repo_token}' http://127.0.0.1:8082/repo/{repo_id}/jwt-token Get jwt-token.
```

**Comment by FluffyDiscord** [comment]
Thanks! could not find the second step
