### ISSUE TITLE
Web api sometimes returns file or folder id as 0000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by FluffyDiscord** [haiwen/seafile#2726]
I am trying to use the web api to list files and directories and sometimes for no apparent reason the api returns file or directory with id 0000000000000000000000000000000000000000. The file or directory actually exists, but the is is just corrupted. Can you look at it please?

**Comment by feiniks** [comment]
> I am trying to use the web api to list files and directories and sometimes for no apparent reason the api returns file or directory with id 0000000000000000000000000000000000000000. The file or directory actually exists, but the is is just corrupted. Can you look at it please?

Hello,
file or directory with id EMPTY_SHA1 means it is an empty file or directory. It‘s normal.

**Comment by FluffyDiscord** [comment]
Does the hash change when specific file content changes? If so, how do I get the previous ID

**Comment by feiniks** [comment]
> ~Does the hash change when specific file content changes? If so, how do I get the previous ID~
> 
> I have just tested it and it's indeed a file/folder content hash. How do I know then, that the file has been changed without listening to the websocket events or listing all files in library again. Isn't there a simpler solution? I guess saving the library commit hash, comparing it and getting the diffs? The ID isn't really an ID, since it's constantly changing .

Yes, you can compare commits before and after file changes to get file changes.
