### ISSUE TITLE
./seafile.sh start boot failed

### ISSUE THREAD

**Issue by v587xpt** [haiwen/seafile#2727]
CentOS Linux release 7.4.1708 (Core)
core：3.10.0-693.el7.x86_64
seafile version：10.0.1
describe：When I started seafile，The question arose
```
[root@ndb2 seafile-server-10.0.1]# ./seafile.sh start

Starting seafile server, please wait ...
/home/system_service/seafile/seafile-server-10.0.1/seafile/bin/seafile-controller: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/system_service/seafile/seafile-server-10.0.1/seafile/lib/libcrypto.so.1.1)
/home/system_service/seafile/seafile-server-10.0.1/seafile/bin/seafile-controller: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/system_service/seafile/seafile-server-10.0.1/seafile/lib/libuuid.so.1)
Failed to start seafile server
[root@ndb2 seafile-server-10.0.1]#
```
Try to solve:
1、update GLIBC；（Maybe it wasn't updated correctly）
2、Replace the operating system；（ubuntu20 was used，But other problems arose）
3、Deploy with docker；（Launched successfully，but strangely, the web was not accessible）

Remember how simple it was to deploy seafile，ask for help.

**Comment by feiniks** [comment]
Hello @v587xpt , this should be a usage issue. Please ask in our forum.
