### ISSUE TITLE
Seafile Drive GUI continues uploading a file that was deleted.

### ISSUE THREAD

**Issue by NjlsShade** [haiwen/seafile#2731]
If I copy a large file such as a ISO over to my Seadrive Library, then decide to delete the file from my library right away before the upload process has completed for it (example situation being if I copied the file over by mistake), the Seadrive client will stage the deletion for after the upload is complete, rather than detect that the deleted file is the same as the one currently being uploaded and cancel the upload task.

Though this current functionality could be useful, as it ensures that your Seafile Trash will be completely accurate server-side, even for Seafile Drive clients, in my use case it wastes time and bandwidth. Maybe make it an option available based on the individual's needs?

OS: Fedora 39
Seadrive Client: 2.0.28
Server Version: 11.0.3

**Comment by killing** [comment]
This is a limitation in the syncing algorithm. It's not easily changed. We don't have plan to change it for now.
