### ISSUE TITLE
Setting fixed_block_size is invalid, it will always be 8M upload blocks.

### ISSUE THREAD

**Issue by SoHugePenguin** [haiwen/seafile#2737]
[fileserver]
port = 8082
fixed_block_size=100
max_indexing_threads=50
worker_threads=15
max_upload_size=2000

log:
<img width="575" alt="236fae8222beedaaf9cca1e6ae980f9" src="https://github.com/haiwen/seafile/assets/100383563/1af6aff2-da2a-4c77-bb3d-de3ad8c1183e">

web console:
<img width="240" alt="3801fba80f41656cc2ef21a4de72989" src="https://github.com/haiwen/seafile/assets/100383563/e24d2f50-634c-4c30-be38-1a2a0d7c33e6">

There are 8MB everywhere, which seriously affects upload speeds! Please note that this slows down the upload speed by at least 3 times!
as follows:

<img width="572" alt="47054b3f9a0251e92d4df400368b273" src="https://github.com/haiwen/seafile/assets/100383563/74211cfd-6df0-48f6-811d-dba55d3e912b">

**Comment by killing** [comment]
The server settings only affect how the file will be split into chunks, but not how it's uploaded. Currently there is no option to control the upload chunk size.
