### ISSUE TITLE
LDAP support does not work on Ubuntu 12.04

### ISSUE THREAD

**Issue by antaflos** [haiwen/seafile#274]
Using Seafile 1.7.0 on Ubuntu 12.04 64bit.

It seems at least `ccnet-server`is linked against libldap-2.3.so.0, but on Ubuntu 12.04 libldap is only available in version 2.4, as in `/usr/lib/x86_64-linux-gnu/libldap-2.4.so.2`.

Here's the `ldd` output:

```
$ ldd ./seafile-server-1.7.0/seafile/bin/ccnet-server
        linux-vdso.so.1 =>  (0x00007fff1fdff000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f8e3e334000)
        libevent-2.0.so.5 => /usr/lib/libevent-2.0.so.5 (0x00007f8e3e0ee000)
        libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f8e3dee9000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8e3dce5000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8e3dace000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f8e3d8ae000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f8e3d692000)
        libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f8e3d490000)
        libffi.so.5 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8e3d272000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8e3d06a000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f8e3ce0b000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f8e3cc06000)
        libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f8e3c963000)
        libsearpc.so.1 => not found
        libsearpc-json-glib.so.0 => not found
        libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f8e3c613000)
        libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f8e3c3c3000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f8e3c0ce000)
        libzdb.so.9 => not found
        libldap-2.3.so.0 => not found
        liblber-2.3.so.0 => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8e3bd0e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8e3e705000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f8e3bb05000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f8e3b8c8000)
```

As you can see there are several libraries not found but libldap and liblber are definitely not available in version 2.3 on Ubuntu 12.04.

I suspect this is why connections to our LDAP server fail entirely (they work fine using `ldapsearch` and other LDAP commandline tools). Here is the relevant (anonymised) portion of `strace`ing the ccnet process: http://apaste.info/576c, maybe it helps.

EDIT: Sorry, seems I spoke too soon. The relevant libraries are packaged with Seafile in `seafile/lib` so that shouldn't be a problem. 

This does not, however, solve the LDAP connection issues, as seen in the `strace` output.

**Comment by t4nec0** [comment]
same issue with version 4.0.6 (Linux, CentOS 7). Tried every kind of syntax (ldaps://, ldapi://, no protocol but just the server address (+port) and USE_SSL=true... no way.
The LDAP server is a 389 (Fedora Directory Server...) configured with SSL on port 636.
Copied correct CA files (and chain) in /etc/openldap/certs/ with dap.conf set as:
  TLS_CACERTDIR   /etc/openldap/certs

Non-ssl connections work, SSL ones do not.

**Comment by killing** [comment]
Have you read and tried the SSL related section in the manual?
http://manual.seafile.com/deploy/using_ldap.html

2015-02-09 20:35 GMT+08:00 t4nec0 <notifications@github.com>:

**Comment by t4nec0** [comment]
On 09/02/2015 14:09, Jiaqiang Xu wrote:
> Have you read and tried the SSL related section in the manual?
> http://manual.seafile.com/deploy/using_ldap.html

sure I did. And also tried with several workarounds/fixes proposed in
the forum/github.
I also tried mixing linux settings with AD settings.

The only thing I was not able to try is using the system libs as
proposed in the "Using TLS connection to LDAP/AD server" section of the
manual page you proposed, because the downloadable bundle of seafile for
linux generic (4.0.6) is using libldap-2.3 while centos 7 has got
libldap-2.4 so the library is not found.

  Ivan

**Comment by killing** [comment]
Well, that's because we build the package on CentOS 5 for compatibility
with old systems. It seems currently nothing can be done. In the next
version we'll upgrade the ldap library or use a newer system to build
package.
The Pro edition seems to be new enough that the workaround mentioned in the
manual can be applied.

2015-02-09 21:46 GMT+08:00 t4nec0 <notifications@github.com>:

**Comment by t4nec0** [comment]
On 10/02/2015 03:30, Jiaqiang Xu wrote:
> Well, that's because we build the package on CentOS 5 for compatibility
> with old systems. It seems currently nothing can be done. In the next
> version we'll upgrade the ldap library or use a newer system to build
> package.
> The Pro edition seems to be new enough that the workaround mentioned in the
> manual can be applied.


OK, thank you for the information. I'll wait for the future release
then. In the meantime, keep on with this beautiful work!
