### ISSUE TITLE
LDAP 用户登录之后，获取邮箱异常

### ISSUE THREAD

**Issue by leim** [haiwen/seafile#2740]
邮箱与姓名显示异常。

LDAP相关配置如下，版本：11.0.5，docker部署，使用镜像 seafileltd/seafile-mc:11.0.5

![z03](https://github.com/haiwen/seafile/assets/1665397/6e1cbf26-d13f-4556-91d0-a13b87384647)

![z04](https://github.com/haiwen/seafile/assets/1665397/769adfd0-4064-47cb-bbb5-53043a21df39)

**Comment by killing** [comment]
Please ask usage and deployment issues on the forum.
