### ISSUE TITLE
Seafile 11 preview broken

### ISSUE THREAD

**Issue by io-err** [haiwen/seafile#2743]
Hi,

I am testing the docker installation of Seafile 11 and found that the file preview is broken (screenshot attached).

versions used:
docker.seadrive.org/seafileltd/seafile-pro-mc:11.0.4
seafileltd/office-preview:latest 

As I see seafileltd/office-preview image was updated a year ago, any replacement for seafile 11? 
![seafile_issue](https://github.com/haiwen/seafile/assets/30839552/f351cc48-aff3-4dcc-b202-40c7181c31c3)

**Comment by freeplant** [comment]
I recommend you to use OnlyOffice or CollaboraOnline. The office-preview image will no longer be maintained.

**Comment by io-err** [comment]
@freeplant Thank you for your quick response.

Yes, I've connected Collabora and it's working for editing as expected, but how to enable it for the file preview?
OFFICE_SERVER_TYPE = 'CollaboraOffice'
ENABLE_OFFICE_WEB_APP = True
OFFICE_WEB_APP_BASE_URL = 'https://domain.com/hosting/discovery'
WOPI_ACCESS_TOKEN_EXPIRATION = 30 * 60   # seconds
OFFICE_WEB_APP_FILE_EXTENSION = ('odp', 'ods', 'odt', 'xls', 'xlsb', 'xlsm', 'xlsx','ppsx', 'ppt', 'pptm', 'pptx', 'doc', 'docm', 'docx')
ENABLE_OFFICE_WEB_APP_EDIT = True
OFFICE_WEB_APP_EDIT_FILE_EXTENSION = ('odp', 'ods', 'odt', 'xls', 'xlsb', 'xlsm', 'xlsx','ppsx', 'ppt', 'pptm', 'pptx', 'doc', 'docm', 'docx')

**Comment by freeplant** [comment]
If you share the folder as read-only to a user, the user will open the file as preview only. You an also ENABLE_OFFICE_WEB_APP_EDIT to false to enforce all files be opened as read-only.
