### ISSUE TITLE
Potential Null pointer dereference when calling sqlite3_step

### ISSUE THREAD

**Issue by icy17** [haiwen/seafile#2754]
In **seafile/daemon/filelock-mgr.c** and **seafile/daemon/repo-mgr.c**, calling `sqlite3_step` without checking the parameter 1 might cause a **null dereference**. 
It's better to add a check before using the pointer or check the return value of `sqlite_query_prepare`

**Comment by feiniks** [comment]
> In **seafile/daemon/filelock-mgr.c** and **seafile/daemon/repo-mgr.c**, calling `sqlite3_step` without checking the parameter 1 might cause a **null dereference**. It's better to add a check before using the pointer or check the return value of `sqlite_query_prepare`

Hello @icy17 , thanks，but `sqlite3_step` will check the arguments for legality itself. So there is no need for additional checking.

**Comment by icy17** [comment]
You are right! Sorry I made a mistake here...
Thank you for the correction.
