### ISSUE TITLE
Seaf-fuse cannot list directory with lots of subfolders

### ISSUE THREAD

**Issue by kocane** [haiwen/seafile#2756]
I have a library that contains a folder with about 43.000 subfolders in it. 

When trying to list all files in this folder via Seafile FUSE mount, the terminal seemingly locks up indefinitely. 

Is this somewhat expected behavior or a known limitation of FUSE? Is there a way to further debug it?

**Comment by feiniks** [comment]
> I have a library that contains a folder with about 43.000 subfolders in it.
> 
> When trying to list all files in this folder via Seafile FUSE mount, the terminal seemingly locks up indefinitely.
> 
> Is this somewhat expected behavior or a known limitation of FUSE? Is there a way to further debug it?

Hi @kocane, this should be normal behavior, caused by too many subfolders.

**Comment by kocane** [comment]
> Hi @kocane, this should be normal behavior, caused by too many subfolders.

Is the problem seaf-fuse or fuse itself, do you know? As far as I know, there are improvements coming to fuse in kernel 6.9 but I'm unsure if they matter at all in this context

**Comment by feiniks** [comment]
Hi @kocane , this is a limitation of FUSE.

**Comment by freeplant** [comment]
> I have a library that contains a folder with about 43.000 subfolders in it.

Do you mean 43.000 subfolders directly in a single folder? It will be definitely slow no matter even if you store it directly on a normal file system other than the fuse interface of Seafile.
