### ISSUE TITLE
seafile-ignore.txt is ... well, ignored by seadrive clients on macOS and windows

### ISSUE THREAD

**Issue by working-name** [haiwen/seafile#2757]
## seafile-ignore.txt

```
.DS_Store
._*
Icon?
~\$*
~*
~$*
```

Created directories on macOS, they look like files (not sure why) but they sync over to the windows machine too.
<img width="528" alt="image" src="https://github.com/haiwen/seafile/assets/16505052/262e2cb3-01a2-4d16-b55e-411d1f1e8ae9">

Now here's the funky part:
- web UI does not list those two above
- files exist on both the station that created them (macOS) and were synced over to the windows machine via the clients. 

So while the server _might_ heed seafile-ignore.txt, the clients won't. 

Or you have trouble parsing special characters in the ignore file, that can also happen.

Windows seadrive client: 3.0.8
macos seadrive client: 3.0.7
Server Version: 10.0.13

**Comment by killing** [comment]
Currently SeaDrive hasn't supported ignore file. Even though there are some built-in ignore patterns, the filenames you mentioned are not matched by the pattern. In future version we will add support for ignore file.

wrt the web interface issue, we'll check.

**Comment by working-name** [comment]
This is a regression, probably **server-side**, since I don't remember using 3.0.6 or lower in terms of clients. The clients also have an option to not sync temporary Ms Office files which follow that pattern, but as I said, regression. It used to be clean before I upgraded the docker server. Can't remember what I ran last, but it's a recent install.

**Comment by killing** [comment]
Update: I made a mistake in my last answer. The pattern ~$* is ignore by our built-in ignore pattern, if you didn't enable the "sync temporary files of MS Office" option. Those are temp files generated by MS Office. So they're actually not uploaded to the server. That explains why they're not shown in the web UI.

The reason why you see those temp files on another client machine may be that they're created locally by Office.

BTW, the ignore file is only used by the clients, not the server.

**Comment by working-name** [comment]
Gotcha, yeah MS Office creates them when you open a file, but those directories I created myself with `mkdir` on macOS and they appeared on windows. It seems seadrive 3.0.7 on macOS had that issue, and I can't reproduce it with 3.0.8. So I guess it's resolved :)
