### ISSUE TITLE
Hello author, after integrating seafile with OnlyOffice, if the file size is greater than 20MB, an error message will appear when opening the conversion timeout. It is normal for the file size to be less than 20MB, and opening a file size greater than 20MB using OnlyOffice alone is also normal

### ISSUE THREAD

**Issue by cfy3133** [haiwen/seafile#2762]
![image](https://github.com/haiwen/seafile/assets/43978367/1ecaa032-a542-4637-bea2-da906a122d86)
![1713177325324](https://github.com/haiwen/seafile/assets/43978367/0ee89d2c-c0ba-40ec-b70b-3a97c1494b69)
Seafile is the latest version

**Comment by freeplant** [comment]
Please rewrite your issue with shorter title first.
