### ISSUE TITLE
generate sharing link on other library causes error

### ISSUE THREAD

**Issue by Entwicklungsleiter** [haiwen/seafile#2764]
Seafile Version:
11.0.7 running on official docker containers, system is Ubuntu 22.04 in last update state.

What am I doing?
I log into web interface and open a library that is NOT mine (for example a folder that was shared with me). I click on sharing symbol and in window "sharing link" I click "generate link". In the next window I do or do not select password or expiration date options. At the bottom I click on "generate".

Expectation: 
I would expect the link to be generated and ready to be copied.

Behavior:
I see an error message in browser window. Browser inspection console mentions http 500 response in URL https://<my_seafile_url>/api/v2.1/multi-share-links/. Seahub logfile shows new generated stack trace: 
![image](https://github.com/haiwen/seafile/assets/50797003/2befa719-bc00-4186-9f69-e9424979ae39)

Workaround:
Instead of sharing data that had been shared with me, I add a folder to my own library and generate a share link for that. This still works in my case.

**Comment by freeplant** [comment]
It will be fixed in the next release.
