### ISSUE TITLE
Directories names between character # are skipped

### ISSUE THREAD

**Issue by rapenne-s** [haiwen/seafile#2766]
hi,

Using seafile client 9.0.5, directories surrounded by the character `#` in their names are skipped.

It's easy to reproduce, type the following command in a seafile library

- `mkdir "#foobar#"`
- sync the library
- use the explorer to check
- the directory won't be there.

**Comment by killing** [comment]
This is a kind of common temporary file names. So it's ignore by default. You should avoid using such file names.
