### ISSUE TITLE
No xattr on OpenBSD

### ISSUE THREAD

**Issue by yason** [haiwen/seafile#2801]
https://github.com/haiwen/seafile/pull/2781 breaks build on OpenBSD because it doesn't support xattr

**Comment by killing** [comment]
This has been fixe in 9.0.8.

**Comment by yason** [comment]
Building 9.0.8 still fails:
ld: error: undefined symbol: removexattr
>>> referenced by utils.c
>>>               utils.o:(seaf_removexattr) in archive /tmp/pobj/seafile-daemon-9.0.8pl20240930/seafile-12c4621cdcd59fe8f71f621f9e0320aeb7cbfb5c/lib/.libs/libseafile_common.a
cc: error: linker command failed with exit code 1 (use -v to see invocation)
Error while executing cc -o seaf-daemon -pthread -DPKGDATADIR="/usr/local/share/seafile" -DPACKAGE_DATA_DIR="/usr/local/share/seafile" -DSEAFILE_CLIENT -D__USE_MINGW_ANSI_STDIO=1 -I../include -I../lib -I../lib -I../common -I/usr/local/include -I/usr/local/include/searpc -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -I/usr/local/include -Wall -O2 -pipe seaf-daemon.o job-mgr.o timer.o cevent.o http-tx-mgr.o vc-utils.o sync-mgr.o seafile-session.o seafile-crypt.o diff-simple.o wt-monitor.o wt-monitor-linux.o wt-monitor-structs.o clone-mgr.o seafile-config.o seafile-error.o branch-mgr.o fs-mgr.o repo-mgr.o commit-mgr.o log.o rpc-service.o vc-common.o obj-store.o obj-backend-fs.o block-mgr.o block-backend.o block-backend-fs.o mq-mgr.o curl-init.o sync-status-tree.o filelock-mgr.o set-perm.o change-set.o notif-mgr.o /tmp/pobj/seafile-daemon-9.0.8pl20240930/seafile-12c4621cdcd59fe8f71f621f9e0320aeb7cbfb5c/lib/.libs/libseafile_common.a /tmp/pobj/seafile-daemon-9.0.8pl20240930/seafile-12c4621cdcd59fe8f71f621f9e0320aeb7cbfb5c/common/cdc/.libs/libcdc.a /tmp/pobj/seafile-daemon-9.0.8pl20240930/seafile-12c4621cdcd59fe8f71f621f9e0320aeb7cbfb5c/common/index/.libs/libindex.a -L.libs -lglib-2.0 -lintl -lgobject-2.0 -luuid -lsqlite3 -lz -lm -lpthread -levent_extra -levent_core -lsearpc -ljansson -liconv -lgio-2.0 -lpcre2-8 -lffi -lssl -lcrypto -lexecinfo -levent_pthreads -linotify -lgmodule-2.0 -lcurl -lnghttp3 -lngtcp2_crypto_quictls -lngtcp2 -lnghttp2 -lwebsockets -Wl,-rpath,/usr/local/lib/inotify,-rpath-link,/usr/local/lib
gmake[2]: *** [Makefile:546: seaf-daemon] Error 2
