### ISSUE TITLE
Is it possible to set different synchronisation (clients) port from webpanel port?

### ISSUE THREAD

**Issue by doman18** [haiwen/seafile#2815]
Im evaluating Seafile as Synology Drive replacement. Currently it works on port 80 behind Caddy proxy (port 443). I would like to start to use it with my VPN (zerotier) but i want to pass only synchronisation traffic, not access do web ui? Ideally they would be on separate ports (443 for webui and some other like 8443 for client aps). But maybe at least allowing 443 (udp only) work? Or clients need both TCP and UDP to work?

**Comment by killing** [comment]
I don't really understand your question. But Seafile only requires 443 or 80 on TCP.

**Comment by doman18** [comment]
On my firewall i want to allow access for syncronisation traffic but block access to webui. I don't want to expose my web panel at all. In synology drive i have port 5001 (https) for webpanel access and 6690 which synlology drive client uses for synchronisation traffic. I only allow 6690 in my firewall so clients can synchronise but people don't have access to webpanel.

Ideally I would like to have https://myseafile.domain.com (port 443) for webpanel and https://myseafile.domain.com:5433 for clients connections. And allow only 5443 in my firewall. Is such separation possible?
