### ISSUE TITLE
Logging to syslog

### ISSUE THREAD

**Issue by vaminakov** [haiwen/seafile#2819]
Hello! I'm using community seafile 11.0.12.
Even if I configure to use syslog all components, for example:

seafevents.conf
`[Syslog]
enabled = true`

seafile.conf

`[general]
enable_syslog = true`

My seafile instance will write logs to files at /var/log/seafile. There are many types of log files.
There are no manual in documentation how to make all services of seafile log only to syslog without logfiles. How possible to do this?

**Comment by freeplant** [comment]
I'm sorry we don't have a plan to support logging to syslog currently.

**Comment by vaminakov** [comment]
@freeplant 
Ok, but is it possible to easily log to stdout? Using logfiles makes deployment difficult in most modern infrastructures.

**Comment by freeplant** [comment]
In version 12, we will make it easy to send all logs to stdout to make log collecting easy in k8s environment.

**Comment by vaminakov** [comment]
Great. This will cover the needs of systemd installations too.
