### ISSUE TITLE
Feature Request: Client Proxy Support 

### ISSUE THREAD

**Issue by f176521** [haiwen/seafile#283]
Many companies do not allow any direct or NAT access to the internet. As matter of this someone is forced to use the companies proxy. It would be graeat to have support on the client side for this, e.g. http proxy or socks proxy (what any ssh tunnel connection can offer). Thank you.

**Comment by erenoglu** [comment]
Just installed Seafile and hit this issue. Our company does not allow any internet access without going through a proxy. Proxy allows connect method though, so it should be possible to securely connect the seafile server that does https syncing. Looking forward for proxy support on the client (windows first).

**Comment by acavas1** [comment]
we have a proxy server. also blocked seafile ports. Just installed seafile server 4.0.5 tested with newest client. cheked option to sync on http port. works great. finally client can sync files from home network. thanks.

**Comment by red-warning** [comment]
hello,
i've also choosed sefile as a dropbox alternate, but this issue hinders me to migrate to seafile, because in can't use the client within my company. proxy-support is a cruicial part of an application, so please update this behavior.

thanks

**Comment by freeplant** [comment]
v4.1 client already add proxy support.

**Comment by red-warning** [comment]
Thank.. meanwhile i installed 4.1.3 and found proxy-options. :) Great!

**Comment by awikatchikaen** [comment]
Where do you found proxy options ? I tried 4.4.2 arnd 5.0.0 on windows but don't find them ...

**Comment by lins05** [comment]
Right click the seafile client tray icon -> settings, in the settings dialog, just click the "network" tab.
