### ISSUE TITLE
Sending Links with Passwords has no HTML escape

### ISSUE THREAD

**Issue by notenoughwoodsire** [haiwen/seafile#2830]
If one create a link with a password and sends it via mail in seafile, the password will be send without HTML escape. The message a User enters can also contain unescaped HTML.

This could lead to missing / wrong passwords after a "<" sign or for malicious use as external links could be injected into the code. 

I used `<h1>Hi</h1>` to demonstrate this behaviour:
![image](https://github.com/user-attachments/assets/4cf74d15-978e-4b43-93b9-ef693b050f70)

also here a ` p="">` was added:
![image](https://github.com/user-attachments/assets/3d462ad2-1709-4b26-95ed-866d0a0cb9b4)

A fix would be those replacements for the password and message variables in the code:

```
.replace(/&/g, '&amp;')
.replace(/</g, '&lt;')
.replace(/>/g, '&gt;')
.replace(/"/g, '&quot;')

```

**Comment by imwhatiam** [comment]
@notenoughwoodsire Hello, this issue does indeed exist, and we will be updating this part of the code soon.

**Comment by freeplant** [comment]
The fix will be included in the next release.
