### ISSUE TITLE
Seafile chunking

### ISSUE THREAD

**Issue by kbkozlev** [haiwen/seafile#2835]
Hi all I'm running Seafile behind Cloudflare tunnel, unfortunately there is an issue.
Cloudflare enforces a max upload of 100mb per request, so larger files cannot be uploaded. I checked the forum, and it said to set ENABLE_RESUMABLE_FILEUPLOAD = True in the seahub_settings.py, however even then the upload fails.

Is there a way to set the size of the chunks that seafile uses?

**Comment by killing** [comment]
Do you mean uploading from web browser fails? We by default upload the files in chunks of 1MB. Please check the web browser console for network errors.

**Comment by kbkozlev** [comment]
Uploading from the browser works, but the moment I try to upload something from the Android App that is larger than 100 mb. It goes the whole process of uploading and then fails at the end with a “Network Error” message. I have tried a mix of files small, large and all together. Everything that is less than 100mb is OK, and all the large ones fail.

**Comment by killing** [comment]
Have you upgraded to the latest version of Android app?

**Comment by kbkozlev** [comment]
Yes I'm running the latest version 3.0.4

**Comment by killing** [comment]
Well that should be due the Cloudflare restriction. Currently there is no way to change the chunk size for Android.
