### ISSUE TITLE
Please fix USE_GPL_CRYPTO flag for new password hash feature

### ISSUE THREAD

**Issue by moschlar** [haiwen/seafile#2842]
See https://github.com/haiwen/seafile/pull/2783#issuecomment-2443503979

The feature introduced a dependency on OpenSSL by not respecting the USE_GPL_CRYPTO flag!

That is problematic for the official Debian packaging due to licensing issues.

Please add appropriate ifdefs and such!

**Comment by killing** [comment]
We'll fix it in future version.

**Comment by moschlar** [comment]
Fixed by #2848 in v9.0.10
