### ISSUE TITLE
Q: Can SeaDrive use a letter as a mounting point in windows?

### ISSUE THREAD

**Issue by bmLucasMorante** [haiwen/seafile#2846]
Hi,
I have installed seafile with docker in Ubuntu22.4 server and the client in a windows WS.

![explorer_QVbaDN6QEW](https://github.com/user-attachments/assets/3e26cc06-d09f-4bcf-ab42-df7de159ac1a)

As you can see in the image, it is beeing mounted with the host ip instead of a drive letter. I havent found any settings or configuration to adjust the mounting point, did I miss anything? 

Is there a way of adjusting the way SeaFile gets mounted in windows? I would like to have it mounted with drive letter that I can choose.

Thanks,
Lucas

**Comment by killing** [comment]
Mounting as drive letter requires use of 3rd party driver named "Dokany". In our experience there could be serious incompatibility issues with this driver. Google Drive apparently use it too. But they hired the author to customize the driver for them. We switched Windows native File Provider API, which is used by all other cloud storage providers (Dropbox, OneDrive etc.). So there is no reliable way to implement it and we have no plan to support it again.
