### ISSUE TITLE
Mobile App Move / Copy contents

### ISSUE THREAD

**Issue by peterbata** [haiwen/seafile#2849]
This is not so much an issue as it is a feature request. When viewing my library on my mobile device it would be nice to have the ability to copy and/or move files between folders. Lovng the app by the way.

**Comment by freeplant** [comment]
For iOS client, click "more" button at the top, then click "Edit", you can now select items and move them.

This function is a little bit "hidden". In the next major release, we will improve the UI.

**Comment by peterbata** [comment]
@freeplant Thank you so much for the prompt response. Much appreciated. Have yourself a safe and wonderful weekend. Peter
