### ISSUE TITLE
The number of share links exceeds the limit

### ISSUE THREAD

**Issue by MarkFullerInflxr** [haiwen/seafile#2850]
Hello, I have a lot of files on my server, almost all of them have a share link, when I try to generate a share link using `/api/v2.1/share-links/` I now get the error. `HTTP 400: {"error_msg":"The number of share link exceeds the limit."}
` Is this something I can configure or bypass?

**Comment by MarkFullerInflxr** [comment]
i found this, https://github.com/haiwen/seahub/blob/45d9e8a127506a2c33a1517bd55d692bbbff3ec1/seahub/constants.py#L35

is there a way to overwrite this value? What are the consequences of increasing this value?

**Comment by freeplant** [comment]
It cannot be changed yet. The constant is for safety measure.

Is it possible for you to split files into different libraries?

**Comment by MarkFullerInflxr** [comment]
What are the consequences for increasing that number?

For our use case it would make more sense to horizontally scale the hardware and have mutliple seafile instances.

**Comment by freeplant** [comment]
The reason behind the design is that if Seafile is used for cloud service, and if every user can create a lot of sharing links for libraries, it will easily make the sharing link table very large.
