### ISSUE TITLE
New Trash not showing files

### ISSUE THREAD

**Issue by thecoffeebin** [haiwen/seafile#2858]
Hello,
I've installed Server Version: 12.0.4 CE with docker

When I deleted files they're not showing in the "new" Trash, it's empty (no files). However when I visited the link "Visit old version page" of the Trash then my deleted file is listed there.

Weird thing is I can Clean trash in both new and old Trash. Just files not showing up in the new Trash.

Screenshots attached.

<img width="548" alt="seafile new trash" src="https://github.com/user-attachments/assets/7d1baec8-258b-4d61-ae93-9b49db3babb6">

<img width="823" alt="seafile old version trash" src="https://github.com/user-attachments/assets/4875c608-8e0a-452e-86da-0d2272b75887">

**Comment by freeplant** [comment]
Can you check whether there are any error log in seafevents.log?

**Comment by thecoffeebin** [comment]
Yes when I deleted a file it has this posted in seafevents.log

```shell
[2024-12-10 01:24:30,614] [WARNING] invalid message format: {'content': 'repo-update\t977356c9-2e19-4d99-a3c6-e09c3aae38d2\t00d36d847eecb3d07e43f7d094d7d2805763ad66', 'ctime': 1733765070}
```

**Comment by freeplant** [comment]
This is a bug. We will fix it in the next release.
