### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by yishiaimeng** [haiwen/seafile#2866]
Dear predecessors, seafile software, window version can not be opened, is there a solution, or troubleshooting method?

The original can be opened, but it failed after I installed "Bohao Cash Register System". The Bohao system has local database synchronization function. After I uninstalled seafile, seafile cannot be opened, nor can it be re-installed or changed environmental variables.

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com, with detailed screenshots.
