### ISSUE TITLE
 	Locked updated file disables any further synchronization on Windows client

### ISSUE THREAD

**Issue by adamryczkowski** [haiwen/seafile#291]
What steps will reproduce the problem?
1. Setup current seafile server
2. Put two files into the shared folder in the server
3. Connect Windows client A to the folder and open the file "X.xls" (with write locking)
4. Modify the same file with client B
5. Let any client B sync with the server.
From now on, client A is banned from any more synchronizations from the server however irrelevant they are to the file "X.xls".

What is the expected output? What do you see instead?
I would expect only subsiding only the updates with the file "X.xls", not simply pause all the synchronization process

What version of the product are you using? On what operating system?
Server: 1.6
Windows Client: 1.7 on both windows XP and Windows 7

Please provide any additional information below.
I might help you with testing the development version of the seafile, but I really don't know hot to make it compile. I would greatly appreciate, if you would include instructions for it on the Wiki.

**Comment by ShonkyCH** [comment]
Is this still a limitation? One locked file means the whole library is blocked from syncing? That would happen somewhat frequently with Windows clients and in particular anyone using Office documents.

**Comment by killing** [comment]
No, not any more.

2015-07-06 12:28 GMT+08:00 ShonkyCH <notifications@github.com>:
