### ISSUE TITLE
Unable to upload to seafile private server

### ISSUE THREAD

**Issue by albas** [haiwen/seafile#303]
Hi Team, 

I have installed a seafile instance on my server. I can view seafile, create libraries, create groups etc. 

However when i try to upload a file i get the error:

Sorry, but the requested page could not be found.

This occurs within the seafile portal (i.e. the menu etc is still there)

I have changed ccnet.conf and seafile.conf to my domain and custom port. 

Is there any other changes that are required to upload files?

**Comment by kneufeld** [comment]
I needed to go into the webui system admin -> settings and change `FILE_SERVER_ROOT` to be `seafile.example.com/seafhttp` as per the local help text.

**Comment by DJHarty** [comment]
I have the same, on my server I can upload without errors. I'm using Windows Server 2012R2. But outside the server, I get always a "unknown error" when I try to upload any file

**Comment by audioscavenger** [comment]
SOLUTION = SERVICE_URL and FILE_SERVER_ROOT must match **scheme+url** of reverse proxy front end!!!
