### ISSUE TITLE
umask on Linux client

### ISSUE THREAD

**Issue by bigio** [haiwen/seafile#310]
It seems as the Linux cli client does not honour umask, when I modify a file on the server, the Linux client downloads it correctly but it sets the file permissions as 640 even with umask = 0000.
Is there a configuration parameter to be able to set correct permissions on the files ?
 Thanks
   Giovanni

**Comment by kingfisher77** [comment]
Hello, i run in this issue too. Syncing with seaf-cli into a samba share - need to set umask. But seaf-cli 4.0.4 still does not honour umask. Any news?

**Comment by kingfisher77** [comment]
@bigio How is your watcher.ini configured? I use events "create" and "self_move". You? How ist your experience on the long run?

**Comment by bigio** [comment]
On 02/17/15 15:29, kingfisher77 wrote:
> @bigio <https://github.com/bigio> How is your watcher.ini configured? I use events "create" and "self_move". You? How ist your experience on the long run?
> 
I had this on my watcher.ini:
events=create,delete,write_close,modify,move

I do not use seafile anymore, I use it just for some months, then I decided not to use any "cloud" solutions.
 Giovanni

**Comment by kingfisher77** [comment]
Thank you!
It seems to me that delete, write_close, modify are not necessary, because the rights are not affected. Did you had specific reasons for choosing these events?

**Comment by bigio** [comment]
On 02/17/15 18:41, kingfisher77 wrote:
> Thank you!
> It seems to me that delete, write_close, modify are not necessary, because the rights are not affected. Did you had specific reasons for choosing these events?
> 
I do not remember at all, I stopped seafile from my server more than a year ago.
 Giovanni

**Comment by kingfisher77** [comment]
Ok.

**Comment by bits4beats** [comment]
We have the same problem. 
Using seaf-cli in a samba contest is not a viable solution if not using something like Watcher script.

I'd like a implementation fixing the issue #1085 .
Thanks for your support!

ROb

**Comment by killing** [comment]
The latest client already honors umask.
