### ISSUE TITLE
Open doc/docx/ppt

### ISSUE THREAD

**Issue by herve456** [haiwen/seafile#314]
Hi, 

I've juste finished to configure Seafile 1.7.0 (for Pi) on my RaspBerry Pi et it work great! Better than other cloud private service...

I've fix the problem to read online pdf document but I've read that we can open doc/docx/ppt too.
But when I click on a doc file it says me that I can't read this file online.
It is normal?

Sorry for my english, I speak french :)

**Comment by builder555** [comment]
I installed the professional edition (in a docker container), however when I click a .docx file it still shows "Online view is not applicable to this file format". Is there additional configuration needed to view these files?

**Comment by freeplant** [comment]
You can integrate with OnlyOffice to view docx file online.
