### ISSUE TITLE
Automatic deletion of obsolete users/data

### ISSUE THREAD

**Issue by HenriWahl** [haiwen/seafile#327]
Hi,
as Seafile is a young (and vivid) project this problem surely does not yet exist but if there are installations working some years there might be a huge amount of obsolete users and their data on a local server. At least in setups where users are free to register and neglect or forget about their accounts/data. Is there already some kind of cleaning mechanism or the opportunity to implement some way to automatically clean obsolete users/data if they where not logged in/did not sync for a certain time?
Regards

**Comment by kototama** [comment]
@lenod see https://forum.seafile-server.org/t/solved-seafile-data-blocks-vs-seafile-data-storage/2180
