### ISSUE TITLE
Files from read-only libraries are "lost" for a client if deleted

### ISSUE THREAD

**Issue by C-Duv** [haiwen/seafile#348]
A file from a read-only library is somehow lost (id. can't have it anymore) to a user if he deletes it from his disk.

I thought client would handle this _forbidden_ action somehow but instead user can't get the file anymore (at least, on this client).
## Steps to reproduce

Given:
- A group named _salesforce_
- A user named _Alice_, member of the _salesforce_ group
- A read-only library named _sale-infos_ and owned by _salesforce_ group
- A  file named _important-infos.md_ into this _sale-infos_ library

Alice synchronizes the _sale-infos_ on her Windows seafile client (v1.8.1) and gets the _important-infos.md_ file on her disk.

She removes the _important-infos.md_ file off her disk (via Windows).
## Expected result

Either:
1. File can't be removed: Windows says it's a read-only file.
2. File is removed but is almost instantly re-put in place by Seafile's client (using cache or something like that).
3. File is removed but is re-put in place by Seafile's client during next synchronization.
## Actual result

File is deleted from folder
Clients tries to synchronize changes, fails to do so and notify the user with the following message:

> sync error: You do not have permission to access this library)

And file is never to be re-fetched again.

Found solution: unsync the library and re-add it (hopefully the _sync with an existing folder_ option avoid re-downloading the entire library).

**Comment by MurzNN** [comment]
Got the same issue on version 6.0 - I need that local folder must be always synced with server, so if user delete or modify file - it will be restored from server. Does seafile support this way of read-only sync?
