### ISSUE TITLE
Check quota before sync client upload is finished

### ISSUE THREAD

**Issue by killing** [haiwen/seafile#352]

**Comment by shoeper** [comment]
Accoring to https://forum.seafile-server.org/t/setting-a-user-quota-to-0-bytes/2583/8 this still needs a fix.

**Comment by shoeper** [comment]
This bug is still there in the most recent pro version.

**Comment by killing** [comment]
Uploading through client sync already checks quota before upload.

**Comment by shoeper** [comment]
Ah sorry, I mixed it up with the Web upload. In Seahub the quota isn't checked before upload and if still having quota left the user can upload a file of any size.
