### ISSUE TITLE
Wrong URL for default avatar with custom MEDIA_URL

### ISSUE THREAD

**Issue by droscy** [haiwen/seafile#355]
Hello,

I have a working seafile-server with custom MEDIA_URL and custom SITE_ROOT path. The default avatar is not showing up correctly because the url in the webpage is still `/media/something` instead of the custom MEDIA_URL.

This is a short extract of the html showing the wrong path for the default avatar and the right path for a personal avatar.

``` html
<ul>
  <li class="member"><img src="/media/avatars/default.jpg" alt="marco@xxxxx.yy" width="16" height="16" class="avatar" /><a class="name" href="/seafile/user/marco@xxxxx.yy/msgs/">Marco</a></li>
  <li class="member"><img src="/media/avatars/default.jpg" alt="luca@xxxxx.yy" width="16" height="16" class="avatar" /><a class="name" href="/seafile/user/luca@xxxxx.yy/msgs/">Luca</a></li>
  <li class="member"><img src="/seafmedia/avatars/simone%40xxxxx.yy/resized/16/sparrow.png" alt="simone@xxxxx.yy" width="16" height="16" class="avatar" /><a class="name" href="/seafile/user/simone@xxxxx.yy/msgs/">Simone</a></li>
</ul>
```

The same happens for group default avatar.

Have I misconfigured something?

Thanks, bye
Simone

**Comment by eriktews** [comment]
I can confirm that the bug still exists in 4.0.6. I installed seafile to my domain root, and later followed http://manual.seafile.com/deploy/deploy_Seahub_at_Non-root_domain.html to move it out of the domain root. Everything works fine, except for the avatar, which is still requested from the /media/ and not the seafmedia directory.

**Comment by eriktews** [comment]
I think I found the problem. The avatar URL is generated correctly, however the old bad value is stored in /tmp/seahub_cache/. So I suggest that the cache should be deleted when the directory is changed. I created a pull request to do that:

https://github.com/haiwen/seafile-docs/pull/65
