### ISSUE TITLE
Seahub redirects to http

### ISSUE THREAD

**Issue by J4nsen** [haiwen/seafile#38]
Hi, I'm running seafile in a virtual machine. To access seahub i've set up an apache proxy on my main web-vm.
When i access http://seafile.mydomain.com everything works fine, except the missing encryption.
When i access https://seafile.mydomain.com i'm redirected to http://seafile.mydomain.com/home/my.
When i access https://seafile.mydomain.com/home/my everything works perfectly.

Any idea why im getting redirected to http?

**Comment by daald** [comment]
@hostirosti Is there also a solution without fastcgi?

```
$ curl -v https://myhost 
> GET / HTTP/1.1
> Host: myhost
> 
< HTTP/1.1 302 FOUND
< Location: http://myhost/accounts/login?next=/
```

**Comment by hostirosti** [comment]
@daald Have you tried any of the solutions mentioned above? I haven't worked with seafile for years so not sure what they currently support.

**Comment by daald** [comment]
I didn't see J4nsen's comment so far, which looks very helpful. The other options didn't apply to my setup (don't have fastcgi and don't have port 80). I listed all possible options in a comment of another issue:  https://github.com/haiwen/seafile/issues/250#issuecomment-338517476

**Comment by daald** [comment]
@hostirosti Yes, the trick with the Django config works. https://github.com/haiwen/seafile/issues/250#issuecomment-339163836. I highly recommend adding a paragraph with this solution to https://manual.seafile.com/deploy/https_with_nginx.html. Without this setting, seafile breaks all the security you can get using https
