### ISSUE TITLE
Make httpServer bind address configurable

### ISSUE THREAD

**Issue by n-rodriguez** [haiwen/seafile#380]
httpServer bind address is hard coded in https://github.com/haiwen/seafile/blob/master/httpserver/httpserver.c line 26

Why not make it configurable like httpServer port?
Also, it would be nice to pass those parameters to the binary with something like -P for port and -b for bind address.

Thank you!

**Comment by kurazli** [comment]
sorry to reopen this issue, but i have a server with two ip addresses and really would like to bind seafile to a specific address from within seafile itself.
any news on this?

**Comment by teknoraver** [comment]
I managed to do this bi editing start_seahub in seahub.sh and replacing 0.0.0.0 to the IP to bind

**Comment by MrEasy** [comment]
> I managed to do this by editing start_seahub in seahub.sh and replacing 0.0.0.0 to the IP to bind
Can confirm with version 6.2.4 (line is 161).

Would appreciate a configuration possibility that survives updates.
