### ISSUE TITLE
metadata and tagging

### ISSUE THREAD

**Issue by ebricca** [haiwen/seafile#384]
Most likely some efforts were already made into the area .. are there any concrete plans of implementing?

tagging is what is really missing for me to use it in an adoption -- as it would allow for easy searchable categorization (in my case for an image repository)

what would be really nice additionally would be images / mp3 etc metadata parsing / display and eventually editing and reintegration into files on download / directly.

**Comment by mponweiser** [comment]
+1

**Comment by ewindes** [comment]
+1

**Comment by walterbyrd** [comment]
+1

**Comment by sinni800** [comment]
+1 with dynamic metadata you could instantly turn seafile into a document management system

**Comment by christianhuebschi** [comment]
+1

**Comment by michaelx** [comment]
+1

**Comment by Patrick-Morgenegg** [comment]
+1
