### ISSUE TITLE
[Feature request] Make the client (2.0) connect via HTTP/HTTPS only

### ISSUE THREAD

**Issue by moonwhaler** [haiwen/seafile#393]
After finally succeeding in setting up the server behind a Nginx HTTPS proxy, installing a (Windows) client was the next step. 

I realized however that the client will connect via HTTP/HTTPS and even lists the libraries, but won't upload/download anything if the ccnet port (default) 10001 and  seaf-server port (default) 12001 are not open!

Please make (all) the clients work with HTTP/HTTPS only. Currently ownCloud, Dropbox and Google Drive support this. I would love to have it in Seafile, as well!

**Comment by shoeper** [comment]
has been implemented.
