### ISSUE TITLE
Sync timer

### ISSUE THREAD

**Issue by antares2001** [haiwen/seafile#395]
Hello,

this is a feature proposal that may be helpful for others as well.

I am using Seafile as storage for a lot of Latex documents. Since live preview is not unusual with my editors, they produce a lot of files and storage operations which are synced to the server most time unnecessarily. Would it be possible to add something similar to the seafile-ignore file which lets me specify a timer like in the format

// [Filepattern] [Time in ms]
*.tex 60000

Which would only sync a .tex file that has not changed in the last minute. This would help reduce network load and the file history in the web browser would be much shorter.

Of course there would be other possible solutions and I would welcome any of them.

**Comment by Deradon** [comment]
:+1: for "We can add an option to support only sync a library once in X minutes."

### UseCase: Sync Thunderbird directory

I'm syncing my ThunderBird directory (mainly for backup purposes).
So I'm able to setup ThunderBird again with all plugins and mails on a new machine.

Thunderbird often changes files, but I do not need to upload these changes immediately.
For my use case, it would be enough, to only sync this directory every xx minutes.

/cc @freeplant

**Comment by K-os** [comment]
Oh, I would also love to see a possibility to specify a minimum synchronization interval for a library! I was just about to submit an issue for that and was checking if that had already been suggested.

My use case:
I keep my Lightroom catalog (an SQLite database) in a Seafile catalog and to prevent it from continuously uploading during editing I always need to disable autosync.

**Comment by shoeper** [comment]
Syncing every X minutes is possible now.

**Comment by Deradon** [comment]
Awesome! :smile:
