### ISSUE TITLE
Packaging seafile for distributions

### ISSUE THREAD

**Issue by Calrama** [haiwen/seafile#406]
Over the course of being a volunteer packager (as I like the software a lot) of seafile for a linux distribution (specifically for the ArchLinux User Repository), I've run into this a couple of times and this issue is currently very bad for seafile imho: The released source tarballs are currently months behind the binary releases and the tags for seafile are done in an inconsistent manner, such as the following tags that I took from seafile's history:

v2.0.4-client
server-2.0
client-2.0.3
v1.8.0-mac
v1.8.0-client
v1.7.3-client
v1.7.2-mac
v1.7.2-win
v1.7.0-server
v1.7.1-mac
v1.7.1-win
v1.7.0-win
v1.7.0-deb
mac-v1.6.2

As you can see, while the tags do follow some rules, they are too unpredictable to use reliably for the explicit purpose of packaging (where upgrading the packaging script to the next version needs to be as clean and simple as possible). For example, if I wanted to package seafile 1.8.0 for a linux distribution, should I choose the v1.8.0-mac tag, or the v1.8.0-client tag? Why are the suffixes sometimes for server/client, sometimes for operating systems? (The questions are rhetorical here, I just wanted to convey the confusion and eventual resignation I faced when trying to use the tags for this purpose)

The result of this tagging is that I cannot rely on these tags for packaging purposes. This combined with the aforementioned fact that the source tarballs are currently several months (last source tarball is from August 26) behind the binary releases leads me to to this:
I would like to ask you to provide at least one reliable way for distribution packagers to get at the clean versioned source code. This can be done in different ways, but the two easiest (and least time-consuming for you) I can think of are as following:

1) Use additional tags (no need to remove the current tagging style) of the following nature "vx.y.z". No suffixes, or anything, just a tag to mark the release of that specific version of seafile.

2) Keep the latest source tarballs at least within one month (preferrably less) of the latest binary releases.

Thanks for reading and please consider this issue / request, as imho properly versioned source code releases are at the very core of open source software.

**Comment by ad-m** [comment]
See https://packager.io/ . I think gitlab is a nice example how less paintful can be installing if prepared for packaging https://packager.io/gh/gitlabhq/gitlabhq https://github.com/gitlabhq/gitlab-recipes/tree/master/install/pkgr .

**Comment by Calrama** [comment]
@ad-m: [packager.io](https://packager.io/ ) seems fairly specific to web applications (without much native code), which this is not, though do correct me if I got the wrong impression: Someone will still have to write the distribution-specific specifications on how to build something (PKGBUILD, EBuild, ...), with patches et cetera; the technique of doing this in a distribution-agnostic way can imho only work in a sane fashion for code that gets executed inside a well-defined box (like web applications with their interpreter runtime).
OT: The only non-overkill way to go around that problem I know of would be to use sanboxing like docker or rkt, but the former [disqualifies itself from server systems](http://reventlov.com/advisories/using-the-docker-command-to-root-the-host) and the latter - at this moment - [requires root](https://github.com/coreos/rkt#trying-out-rkt-using-vagrant), no neither are currently an acceptable solution imho. Personally, as soon as sanboxing becomes a pratical solution, I'll switch over to that and run any servers with only the bare bones necessary for ssh and sandboxing.
However, for right now, manual work on both ends - upstream devs and distribution packagers - is still necessary.

**Comment by Calrama** [comment]
There is one issue concerning packaging - which I would like to address - as it has been bothering me for a while now: To be frank, imho this repository should either be split into the actual server, the CLI client, and the components shared between the server and the clients (namely seafile-daemon, libseafile, and libseafile's python bindings), or (which I assume will be the variant you're more inclined to) at the very least copy the CLI client and the shared components out of this repository into their own repositories (one for the CLI client, one for seafile-daemon, and one for libseafile and its python bindings), where they will be developed, individually versioned and released with git tags (so both the server and the desktop client can depend on proper versions when packaging for distributions); you can then keep the original versions in this repository and merge from the new repository back into this one for each release of seafile itself, so you don't have to change how you build your binaries, while packagers for distributions use this repositry only for the server itself.

**Comment by Calrama** [comment]
Could you please provide some context to the closing, since this tells me (and others) little? Do you consider this as a WONTFIX? Is anythimg planned to address this?

**Comment by freeplant** [comment]
Since the current tagging names and repositories are used for a long time and can work, we are not going to change.

**Comment by Calrama** [comment]
The tagging names are better than what was before, but they are non-standard and unnecessarily increase the workload for packagers. Same for the tight repository coupling. It is convoluted and drives potential packagers away, decreasing the availability of this otherwise good piece of software for Linux distributions (and your comment makes you appear to not care about that). Regardless, it is your project and I relinquished my maintainer duties for Archlinux some time after posting the latest long comment, so I will let the matter rest here.

**Comment by freeplant** [comment]
Sorry for my comment offend you. I close the issue because it is a long pending one and it seems the current tagging names are fine. For re-organizing the source code, it is too hard for a three-years project to significantly re-structure the source code.

**Comment by Calrama** [comment]
No offense taken (and if my comment seemed to convey me being offended I apologise), I just wanted to stress this point very clearly, because I believe this will - in the long - be harmful to the project as a whole; that's all.

**Comment by erenoglu** [comment]
As a user, I also agree that this shall not be closed. I would rather see the seafile developers stop developing new features for some time, put priority and focus on sorting out the code and package building so that linux distributions can pick it up and package it easily. This way you will reach way more users and have access to many more developers who would want to contribute into your project.

**Comment by freeplant** [comment]
This issue is originally regarding two problems:

* The released source tarballs are currently months behind the binary releases
* The tags for seafile are done in an inconsistent manner

These two problems are outdated now. For he source tarball, the Github automatically generate the source code tarballs after tag a release.

It is better to open another issue for source code repository re-organizing.
