### ISSUE TITLE
Start seafile server at system bootup before mysql server

### ISSUE THREAD

**Issue by kama3** [haiwen/seafile#430]
Seafile server starts at bootup with connection error to mysql server

 #cat logs/seafile.init.log
SQLException: Failed to start connection pool -- Lost connection to MySQL server at 'reading initial communication packet', system error: 111
 raised in ConnectionPool_start at src/db/ConnectionPool.c:287

Manual start works propertly (using command service seafile-server start).

**Comment by swissr** [comment]
Had the same problem with Debian Wheezy. Tried changing S02 -> S99 etc. but it didn't help. In the end, just added `sleep 2` into the '/etc/init.d/seafile' script. Bloody hack but it works...

**Comment by mirkster** [comment]
Thanks! The sleep 2 in the seafile script worked for me too and mine is running on Debian Jessie.

**Comment by jasonching** [comment]
I am using Ubuntu 14.04, and it's default to use UpStart, not SystemV.

As Hancho2009 had mentioned up there, the right way to do is to use UpStart and set the mysql dependency right.

Below is my version of the /etc/init/seafile-server.config file.

Here is my version:
```
# Seafile Server

description     "Seafile Server"
author          "Jason Ching"

start on (started mysql and runlevel [2345])
stop on (stopping mysql and runlevel [016])

pre-start script
    sudo -u seafile /opt/seafile/seafile-server-latest/seafile.sh start >> /opt/seafile/logs/seafile.init.log
    sudo -u seafile /opt/seafile/seafile-server-latest/seahub.sh start-fastcgi >> /opt/seafile/logs/seahub.init.log
end script

post-stop script
    sudo -u seafile /opt/seafile/seafile-server-latest/seafile.sh stop >> /opt/seafile/logs/seafile.init.log
    sudo -u seafile /opt/seafile/seafile-server-latest/seahub.sh stop >> /opt/seafile/logs/seahub.init.log
end script
```
