### ISSUE TITLE
file rename breaks share links

### ISSUE THREAD

**Issue by streaps** [haiwen/seafile#435]

**Comment by rawbertp** [comment]
Any updates on this one? This is quite annoying, isn't it?!

**Comment by freeplant** [comment]
This is a designed behaviour. Sharing link is bind to a specific path.

**Comment by rawbertp** [comment]
Ok, so the design appears to be wrong to me. Why would it be a good design if you had to send out a new link to everyone you shared a folder with after renaming or moving it? Fixing this would be a major improvement imho.
