### ISSUE TITLE
Indexing / Synchronization stops when NTFS long file name encountered

### ISSUE THREAD

**Issue by boa01** [haiwen/seafile#447]
Hello,

Is there a way for the Windows Client to just skip over and ignore any files which exceed this limitation but continue indexing / synchronizing the remaining folders?

Also, would be nice if under the "status" of the library this specific issue was named as the reason for why synchronization has stopped.  Pop-up balloon and all the rest for those of us who don't like to or know how to sift through log files...

**Comment by freeplant** [comment]
It is fixed in v4.0.7 for supporting syncing of long path.
