### ISSUE TITLE
Discrepancy between seafile.conf quota setting and seahub interface

### ISSUE THREAD

**Issue by wamdam** [haiwen/seafile#449]
In seafile.conf, quota must be given as integer in GB (see https://github.com/haiwen/seafile/wiki/Seafile-server-configuration-options#wiki-Storage_Quota_Setting_seafileconf).
In seahub, quota can be set in MB.

I propose to set both to MB so that default quota for anonymous-registration portals can be enabled. Small-quota accounts are useful for sharing regular repositories with them through a seafile-client without having big costs when they actually use their x GB of data.

**Comment by shoeper** [comment]
For individual setups the API can be used to adjust the quota.
http://manual.seafile.com/develop/web_api.html#update-account
