### ISSUE TITLE
[Feature request] Make library descriptions optional (again?)

### ISSUE THREAD

**Issue by Calrama** [haiwen/seafile#467]
This shouldn't be a big change as I doubt the description is used anywhere in the code to uniquely identify a library (correct me if I'm wrong, though), but it would be most welcome change, as I do not need any descriptions for my private libraries. For those I share with other people, sure; but for my private ones it's just annoying (I know what my stuff is).

Previously, you could just use a single space for descriptions, but when trying to edit one of my libraries right now with a description of " " Seahub refuses to save the new settings and says "description needed", which effectively blocks me from editing that library's settings as I refuse to have a description I don't need.

I realize this is only a minor issue and may seem silly, but it is quite serious for me.

**Comment by shoeper** [comment]
this is still an issue. Would be nice if the description wouldn't be required.

**Comment by Calrama** [comment]
This issue is still present.

**Comment by shoeper** [comment]
And please, do not fix it by completely removing the description as it was planned at some time. It can be helpful espacially when sharing a library with others but it shouldn't be required.

**Comment by freeplant** [comment]
OK. We will make the description optional.

**Comment by shoeper** [comment]
thanks!

**Comment by shoeper** [comment]
Description has been removed.
