### ISSUE TITLE
2.1.0 beta and webdav with fastcgi

### ISSUE THREAD

**Issue by szimszon** [haiwen/seafile#479]
I wonder if somebody could help me.

I tried to set up webdav with apache as in https://github.com/haiwen/seafile/wiki/Seafile-WebDAV-Server but I got these:

--- cut ---
*\* Message: seafile-controller.c(854): Error when reading WEBDAV.fastcgi, use default value 'false'

*\* Message: seafile-controller.c(863): Error when reading WEBDAV.port, use deafult value 8080
--- cut ---

[WEBDAV]
enabled = true
port = 8080
fastcgi = true
share_name = /seafdav

**Comment by kmnns** [comment]
Same problem, same solution. Sorcery!

**Comment by Findus23** [comment]
I thought I was going crazy. I had a space after `fastcgi = true` and because of that it defaulted to false.

Thank for the solution
