### ISSUE TITLE
Question about upload-api

### ISSUE THREAD

**Issue by szimszon** [haiwen/seafile#485]
Hi!

I wonder if somebody could help me.

As I tinkered with [upload-api](https://github.com/haiwen/seafile/wiki/Seafile-web-API#wiki-upload-file) in [SeaFile exstension for Thunderbird](https://github.com/szimszon/tb-filelink-seafile) and stumbled upon a problem. If I upload a file with the same filename that exists already who can I know what name has the newly uploaded file. It could be good to receive the filename it got saved in the upload response.

**Comment by shoeper** [comment]
The extions (if it doesn't already have a fix) would have to check whether the file exists first to work properly.
