### ISSUE TITLE
Server on Arch Linux ARM does not work

### ISSUE THREAD

**Issue by screendriver** [haiwen/seafile#493]
Hi,
I am using a RaspberryPi with Arch Linux ARM installed on it. Today I wanted to try seafile. I installed all [dependencies](https://github.com/haiwen/seafile/wiki/Download-and-setup-seafile-server) and followed the installation guide. Unfortunately I get following error and I don't know how to solve it:

```
Generating ccnet configuration in /home/me/seafile/ccnet...

/home/me/seafile/seafile-server-2.0.3/seafile/bin/ccnet-init: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
```

**Comment by Danny4927** [comment]
installing `libselinux` from Arch AUR also fixes the issue, just had the problem myself

**Comment by ikwyl6** [comment]
I download the snapshot from the AUR, run 'makepkg' and I get:

==> ERROR: seafile-server is not available for the 'arm' architecture.

I'm using arch linux on arm on pogoplug.
