### ISSUE TITLE
Ignore pattern is not recursive

### ISSUE THREAD

**Issue by MoritzMaxeiner** [haiwen/seafile#502]
In the original feature request it was stated that the ignore.txt should work like a .gitignore (https://github.com/haiwen/seafile/issues/114). However, while this
".dub/" in .gitignore
will make git ignore a folder named ".dub" in any subdirectories,
".dub/" in seafile-ignore.txt
will make the seafile-client only ignore a folder ".dub" at the root level of the library.
If this is as inteded, is there a way to specify the pattern to be recursive for seafile-client?

**Comment by afcuttin** [comment]
http://seafile.com/en/help/ignore/ dead link
