### ISSUE TITLE
Page Unavailable error with some user login

### ISSUE THREAD

**Issue by reyman** [haiwen/seafile#505]
Hi,
After upgrade to last server version, some user have problem with login/password.
I try to reset pwd, without success :
After identification, they have a Page Unavailable error !

Message say : 
Sorry, but the requested page is unavailable due to a server hiccup.
Our engineers have been notified, so check back later.

Is there a solution ? 
SR

**Comment by MakerYan** [comment]
Page unavailable

Sorry, but the requested page is unavailable due to a server hiccup.

Our engineers have been notified, so check back later.
