### ISSUE TITLE
Error after the first logon

### ISSUE THREAD

**Issue by tacitus-def** [haiwen/seafile#510]
Seafile 2.1.3 installed on ubuntu 12.04 (i386) and configured with LDAP users (Active Directory). When a user first logs in, he gets an error message "Page unavailable".

Debug messages:

SearpcError at /home/my/
Get repo error
Request Method:	GET
Request URL:	http://192.168.x.xxx/home/my/
Django Version:	1.5.1
Exception Type:	SearpcError
Exception Value:	
Get repo error
Exception Location:	/opt/seafile/server/seafile/lib/python2.6/site-packages/pysearpc/client.py in _fret_string, line 25
Python Executable:	/usr/bin/python2.7
Python Version:	2.7.3
Python Path:	
['/opt/seafile/server/seahub',
 '/opt/seafile/server/seahub/thirdpart/Djblets-0.6.14.dev-py2.6.egg',
 '/opt/seafile/server/seahub/thirdpart/gunicorn-0.16.1-py2.6.egg',
 '/opt/seafile/server/seahub/thirdpart/flup-1.0-py2.6.egg',
 '/opt/seafile/server/seahub/thirdpart/chardet-2.1.1-py2.6.egg',
 '/opt/seafile/server/seahub/thirdpart/Django-1.5.1-py2.6.egg',
 '/opt/seafile/server/seahub/thirdpart/python_daemon-1.5.5-py2.6.egg',
 '/opt/seafile/server/seahub/thirdpart/lockfile-0.9.1-py2.6.egg',
 '/opt/seafile/server/seahub/thirdpart/six-1.4.1-py2.6.egg',
 '/opt/seafile/server/seahub/thirdpart/WsgiDAV-0.5.1.dev_20131224-py2.6.egg',
 '/opt/seafile/server/seafile/lib/python2.7/site-packages',
 '/opt/seafile/server/seafile/lib64/python2.7/site-packages',
 '/opt/seafile/server/seafile/lib/python2.6/site-packages',
 '/opt/seafile/server/seafile/lib64/python2.6/site-packages',
 '/opt/seafile/server/seahub/thirdpart',
 '/opt/seafile',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PIL',
 '/usr/lib/pymodules/python2.7',
 '/opt/seafile/server/seafile/lib/python2.7/site-packages',
 '/opt/seafile/server/seafile/lib64/python2.7/site-packages',
 '/opt/seafile/server/seafile/lib64/python2.6/site-packages']

Environment:

Request Method: GET
Request URL: http://192.168.x.xxx/home/my/

Django Version: 1.5.1
Python Version: 2.7.3
Installed Applications:
('django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'registration',
 'captcha',
 'seahub.api2',
 'seahub.avatar',
 'seahub.base',
 'seahub.contacts',
 'seahub.wiki',
 'seahub.group',
 'seahub.message',
 'seahub.notifications',
 'seahub.options',
 'seahub.profile',
 'seahub.share',
 'seahub.help',
 'gunicorn')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'seahub.auth.middleware.AuthenticationMiddleware',
 'seahub.base.middleware.BaseMiddleware',
 'seahub.base.middleware.InfobarMiddleware')

Traceback:
File "/opt/seafile/server/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/core/handlers/base.py" in get_response
  115.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/seafile/server/seahub/seahub/auth/decorators.py" in _wrapped_view
  25.                 return view_func(request, *args, **kwargs)
File "/opt/seafile/server/seahub/seahub/views/__init__.py" in myhome
  996.             create_default_library(username)
File "/opt/seafile/server/seahub/seahub/views/__init__.py" in create_default_library
  909.     dirents = seafile_api.list_dir_by_path(sys_repo_id, '/')
File "/opt/seafile/server/seafile/lib/python2.6/site-packages/seaserv/api.py" in list_dir_by_path
  174.         dir_id = seafserv_threaded_rpc.get_dir_id_by_path(repo_id, path)
File "/opt/seafile/server/seafile/lib/python2.6/site-packages/pysearpc/client.py" in newfunc
  112.                 return fret(ret_str)
File "/opt/seafile/server/seafile/lib/python2.6/site-packages/pysearpc/client.py" in _fret_string
  25.         raise SearpcError(dicts['err_msg'])

Exception Type: SearpcError at /home/my/
Exception Value: Get repo error

**Comment by kevinvalk** [comment]
I am running CE edition version: 4.3.2. This button is still present. Actually, I would love to delete it so that new accounts do not have a default library but I could not find any information regarding if these issues are fixed or not.

![delete](https://cloud.githubusercontent.com/assets/3524694/10011623/035592de-60b2-11e5-8c61-1d349066aef0.png)

**Comment by swennijboer** [comment]
It is still possible to remove te library, I don't know if it is considered a bug but you can do it by:

1) transfer to your own account
2) remove the library

You will get an error wehn you head for the "System" tab so I would not advise to do this.
