### ISSUE TITLE
Deleting a shared folder doesn't delete the Download Link

### ISSUE THREAD

**Issue by jpfleury** [haiwen/seafile#511]
If we forget to unshare a shared folder before deleting it, the Download Link will still exist. Then if we visit this link, the deleted folder will appear (but empty):

> folder name
> Shared by: pseudo
> Current path: folder name

If we click on the ZIP link to download the folder, we have an error:

> Page unavailable
> Sorry, but the requested page is unavailable due to a server hiccup.
> Our engineers have been notified, so check back later.

Here are two possibilities to fix this:

1. Automatically delete a share link when a shared file or folder is deleted by the user.

2. When the user wants to delete a shared file or folder, display a pop up warning to remind him that it must unshare it before deleting it.

**Comment by shoeper** [comment]
At least when performing those actions via Seahub it works (now).
