### ISSUE TITLE
LDAP login by Username 

### ISSUE THREAD

**Issue by stlorenz** [haiwen/seafile#523]
What is needed to accomplish this?

Its a feature that i really need in my enviroment so i am willing an hopefully able to contribute. 

To be more concise in this topic:

I want to integrate Seafile in an enviroment where everything is connected to the Username and not the Email. 
Many Users therefore do not even have an Email-Account in this Domain (Samba4). 

For the first integration it would be sufficient to authenticate against the Samba4-Domain or the sychronized OpenLDAP-Directory with Username and Password where Group-Membership enables Access to Seafile or not. .

**Comment by shoeper** [comment]
Login via username has been implemented.
