### ISSUE TITLE
LDAP Support for Groups

### ISSUE THREAD

**Issue by simon-imc** [haiwen/seafile#526]
We have set up Seafile for the file exchange in a research project and it is running very smoothly. But by being is used in the context of a collaboration platform (wiki, vcs, xmpp, etc.), the missing support for LDAP groups turned out as major drawback.

Please consider putting this feature on the roadmap for the seafile server.

P.S.: This request is already addressed in [Google Groups](https://groups.google.com/forum/#!searchin/seafile/ldap$20groups/seafile/0NI1Z1fkPsY/R0eUfEb5Vc0J).

**Comment by werner-j** [comment]
Any news on this?

**Comment by freeplant** [comment]
We are going to support LDAP group in a few months. Probably this feature will be in pro edition.

**Comment by borja44** [comment]
Have you released a new server pro version and is LDAP group supported?
Any new?

**Comment by freeplant** [comment]
We are working on a feature that syncing LDAP groups into Seafile. It will be included in version pro 4.1 which will be ready in the next month.

**Comment by borja44** [comment]
What happens if I create the user manually and afterwords in future, are connected against LDAP?

**Comment by freeplant** [comment]
This feature creates Seafile groups to mirror LDAP groups. If you have a LDAP group tech-team, it will create a group tech-team in Seafile and settings the members of the team the same as the LDAP group. It does affect accounts management.

**Comment by darkcircle** [comment]
I tested with 4.2.0 Pro edition by set GROUP_FILTER value 
(&(|(cn=AM)(cn=Future*))(objectclass=group)) 
into the ccnet.conf 
with
GROUP_OBJECT_CLASS = group
GROUP_MEMBER_ATTR = member

and there is 'Bad search filter' warning.

what is the possibility to take my own mistake for writing a ldap query?

P.S. of course I also read [this link, LDAP group sync](http://manual.seafile.com/deploy/ldap_group_sync.html).

**Comment by killing** [comment]
You can try to remove (objectclass=group) from your filter. That's already
included for the internal filter.

2015-06-19 1:05 GMT+08:00 Seong-ho Cho <notifications@github.com>:
