### ISSUE TITLE
[Feature request] Selectable encryption scheme

### ISSUE THREAD

**Issue by MoritzMaxeiner** [haiwen/seafile#530]
It seems I misread what's written in seafile-crypt.h, which is why I've changed the title and contents of the issue.

Seafile seems to use AES with 256 bit and in CBC mode at the highest "version" (I have not yet found out how the version is determined?).
Could we get the ability to set which encryption scheme / key length / block cipher mode should be used at library creation time? Also, by additionally using libsodioum[1], you could support some more encryption schemes for that.

[1] https://github.com/jedisct1/libsodium

**Comment by freeplant** [comment]
This feature will not be implemented.
