### ISSUE TITLE
[Feature request] Hybrid encryption

### ISSUE THREAD

**Issue by MoritzMaxeiner** [haiwen/seafile#531]
By using client-side hybrid encryption[1] you could share encrypted libraries between people without the need to manually, securely share a private key. Instead, the creator of the encrypted library L would create a random symmetric private key K_priv, which is used to enrypt the library's data, and then encrypt that symmetric private key with his own asymmetric public key K_pub(creator) and stores in in a seperate segment (belonging to the that library) C_PrivK on the server , so it can be retrieved later by means of the creator's asymetric secret key.
In order to share a library with someone, the creator would retrieve the segment C_PrivK from the server, decrypt his own entry in it with his own asymmetric secret key, encrypt it with the intended recipient's asymmetric public key, append that to the library's key segment, and write the segment back to the server. As soon as that has been done, the person who the library is supposed to be shared with can retrieve the new C_PrivK, decrypt his own (new) entry with his own asymmetric secret key, which yields the symmetric private key that was randomly chosen by the creator, with which he can decrypt the data in the library.

[1] http://en.wikipedia.org/wiki/Hybrid_cryptosystem

**Comment by Calrama** [comment]
That's an argument for more user-friendly crypto-tools, rather than against hybrid encryption. I still consider the latter to be the easiest integrated way for securely sharing a library with a bunch of people. Sure, you could use an external, secure channel (PGP-encrypted email, mobile crypto-messengers) and that is what I'd currently do, but it falls short of an integrated solution using a hybrid cryptosystem mho.

**Comment by MoritzMaxeiner** [comment]
@killing Does seafile now support hybrid encryption, or why has this been closed without comment? If this is definitely not going to be supported, please mark this as `WONTFIX`.

**Comment by killing** [comment]
Hi,

We don't have plan to support this scheme. I marked it as rejected. Thanks for your suggestions though!
