### ISSUE TITLE
[Feature Request] Antivirus

### ISSUE THREAD

**Issue by todiadiyatmo** [haiwen/seafile#533]
Hi ! 
I've been using seafile for 1 month and it runs smoothly :)

Is there any chance to release antivirus to scan the file that uploaded. Because i hear a story about a cloud user get infected by other people file. I think having a scaner will be a nice feature. Or if it can be integrated with 3rd party scanner, is there any how to ?

Regards,
Todi

**Comment by arobertz** [comment]
Any news on this? I also would like to secure seafile by for example calmav while uploading files.

**Comment by shoeper** [comment]
You could use fuse. Problem there is that it is read only so you would have to delete the files on another way.
Depending on the amount of users you could notify yourself (the admin) that a bad file has been found in folder x.

**Comment by egroeper** [comment]
This is a pro feature since 4.4.
