### ISSUE TITLE
How is data stored ? How to get particular data file/folder ?

### ISSUE THREAD

**Issue by shubhank008** [haiwen/seafile#543]
One thing I have been trying to figure out and understand is, how does Seafile stores the data ?
In OC, it simply uploaded the files to a folder named with the username of the user

So backing up or getting particular files/folders or transferring them for one user was piece of cake.

How does SF stores the data ? How do you get particular folders or library or such for a client ?

We have been thinking and planning to allow our user a option to "push" their files/folders (if not directly then a full library itself) to their own FTP server or a remote location.

Ofcourse we will write the code for the transfer and such, our only problem is getting the data/library user wants to "push".

**Comment by sam9s** [comment]
FUSE is just so irritating .... every now and then it would just unmount it and show 0 files. stopping and restaring fuse does not help ... the only way is to uninstalled fuse and reinstall it ..... wish there was a direct way to access seafile folders ...

**Comment by shoeper** [comment]
FUSE is running for month here with heavy access from time to time (one library has 700k files and has been scanned multiple times via fuse).

**Comment by sam9s** [comment]
^^ Then enlighten me with what might be wrong ......
