### ISSUE TITLE
Improvements to the file history

### ISSUE THREAD

**Issue by piafinho** [haiwen/seafile#544]
Current options allow to keep the full history, no history or for X number of days.
It would be very good to have some more control over the file history:
- Ability to manually remove files from history
- Ability to define a maximum number of versions per file in history
- Ability to mark version in history not to be removed (main versions) if time based or number of files is being used
- Ability to overwrite the Library settings on a subfolder or file. So that on a given file that changes too often I would not keep a big list

**Comment by Inza** [comment]
This would really great! Because for files are changes very often the history makes too much of copies and that takes a lot of disk space

**Comment by freeplant** [comment]
This feature will not be implemented.
