### ISSUE TITLE
How to compile on Windows ?

### ISSUE THREAD

**Issue by ghost** [haiwen/seafile#545]
Hello, 

Can someone give me directions on how to compile on Windows ?
I've found for Linux and Mac but not Windows.

Thanks

**Comment by ejb1123** [comment]
+1

**Comment by coloradomountain** [comment]
I will be installing windows 10 to a new device tonight, I will look into writing up documentation on compiling on Windows.

**Comment by shoeper** [comment]
see the issue in seafile-client https://github.com/haiwen/seafile-client/issues/810
