### ISSUE TITLE
No slideshow support

### ISSUE THREAD

**Issue by bobbaluba** [haiwen/seafile#557]
When viewing family photos and similar using the web client, it is very annoying to have to scroll down each time you go to the next picture.

Adding a slideshow feature should be relatively easy, and would be greatly appreciated.

This problem is most visible on low resolution wide screen TVs. Example:
![screenshot from 2014-03-02 14 45 06](https://f.cloud.github.com/assets/397753/2304255/eaf9d792-a210-11e3-962c-258c6b496bdd.png)

This has also been mentioned in issue #366

**Comment by dstuxo** [comment]
This looks very nice!! https://github.com/blueimp/Gallery
Photo preview/gallery would be a much appreciated feature, for sure!

**Comment by stefanandres** [comment]
The current version (4.x) has some kind of basic thumbnail support in the web-ui.

**Comment by dstuxo** [comment]
ok.Thanks. Is this also available in the demo https://seacloud.cc ,  or it's not running the latest version?

**Comment by stefanandres** [comment]
I don't know, but it looks like this in my installation:

![screen shot 2015-01-06 at 10 49 50](https://cloud.githubusercontent.com/assets/2674469/5626901/d6445708-9591-11e4-8d5b-de93e213fe97.png)

**Comment by mbedded** [comment]
A gallery-function would be really nice.
I tested Seafile because OwnCloud has too much overhead and i like SeaFile more than OwnCloud.
A gallery would be nice if you want to share some photos from your holidays.

**Comment by Alukardd** [comment]
Hi, all!

Can anybody tell me what I should do for generating and viewing thumbnails for all my images?
I have Server Version: 4.2.3.
In ```seahub/seahub/settings.py``` I have ```ENABLE_THUMBNAIL = True```

**Comment by Alukardd** [comment]
Oh, It is my fail: I had wrong SERVICE_URL in my ccnet.conf

**Comment by johanhelsing** [comment]
This has improved a lot, but is IMO this is still not completely solved.

![screenshot from 2016-03-22 13-30-49](https://cloud.githubusercontent.com/assets/2620557/13951639/9fed525c-f032-11e5-9e2a-be9fd5237f16.png)

There is a lot of wasted space above/below and on the sides. What I would have liked to see, is a mode where the background is completely black and the pictures take the maximum width available on the screen.
