### ISSUE TITLE
Can't use webdav when compiling from source

### ISSUE THREAD

**Issue by jprjr** [haiwen/seafile#565]
Hi there -

I've been banging my head trying to get WebDAV up and running. I've compiled Seafile from source on Arch Linux.

It looks like the pre-compiled download includes wsgidav + a seafile_dav_provider addon.

I can't find the source for the safile dav provider anywhere on github

**Comment by audax** [comment]
Where can I find the documentation you mentioned?

**Comment by simeonfelis** [comment]
Hi,Seehttp://manual.seafile.com/extension/webdav.html                                                                                                                                     Regards                                                                                                                                                                                                                                                                                                                                                                               Von: Jens KadenbachGesendet: Dienstag, 6. Januar 2015 14:07An: haiwen/seafileAntwort an: haiwen/seafileCc: simeonfelisBetreff: Re: [seafile] Can't use webdav when compiling from source (#565)Where can I find the documentation you mentioned?

—Reply to this email directly or view it on GitHub.

**Comment by kangwook** [comment]
Hi, 

I have same problem, but finally I solved this.

First of all, I copied seafobj and wsgidav into "seafile-server/seahub/thirdpart' which can be found in 
https://github.com/haiwen/seafobj, https://github.com/haiwen/seafdav.
I used "seafobj-master/seafobj" and "seafdav-master/wsgidav".

And then, I modified seafile-controller.c and rebuild it. 
What I modified is "seafile-server/src/seafile-4.0.5-server/controller/seafile-controller.c".
In my case, topdir variable which points base directory of  seafdav.conf file in read_seafdav_config() is defined as "/".
So I change it, e.g., "/data/haiwen/", and it works. 
BTW, changing topdir also changes pids directory location.

I didn't check whether /conf/seafdav.conf works without modifying seafile-controller.c, but I guess it will work if you can create conf directory on "/".

My environments are Debian on ARM processor, apache with ssl and fastcgi, and sqlite. 
Set PYTHONPATH , and then run "seafile-admin start --fastcgi"

good luck
