### ISSUE TITLE
[server] Sync between servers

### ISSUE THREAD

**Issue by freeplant** [haiwen/seafile#58]

**Comment by theliquid** [comment]
Any update on this?

**Comment by muzzol** [comment]
I'm very interested in this feature too.

**Comment by Jip-Hop** [comment]
So am I. Especially the replication scenario is of interest to me because I have a very slow internet connection in my home. With a Seafile server on my home network and a second Seafile server on a place with a fast internet connection I could quickly sync all my files in my LAN. These changes would slowly replicate to the second Seafile server that ensures speedy access when outside of my LAN.

**Comment by epe** [comment]
The variant a) could also be achieved by enabling local LAN sync (via DNS_SD/Zeroconf) if you have a second client in the local network that is mostly or always on.. 
DropXXX offers such a local LAN sync feature. 
I would be interested to hear from the core developers, which of theses things could be implemented easiest with the current architecture and how the community could support the development.

**Comment by theliquid** [comment]
Any news on that?

**Comment by shoeper** [comment]
No

**Comment by muzzol** [comment]
I love this comments :D

**Comment by killing** [comment]
A version of server sync may be available in 5.1 Pro edition. The feature only supports the replication/backup scenario. Other scenarios are too hard to implement. We haven't found good way to do that.

**Comment by theliquid** [comment]
Ok, thanks. These are good news. 

My current setup is: A Seafile Client on the Seafile Server which syncs the library in a local folder. The folders gets rsynced every hour into another local folder. And the other local folder is synced to a second server. This method works only one way, but it is currently the only way to have a backup server with my repo online.

**Comment by shoeper** [comment]
@theliquid maybe you could run the client to sync it on one server with a folder and then sync this folder first with one server next with the other server and so on. Using Seafile CLI (create a script doing these steps every few minutes) there should imho be some way to do this. The only problem I see is that it could need much resources with large datasets. But I could think of that it's working well with smaller libraries.

Another thing that could work (I'm not sure if also with the CE): Using some storage backend with replication (with CE this could work if one configures NFS to replicate) and mysql replication. Drawback with this would be that it could work well with the whole server but not with just a few libraries.

**Comment by Mikeichhalt** [comment]
@killing Will the replicaion/backup scenario also be in the Community Edition?

**Comment by shoeper** [comment]
no

**Comment by MurzNN** [comment]
Seems synchronization between servers now can be implemented via Open Cloud Mesh protocol: https://manual.seafile.com/deploy/ocm/
