### ISSUE TITLE
add a "start-fcgi" command to seahub.sh

### ISSUE THREAD

**Issue by lins05** [haiwen/seafile#59]

**Comment by zhenghailong888** [comment]
我在执行 seahub.sh start-fastcgi  时  报 Unknown command: 'fastcgi' 的错误，
'''
bash -x  seahub.sh start-fastcgi
+ check_init_admin
+ check_init_admin_script=/home/zheng/haiwen/seafile-server-6.3.3/check_init_admin.py
+ python2.7 /home/zheng/haiwen/seafile-server-6.3.3/check_init_admin.py
+ python2.7 /home/zheng/haiwen/seafile-server-6.3.3/seahub/manage.py fastcgi maxchildren=8 host=127.0.0.1 port=8000 pidfile=/home/zheng/haiwen/pids/seahub.pid outlog=/home/zheng/haiwen/logs/gunicorn_access.log errlog=/home/zheng/haiwen/logs/gunicorn_error.log
Unknown command: 'fastcgi'
Type 'manage.py help' for usage.
+ sleep 5
+ pgrep -f /home/zheng/haiwen/seafile-server-6.3.3/seahub/manage.py
+ printf '\033[33mError:Seahub failed to start.\033[m\n'
Error:Seahub failed to start.
+ exit 1
'''
