### ISSUE TITLE
Implement CMIS

### ISSUE THREAD

**Issue by nicolas-raoul** [haiwen/seafile#600]
(enhancement)

The Seafile server already implements WebDAV.
Implementing CMIS would make the server much more interoperable.

CMIS is the protocol for Enterprise Content Management:
https://en.wikipedia.org/wiki/Content_Management_Interoperability_Services

I see CMIS as a necessary step before Seafile can enter the enterprise market.

**Comment by freeplant** [comment]
The demand is quite low.
