### ISSUE TITLE
sea file desktop daemon interface

### ISSUE THREAD

**Issue by vincentkersten** [haiwen/seafile#607]
Dear sea file,
having great fun with the community edition (works very well so far!) and while working i found that i missed in the menu (attach1) a quick way to access my libraries which I am having in the client window.

Hope this can be useful for others as well!

Regards,

  Vincent

![seafile](https://cloud.githubusercontent.com/assets/5429401/2813718/36ba0dae-ce95-11e3-8f26-180b9c477027.png)

**Comment by freeplant** [comment]
It is already implemented
