### ISSUE TITLE
ACL what libraries a client can access

### ISSUE THREAD

**Issue by allo-** [haiwen/seafile#612]
It would be good, to limit the access of a client to certain libraries.

Example:
i have a private library "private" and one for for university "uni". Now i do not want, that the client token for the uni client can be used to download the privat library.

possible solutions:
1) add some ACL feature, which can be set in the webinterface where i can unlink clients (whitelist / blacklist for library access)
2) require the password again for each new library checkout (which would still mean a whitelist for each client on the server side)

**Comment by shoeper** [comment]
This can be achieved by adding another account and only sharing those libraries.
