### ISSUE TITLE
CRITICAL! seafhttp does not check user rights

### ISSUE THREAD

**Issue by JMLX42** [haiwen/seafile#623]
Hello,

whenever you click a file to "view" it in your browser, the file (eg. an image) is retrieved by the file view template using a link like this:

<pre>https://my.domain.com/seafhttp/files/{some-id}/{filename}</pre>

eg: https://cloud.minko.io/seafhttp/files/db4fef19/Desert.jpg

This link is completely public. Even if that file has never been publicly shared or is supposed to be private, seafhttp does not check for any form of credentials before serving the file.

I think this is a major security breach. Indeed, it means anyone can share links on files that are supposed to be password protected.

The fact that there is some unique ID does not change the fact the file is accessible from outside the platform. Possible fixes:
- generate a temporary link that can only be used once, and discarded when it has been served
- make sure seafile check that the user is a) properly logged in b) has the required rights before serving a file

I think this should be solved ASAP.

What do you think?

**Comment by JocelynDelalande** [comment]
With that evolution, how to address the feature that was previously allowed : the ability to  downloaded a file shared via share link without a browser (ex: wget/curl/whatever ?)

Before, it was possible copy-pasting the link from the web page and using it within the hour.

**Comment by shoeper** [comment]
Try appending ?dl=1 to the share url.

**Comment by JocelynDelalande** [comment]
@shoeper thanks a lot for your answer. 

I only have v0.4.1.x and v0.4.0.x right now to test, seems not to work with those, is that a new feature from 4.2 ?

**Comment by shoeper** [comment]
I catched it from this pr for seafile-client (which is from today or yesterday) https://github.com/haiwen/seafile-client/pull/602
Could be that server side part of this has not been published so far.

**Comment by JocelynDelalande** [comment]
@shoeper ok, thanks for your replies, I'll wait then :)
