### ISSUE TITLE
Write support in seafile-fuse

### ISSUE THREAD

**Issue by tcpie** [haiwen/seafile#645]
Currently seafile-fuse only provides a read-only filesystem. By supporting writing as well, Seafile can be used on NAS devices (samba / NFS link to the seafile-fuse mountpoint), as well as making it really easy to transfer data from the server seafile runs on, to the Seafile libraries. The latter makes it possible to do all kinds of interesting things (e.g. wget into seafile libraries, running cronjobs, ...)

**Comment by skidelo** [comment]
Agree! I also want to use plex with seafile. But webdav just doesn't cut it.

**Comment by Glaedr** [comment]
Can you please implement that?
It would be useful for many cases, for example you can then sync multiple SeaFile installations!

**Comment by killing** [comment]
It's too complicated so we don't have plan to do that right now.

2015-05-16 0:26 GMT+08:00 Glaedr <notifications@github.com>:

**Comment by desertcrystal** [comment]
I currently have a client that requires some seafile directories to be synced with Google Docs.  Mounting a writable seafile filesystem would be amazing..
I'm somewhat dreading the alternative of using WebDAV to mount the directories on the server, it's not efficient or always reliable, but it works.

I've seen your codebase so I understand why write access is so complicated and not of high priority.

**Comment by martinplattnr** [comment]
Can this be considered again? It would simplify many use cases...

**Comment by tbleiker** [comment]
Any new statements on this? This is actually the only thing which stops me from using seafile.

**Comment by clodi95** [comment]
pls i need read/write for viewing & managing my images in immich...
