### ISSUE TITLE
[Linux] Conflict with an existing library even if this one is deleted 

### ISSUE THREAD

**Issue by PPaques** [haiwen/seafile#649]
Hi,
Thank for your work on Seafile. I use it every day and this is my first bug in 6 months.

**EDIT : Sorry, it's the wrong repository, i'll look to seafile-client repository !**
###### The problem

When you delete a library before the upload (first commit) is done, you cannot create a new library in a subfolder.

If i try to create a new library from the client : 

> The path "/home/pierre/Projects/rails" conflicts with an existing library

If i create the library directly on the server and try to sync with an existing directory : 

> Failed to add download task:
> Worktree conflicts existing repo
###### Environment :
- Client :  seafile-client 3.0.4 on Archlinux
- Server : seafile-server 3.0.3 on a Debian Lenny server
###### How to reproduce this bug :
- Create a library with the client (In my case it was on a folder with 5Go) and stop the sync during the first upload (after  the file indexing)
- Delete this library directly on the server with the web interface
- Try to create a library on a sub-folder of the old deleted library.
###### Solution : Unknown yet

I've tried to restart the client but it isn't working. I'll look further soon.

Thanks
Pierre

**Comment by farbenfeuer** [comment]
As for me, i had the same problem on mac and renaming the folder did not work, but i quit seafile and killed the Seafile Sync finder process in the activity monitor and then it seemed to work. (in my case i even put the folder into the trash bin, but im guessing its not necessary tho).

Just in case someone had the same problem
