### ISSUE TITLE
Setting quota via the web API

### ISSUE THREAD

**Issue by promethe42** [haiwen/seafile#664]
Hello,

for Seafile to be integrated with 3rd party subscription systems, we need a way to set the quota for each user using the web API.

It is already possible to set the quota for each user in the admin console, but not using the web API. Can this be fixed please?

Regards,

**Comment by rabb1t** [comment]
Hello guys,

Is there any progress on this feature?

**Comment by freeplant** [comment]
See http://manual.seafile.com/develop/web_api.html#update-account
