### ISSUE TITLE
support two factor authentication

### ISSUE THREAD

**Issue by midi** [haiwen/seafile#671]
ni hao,

consider adding two factor authentication. 
you're missing from this list: http://twofactorauth.org/
github and hover do it quite well: https://help.hover.com/entries/26677644-How-to-Enable-two-step-signin-on-your-Hover-account 

google authenticator style support is very convenient, as you don't need to be limited by a cell phone number.

xiexie

**Comment by daMupfel** [comment]
+1

**Comment by legacycode** [comment]
+1 FIDO U2F

**Comment by softcat** [comment]
+1 FIDO U2F

**Comment by rene-s** [comment]
+1 FIDO U2F

**Comment by kingbobski** [comment]
+1 for FIDO U2F or Google Authentication.

**Comment by unixfox** [comment]
:+1:

**Comment by Ashaman-** [comment]
+1 for FIDO U2F or Google Authentication.

**Comment by benoit74** [comment]
Hi,
Can we know what you are developping ? Google Authenticator or FIDO U2F or anything else ?
Thanks a lot for considering this feature !

**Comment by freeplant** [comment]
It is  Google Authenticator

**Comment by benoit74** [comment]
Nice ! 👍
