### ISSUE TITLE
Invitation-based Registration

### ISSUE THREAD

**Issue by nichtsistwahr** [haiwen/seafile#673]
It would be great to have an invitation-only user registration mode, as opposed to open registrations plus the optional activation-by-global-admin or manual user management. It would prevent unauthorized user registration without the need for a centralized registration authority.

Use cases:
- A group wants to invite an additional, external member. Group Admins should be able to send out an invitation token that allows the user to register and automatically become a member of the group.
- A user wants to share her library with friends. She should be able to send invitations, access to her library should be automatically added after successfull user registration.

The permission to send out invitations should be configurable, either as a role and/or in seahub.conf, e.g. ENABLE_INVITATION_GROUP and ENABLE_INVITATION_USER.

**Comment by einot** [comment]
+1

**Comment by dakira** [comment]
:+1: This would be such a time saver.

**Comment by Lapin0t** [comment]
Any update? Did someone come up with some little hack?

**Comment by dakira** [comment]
@killing has this been implemented or is this feature declined or should we open a new issue if we want this?
