### ISSUE TITLE
Shared folders are shown in Share Admin -> Library not in Share Admin -> Folders

### ISSUE THREAD

**Issue by Koetermann** [haiwen/seafile#683]
System: Raspberry PI with Seafile Server 3.0.2

1.) I created a library called e.g. "Lib-A" in "My Home" -> "Personal".
2.) Then I shared this library to a group called "B-people".
3.) After that I created a folder/directory unter "Lib-A" named "Folder-B" and shared this to a user "Person-C".
4.) Now I took a look into "Share Admin" -> "Folders" and expected to find the folder "Folder-B" in there. But "Folders" is empty: "You have not shared any folder".
5.) But I found the "Folder-B" in "Share Admin" ->"Library" obviously as a library.

So the folder moved into a library? The overview in "Share Admin" ->"Library" is then overloaded because every shared folder is also there.

**Comment by shoeper** [comment]
Folders are shared as virtual libraries. This is by design.
