### ISSUE TITLE
conflict with existing repo

### ISSUE THREAD

**Issue by juerggloor** [haiwen/seafile#694]
I use seafile 3.03, several libraries, one of them synced with existing folder. For unknown reasen seafile "forgot" this library. Local folder still exists, but seafile does not know it anymore. Trying to re-add the folder throws error "conflict with existing repo". 

Is there a method to remove crashed libraries manually (manipulate seafile's library database)? I do not want do rename the original folder because other people in the company also use it.

**Comment by aminalid** [comment]
Thanks, this helped!
