### ISSUE TITLE
captcha not working

### ISSUE THREAD

**Issue by pfuhli** [haiwen/seafile#696]
The captcha is not working for me. I entered 8 times a wrong password and still no captcha is being displayed but my AD account gets locked.

I use 3.0.4 in the configuration with nginx and LDAP auth.

regards,

daniel

**Comment by rawbertp** [comment]
Has this been fixed yet? I added "LOGIN_ATTEMPT_LIMIT = 3" to the seahub_settings.py but no capture is shown. Server version 4.3.3

**Comment by shoeper** [comment]
The captcha works here. ... as it does on seacloud.cc.

Do you have adblock or something similiar (for me it blocks the share icon from seafile)? Otherwise there is something missing on your setup or some package versions are incompatible.

Is there something in the logs when the captcha should appear?

**Comment by pfuhli** [comment]
No change on our installation. Captcha is not working and we are on 4.3.2 on Linux

**Comment by rawbertp** [comment]
It doesn work with or without AdBlocker, I've tried several different browsers. I also do not see anything in the logs either. Not sure what could be missing - I followed the official setup instructions.

**Comment by simsasaile** [comment]
Also still not working here: Server 64bit for Linux Version 4.3.2, no Adblock

**Comment by shoeper** [comment]
And which "linux" do you have?

Here it is debian wheezy 64 bit, seafile running as user seafile

**Comment by simsasaile** [comment]
I use ubuntu 14.04, also seafile running as user seafile

**Comment by rawbertp** [comment]
Ubuntu 14.04.3 64bit
Linux version 3.16.0-46-generic (buildd@lgw01-57) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #62~14.04.1-Ubuntu SMP Tue Aug 11 16:27:16 UTC 2015
Seafile running as user "seafile"

**Comment by rawbertp** [comment]
Just tested in Nginx and it's not working either. Hence, I think, a web server config issue can be ruled out.

**Comment by shoeper** [comment]
Have you insed these packages?

python2.7 python-setuptools python-imaging python-mysqldb

**Comment by rawbertp** [comment]
I have no idea why but all of a sudden it started to work. Maybe it was related to my Apache config, after all.

**Comment by pfuhli** [comment]
yes, for my installation all these packages are installed but captcha is not working on Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-61-generic i686)

**Comment by shoeper** [comment]
@rawbertp can you find out what you've changed?

**Comment by rawbertp** [comment]
I'm afraid I can't... I tried it again with Apache which now works as well (and I haven't touched the Apache config at all).

The only changes I'm aware of are the following package installations I executed this morning:


```
cat /var/log/dpkg.log | grep "\ install\ "
2015-09-03 08:05:18 install libpcrecpp0:amd64 <none> 1:8.31-2ubuntu2.1
2015-09-03 08:05:18 install libpcre3-dev:amd64 <none> 1:8.31-2ubuntu2.1
2015-09-03 08:05:18 install zlib1g-dev:amd64 <none> 1:1.2.8.dfsg-1ubuntu1
2015-09-03 08:05:18 install libssl-dev:amd64 <none> 1.0.1f-1ubuntu2.15
2015-09-03 08:05:19 install libssl-doc:all <none> 1.0.1f-1ubuntu2.15
2015-09-03 08:16:43 install nginx-common:all 1.4.6-1ubuntu3.2 1.4.6-1ubuntu3.3
2015-09-03 08:16:43 install nginx-light:amd64 <none> 1.4.6-1ubuntu3.3
2015-09-03 08:26:16 install libxslt1.1:amd64 1.1.28-2build1 1.1.28-2build1
2015-09-03 08:26:16 install nginx-core:amd64 <none> 1.4.6-1ubuntu3.3
2015-09-03 08:26:16 install nginx:all <none> 1.4.6-1ubuntu3.3
2015-09-03 09:03:31 install nginx:all <none> 1.4.6-1ubuntu3.3
2015-09-03 09:04:20 install nginx-common:all <none> 1.4.6-1ubuntu3.3
2015-09-03 09:04:21 install nginx-core:amd64 <none> 1.4.6-1ubuntu3.3
2015-09-03 09:04:21 install nginx:all <none> 1.4.6-1ubuntu3.3
2015-09-03 09:05:54 install php5-cgi:amd64 <none> 5.5.9+dfsg-1ubuntu4.11
2015-09-03 09:06:03 install spawn-fcgi:amd64 <none> 1.6.3-1
2015-09-03 09:07:01 install php5-fpm:amd64 <none> 5.5.9+dfsg-1ubuntu4.11
```

Maybe one of these added a missing lib?

**Comment by simsasaile** [comment]
>Have you insed these packages?
>python2.7 python-setuptools python-imaging python-mysqldb

Yes, all of them are already installed.

**Comment by shoeper** [comment]
And what says the log? There should be a request like `GET /captcha/image/`sometokenhere/

**Comment by simsasaile** [comment]
No there is nothing with captcha in seahub.access.log or seahub.error.log. 

If I try to log in with wrong credentials I only get this in seahub.access.log:

`192.168.11.24 - - [03/Sep/2015:17:36:31 +0200] "POST /accounts/login/?next=/ HTTP/1.1" 200 12943 "https://mydomain.de/accounts/login/?next=/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/7.1.8 Safari/537.85.17"

But that's just the seafile startpage.

**Comment by shoeper** [comment]
Have you also checked the error log?

**Comment by simsasaile** [comment]
Yes, sorry forgot to mention: there no entry in seahub.error.log nor in error.log.

**Comment by shoeper** [comment]
Ok and when you inspect the source code of the returned page is there a line like this one?

```<img class="captcha" alt="captcha" src="/captcha/image/somecaptchatokenhere/">```

If not then there could be some bug in seahub not inserting a captcha under certain conditions.

**Comment by simsasaile** [comment]
No that line is not in the source code of the returned page (I tried to log in 3 times, (LOGIN_ATTEMPT_LIMIT = 2 in seahub_settings.py)). The only captcha related lines are:

```
<script type="text/javascript">
function setCaptchaInputWidth() {
    $('#id_captcha_1').css({'width': $('.input').outerWidth() - $('.captcha').width() - 10});
}
$(window).load(setCaptchaInputWidth);
$('.captcha').load(setCaptchaInputWidth);

$('#refresh-captcha').parent().css({'text-align':'right', 'margin':0});
$('#refresh-captcha').click(function() {
    $.ajax({
        url: '/captcha/refresh/',
        dataType:'json',
        cache:false,
        success: function(data) {
            $('.captcha').attr('src', data['image_url']); 
            $('#id_captcha_0').val(data['key']);
        },
        error: function() {
            $('.error').removeClass('hide').html("CAPTCHA-Aktualisierung fehlgeschlagen, bitte versuchen Sie es später noch einmal.");
        }
    });
    return false;
});
```

**Comment by shoeper** [comment]
Ok. Which browser are you using?

Have you deployed Seafile on root (example.com) or non-root domain (example.com/seafile)?

And could you temporarily set LOGIN_ATTEMPT_LIMIT back to the default value 3 and see if it works in that case (maybe there is something hardcoded)?

**Comment by simsasaile** [comment]
1) I tried Safari, Firefox and Chrome.
2) Under root (example.com)
3) Set back to 3, same result :(

**Comment by shoeper** [comment]
Ok 1 and 2 are totally fine.

Just to make sure: Have you tried to type in wrong credentials 4 or 5 times? Although default should be 3 I had to type in wrong data 4 time in a row.

**Comment by simsasaile** [comment]
Yes, even tried it ten times in despair :)

**Comment by pfuhli** [comment]
Just to mention it: they behaviour of my installation is so far the same as simsasaile is describing it.

**Comment by rawbertp** [comment]
Update: The whole Captcha logic appears to be completely random to me. The setting was at 3 and I had to enter the wrong password 4 times before the capture was finally shown. When I opened the site with a different browser it also showed the Captcha immediately (I tried with a fresh Chrome install which has never visited my Seafile installation before) - that doesn't make sense to me at all!

Then I successfully logged in with the other browser. I visited the page again with Chrome and the Captcha was shown after 1 (ONE) failed login attempt.

I believe this needs some rework.

**Comment by shoeper** [comment]
> When I opened the site with a different browser it also showed the captcha immediately

That's the feature. It is IP based (haven't checked it, but everything else doesn't make sense). So it's the wanted behaviour. And of course if you increase it and still have x failed logins for your IP in the logs the warning will be there after very few or even no more requests.

**Comment by rawbertp** [comment]
IP based makes sense but once having logged in successfully the counter should be reset.

**Comment by shoeper** [comment]
The counter resets after some time. I don't think it is important to also reset it on successful login (which benefit would it have?).

**Comment by shoeper** [comment]
Btw: That would also lead to new problems. One could attack 4 times, login with an account. Attack the other account 4 times again.
So to keep things simple the easiest is to not reset the counter unless some time elapsed.

**Comment by rawbertp** [comment]
Ok, that probably makes sense. Would be good to add this to the documentation somewhere. ;)

**Comment by simsasaile** [comment]
I switched to debian 8.1 same here, no captcha. The only thing I kept is the data-folder. Really strange.
@freeplant Any chance to reopen this issue? It's an security issue in my eye's, no protection against brute force.

**Comment by shoeper** [comment]
Is just the image missing (so you cannot login anymore). Or is there never a captcha AND you can still login?

**Comment by simsasaile** [comment]
No captcha and I can try to login as often as I like (so second option)

**Comment by shoeper** [comment]
Are you using nginx or apache?

**Comment by simsasaile** [comment]
nginx (1.6.2) with TLS (trusted cert from StartSSL)

**Comment by shoeper** [comment]
Make sure you have this in your nginx config (within server block):
`proxy_set_header X-Forwarded-For $remote_addr;`

And otherwise please try if one of these packages helps:
```
2015-09-03 08:05:18 install libpcrecpp0:amd64 <none> 1:8.31-2ubuntu2.1
2015-09-03 08:05:18 install libpcre3-dev:amd64 <none> 1:8.31-2ubuntu2.1
2015-09-03 08:05:18 install zlib1g-dev:amd64 <none> 1:1.2.8.dfsg-1ubuntu1
2015-09-03 08:05:18 install libssl-dev:amd64 <none> 1.0.1f-1ubuntu2.15
2015-09-03 08:26:16 install libxslt1.1:amd64 1.1.28-2build1 1.1.28-2build1
```
rawbertp reported earlier (in this thread) that it started to work without knowing how and posted amongst other packages those above.

**Comment by simsasaile** [comment]
Already had this line in my nginx config.

I installed all named packages and restarted nginx, seafile and seahub after that, but still no captcha.
