### ISSUE TITLE
Firefox upload problem

### ISSUE THREAD

**Issue by AdrianRibao** [haiwen/seafile#708]
When uploading a file from firefox and using https, the upload fails with this message:

    Error: [Exception... "<no message>" nsresult: "0x805e0006 (<unknown>)" location: "JS frame :: https://my.url/media/js/jq.min.js?t=1402119297 :: .send :: line 4" data: no]

Firefox blocks the upload of mixed content, because it tries to upload to http://my.url instead of https://my.url

It works ok with Chrome.

**Comment by nottinhill** [comment]
Do a

    $ sudo emacs /home/USER/PROJECTNAME/ccnet/ccnet.conf 

and change `SERVICE_URL = https://www.example.com`, then save, exit and do a:

    $ echo "FILE_SERVER_ROOT = 'https://YOURDOMAIN/seafhttp' >> /home/USER/PROJECTNAME/seahub_settings.py && cd /home/USER/PROJECTNAME/seafile-server-latest && ./seafile.sh stop && ./seahub.sh stop && ./seafile.sh start && ./seahub.sh start-fastcgi

Done.
