### ISSUE TITLE
Changing password on an encrypted library, doesn't stop clients from syncing the same library

### ISSUE THREAD

**Issue by acavas** [haiwen/seafile#758]
Hi,

There is no way to force users to change the password on their clients, because the client just notifies that the password has been changed and continues syncing. You can do an unshare if you want to exclude a user from share, but the strange part is if you share a library again it syncs it without asking for a password.

Question is whether it is possible in some later release to include an option on a server side if you want a client to sync an encrypted library after the password change or not?

**Comment by shoeper** [comment]
All tokens are deleted for some time now on password change.
