### ISSUE TITLE
Allow "Exclude ALL BUT" pattern in seafile-ignore.txt

### ISSUE THREAD

**Issue by matthid** [haiwen/seafile#762]
It should be possible to do something like:

```
/*
!file.txt
!dir/
dir/*
!dir/fileinner.txt
```

Which should ignore ALL files but 'file.txt' and 'dir/fileinner.txt'. See .gitignore help for details. As far as I can see this is currently not possible (http://seafile.com/en/help/ignore/).

**Comment by nowherecat** [comment]
I would be happy about this, as well

**Comment by OliverCi** [comment]
I would have similar needs in many places. Thinking this through, the optimal solution would be to allow alternating include/exclude cascades, e.g. as already supported by the rdiff-backup tool:

http://www.nongnu.org/rdiff-backup/examples.html#exclude

**Comment by dionysius** [comment]
For providing ideas: In Syncthing this can be done like:

* (or **) for everything, depends what you include in that wildcard sign.
! for negating a line (explicitly negating exclude -> allowed)

```
C:\Users\Dionysius
λ cat .stignore
!/Desktop
!/Documents
!/Music
!/Pictures
!/Videos
*
```

**Comment by jcrben** [comment]
It would be best if the pattern of `.gitignore` was followed as closely as possible.

**Comment by PerchunPak** [comment]
Why has it been closed? I still cannot use this inside `seafile-ignore`, while it works perfect in `.gitignore`
```gitignore
*
!foo.txt
```
