### ISSUE TITLE
recent versions of libevhtp do not work with fileserver

### ISSUE THREAD

**Issue by dbruenig** [haiwen/seafile#777]
I know the manual states that libevhtp version 1.1.6 or 1.1.7 has to be used with seafile, so I just want to give a hint to everyone compiling from source that more recent versions of libevhtp (1.2.9) do not work with the fileserver component yet and there is no error message that indicates this explicitly on a normal start. The fileserver log file states that the network socket is created but the process exists (normally) right after.
Running fileserver in foreground with -f and then trying to debug it with dbg showed in the backtrace that an exception appears in libevhtp.

**Comment by yshui** [comment]
Why are this closed? This and #571 

There need to be proper check for libevhtp at configuration time.

**Comment by yshui** [comment]
Looks like the problem is easy to fix, just removing one 

evhtp_request_pause() solves the problem for me.

**Comment by dbruenig** [comment]
When I saw that the issue was closed I assumed the problem was fixed. I did not inquire any further at the time I encountered the problem but I could have another look at it if this problem still occurs.

**Comment by yshui** [comment]
Build seaf-server with most recent libevhtp, and access to /files/ will hang,
