### ISSUE TITLE
Seafile Protocol: Are ports 8082, 10001 and 12001 safe and/or necessary?

### ISSUE THREAD

**Issue by fraber** [haiwen/seafile#791]
Hi Seafile team!

First of all congratulations to such a slick and high-potential product.

I've got some questions/issues concerning the architecture of Seafile: We have tried to install Seafile securely using HTTPS and our favorite reverse proxy "Pound". This is actually working for the Web client by using a separate domain for the port 8082 service. Also, we can HTTPS-protect both ports this way.

However, I'm kind of surprised to see that additional ports 10001 and 12001 are necessary for synchronization operations of the Windows client. May I ask: 

- Is this safe? From what I understand ports 10001 and 12001 run a HTTP type of protocol, but unencrypted. Is that right? Also, there are now a total of 4 (different) Web servers that all need to be maintained. Isn't that an unnecessary large "attack surface"?

- Is this a feature? It practically makes it impossible for a "road warrior" (somebody with a laptop outside the company firewall) to sync with a Windows Seafile client. This is our main use-case. So we are now considering to use OpenVPN in order to work around this issue.

- Is this really necessary? Wouldn't it be possible to hide these 4 additional ports somehow? Everybody bitches about the old FTP protocol because of it's extra ports. Couldn't you just build a kind of forwarding  feature in your Seahub component?

In some texts you mention performance as a reason for this architecture. Even though I understand that there may be slow components in the Seafile technology stack, I don't understand why you couldn't use Seahub to _redirect_ these queries to the appropriate component. A few socket operations should be sufficient for that with minor performance impact.

We are evaluating Seafile both for internal use as well as providing it to our SaaS customers (I'm the founder of http://www.project-open.com/).

Again, congratulations to your product!
Frank

**Comment by qnxor** [comment]
I just tried Seafile for the first time, v4.1.2 (server) and v4.1.6 (client) and I'm also very surprised to see it needs 4 different ports .. 8000, 8082, 10001, 12001 ... wasn't this plethora of ports going to be dropped in v4.0? What are the plans?

**Comment by freeplant** [comment]
10001, 12001 is no longer needed from v4.0 if you config Seafile behind Nginx/Apache. See more here: http://manual.seafile.com/overview/components.html

**Comment by qnxor** [comment]
Thanks for replying. I'm using the SQLite config with the default seahub: http://manual.seafile.com/deploy/using_sqlite.html
I wanted to avoid proxy and reverseproxy for speed (though I admit I haven't yet tested performance of seahub vs apache). I take it I can migrate from seahub to Apache without affecting the stored data.

**Comment by qnxor** [comment]
Ok, I just configured Seafile with Apache and HTTPS and the client still uses ports 10001 and 12001 ... clearly seen in tcpdump (MacOSX client v4.1.6)

I did enable sync via http in the client and I followed (this)[http://manual.seafile.com/deploy/deploy_with_apache.html] and (this)[http://manual.seafile.com/deploy/https_with_apache.html] for the server.

Any clues?

**Comment by freeplant** [comment]
You can check the seafile.log. If it failed to connect to https://domain/seafhttp/protocol-version, it will fall back to using port 10001 and 12001. In the next version v4.2, it will not fall back but will try to https://domain/seafhttp/protocol-version every few seconds.

**Comment by qnxor** [comment]
That log only says the following, and as you can see, it immediately starts listening on 12001 (I don't see any errors):
```
[04/25/2015 10:34:34 AM] processors/putfs-v2-proc.c(363): No fs objects to put. Done.
[04/25/2015 12:36:54 PM] ../common/mq-mgr.c(60): [mq client] mq cilent is started
[04/25/2015 12:36:54 PM] ../common/mq-mgr.c(106): [mq mgr] publish to hearbeat mq: seaf_server.heartbeat
[04/25/2015 12:36:54 PM] listen-mgr.c(115): listen on port 12001 for block tranfer
[04/25/2015 12:44:48 PM] ccnet_processor_handle_update: [Proc] Shutdown processor threaded-rpcserver-proc(-1009) for bad upda
te: 515 peer down
[04/25/2015 12:44:57 PM] ccnet_processor_handle_update: [Proc] Shutdown processor threaded-rpcserver-proc(-1042) for bad upda
te: 515 peer down
```

**Comment by qnxor** [comment]
[Deleted previous message] The client log indeed fails to see "https://domain/seafhttp/protocol-version" ... odd, because the apache logs do report that other /seafhttp requests are served just fiine (200)

Any ideas?

Permissions seem not to be an issue, even though apache runs as www-data, because the web works displays fine.

**Comment by qnxor** [comment]
Got it! The certificate was self-signed and the client's libcurl was refusing to get the /seafhttp/protocol-version url as it couldn't auth with the CA ... I check the "Do not verify server certificate in HTTPS syncing" in the client settings and it's now only using port 443.

Many thanks for the pointer.

**Comment by shoeper** [comment]
Of you use your own domain, you could get your certificate signed by StartSSL for free. Just make sure to also include chain certificates to make it work well.

**Comment by qnxor** [comment]
@shoeper I didn't know companies started to do that (is the browser coverage any good?). It requires verification of domain and email ownership so I'll leave as is for now -- I do have my own domain but it's privacy protected (for a reason).

**Comment by shoeper** [comment]
You just need the to setup the chain properly. Afaik their ca certificate is accpeted on all major platforms and browser.

You can get a certificate without having to identify yourself. You just receive a mail at postmaster@example.com (or ~4 others) and it'll be verified. No need of a personal mail, name or anything else. The certificate will just be domain validated (which is enough) and you won't have to include you name or anything else personal in the certificate.

**Comment by qnxor** [comment]
@shoeper I don't want to push this discussion further here as it's off-topic, but the free StartSSL cert does require you to provide all information about yourself, including name, address, phone number ... sure, you can lie about it and try to use disposable email addresses -- but they do reject most disposable email address domains (guerrilla, hmamail etc).

**Comment by shoeper** [comment]
@qnxor ok, sorry - didn't have that in mind anymore. Thanks for your hint.
