### ISSUE TITLE
Seafile with HTTPS Using Reverse Proxy "Pound" Instead of "Nginx"

### ISSUE THREAD

**Issue by fraber** [haiwen/seafile#792]
Hi!

I just wanted to let you that we managed to get Seafile working using www.apsis.ch/pound as a reverse proxy dealing with HTTPS decoding. Please find below our /etc/pound.cfg. Basically, Pound doesn't allow for URL rewriting, so we had to work around and create a second virtual domain "seafiledata" in addition to "seafile". Please note that this "seafiledata" entry needs to be _before_ the "seafile" entry.

<pre>
# *****************************************************
# /etc/pound.cfg
# *****************************************************

User            "nobody"
Group           "nobody"

ListenHTTPS
        Address 0.0.0.0
        Port    443
        xHTTP   2
        Cert    "/etc/pound/cert.pem"
End

Service
        HeadRequire "Host:.*seafiledata.*"
        BackEnd
                Address 192.168.1.5
                Port    8082
                TimeOut 600
        End
End

Service
        HeadRequire "Host:.*seafile.*"
        BackEnd
                Address 192.168.1.5
                Port    8000
                TimeOut 600
        End
End

</pre>

Cheers,
Frank

**Comment by aacebedo** [comment]
Hi 
I am exactly in this case. 
How do you configure your client it query seahub on seafile.domain and query seafile on seafiledata.domain ?

**Comment by shoeper** [comment]
Those are the configs for nginx and other steps required. You can use them as reference. http://manual.seafile.com/deploy/deploy_with_nginx.html
http://manual.seafile.com/deploy/https_with_nginx.html
