### ISSUE TITLE
[Feature Request] CardDAV and CalDAV 

### ISSUE THREAD

**Issue by Rehwanne** [haiwen/seafile#801]

**Comment by aristorias** [comment]
+1

**Comment by peterkahl** [comment]
+1

**Comment by jgonsior** [comment]
+1

**Comment by Madic-** [comment]
+1

**Comment by shoeper** [comment]
https://www.seafile-server.org/seafile-und-die-synchronisierung-von-caldav-und-carddav/ (german)

https://www.seafile-server.org/en/seafile-syncing-caldav-and-carddav/

**Comment by LeonardoGentile** [comment]
@shoeper links are dead

**Comment by lakano** [comment]
Hello @Vagdish !
Could you explain how to add Radicale on the server with Seafile please ?

As @LeonardoGentile said, the links of @shoeper are dead (so I don't known if there is already this feature included in seafile, but the docs doesn't speak about this).

Thanks

**Comment by Vagdish** [comment]
Heya :)

The hack I've done 3 years ago doesn't work anymore.
I'm currently using Radicale side by side with Seafile without any interactions between the two software.

Sorry I can't help you more :/

**Comment by lakano** [comment]
Ok! Thanks for your quick reply @Vagdish

**Comment by christophdb** [comment]
-1

Hi everybody,
I think that the integration of caldav and carddav is **not** a good idea. The Caldav and Carddav Protocol are difficult protocols and you have to deal with a lot of different client systems that all behave different. 
**Right now seafile is easy, stable, fast and reliable** - and that is what customers love about seafile. 

The Integration of caldav and carddav includes the risk that seafile looses this position in the future. And on the other hand there are so many caldav and carddav solutions out there that it should not be difficult to find a matching solution. 

There is sabre/dav or there is baikal. Both solutions are easy to implement and both are ready for productive usage. 

And now a little bit advertising for myself - also to show that I know what I am talking about. I started a tutorial series about sabre/dav (https://www.datamate.org/?s=sabredav) and if somebody wants to have **seafile + caldav/carddav** together under one single webpage than please try https://www.privatecloud.de. 

Best regards
Christoph Dyllick
(official german support partner of seafile Ltd.)
