### ISSUE TITLE
bug in download counter

### ISSUE THREAD

**Issue by simsasaile** [haiwen/seafile#816]
Hi,

in some circumstances the download counter does not count. 
For example if you share a video file (in my case with the extension .mp4) which is bigger as the online preview allows, the counter (counter ("Visits") under "Links - > Download Links") shows always zero, it doesn't matter how often you open the link.

Steps to reproduces:
Install seafile-server 3.1.3 for raspberry pi
Share a big .MP4-File
Visit the download counter

Greetings, simsasaile

**Comment by freeplant** [comment]
It is fixed already.
