### ISSUE TITLE
seafile-ignore.txt weird behavior

### ISSUE THREAD

**Issue by schleumer** [haiwen/seafile#826]
Hey! Thanks for the awesome software :heart: But i'm having some weird behavior from `seafile-ignore.txt`, some paths passes `seafile-ignore.txt` filter and are uploaded.

In my `seafile-ignore.txt` i got:
```
projects/scala/*/logs/
projects/scala/*/target/
projects/scala/*/project/project/
projects/scala/*/project/target/
```

But the path `projects/scala/cool-stuff/project/target/scala-2.10/sbt-0.13` is uploaded.

I'm on Windows 8.1 and this also happens on Ubuntu 14.04. Others paths are ok with filter.

The content of `projects/scala/cool-stuff/project/target/` is:
```
coffeescript
config-classes
jshint
less
node-modules
resolution-cache
scala-2.10
streams
webjars-plugin.cache
```

Also, [here is](http://pastebin.com/nCm8KpPU) the tree dump of `projects/scala/cool-stuff/project/target/`, tree dump [with files](http://pastebin.com/BYcurkA4)

Where `projects/scala/cool-stuff` is a Play Framework project root.

I don't know if it's a bug or if it's a misconfiguration of my part. I've followed all steps on [this link](http://seafile.com/en/help/ignore/). Thanks!

**Comment by killing** [comment]
This should have been fixed recently.
