### ISSUE TITLE
Sync Errors on Windows 2k12r2 Terminal Server

### ISSUE THREAD

**Issue by mitterhuemer** [haiwen/seafile#836]
We have interesting errors with seafile.
Problem one: 
If the Sync folder is on a shared smb folder in Windows (Like Z:/Seafile), then Seafile is Syncing files only on client start. When the client is running and i add some files or folders then seafile does not sync the files. But if i add something on the webpanel then seafile is syncing the new things i added on the webpanel. 
After a new Client restart Seafile is syncing also my local added files but only for one time.

Problem two :
If i delete all files in a Library Seafile gets an Sync error (!)  and so i have to unsync the Library and add the Library again to the Sync local Folder if i delete all files again then the error exists again.

Our Seafile Server:
Seafile 3.1.5 with Apache 2.2 and SSL Security on Debian 7 latest.
Latest Seafile Client is already installed!

**Comment by mitterhuemer** [comment]
Owncloud has solved the first problem ;-)

**Comment by shoeper** [comment]
It has been solved for Seafile, too. You can choose a sync intervall in the Client instead of auto change detection.
