### ISSUE TITLE
LDAP user didn't come up when I want to share a file to other user

### ISSUE THREAD

**Issue by FireROR** [haiwen/seafile#844]
1. Users are in the LDAP and they are able to login. For example, I have two user, abc@123.com, def@123.com
2. If I create a group and put abc@123.com into the group, it works and shows up in the group member.
3. Go to share a file, I can put abc@123.com and the system will find the user. If I put def@123.com, the system will not be able to find user and not allow me to add to the share list.

So, put it short, if ldap user are not in the group list, they are not showing in the user list when I want to share a file.

Regular users which created locally are ok.

Thanks

Alex

**Comment by freeplant** [comment]
I think the problem should already fixed, though I can't remember which version fixed it.
