### ISSUE TITLE
Add command to completely delete file from seafile

### ISSUE THREAD

**Issue by rominf** [haiwen/seafile#861]
I have a "University" library. My teacher gave me a set of virtual machines (50 GiB) for network classes and I accidentally put them into my library. Next day I saw that seafile client is stuck in uploading (0%) and my library grew up to 65 GiB. I've moved files out of the library, ran garbage collector (on the server side), cleared `blocks` directory — nothing helped me. Moreover, uploading those virtual machines blocks seafile from uploading other changes in my "University" library.

I know that I can change the history period to the 0 days and then run garbage collector, but I don't want to lose my history.

I would like to have a command (probably on a server side) that could remove specified files completely. directory.

PS: How can I fix this situation by now?

**Comment by deragon** [comment]
Why was this issue closed?

**Comment by dawansv** [comment]
It's a shame this issue was closed because this is a very good explanation of the problem and as of 2024 this is still needed. I understand it might be difficult to implement, but the issue should remain open until then.

**Comment by akostadinov** [comment]
Yeah, some files need to be deleted from history for compliance purposes. I wonder how pro users handle this.

Removing all files history to remove a single file doesn't sound like a good solution. Running online or offline GC doesn't change the question.
