### ISSUE TITLE
Fileserver.c using host 0.0.0.0 regardless of IP entered during setup.

### ISSUE THREAD

**Issue by rahlquist** [haiwen/seafile#867]
Steps to reproduce. Follow linux install instructions here http://manual.seafile.com/deploy/README.html

When you enter an IP for the server, it is ignored by Seafile and fileserver.c evidently. Log line shows;
[09/24/2014 03:33:24 PM] fileserver.c(337): host = 0.0.0.0, port = 8085

I had a conflict on port 8082. I had set Seafile to use ip 192.168.0.50 and another service was using 192.168.0.49:8082. Since Seafile did not use its given IP and grabbed 0.0.0.0 it tried to take port 8082 on all avalible IP's for that interface/MAC address which in my case is a total of 7 IP's. I cant imagine the is purposeful design. 

When the IP/port conflict happened I was still able to partly login to the server but landed on an error page. The mobile app connected as well but displayed "Error loading libraries". The mobile app even after deleting the account in the mobile app and trying to re-add still had this error. I had to go into android app management and delete the data and cache, then reconnect for it to pickup the now functional libraries.

**Comment by freeplant** [comment]
If you'd like to change the IP the fileserver listen, you can modify seafile.conf.
