### ISSUE TITLE
Client should check free disk space before indexing files for upload

### ISSUE THREAD

**Issue by seanmadsen** [haiwen/seafile#871]
I have noticed that when Seafile uploads new data from client to server it builds a temporary index nearly the size of the files to be uploaded. (This temporary index is cleared upon restarting the client.) This means that if I want to upload 10GB at once, I better have 10GB of free disk space for Seafile to use in building the index. Fixing this hungry-index behavior of Seafile would be nice, but in this GitHub issue I'm simply requesting that Seafile check the free disk space before indexing and issue a warning to the user explaining the disk space requirements. 

I can imagine it might be difficult to predict exactly how much space will be required for the index, but I'd recommend issuing the warning in any case where the free disk space is less than the total size of files to be uploaded. The warning would give the user the option of proceeding with the sync anyway, essentially crossing their fingers. The warning would read something like this (with buttons as choices at the bottom): 
> Warning: The current sync requires Seafile to upload a total of 9.8GB. Before uploading, Seafile must build a temporary index of these files, which may consume as much as 9.8GB and will be cleared upon restarting the client. Because you have only 6.2GB of free disk space, we recommend either: (1) freeing more disk space for this index to be built, or (2) moving files into your library in smaller increments and restarting the client after each increment in synchronized. 
> [[Cancel sync]]   [Attempt to sync anyway]

**Comment by deragon** [comment]
Mmm.  Running client 4.1.5 here.  During indexing, it still requires Gib of disk space and I am running out each time.  Not sure though if it is for uploading files or for any other reason.  Might be another bug.  Anybody can provide help to figure out what is going on?

**Comment by killing** [comment]
Is the library created before 3.0 version? Older libraries don't use new
syncing algorithms.

2015-06-06 22:21 GMT+08:00 Hans Deragon <notifications@github.com>:

**Comment by deragon** [comment]
I have different libraries created at different time.  Here are some questions I have:

1) How can I tell which library's indexing is causing the problem?  I guess I have to look at the main window and check it out when this is happening?

2) How can I tell the version of the library?

To get around the problem, yesterday I eliminated some huge files from the library.

**Comment by killing** [comment]
Unfortunately there is no easy way to tell right now.
If you use 4.2 client, in seafile.log, you can see a line "Download with
HTTP sync protocol version 1" for libraries created after 3.0 version.
Older libraries will show the line "repo version is 1, protocol version is
7".
BTW, you can open log folder by right clicking the icon in system
notification area.

2015-06-07 21:23 GMT+08:00 Hans Deragon <notifications@github.com>:
