### ISSUE TITLE
Notification when sharing in group

### ISSUE THREAD

**Issue by Radapompa** [haiwen/seafile#874]
Hi,
I would like to request a feature where you get a notification when you share libraries in a group. Today you can share a library with a group without no one noticing until they check manually either in the actual group or click on the group tab in the home window.

Steps to reproduce:
1. Share a library with a group
2. Log in as another user that is a member of that group
3. The user will not have any notification at the top right corner that there is a new share library.

Thanks

**Comment by freeplant** [comment]
It will be included in the next release.
