### ISSUE TITLE
How to delete server from client 

### ISSUE THREAD

**Issue by TI-Admin** [haiwen/seafile#877]
Server connection status in the lower left of a windows v3.1.7 client shows a red symbol and lists a good server and a server with a red cross symbol which is no longer active. How do I delete this inactive server ip from the client list ?

**Comment by GeorgeHahn** [comment]
I just ran into this issue on the Windows client.

Reproduction steps:
 - Log into a server
 - [external] Server changes address/IP
 - Change server address by clicking avatar and editing URL
 - Client never deletes the old URL
