### ISSUE TITLE
Share settings are not transferred when transferring ownership of a library

### ISSUE THREAD

**Issue by Corwitep** [haiwen/seafile#883]
If one transfers ownership of a library, its share settings are not transferred to the new owner
but instead stay with the old one.

Steps to reproduce:

1. Create a library 'test'.
2. Share 'test' with, for example, a group.
3. Give 'test' to another user.

Now the library is transferred as expected, but the share settings stay with the original owner don't appear in the list of shared libraries of the new user.

**Comment by fenderle** [comment]
confirmed for version 4.0.3

**Comment by d0teater** [comment]
confirmed on 4.0.3 as well. 

Got into mysql and moved the shares manually, seems to work: 
update SharedRepo set from_email = 'sharee@example.com' where repo_id = 'REPO-ID';

It would be great if transfer ownership moved the shares along with it.

**Comment by freeplant** [comment]
In our current implementation, after the transfer of a library, all the old shares are removed. This makes the "sharing state" of the library clean to avoid strange problems.
