### ISSUE TITLE
seahub behind apache with mod_proxy_fcgi does not work

### ISSUE THREAD

**Issue by liayn** [haiwen/seafile#884]
Hi!

I tried to set up seahub behind apache 2.4 with mod_proxy_fcgi instead of mod_fastcgi.

The only difference should be that the apache config does not need the FastCGIExternalServer line and the rewrite rule should look like this:

`RewriteRule ^(.*)$ fcgi://127.0.0.1:8000$1 [QSA,L,E=HTTP_AUTHORIZATION:%{HTTP:Authorization},P]`

_Notice_ the P as the last flag.

Obviously apache hands the request to seahub (http://example.com/), as seahub issues a Location header for a redirect to http://example.com/accounts/login. (_Notice_ the missing ending slash, which is present when doing it with mod_fastcgi)
The browser's request to http://example.com/accounts/login triggers the same redirect in an endless loop (until the browser stops with an redirection error).

Does anybody have a hint for me, what the correct configuration is, such that I can use mod_proxy_fcgi?

I'm not a python/django programmer, so I've no clue how/where to debug the thing, to find out the subtle difference between these fcgi approaches.

Thanks for your help.

**Comment by tomchiverton** [comment]
This needs to go in the main docs. mod_fastcgi isn't available for Apache 2.4 in Fedora, for instance, and this method is much more straight forward.

**Comment by liayn** [comment]
I can confirm that this approach works like a charm now. Add it to the docs!

**Comment by tomchiverton** [comment]
Are the docs editable ?

**Comment by freeplant** [comment]
You can fork and edit https://github.com/haiwen/seafile-docs

**Comment by zangetsu05** [comment]
Hi all, i have a problem to deploy seafile under Apache/mod_proxy_fcgi.
Your example work fine if you deploy seafile as the root domain, es: https://www.somesite.com/
but it doesn't  work if you want to deploy it as a non-root domain.
Most of the errors are like page not find or work uri in response, so i think that the key is
the ProxyPass related ti the fcgi module.
Can you help me to set the right configuration to work with this kind of url: https://www.somesite.com/seafile ?

**Comment by tomchiverton** [comment]
@zangetsu05 are you saying you want to use a simple ProxyPass based method with a non-domain root Seafle install ? Adjust the Alias, Location and left hand side of the ProxyPass to match. Probably.

**Comment by zangetsu05** [comment]
Resolved in #1186 thanks!
