### ISSUE TITLE
Feature Request: Made snapshot accessible as (virtual) library

### ISSUE THREAD

**Issue by kepi** [haiwen/seafile#891]
## Feature Request

Add another possibility to snapshot library view next to View and Restore. It can be either "Restore to Library" which will simply create clone of library up to specific commit.

Another way would be "Show snapshot as virtual library" which will somehow magicaly :) show specific commit (snapshot) in client libraries.

## Background

For second time we found out that some time ago (i.e. month ago) "someone" had deleted some folder. Since that there are dozen or hundred of changes in our library.

It seams that now there is only one possibility with history - restore snapshot. In such case snapshot is restored and all changes are gone. I have to sync restored library, copy content somewhere else and restore snapshot previous to restore... It may not be big deal for single user but when more then 10 people share this library they sync and sync again during this operation.

Thanks for considering

**Comment by freeplant** [comment]
In v4.0.5, the owner of a library can restore any single file/directory from the snapshot.

**Comment by simsasaile** [comment]
Really nice thanks for that!

**Comment by kepi** [comment]
Thanks, great news! I can see how to restore file now but can you please give me hint how to restore specific directory?
