### ISSUE TITLE
Issue with very high resolution

### ISSUE THREAD

**Issue by samerafach** [haiwen/seafile#895]
I use a very high resolution on my computer, 3200x1800, and apparently Seafile isn't compatible with that. Most of the text in options doesn't show up and there's an obvious alignment problem in everything. Check the attached image.
![optionswindow](https://cloud.githubusercontent.com/assets/8694366/4722005/c3806c74-593c-11e4-9f4c-4fb9725f54ea.jpg)

**Comment by freeplant** [comment]
Please give the new version a try: https://bitbucket.org/haiwen/seafile/downloads/seafile-4.1.0-en.msi

**Comment by samerafach** [comment]
Tried it. Same problem still there. Be aware that this may be a problem with Qt.

**Comment by Chilledheart** [comment]
Hi samerafach:
   Currently, we still have some work to deal with the hidpi situation under windows. But you can set your environment variable for workaround, by setting `QT_DEVICE_PIXEL_RATIO` to `2.0` (or something else to match your DPI settings).

Get your dpi ratio, e.g. it's 200% (2.0):
![screen shot 2015-02-01 at 16 27 53](https://cloud.githubusercontent.com/assets/2123461/5991533/4c83ea58-aa2f-11e4-987f-b0be8c789f9a.png)

Add the env variable `QT_DEVICE_PIXEL_RATIO` to  the dpi e.g. `2.0`:
![screen shot 2015-02-01 at 16 26 06](https://cloud.githubusercontent.com/assets/2123461/5991528/0f02da72-aa2f-11e4-96e7-ba06304bef88.png)

What it looks like after setting the qt dpi env variable: 
![screen shot 2015-02-01 at 16 25 51](https://cloud.githubusercontent.com/assets/2123461/5991527/0e41d200-aa2f-11e4-938f-ccc40c9ab275.png)

**Comment by samerafach** [comment]
Thank you. Setting the environment variable QT_DEVICE_PIXEL_RATIO to 2.0 solved the problem.

**Comment by freeplant** [comment]
@Chilledheart :+1:

**Comment by samerafach** [comment]
@Chilledheart I got a new computer with the same resolution. I tried the same soution with Seafile 4.07 to it but it didn't work. Any other ideas? Does the solution only work with Seafile 4.1.0?

**Comment by Chilledheart** [comment]
@samerafach Unfortunately, yes. It is only supported from seafile-client 4.1.0 which is bundled with qt 5.4 instead of old qt4.

**Comment by samerafach** [comment]
Let me put one more important note: If this doesn't work, try to set the environment variable to only 2, and not 2.0. In some languages the decimal point is a comma, which could be a problem. In another system of mine, I had to set this to 2 rather than 2.0 for it to work.

**Comment by Chilledheart** [comment]
Thank you, @samerafach.

**Comment by Chilledheart** [comment]
Actually, the hidpi issue for linux is solved as well if you are using GNOME 3 or any modern linux desktop. You might need to execute this line below in your terminal and login again before starting seafile client:

``echo "export QT_DEVICE_PIXEL_RATIO=2" >> ~/.bashrc``

**Comment by Burtan** [comment]
Hi, 
I'm using debian testing with seafile client 4.2.3 downloaded from http://seafile.com/en/download/. The GUI does not scale although I have configured 
echo "export QT_DEVICE_PIXEL_RATIO=2" >> ~/.bashrc
Is the binary package not build against Qt 5.4 or do I most likely have a different problem?

**Comment by samerafach** [comment]
@Burtan You should add that export command in /etc/profile.

sudo echo "export QT_DEVICE_PIXEL_RATIO=2">>/etc/profile

Try this and restart your computer.

**Comment by Burtan** [comment]
@samerafach 
Thanks for the tip, but it didn't change the GUI scaling :(

**Comment by samerafach** [comment]
@Burtan That's weird. This works for me for Seafile and QtCreator on Debian Wheezy and Jessie... 

Let's recheck. Please open the file 

/etc/profile

with your favourite editor (like nano) with the command

sudo nano /etc/profile

and make sure that the line

export QT_DEVICE_PIXEL_RATIO=2

Is there at the end (with no quotation marks). It's also important to restart your computer after you do change that (probably log off is enough but we have nothing to lose)

Solution #2:

If you're super-desparate and can't get this to work eventually, you could try creating a desktop launcher (shortcut in Windows terms) that will run the command for you. An example is provided here:

http://superuser.com/questions/676307/adding-a-complicated-launcher-to-the-open-with-list-in-ubuntu

So you can make the launcher command for Seafile

screen -d -m bash -c "export QT_DEVICE_PIXEL_RATIO=2;seafile-applet"

Of course assuming that seafile-applet program is in the global directory. This will create an internal shell and define that environment variable in it. For this solution, of course install screen if you don't have it, with

sudo apt-get install screen

**Comment by Burtan** [comment]
@samerafach 
I've already checked that file and the command is correctly inserted. I will try your second solution and will report the results. But I don't have access to my 4k screen the next two weeks.

**Comment by Burtan** [comment]
I tried your second solution:
screen -d -m bash -c "export QT_DEVICE_PIXEL_RATIO=2;seafile-applet"
Unfortunately, the seafile client is still not scaled.

**Comment by samerafach** [comment]
@Burtan You probably have a Qt which is earlier than 5.4. Sorry for the late response, haven't noticed your message until now.

**Comment by Burtan** [comment]
Hi,
I have tested both your solutions now on Debian Testing with qt5-default being 5.4.2, but it still doesn't work. Anymore suggestions?

**Comment by MAFLO321** [comment]
Hi,
I have installed Seafile client 5.0.1 on my Surface Pro 4 and the dpi bug is still there.
I have temporarily solved it with `QT_DEVICE_PIXEL_RATIO=2`.
`QT_DEVICE_PIXEL_RATIO=2.0` didn't work.

**Comment by freeplant** [comment]
It will be solved when Qt 5.6 is released in the first quarter of 2016.

**Comment by MichaelAquilina** [comment]
Hi, any news on this? I compiled seafile-applet against qt 5 but this had a few graphical glitches and was wondering when an official release will be made?

**Comment by MAFLO321** [comment]
is now solved in Seafile client 5.1 on my Surface Pro 4

**Comment by MichaelAquilina** [comment]
It seems like I was using the older 5.0. Will try it out at home and let you know how it goes.

**Comment by shoeper** [comment]
Although it seems not to be perfect all the time this is more a QT issue which is getting continously worked on.

On a Surface Pro 3 having a relatively high resolution it works well since 5.1.
