### ISSUE TITLE
Web API Create Directory problem.

### ISSUE THREAD

**Issue by wtrucci** [haiwen/seafile#899]
Hi, I'm using Web API to check and create directory but there is problem.

For example, I have this structure:

Foo/Bar/Tool

and I need to create Foo/Bar/Tool/Ball/Top

so I check if folders before Top exist and if they exist I create Top or if Ball not exist I need to create Ball and then Top. Some times (I don't know why) Seafile on directory request don't answer or answer that dir doesn't exist so my program creare all folder tree and here is the problem!

If I create by Web API a folder already present I see something like this: Foo (1)/Bar (1)/Tool (1) all empty so I need to delete it. Is it normal? Do you have any tip about this?

In the doc manual I see a note:
Newly created directory will be renamed if the name is duplicated.

But this not works as expected, if dir exist Seafile add (1) at the end.
I'm using Seafile server linux generic 64 bit 3.1.6 and 3.1.7 
Thanks

Walter

**Comment by shoeper** [comment]
> But this not works as expected, if dir exist Seafile add (1) at the end.

It is the expected behaviour.
