### ISSUE TITLE
django_session table grows when users don't logout

### ISSUE THREAD

**Issue by metawave** [haiwen/seafile#905]
when users don't logout with the logout link on the site, the session data of this user will never been deleted in the django_session table, see documentation regarding this behaviour: https://docs.djangoproject.com/en/dev/topics/http/sessions/#clearing-the-session-store

since the session is quite small it's not a big problem, but may slowdown things a tiny bit when the userbase is growing.

**Comment by shoeper** [comment]
http://manual.seafile.com/maintain/clean_database.html

**Comment by metawave** [comment]
> Since version 5.0, we offered command to clear expired session records in seahub database.

might confuse people, because you speak in past tense about it. Is this feature still available in the latest version?

**Comment by shoeper** [comment]
it is available.
