### ISSUE TITLE
[mac] Improvement: add seafile version information at the "default" location

### ISSUE THREAD

**Issue by delgurth** [haiwen/seafile#917]
I was just reporting an Issue about seafile 3.1.8. When I was creating that I was also wondering where I could see the version of the app installed (besides looking in the logfile). 

On OS X applications this information is normally added to the main menu item (here seafile-applet) and then the first item. But for seafile it's "hidden" in the status menu and also there not on a "logical" mac location. 

Since in the status menu it's normally also put in the main menu and not beneath the help (which is the default microsoft windows location).

**Comment by lins05** [comment]
Done in https://github.com/haiwen/seafile-client/commit/a037375e98327a18959c7b6a30671c1807b91c93
