### ISSUE TITLE
Add a tool to check database consistency

### ISSUE THREAD

**Issue by rominf** [haiwen/seafile#921]
As I have described in https://github.com/haiwen/seafile/issues/728 I cannot manage users. Nobody replied me and I guess that only I encounter this problem. That means that probably this is a local issue.

I guess that this can be caused by bad migration between databases versions. I'm using PostgreSQL (which is the best DBMS IMHO) which is not officially supported. Because of that I needed to write migration scripts on my own. I've worked with PostgreSQL and SQLite, so I've converted SQLite script into PostgreSQL. But I'm not a seafile developer, so there are chances that I did something wrong.

Is there way to check database consistency?

**Comment by shoeper** [comment]
Database issues are really rare. It is recommended to create a backup before upgrading.
