### ISSUE TITLE
Cant' add new admin user with ldap authentication enabled

### ISSUE THREAD

**Issue by 1resu** [haiwen/seafile#922]
Hi,
we use the latest seafile version 3.1.7 installed at a Debian stable system. Authentification against our ldap server is enabled.
I added a new (mysql) database user and tried to add this user as an administrator. It fails with the following error message: Using LDAP now, can not add admin.

The only way to give a user in the database admin rights is to set "is_staff" to "1" in table "EmailUser" ccnet-db.

Furthermore the same field ("is_staff") exists in table "GroupUser" but makes no difference if set to "1" - ldap accounts can't become admins this way.

**Comment by freeplant** [comment]
This problem will be solved in the next release.

**Comment by 1resu** [comment]
Fixed in 4.0.5 - Thanks!
