### ISSUE TITLE
Feature Request: Client version log and/or minimal version limit

### ISSUE THREAD

**Issue by kepi** [haiwen/seafile#927]
It would be great to be able to see users client version in seafile admin interface. It will help to identify users who forgot to upgrade their clients.

There could be also option in seafile server config to set minimal allowed version of client.

It will probably not be so important in future but now there are many fixes in every Seafile release and some of them are really curical in our environment. Manual checking of all user computers is really time consuming and complicated and in same cases also impossible.

Thanks for considering.

**Comment by caniwi** [comment]
I would like to see this feature as well.  We have numerous clients and many problems are solved by having up to date client versions.  Having central visibility of this would reduce trouble shooting time.

**Comment by shoeper** [comment]
Parts of this are on the roadmap for 5.1

> Show the list of all desktop clients (version and syncing status) (pro)

see https://seacloud.cc/group/3/wiki/seafile-roadmap
