### ISSUE TITLE
Can't contact LDAP server. - Professional Version

### ISSUE THREAD

**Issue by typingm0nk** [haiwen/seafile#940]
Hi,

on our professional (3.1.13) setup, we can't start seafile with ldap. 
It responds with following error message:

```
[11/27/14 13:51:40] user-mgr.c(540): ldap_search failed: Can't contact LDAP server.
[11/27/14 13:51:40] user-mgr.c(99): Failed to get user number from LDAP.
failed to run "ccnet-server -t"
```

The config is the same with our community setup. There it works.
On our professional server ldap_search works, the workaround for the cert path for ubuntu is active and our ldap server is reachable.

**Comment by typingm0nk** [comment]
Our LDAP supports paged result. It runs with version 2 and 3. PR is part of version 3.
We tried setting the version in ccnet.conf, but it seems to have no effect.
With seafile-pro-server-4.0.2 the error message changed slightly.
```
[01/13/15 14:07:55] user-mgr.c(562): ldap_search failed: Can't contact LDAP server.
[01/13/15 14:07:55] user-mgr.c(99): Failed to get user number from LDAP.
failed to run "ccnet-server -t"
```
other than that, no changes.

**Comment by killing** [comment]
Have you tried non-SSL connection to LDAP server? Are you using the same machine for the community version and pro version?

**Comment by typingm0nk** [comment]
non-SSL: same error.
On that machine we are using primarily the pro versions, but i installed a community version once to test the upgrade to pro process.

**Comment by killing** [comment]
In the pro version, we use paged result extension to enhance user listing speed. I suspect this error is related to the server's support or setting for paged result extension.
You can try the same ldapsearch command with the additional option "-E pr=100" to check whether the server supports paged result correctly.
Right now we're going to add an config option to ccnet to disable using paged result extension.

**Comment by typingm0nk** [comment]
ldapsearch with pr works correctly.

**Comment by freeplant** [comment]
Can you test the new v4.0.3 pro version? We disabled the "page result" and tried to make compatible with community edition.

**Comment by typingm0nk** [comment]
Did the tests with v4.0.3 pro.

our regular LDAP, no SSL

```
** Message: seafile-controller.c(1067): loading seafdav config from /data/seedatei/conf/seafdav.conf

[01/15/15 15:36:54] user-mgr.c(139): The number of users exceeds limit, max 50, current 68217
failed to run "ccnet-server -t"
```

I am not sure where the "max 50" comes from.

with SSL the same old:
```
** Message: seafile-controller.c(1067): loading seafdav config from /data/seedatei/conf/seafdav.conf

[01/15/15 16:16:07] user-mgr.c(673): ldap_search failed: Can't contact LDAP server.
[01/15/15 16:16:07] user-mgr.c(99): Failed to get user number from LDAP.
failed to run "ccnet-server -t"
```

The small testbranch with SSL produces the same error.

Without SSL it starts, but we can't actually login without it.

We tested the following ldapsearchs, they are working.

```
ldapsearch -ZZ -x -h <our ldap server> -b 'o=<our organisation>,c=de'
ldapsearch -x -H ldaps://<our ldap server> -b 'o=<our organisation>,c=de'
ldapsearch -x -H ldaps://<our ldap server> -b 'o=<our organisation>,c=de' -E pr=10
```

**Comment by freeplant** [comment]
Hi, now the LDAP can work with out SSL as the message shown: "The number of users exceeds limit, max 50, current 68217". The license I send to you is for at most 50 users. But your LDAP contains 68217 records. So the seafile server can't start.

**Comment by replug** [comment]
Hi, we are using a license which reads MaxUsers = "100".

**Comment by typingm0nk** [comment]
Actually on that server was indeed the old (and a few months expired) license with 50 users, with the new one it reads 100. Which is arguably still a lot less than 68217.

We assumed something like that, therefore the much smaller testbranch (20 users). 
So we are still at the problem with the obligatory SSL.

The community edition works fine with SSL and our setup.

**Comment by freeplant** [comment]
This should be caused by the LDAP library that packaged with Seafile pro. It is different from the library in the community edition. We'll see how to solve it tomorrow.

**Comment by killing** [comment]
@typingm0nk @replug You can try to move liblber-2.4.so.2  libldap-2.4.so.2  libsasl2.so.2 from seafile-server-latest/seafile/lib to somewhere else. Then Seafile will use the ldap library from the system. This may solve the issue. I've tried it on Ubuntu 14.04. Seafile can start without a problem. Our pro edition package is compiled on Centos 6.2. I found the version of libldap on Ubuntu 12.04, 14.04 and Centos 6 are all version 2.4.

**Comment by egroeper** [comment]
@killing With that workaround it works fine. Thanks!
We will try it with paging enabled (should be disabled by default in 4.0.3).

**Comment by killing** [comment]
We haven't updated the documentation. You should add USE_PAGED_RESULT = true to LDAP configuration in ccnet.conf.

**Comment by replug** [comment]
@killing ...okay - thanks!

**Comment by typingm0nk** [comment]
@killing @freeplant  thanks.

**Comment by typingm0nk** [comment]
As of pro 4.11 the workaround is still needed. The issue with LDAP libraries consists.

**Comment by killing** [comment]
@typingm0nk Hi, the reason we still keep the LDAP client library in the package is that: some Pro users don't use LDAP, there system may not have LDAP library installed. But our binary depends on LDAP library to run. So we can't remove the library from the package.

**Comment by shoeper** [comment]
You could try moving LDAP into a plugin/module/library which is only loaded when LDAP is enabled via config. Then Seafile wouldn't need libraries without using LDAP and people wanting to use LDAP could install the libraries via e.g. apt-get or yum.

**Comment by killing** [comment]
This is a good idea, we'll consider it.

2015-04-29 23:33 GMT+08:00 Sven <notifications@github.com>:
