### ISSUE TITLE
Use of ports 10001 and 12001

### ISSUE THREAD

**Issue by sehfellowes** [haiwen/seafile#943]
I am running Seafile as an https service on port 443. It seems to need to use ports 10001 and 12001 for its synchronisation to clients etc. 
Unfortunately, these ports are closed on a lot of firewalls at the places I visit including my office.
Are there plans to make all exchanges work just using port 443 (or 80) as is the case with other products such as Dropbox or ownCloud?

**Comment by shoeper** [comment]
Port 10001 and 12001 aren't used anymore.
