### ISSUE TITLE
Upload to new (empty) Directory via API

### ISSUE THREAD

**Issue by Sicci** [haiwen/seafile#951]
Hello,

if a user creates a new directory and I list all directory entries via WebAPI the directory has no ID.
How am I supposed to upload a file to such a directory if i have no ID? The WebAPI upload has only a repo-id parameter and no path parameter.

Is there any possibility to initialize the empty directory with an ID? Does the upload support a directory path but it's not documented?

I'm thankful for any advice. Thanks.

**Comment by shoeper** [comment]
http://manual.seafile.com/develop/web_api.html
