### ISSUE TITLE
Seafile Android App can't connect to private Seafile Server behind a Reverse Proxy

### ISSUE THREAD

**Issue by alvaroaleman** [haiwen/seafile#958]
The seafile android app apparently has some issues conneting to a seafile server thats behind a reverse proxy, it always returns a 'Network Error'.

Connecting and up-/downloading works fine on both the Desktop Client and the WebUI.

**Comment by shoeper** [comment]
Tested it on Nexus 7 with multiple keyboards. But did not have success.

On S4 you've 'just' to delete space after characters like '?'. To do this type ? and then some letter.  Press two times back after that and retype the letter after the question mark

**Comment by dbruenig** [comment]
Another possible cause for a network error might be a not supported ssl cipher by seadroid. A list of supported ciphers can be found in
src/com/seafile/seadroid2/SSLSeafileSocketFactory.java

Even if your reverse proxy uses a secure cipher a connection to it will result in a network error if your cipher is not a member of the list of supported ciphers.

**Comment by alvaroaleman** [comment]
The issue was caused by special characters on Android keyboard and the Seafile app not supporting TLS above 1.0. The latter was changed ~two weeks ago.

**Comment by huegelc** [comment]
This issue seems to persists.I get a loop wheen trying to connect to my private server.used that android asop keybord for password input
