### ISSUE TITLE
Syncing is stuck at 66%, receiving two block-tx-client.c errors

### ISSUE THREAD

**Issue by manorius** [haiwen/seafile#959]
Hi,

I'm running Client 3.1.11 and server 3.1.6 on a Rpi
For the past month syncing is stuck at 66% and I keep on receiving the following errors over and over again:
[12/08/14 11:17:35] block-tx-client.c(757): Data connection is closed by the server.
[12/08/14 11:17:35] block-tx-client.c(989): Restarting block tx client.

Any ideas what might be the problem?

**Comment by lins05** [comment]
Can you upgrade to the latest seafile server & client and see if the problem is still there?

**Comment by manorius** [comment]
Same. I have been having a lot of issues lately with libraries not syncing etc..

**Comment by freeplant** [comment]
Can you post the full seafile.log from the server and the client?

**Comment by manorius** [comment]
This one is from the client. I will be sending the server one later. https://drive.google.com/file/d/0B4UTRiy0r1IzX1h0d3NvQ1JvcEU/view?usp=sharing

**Comment by killing** [comment]
The error should be caused by the server. Can you find errors in server
seafile.log?

2015-02-17 11:43 GMT+08:00 Manolis <notifications@github.com>:
