### ISSUE TITLE
Manage user quota (API)

### ISSUE THREAD

**Issue by shubhank008** [haiwen/seafile#976]
Aside from changing a user's storage quota from admin panel (editing user), is there a way to do the same using the webAPI or any other way ?
For example, I want to assign different user quote during sign up itself (custom sign up page using webAPI to create new user) based on their referral or want to integrate increasing user quota in some other integrations

Kind of looking for how dropbox does it

**Comment by shoeper** [comment]
http://manual.seafile.com/develop/web_api.html#update-account
