### ISSUE TITLE
Prolicense questions

### ISSUE THREAD

**Issue by shubhank008** [haiwen/seafile#977]
I sent this in a mail a few days ago (2-3) but didn't got a reply so asking here

I am interested in SeaFile and have been following your progress since last 2 years (when it wasn't as advanced as it is now, I was using OwnCloud).
I am really interested in SeaFile as my platform for a new project we are planning and have a few questions for its ProLicense, which I assume we will need in due time.
 
I have the following queries:-
 
1. If we start from community edition, can we upgrade to pro-license and features without hiccups ? Do you provide assistance in upgrade if needed, specially multi-server setup and clustering ?
2. Do you provide support/help after initial 12 months, charged at any extra rate, hourly or fixed ? Do you provide any service like custom feature, customizing frontend, or simply assistance related to server setup, migration, clustering, etc. ?
3. I am a bit confused on pricing model, its one time payment based on number of users right ? The users are ones who are registered in system and not the ones who can actually download a public file ? As such, if we start with 5 licensed users, then upgrade to 20 next month, 100 after that and so on, do we get discounted prices on our next batch of license order ?
4. Do community edition offer any kind of multi-server, clustering or load balancing feature at all ?
5. Can SeaFile be used in a dropbox model, with 10GB free for a registered user and 100GB for a paid user. Aka a usergroup config model.
6. Whats the potential to use Seafile for a semi-filehost (mega/mediafire) rather then a full cloud service ?
7. Can we disable some features like versioning, etc. which can potentially increase disk space ?
8. How advanced is SeaFile's file search, or rather search system ? Does it support "word" based filters for files uploadable, etc. basically to filter out adult or copyrighted content or delete them
9. Do SeaFile support video or audio streaming/playback, like if you upload a video file, open it on a mobile/web browser, user can play it rather then complete download
10. How hard/easy is it to customize or theme SeaFile frontend
11. Do you have any advice for using SeaFile for an actual production environment, aiming to be the next dropbox or mega ?
12. Can you provide more details about the Service Provider license, its cost and details about multi-server tenancy
 
Regards

**Comment by shoeper** [comment]
I close this because it is a bug tracker and the ticket is outdated. Questions relating the pro license can always be directly asked via email.
