### ISSUE TITLE
Creating a new folder creates also "untitled folder". Also renaming folders keeps old "ghost" folder as well

### ISSUE THREAD

**Issue by priyadarshan** [haiwen/seafile#980]
Client: seafile 4.0.4 (OS X 10.9.5)
Server: seafile 4.0.1 (Ubuntu server 14.04)

On a freshly created library, sometimes, creating a new folder on the client will sync that folder plus a "untitled folder". See screenshot, after creating new folder named "a":
![screen shot 2014-12-19 at 20 41 51](https://cloud.githubusercontent.com/assets/1652143/5510145/802219f8-87bf-11e4-8d1b-e4894c465dde.png)

Of course, after a while, that extraneous "untitled folder" gets sync back to the client, although it was never created in the first place.

Perhaps related to that: if one renames a folder on the client, sometimes (but not always), the original folder is left there, and a new one is created with the new name.

Example, if one renames the folder from the situation the image above, from `a` to `a1`, it will rename the original folder, but leave a "ghost" folder behind, with the old name, as this state on the cloud shows:

![screen shot 2014-12-19 at 20 44 37](https://cloud.githubusercontent.com/assets/1652143/5510210/fa0ee73c-87bf-11e4-8892-b56a32a510e0.png)

**Comment by freeplant** [comment]
This should be fixed in v4.0.5

**Comment by priyadarshan** [comment]
Yes, I can confirm that behaviour is now gone. Thank you so much.
