### ISSUE TITLE
How to change desktop client language?

### ISSUE THREAD

**Issue by galvanopus** [haiwen/seafile#982]
Hi!

I am using English OS with Russian regional settings. Desktop client 4.0.3 interface is shown partially in Russian, partially in English. How can I switch to English interface?

And here are some thoughts about selecting language for interface:
* By default program language should conform user OS interface language
  * It is worth remembering that OS language can differ from user language, For example, Windows 8.1 EN allows language packs installation and setting different languages for the different users. OS language can be EN, user1 language can be RU, user2 language can be CN.
  * Regional settings **should not be used** to determine program interface language.
  * If no translation is available, default program language should be used.
* User should be able to override automatically chosen interface language.

**Comment by lins05** [comment]
This feature was added in https://github.com/haiwen/seafile-client/commit/4444ebeb65a85921b1ae7741a5b0b15da1e36483.

**Comment by galvanopus** [comment]
Thank you!
