### ISSUE TITLE
Feature request: Full postgres support

### ISSUE THREAD

**Issue by ikcalB** [haiwen/seafile#983]
As the db-interface library supports postgres dbs, I really wish a full integration!

I expect
- install / update scripts
- postgres specific config-options: which port & socket to connect to (to choose the server instance)

NOTE:
Currently, initialising seahub-db `python manage.py syncdb` breaks the seafile server (no pid file, keeps restarting every 10sec)

EDIT:
this only happens, if I do not use an alternate db (like sqlite) to start seafile for the first time.
(there seems to happen some magic here)

**Comment by brot** [comment]
I would also love to see postgres support

**Comment by e-minguez** [comment]
+1

**Comment by jirutka** [comment]
+1

**Comment by tuxayo** [comment]
+1
Is there someone that managed to deploy 4.3 with postgres? It seems that each version can break it (which is to be expected)

**Comment by ikcalB** [comment]
DISLAIMER: on your own risk. make backups first!!

@tuxayo I managed to do so (multiplexed terminal helps):
- stop everything
- translate & execut every sql instruction manually on your psql database (BE CAREFUL, NO TYPOS)
- change update-script not to check for sql
- change update script not to execute the database update
- start everything

**Comment by tuxayo** [comment]
Thanks for instructions, I'll give feedback if I get to try!

**Comment by tuxayo** [comment]
Thanks for instructions, I'll give feedback if I get to try!

**Comment by tuxayo** [comment]
@ikcalB Your instructions are for upgrade right? I'm looking for deploying a new instance.

**Comment by mauriciobaeza** [comment]
@tuxayo Look here: http://mauriciobaeza.net/posts/install-seafile-with-postgresql-in-centos/

**Comment by ikcalB** [comment]
Have been using seafile since version 2.something with postgresql

I am familiar with that DB, use multiple clusters on my server, and like it a whole lot better than anything comparable.

Please add full support! :)
