### ISSUE TITLE
Feature request: Public folder with upload & download

### ISSUE THREAD

**Issue by manfredmann** [haiwen/seafile#987]
Hello. Now to upload into a public folder, and download public folders - separate links. I would like to see it as it is implemented in owncloud: a public link to the folder that you can both upload and download files.

Sorry for my bad english :-(

**Comment by NNois** [comment]
Hi,
This would be so convenient, having to send 2 links to client isn't really perfect....

**Comment by shoeper** [comment]
It has also been proposed in the forum. See https://forum.seafile-server.org/t/upload-download-share/2815?u=shoeper

**Comment by fhdummy** [comment]
Any news on this?

**Comment by freeplant** [comment]
We don't have a plan to support this feature. It may make Seafile be used as a public FTP server. Not the way we want.

**Comment by MarcusRiemer** [comment]
Hmm, thats a pity! I do see where you are coming from, but at least in my personal space this kind of "public ftp" feature would have been great. Currently I send out two links after every bigger family gathering (asking for photos) and the two links almost always cause confusion:

* Some people are irritated that they can't see what they have uploaded. They then upload their stuff multiple times.
* Sometimes people confuse the two links and either tell me "I don't see anything" or "I can't upload anything".

**Comment by marcusmysc** [comment]
Please consider to add this feature, it would really help how someone works with external users.

**Comment by bitfasching** [comment]
Any update on this issue? Besides keeping files in sync across devices, creating shared folders for exchanging files with friends and familiy is my primary use case for a self-hosted cloud service. I don't want to replace Seafile, but I struggle to understand why this feature would not be added.

**Comment by freeplant** [comment]
The feature will be added in version 8.0.

**Comment by hubertguillemain** [comment]
Hello, I see that the feature has been marked as Finished in the roadmap, but I cant see the implementation in 8.0.4 CE.
Is there some setting to enable the feature?
