### ISSUE TITLE
seaf-cli list command: Show Hostname/Account

### ISSUE THREAD

**Issue by epe** [haiwen/seafile#988]
seaf-cli list should show which library belongs to which account or Host. 
Since seafile clients has the great feature to connect to several servers with different accounts it should be possible to keep things appart. 

(also relevant for the applet: For each account a folder prefix could be set to keep folders appart
~/wrk/libraryname
~/wrk/otherlibrary
~/seacloud/lib
or:
~/sea.lib/
~/wrk.libraryname/
)

**Comment by freeplant** [comment]
We don't have a plan to implement this feature. Closing it.
