### ISSUE TITLE
Feature request: Manage clients from server/seahub

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile#991]
It would be a nice feature if the administrator could roll out automatic updates via seafile server. 
When there is a new update the administrator would be able to enable automatic install for the newest version in the admin interface. The client would then automatically get newest client version from private seafile server and upgrade the client in the background.

Although I have a very small (private use only) setup I think this feature would be very helpful. Of course espacially for those deploying seafile for hundrets or thousands of people. This could greatly reduce time used for support when there are new bugs (like the one where removed folders reappeared in the past). 

And the local delivery (of new client version) could save up bandwidth and speedup the rollout in all those cases where seafile servers are in house.

**Comment by caniwi** [comment]
An administrator being able to see what version of client a user has installed would be an asset.

**Comment by shoeper** [comment]
https://github.com/haiwen/seafile/pull/1516
