### ISSUE TITLE
Changes on server are only propagated to the client after a delay

### ISSUE THREAD

**Issue by a3nm** [haiwen/seafile#992]
Hi,

I am trying to use Seafile open source edition on my own server. I successfully set up the 4.0.1 server and tried both the 4.0.5 client and the 4.0.4 CLI client on the server itself and on another machine. I managed to synchronize a library successfully between both clients, however I have a problem with the speed at which changes on one client are picked up by the other client.

When a change is performed on a client, it is sent by the server after 1-2 seconds only (e.g., when creating a new file, it appears on the Web interface after 1-2 seconds). However, other clients are slow to pick up this change: it takes roughly 20-30 seconds for clients to notice it and synchronize.

Is there a way to ensure that changes on the server are picked up immediately by clients?

Thanks in advance!

**Comment by milosivanovic** [comment]
Seafile should definitely not rely on polling for this. I would flag this as a scalability issue. Have WebSockets been considered, allowing server-side pushes to be performed on an as-needed basis?

**Comment by shoeper** [comment]
it is definetly no scalability issue. There are almost no resource costs in practise (with seafiles implementition).

**Comment by milosivanovic** [comment]
There may be "almost no resource costs", but they are still wasteful, and becoming especially prominent when handling thousands of clients, and of course can be avoided with a push-based system.

**Comment by a3nm** [comment]
In addition to scalability, I would also say that this is a usability issue. Having to wait 30 seconds for changes to propagate can be a problem in many situations: it can give a false impression that synchronization is not running because you don't see changes propagated straight away; you could change files on a machine and disconnect a second one just afterwards without knowing that the changes were not propagated yet; you could edit a file on one machine and then on another (e.g., via SSH) before the changes propagated.

**Comment by a3nm** [comment]
Hi, would it be possible to let me know if you are closing because this issue has been addressed, or because you have decided not to address it? Many thanks!

**Comment by killing** [comment]
Hi,

We have no plan to address this issue as it adds complexity to the deployment.
