### ISSUE TITLE
Feature Request: 'Upload only' Library without syncing

### ISSUE THREAD

**Issue by geist1** [haiwen/seafile#994]
It would be great to have the option to only upload stuff into the cloud, without having to sync an entyre library. Thoughts on that? 
Thanks!

**Comment by awikatchikaen** [comment]
I would like such features ! 
I want to centralized automatically all photos from my differents devices but don't want to download them on each one.

**Comment by shoeper** [comment]
You can already use the cloud file explorer or use WebDAV to access the data.
