### ISSUE TITLE
ldaps does not work since upgrade to 4.0.2

### ISSUE THREAD

**Issue by Corwitep** [haiwen/seafile#995]
Connecting to a ldap server via ssl worked fine with 3.1, but stopped working since upgrading to 4.0.2. If I connect to ldap without ssl everything works fine.

The ccnet.log shows:

[12/29/14 10:41:58] user-mgr.c(225): ldap_bind failed: Can't contact LDAP server.

when any user attempts to login. I can connect to the (openldap) server via ldapsearch.

The relevant lines from ccnet.conf:

[LDAP]
# LDAP URL for the host, ldap://, ldaps:// and ldapi:// are supported
# To use TLS, you should configure the LDAP server to listen on LDAPS
# port and specify ldaps:// here.
# stopped working since 4.0
#HOST = ldaps://ldap.zfn.uni-bremen.de
HOST = ldap://ldap.zfn.uni-bremen.de
# base DN from where all the users can be reached.
BASE = ou=people,dc=zfn,dc=uni-bremen,dc=de
# user DN to bind to. If not set, will use anonymous login.
USER_DN = cn=XXXXXXXX,dc=zfn,dc=uni-bremen,dc=de
# Password for the user DN
PASSWORD = XXXXXXXXXXXX
# The attribute to be used as user login id.
# By default it's the 'mail' attribute.
# Note that only email can be used as user name for now.
LOGIN_ATTR = mail

**Comment by t4nec0** [comment]
same issue with version 4.0.6 (Linux, CentOS). Tried every kind of syntax (ldaps://, ldapi://, no protocol but just the server address (+port) and USE_SSL=true... no way.
The LDAP server is a 389 (Fedora Directory Server...) configured with SSL on port 636.
Non-ssl connections work, SSL ones do not. Same error given as above.

**Comment by nidheesh-eglobeits** [comment]
I am also having the same issue and my seafile configured on Ubuntu 14.04.2 LTS machine and LDAP is using for authenticating my window server user in seafile. I have tried all changes mentioned above and I am in a situation same as 't4nec0'. Advance thanks for any help.
