### ISSUE TITLE
seafile user without password.

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile#999]
Just had a look at phpmyadmin and found out there is a user `seafile@%` without password.
See image from pma (second one is the "normal" user but what's the first one?):
![0763](https://cloud.githubusercontent.com/assets/5340585/5579448/51d607e2-903b-11e4-8570-3b7956ca3a1f.png)

It's no risk in my case but is this really wanted?

**Comment by shoeper** [comment]
Furthermore db rights are granted to seafile user without password. Deleting the user results in a not working seafile installation - until I grant those rights on the seafile user with password.

**Comment by lins05** [comment]
@Sven: I'll check that soon.

**Comment by shoeper** [comment]
Maybe there is a wrong grant command leading to a new user with given rights (not sure if it is possible but could be)

**Comment by lins05** [comment]
yeah, I have fixed that
https://github.com/haiwen/seafile/commit/146c46bc3d373180538b833d6fa4d0ec8d863418.
I guess we'll release a new version soon with this fixed.

**Comment by shoeper** [comment]
You should also make and upgrade script to remove the user without password and grant permissions to the one with password.

**Comment by lins05** [comment]
Agreed.

**Comment by freeplant** [comment]
People will run the upgrade script only in a minor or major upgrade. We will add the fix to "upgrade_4.0_4.1.sh"

**Comment by shoeper** [comment]
Ok.
Am 07.01.2015 03:22 schrieb "Daniel Pan" <notifications@github.com>:
